### ISSUE TITLE
Deck stats deleted when deck 'updated' without change

### ISSUE THREAD

**Issue by ckirkman** [HearthSim/Hearthstone-Deck-Tracker#1001]
This may be intentional, but seemed like a unintended consequence to me: After editing a deck, and deciding to not make a change (and not save as a new version of the deck), the deck stats [win/loss rate] was overwritten when on the detailed stats view, but merged when looking at the summary from the general deck selection view.

(e.g., a deck has a win rate of 1-0; after editing, making zero changes, then playing one more game and losing it, the detailed stats pages says the win rate is 0-1, while the main deck listing says 1-1.)

**Comment by culinko** [comment]
Does this still happen?
