### ISSUE TITLE
Problem in the Stats page

### ISSUE THREAD

**Issue by lord666** [HearthSim/Hearthstone-Deck-Tracker#1084]
I noticed the meter Quests don't show the proper result 1/3 - ( 90/100 ), while Hearsthone told me I already win 100 Gold. Apparently it's just some games aren't save : 55 but recorded 53 games

**Comment by Elitesparkle** [comment]
@Epix37, I suggest you to add two buttons somewhere in the options to manually add and remove a victory to the counter respectively.

**Comment by culinko** [comment]
Does this issue still happen?
