### ISSUE TITLE
Problem with stats

### ISSUE THREAD

**Issue by jenius20** [HearthSim/Hearthstone-Deck-Tracker#1096]
On hearthstats my stats for versions other than the most recent one are not being reccorded when i synch. Also on the win/loss for each deck, it shows the most recent deck versions winloss even if i change the version. (for example if i have dragon v2 with a win loss of 3/2 and i change it to version 1 the win loss will stay at 3/2 even if it is not that)

**Comment by jenius20** [comment]
bump

**Comment by Elitesparkle** [comment]
I think this issue could be related to "Stats displays active deck, not selected deck" (#1073).

**Comment by Epix37** [comment]
The second part of this will be fixed with the next update and we will look into the first.

**Comment by culinko** [comment]
Is this still an issue?

**Comment by judge2020** [comment]
HearthStats is no longer supported by HDT, a new synchronization system is planned for HSReplay.
