### ISSUE TITLE
Gold Progress not showing in Windowed Mode

### ISSUE THREAD

**Issue by ghost** [HearthSim/Hearthstone-Deck-Tracker#1135]
When lowering the region of window mode to a certain resolution, the gold progress doesn't show anymore.

this is the resolution it works
![image](https://cloud.githubusercontent.com/assets/235410/14912240/87849574-0e03-11e6-97b4-dc9605b3957b.png)

changing a few pixels "hides" it
![image](https://cloud.githubusercontent.com/assets/235410/14912249/929898d4-0e03-11e6-90f6-d00b1686d333.png)

**Comment by riQQ** [comment]
Can't reproduce.
