### ISSUE TITLE
Unable to import or record stats, decks not syncing properly

### ISSUE THREAD

**Issue by Jumiric** [HearthSim/Hearthstone-Deck-Tracker#1145]
HearthStats is now using this program and it has been a huge hassle. I cannot get the program to record wins/losses, but it strangely records each turn of a match. I was unable to find a way to upload my previous stats into the program. I am also having a problem syncing. Each time I sync from HearthStats, I see a different mix of active and past decks, and never see all of my currently active decks.

**Comment by Jumiric** [comment]
Other posts mention some kind of log file. Here's mine.

http://pastebin.com/M8rdekV4

**Comment by eunito** [comment]
I'm having the exact same problem...
Anyone knows how to fix it?

**Comment by culinko** [comment]
Are you still experiencing this issue?

**Comment by eunito** [comment]
Stoped using it due to that issue :(

No dia 15/04/2016, às 19:46, Peter Culak <notifications@github.com> escreveu:

**Comment by judge2020** [comment]
HearthStats is no longer supported by HDT, a new synchronization system is planned for HSReplay.
