### ISSUE TITLE
Importing deck from JudgeHype

### ISSUE THREAD

**Issue by FitzcairnHS** [HearthSim/Hearthstone-Deck-Tracker#1187]
Hi there, i know it will only interest french players but it would be nice if you could add JudgeHype to the supported website liste. 

There are many decks and they use to post several news decks and some are very interesting to test and it suck to have do it manually :p

Exemple of deck : http://hearthstone.judgehype.com/deck/14891/

**Comment by andburn** [comment]
That site is supported by [NetDeck](https://netdeck.n4ru.it/), you could import to deck tracker that way.
