### ISSUE TITLE
Hearthstats: new Arena run isn't created by syncing

### ISSUE THREAD

**Issue by riQQ** [HearthSim/Hearthstone-Deck-Tracker#1189]
If the first game of a new Arena run can't be submitted, e.g. because HearthStats isn't available, the Arena game can't be synced later.

**Comment by Epix37** [comment]
Yea, the whole arena syncing is still a bit of a temporary solution. Should be fixed some time in the future.

**Comment by riQQ** [comment]
Closing, as HearthStats isn't supported anymore.
