### ISSUE TITLE
Joust Suggestion

### ISSUE THREAD

**Issue by tgcp** [HearthSim/Hearthstone-Deck-Tracker#1198]
With the new Joust mechanic I think it would be useful if the deck tracking overlay included an "average cost of minions in deck" counter. This would be similar to the existing counts of number of cards in hand and number of cards in deck.

**Comment by Epix37** [comment]
Good idea.

Might have to look into what gives a better value here, average or median.

**Comment by samarthj** [comment]
Median is always better in such situations. More indicative of a card of a mana cost being drawn. Avg gets too skewed by outliers.

**Comment by stdscatchemall** [comment]
Another way is to just have an on-screen Mana Curve that fills in as you play

**Comment by culinko** [comment]
Same as #425.
