### ISSUE TITLE
sync issues; refreshes not happening automatically

### ISSUE THREAD

**Issue by kenshinvt** [HearthSim/Hearthstone-Deck-Tracker#1273]
Hello, I use HDT on multiple devices frequently (two tablets + one desktop).  Love the sync feature. However, I've noticed that, without fail, when I sync the deck list does not update (win / loss totals).  Sometimes performing a "full sync" will cause the main list to update, but the only really guaranteed way to have it update is to perform a log out and log in via the hearthstats menu.

I've used HDT for a very long time and I don't remember this being an issue for me with earlier releases regarding the sync feature.

In case it matters, I do leave the desktop HDT app running and open 24x7.  I just update it via the sync menu option when I am about to play on the desktop.

**Comment by Epix37** [comment]
HearthStats was/is having some server issues, might be related to that? Should be fixed soon.

**Comment by kenshinvt** [comment]
So that is another issue entirely--I guess my post had some unfortunate coincidental timing.  I did notice a lot of sync problems yesterday.

This, however, is an ongoing issue that I have seen for the past few months.  For whatever reason, the deck list won't update upon sync.  Extra steps have to be taken like logging in/out or doing a full sync (full sync often doesn't work though--just the login/logout).  Do you ever get any testing in where you have one HDT client sitting open while you then go and use another instance of the program on a different computer?  Then update the primary one?  That use case might replicate this.

**Comment by Epix37** [comment]
Okay, I see. I have not tested anything multi-instance in a very long time. Gonna check it out!

**Comment by judge2020** [comment]
HearthStats is no longer supported by HDT, a new synchronization system is planned for HSReplay.
