### ISSUE TITLE
HearthStats split up my Arena runs into two

### ISSUE THREAD

**Issue by garyking** [HearthSim/Hearthstone-Deck-Tracker#1286]
I have an Arena run, where I went 5-3. On HearthStats, it is split up into two Arena runs of 5-2 and 0-1. What's the best way to fix this? I tried forcing a Full Sync but that didn't fix it. 

If I hit Reset on HearthStats and Sync again, then will that fix the problem? I don't want to Reset my HearthStats account and then have to start from scratch.

Thanks in advance!

**Comment by Epix37** [comment]
Could be related to the server issues that are going on :/.

The easiest should be to just delete the 0-1 run on hearthstats and manually add one to the other one.

**Comment by GaryKing** [comment]
These are Arena runs that were uploaded a few weeks ago so I don't think they are related to the recent problems.

Okay I will do them manually if there aren't too many of them.

Are there potential problems with resetting on the Hearth Stats website and then force syncing in HDT though?

**Comment by judge2020** [comment]
HearthStats is no longer supported by HDT, a new synchronization system is planned for HSReplay.
