### ISSUE TITLE
game record do not work every time

### ISSUE THREAD

**Issue by chucklu** [HearthSim/Hearthstone-Deck-Tracker#1315]
I checked the C:\Users\Administrator\AppData\Roaming\HearthstoneDeckTracker\Games.
I find there are 8248 files in this directory.
I wonder what' the max number of game record could be record in this directory

**Comment by MechaLynx** [comment]
Is there any pattern to the kinds of games not recorded?

There is no definite maximum and certainly no maximum defined by the number of files or filesystem restrictions. Make sure that you have the types of games you want recorded selected from `options` -> `tracker` -> `stats`.

**Comment by chucklu** [comment]
I double checked I have selected the right type of games to record.
I just played the casual mode
I 'll check the record tonight,again

**Comment by chucklu** [comment]
I am using a deck of paladin ,I played  Paladin for a while.
Then I used Hunter ,do not want to exchange deck.
HDT worked well
I played Hunter for a while too.
Then I used Priest,however ,HDT will not record the priest deck's game

**Comment by Epix37** [comment]
Could you post the log after that happened?
https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by eunito** [comment]
Same happening here... No stats being recorded...

**Comment by culinko** [comment]
Is this still an issue?

**Comment by chucklu** [comment]
@culinko not sure,I will check this ,when i am free

**Comment by culinko** [comment]
Any news?

**Comment by chucklu** [comment]
@culinko sorry,I have forgot about this issue.

**Comment by eunito** [comment]
Hi! My last games get recorded! :)

No dia 22/06/2016, às 06:49, Peter Culak <notifications@github.com> escreveu:

**Comment by chucklu** [comment]
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/453278/hdt_log.txt)
17:27:51|Debug|XmlManager.Save >> Saving file: C:\Users\Administrator\AppData\Roaming\HearthstoneDeckTracker\DeckStats.xml
17:27:51|Debug|XmlManager.Save >> File saved: C:\Users\Administrator\AppData\Roaming\HearthstoneDeckTracker\DeckStats.xml

I have post the log ,in the log ,it seemed the game stats was saved
but i can not find the record on the hdt

**Comment by azeier** [comment]
Are you maybe filtering for ranked games?

**Comment by chucklu** [comment]
@azeier  no,just filter time for this week ,the other s are all

**Comment by chucklu** [comment]
I am debuging this problem,
Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\GameEventHandler.cs
	if(_assignedDeck == null)
				{
					Log.Info("Saving DefaultDeckStats");
					DefaultDeckStats.Save();
				}
				else
				{
					_assignedDeck.StatsUpdated();
					Log.Info("Saving DeckStats");
					DeckStatsList.Save();
				}

**Comment by azeier** [comment]
Check in `DeckStats.xml` if the game exists - searching for the opponent name should be the easiest way to find it.

**Comment by chucklu** [comment]
I have ended another game,the opponent name is  古怪之裤子
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/453282/hdt_log.txt)

I can find only one record in the DeckStats.xml,not sure if the time is 
correct.
<Game>
          <GameId>addc1101-0dc0-4990-8982-675c61107bdc</GameId>
          <PlayerHero>Mage</PlayerHero>
          <OpponentHero>Warrior</OpponentHero>
          <Coin>true</Coin>
          <GameMode>Casual</GameMode>
          <Result>Loss</Result>
          <Turns>0</Turns>
          <StartTime>2016-07-16T23:37:13.27238+08:00</StartTime>
          <EndTime>2016-07-16T23:37:29.4403048+08:00</EndTime>
          <PlayerName>子非鱼</PlayerName>
          <OpponentName>古怪之裤子</OpponentName>
          <ReplayFile>子非鱼(Mage) vs 古怪之裤子(Warrior) 2337-160716.hdtreplay</ReplayFile>
          <WasConceded>true</WasConceded>
          <PlayerCardbackId>43</PlayerCardbackId>
          <FriendlyPlayerId>2</FriendlyPlayerId>
          <ScenarioId>2</ScenarioId>
          <Region>ASIA</Region>
          <Format>Standard</Format>
          <DeckId>00000000-0000-0000-0000-000000000000</DeckId>
          <DeckName>none</DeckName>
          <PlayerCards>
            <Card Id="CS2_023" Count="1" />
            <Card Id="AT_004" Count="1" />
            <Card Id="NEW1_012" Count="1" />
            <Card Id="OG_207" Count="1" />
          </PlayerCards>
        </Game>

I wonder if I can clear the content of the DeckStats.xml

**Comment by chucklu** [comment]
I am sorry ,forget it ,I find record in a wrong file  DefaultDeckStats.xml

**Comment by chucklu** [comment]
sorry,acutually,I  can not find the record.
子非鱼(Mage)   can not match my hero class
I am using paladin

**Comment by azeier** [comment]
there's a bunch of these messages in the log:
`17:24:31|Warning|DeckManager.DetectCurrentDeck >> Cards not found in deck: Kvaldir Raider (AT_119), C'Thun (OG_280), Beckoner of Evil (OG_281), Disciple of C'Thun (OG_162), Scaled Nightmare (OG_271), Sunwalker (EX1_032)
`

Are you maybe using the wrong deck and have auto selection disabled?

**Comment by chucklu** [comment]
tried another game,and  i can find the game record in DeckStats.xml
```xml
<Game>
          <GameId>28f9ee8b-dacd-4c62-81b6-f0cc0686b2d5</GameId>
          <PlayerHero>Paladin</PlayerHero>
          <OpponentHero>Warlock</OpponentHero>
          <Coin>false</Coin>
          <GameMode>Casual</GameMode>
          <Result>Loss</Result>
          <Turns>1</Turns>
          <StartTime>2016-09-03T17:48:59.3412851+08:00</StartTime>
          <EndTime>2016-09-03T17:49:57.2205956+08:00</EndTime>
          <PlayerName>死亡之翼</PlayerName>
          <OpponentName>迅捷之潜行者</OpponentName>
          <ReplayFile>死亡之翼(Paladin) vs 迅捷之潜行者(Warlock) 1751-030916.hdtreplay</ReplayFile>
          <WasConceded>true</WasConceded>
          <PlayerCardbackId>43</PlayerCardbackId>
          <FriendlyPlayerId>2</FriendlyPlayerId>
          <ScenarioId>2</ScenarioId>
          <ServerInfo>
            <Address>114.113.218.171</Address>
            <AuroraPassword>JPhaME</AuroraPassword>
            <ClientHandle>3480223</ClientHandle>
            <GameHandle>61866354</GameHandle>
            <Mission>2</Mission>
            <Port>3724</Port>
            <Resumable>true</Resumable>
            <SpectatorMode>false</SpectatorMode>
            <SpectatorPassword>OKLeHj</SpectatorPassword>
            <Version>261402</Version>
          </ServerInfo>
          <Region>CHINA</Region>
          <Format>Standard</Format>
          <DeckId>91e62398-0e92-48da-b012-9646d7af19f1</DeckId>
          <DeckName>614982784圣骑士</DeckName>
          <PlayerDeckVersion>
            <Build>0</Build>
            <Major>1</Major>
            <Minor>0</Minor>
            <Revision>0</Revision>
          </PlayerDeckVersion>
          <PlayerCards>
            <Card Id="AT_114" Count="1" />
            <Card Id="OG_131" Count="1" />
            <Card Id="OG_152" Count="1" />
            <Card Id="OG_286" Count="1" />
            <Card Id="EX1_371" Count="2" Unconfirmed="2" />
            <Card Id="EX1_360" Count="1" Unconfirmed="1" />
            <Card Id="EX1_004" Count="1" Unconfirmed="1" />
            <Card Id="CS2_172" Count="1" Unconfirmed="1" />
            <Card Id="EX1_066" Count="1" Unconfirmed="1" />
            <Card Id="EX1_362" Count="2" Unconfirmed="2" />
            <Card Id="EX1_349" Count="1" Unconfirmed="1" />
            <Card Id="CS2_122" Count="1" Unconfirmed="1" />
            <Card Id="EX1_382" Count="1" Unconfirmed="1" />
            <Card Id="EX1_597" Count="1" Unconfirmed="1" />
            <Card Id="EX1_170" Count="1" Unconfirmed="1" />
            <Card Id="EX1_102" Count="1" Unconfirmed="1" />
            <Card Id="EX1_019" Count="1" Unconfirmed="1" />
            <Card Id="CS2_125" Count="1" Unconfirmed="1" />
            <Card Id="CS2_097" Count="2" Unconfirmed="2" />
            <Card Id="CS2_093" Count="2" Unconfirmed="2" />
            <Card Id="CS2_182" Count="1" Unconfirmed="1" />
            <Card Id="CS2_179" Count="2" Unconfirmed="2" />
            <Card Id="EX1_046" Count="1" Unconfirmed="1" />
            <Card Id="CS2_221" Count="1" Unconfirmed="1" />
            <Card Id="EX1_564" Count="1" Unconfirmed="1" />
            <Card Id="DS1_055" Count="1" Unconfirmed="1" />
            <Card Id="EX1_067" Count="1" Unconfirmed="1" />
            <Card Id="CS2_088" Count="1" Unconfirmed="1" />
            <Card Id="CS2_222" Count="1" Unconfirmed="1" />
          </PlayerCards>
```

**Comment by chucklu** [comment]
@azeier  i have modified the deck in the game ,and lazy to update in hdt
I just want to record the loss and win 

so,yes,I am using the wrong deck and disbaled the auto detection

**Comment by chucklu** [comment]
since we can find the record in the DeckStats.xml

maybe,the error is under Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Windows\OverlayWindow.Update.cs

found this 
17:58:30|Info|OverlayWindow.Update >> Refreshed overlay topmost status

**Comment by chucklu** [comment]
I have closed the hdt,reopen it,still can not load the missed gamerecord

**Comment by azeier** [comment]
try deleting (renaming) the `config.xml`

**Comment by chucklu** [comment]
I have tried,it's not working
still can not load the game record

**Comment by chucklu** [comment]
Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Controls\Stats\Overview.xaml.cs
UpdateStats()

	if(TreeViewItemConstructedGames.IsSelected)
			{
				ConstructedStats.Instance.UpdateGames();
				return;
			}

	[NotifyPropertyChangedInvocator]
		protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
		{
			PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
		}

can not debug this

**Comment by chucklu** [comment]
Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Stats\DeckStatsList.cs
instance = XmlManager<DeckStatsList>.Load(file);

have checked the game record was loaded successfully into the nstance

**Comment by chucklu** [comment]
could you tell me where is the source code for display the game record

**Comment by chucklu** [comment]
Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\Stats\CompiledStats\ConstructedStats.cs
maybe,this is the function to filter deck stats
public IEnumerable<GameStats> GetFilteredGames(IEnumerable<Deck> decks, bool archived = true, bool playerClass = true, bool region = true,
													   bool timeframe = true, bool mode = true, bool rank = true, 
													   bool format = true, bool turns = true, bool coin = true,
													   bool result = true, bool oppClass = true, bool oppName = true,
													   bool note = true, bool tags = true, bool includeNoDeck = true)

**Comment by chucklu** [comment]
I am sorry，at last I find the deck belongs to the arena deck
I am not sure how could thi deck was set to arena type.

**Comment by chucklu** [comment]
@azeier hi,I met this problem again ,and I have saved the log text and got a screenshot for you
the last game recorded by HDT was https://hsreplay.net/replay/NuY2LB5V4rRMvdwtArcDP9

after that game,I continue use the same deck play the game.
Then I played two more games,the first game I forgot to take the screenshot.
I got the second game's screenshot to prove that HDT stopped working

here is the log for last game recorded by HDT, also included the two games after that(but recorded nothing?)

**Comment by chucklu** [comment]
same problem as #3182
