### ISSUE TITLE
New deck editor mock-up!

### ISSUE THREAD

**Issue by narucy** [HearthSim/Hearthstone-Deck-Tracker#1357]
Hi! I'm really enjoy using Hearthstone deck tracker thank you very much.

Personally more enjoy deck editing on deck tracker. therefore I made mock-up for new deck editor. I hope implementation these style new deck editor.

![hearthstone_deck_tracker-deck_edit fw](https://cloud.githubusercontent.com/assets/4232498/9554616/09e28a0c-4e02-11e5-91c5-6f5cc7568d6a.png)
## 

Hearthstone Deck Tracker is awesome!

**Comment by andburn** [comment]
This is probably my most wanted feature too, I have been thinking about it for ages. 
I'd like to see something that improves on the hearthstone builder, with better filtering, plus card ratings and maybe synergies. Something like the Magic duels builder, but less fancy :stuck_out_tongue_winking_eye: 

![mtg1](https://cloud.githubusercontent.com/assets/5419653/9556738/e625e06a-4dce-11e5-97ab-83f4e753f446.jpg)

![mtg2](https://cloud.githubusercontent.com/assets/5419653/9556742/eaddb16e-4dce-11e5-8211-9d35c883622f.jpg)

It will be a some time, before we see anything like it though :disappointed:

**Comment by Epix37** [comment]
I had an idea about a concept today, not sure how practical that would actually be but it might be worth playing around with:
![screenshot 2015-10-07 20 42 18](https://cloud.githubusercontent.com/assets/7737910/10347391/e9b79546-6d33-11e5-92c6-8af1f83db90a.png)

**Comment by quark-zju** [comment]
I think narucy's UI more practical. It displays more cards. I am not a fan of Cover Flow stuff. It's not actually practical useful.

For the filter, maybe something like GitHub's issue search box is good. It's one text box, easier to both implement and use. It's nice to have a history of searches in dropdown, just like browser address bar. Use up and down key to switch among history entries just like command line. Even with the history feature off, using the GitHub style search box, the user can still use a clipboard manager to filter cards efficiently.

**Comment by andburn** [comment]
I agree that a *cover flow* style wouldn't be very practical. I do like Epix's general mock-up, I'd have the cards as a grid that you can page or scroll (like hearthstone). The idea of a single search/filter box is nice and ties in with the hearthstone search box. However, I think you would still need to have the filters on the left as they are easier to use for the average user (command line interfaces are scary for most!).

When I get the card art and tool-tips sorted, Soon&trade;. I'll start on implementing something like this.

**Comment by azeier** [comment]
Guess I can close this.
