### ISSUE TITLE
Win Percentage

### ISSUE THREAD

**Issue by Merovin90** [HearthSim/Hearthstone-Deck-Tracker#1363]
I have noticed a bug whereby the win percentage for some of my decks are showing to be lower than what they should be (I think it may be linked to spectating a game with the deck being active). For example, I made a new deck and won my first game. I then proceeded to spectate a friend who won, and went to play a second game and my win percentage was showing at 50%, despite showing the wins as 1-0. After winning and going to 2-0, the win percentage updated to 67%, so for some reason the percentage calculation is incorrectly counting a loss from somewhere.

**Comment by GiggliG** [comment]
Have you checked filters? Both in the stats screen (check game mode is set to all), and also in top menu Main -> Sort/Filter -> All.

**Comment by Merovin90** [comment]
Just doubled checked these now and both in the stats screen and in the top menu are set to all, yet my Warrior deck is currently displayed as 50%, with 10 wins and 7 losses.

**Comment by culinko** [comment]
Could you check if this one got fixed? I remember @Epix37 corrected the score calculation for when the game ended in a draw in 0.13.8.

**Comment by culinko** [comment]
Is this still an issue with 0.14.0?
