### ISSUE TITLE
HDT says "could not find or start the battle.net launcher" right before it launches battle.net client

### ISSUE THREAD

**Issue by BobHassok** [HearthSim/Hearthstone-Deck-Tracker#1372]
As the title says, HDT says it cannot find/start battle.net right before it launches my battle.net client. I've set my Hearthstone path in settings; restart HDT; click the launch button; same issue, every time. Also, I assume the Set Data Path in settings adjusts HDT's files and it's not asking for the folder named "Hearthstone_Data" in the Hearthstone folder.

I'm using the newest HDT; newest Hearthstone and Battle.net Client (obviously); Windows 8.1; and can provide more information if needed.

**Comment by Epix37** [comment]
You are correct on the data path.

Can you check what the battle.net launer process is called?

**Comment by BobHassok** [comment]
Yeah, it shows up as "Battle.net desktop app (32-bit)"

**Comment by xeropwnage** [comment]
I'm also currently having this problem on version 0.13.3. Clicking the "Start Launcher/Hearthstone" button once will open the launcher but will not open Hearthstone - on a couple rare occasions, though, it has opened Hearthstone. I've noticed that if I click the button twice, it will open Hearthstone - always. I don't know if that helps or not.

**Comment by Zildjian299** [comment]
im getting this error as well maybe its related to not tracking what you have drawn or played or oponent stats too.

**Comment by Bangy** [comment]
@BobHassok I've had the same problem, it's not a bug. I think you've selected the hearthstone folder  ( for me it's located at   Local Disk (c:)>Program Files (x86)>Hearthstone ) as data path but you should have selected the Battle.net folder ( which for me is located at Local Disk (D:)>Battle.net ). Hope it helped :)

**Comment by Epix37** [comment]
The data path is just where hdt stores stuff, unrelated. 

The launcher and hearthstone are started using "battlenet://" and "battlenet://wtcg".

**Comment by Bangy** [comment]
@Epix37 but selecting that path made my problem go away, which seems to be the same as his, so why not give it a try?

**Comment by azeier** [comment]
The timeout o n this has been increased since.
