### ISSUE TITLE
enhancement: separate the images and program files for updating

### ISSUE THREAD

**Issue by ForceRockWONG** [HearthSim/Hearthstone-Deck-Tracker#1383]
I have some troubles to access/download the full release .zip file. Although it's just less than 15MB, it's too large for me.
I think most of the size of the zip file is for the images, which I don't need to download them every time a new version released.

Is it possible to separate the images and the program files for updating?
I don't think it would be easy for new users to download them from /releases, but it would be great to update them separately via HDTUpdate.exe

Thanks.

**Comment by Epix37** [comment]
It's certainly possible but a lot of work for a minimal effect. I would probably agree, if the download was 100 mb of only images and 5mb of binaries, but currently... it's not worth the effort in my opinion.

**Comment by ForceRockWONG** [comment]
Thanks, Epix37.~

**Comment by riQQ** [comment]
@azeier with the new updater and delta updates this is done, right?
