### ISSUE TITLE
error when importing a deck from hearthstone-decks.com

### ISSUE THREAD

**Issue by Geoff69** [HearthSim/Hearthstone-Deck-Tracker#1396]
could not load deck from specified URL

Hi, this above is the error message I have when I try to import a deck from website Heartstone-deck.

I put French in settings, tried with several decks, always the same error;

Could you help me ? 

thanks !

**Comment by Epix37** [comment]
What website are we talking about exactly? Could you link a deck?

**Comment by Geoff69** [comment]
website is : www.heartstone-deck.fr

this link : http://www.hearthstone-decks.com/deck/voir/gt-gorges-abidol-5445

 [image: Images intégrées 1]

2015-09-05 0:26 GMT+02:00 Epix <notifications@github.com>:

**Comment by Geoff69** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/14132424/9699186/9de32504-53d9-11e5-9722-b68cdf957eec.png)

**Comment by Epix37** [comment]
They didn't update the IDs for the new cards again :(.

I suggest you use [NetDeck](https://chrome.google.com/webstore/detail/netdeck/lpdbiakcpmcppnpchohihcbdnojlgeel)

**Comment by Geoff69** [comment]
oh ok

2015-09-05 16:06 GMT+02:00 Epix <notifications@github.com>:

**Comment by Geoff69** [comment]
Are they planning to release an update ?



2015-09-05 16:23 GMT+02:00 Geoffray Ielo <geoffrayielo@gmail.com>:
