### ISSUE TITLE
HDT "losing" new deck revision after Hearthstats sync

### ISSUE THREAD

**Issue by dhoepelman** [HearthSim/Hearthstone-Deck-Tracker#1508]
Firstly thanks for your awesome and I feel bad for opening another issue on top of the already long list, but here it goes.

Problem: New deck versions aren't synced with hearthstats, and "force full sync" only works while the decktracker is open.

Note that this happened "naturally" a few times, so I don't know if opening/closing HDT in between steps has an influence.
**Steps to reproduce**:
1. Install HDT on 2 computers and link with hearthstats
2. Create a deck with version 1.0 on computer A, sync on computer B ("force fully sync" is usually needed)
3. Edit the deck on computer B and store as a new version 1.1
4. Get the new deck version on computer A with "force full sync". HDT shows 1.1, altough switching to another deck and back is needed to get the in-game tracker to update.
5. Close HDT on A
6. Reopen HDT on A and check deck version, which is 1.0 again.

Additionally there's the hidden problem that the deck sync doesn't happen automatically and "force full sync" sound scary (because of "force", e.g. in force quit), but this may work as intended.

**Comment by Epix37** [comment]
Workaround in #2186

**Comment by judge2020** [comment]
HearthStats is no longer supported by HDT, a new synchronization system is planned for HSReplay.
