### ISSUE TITLE
"Show missing cards" option doesn't appear for all decks with missing cards

### ISSUE THREAD

**Issue by garyking** [HearthSim/Hearthstone-Deck-Tracker#1530]
I right-clicked on a deck I imported from a website, and noticed the "Show missing cards" option. Clicking it did indeed indicate which cards were different. 

However, this option doesn't appear for all decks, even the other decks definitely have different cards as well, from their origin. 

Is there any reason for this, or is it just a bug?

**Comment by Epix37** [comment]
Decks have to be exported to HS once.

**Comment by GaryKing** [comment]
They were already exported to HS, on the same day I checked for this option. I did, however, save them as v1.1, after I made some changes, but I don't think that matters? If I recall, HDT still noticed the changes for one deck comparing my 1.1 to the original from the web.
