### ISSUE TITLE
Class not reported correctly for arena game and blank opponent names

### ISSUE THREAD

**Issue by VicTT** [HearthSim/Hearthstone-Deck-Tracker#1609]
The arena class reported in the Stats->Select Replay window is Hunter (screenshot 1), but my opponent was really mage (screenshot 2).
The name of the replay is correct: VicTT(Priest) vs Uzero(Mage) 0122-141015.hdtreplay
![breport](https://cloud.githubusercontent.com/assets/2959425/10471089/1d697418-721b-11e5-840d-d570dfcfdb79.png)
![breport2](https://cloud.githubusercontent.com/assets/2959425/10471091/2167ea04-721b-11e5-80b0-f1525708909b.png)
Also note the hunter game just above the game one against Uzero. There name is blank there, but is correctly displayed in Replay viewer.

**Comment by culinko** [comment]
Does this still happen to you?
