### ISSUE TITLE
Stuck on uploading new matches

### ISSUE THREAD

**Issue by Necessaryevil91** [HearthSim/Hearthstone-Deck-Tracker#1684]
So I have been having this issue for some time now. I was hoping that it would be resolved after the latest patch but it didn't. Here is a screenshot on were exactly it gets stuck. Anyone got any solution for this? 

![image](https://cloud.githubusercontent.com/assets/15525057/10865367/d3e65b44-8011-11e5-9af6-2292503e31c4.png)

**Comment by Epix37** [comment]
Hearthstats servers were a bit slow lately. Still having the issue?

**Comment by Necessaryevil91** [comment]
Yup! Unfortunately it still persists. I left it for like 1 hour and it's still stuck there, which basically renders HDT unusuable for my main PC :(.

**Comment by Cu8eR** [comment]
https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/1686 there are issues with Hearthstats servers. Sync works fine, but you have to try it later

**Comment by Necessaryevil91** [comment]
Even after 5 days I'm still trying to sync but with no success, are you sure that this is exclusive fault of Hearthstats?

**Comment by culinko** [comment]
Does this still happen?

**Comment by Cu8eR** [comment]
@culinko - I think this occurs only sometimes, because of HearthStats servers - they are overloaded sometimes :(

**Comment by jleclanche** [comment]
Closing, there's nothing we can do about hearthstats issues.
