### ISSUE TITLE
Arena games not syncing

### ISSUE THREAD

**Issue by Melvalan** [HearthSim/Hearthstone-Deck-Tracker#1691]
Hi,
I have had a problem for some time with my arena games. You just added this amazing stat chart for arena games and I would like to use it properly.
However, there is a problem with that, when I create an arena deck on one computer and then jump in the middle to another one, the stats or deck dosn't sync. (They sync with hearthstats) 
This is a bit annoying as that means that my stats are spread out all over the computers that I am using. And since I can see that they are indeed syncing with the internet it would be nice if the decks would sync over all the computers as well.
This is just a problem with arena however. The constructed importer works fine.
Thank you for creating this tracker. :)

**Comment by Epix37** [comment]
Yea, arena "syncing" is currently one-way.

**Comment by judge2020** [comment]
HearthStats is no longer supported by HDT, a new synchronization system is planned for HSReplay.
