### ISSUE TITLE
Flame Leviathan is missing from the opponent's deck

### ISSUE THREAD

**Issue by culinko** [HearthSim/Hearthstone-Deck-Tracker#1702]
My opponent had drawn Flame Leviathan and then played him (in the same turn, also tested in separate turns). It was missing from his deck in the overlay, also after game when i opened opponent's deck. I can upload all the logs/replays if needed.

**Comment by Cu8eR** [comment]
Upload all logs here please

**Comment by culinko** [comment]
You don't need to reply to every issue here on github. I'm sure if Epix wanted, he'd message me here, on gitter or on irc.

**Comment by andburn** [comment]
> You don't need to reply to every issue here on github. I'm sure if Epix wanted the logs, he would either message me here, on gitter or on irc.

:+1:

**Comment by Cu8eR** [comment]
Sorry that you are not the only one who is curious about this :-1: 

Arent you from the East Europe? Must be :dancer:

**Comment by culinko** [comment]
I don't know what is so interesting about this issue. Anyway, the hdt log lines in question are (missing cardId and cardName):

[20:42:49] Opponent Draw: id=61, cardId=, cardName=, turn=14
[20:43:03] Opponent Play: id=61, cardId=, cardName=, turn=14

To compare it to regular card:

[20:43:37] Opponent Draw: id=51, cardId=, cardName=, turn=15
[20:43:50] Opponent Play: id=51, cardId=AT_008, cardName=Coldarra Drake, turn=15

Power.log lines are not interesting at all.

**Comment by Cu8eR** [comment]
@culinko - Thank you! Have a nice day

**Comment by Epix37** [comment]
Reproducible?

**Comment by culinko** [comment]
Yeah, reproduced it 2/2 so far.

**Comment by Epix37** [comment]
Do you post the Power.log? I have an idea what this could be.

**Comment by Epix37** [comment]
Still an issue?

**Comment by culinko** [comment]
This has been fixed since, I can confirm that it no longer happens.
