### ISSUE TITLE
Not tracking losses?

### ISSUE THREAD

**Issue by rxHydrocodone** [HearthSim/Hearthstone-Deck-Tracker#1714]
I just made a new deck and played four games, two wins and two losses. The two wins were successfully recorded and it seems like the replays and all the stats are there. But the two losses were not.

The first loss I conceded, and so I wondered if that caused a problem or I had some option checked to not save games I concede. But the second played out to the end and also wasn't saved. In both cases, I'm pretty sure I saw the information in the overlay above my decklist update to "2-1" but then revert to "2-0" just an instant later.

I haven't experienced other problems recently, with the deck tracker or the game. I'm not running any plugins or other programs related to Hearthstone and deck tracker.

**Comment by rxHydrocodone** [comment]
I just noticed the deck says "67% | 2-1" below its name in the Deck Tracker's main window. But the overlay still reads 2-0 and the stats page shows me 1-0 against druid and 1-0 against priest (my two wins) but 0-0 against mages (both my losses were to mages). And viewing the last replay loads my win against the priest 3 games ago.

Below the deck name is the only place it shows a loss, and still only one of my two.

**Comment by rxHydrocodone** [comment]
It seems to be recording correctly now. I manually added the 2 missing losses and they haven't reappeared, but it has correctly tracked about ten games since, win or lose.

**Comment by riQQ** [comment]
Did this occur around midnight? There's a known bug, that the tracker stops working after midnight and has to be restarted.

**Comment by rxHydrocodone** [comment]
This happened early afternoon, I think around 2 or 3pm EST. Still no problems since then, though.

**Comment by culinko** [comment]
Does this still happen?

**Comment by Epix37** [comment]
Closing for now.
