### ISSUE TITLE
Weird stats - extra classes

### ISSUE THREAD

**Issue by GiggliG** [HearthSim/Hearthstone-Deck-Tracker#1775]
I looked at overall stats today, and noticed that in addition to the 9 classes, there are two extra rows with no games. I have no clue what they are meant to represent. Here's a screenshot.

![image](https://cloud.githubusercontent.com/assets/10089419/11274958/4774df34-8ed3-11e5-8d41-d14ce75d9eaf.png)

**Comment by andburn** [comment]
I noticed this too. They are from last weeks brawl, *Ragnaros* and *Neferian* respectively, not sure how it happened.

**Comment by Epix37** [comment]
Fixed with v0.14.4.
