### ISSUE TITLE
missing/disappearing arena games

### ISSUE THREAD

**Issue by boydkr** [HearthSim/Hearthstone-Deck-Tracker#1848]
use version 13.5 beta

http://pastebin.com/kVBm2VjK

HDT appears to be picking up the games at first, but then some of them mysteriously disappear

Here is a screencap of the [old] games and stats page. It shows 5 games, with 4 of them showing as game mode: None (I manually changed the first game to Arena)  3 games are missing, all wins.
![arena](https://cloud.githubusercontent.com/assets/5815066/11736134/32757c56-9f90-11e5-99ec-d7c63bf7e0e9.PNG)

Here is the new arena run stats view, the game vs Bojangles has now disappeared.
![arena_run](https://cloud.githubusercontent.com/assets/5815066/11736136/366a11c8-9f90-11e5-8327-44c22b9c70ba.PNG)

**Comment by Epix37** [comment]
Did you restart hearthstone after updating to 13.5? Looks like hearthstone is not writing the log file required for mode detection.

**Comment by veri745** [comment]
Restarting Heartstone / HDT did not help.  I played another area, went 4-3, HDT has only 3 games recorded

http://pastebin.com/PLnChi4B

![arena_run](https://cloud.githubusercontent.com/assets/5815066/11751284/330ecfa0-9ffe-11e5-9494-2da657f8234d.PNG)

**Comment by veri745** [comment]
The only other extenuating circumstance I can think of is that I'm using the HearthArena overlay to help with deck creation, so that's running also.  However, unlike in #1819, all of the HDT overlay stuff during the games works just fine.

**Comment by culinko** [comment]
Is this still an issue with the newest version?
