### ISSUE TITLE
Copying the Coin (via mind vision) changes display to "-1" from "C"

### ISSUE THREAD

**Issue by Kryai** [HearthSim/Hearthstone-Deck-Tracker#185]
As mentioned above: While playing priest if you use the spell mind vision (which copies a card from your enemies hand), and you happen to select the Coin, the HUD changes the designation for the coin from "0 C" which makes sense, to the turn value of "-1" which does not make sense.

Is this intended?

Before: ![image1](http://puu.sh/aOntT/a29bcf11ea.jpg)
After: ![image2](http://puu.sh/aOnvD/41b606a30f.jpg)

**Comment by mvordeme** [comment]
The same thing actually happened to me a few minutes ago in Tavern Brawl. I am using version 0.10.7.

**Comment by MechaLynx** [comment]
Pretty sure I've seen this happen myself a few times and I wasn't even using HDT back in August 2014. Not a biggie, but it seems to still be there.
