### ISSUE TITLE
Consumes huge constant CPU resource

### ISSUE THREAD

**Issue by CrendKing** [HearthSim/Hearthstone-Deck-Tracker#1857]
I noticed that if the tracker is left open after Hearthstone is closed, it will constantly consume huge CPU resource (~10% on my Intel i5 3570K). Here's the thread and its stack that consumes the CPU: 
![image](https://cloud.githubusercontent.com/assets/235410/14912216/61b7415c-0e03-11e6-980a-2cbb2cb0f3f8.png)

HDT version: v0.13.3

**Comment by CrendKing** [comment]
Refer to issue #1921, temporary fix is to disable the "Advanced window search" option.

After the change, there is still another relatively high CPU thread from "wpfgfx_v0400.dll!WgxConnection_ShouldForceSoftwareForGraphicsStreamClient+0x39", averaging at 1.5%. Much better, but I expect HDT should not use that much when Hearthstone is closed.

![wpfgfx_v0400](https://cloud.githubusercontent.com/assets/975235/12012871/b328f82a-acbd-11e5-899c-428609272750.png)

**Comment by Nicte** [comment]
Hi,

Just to let you know that I still see this issue. I have tried the proposed fix of unselecting "Advance Windows Search" but it didn't help.

![image](https://cloud.githubusercontent.com/assets/4835465/13727722/16769b2c-e8fe-11e5-87fd-42529d223747.png)

By the way, I am using latest version v0.13.14

**Comment by Epix37** [comment]
This should finally be fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/d54f16f27ca6341e2bb5712afc61ebb276449429.

**Comment by Epix37** [comment]
Should be fixed with v0.15.4
