### ISSUE TITLE
Exporting too fast

### ISSUE THREAD

**Issue by MantiBrutalis** [HearthSim/Hearthstone-Deck-Tracker#1859]
My laptop is not exactly a powerful machine, so Herthstone gets a bit choppy if I use any kind of overlay. That's fine with me, but when trying to export from HDT to Hearthstone, the game just can't keep up even with Very Slow (150ms) setting and 30-50% of the cards get missed. Sometimes one copy, sometimes both copies don't get in. I can clearly see HDT clicking the spot where the card should be after it searches for it, but the Collection Manager just "searches" for it a bit too late in some cases.

Can we have an even slower setting? Or can I somehow modify the config files to change the speed setting myself?

**Comment by andburn** [comment]
You should be able to change the setting in the config file `%AppData%\HearthstoneDeckTracker\config.xml`. When HDT is not running open the config file and look for the line containing `<DeckExportDelay>150</DeckExportDelay>` and change the number to whatever. The change won't be reflected in the options, but the new delay will be used when exporting. Hopefully, it works out for you.

**Comment by MantiBrutalis** [comment]
Changed the delay to 250 and 300, tried a few times. The exporting process simply just stops after adding the first card now. Reverting the value back to 150 fixes the issue. Meanwhile I managed to squeeze a bit more out of my laptop by tweaking some priority settings. Still skipping over 3-5 cards on average though.

**Comment by Epix37** [comment]
Have you tried the first two suggestions in the FAQ? https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#exporting

**Comment by Lutwick** [comment]
Hi there, I am having the same problem as MantiBrutalis: also I am running HS on a rather old machine (Dual Core, 4 GB RAM) such that the animations of adding cards to the deck or even the loading of new cards after entering the search strings. The effect is that sometimes some cards are missed during export.

However, changing the <DeckExportDelay> entry in config.xml does not show any effect. And when I close and restart HST, the entry is reset automatically to the previous value (150).

Help would be greatly appreciated. Thanks!

**Comment by KoRRo** [comment]
even if my pc is pretty powerful i had the same problem before moving hs from my mechanical disk to my ssd. for me it looked like hs was too slow reading the cards and loading them in memory. a workaround that worked pretty well was to turn all the collection pages before exporting, so all the cards were already in memory when exporting. if changing the configuration isn't enough you could try this, maybe it could also be added to the faq.

**Comment by Lutwick** [comment]
This issue does not occur any more for me, even though I did not change my PC. Have not tried it for some time, so I cannot say with which version it got resolved.

**Comment by azeier** [comment]
That's great to hear! There were some improvements to exporting stability with v1.1.0.2.

**Comment by azeier** [comment]
HDT now uses Hearthstones native deck string importing system.
