### ISSUE TITLE
Sometimes games don't record.

### ISSUE THREAD

**Issue by MarineKingAizen** [HearthSim/Hearthstone-Deck-Tracker#1865]
Hi, sometimes the game just won't record properly. It's been happening WAY more since LoE (and this isn't related to the Entomb issue. The other thing is, I notice when the game doesn't record neither does the rank. The game shows up in my list of "overall games" but it won't show for the deck that was used.

Then, when I move the game to the proper deck by force, it still won't show up on the main screen for win/loss. Please advise, thanks.

**Comment by Epix37** [comment]
This is with v0.13.3? (You can see the version number under "help" in the title bar or in the system tray icon tooltip)

What game modes do you have the problem with?

**Comment by jayhall** [comment]
Happens to me I'm not sure when or why, but games will randomly not record.   Possibly once it stops it doesn't record again that runtime.   For example I just noticed today that non of my games recorded.  

I think in the past I've had it happen mid session, so maybe there is some bug that happens in certain game conditions that stops the recording for the session.

Also is there a way to manually add games from the app data files so I don't have to just manually add them in the HDT "add game ui".   I'd like to have the full review and everything.

I see xml docs in AppData/Roaming/HDT/Games but I am having trouble attaching them in a zip file for some reason.   Will keep trying.

Thanks

**Comment by jayhall** [comment]
[HDT_log.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/63149/HDT_log.txt)

Maybe this will be useful.   (and I was able to attach it).   Looking further into it, the files I was referencing before seem like something created as games are logged, so you probably didn't want those anyway.

**Comment by MarineKingAizen** [comment]
I am running v0.13.3 and the mode I often have problems with is ranked. The issue doesn't consistently happen, just sometimes and for no apparent reason that I can see. What I can say is this, once it fails to record a game for a certain deck, it will continue not recording games until I reboot the tracker.

**Comment by Epix37** [comment]
This should hopefully be fixed with the next release.

**Comment by MarineKingAizen** [comment]
Ok now I have the new patch and the tracker is dropping more games than ever before. It's not recording almost anything : (

**Comment by Epix37** [comment]
Could you post the hdt logs of that happening? `options > tracker > settings > open appdata folder`, "Logs" folder, zip and upload the hdt_log files since you started using 0.13.6 (http://zippyshare.com).

**Comment by eshlin** [comment]
Wanted to mention that I had been seeing a similar intermittent problem where games would either not record or even record with wrong or missing information, since LoE. But just grabbed the latest 0.13.7 patch from an hour ago, and everything seems to be recording perfectly now. Thanks!

**Comment by mvordeme** [comment]
I have seen similar problems, too, mainly because the tracker didn't recognize the end of a game and kept on drawing from the same deck. It happens consistently whenever a new quest pops up at the end of a game, but not only then.

**Comment by MarineKingAizen** [comment]
*LOG ATTACHED*

Hi Epix, I currently have v0.13.7 and I am still experiencing the same problem, games are not recording. Every once in a while a few games will record, but most often they won't.

This morning I played 3 games and none of them recorded, neither for the deck nor under All Games, I checked for all modes as well and nothing. It's as if the tracker missed the entire session. I've attached the log for todays 3 games, perhaps you can shine some light on the issue. Thanks.

[hdt_log.txt](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/83213/hdt_log.txt)

**Comment by culinko** [comment]
@MarineKingAizen Your games were detected as Casual (#1852, #1889) and you have saving Casual games off. You should turn on saving games in Casual mode until this bug gets fixed.

**Comment by MarineKingAizen** [comment]
Thanks for the tip culinko. I did enable the tracker to record all game types including casual and that did improve the recording rate a lot. However there are still a lot of games not being recording. If I had to put number to it, I'd say about 30% of the games are not recorded even though I have all the record modes enabled.

Another interesting thing, when I delete stats from a deck or multiple decks and then switch back the main screen it still shows all the wins/losses next to their respective decks, even though I just deleted those games. It shouldn't be showing anything next to a deck if I cleared all the games, but there it sits and won't refresh to 0/0 until I shut down HDT and reboot it.

**Comment by culinko** [comment]
Is this still an issue in the newest version?

**Comment by MarineKingAizen** [comment]
@culinko Thanks for asking, it's been pretty solid over the last few versions. All games are recording now, but they almost always record as casual even though I'm playing ladder.

**Comment by Epix37** [comment]
@MarineKingAizen See if this helps / is the case for you: https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#ranked-games-are-recorded-as-casual

**Comment by culinko** [comment]
Closing for now, let me know if this is still an issue and I will reopen it.
