### ISSUE TITLE
Tie is marked as loss in stats

### ISSUE THREAD

**Issue by NoHuman** [HearthSim/Hearthstone-Deck-Tracker#189]
I was playing in arena, and we both died to an abomination deathrattle. It told me in game that it was a defeat, but I suspect my opponent also got "defeat". Back in my arena screen I am still at 2 wins and 0 losses, so I didn't get a win nor a loss. How could we solve this in the tracker stats, which currently says 67% win ratio?

**Comment by culinko** [comment]
Now that we can actually add/edit the games itself, would it be viable to add an option to change/add the result as a tie or would it be too much of a hassle?

**Comment by Epix37** [comment]
Is that not possible already? It's just called 'draw'  instead of 'tie'.

**Comment by culinko** [comment]
Apparently I'm dumb, sorry!
