### ISSUE TITLE
Spectator mode usually missing result/name/turns

### ISSUE THREAD

**Issue by dphil** [HearthSim/Hearthstone-Deck-Tracker#1917]
I've been spectating quite a few games lately, and have noticed that _most_ of the time it records nothing for the result, # turns and opponent name for each match (it generally always records "hero", "vs", "time", "started", "coin" and "region" correctly though), . Once in a while it does record all of those (seems to be an all-or-none issue for those 3 fields). I'm not really sure why only the rare occasional game records that data while the rest don't. Is it not just pulling that data from the log file? If it's getting all of that via some sort of image detection or something, then perhaps it's an issue with me not having HS in the forefront all the time, or using a screen dimmer (as I pointed out was an issue with ranked detection in another bug report).

I do have HDT set to record stats for Spectator games under the settings.

On a possibly related note, it records the game mode for a lot of the games I spectate as "None", including for the ones where it records all the details (result, turns, name, etc) correctly. I think it may not identify the first spectated match correctly, but even after spectating a streak of matches in a row identifying them correctly as spectator mode, I've had it suddenly not recognize the following spectated matches anymore (instead simply labelling their game mode as "None").

**Comment by dphil** [comment]
Screenshot of what I mean: http://i.imgur.com/q4AWuoi.png

All of those except the very last (topmost) game were spectate in an uninterrupted streak. I assume the first one (at the bottom of the list) is "None" because it has trouble detecting if you jump into spectating after a match has started, which is fine. However after registering the next 5 games correctly as Spectator mode, suddenly it goes back to "None" for the next few (again, disregarding the last game where I stopped and re-started spectating). And notice how for some reason it only recorded opponent's name, # turns and game result for that one (3rd-last) match.

**Comment by culinko** [comment]
Does this still happen in the newest version?

**Comment by riQQ** [comment]
Working for me for quite some time now.
