### ISSUE TITLE
Replays: Secret-related bugs

### ISSUE THREAD

**Issue by culinko** [HearthSim/Hearthstone-Deck-Tracker#2021]
When your opponent plays a secret that won't be revealed until the end of the game, its entry will be missing in the replay viewer. Also, if your opponent plays a Mysterious Challenger (untested with Kezan Mystic stealing your secret), the secrets brought into play will be on your side of the replay tree.

![secrets](https://cloud.githubusercontent.com/assets/11700272/12616334/e6a2e584-c50a-11e5-96cb-14b086a70a73.png)

**Comment by azeier** [comment]
Local replay support has now been fully removed.
