### ISSUE TITLE
Enhance-o-Mechano - Not showing Windfury effect text in replay

### ISSUE THREAD

**Issue by jmac-slash0** [HearthSim/Hearthstone-Deck-Tracker#2036]
When playing Enhance-o-Mechano the Divine Shield and Taunt effects are displayed as text on the cards in replays. However, no text is present for cards given the Windfury effect. You can see the issue in the attached replay on turn 9.

[Occ(Warlock) vs Twfic(Warlock) 2120-280116.zip](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/110285/Occ.Warlock.vs.Twfic.Warlock.2120-280116.zip)

**Comment by azeier** [comment]
Local replay support has now been fully removed.
