### ISSUE TITLE
Can't register my account.

### ISSUE THREAD

**Issue by legends784** [HearthSim/Hearthstone-Deck-Tracker#2046]
I just installed the Deck Tracker a couple of days ago and everytime I open it up and try to register an account it just keeps saying "registering account" with the loading symbol and eventually times out after 
10 minutes. I can sign in as a guest just fine but I'd like to actually use an account if possible. 

Thanks,
~legends784

**Comment by Epix37** [comment]
Try creating an acccount on the website (here: http://hearthstats.net/users/sign_up?) and signing in with that.

**Comment by legends784** [comment]
i created an account on the site and that worked but when i try to sign in
on the app the same problem arises except now it says "logging in" for 20
minutes before timing out and telling me the connection was interrupted.

**Comment by Epix37** [comment]
Could you post the log after trying to login/register? ([see here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues))

**Comment by legends784** [comment]
Well this is it after I logged in as a guest, but I can't really get you a
log after "replicating the problem" because the problem is that it won't
let me log in in the first place.

http://pastebin.com/FBTbaAbk

**Comment by jleclanche** [comment]
Closing this as HearthStats integration is essentially deprecated.
