### ISSUE TITLE
New Decks Show Record

### ISSUE THREAD

**Issue by obroithe** [HearthSim/Hearthstone-Deck-Tracker#2101]
Whenever I make a new version of a deck (say 1.5 from a 1.4), it will give it an existing record of one or two games when there has never been a deck there.

**Comment by Epix37** [comment]
Where exactly do you see those? In the deck list or actually under `STATS > GAMES & STATISTICS > Deck > Stats` for the new version?

If it's the former:
- Are they still there after restarting HDT?
- What is selected under `options > tracker > stats > display`?

**Comment by obroithe** [comment]
In the deck list on the main screen of HDT.

Yes they are still there after restarting.

Selected / All / All Time

**Comment by Epix37** [comment]
Please check if you still have this problem with the latest release (v0.14.0)

**Comment by VeXHarbinger** [comment]
I've seen this before when building newer versions of decks. To resolve it I just Right clicked on the deck in the deck selector, and selected the Clone deck, do not clone history.  Then I just archived the old version.  This doesn't occur all the time but, I think I've only experienced it after a patch release on Hearthstones part. Did not occur for all decks at the time, only one or two.  I'll try to watch for this behavior in the future, if it occurs again in the hopes to help trace the causality.

**Comment by obroithe** [comment]
This still happens for me. Updated a deck from version 1.6 to 1.7 and it immediately gave it a record of 0-1.

**Comment by culinko** [comment]
Can you upload your DeckStats.xml (you can find it in %AppData%/Roaming/HearthstoneDeckTracker/) and tell me which decks are affected?

**Comment by culinko** [comment]
Does this still happen?

**Comment by obroithe** [comment]
No. It seems to be fixed now. I have another problem though with the deck
tracker for opponents. After a game or two, it stops showing up unless I
restart the program until it does it again a few games later.

**Comment by riQQ** [comment]
Original issue is fixed, the other was fixed as well as per #2525.
