### ISSUE TITLE
Add legend rank to GameStats

### ISSUE THREAD

**Issue by Epix37** [HearthSim/Hearthstone-Deck-Tracker#2117]
`GameMetaData` now holds that information.

Figure out:
- Use the one logged before the game?
- How to display in stats rank column? `L42`?

**Comment by Cu8eR** [comment]
I think this is implemented via https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/85c4d5dbc5f48c80bc98567616b49c0f63e727f1

**Comment by Epix37** [comment]
Added  with v0.14.4.
