### ISSUE TITLE
Suggestion: Option to Start/Close HDT & Hearthstone/Battle.net

### ISSUE THREAD

**Issue by DrHackenstein** [HearthSim/Hearthstone-Deck-Tracker#216]
It would be awesome if I didn't have to start and close HDT and Hearthstone separately. There could be:
1. Option to close HDT, when Hearthstone is quit
2. An executable that starts HDT and then Hearthstone/Battle.net

**Comment by Matter94** [comment]
I've read a reddit post today which told us how to open Hearthstone without the launcher.
You simply have to create a shortcut to the path: "battlenet://WTCG" and with this shortcut just refer to it with the ending .url in a .bat file and you can start Hearthstone and HDT at the same time! :)

The .bat looks like this
start "" "[your HDT directory]\Hearthstone Deck Tracker.exe"
start "" "[your shortcut directory]\[shortcut name].url"
