### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Radiohawk58** [HearthSim/Hearthstone-Deck-Tracker#2165]
Hi, in the middle of Arena run (during the card selection session) w/following report via the app:

http://pastebin.com/xpVbJp6H

Thanks!!!

**Comment by Epix37** [comment]
```
10:25:46 AM|Warning|PluginWrapper.Update >> Updating Arena Helper took 3381 ms.
```

Not necessarily the cause but it's the last thing logged before the crash, so likely.

@Rembound The log contains 12 instances of that, could you look into moving [whatever happens in the `OnUpdate `] off of the main thread?

**Comment by rembound** [comment]
I can see that auto-saving of decks is enabled during a draft. I use the `SetNewDeck, SaveDeck, SelectDeck` functions to partially build the deck. I have noticed that `GameV2.Reset` is called each time after saving the deck. This will reset the logreaders and results in having to process the entire log file again. I use `LogEvents.OnArenaLogLine.Add(OnArenaLogLine)` to process card picks. I have compensated for this behavior by filtering old loglines. If the log file is big, a lot of lines are processed each time a SaveDeck is called in the `OnUpdate`, which results in a delay.

There is one other issue that comes up. Sometimes the logreader stops functioning after the `GameV2.Reset` is called. I can see that the actual HS logfile gets updated, but the logreaders don't get any new lines to process. Only restarting Hearthstone fixes it. When the issue happens, I can see In the HDT log that `Restarting LogReaders.` is displayed, but afterwards `Stopped LogReaders.` is displayed without ever starting the logreaders. Maybe this is a threading issue, by calling `GameV2.Reset` multiple times.

**Comment by Radiohawk58** [comment]
First- I ask that you forgive my ignorance :)
So the update has continued to stop as described, this morning I followed the instructions to manually install.  Now I have multiple instances of HDT in the documents folder and the new version has lost most of my history plus the plugin for arenas is missing - where file does HDT store history in, can I just copy my games to the new version?  after that can I safely just delete the other instances (old versions it appears) in there entirety?

thanks

**Comment by Epix37** [comment]
Unless you changed `options > tracker > settings > store data in appdata`, HDT stores everthing in `%AppData%/HearthstoneDeckTracker` (`options > tracker > settings > open appdata folder`). The data is independant of "installations", you have the same decks and stats, running HDT from 3 different folders. 

If you *did* disable`store data in appdata`, copying over everything (or just overwriting the files in the previous installation) should work just fine.

Otherwise you can try restoring a previous backup under `options > tracker > backups`.

**Comment by Radiohawk58** [comment]
thanks very much!!

**Comment by Epix37** [comment]
Does this still happen with v0.14?

**Comment by Radiohawk58** [comment]
HI, sorry about the delay in answering... got a new 'puter and trying to set it up. all seems to be working better... on a different issue, when using "sync" or "force complete sync" almost always get an error that says something to the effect of connection to hearthstats timed out" unless i sync very often (hourly)

it appears tho' that the sync does perform, i always do the sync again just to make sure.  never reported it as it's no biggie to just do it again, just providing an fyi.
