### ISSUE TITLE
feature: wild vs standard

### ISSUE THREAD

**Issue by anonymous555** [HearthSim/Hearthstone-Deck-Tracker#2178]
Distinguish (maybe with an icon)
wild games from  standard
wild cards vs standard cards
wild decks vs standard decks
wild vs standard deck filtering.

**Comment by GiggliG** [comment]
Great idea.

**Comment by Epix37** [comment]
That's planned, yes.

**Comment by Epix37** [comment]
Progess:
- [ ] distinguish games
- [x] distinguish decks
- [x] filter decks
- [x] filter cards

**Comment by Epix37** [comment]
Added  with v0.14.4.
