### ISSUE TITLE
Stats for the past 30, 60, x days

### ISSUE THREAD

**Issue by GaryKing** [HearthSim/Hearthstone-Deck-Tracker#2195]
It would be nice to get stats for not just the pre-set time spans like This Month, Last Month, but also for the past 30 days, past 60 days, past X days, etc.

Because if I play HS at the first 3 weeks of February and then start playing the second week of March, then I have no useful stats. "Last 7 days" and "This Month" shows no games, "Last Month" won't show the few number of games I've played so far this month, etc. But "Last 30/60/x days" would cover all that, and therefore provide useful stats.

**Comment by Epix37** [comment]
Already possible with display (deck/overlay) and arena, will of course also come for constructed with the rework on that.

**Comment by GaryKing** [comment]
For decks and arena, we can just show stats from a specific X date to today, but not a rolling date range of the past X days though. So we always have to change the X date every once in a while.

**Comment by Epix37** [comment]
So, adding one item for `Past X days` (needs better phrasing) that spawns a input text box should cover all of this. That would be fine I suppose.

**Comment by culinko** [comment]
> Started (see #573): select a range to show games played in that period (e.g. from 12 February 2015 15:00 to 13 February 15:00).

See filters in #692.

**Comment by Epix37** [comment]
Closing in favor of https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/692#issuecomment-213521877
