### ISSUE TITLE
Export to website

### ISSUE THREAD

**Issue by Glaived** [HearthSim/Hearthstone-Deck-Tracker#220]
Hello,
Would it be possible to export a deck, to the site such as hearthhead or other (it was an example) ?

**Comment by n4ru** [comment]
This should be totally possible for HearthHead. The deckbuilder URL converts cards to part of the URL string.

**Comment by mjc-** [comment]
Hearthpwn should be quite easy to add if cardDB.<lang>.xml had the magic hearthpwn IDs. 

I wrote up my own tool to just take the named export and convert it using data pulled from their deckbuilder.

https://github.com/mjc-/hstracker-to-hearthpwn

**Comment by shishi** [comment]
I want to export Hearthpwn too! :+1:

**Comment by judge2020** [comment]
I have made a plugin for this! 

https://github.com/judge2020/Export-To-Web-HDT

Currently it only works for Hearthpwn but I hope to support more in the future.

**Comment by judge2020** [comment]
Most websites now accept importing deck string, going to close.
