### ISSUE TITLE
How do i import decks (from constructed) properly?

### ISSUE THREAD

**Issue by bajungadustin** [HearthSim/Hearthstone-Deck-Tracker#2250]
i know its said its in beta for a while now... but it really just doesnt seem to work as good as it used to.

When i import it only imports everything from about 4 to 6 mana cost and up and everything under that is all spells and cards from the specific class that i didnt put there

i mean i know how to do it.. or what it says.. i go to the main menu... open collection... click the deck.. click back.. click back to the main menu... and then click import...

Edit - I have reset up my collection multiple times and this is the result.. my collection hasnt changed

**Comment by bajungadustin** [comment]
i mean i know how to do it.. or what it says.. i go to the main menu... open collection... click the deck.. click back.. click back to the main menu... and then click import...

**Comment by GiggliG** [comment]
I find it is a bit flaky, sometimes it works okay, other times it misses out cards below a certain mana cost (not always the same).

Try this - with HDT open, go to your collection, click on druid, then flip through your entire collection, one page at a time, till you reach the end.

Then back out to the main menu. Then do what it says to import a collection: open collection, open deck, click back and again to the main menu, then do the import.

See how that works.

**Comment by YuiKitamura** [comment]
There have been numerous reports of this problem, the importing feature is clearly not working properly and I feel as if the creator of this program just refuses to admit that it's broken.

**Comment by Epix37** [comment]
Now that's just not true. Almost every chance I get I say this feature is very far from perfect but it sadly is as good as it gets when it comes to importing constructed decks without reading the game memory. There is next to no information in the game logs about constructed decks.

Try re-running setup via `options (advanced) > tracker > importing > set up constructed importing`.

**Comment by YuiKitamura** [comment]
I understand that, the only thing I could possibly think of is that something changed in the way that Blizzard stores information for how you import the constructed decks. They simply don't import like they used to, this isn't just a persistent problem that was always part of the deck tracker, it started happening to people pretty recently. Sorry if I came off as aggravated, I can see the amount of effort you put into making this the best you can for everyone that uses it, I just don't understand how something could so clearly change without any signs being shown.

**Comment by Epix37** [comment]
Constructed importing works by checking the logs for unloaded assets (card images) when exiting the collection screen. This has two main problems:
1) Each image is only unloaded once, meaning determining the count of cards is not possible
2) The collection pages (on the left) also contain cards that get unloaded and there is no way to differentiate between those cards and the cards that were in a deck.

The second point is why the importing asks you to open all the first class pages - to see which cards get unloaded from them, so that those cards can be ignored when actually trying to import decks.
This means, when your collection changes, there is a chance the cards on the first page also change and with that HDT will ignore the wrong cards unless the setup in run again.

So the longer you use HDT (and the more your collection changes) the worse importing will get until the setup is re-run. And even then, this method is just wonky period.

Hope that sheds some light on the problem.

**Comment by tknights2015** [comment]
Still having this issue. Almost all cards are incorrect, up to 4 or 5 casting cost. Have run the constructed set-up multiple times and results in no change.

**Comment by tknights2015** [comment]
Currently when importing, entire first page is added to the deck and nothing until higher casting cost cards.  Ran the constructed set up just prior to this import.
[log_2742016-19957.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/239617/log_2742016-19957.txt)
![capture](https://cloud.githubusercontent.com/assets/16232528/14872687/fe17d7ea-0cab-11e6-9008-9d69da7ab8d8.JPG)

**Comment by matteo-mosca** [comment]
I don't know if this can be helpful, but the application "Innkeeper" reads your constructed decks fine, with card quantity too, and does it automatically just running in the background, and then shows your deck to the right when you start a game just like your app does. Maybe you can try to check how they do it?

**Comment by culinko** [comment]
Importing should be fixed with 0.15, can you guys confirm?

**Comment by GiggliG** [comment]
It's not working for me. Is there anything i need to do to check its set up
properly?

**Comment by GiggliG** [comment]
Update: i made a brand new deck, ran the import manually and it worked perfectly.
Then modified the deck, and returned to play menu, and it got updated.

So maybe this works only with decks created or imported since the update? I'll do some more testing later.

**Comment by Epix37** [comment]
It should also work with existing decks. 

One thing to note: If a version of the deck you are trying to import already has all the cards, it won't create a new version.

**Comment by GiggliG** [comment]
It seems like its updating decks that just have 1 version (1.0), but not updating decks that have multiple versions. 
* The new deck I made above, I then modified again, and that change did not get imported to HDT.
* I modified a deck that already existed but only had 1 version, and it's changes got imported, creating version 1.1. I then altered it again, and the new changes should have made a version 1.2, but nothing happened.

**Comment by Epix37** [comment]
I think I found the issue.

**Comment by GiggliG** [comment]
i did just create a new deck, and get it to update through versions 1, 1.1., 1.2, and 1.3, so it seems intermittent and I cant see why it works for some decks and not others. 

But if you've found the issue, great!

**Comment by YuiKitamura** [comment]
It works wonderfully now, I really appreciate the effort that went into this.

**Comment by tknights2015** [comment]
It works me me also. Haven't tested updating an existing or other versions, but initial imports on new decks works great.  Thank you , Thank you !!

**Comment by culinko** [comment]
Closing this for now, let me know if anything is still bugged and I will reopen this.
