### ISSUE TITLE
Stats are tracked no matter what settings you choose

### ISSUE THREAD

**Issue by anonbro** [HearthSim/Hearthstone-Deck-Tracker#2255]
I have no interest in seeing my deck's win/loss ratio, so I turn literally every single stat tracker off. The app still tracks with the full suite of features, completely ignoring my settings.

**Comment by Epix37** [comment]
Can not reproduce this. 

Conceded a game in ranked, constructed and practice, with modes disabled under `options > tracker > stats > record`, none were recorded.

Are you using the latest version? An issue like this was fixed with v0.13.13. See #2107.

**Comment by anonbro** [comment]
Using 0.13.17, I let the auto-updater keep it up to date. Settings:

![asdf](https://cloud.githubusercontent.com/assets/7203579/14020696/85b9976a-f195-11e5-941a-1d6595b3f0d1.jpg)

**Comment by Epix37** [comment]
Please reproduce the issue:
- restart HDT and HS
- play 2 games where the stats get recorded (concede vs ai is fine if that works) 

Then post the hdt log ([see here](https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)) and a screenshot of the `stats > games & statistics > overall > games` table.

**Comment by culinko** [comment]
I remember this happening to me with AI/spectator games being recorded if I was switching my deck a couple of times during the match (also could be switching between deck and no deck mode).

**Comment by culinko** [comment]
Does this still happen?

**Comment by riQQ** [comment]
Probably the same as #3343.
