### ISSUE TITLE
Replays: Card names cut off

### ISSUE THREAD

**Issue by culinko** [HearthSim/Hearthstone-Deck-Tracker#2283]
When viewing replays, the card names on the battlefield have their names cut off (e.g. Captain, Mimiron's, Shieldmaide). Using 0.13.19.

![replays](https://cloud.githubusercontent.com/assets/11700272/14156144/2bc45b66-f6c5-11e5-9e48-2d2a242c201b.png)

**Comment by judge2020** [comment]
Local replays are now unmaintained, and replays should now use hsreplay.net

If this is a problem there as well, it would be best to create in issue on [that repo](https://github.com/HearthSim/HSReplay.net).
