### ISSUE TITLE
Thaurissan: cost reduction indicator doesn't work correctly

### ISSUE THREAD

**Issue by CookieCompiler** [HearthSim/Hearthstone-Deck-Tracker#2301]
The value of the cost reduction indicator decreases even if Thaurissan is defeated.

**Comment by CookieCompiler** [comment]
Additionally, the values change at the beginning of the turn, and not at the end.

**Comment by sourtoshi** [comment]
also decreases after being silenced

**Comment by Epix37** [comment]
Well, it *seemed* to be too easy to be true. Guess it was. 

It will currently just decrease while the buff is in play. For some reason I thought the buff would get removed after Thaurissan is dead, which, of course it does not.

**Comment by Epix37** [comment]
The values will now:
- only increment if Thaurissan is still in play and not silenced
- update at the start of the player turn, instead of the start of the next opponents turn

**Comment by askarmuk** [comment]
I can confirm this. Thought of uploading logs but it seems there is no reason for it.

**Comment by Epix37** [comment]
Fixed with v0.14.4.
