### ISSUE TITLE
Help please! Deck Tracker shows but doesn't work

### ISSUE THREAD

**Issue by amospottero** [HearthSim/Hearthstone-Deck-Tracker#2330]
Hey,
I have installed the latest Deck Tracker update for hearthstone. It appears fine in my Hearthstone client, even though the resolution is very low, but it doesn't work. I'm able to see my deck on the right when I play Hearthstone, but the cards in my hands are not disapearing in the decklist. It's just a static image, although it says it's active in my deck tracker window. 
Other options such as importing or exporting decks work fine. 
Can anyone help me?
Thanks

**Comment by Epix37** [comment]
See https://github.com/Epix37/Hearthstone-Deck-Tracker/wiki/FAQ#not-working

**Comment by Ohdrin** [comment]
This is what I'm seeing in Event Viewer:

Fault bucket 108086116497, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Hearthstone Deck Tracker.exe
P2: 0.1.0.0
P3: 56ff8ee1
P4: clr.dll
P5: 4.6.1073.0
P6: 56b2832e
P7: c0000005
P8: 0001fd54
P9: 
P10: 

Attached files:
C:\Users\Drew\AppData\Local\Temp\WER2D6F.tmp.WERInternalMetadata.xml
C:\Users\Drew\AppData\Local\Temp\WER3947.tmp.appcompat.txt
C:\ProgramData\Microsoft\Windows\WER\Temp\WER3977.tmp.dmp
C:\Users\Drew\AppData\Local\Temp\WER3A91.tmp.WERDataCollectionFailure.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Hearthstone Deck_8f553c4271412cb961d37afe3eb217f46b0d81_102a5675_225a3f8f

Analysis symbol: 
Rechecking for solution: 0
Report Id: 9d52a8dc-11de-47e7-865d-28e8faff6d10
Report Status: 4104
Hashed bucket: 77d1891f71b0dea0c8150c6e5e1fcd67

**Comment by rocknex7** [comment]
The FAQ dosen't help me at all. The trakcer dosen't track and I have tried SO many things but nothing works. Even tho the deck is active!

**Comment by riQQ** [comment]
Are the Hearthstone logs created (see linked FAQ entry for folder)?

**Comment by riQQ** [comment]
@Ohdrin create a separate issue, please.

**Comment by Epix37** [comment]
Closing due to lack of response.
