### ISSUE TITLE
Bugs with secrets from multiple classes

### ISSUE THREAD

**Issue by culinko** [HearthSim/Hearthstone-Deck-Tracker#2337]
This only happens if you have Interactivity turned on, along with "Click secrets to gray out". If your opponent has secrets from multiple classes active and you click on the overlay to disable and enable them again, it will display each secret in the upper list multiple times (the total number of active secrets, disregarding the different classes, so in this case it was 2, because of 2 active secrets). Also, you can only click on the upper list, you can't click on the lower ones. The secrets in the picture below were Misdirection and Mirror Entity.

![secrets](https://cloud.githubusercontent.com/assets/11700272/14440726/8eaad438-0031-11e6-8153-d7b1cd559bc2.png)

**Comment by azeier** [comment]
Should be fixed by https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/5a25bc54665c8e7266ebbd6687e5834afe6e89cb
