### ISSUE TITLE
App won't launch.

### ISSUE THREAD

**Issue by Ohdrin** [HearthSim/Hearthstone-Deck-Tracker#2340]
I've already removed and reinstalled .NET Framework 4.6.1, ran the MS provided cleanup utility on it as well. Removed and reinstalled the Deck Tracker as well. On launch it immediately presents error:

"Application has stopped working."

Here's what I'm getting from event logs:

Fault bucket 108086116497, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Hearthstone Deck Tracker.exe
P2: 0.1.0.0
P3: 56ff8ee1
P4: clr.dll
P5: 4.6.1073.0
P6: 56b2832e
P7: c0000005
P8: 0001fd54
P9: 
P10:

Attached files:
C:\Users\Drew\AppData\Local\Temp\WER2D6F.tmp.WERInternalMetadata.xml
C:\Users\Drew\AppData\Local\Temp\WER3947.tmp.appcompat.txt
C:\ProgramData\Microsoft\Windows\WER\Temp\WER3977.tmp.dmp
C:\Users\Drew\AppData\Local\Temp\WER3A91.tmp.WERDataCollectionFailure.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Hearthstone Deck_8f553c4271412cb961d37afe3eb217f46b0d81_102a5675_225a3f8f

Analysis symbol: 
Rechecking for solution: 0
Report Id: 9d52a8dc-11de-47e7-865d-28e8faff6d10
Report Status: 4104
Hashed bucket: 77d1891f71b0dea0c8150c6e5e1fcd67

**Comment by riQQ** [comment]
Which windows version are you using? Can you zip and upload the files mentioned under `Attached files`?

**Comment by Ohdrin** [comment]
Windows 10 Pro, 64 bit. Also getting this now:

Application: Hearthstone Deck Tracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an internal error in the .NET Runtime at IP 70D2FD54 (70D10000) with exit code 80131506.

I'll get the files attached here shortly.

**Comment by Epix37** [comment]
Did you extract the zip? HDT does not run from within the zip in most cases.

**Comment by Ohdrin** [comment]
Extracted a fresh copy ot my desktop with the same error.

Seeing this in the Event Viewer:

Application: Hearthstone Deck Tracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an internal error in the .NET Runtime at IP 70D2FD54 (70D10000) with exit code 80131506.

and

Faulting application name: Hearthstone Deck Tracker.exe, version: 0.1.0.0, time stamp: 0x56ff8ee1
Faulting module name: clr.dll, version: 4.6.1073.0, time stamp: 0x56b2832e
Exception code: 0xc0000005
Fault offset: 0x0001fd54
Faulting process id: 0x480
Faulting application start time: 0x01d19504718f7f9c
Faulting application path: C:\Users\Drew\Desktop\Hearthstone Deck Tracker\Hearthstone Deck Tracker.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Report Id: e9f70179-c6cf-4609-a70a-fe5d0b5ecc00
Faulting package full name: 
Faulting package-relative application ID:

**Comment by riQQ** [comment]
Please provide the files. Error code hints at this: http://stackoverflow.com/questions/4367664/application-crashes-with-internal-error-in-the-net-runtime.

**Comment by Ohdrin** [comment]
[Error 1.zip](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/216020/Error.1.zip)

**Comment by riQQ** [comment]
Can you look for these:
>Attached files:
C:\Users\Drew\AppData\Local\Temp\WER2D6F.tmp.WERInternalMetadata.xml
C:\Users\Drew\AppData\Local\Temp\WER3947.tmp.appcompat.txt
C:\ProgramData\Microsoft\Windows\WER\Temp\WER3977.tmp.dmp
C:\Users\Drew\AppData\Local\Temp\WER3A91.tmp.WERDataCollectionFailure.txt

>These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Hearthstone Deck_8f553c4271412cb961d37afe3eb217f46b0d81_102a5675_225a3f8f

**Comment by Ohdrin** [comment]
Here's all of them from today.

[AppCrash_Hearthstone Deck_8f553c4271412cb961d37afe3eb217f46b0d81_102a5675_11ceca03.zip](https://github.com/Epix37/Hearthstone-Deck-Tracker/files/216065/AppCrash_Hearthstone.Deck_8f553c4271412cb961d37afe3eb217f46b0d81_102a5675_11ceca03.zip)

**Comment by riQQ** [comment]
I'm sorry, i need this one, too:
> C:\ProgramData\Microsoft\Windows\WER\Temp\WER3977.tmp.dmp

**Comment by Ohdrin** [comment]
There's nothing in that directory it looks like.

**Comment by riQQ** [comment]
Turn on Windows Error Reporting: Create this registry key `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps`, reproduce the crash and then upload the crash dump from `%LocalAppData%\CrashDumps`.
By deleting the registry key, crash dump creation is turned off again.

**Comment by sdbds** [comment]
try to uninstall net 4.6 and install 4.5.
when i in win8.1, with net 4.6，i find some bugs with it。

**Comment by Epix37** [comment]
Closing for lack of response.
