### ISSUE TITLE
Syncing feature request

### ISSUE THREAD

**Issue by Palaryel** [HearthSim/Hearthstone-Deck-Tracker#2347]
I run 2 instances of HDT, one on my desktop, and one on my laptop. However, syncing decks between the two is a bit of a nightmare. The only good solution so far is to manually transfer all the config files between the two installations before running the respective instance. However, this turns to be quite annoying when you juggle between the 2 machines often (also, regardless of how you sync - except manually transfering files - the win-loose stats are machine specific). Note that I'm only asking for this since deleting lists manually from Hearthstats can only be done 1 by 1, which is another nightmare xD

In regards to the above I'd like to kindly ask for a new feature to be added under the Hearthstats menu:
Delete all decks on Hearthstats that are not currently present in the application.

Such a feature would enable a person to only receive the exact same decklists from Hearthstats that are present in the HDT instance where from the deletion request was issued.

Alternatively, allowing the config files to be hosted and pulled from an online server (especially if that could work with Google Drive, DropBox etc...) might be an even better solution (but more complicated to implement).

**Comment by GaryKing** [comment]
How about keeping the config files in Dropbox and then creating a Windows symlink from the original HDT config location to the Dropbox location, so HDT can't tell the difference?

**Comment by Palaryel** [comment]
Awesome idea, for some reason I never think of symlinks outside of Linux operating systems xD Symlinked HDT config folder to Google Drive folder, it seems to be working, I'll check how the sync goes when I'm home ^^

**Comment by Palaryel** [comment]
Working flawlessly thanks for the tip!
