### ISSUE TITLE
New Font / Theme?

### ISSUE THREAD

**Issue by managaming** [HearthSim/Hearthstone-Deck-Tracker#2350]
Hey!

Your new Theme looks very good, u did a nice job since the release of HDT. But ... which Font did u used for the new Theme? I wanna use it for some Layouts too.

Thanks.

**Comment by Hydrox6** [comment]
Pretty sure it's Chunkfive https://https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/Hearthstone Deck Tracker/Resources/Chunkfive.otf

**Comment by Epix37** [comment]
Yes, it's [ChunkFive](https://www.fontsquirrel.com/fonts/ChunkFive).
