### ISSUE TITLE
Flame Leviathan visible in deck/hand when not drawn

### ISSUE THREAD

**Issue by Repter** [HearthSim/Hearthstone-Deck-Tracker#2351]
Today I played against mage. And when he played Gorillabot and chose the card. I saw in his deck that it was Flame Leviathan. It is kinda cheating. And totaly not a thing you can do with your pen and a paper.
P.S. Sorry for my English if there are mistakes.

**Comment by Epix37** [comment]
This is a bug in the game logs, Flame Leviathan is always revealed even when not drawn.

**Comment by jleclanche** [comment]
This is an issue with Blizzard. They are aware of it.

You can actually see Flame Leviathan if you look at the sidebar.

Closing wontfix.

**Comment by culinko** [comment]
The issue in question tracked at hs-bugs: https://github.com/HearthSim/hs-bugs/issues/19.
