### ISSUE TITLE
Issue updating to latest version

### ISSUE THREAD

**Issue by MeisterNeefs** [HearthSim/Hearthstone-Deck-Tracker#2352]
After trying to download the latest version I get an error message 'there was a problem updating to the latest version'. Any advice what I sould do to solve this?
![hs tracker update error](https://cloud.githubusercontent.com/assets/18537482/14615249/09cfdd0c-05a5-11e6-8fee-fd80f0b41871.png)

**Comment by Epix37** [comment]
- Download the latest release here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases
- Overwrite your current installation with the new files
