### ISSUE TITLE
Hearthstone install directory not found - HELP PLEASE

### ISSUE THREAD

**Issue by Swagganomics** [HearthSim/Hearthstone-Deck-Tracker#2353]
Found a similar post but it didnt have my exact issue.

Basically when I open HDT I get a message: Hearthstone install directory not found

Now on another post someone suggested: "Try setting the patch via options > tracker > settings > set hearthstone path"

I tried this... however my **I dont HAVE hearthstone as a program anywhere on my computer. I have to launch it through Battlenet... then click on heathstone.**

I tried installing HS directly but cant seem to do it.

Can someone please help so I can use HDT? 

Thanks!

**Comment by riQQ** [comment]
In you Battle.net Client, click the symbol at the top left and select the menu entry `Settings`. In the settings dialog, select the `Game Install/Update` tab. There, you'll find your Hearthstone path.

**Comment by Swagganomics** [comment]
Wow thanks man! Helped a lot

Kind Regards,

Riley I
