### ISSUE TITLE
Sync on HearthStats

### ISSUE THREAD

**Issue by bombek92** [HearthSim/Hearthstone-Deck-Tracker#2355]
Hi!

So I use only HDT on one PC, and I mainly use it for arena statistics. I've got two issues with Sync option and HearthStats. There is no reward saved there and one arena is 'splitted' I mean it shows 7-2 and 2-1 as seperate runs even though it was single one - 9-3. 

Should I relay on my backups of folder which I do every now and then and completly leave the sync option behind?

**Comment by culinko** [comment]
@Epix37 Looks like #1286?

**Comment by bombek92** [comment]
@culinko I think it's similar problem. What about the missing rewards on website?

**Comment by riQQ** [comment]
See #2217.
