### ISSUE TITLE
Getting Arena Stats/Decks back

### ISSUE THREAD

**Issue by TheRedViper1** [HearthSim/Hearthstone-Deck-Tracker#2356]
So I just had to "refresh" my Windows 8.1 , meaning it reset all settings etc like it was brand new , but still kept all my files in place. So I had to reinstall HDT and got my Constructed Decks/Stats back through Hearthstats-Sync, but not my Arena runs. Is there a way to get them back? I still have the "old" folder of HDT before the refresh.

**Comment by Epix37** [comment]
Arena runs are only uploaded. See #1691.

There's no data saved in the installation folder. If you have backup of the "%AppData%/HearthstoneDeckTracker" folder, you can restore that, yes.
