### ISSUE TITLE
Discovered cards do not appear in the opponent's deck list

### ISSUE THREAD

**Issue by GaryKing** [HearthSim/Hearthstone-Deck-Tracker#2357]
I'm using the latest HDT version (I'm on the beta channel). Since a week or two ago, I've noticed that discovered cards usually don't appear in the opponent's deck list. I'm not sure if they don't appear 100% of the time, or just some of the time; I can't recall.

I have attached a log file from my most recent game. It's an Arena game. The opponent played at least two discover cards; there might have been one or two more, I don't remember. They definitely played two Tomb Spiders, which discovered Malorne and Maexxna. Malorne appeared in the opponent's deck list once he was sent back to the opponent's deck due to his Deathrattle.

[Game log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/227114/Game.log.txt)

**Comment by Epix37** [comment]
See #2286
