### ISSUE TITLE
Export to hearthstone isn't working!

### ISSUE THREAD

**Issue by chupstickzz** [HearthSim/Hearthstone-Deck-Tracker#2359]
Whenever i use the export to hearthstone feature it is just searching for the cards but not adding them to my deck. In the end it says i don't have the cards.

https://gyazo.com/b583d6eacec192f7c939a9872c624317

**Comment by Epix37** [comment]
Try running HDT as admin.

Otherwise see here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#exporting
