### ISSUE TITLE
Deck list was corrupted

### ISSUE THREAD

**Issue by kevschow** [HearthSim/Hearthstone-Deck-Tracker#2360]
http://pastebin.com/wzQgcUaM

**Comment by culinko** [comment]
Could you upload your current PlayerDecks.xml? You can find them in (%AppData%/Roaming/HearthstoneDeckTracker/). As a workaround for fixing the issue, you can copy your old PlayerDecks.xml from the Backups directory.

**Comment by Epix37** [comment]
More specifically: go to `%AppData%/HearthstoneDeckTracker` (Win+R, paste) and delete the `PlayerDecks.xml` file. If there is a `PlayerDecks_backup.xml`, rename it to `PlayerDecks.xml`. Otherwise go to the "Backups" folder and replace it with the `PlayerDecks.xml` from the latest zip.

**Comment by kevschow** [comment]
This is the one created after the corruption but I'm not sure how helpful it could be . . there is one called PlayerDecks_corrupted.xml

http://pastebin.com/GryVnAjf

**Comment by culinko** [comment]
Were you able to resolve the issue with your backups?
