### ISSUE TITLE
Show Overlay with Note Dialog

### ISSUE THREAD

**Issue by Elitesparkle** [HearthSim/Hearthstone-Deck-Tracker#2363]
When a game ends and you have disabled the overlay while in menu, the note dialog pops up but the overlay desappears.

I suggest to show the overlay while the note dialog is visible since sometimes we could need to look at it before taking notes.

It would be fine to have an option to toggle this feature.

**Comment by culinko** [comment]
I'd love this feature. Either automatically showing the overlay, or a button called "Show Opp. Deck".

**Comment by andburn** [comment]
The [EndGame plugin](https://github.com/andburn/hdt-plugin-endgame) can do this now, see the [Readme](https://github.com/andburn/hdt-plugin-endgame/blob/master/README.md) for more.

![image](http://i.imgur.com/WAlfayX.png)

**Comment by azeier** [comment]
Implemented with #2775
