### ISSUE TITLE
Disconnection Management

### ISSUE THREAD

**Issue by Elitesparkle** [HearthSim/Hearthstone-Deck-Tracker#2364]
In the version 0.13.13 release notes you say:

> Fixed an issue where games would not be recorded when re-joining after disconnects.
> Joining in-progress games (reconnected or spectator) now correctly displays the decks.

Actually every time I get a disconnection the tracker acts as if the game ended, in fact the note dialog pops up and the overlay desappear.

After that, the overlay stays hidden even if I close the note dialog.

**Comment by Epix37** [comment]
I need the [hdt log](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues), Power.log and Net.log (`Hearthstone/Logs`) of this.

**Comment by Elitesparkle** [comment]
At the turn 3 I forced a disconnection to get the following logs.

I noticed that as soon as the game ended the reconnection, the overlay changed from game version to menu version because the Gold progress bar was visible during the rest of the match.

After some time I used the hotkeys to call a deck reset, but it just forced the note dialog to pop up.
Nothing else happened.

I tried also to disable the automatic deck selection, change the deck manually and activate the no deck mode, but it didn't work. I just got the note dialog again and again.

At the end, in the stats window, I've got a game with the correct duration and the note I wrote in the latest note dialog.

Calling the latest replay, though, the history was the following:

> **Turn 3**
>
> **Player**
> Draw: Azure Drake
> Draw: Sludge Belcher
> Draw: Loatheb
> Draw: Mad Scientist
> Play: Mad Scientist
> Attack: Entity 24
> Draw: Frostbolt
> Draw: Frostbolt
>
> **Opponent**
> Draw: Unstable Portal
> Play: Unstable Portal
>
> **Player**
> Play: Fireblast
> Play: Fireblast

Those replay information are wrong.
As you can see from the logs, I played Mad Scientist on my turn 2 and used Fireblast on my turn 3.
Additionally, it's impossible a player used Hero Power 2 times in the same turn.

Log:
http://pastebin.com/8jQ7sKVc

Power.log:
http://pastebin.com/b1jZwwSd
http://pastebin.com/XQZxwAc5

Net.log:
http://pastebin.com/8gATxWKs

**Comment by Epix37** [comment]
Oh, this might be fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/445101bbbf40bef9016a6a6ebb49a8cc98431b6a

Try the 14.3 pre-release: https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/tag/v0.14.3

**Comment by Epix37** [comment]
Is this still an issue?

**Comment by Elitesparkle** [comment]
Yes.

**Comment by Epix37** [comment]
Let me know if this is still an issue with v0.15.4.
