### ISSUE TITLE
Still can't update  past vesion 0.13.17

### ISSUE THREAD

**Issue by JohnBonoSmith** [HearthSim/Hearthstone-Deck-Tracker#2365]
Haven't been able to update since 0.14.0 came out.  When the auto-update fails and prompts me to update manually, I download the latest version (0.14.1), and try running every .exe, but nothing actually updates deck tracker.  Without any instructions anywhere, I don't want to risk having to re-make/re-import all of my decks.

**Comment by JohnBonoSmith** [comment]
So it was convenient enough to batch-export my regular decks, then my archived decks to a single folder; so it wasn't that painful to test.  It was indeed as simple as just copying files into the existing folder; and it kept my decks alive... somewhere, so I didn't have to export.

**Comment by riQQ** [comment]
Your data is stored at `%APPDATA%\HearthstoneDeckTracker`.
