### ISSUE TITLE
Bug: two copies of the same secret

### ISSUE THREAD

**Issue by Weypare** [HearthSim/Hearthstone-Deck-Tracker#2367]
![screenshot 3](https://cloud.githubusercontent.com/assets/17096718/14785495/c00466b6-0b03-11e6-9f2c-2e9aee773353.png)
![screenshot 4](https://cloud.githubusercontent.com/assets/17096718/14785496/c00a1e44-0b03-11e6-8d74-4c0d4205875d.png)

**Comment by Epix37** [comment]
If it worked any different, you would not able to tell which what the first secret was after the second was played. See #2338 for further explanation. 

Not a bug.
