### ISSUE TITLE
Constructed stats, bugs

### ISSUE THREAD

**Issue by GaryKing** [HearthSim/Hearthstone-Deck-Tracker#2371]
When I go to Constructed -> Matches, Arena and Brawl matches also appear. Since Arena has their own page, perhaps at least excluding those? Although I guess at worst, I just filter for Ranked games only then.

When I go to Custom Season, it automatically sets "Season 1 to 25". It should allow us to leave the second number empty, to indicate up to the current season, especially since I can't remember what season number the current one is. Also, it'd be nice to be able to set "Season -1 to 0" for the previous season to the current one, for instance, or "Season -2 to -1", etc.

**Comment by Epix37** [comment]
I though I excluded arena decks. Oops, fixed that.

Brawl showing up in constructed is working as intended. For all intents and purposes, those are constructed decks/games.

If you try to enter a too high season (e.g. 30) it will tell you what the current maximum number is.

No to the rest for now.
