### ISSUE TITLE
Export Screenshot Improvement

### ISSUE THREAD

**Issue by Elitesparkle** [HearthSim/Hearthstone-Deck-Tracker#2374]
When you try to export a screenshot, using the menu or using the hotkeys, a windows pops up.

First of all, the window doesn't have any Cancel button.

In addition, there should be a way to save a default behaviour so that when I use the assigned hotkey to save a screenshot I won't need to go back to desktop just to click Save Only.

In order for this to work, you need to set a default path where to save screenshots else a window will still appear.

The window that shows the uploading is in progress needs a Cancel button as well.

When the hotkey is used to save a screenshot and the default behaviour selected is Upload, the window that shows the URL will be a bit problematic since it will force you to go back to desktop, so you could store all URLs in a file and show them when Hearthstone is closed or when the user choose to view them from the menu.

Even if less important, can you let us login to Imgur so that any uploaded image will be accessible from our profile?

**Comment by Epix37** [comment]
Added the cancel button. 

Not too sure on the rest though. E.g. if you set the default operation to 'save', you would have to look for an option to be able to upload it. The 'upload' default behaviour you describe is another example of this just not working well. Don't I think this is a good idea.

I have nothing against being able to set an imgur account, but it's not something I have time to do. If anyone wants to PR - feel free.

**Comment by Elitesparkle** [comment]
> Added the cancel button.

Nice.

> Not too sure on the rest though. E.g. if you set the default operation to 'save', you would have to look for an option to be able to upload it. The 'upload' default behaviour you describe is another example of this just not working well. Don't I think this is a good idea.

If I click Save to store a screenshot in a folder, it means I don't want to update it, that I will do it manually or using a different site.

Even if you don't want to do what I said about the upload, I think it would still be a good idea to let us set Save as a default operation to save the screenshots in a given path. Save & Upload and Upload will stay the same.

Just add a checkbox in the same window (e.g "Remember this selection.") and another one in the options so that users can disable it when they change mind.

> I have nothing against being able to set an imgur account, but it's not something I have time to do. If anyone wants to PR - feel free.

I know, I know.

**Comment by azeier** [comment]
Added new screenshot dialog with v1.3
