### ISSUE TITLE
Deck Exporting

### ISSUE THREAD

**Issue by Elitesparkle** [HearthSim/Hearthstone-Deck-Tracker#2376]
I've just tested deck exporting on v0.14.3 Pre-Release.

It works only if you export at 150 ms, else it will miss the first field of the sets menu because of the slow animation.

You should slow down the clicks related to sets filters, even when the selected speed is faster than 150 ms for the rest of the exporting operation.

Keep in mind that when Standard will rotate they will probably add a new button in the sets menu.
In that case you'll need to check if the Wild button will be where the Standard one is now. If not, you'll need to click a bit lower.

The rest is working fine.

I'll uncheck Clear filters in the meanwhile and clear them manually.

**Comment by Epix37** [comment]
Has been fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/808705e8b6caf2143497ab13e631e57549596685

**Comment by Elitesparkle** [comment]
When I tried at 60 ms it clicked the button that suggests cards. Check it.

**Comment by Epix37** [comment]
Well, that's why the speed options exist I guess. Works perfectly fine for me even at 20ms.
