### ISSUE TITLE
How to set a standard deck just in the Standard format ?

### ISSUE THREAD

**Issue by everchump** [HearthSim/Hearthstone-Deck-Tracker#2377]
Though a standard deck can be played in the  Wild format，but I just want it only disappear in the Standard format.  

You know，I won't play a standard deck in the Wild format.

Now the HDT disappear a standard deck in both formats.

![disappear in the wild format](http://i66.tinypic.com/2585s06.jpg)

**Comment by Epix37** [comment]
uncheck `Sort/Filter (button right next to wild) > include 'standard' decks in 'wild'`

**Comment by everchump** [comment]
Oh, thanks again.
