### ISSUE TITLE
Hunter Tracking Bug

### ISSUE THREAD

**Issue by Doomelf** [HearthSim/Hearthstone-Deck-Tracker#2378]
When I use Tracking the deck tracker does not remove the chosen card from the overlay.

There is also a problem when playing the Golden Monkey. When played it transforms the remaining cards in deck to legendaries and so the overlay should show in no deck mode since the normal cards are "removed".

**Comment by Epix37** [comment]
Please provide screenshots/logs for the tracking issue. See here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ

Switching to no deck mode is not a good idea. If anything, the list should show [Legendaries (7)]. See #961.

**Comment by Doomelf** [comment]
Here is the log: http://pastebin.com/bFaqiu55

As for screenshots:

![1](https://cloud.githubusercontent.com/assets/12450654/14827338/825c5278-0bea-11e6-8248-7dce4506edde.JPG)
![2](https://cloud.githubusercontent.com/assets/12450654/14827344/87b5c8b2-0bea-11e6-9b3e-306a2cbea1b8.JPG)
![3](https://cloud.githubusercontent.com/assets/12450654/14827349/8cbf82f8-0bea-11e6-8f50-f6ee714c0178.JPG)
![4](https://cloud.githubusercontent.com/assets/12450654/14827351/9132e8de-0bea-11e6-92ea-2b1b9f2558a1.JPG)
![5](https://cloud.githubusercontent.com/assets/12450654/14827357/956bd4ba-0bea-11e6-8ee8-fccdb2f53db4.JPG)
![6](https://cloud.githubusercontent.com/assets/12450654/14827358/990f1e56-0bea-11e6-9219-df3e21c85f1a.JPG)
