### ISSUE TITLE
Crash on startup with new version (Release v0.14.4)

### ISSUE THREAD

**Issue by mudzereli** [HearthSim/Hearthstone-Deck-Tracker#2379]
Just started getting this with the new version. Tried clearing my %appdata%\Hearthstone Deck Tracker folder, and that didn't help either. 

![HDT Crash](http://i.imgur.com/T9KjAEM.png)

**Comment by Epix37** [comment]
See here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#hdt-is-not-starting--crashing-at-start-up-how-do-i-fix-this

**Comment by mudzereli** [comment]
- Do you have Windows Vista or higher and .NET Framework 4.5 or higher?
**yes**
- Have you extracted all the files? Don't start HDT from a zipped folder.
**yes**
- Try reinstalling / repairing your .NET Framework installation
**Have .NET 4.5. and reinstalled it with the same issue**
- Is there a log entry in the windows event viewer (Windows start menu > control panel > management tool > event viewer > windows log > application)
**yes, related to UIAutomationCore.dll**

Apparently this issue happens on Win 7 64 bit system with some Flight Simulator as well. I used this fix:

http://www.avsim.com/topic/273341-heres-the-apparent-fix-to-fsx-crashing-win-7-x64/

**Comment by Epix37** [comment]
:+1:
