### ISSUE TITLE
Arena Rewards Update

### ISSUE THREAD

**Issue by Elitesparkle** [HearthSim/Hearthstone-Deck-Tracker#2380]
We are not able to select Whispers of the Old Gods packs as Arena reward.

I think we have chance to win a third pack, but I can't confirm this, so you could need to add a third field for packs won.

**Comment by Epix37** [comment]
Added the missing pack option. Thanks.

Source on the 3rd pack? Patch notes only say this: 
> Additionally, you are slightly more likely to receive a second card pack from a different Standard set.

**Comment by Elitesparkle** [comment]
> Added the missing pack option. Thanks.

You are welcome.

> Source on the 3rd pack? 

I don't have, that's why I said I can't confirm that, but someone has got a second pack at as low as 3-3.

**Comment by Epix37** [comment]
yeah, that's exactly what the patch notes say. I doubt you can get a 3rd pack.

**Comment by Elitesparkle** [comment]
> yeah, that's exactly what the patch notes say. I doubt you can get a 3rd pack.

You are right. I did a wrong assumption.

**Comment by Epix37** [comment]
Fixed with v0.14.5
