### ISSUE TITLE
Add Yogg-Saron spell counter and C'Thun counter

### ISSUE THREAD

**Issue by aleksg** [HearthSim/Hearthstone-Deck-Tracker#2382]
It would be great to have an option to enable a spell counter, in order to know when to play Yogg-Saron.

**Comment by Epix37** [comment]
This, along with a counter C'Thun is planned for the next update - probably tomorrow.

**Comment by aleksg** [comment]
Awesome!
Keep up the great work guys. The deck tracker is a great tool!

**Comment by Epix37** [comment]
Added with v0.14.5
