### ISSUE TITLE
No Overlay hide on Friends Menu Opening

### ISSUE THREAD

**Issue by gabessdsp** [HearthSim/Hearthstone-Deck-Tracker#2383]
Just like the title states the overlay is not hidden if I open my friends menu, I searched through the optiuons because I know some were reset and also couldn't find it. Is it still there/when will it be back?

**Comment by Epix37** [comment]
`options (advanced) > overlay > interactivity`

**Comment by gabessdsp** [comment]
ahh thank you! I forgot about the advanced options checkbox
