### ISSUE TITLE
HearthPwn importing not working

### ISSUE THREAD

**Issue by Epix37** [HearthSim/Hearthstone-Deck-Tracker#2384]
Fails at line 58, "card count node" has changed. `LastChild` is now "You don't have this card in your collection"

**Comment by emzero** [comment]
I can confirm.

I get the following message:

Error
Could not load deck from specified url 

Url is: http://www.hearthpwn.com/decks/501396-standard-priest-cthun-opti

**Comment by LOGICserum** [comment]
Same here
