### ISSUE TITLE
Arena Reward chooser doesn't include WotOG deck option.

### ISSUE THREAD

**Issue by chriskarel** [HearthSim/Hearthstone-Deck-Tracker#2385]
After the completion of an Arena run, you get presented with an award popup.  Part of that is to choose what type of deck you received.  "Whispers of the Old Gods" is not presented as an option, despite it being a guaranteed drop.

**Comment by ser3nitynow** [comment]
The new cards also aren't being detected when entering in individual card rewards.

**Comment by Epix37** [comment]
Duplicate #2380
