### ISSUE TITLE
HDT thinks a game is Standard, if I play a Standard deck in Wild

### ISSUE THREAD

**Issue by GaryKing** [HearthSim/Hearthstone-Deck-Tracker#2390]
If I play a Standard deck in Wild, HDT still thinks the game is a Standard game.

**Comment by Epix37** [comment]
As far as I can tell, there is no clear way to tell the format from the logs. 

Currently it's purely based on cards played / deck selected. If either the deck is not standard viable or any non-created wild card was revealed, it's set to wild.

The two mediocre options I can think of right now:
- use image recognition in the `TOURNAMENT` screen
- use the asset log (I would prefer not to)

**Comment by Epix37** [comment]
Fixed with v0.15
