### ISSUE TITLE
Standard Ranked Games are saved as Casual

### ISSUE THREAD

**Issue by TheRedViper1** [HearthSim/Hearthstone-Deck-Tracker#2392]
Not the biggest issue since you can quickly change it but I thought I might note it here. Possible solution?

**Comment by Epix37** [comment]
Works fine for me. Are wild ranked games recorded as ranked for you? Either way see if any of this helps: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#ranked

**Comment by TheRedViper1** [comment]
I feel stupid for not checking the FAQ first, thought it had to be something with the new mode, thank you :)

**Comment by Epix37** [comment]
:+1:
