### ISSUE TITLE
Importing decks from web gives error

### ISSUE THREAD

**Issue by samuri55** [HearthSim/Hearthstone-Deck-Tracker#2395]
I tried importing a deck from hearthpwn (ex.http://www.hearthpwn.com/decks/480062-have-you-heard-about-our-lord-saviour-yogg-saron). It gives me an error that saids "could not load deck from a specified url". Im currently using version 0.14.4

**Comment by waibcam** [comment]
yes same for me.

**Comment by Epix37** [comment]
https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2384

Leaving this one open for now so we don't get 10 more of these :).

**Comment by waibcam** [comment]
ahah good idea :) Thx Epix37 !

**Comment by ZaaaM** [comment]
guys plz fix it. cant import from hearthpwn.com !!!!!!

**Comment by Epix37** [comment]
There will be an update in a few hours.

**Comment by Epix37** [comment]
Fixed with v0.14.5
