### ISSUE TITLE
Request： Add Deck Title , Deck Tag, Dust cost ,etc. to Deck Screenshot

### ISSUE THREAD

**Issue by everchump** [HearthSim/Hearthstone-Deck-Tracker#2396]
![deck](http://i65.tinypic.com/2v9w1g6.jpg)

The pic is modified from the topdecks (URL [HERE](http://www.hearthstonetopdecks.com/deck-builder/#?deck_id=21913)).

May you add an option to add these stuffs disappearing in the screened deck pic ?

- Deck Title：Deck Name & Hero background pic. It's better if  you can select the hero bg pics.    
- Deck Tag(Date/Note）：You can add a tag or date here ，for example，“Midrange".  
- Dust Cost：Dust cost of the deck，as a new player, it's useful.

**Comment by Elitesparkle** [comment]
Nice idea, but keep it optional, please.

**Comment by andburn** [comment]
This is pretty cool idea.
@Elitesparkle why would you want it optional out of interest, specifically when would the extra info interfere with the way you use the screenshot?

**Comment by Cu8eR** [comment]
Really good idea! and useful!

**Comment by Elitesparkle** [comment]
I have some ideas about things to add:
- Format: based on cards in it, show if the deck is Standard legal or not;
- Sets: as you do in the tracker, show an icon for each cards set needed to build it;
- Rank: show the best Rank you have reached with that deck version;
- Wins/Losses (Percentage): show how many games you have won and lost, win rate included.

> @Elitesparkle why would you want it optional out of interest, specifically when would the extra info interfere with the way you use the screenshot?

Sometimes you don't need to show too many information (e.g. you don't know the deck author, you didn't give a name to your new deck yet, you don't want to show your Rank and/or win rate).
