### ISSUE TITLE
Doomcaller battlecry

### ISSUE THREAD

**Issue by MrZebrisko** [HearthSim/Hearthstone-Deck-Tracker#2397]
In scenario where C'thun is dead and you play Doomcaller to shuffle C'thun into your deck 2nd C'Thun won't show in the deck no idea if bug or something

**Comment by Epix37** [comment]
fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/fbdc37e3fed808baedea41bde5c08898fb033021

**Comment by Epix37** [comment]
Fixed with v0.14.5
