### ISSUE TITLE
Editing opponents deck doesn't show class cards

### ISSUE THREAD

**Issue by MACDARK007** [HearthSim/Hearthstone-Deck-Tracker#2398]
After **importing my opponents deck,it doesn't show class cards** when using the search mechanic to add any of them,it's just showing neutral ones ... by the way before anyone say _check the filters_,they are by default and the class icon is missing in the list so there must be any problem.

![captura](https://cloud.githubusercontent.com/assets/11761329/14862427/bbf16da0-0c87-11e6-82bb-a216abfc12d6.JPG)

**Comment by Epix37** [comment]
This was fixed with v0.14.5.

However, you have to import the decks again, as they were saved without a class.

**Comment by MACDARK007** [comment]
Fine Sir,then excuse me just was trying to drag some decks just now and this Happened. Thanks for let me know.Have a nice day.
