### ISSUE TITLE
Spell counter doesnt reset

### ISSUE THREAD

**Issue by brostone51** [HearthSim/Hearthstone-Deck-Tracker#2399]
After my first game with the new spell counter, it didnt reset to 0

**Comment by Epix37** [comment]
Oops! That's what happens when you (me) restart HDT at least once every game :P.

Fixed with v0.14.6: https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/tag/v0.14.6

**Comment by brostone51** [comment]
Thanks!
