### ISSUE TITLE
Yogg-Saron Spell tracker!

### ISSUE THREAD

**Issue by xMoltrex** [HearthSim/Hearthstone-Deck-Tracker#2401]
So apparently Yogg-Saron spell tracker is bugged. The bug is that the spell number does not reset after the game. What it does instead is that the starting number that should be 0 is actually the number left off from the last game and i doesn't fix itself by restarting a game or a deck tracker client. Tell If you need any more information like screenshot or a logs.

**Comment by jleclanche** [comment]
Dupe of #2399

**Comment by xMoltrex** [comment]
Oh sorry didn't see it i guess :/
