### ISSUE TITLE
C'Thun counter should not disappear when C'Thun dies

### ISSUE THREAD

**Issue by GaryKing** [HearthSim/Hearthstone-Deck-Tracker#2402]
Doomcaller can still bring it back to life, and effects will still proc based on his Attack.

**Comment by Epix37** [comment]
- It will re-appear if C'Thun is added to the deck again.
- If C'Thun was played, in 99% of case you can safely assume any effect will trigger.
- You can set it to always on under `options > overlay > player/opponent`.

**Comment by GaryKing** [comment]
If I set it to Always On, though, then does it still appear if I don't even have C'Thun in my deck?

**Comment by Epix37** [comment]
Yes, always on is always on.

**Comment by Epix37** [comment]
It might be fine to keep it visible while C'Thun is on board/dead. Not sure.

**Comment by GaryKing** [comment]
Okay then I think "Always" should just keep it visible only when C'Thun is in your deck, regardless of whether it's alive or dead. Also, "Always" should also keep the C'Thun counter visible even before I play my first C'Thun minion, because I notice that the counter doesn't appear until then.

**Comment by riQQ** [comment]
The counter shouldn't appear if there's no C'Thun in the deck.

**Comment by GaryKing** [comment]
I just played a game where I played C'Thun with zero buffs, as a vanilla 6/6. This was with a Renolock deck, so it is possible to never draw any C'Thun cards, however unlikely that is. I played him because the opponent was playing Zoolock and filled the board with tentacles, so even 6 missiles was good enough in that situation. 

So there are definitely times when you play C'Thun with no buffs. And so it gets weird when you have a game where he is played, and the counter doesn't even appear when he's played. Which is why the counter should immediately appear when HDT recognizes that my deck is a C'Thun deck.

**Comment by GaryKing** [comment]
The C'Thun counter should absolutely remain on the board during the entire game, for the player if C'Thun is detected in their deck, and for the opponent if they have played at least one C'Thun buff card, or C'Thun itself.

I say this because I just had a game vs. a Priest who entombed my C'Thun, then played their own C'Thun, I killed that, then the counter disappeared. Then they played their second C'Thun, but the counter was gone by then. Let's say the C'Thun counter was at 16, and I was at 15 health with an empty board, then I could have armored up as a Warrior to prevent lethal, for instance.
