### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by pcg79** [HearthSim/Hearthstone-Deck-Tracker#2403]
I have been unable to update for the past two updates.  Both times look like this:

>Creating temp file directory
Downloading latest version... 23474/23474KB (100%)
Extracting files...
Writing AForge.dll
Writing AForge.Imaging.dll
Writing AForge.Math.dll
Writing De.TorstenMandelkow.MetroChart.dll
Writing Garlic.dll
Writing HDTHelper.exe
Writing HDTUninstaller.exe
Writing HDTUpdate.exe
There was a problem updating to the latest version. Pressing any key will direct
 you to the manual download.

I'm not sure if I've done something wrong but this did used to work.

**Comment by Epix37** [comment]
Try downloading the latest release ([here](https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/tag/v0.14.6)) and **not** overwriting the existing files. You will keep all your data.

**Comment by pcg79** [comment]
That seems to have done it.  Today's update worked fine.

Thanks for your help.
