### ISSUE TITLE
Problems with HDT and no-deck mode

### ISSUE THREAD

**Issue by GaryKing** [HearthSim/Hearthstone-Deck-Tracker#2404]
There are a few problems in HDT and no-deck mode. I encountered these when I played the Brawl.

1. I started a Brawl game. HDT doesn't show the dialog that asks me if I want to change to no-deck mode because the cards do not match. I have to manually enable no-deck mode.
2. In Brawl, cards that I draw are not added to my deck list. However, cards that I mulliganed away are in the deck list (and greyed out), and they disappear when I draw them.

**Comment by Epix37** [comment]
1. was "auto" actually enabled?
2. #2319 / #961

**Comment by GaryKing** [comment]
Yep "auto" was enabled at the time. And I always check that it's enabled.

**Comment by Epix37** [comment]
Can you reproduce it?

**Comment by GaryKing** [comment]
Yeah I just played Brawl just now, and still HDT doesn't ask for a deck. I included a log.
[Game log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/239463/Game.log.txt)

**Comment by GaryKing** [comment]
So if I want cards to appear in my deck list, then I have to enable the "show obtained cards in my deck" setting? The reason I keep that off is because it clutters up my deck list way too much, when I want to see how many outs I have for draws, etc. Especially when playing Renolock, where the deck list is already long, adding more cards is a problem. 

So that's why I think it's best the way it was before, where if you're in no-deck mode and "show obtained cards in my deck" is disabled, then cards still appeared, because they aren't obtained. Unless they still come from Discover, of course.

**Comment by Epix37** [comment]
Oh, I see why the brawl thing happens. All cards in the current brawl are created after the initial cards in the deck and therefore ignored when it comes to auto deck detection. 

Not sure how to fix that. This is the cause of both of these problem though.

**Comment by GaryKing** [comment]
Okay if it's just this one brawl then that's fine. 

I'll try and test no-deck mode when I have time, by playing a deck that isn't in HDT.

**Comment by Epix37** [comment]
Turns out I actually managed to fix both of those problems now!

**Comment by GaryKing** [comment]
#1 is not fixed. #2 is fixed.

Playing the current brawl still doesn't ask me if I want to change to no-deck mode. But brawl cards now do appear in my deck list if I'm in no-deck mode.
