### ISSUE TITLE
Playing C'Thun card without C'Thun in their deck.

### ISSUE THREAD

**Issue by FlamingFox911** [HearthSim/Hearthstone-Deck-Tracker#2408]
Specifically, if the person who plays the card does not have C'Thun in their deck, there shouldn't be a counter for it. What's happening right now is it is applying the counter when C'Thun doesn't even exist.

**Comment by jleclanche** [comment]
@Epix37 You should track `RITUAL` blocks instead of cards played.

**Comment by Epix37** [comment]
I currently track the `PROXY`. Not sure why it would be created.

**Comment by jleclanche** [comment]
Could it be there is a proxy even if no cthun? Do you have a log of playing a cthun card without cthun?

**Comment by Epix37** [comment]
The proxy is not created until a `RITUAL` card is played. I assumed it would not create the proxy if there was no C'Thun. No logs yet.

**Comment by Epix37** [comment]
Well crap, this is from a game without C'Thun in the deck: http://pastebin.com/VnXtN8iL

Kind of interesting though, this means if you obtain C'Thun by other means later in the game, it will have all the buffs regardless.

As for this issue: Preventing the counter from showing, if a active deck without C'Thun is used should solve most cases. I can't think a way to prevent it from showing when playing without a deck or if the opponent has no C'Thun.

**Comment by Epix37** [comment]
Figured it out: `SEEN_CTHUN` player tag only get set when it's revealed, i.e. there is a C'Thun in the deck.
