### ISSUE TITLE
Shifter Zerus is shown as the card he transformed into instead of the actual Zerus.

### ISSUE THREAD

**Issue by mclemente** [HearthSim/Hearthstone-Deck-Tracker#2409]
Just played a game where my opponent played a Shifter Zerus that transformed into a Crowd Favorite, but the tracker only showed Crowd Favorite as a card on his deck.

**Comment by GaryKing** [comment]
Yeah I think it makes more sense for him to appear as himself rather than the card he transformed into, because ultimately I think it's best to know what cards the opponent purposely put in their deck, so we can then deduce why they did it, etc. and try to figure out their game plan.
