### ISSUE TITLE
Overlay

### ISSUE THREAD

**Issue by Fabbruz22** [HearthSim/Hearthstone-Deck-Tracker#2411]
Why my decklist is a windows and not an overlay? so when i press something it disappear?
![immagine](https://cloud.githubusercontent.com/assets/18719510/14885170/4db7dda6-0d4a-11e6-9d95-803484ed929c.png)

**Comment by Epix37** [comment]
Because you have `options > overlay > deck **windows** > player` enabled there.

**Comment by Fabbruz22** [comment]
i have disabled it but now when i start game i can't see the tracker D:

**Comment by Epix37** [comment]
Do this:

1. go to `options > tracker > settings`
2. click `open appdata folder`
3. close HDT
4. delete the `config.xml` file in that folder
5. start HDT again

**Comment by Fabbruz22** [comment]
i have done this, know there is " Use" but when i get in game can't see my deck D:
