### ISSUE TITLE
v0.14.6 Bug with 150 cards when importing with NetDeck chrome addon

### ISSUE THREAD

**Issue by lovelord83** [HearthSim/Hearthstone-Deck-Tracker#2412]
Hello there, 

now with v0.14.6 + NetDeck chrome plugin (version 3.0.7), importing any decks in HDT cause a 150 deck to be created with 120 "NOOOOOOOOOOOO" 's cards on it... Could you please verify it?

Attached original link and bug screenshot:

HDT: v0.14.6
Original link: http://www.hearthpwn.com/decks/504074-legend-12-2-patron-wog
NetDeck chrome plugin version: 3.0.7

![cattura](https://cloud.githubusercontent.com/assets/18720065/14886116/76bbebc0-0d4f-11e6-9454-b8c5e0fbc2f8.PNG)
[Legend 12-2 Patron WoG.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/240518/Legend.12-2.Patron.WoG.txt)

**Comment by Epix37** [comment]
#2386
