### ISSUE TITLE
Hearthstone Deck Tracker.exe getting deleted by malwarebytes

### ISSUE THREAD

**Issue by Steel-Blade** [HearthSim/Hearthstone-Deck-Tracker#2413]
As title.
Since the last update they .exe is getting blocked from malwarebytes as an injector.
False positive or not?
EDIT
Grammar :D

**Comment by jleclanche** [comment]
Where did you download HDT from?

**Comment by Steel-Blade** [comment]
100% from here and I just downloaded again and still has the same problems.

**Comment by MrOmen13** [comment]
Same issue here, i have had HDT installed for months without this happening and then all of a sudden today I see in the MBAM log repeated alerts for it. 

Here is a screenshot: 
![hdt-mbam](https://cloud.githubusercontent.com/assets/18721070/14888015/31fa4faa-0d26-11e6-8b76-03f7b8c539d2.JPG)

**Comment by Steel-Blade** [comment]
That is exactly what I am getting, to lazy to screenshot :)

**Comment by jleclanche** [comment]
It's a false positive, not sure what we can do about it.

**Comment by MrOmen13** [comment]
I have been using MBAM both personal and enterprise for at least 8 years now and I can count on one hand how many times I have seen a false positive. So either your code is infected or the update has some tie in it that MBAM doesn't like. Either way, I will be uninstalling until its fixed. I can't take the chance!

**Comment by Steel-Blade** [comment]
> It's a false positive, not sure what we can do about it.

Contact malwarebytes would be a start I guess.

**Comment by Epix37** [comment]
This is rather strange. Everything, including malwarebytes, shows no detection on virustotal: https://www.virustotal.com/en/file/09a03837d1c327e0595cbada7c74b4a53aae3ab23658a3b28a21381a88c8f3d4/analysis/

**Comment by Epix37** [comment]
I am *very* confused. I downloaded and ran MBAM over v0.14.6 - same thing. *However*, v0.14.5 comes out clean. [__This__](https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/e13e5b51edec01d41e5c92f552392687a024375a) is the difference between v0.14.5 and v0.14.6. One line, resetting one variable. 

Even more confusing: the current dev build also comes out clean.

I idea what this is about, but I uploaded the current build for you guys here: https://github.com/Epix37/HDT-Test/releases/tag/v0.14.6_dev1

Hope you feel better using this one :).

**Comment by Steel-Blade** [comment]
https://github.com/Epix37/HDT-Test/releases/tag/v0.14.6_dev1
Just downloaded this, extract it and still is getting caught by malwarebytes

**Comment by Epix37** [comment]
I ran it 3 times now to make sure I got the right file, nothing. Maybe it still has that filename registered as "bad" on your end? Try removing it from quarantine under `History > Quarantine`

**Comment by donlegacy** [comment]
i got the same thing 

![hdt trojan injector](https://cloud.githubusercontent.com/assets/18722421/14890354/43b483d2-0d30-11e6-961c-3a1cf93d90f6.png)

**Comment by Epix37** [comment]
Is that the correct file? The modified date on the exe should be of today.

**Comment by donlegacy** [comment]
that was the old one, prior to trying out the dev version.  

I just loaded up the dev version without malwarebytes flagging it.  all is well now.

**Comment by Steel-Blade** [comment]
No matter what I do it keeps getting deleted.
I cleared the quarantine, deleted entirely the old folder, I even moved it on another hard drive.
Still getting caught by malware.

**Comment by Epix37** [comment]
Updated to v0.14.7 to hopefully prevent this from happening further.

**Comment by Steel-Blade** [comment]
Job well done :)
Thanks Epix.

**Comment by XanGit** [comment]
Don't try to understand or mess with the snake oil companys. 

You may want to read about _"Antivirus companies cause a big headache to small developers."_ at http://blog.nirsoft.net/2009/05/17/antivirus-companies-cause-a-big-headache-to-small-developers/ , a sample of other blog entries at http://blog.nirsoft.net/category/antivirus-issues/ or other ressources.

**Comment by Steel-Blade** [comment]
Do they do this intentionally though or they just don't care about the small software?

**Comment by gryffon** [comment]
https://forums.malwarebytes.org/forum/42-file-detections/ is the location to go to to report false positives.

**Comment by gryffon** [comment]
Additionally, if this does come up, you may go to Settings->Malware Exclusions and Add the executable to the list so that Malwarebytes does not pick it up.

**Comment by gryffon** [comment]
New build appears to be working for me.

**Comment by MrOmen13** [comment]
I restored the file from Quarantine and relaunched HDT fine. MBAM doesn't seem to be complaining now, nice work! Thanks Epix37!

It broke the icon for HDT but I am hoping a reboot fixes that. If not I will reinstall.
