### ISSUE TITLE
Doesn't appear

### ISSUE THREAD

**Issue by Fabbruz22** [HearthSim/Hearthstone-Deck-Tracker#2415]
i've alrwady installed the tracker and when i select my deck and start the game the deck doesn't appear on the monitor, the trackerd doesn't save neither the game results...

**Comment by Epix37** [comment]
See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#not-working

**Comment by Fabbruz22** [comment]
ty but how  can i make it appear in game?

**Comment by Epix37** [comment]
It *should* appear by default.

- Is `options > overlay > hide` enabled?
- Try enabling `options (advanced) > tracker > settings > alternative window search`.

**Comment by Fabbruz22** [comment]
i've created the deck, i selected it as active and after stat a game, should it appear?

**Comment by Epix37** [comment]
Did you check/try the two points I mentioned?

**Comment by Gleecerine** [comment]
Hello, I've been having the same issue (I've been using Hearthstone Deck Tracker for a while) in the past week. Overlay was set to hidden in spec / menu / outside HS but still, nothing appeared in game. I found a solution, which was to launch hearthstone from the HDT.

On a side note, I'm guessing you meant Advanced window search in your second option.

**Comment by ThorsAngerVaNeT** [comment]
Same problem, but it's obly appears when "Hide in menu" option is active... Seems that HDT have problem with undestanding where is menu and where isn't

**Comment by Epix37** [comment]
Did you guys try this? https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Setting-up-the-log.config

If that doesn't help please post the log after playing a few games. See here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by ThorsAngerVaNeT** [comment]
@Epix37, has done "Setting up the log.config", didnt help...
Try to open AppData from HDT and it has crashed... Maybe cause i set that logs are saving in HDT folder...
Crash report: http://pastebin.com/KGWSqXgk
HDT Log: http://pastebin.com/MZzx9zfR

**Comment by Epix37** [comment]
Did you actually play a game during the HDT session you just posted the log of?

**Comment by ThorsAngerVaNeT** [comment]
@Epix37, yes, against tavern keaper. I will play regular game if you need... Did you read my updated post describing problem? HDT seems can cathch that game has started...

**Comment by Epix37** [comment]
HDT does find any logs to read from. Either the game path is set incorrectly or Hearthstone is not creating log files.

https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#not-working
Doublecheck point 3 and 4.

**Comment by ThorsAngerVaNeT** [comment]
@Epix37, oh... the game path in HDT is correct, but not in Battle.net client, running game from backup folder, thx :-)
