### ISSUE TITLE
All games listed as Casual + Casual being tracked (when not supposed to)

### ISSUE THREAD

**Issue by JasonMcMahon** [HearthSim/Hearthstone-Deck-Tracker#2416]
So this is probably two separate, though related bugs.  As background I mostly play Ranked, and only want my Ranked games tracked.  I experiment & practice in Casual, though don't want those games recorded.

1. When I look at my Matches, every game has Mode = Casual.  Even though most of those games were actually played as Ranked.

2. In the Tracker -> Stats settings, I only have the Ranked box ticked.  However all of my Casual games still get recorded, and show up in my Matches.

(as bonus info.. tracking my Replays and Opponent's Decks appears to be busted. Though I assume that is an unrelated bug I'll look for an open issue on.)

**Comment by Epix37** [comment]
See here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#ranked
