### ISSUE TITLE
Deck Tracker crashes when attempting to open a specific Replay

### ISSUE THREAD

**Issue by Ronker** [HearthSim/Hearthstone-Deck-Tracker#2419]
Hi!
The Decktracker crashes, when I open a specific replay. The other matches work fine. This is really sad, because it was an epic one!!! I hope it can be fixed.
Crash Report:
[Crash report 2842016-2050.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/241256/Crash.report.2842016-2050.txt)
Some of the text seems to be in german, sorry for that. 
Here is a Screenshot:

![image](https://cloud.githubusercontent.com/assets/235410/14912179/27141ae8-0e03-11e6-99f7-767849844d35.png)

Keep up the good work!

**Comment by Epix37** [comment]
Fixed. This is an issue with games recorded before v0.14.5, where a weapon was played. 

It should work again with the next release.

**Comment by Ronker** [comment]
Wow, that was quick! Thank you :)
