### ISSUE TITLE
All data deleted

### ISSUE THREAD

**Issue by axelG97** [HearthSim/Hearthstone-Deck-Tracker#2420]
Suddenly all my decks and statistics seem to have disappeared. I used it last yesterday and it seemed to work fine, but when i tried to open it today it crashed a few times and gave me error messagers i stupidly disn't bother to read. Afterwards it needed and update and since then all my files are gone. Any solutions?

**Comment by riQQ** [comment]
Look here for backups `%AppData%/HearthstoneDeckTracker\Backups`.

**Comment by axelG97** [comment]
Thank you a lot, this fixed the issue
