### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by turtleOnline** [HearthSim/Hearthstone-Deck-Tracker#2423]
Hi, I haven't been able to update HDT automatically for a few versions now (in many previous updates it worked fine). The problem seems to be identical to one listed under another thread "Unable to update #2403" where it reads:

Creating temp file directory
Downloading latest version... 23474/23474KB (100%)
Extracting files...
Writing AForge.dll
Writing AForge.Imaging.dll
Writing AForge.Math.dll
Writing De.TorstenMandelkow.MetroChart.dll
Writing Garlic.dll
Writing HDTHelper.exe
Writing HDTUninstaller.exe
Writing HDTUpdate.exe
There was a problem updating to the latest version. Pressing any key will direct
you to the manual download.

I've downloaded the ZIP file for 14.7 and copied over all of the files to the real Hearthstone Deck Tracker. It noticed many of the files were duplicates and I -did not- copy over the duplicates because I didn't want to erase my replays, arena stats, decks, etc.

It didn't work. Frankly, it wasn't my best idea ever, so that doesn't surprise me, but I'm looking for guidance on how to get it to update without erasing all my prior data. The current version I'm using doesnt seem to recognize WOG cards.

Thanks!

**Comment by Epix37** [comment]
What I meant by "not overwriting" was to extract the files somewhere else, essentially a fresh installation. 

Your data is by defauled stored at "%AppData%/HearthstoneDeckTracker", so if you unzip is somewhere else and run it, you will still have all your data.
