### ISSUE TITLE
Yogg-Saron counter missing option for opponent to auto-detect

### ISSUE THREAD

**Issue by Musouv** [HearthSim/Hearthstone-Deck-Tracker#2425]
As stated in the title,
http://i.imgur.com/fQPAPhb.png
Yogg-Saron counter for opponents only has the Always and Never options, while all the others have Always, Auto, and Never

**Comment by GaryKing** [comment]
How would HDT auto-detect Yogg unless he's already played...?

**Comment by Epix37** [comment]
That is the correct answer. There is no good method for auto detecting whether the opponent is playing Yogg. The only idea was to use a minimum number of spells cast to show it, but that's not only too inconsistent but would also show the counter for many decks that don't actually contain Yogg.

The missing auto option is intended.
