### ISSUE TITLE
Export to Russian Hearthstone client

### ISSUE THREAD

**Issue by dmitryryzhkov** [HearthSim/Hearthstone-Deck-Tracker#2428]
Hello guys. Your program is amazing!!! But latest 3 or 4 versions, export on russian language works incorrectly (typed "v" instead name of cards). Could you check and fix this issue please ?

**Comment by Epix37** [comment]
Hm.. not really sure why this is happening again :/. 

Related: #2260

**Comment by dShadowHS** [comment]
Same problem, he copies it to clipboard (it can be checked by pasting last card name somewhere) but instead of entering text into search filter, he only writes "v". Interesting thing that he can copypaste name of the deck correctly, in any language.

**Comment by dmitryryzhkov** [comment]
Now I using english version, where everything is ok :) Looking forward when russian version will be fixed too

**Comment by ThorsAngerVaNeT** [comment]
Guys, your keyboard language in HDT must be English then everything is exporting just fine.

**Comment by dmitryryzhkov** [comment]
@Epix37 Hi, could u tell when this bug will be fixed ?

**Comment by Epix37** [comment]
I wish I could, but I don't really know why this is happening :/.

**Comment by LostSenSS** [comment]
> Guys, your keyboard language in HDT must be English then everything is exporting just fine.
+1

**Comment by azeier** [comment]
HDT now uses Hearthstones native deck string importing system.
