### ISSUE TITLE
[Feature Request] Export arena stats and deck lists to a CSV file

### ISSUE THREAD

**Issue by LVPols** [HearthSim/Hearthstone-Deck-Tracker#2429]
With the Stats Converter plugin you can export your arena runs to a CSV file. This is great, however it does not export your deck list as well.

It would be great if you can export your arena deck lists and stats to a CSV file. I'm thinking one line can represent an arena run, containing among other things, your score, rewards and deck list.

**Comment by Epix37** [comment]
This is a feature request you should make for the plugin, here: https://github.com/andburn/hdt-plugin-statsconverter.


@andburn fyi
