### ISSUE TITLE
When importing from a constructed deck, cards with less than 3 mana are not included

### ISSUE THREAD

**Issue by ThrillerHS** [HearthSim/Hearthstone-Deck-Tracker#2431]
I don't know if this is relevant, but I am using 4/3 monitor (1280/1024 resolution).
Also I think this was fixed in a patch a few days ago only to get broken again by the next one. (not sure though).
Also I think importing arena decks works fine.

**Comment by Epix37** [comment]
See #2250.

> Try re-running setup via options (advanced) > tracker > importing > set up constructed importing.

For some more insight on how the importing works, why it broke with the WotOG update and why it won't ever be perfect, see here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2250#issuecomment-204116658

**Comment by culinko** [comment]
Importing should be fixed in 0.15.
