### ISSUE TITLE
Feature request: would be really awesome to have  a hotkey to show/hide the overlay

### ISSUE THREAD

**Issue by ThrillerHS** [HearthSim/Hearthstone-Deck-Tracker#2432]
Most of the time I would like to see the game cleanly without the cards hiding card draws ect..
Also if you want to go really crazy with this you can have check boxes for each overlay part to be affected or not by the hotkey. So say I can have time and c'thun counters always showing but the deck lists either hidden or shown.

**Comment by Epix37** [comment]
`options (advanced) > tracker > hotkeys`: `Toggle overlay`

**Comment by ThrillerHS** [comment]
So so sorry.. looked for like 10 minutes before posting this. :( 
Mistakes were made.

**Comment by ThrillerHS** [comment]
Ok just set it up and it's working great excluding 2 things:
1) I used the space bar for my hotkey and it prevented from it working in other programs in windows, like this browser for example.
2) Would be nice if you added an option: "Toggle overlay: deck lists". Personally I like all the small unobtrusive stuff (markers, c'thun counter, timer) to show all of the time because they don't hide much of the game.
Thanks a lot for all of this.

**Comment by Epix37** [comment]
Try playing around with the scaling and opacity values under `options (advanced) > overlay > player/opponent`. Those should help to make the deck list hide less of the game. Also in case you don't know: you can move overlay elements around via `options > overlay > general > unlock`.
