### ISSUE TITLE
Bug: Stats for active deck only are missing the latest version

### ISSUE THREAD

**Issue by ThrillerHS** [HearthSim/Hearthstone-Deck-Tracker#2433]
When you view the new and awesome stats for an active deck the table shows lines:
All
V1.0
V1.1

But I also have a V1.2.

**Comment by Epix37** [comment]
Fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/59820c5f748b72a21f026a1cad88d33c8ca166ae.

**Comment by ThrillerHS** [comment]
Thanks!
