### ISSUE TITLE
 N'Zoth, The Corruptor error on web import

### ISSUE THREAD

**Issue by tknights2015** [HearthSim/Hearthstone-Deck-Tracker#2434]
When importing decks from the web,  N'Zoth, The Corruptor is not imported.
Example when importing this deck 
http://www.hearthstonetopdecks.com/decks/kolentos-wotog-standard-control-deathrattle-paladin/
(apostrophe maybe causing issue?)

**Comment by Epix37** [comment]
Fixed with https://github.com/HearthSim/HearthDb/commit/14b4ea7064912cb13021211c55af85a7bae3efa8

**Comment by Epix37** [comment]
Interesting though, they seem to be using a different apostrophe, this one works fine: http://www.hearthpwn.com/decks/495053-whispers-of-death-old-gods-deck-recipe

**Comment by Epix37** [comment]
Ooh, nvm. It's because they spell it "N'Zoth, The Corruptor", the correct spelling is "N'Zoth, the Corruptor" (lower case t).

**Comment by robertsmieja** [comment]
I was just about to report the same bug. Nice to see it's already fixed. Thanks! :)
