### ISSUE TITLE
Deck Tracker Won't Import Keeps Showing Instruction

### ISSUE THREAD

**Issue by unholypeon** [HearthSim/Hearthstone-Deck-Tracker#2435]
I have tried multiple times to get the deck tracker to import decks from the game but it always just shows the instructions.  I read through the other posts and restarting hearthstone or entering "play" mode once would not work either.  It always just keeps showing the instructions.

**Comment by Epix37** [comment]
Is the rest working? If not, see here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#not-working. That's likely to be the same problem.
