### ISSUE TITLE
Bug: Yogg-Saron counter broken

### ISSUE THREAD

**Issue by rorgier10** [HearthSim/Hearthstone-Deck-Tracker#2438]
The Yogg-saron counter wich first was just merged into one with the C'Thun counter now only shows up in menu's after a game. This is only for your opponents Yogg-Saron counter. C'Thun counter for opponent works just fine.

**Comment by Epix37** [comment]
Whoops, must have made a copy paste error when moving things around.

**Comment by piotr9k** [comment]
I'm sorry but could anyone post a screenshot of where that counter is supposed to appear? I see nothing in the default 4 windows (main, timer, opponent, player).
