### ISSUE TITLE
Request: N'Zoth counter

### ISSUE THREAD

**Issue by rorgier10** [HearthSim/Hearthstone-Deck-Tracker#2439]
When playing all of my new decks I was really happy to see the C'Thun and Yogg-Saron counters. Only one thing was just missing. When playing decks with all of the old gods I noticed I took quite some time looking for wich deathrattle minions I had already played and died.

Something like the Yogg-Saron counter would be ok(everytime a deathrattle minion died it goes up by one). But for the best experience I think that if you hover over the deathrattle counter you get a nice list of wich deathrattle minions died and in what order. This because you can only spawn 6 in the best case.

**Comment by Epix37** [comment]
Instead of adding a 3rd counter, #868 should solve this. Maybe deathrattle cards could be marked as such in the list.

**Comment by rorgier10** [comment]
The graveyard sounds pretty nice indeed, but i can't find anything in the options to show such an option. Is it implemented already? If yes, where do I enable it?

**Comment by Epix37** [comment]
That's not implemented yet, no.

**Comment by rorgier10** [comment]
I'm not sure where you would use the graveyard else for, and personally think that a nice 3 old gods counter combo would look way more clean than another option fot the graveyard. But I would love both of them right now ;)

**Comment by Cu8eR** [comment]
@Epix37 - I like both ideas - graveyard can be used in more cases that counter for just one combo. I dont know how difficult it is to implemented. Anyway graveyard can be used together with DT icons for specific minions (or highlight them).

**Comment by Epix37** [comment]
I'm strongly leaning towards the graveyard for this since it's a lot more versatile. Currently the other use for it would be Resurrect. And chances are future expansions will add new cards that interact with the graveyard.

I will have to think about the best way to add this to the UI for a day or two.

Closing in favor of #868.
