### ISSUE TITLE
Request: Button to hide/collapse "Deck History"

### ISSUE THREAD

**Issue by Fonjask** [HearthSim/Hearthstone-Deck-Tracker#2440]
Whenever editing a deck that has a history the window expands to the right a great deal blocking more often than not the actual deck list I'm trying to copy over. It seems wrong that with a good feature like Deck History in the app I'm having a better experience when just creating a new deck and removing the old one. Maybe it's somewhere in the options but I couldn't find it and the search didn't turn up with anything when looking for "history".

**Comment by Epix37** [comment]
Good suggestion. I added a button in the editing UI to show/hide the history - collapsed is the default now.
