### ISSUE TITLE
Built-in deck recipes

### ISSUE THREAD

**Issue by dvide** [HearthSim/Hearthstone-Deck-Tracker#2444]
Just a thought, not sure if it's worth it, but perhaps it would be a good idea to have the official deck recipes built in as a few default decks that come with HDT? Maybe with some option to hide the recipe decks if people don't want them filling up their deck lists. But when users first download HDT, it might be nice to see a few decks there already. It also serves to inform users of how HDT works: that they will be required to add their own decks into the app too if they want to track with them.

There are some issues to figure out though. If Blizzard ever tweaks a recipe, you could perhaps have it create a v1.1 of the same deck. Not sure what to do if a v1.1 already exists by the user, as in that case maybe you don't want to just make a v1.2 for them automatically (that might be confusing). If Blizzard ever replaces a recipe entirely with a different one, you could delete the original deck and replace it with the new one, unless they have some games associated with it, in which case keep the old deck too.

Or perhaps it's best to just have them be special decks in some separate interface area that you can only view, not edit or select to play games with. And then users can make a copy of these special decks into their main deck list to play with if they want. That way you can always change the special decks whenever Blizzard does, without worrying about these issues. You could also put more decks than just the recipes into this special area, like popular decks of the week, meta decks, etc. from the community.

**Comment by Epix37** [comment]
Not sure this is worth the effort.

**Comment by GaryKing** [comment]
You'd need someone to manage this in the long term otherwise it'd be a useless feature. Not really worth it.

**Comment by Cu8eR** [comment]
maybe better to use one of the web solution - hearthpwn.com

You can see rating, comments and easily import into HS

**Comment by Epix37** [comment]
I agree. Rejected.

**Comment by GiggliG** [comment]
The deck recipes are all listed on hearthpwn, you can import them from there easily enough. That's what I did.
