### ISSUE TITLE
HDT Splash opens when this Error occurs

### ISSUE THREAD

**Issue by synplex** [HearthSim/Hearthstone-Deck-Tracker#2448]
########## 30.04.2016 22:38:08 ##########
System.InvalidOperationException: Die Verteilerverarbeitung wurde deaktiviert, es werden jedoch weiterhin Nachrichten verarbeitet.
   bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[Crash report 3042016-2238.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/243827/Crash.report.3042016-2238.txt)
[Crash report 3042016-2240.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/243828/Crash.report.3042016-2240.txt)

**Comment by Epix37** [comment]
Translated exception: 
> Dispatcher processing has been suspended, but messages are still being processed

Not really sure what this is.

**Comment by Epix37** [comment]
Let's give the standard answer a shot (not sure if it helps in this case): Try reinstalling .NET Framework.
