### ISSUE TITLE
Export not clicking on correct coordinates

### ISSUE THREAD

**Issue by TheSpartanZeus** [HearthSim/Hearthstone-Deck-Tracker#2449]
When trying to export a deck to HS, the exporter clicks 'Deck Helper' 30 times (obviously to try to clear the deck?) and when trying to double click the mana crystal at the bottom it selects 0. This causes none of the cards to show as the filter is then set for 0 mana.
I have tried in both windowed and fullscreen, with the explicit resolution of 1920x1080 and 1680x1050
The result is the same. I have also restarted both HS and HDT, along with my computer and HDT has admin access.
I am running windows 10 with HDT 14.7

**Comment by Epix37** [comment]
See here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#exporting

**Comment by TheSpartanZeus** [comment]
I did check that, but none of the suggestions worked :(
If it helps, the export function was working in 13.x but as soon as i upgraded to 14.x it broke.

**Comment by Epix37** [comment]
Try changing your in-game resolution and/or windowed/fullscreen.

**Comment by TheSpartanZeus** [comment]
Found the issue. 
Having RadeonPro open in the background with AA or SweetFX causes the coord issue.
So just turning off RadeonPro should fix the issue :)

**Comment by Epix37** [comment]
:+1:
