### ISSUE TITLE
Suggestion: remove standard decks from wild filter

### ISSUE THREAD

**Issue by GiggliG** [HearthSim/Hearthstone-Deck-Tracker#2450]
At present when looking at decklist, Standard shows only Standard decks, but Wild shows Wild + Standard.

I think it would be better to remove the standard decks from the wild list. Yes, we can use standard decks in wild, but the current set up means the wild list is basically the same as All if you dont play much arena.

**Comment by dvide** [comment]
This option already exists in the `Sort / Filter Decks` panel, at the bottom :)

**Comment by GiggliG** [comment]
Oops! You learn something new every day :)
