### ISSUE TITLE
Arena HearthStats sync not syncing prizes

### ISSUE THREAD

**Issue by scottrick** [HearthSim/Hearthstone-Deck-Tracker#2452]
Gold rewards aaren't synced to the HearthStats website.  Maybe dust as well, but not sure.

**Comment by jleclanche** [comment]
Dupe of #2380

**Comment by riQQ** [comment]
Not a dupe of #2380.

**Comment by scottrick** [comment]
Yeah, this doesn't look like a duplicate.

**Comment by scottrick** [comment]
Maybe it was fixed at the same time, though.
