### ISSUE TITLE
UUUGGGHHH!  Deck Tracker WILL NOT find Hearthstone!

### ISSUE THREAD

**Issue by MadZoo** [HearthSim/Hearthstone-Deck-Tracker#2453]
Ok, I'm more than a little furious at this point.  I have watched two youtube videos and followed directions to a Tee.  However whenever I start Hearthstone IT NEVER FINDS THE FREAKING GAME!  I set the link via user/appdata/local/blizzard/hearthstone.  Then it says I have to restart HDT.  However, once I open the HDT again, it says I "OBVIOUSLY" need to install Hearthstone first....WHILE HEARTHSTONE IS RUNNING!  Can someone please give me some direction. This tool seems valuable, however, it is not for those of us with little coding ability.

**Comment by jleclanche** [comment]
Where's your Hearthstone directory located on your drive?

**Comment by MadZoo** [comment]
C: Drive

**Comment by jleclanche** [comment]
That's not enough to go on - what is the location of your Hearthstone directory? Eg. `C:/Program Files (x86)/Hearthstone/Hearthstone.exe`?

**Comment by MadZoo** [comment]
ummm...that I have no clue.. I can only find battle.net.  I have never been able to actually find a hearthstone.exe - even when I search for it, it never appears.  However, I have hearthstone running right now.

**Comment by MadZoo** [comment]
thank you for being willing to help btw

**Comment by MadZoo** [comment]
your thought, actually lead me to water here.  Just go around battle.net... I think I just figured it out

**Comment by jleclanche** [comment]
You should be able to find the Hearthstone path in the Battle.net settings:

![image](https://cloud.githubusercontent.com/assets/235410/14943840/825300d2-0fec-11e6-829b-1185c02e212b.png)

**Comment by pautpy** [comment]
I'm having the same issue. Where was the HS path set to originally? Maybe I can reset the path to the correct one.

**Comment by Epix37** [comment]
Should no longer be an issue with v0.14.8+.
