### ISSUE TITLE
Seems like all my stats disappeared

### ISSUE THREAD

**Issue by Slamooh** [HearthSim/Hearthstone-Deck-Tracker#2456]
Hello

it seems like all my stats have been erased :/
how can i troubleshoot this and try to recover them

Sidenote: for a few weeks i have not been able to update the tracker "automatically" . I always need to download the zip files from github and "install" it again

Thanks for your help

**Comment by jleclanche** [comment]
- Did you use the HearthStats integration?
- Do you know why they would have been erased? Maybe you upgraded your OS recently, or installed a new antivirus, anything like that?

**Comment by Epix37** [comment]
- Make sure you don't just have filters set accidentally: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#tag-filter
- HDT automatically creates daily backups, you can restore those under `options (advanced) > tracker > backups`

**Comment by Epix37** [comment]
For the updating issue, see #2403.

**Comment by Slamooh** [comment]
Thanks for your help
No hearthstats integration here
And i didn't change anything on my comp that i can remember

checked the filters, seems like everything is fine

finally used the back up system and restored one backup from 2 days ago. I guess i lost a few matches but most of it is back.
Now that i know about the backups, if it happens again i have a solution ;)

I'll check the update issue

Thanks for your help

**Comment by jleclanche** [comment]
Good to hear.
