### ISSUE TITLE
Alexstraza no deck match

### ISSUE THREAD

**Issue by eatadick** [HearthSim/Hearthstone-Deck-Tracker#2458]
Perfectly entered warrior deck gave me the no match deck error the moment I drew my Alexstraza, even though Alexstraza is in the deck list. It's a bit annoying I can't tell the tracker "yo shut up it's a match keep stats still please..."

**Comment by eatadick** [comment]
It's still repeatedly wanting to not accept there's an Alexstrasza in this deck for no reason, permenantly staring at the "Warning! Cards not found in deck: Alexstrasza"

**Comment by Epix37** [comment]
Please post the deck (`EXPORT > SAVE AS XML`) and log of a game where this happened ([see here](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)).

**Comment by Epix37** [comment]
Closing for lack of response
