### ISSUE TITLE
HSDecktracker crashes at Start

### ISSUE THREAD

**Issue by KinderR1egel** [HearthSim/Hearthstone-Deck-Tracker#2459]
########## 02.05.2016 15:33:25 ##########
System.Exception: Error restoring PlayerDecks backup. Please manually rename "PlayerDecks_backup.xml" to "PlayerDecks.xml" in "%appdata\HearthstoneDeckTracker". ---> System.InvalidOperationException: Fehler im XML-Dokument (3832,4). ---> System.Xml.XmlException: Unerwartetes Dateiende. Die folgenden Elemente wurden nicht geschlossen: Cards, Deck, Decks. Zeile 3832, Position 4.
   bei System.Xml.XmlTextReaderImpl.Throw(Exception e)
   bei System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   bei System.Xml.XmlTextReaderImpl.ThrowUnclosedElements()
   bei System.Xml.XmlTextReaderImpl.ParseElementContent()
   bei System.Xml.XmlTextReaderImpl.Read()
   bei System.Xml.XmlTextReader.Read()
   bei System.Xml.XmlReader.ReadEndElement()
   bei System.Xml.Serialization.XmlSerializationReader.ReadEndElement()
   bei Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckList.Read2_Card(Boolean isNullable, Boolean checkType)
   bei Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckList.Read9_Deck(Boolean isNullable, Boolean checkType)
   bei Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckList.Read11_DeckList(Boolean isNullable, Boolean checkType)
   bei Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderDeckList.Read12_Decks()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   bei System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   bei Hearthstone_Deck_Tracker.XmlManager`1.Load(String path)
   bei Hearthstone_Deck_Tracker.DeckList.Load()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Hearthstone_Deck_Tracker.DeckList.Load()
   bei System.Lazy`1.CreateValue()
   bei System.Lazy`1.LazyInitValue()
   bei System.Lazy`1.get_Value()
   bei Hearthstone_Deck_Tracker.Windows.OverlayWindow.SetDeckTitle()
   bei Hearthstone_Deck_Tracker.Windows.OverlayWindow.Update(Boolean refresh)
   bei Hearthstone_Deck_Tracker.Windows.OverlayWindow..ctor(GameV2 game)
   bei Hearthstone_Deck_Tracker.Core.get_Overlay()
   bei Hearthstone_Deck_Tracker.FlyoutControls.Options.Overlay.OverlayOpponent.Load(GameV2 game)
   bei Hearthstone_Deck_Tracker.FlyoutControls.OptionsMain.Load(GameV2 game)
   bei Hearthstone_Deck_Tracker.Windows.MainWindow.LoadConfigSettings()
   bei Hearthstone_Deck_Tracker.Core.Initialize()
   bei Hearthstone_Deck_Tracker.App.App_OnStartup(Object sender, StartupEventArgs e)
   bei System.Windows.Application.OnStartup(StartupEventArgs e)
   bei System.Windows.Application.<.ctor>b__1_0(Object unused)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Epix37** [comment]
Go to `%AppData%/HearthstoneDeckTracker` (Win+R, paste) and delete the "PlayerDecks.xml" file. If there is a "PlayerDecks_backup.xml", rename it to "PlayerDecks.xml". Otherwise go to the "Backups" folder and replace it with the "PlayerDecks.xml" from the latest zip.

**Comment by KinderR1egel** [comment]
Hey, thanks for the help...
I already went to %AppData%/HearthstoneDeckTracker (Win+R, paste) and replaced  "PlayerDecks.xml" with the renamed "PlayerDecks_backup.xml". Now it works....but all my Decks and Stats are gone ;(
Are they lost forever?

**Comment by KinderR1egel** [comment]
Also I just got a new Issue... I was trying to Import a Deck from Web and got this CrashReport:

########## 03.05.2016 03:24:19 ##########
System.Exception: DeckStats.xml is corrupted.
   bei Hearthstone_Deck_Tracker.Stats.DeckStatsList.Load()
   bei System.Lazy`1.CreateValue()
   bei System.Lazy`1.LazyInitValue()
   bei System.Lazy`1.get_Value()
   bei Hearthstone_Deck_Tracker.Hearthstone.Deck.get_DeckStats()
   bei Hearthstone_Deck_Tracker.Hearthstone.Deck.CheckIfArenaDeck()
   bei Hearthstone_Deck_Tracker.Hearthstone.Deck.get_IsArenaDeck()
   bei Hearthstone_Deck_Tracker.Hearthstone.Deck.Clone()
   bei Hearthstone_Deck_Tracker.Windows.MainWindow.SetNewDeck(Deck deck, Boolean editing)
   bei Hearthstone_Deck_Tracker.Windows.MainWindow.<ImportDeck>d__125.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
15:42:04|Info|OverlayWindow.Update >> Refreshed overlay topmost status
15:42:05|Warning|LogReaderManager.Stop >> LogReaders could not be stopped, stop already in progress.
15:42:05|Info|GameV2.Reset >> -------- Reset ---------
15:42:05|Info|Player.Name >> [Player] 
15:42:05|Info|Player.Name >> [Opponent] 
15:42:05|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
15:42:05|Info|DataIssueResolver.RemoveDuplicateMatches >> Checking for duplicate matches...
15:42:05|Info|BackupManager.Run >> Running BackupManager
15:42:05|Info|BackupManager.Run >> Deleting old backup: Backup_23042016.zip
15:42:05|Info|BackupManager.Run >> Creating backup for today
15:42:06|Info|PluginManager.LoadPlugins >> Loading Plugins...
15:42:06|Info|GitHub.CheckForUpdate >> HearthSim/Hearthstone-Deck-Tracker: Checking for updates (current=0.14.7.0, pre-release=False)
15:42:06|Info|GameEventHandler.ResetConstructedImporting >> Reset constructed importing
15:42:07|Info|GitHub.CheckForUpdate >> HearthSim/Hearthstone-Deck-Tracker: We are up-to-date (latest=v0.14.7, pre-release=False)
02:41:25|Error|NewsUpdater.UpdateAsync >> Error loading news: System.Net.WebException: Der Remotename konnte nicht aufgelöst werden: 'raw.githubusercontent.com'
   bei System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   bei System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   bei System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Hearthstone_Deck_Tracker.Utility.NewsUpdater.<UpdateAsync>d__21.MoveNext()
03:24:16|Info|DeckImporter.Import >> Importing deck from http://www.hearthstonetopdecks.com/decks/purples-wotog-standard-face-hunter/

**Comment by Epix37** [comment]
Try overwriting all your files with those of a zip from the backups folder from 2 days or so ago.

**Comment by KinderR1egel** [comment]
Seems like it worked....thx
