### ISSUE TITLE
Last played - N/A

### ISSUE THREAD

**Issue by Cu8eR** [HearthSim/Hearthstone-Deck-Tracker#2460]
For every new deck it shows N/A instead of date. For these new deck I played yesterday and today (ranked. standard/wild)

For old decks works fine, here is the screenshot
![lasttimeplayed](https://cloud.githubusercontent.com/assets/778890/14956157/8ba1ebb6-107e-11e6-83af-71da775418c3.png)

**Comment by Epix37** [comment]
Does this persist after restarting?

**Comment by Cu8eR** [comment]
@Epix37 - ok, I restarted HS tracker and dates are shown... maybe could you add autorefresh without reseting tracker?

**Comment by Epix37** [comment]
Might be related to the theme you have selected, I think I fixed that previously (apparently not for all). I'll look into it.
