### ISSUE TITLE
Constructed decks stats - easily assign a deck for unknown matches

### ISSUE THREAD

**Issue by Cu8eR** [HearthSim/Hearthstone-Deck-Tracker#2466]
Sometimes deck is not selected automaticaly - so I have an unknown match in stats tab - is there any way how to easily assing an existing deck into this match? thank you

**Comment by Epix37** [comment]
Matches under `stats > constructed > matches` have a `move` button when selected, allowing you to move it to another deck. Is that what you are looking for?

**Comment by Cu8eR** [comment]
@Epix37 - for unknown decks too? just assing the correct deck?

**Comment by Epix37** [comment]
Yes
