### ISSUE TITLE
Where did my constructed games stats go?

### ISSUE THREAD

**Issue by jesperhansson** [HearthSim/Hearthstone-Deck-Tracker#2467]
After last update, 0.14.7, I can't seem to find my constructed matches/stats. Arena matches/stats are kept.
The list of games is empty when I view stats, except for new games after May 1st.
The deck win counters are still there for latest version of the deck. 

Anyone else who experienced this? Any fix? Is this on purpose?

I do not have any backup of %AppData%\Local\HearthstoneTracker

**Comment by Epix37** [comment]
The constructed stats timeframe filter is set to `season` by default (i.e. only the current month). This sounds like that might be it - see if changing it helps.

**Comment by jesperhansson** [comment]
Thx. I did not see that option. Thank you for bothering to reply. 
I'll throw in an extra donation :-)
