### ISSUE TITLE
ManaCrystals.com Import

### ISSUE THREAD

**Issue by mraakashshah** [HearthSim/Hearthstone-Deck-Tracker#2468]
Please add deck importing from ManaCrystals.com

Example guide:
https://manacrystals.com/deck_guides/170-dragon-priest-to-top-200-legend-78-win-rate

Note: If you can poke me in the correct direction I can attempt it myself. I've already been working on some plugins.

**Comment by riQQ** [comment]
Already implemented, see #2430. You'll have to wait for the next release or clone and compile master.
