### ISSUE TITLE
Mulch

### ISSUE THREAD

**Issue by Tarrim** [HearthSim/Hearthstone-Deck-Tracker#2469]
the tracker reveled the card my opponent got from a mulch before it was played

**Comment by GaryKing** [comment]
Got a log or screenshot of this? I can't imagine how HDT could know the result? What card did it end up being?

**Comment by riQQ** [comment]
Do you have the replay?

**Comment by Tarrim** [comment]
it was sea reaver  probably tied to that i will upload what screen shots i have and the replay when i get back from work if still needed

**Comment by Tarrim** [comment]
Yeah tied to the affect even though not reveled on client can be read by the tracker http://us.battle.net/hearthstone/en/forum/topic/19893169957

**Comment by culinko** [comment]
Unfortunately, it's a bug with Hearthstone, not a bug with HDT: https://github.com/HearthSim/hs-bugs/issues/19.
