### ISSUE TITLE
Missing current version of stat in contructed summary

### ISSUE THREAD

**Issue by leadingmore** [HearthSim/Hearthstone-Deck-Tracker#2477]
![hdt_missing_current_deck_stats_in_summary](https://cloud.githubusercontent.com/assets/11826059/15084140/95e321ac-139f-11e6-827e-cc6ed5234eac.png)

The summary screen is missing stats for current version.  In the screenshot, you can see stats for v1.0 is 4-2.  And stats for all version is 10-6.  What's missing is the 6-4 stats for version v1.1.

I think it was working properly in the old stats screen

**Comment by culinko** [comment]
Already fixed with 59820c5, the version just hasn't been released yet.
