### ISSUE TITLE
Ranked Games Not recorded Weird iteration

### ISSUE THREAD

**Issue by EAldanaJ** [HearthSim/Hearthstone-Deck-Tracker#2479]
I started using HDT 2 days ago, and everything works as intended but the deck stats when i win games some are recorded but most of them arent, are not shown neither on the HDT window or the Overlay in game, but when i acces to the Stats menu they are there everything is there but missing the rank the game was played
Anyone having this problem¡? have a fix or its a bug? or its just me?

**Comment by EAldanaJ** [comment]
After messing with the edditing, i found hat games are being recorded as casual not ranked being that the problem !! how can i get this fixed?

**Comment by culinko** [comment]
See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#ranked-games-are-recorded-as-casual.
