### ISSUE TITLE
Ability usage counter

### ISSUE THREAD

**Issue by HellbringerOnline** [HearthSim/Hearthstone-Deck-Tracker#2481]
For the tempo control.

**Comment by Epix37** [comment]
What exactly do you mean? Hero power? In that case this would be more of a plugin kind of thing, I think.

**Comment by Cu8eR** [comment]
I think he means a hero power - sometimes useful. I have seen this suggestion (similiar) before.

**Comment by culinko** [comment]
Is this ticket about #1532?

**Comment by Cu8eR** [comment]
Yes, thats it!
