### ISSUE TITLE
Problems with cathing image

### ISSUE THREAD

**Issue by Bloomer24** [HearthSim/Hearthstone-Deck-Tracker#2486]
Instaled Arena helper plugin with HDT on new pc. Got something like this:

![image](https://cloud.githubusercontent.com/assets/235410/15181253/d7934274-178e-11e6-9165-c0e80dd465e1.png)

Program cannot detect heros nor cards.

Please help :(

**Comment by Epix37** [comment]
Please create an issue on the plugin GitHub: https://github.com/rembound/Arena-Helper

(@rembound fyi)

**Comment by rembound** [comment]
@Bloomer24 This is an installation error. Check out my comments at: https://github.com/rembound/Arena-Helper/issues/75#issuecomment-202046640

**Comment by Bloomer24** [comment]
Tried most things (all "How to install" and few from comments) so far and still the same.
