### ISSUE TITLE
Deck tracker doesnt connect to hearthstone

### ISSUE THREAD

**Issue by jipprinsen** [HearthSim/Hearthstone-Deck-Tracker#2487]
Hello,
I have used HDT without troubles a long time, but quit HS two months ago. When i got back into it a few days ago, and i tried to use the tracker, it didnt work (i dont remember the reason), so i removed it, reinstalled it, when i started it, it said the folder backup data was missing, so i created a folder with that name, i started the tracker and it didnt give the error message, but since then, the tracker overlay doesnt appear on hearthstone, i can make decks myself on the tracker or upload them from the web, but when i activate the decks (or any other part of the overlay) doesnt appear. It is like the tracker doesnt recognize that hearthstone is running. How do i solve this?

**Comment by riQQ** [comment]
See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#not-working.
