### ISSUE TITLE
Bug with this week's Tavern Brawl

### ISSUE THREAD

**Issue by GaryKing** [HearthSim/Hearthstone-Deck-Tracker#2488]
The two cards I chose in this week's Tavern Brawl were Living Roots and Power of the Wild, both Druid cards.

HDT first thought that I was using my Druid deck because these two cards are in my Druid deck, but when there were more than 2 copies of one of the cards in my opening hand, HDT should have asked if I wanted to go into no-deck mode instead, which it didn't.

**Comment by Epix37** [comment]
Logs please.

**Comment by GaryKing** [comment]
Attached
[Tavern Brawl HDT game log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/259990/Tavern.Brawl.HDT.game.log.txt)

**Comment by Epix37** [comment]
Oh, this happens because HDT was not yet able to determine which player is which (this is a problem with brawl). On the next turn you should have gotten the dialog.

Should be the same as https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2404#issuecomment-215570829.

**Comment by GaryKing** [comment]
Yeah the dialog came up when I just tried the Brawl again. It seems like the dialog comes later if I go second.
