### ISSUE TITLE
Lost all decks and statistics upon HS crash

### ISSUE THREAD

**Issue by Skinnyrogue** [HearthSim/Hearthstone-Deck-Tracker#2490]
Hi there,

I was in an Arena match and when the match finished there was a short public Battle.net error where nobody could connect to Hearthstone. I was running HDT at the moment and had to force shutdown HS and HDT after the match. Apparently something went wrong because when I reopened HDT all my decks and statistics were lost.  When checking my Appdata I found the file PlayerDecks_corrupted.xml, with all my deck info in there. Also in my HDT folder in the folder Crash Reports there is a file dating to when the crash happened. 

My PlayerDecks_corrupted.xml file: http://pastebin.com/HFvQgXhV
My Crash Report file: http://pastebin.com/6QcWK7k8

Anyone who has a clue on how to get all my deck info and statistics back?

Thanks a lot in advance!

**Comment by andburn** [comment]
Check the *Backups* folder in AppData, the latest zip file should have a backup of your *PlayerDecks* (stats too but you probably won't need to restore them).

**Comment by Epix37** [comment]
You can also restore backups under `options (advaned) > tracker > backups`. (@andburn fyi :P)

**Comment by Skinnyrogue** [comment]
Oh wow, such an easy fix. How did I not see that. Thanks a lot!
