### ISSUE TITLE
Not Highlighting Cards when Playing !!!

### ISSUE THREAD

**Issue by ABOOD729** [HearthSim/Hearthstone-Deck-Tracker#2491]
this problem is so annoying !! my drawn cards and everything doesn't get highlighting ! i tried everything i restarted hearthstone i reinstalled the deck tracker i updated the deck tracker still doesn't work with me !!! please help me

**Comment by riQQ** [comment]
See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#not-working.

**Comment by ABOOD729** [comment]
THANKS BRO THAT WORKED !!
