### ISSUE TITLE
Created minions (imps, murloc scout, ooze, silver hand murloc, etc) incorrectly trick the tracker into thinking I'm using the wrong deck

### ISSUE THREAD

**Issue by zacharyaugustine** [HearthSim/Hearthstone-Deck-Tracker#2492]
These created minions show up in the card list as if they were in my deck all along.

**Comment by Epix37** [comment]
Please post logs of games where that happens - see here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues
