### ISSUE TITLE
Problem when I record games

### ISSUE THREAD

**Issue by Thankcobra** [HearthSim/Hearthstone-Deck-Tracker#2494]
Hello, can someone help me with this problem? I don't know why Deck Tracker still continue to record casual games. I already have the latest version and try to reinstall it.

https://i.gyazo.com/3a8b1a5a3ec1e13756f68712b2dadf9f.png

https://i.gyazo.com/4e950180a9638feb0c8b8dfdfec957a2.png

**Comment by Epix37** [comment]
Should  be the same as #2494. I think we are on our way to a solution to that one.
