### ISSUE TITLE
Certain decks not being uploaded to hearthstats after deck merge

### ISSUE THREAD

**Issue by zaheer12a** [HearthSim/Hearthstone-Deck-Tracker#2495]
I decided to merge several different decks of the same archetypes on my hearthstats account. After I did this, certain decks won't be tracked on hearthstats anymore. The games are tracked in the deck tracker, but after several attempts of syncing (inluding force full sync) it still doesn't upload the games. What's going wrong here?

**Comment by zaheer12a** [comment]
The decks that I´m sure of that are not getting tracked are these two:
http://hearthstats.net/decks/standard-zoo--965?locale=en
http://hearthstats.net/decks/standard-freeze-mage--396?locale=en

**Comment by zaheer12a** [comment]
4 days later, no response, nothing at all besides the tag. It's evident you don't care about this issue or you would have said something. Great support guys. Hats off to your support staff for being so helpful. Remind me never to report any issues in the future.

**Comment by culinko** [comment]
There is no "support staff". Epix is the only person who handles issues with HDT. I merely added label for the issue to help him with tracking down duplicate issues. And if you look at the latest HDT commits, you can clearly see that he's been busy with implementing suff for HSReplay to work properly.

**Comment by jleclanche** [comment]
@zaheer12a You are using a free product and support for it is limited to volunteers. You didn't purchase HDT and you certainly didn't pay for 24/7 "support staff". Besides, free or paid, nobody wants someone with an attitude like this using their software.

Closing as this is a HearthStats issue. That particular feature is getting phased out very soon in favor of HSReplay support.
