### ISSUE TITLE
Tracker doesnt show decks/cards ingame

### ISSUE THREAD

**Issue by DoerdiDara** [HearthSim/Hearthstone-Deck-Tracker#2496]
Hey guys. My Decktracker is working. I can create decks or import them, but when i start a match, the deck doesnt show up. i went through all options but i couldnt find anything what would fix the problem. does anyone have an idea?

**Comment by riQQ** [comment]
See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#its-not-detecting-cards-i-or-my-opponent-play.

**Comment by DoerdiDara** [comment]
Hey riQQ thanks for the answer. Actually none of the steps helped me to fix the problem, but i still found a way to run the decktracker again :) I just had to use the "uninstall.exe" in the folder and remove every data. After that I clicked the installer.exe and everything was working fine :)
