### ISSUE TITLE
Overlay not working

### ISSUE THREAD

**Issue by djannih** [HearthSim/Hearthstone-Deck-Tracker#2497]
I've gone through all steps in the FAQ to no avail. I replaced the contents of log.config, I checked my antivirus and if the HS logs were up to date. I've manually entered the HS path into Decktrackers config file.

The deck I've created, and set to "Active", will show the complete deck contents to the right on my screen. But nothing happens as a game progresses.

I'm running Windows 10.1, AVG antivirus. I've tried every solution from the FAQ but nothing seems to help.

**Comment by riQQ** [comment]
Can you post your hdt log? See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues.

**Comment by djannih** [comment]
23:23:27|Info|GameV2.CurrentGameMode >> Set CurrentGameMode to None
23:23:27|Info|GameV2.Reset >> -------- Reset ---------
23:23:27|Info|Player.Name >> [Player] 
23:23:27|Info|Player.Name >> [Opponent] 
23:23:27|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
23:23:28|Info|OverlayWindow.Update >> Refreshed overlay topmost status
23:23:28|Info|MainWindow.SelectDeck >> Switched to deck: Midrange
23:23:28|Warning|LogReaderManager.Stop >> LogReaders could not be stopped, stop already in progress.
23:23:28|Info|GameV2.Reset >> -------- Reset ---------
23:23:28|Info|Player.Name >> [Player] 
23:23:28|Info|Player.Name >> [Opponent] 
23:23:28|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
23:23:29|Info|DataIssueResolver.RemoveDuplicateMatches >> Checking for duplicate matches...
23:23:29|Info|BackupManager.Run >> Running BackupManager
23:23:29|Info|BackupManager.Run >> Backup for today already exists
23:23:29|Info|PluginManager.LoadPlugins >> Loading Plugins...
23:23:29|Info|GitHub.CheckForUpdate >> HearthSim/Hearthstone-Deck-Tracker: Checking for updates (current=0.14.7.0, pre-release=False)
23:23:29|Info|OverlayWindow.Update >> Refreshed overlay topmost status
23:23:29|Info|GameEventHandler.ResetConstructedImporting >> Reset constructed importing
23:23:30|Info|GitHub.CheckForUpdate >> HearthSim/Hearthstone-Deck-Tracker: We are up-to-date (latest=v0.14.7, pre-release=False)
23:24:08|Info|OverlayWindow.Update >> Refreshed overlay topmost status
23:24:46|Info|OverlayWindow.Update >> Refreshed overlay topmost status
23:25:31|Info|OverlayWindow.Update >> Refreshed overlay topmost status
23:25:56|Info|OverlayWindow.Update >> Refreshed overlay topmost status
23:26:35|Info|OverlayWindow.Update >> Refreshed overlay topmost status
23:27:02|Info|OverlayWindow.Update >> Refreshed overlay topmost status
23:27:07|Info|OverlayWindow.Update >> Refreshed overlay topmost status
23:27:18|Info|OverlayWindow.Update >> Refreshed overlay topmost status
23:28:07|Info|OverlayWindow.Update >> Refreshed overlay topmost status
23:28:38|Info|OverlayWindow.Update >> Refreshed overlay topmost status
23:28:41|Info|OverlayWindow.Update >> Refreshed overlay topmost status
23:29:23|Info|OverlayWindow.Update >> Refreshed overlay topmost status
23:30:50|Info|OverlayWindow.Update >> Refreshed overlay topmost status
23:32:27|Info|OverlayWindow.Update >> Refreshed overlay topmost status
23:32:39|Info|LogReaderManager.Stop >> Stopped LogReaders.

**Comment by djannih** [comment]
![hearthstone screenshot 05-13-16 15 11 17](https://cloud.githubusercontent.com/assets/19335021/15248909/fbc9b7a6-191c-11e6-9215-10aa6f293043.png)

This is what it looks like when I'm playing. :/

**Comment by djannih** [comment]
Oh, sry. I just realized the way I posted my log wasn't the preferred one. Here's the .txt-file. 
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/264042/hdt_log.txt)

**Comment by riQQ** [comment]
What's your Hearthstone path?

**Comment by djannih** [comment]
The path is E:\Spel\Hearthstone. It's on a secondary SSD drive.

**Comment by riQQ** [comment]
Have you tried the latest update of HDT? There have been some changes that could fix your problem.

**Comment by djannih** [comment]
I have. :( Doesn't work.

**Comment by Epix37** [comment]
Check the last point (and 2nd sub-point) here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#not-working

If that does not help, delete the mentioned folder again and try reinstalling Hearthstone.

**Comment by djannih** [comment]
I reinstalled HS (and also deleted %LOCALAPPDATA%\Blizzard\Hearthstone) and now it works!! Thanks for the help!
