### ISSUE TITLE
Overlay disappearing

### ISSUE THREAD

**Issue by YvesW** [HearthSim/Hearthstone-Deck-Tracker#25]
Hi,

The overlay often disappears, which is only fixable by restarting the tracker. It isn't on top anymore in that case; I can slightly see it when I minimize and restore my hs window. I'm using 2 monitors, HS isn't fullscreen and I often switch monitors.

Yves

**Comment by nicki118** [comment]
Same over here...
If i am minimizing hearthstone or just klicking somewhere on my second screen the deck tracker overlay disappeers 
Regard Nick
