### ISSUE TITLE
Cannot add card as a arena reward

### ISSUE THREAD

**Issue by bombek92** [HearthSim/Hearthstone-Deck-Tracker#2501]
![bug](https://cloud.githubusercontent.com/assets/16099706/15269758/b3622fb4-1a09-11e6-9531-1a5e021bcad5.jpg)
After patching program today I cannot add card as a Arena Reward. Firstly i typed it in the "reward box" which open just after finishing arena run, then I noticed on the stats list that it is not there so I tried to edit reward by clicking "Edit rewards" and after saving it doesn't appear. Also reward-statisitc doesn't update so it basically doesn't exist.

Can anyone try to reproduce this bug?

**Comment by Epix37** [comment]
Fixed.

I will push the update tomorrow or the day after. Write your cards down for now (if you can remember), you will be able to add them again with the next version.

**Comment by bombek92** [comment]
Thank you!
