### ISSUE TITLE
Not recording stats anymore.

### ISSUE THREAD

**Issue by jakeslab** [HearthSim/Hearthstone-Deck-Tracker#2502]
For some reason at 12:09 PST the deck tracker decided that it would no longer keep track of my games.

**Comment by jakeslab** [comment]
For some reason at 12:09 PST the deck tracker decided that it would no longer keep track of my games.

**Comment by Epix37** [comment]
Please post the logs of that - see here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues.

Maybe https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/1553?

**Comment by jakeslab** [comment]
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/264778/hdt_log.txt)

**Comment by Epix37** [comment]
Games definitely are recorded. Where are you expecting the stats? Judging from the logs you have no deck selected, so they would only show up under stats. See if resetting the filter helps: `STATS > CONSTRUCTED > FILTERS > ... > RESET`

**Comment by jakeslab** [comment]
Ya that worked thanks
