### ISSUE TITLE
Arena Helper Not Working V0.14.8

### ISSUE THREAD

**Issue by tknights2015** [HearthSim/Hearthstone-Deck-Tracker#2503]
After the update, Arena Helping is not Detecting arena. Had to manually select hero and does not detect cards.  Sits on detecting arena.
![arena helper](https://cloud.githubusercontent.com/assets/16232528/15271061/ee609e2c-19f3-11e6-9226-4ef855ffa4df.JPG)

**Comment by tknights2015** [comment]
Reverted to 14.7 and works fine. Issue is with 14.8

**Comment by Epix37** [comment]
Hm.. works completely fine for me. Are you using the latest ArenaHelper version?

**Comment by tknights2015** [comment]
Yes version is 8.0 and was  working prior to the HDT update and also works when reverted to HDT 14.7.  Will try again later with updated HDT to 14.8

**Comment by tknights2015** [comment]
This is working now. Version 14.9  HDT and Arena Helper 8.0

**Comment by Epix37** [comment]
:+1:
