### ISSUE TITLE
Brawl, Friendly, Practice, Spectator matches not showing up in 0.14.8

### ISSUE THREAD

**Issue by jedimaster421** [HearthSim/Hearthstone-Deck-Tracker#2504]
Only Ranked and Casual matches are showing up on the Stats page list of matches. When I revert to 0.14.7, all matches appear correctly.

Edit: to be clear, all past matches from those four modes are missing, not just new matches. I did not test if new matches of those modes are recorded.

**Comment by Epix37** [comment]
This is an issue with the format filter. Select ranked or casual mode, then set the format filter so "all". 

An updater later today will fix this.
