### ISSUE TITLE
[Suggestion] Detect Spectator Mode

### ISSUE THREAD

**Issue by Olpol** [HearthSim/Hearthstone-Deck-Tracker#2506]
Whenever I'm spectating a friend's game, HDT gets a little antsy and can't detect the deck they're playing as one that I've saved (because I haven't). So it prompts me to turn on "no deck" mode. That's fine I don't mind that. But I'd like it to restore back to normal when I leave spectating mode.

Thank you for a great app.

**Comment by Epix37** [comment]
There are easy several options:
- `options (advanced) > tracker > general > use no deck on spectator mode` should automatically switch back after leaving spectator.
- Set a hotkey for `toggle no deck mode` (`options (advanced) > tracker > hotkeys`). Pressing it a second time will re-select the last deck
- Uncheck `use no deck` in the tray icon context menu. This will also re-select the last deck.

**Comment by Olpol** [comment]
Thank you very much!

**Comment by Epix37** [comment]
:+1:
