### ISSUE TITLE
[SUGGESTION] Damage counter to display when you have lethal

### ISSUE THREAD

**Issue by Parusu** [HearthSim/Hearthstone-Deck-Tracker#2508]
I recently discovered the damage counter option. I think it is very usefull. Maybe to enhance the visability with a colorchange of the text, when the damage on board > Enemy face HP

Even if it will be difficult with taunts / iceblock, I think it would be nice to see a change 'Hey, if you could go face, you have lethal'

**Comment by pnicolli** [comment]
This sounds dangerous to me. It's the software actually making damage calculations for us and giving us a little strategic advice. Just calculating the damage seems fine to me.

**Comment by Epix37** [comment]
The damage counters are as far as I'm willing to go with this. Not only does it require a lot of work to get right, but it's also moving towards a very dark-gray area.
