### ISSUE TITLE
how to get the number of cards that in my hand.

### ISSUE THREAD

**Issue by jeraxx** [HearthSim/Hearthstone-Deck-Tracker#2510]
my program need to know the number of cards in my hand,where can I get this information,log?

**Comment by Epix37** [comment]
You are talking about a standalone program, not a HDT plugin? You need to parse the Power.log (found in Hearthstone/Logs, [see  here for more info](https://github.com/jleclanche/fireplace/wiki/How-to-enable-logging)) and keep track of entities entering/leaving the hand.
