### ISSUE TITLE
[win10] Can't see the arena stats

### ISSUE THREAD

**Issue by bizzmane** [HearthSim/Hearthstone-Deck-Tracker#2512]
When I open the arena stats a new window with the stats will open, but I can't fokus it and its nothing in there.

**Comment by riQQ** [comment]
Is this still happening?

**Comment by riQQ** [comment]
Probably the same issue as reported in https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3427#issuecomment-358788239
