### ISSUE TITLE
Full Freeze - Crash Report

### ISSUE THREAD

**Issue by CruzinToVictory** [HearthSim/Hearthstone-Deck-Tracker#2514]
My entire computer froze after selecting an older version of one of my decks. Upon rebooting, the pop up told me to send my crash report here.

Thanks!
[Crash report 1652016-2214.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/267364/Crash.report.1652016-2214.txt)

**Comment by CruzinToVictory** [comment]
Just to update here. i was able to restore my deck lists by using an automatic backup that was made earlier today. It even saved all of the matches I played after that backup, so up and running. Thanks again for the awesome software!

**Comment by Epix37** [comment]
:+1: restoring from a backup would have been my solution, too.
