### ISSUE TITLE
[?] HDT stops working

### ISSUE THREAD

**Issue by zedor** [HearthSim/Hearthstone-Deck-Tracker#2516]
So here goes nothing. I noticed a problem while running this list:

![image](https://cloud.githubusercontent.com/assets/235410/15390356/26bc031e-1dc4-11e6-9533-d8df61d46ef8.png)

I started hunting legend (massing games) for this season and chose this list to do it the version before the current one (current is v0.14.9), so I don't know if it happens with other lists or when it started **exactly**.

So the problem is that it just stops tracking games. I don't use overlay so I notice it after finishing a game that the end game note didn't pop up, after which I have to restart HDT so it correctly starts working again.

One game I activated overlay with 1 card left in the deck but HDT shown 5 cards left. After the game was done, it wasnt recorded as expected.

I hit legend after a few days so I started switching lists but I also stopped massing games and haven't seen it happen again yet (I play a few games per day now). My (probably wrong) assumption is that something goes wrong due to some cthun interaction, perhaps with brann or emperor. I have no clue how to find out what the problem is after the game doesn't get tracked, so if you could point me in the right direction that would be grand. I assume uploading the log.config if it happens again would suffice or do you perhaps have another hunch?

Thanks for reading my rambling!

**Comment by culinko** [comment]
Could you upload HDT logs containing those games? The log is located in %Appdata%/Roaming/HearthstoneDeckTracker/Logs. Also, upload the Replays if they have been recorded as well.

**Comment by zedor** [comment]
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/296906/hdt_log.txt)
just noticed right now that it happened again. last recorded game started 05:26 and lasted for 9 mins. as you can see, game after that was against a tempo mage with yogg saron (which was recorded in the logs but not in the HDT stats)

**Comment by zedor** [comment]
happened again. second to last game in the logs
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/300870/hdt_log.txt)

**Comment by culinko** [comment]
The last interaction in your previous report was Sylvanas and then Brawl, with 2 secrets up from the Opponent's Yogg that has been played the turn before that. Possible Traps: Dart Trap, Snake Trap, Duplicate, Effigy, Ice Block, Spellbender, Avenge, Redemption, Sacred Trial and Competitive Spirit. However, I have no idea why the tracker stopped after the Brawl, but it's likely that it was related to one of the opponent's secret triggering.

Your last report shows Harrison Jones destroying your opponent's Doomhammer and drawing you 6 cards as the last action. I experienced a similar thing with my opponent destroying my Blood Fury (Jaraxxus weapon) with Harrison as well. The overlay stopped working after that, same with HDT log. Attaching HDT log, Power.log, and a screenshot:
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/301024/hdt_log.txt)
[Power.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/301025/Power.txt)

![hdt-bug](https://cloud.githubusercontent.com/assets/11700272/15832239/92af97c8-2c21-11e6-87fc-71d25a5db92e.png)

**Comment by culinko** [comment]
Happened again today. I played Harrison Jones into opponent's Doomhammer with 6 charges. Same issue, tracker stopped recording after it happened.
Log (last match): [hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/316836/hdt_log.txt)

**Comment by Epix37** [comment]
Gonna look into this today.
