### ISSUE TITLE
Not tracking all Arena stats

### ISSUE THREAD

**Issue by nicholberry** [HearthSim/Hearthstone-Deck-Tracker#2521]
Started a new Arena today and it did (correctly) create the deck in deck tracker, and did populate the deck onto hearthstone play screen, but it failed to track the first two games. Only tracked the third and fourth which now shows I'm 2-0... and I should 3-1. Is there a way to manually correct this?

**Comment by culinko** [comment]
You can add a game to your Arena deck manually. Click Stats -> Arena -> Runs & matches, select the desired deck and click 'Add game'.
