### ISSUE TITLE
What is the default hearthstone path?

### ISSUE THREAD

**Issue by pautpy** [HearthSim/Hearthstone-Deck-Tracker#2531]
I have my HDT to start HS every time it launches, but even though it starts HS fine, it says that it could not find the bnet launcher.

**Comment by Epix37** [comment]
Hearthstone / Battle.net are not started from any path but rather via `battlenet://` and `battlenet://WTCG`. If it takes longer than 10 seconds to start the battle.net app, HDT will not try to start hearthstone.

This might be an issue on slow machines. Does the battle.net app start eventually for you? How long does it take?

**Comment by pautpy** [comment]
@Epix37 You are correct. When Bnet+HS launches quickly, I do not get the pop-up. I guess it's at times when the PC's running slowly. In any case, could you tell me the original path for "set Hearthstone path" because I fiddled with it a couple months ago, and I want to make sure it's the right path.

**Comment by Epix37** [comment]
It's whatever your install location is. If HDT is working (i.e. cards are being tracked), the path is correct.

**Comment by culinko** [comment]
Closing in favor of #1372.
