### ISSUE TITLE
"Export to Hearthstone" adds the first 1-2 cards incorrectly

### ISSUE THREAD

**Issue by Jakub-CZ** [HearthSim/Hearthstone-Deck-Tracker#2532]
Occurs when `Auto clear filters` option is on.
Instead of the first 1-2 cards (depending on how many are in the source deck list on the first position), 1-2 cheapest class cards are added to the deck.

Issue doesn't occur when the option is off, or when using otherwise unnecessarily slow speed of the export. Apparently, the animation of the card set filter list is too slow.

Increasing `Wait x seconds before starting` doesn't help.

Could an extra delay be added, just once after clearing the filters?

**Comment by theVDude** [comment]
I've had a similar issue, either with the 0 mana filter staying selected or it missing typing in the first cards completely.

**Comment by azeier** [comment]
HDT now uses Hearthstones native deck string importing system.
