### ISSUE TITLE
Critical crash error

### ISSUE THREAD

**Issue by NITRO86sp** [HearthSim/Hearthstone-Deck-Tracker#2536]
[Crash report 2952016-2011.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/288476/Crash.report.2952016-2011.txt)
Right click on a deck-> Link to new URL -> writing one of those names suggested -> critical error which crashes HDT.

**Comment by Epix37** [comment]
Please post the generated crash report.

**Comment by NITRO86sp** [comment]
Edited the first post with it :)
