### ISSUE TITLE
wild cards not showing up

### ISSUE THREAD

**Issue by gardian06** [HearthSim/Hearthstone-Deck-Tracker#2537]
I was trying to create a tavern brawl deck, and/or a constructed deck, and several of the wild cards did not show up at all in the selectable/searchable list. requiring me to use no deck mode.

as far as I am aware every tavern brawl to date has allowed wild cards

the tracker still has all of my saved constructed decks, but does not allow me to create wild decks.

**Comment by Epix37** [comment]
There is a `include wild-only cards` at the bottom of the card list when editing a deck. Make sure it's checked.
