### ISSUE TITLE
need totem counter and N'zoth counter。

### ISSUE THREAD

**Issue by sdbds** [HearthSim/Hearthstone-Deck-Tracker#2538]
when i use shaman or VS shaman，i dont know how many mana Things form blow cost。
same as N‘zoth。

**Comment by serjoscha87** [comment]
Agree with N'zoth! My favorite deck is the N'zoth hunter and a quick overview of deathrattle minions that already died would be nice.

**Comment by Epix37** [comment]
Duplicate #1532 and #2439.
