### ISSUE TITLE
Stats reset after every game

### ISSUE THREAD

**Issue by n4ru** [HearthSim/Hearthstone-Deck-Tracker#2539]
I created a new deck on the latest version of deck tracker, went to play a few games, and realized my winrate is shown as 0-0 both above the Player deck and in stats. The deck selection menu shows no stats as well despite over a dozen games played.

Observing the counter, it DOES update at the end of each game, and then once I am returned to the menu to queue again, it reverts almost immediately back to 0 - 0.

**Comment by Epix37** [comment]
This sounds like you have the mode you are playing set to not be recorded (`optoins > tracker > stats`) - possibly due to rank(ed) detection failing, for that see here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#ranked

**Comment by n4ru** [comment]
I do have the correct mode set to be recorded, however I am running an an ultrawide monitor which may lead to the detection failing.

**Comment by Epix37** [comment]
You can edit the game mode in the post-game notification.

However, the next release will also fix game mode detection :).

**Comment by Epix37** [comment]
Should no longer be an issue with v0.15
