### ISSUE TITLE
End of game crash

### ISSUE THREAD

**Issue by riQQ** [HearthSim/Hearthstone-Deck-Tracker#2540]
Using the v0.14.9 hsreplay beta7 a NullReferenceException occurred at the end of a game. See attached log.

[Crash report](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/288440/Crash.report.2952016-1838.txt)

**Comment by Epix37** [comment]
Should be fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/f93f42d3250d5c642bdb8224e692cd831d54bc6f
