### ISSUE TITLE
The Deck overlay is too big and can't make it smaller

### ISSUE THREAD

**Issue by krazypunk1018** [HearthSim/Hearthstone-Deck-Tracker#2541]
So I had to reinstall windows and gave my computer some new upgrades, I reinstalled hearthstone and the deck tracker and now the overlay is huge compared to before. When I tried to resize it it only lets me resize it the long way from top to bottom like moving it up or down which wasn't my problem its that the overlay is too wide now and it won't let me make it smaller. Any way around that?

**Comment by krazypunk1018** [comment]
Well I guess forget about it, I just got the config file from my old harddrive and replaced the new config file in my ssd with this and it fixed the problem.

**Comment by nicholberry** [comment]
I have the same problem except I have no old config file. I just downloaded this on my laptop and the overlay takes up almost half of the screen (with both the opponents and my cards, add secret tooltips and wow, can't hardly find the enemy turn button). Am I missing something?

**Comment by azeier** [comment]
@nicholberry See my answer in #2984

**Comment by nicholberry** [comment]
Awesome! Thank you 

----- Original Message -----
