### ISSUE TITLE
Some card graphics are disappearing from the tracker

### ISSUE THREAD

**Issue by LufgtHuron** [HearthSim/Hearthstone-Deck-Tracker#2542]
Cards graphics missing from the tracker until they are drawn in game. For example: here is the cabalist tome missing until it is drawn:

![image](https://cloud.githubusercontent.com/assets/235410/15655184/7a41a506-26a3-11e6-9037-16b17d94a03c.png)

Is this a known but? is there a fix? It came up only in the last few versions and I had hoped last patch would have fixed it.

**Comment by riQQ** [comment]
Duplicate of #757.
