### ISSUE TITLE
Hearthstone not popping up on turn start

### ISSUE THREAD

**Issue by FastestAPM** [HearthSim/Hearthstone-Deck-Tracker#2544]
When I use chrome while the opponent plays his turn, it doesn't pop back up when it becomes my turn.
It does flash, however. I tried clearing and restarting HDT and it still didn't pop up on turn start.

**Comment by FastestAPM** [comment]
EDIT: It pops up only when I'm in the HDT window. It does not work when using Chrome, however.

**Comment by PattuX** [comment]
Options > Tracker > General > Tick Popup Hearthstone on turn start

**Comment by FastestAPM** [comment]
Yeah, I made sure of that already, still doesn't work.

**Comment by FastestAPM** [comment]
EDIT: I tried resetting it twice, and it Hearthstone still keeps popping up only if you're in the HDT window. Almost sure this is a bug that everyone has right now.

**Comment by culinko** [comment]
I remember Epix fixing this some time ago per my request, I'll test it later today. What OS are you using?

**Comment by Epix37** [comment]
I may have broken that with the 15 release. I'll look into it.

**Comment by Epix37** [comment]
Fixed with v0.15.2
