### ISSUE TITLE
lost ALL stats after update

### ISSUE THREAD

**Issue by depechenode** [HearthSim/Hearthstone-Deck-Tracker#2545]
Updated to newest, and lost ALL stats for ALL games / deck types

**Comment by Epix37** [comment]
You can restore backups under `options (advanced) > tracker > backups`. Try restoring the latest or the one before that.

**Comment by depechenode** [comment]
restore worked will play again and see it resets. thanks!!

**Comment by depechenode** [comment]
seems to be fine now thank you again!!!

**Comment by Epix37** [comment]
Great :+1:.
