### ISSUE TITLE
Bars of screenshot reno deck get shrunk after version 14.7

### ISSUE THREAD

**Issue by everchump** [HearthSim/Hearthstone-Deck-Tracker#2546]
Reno decks have 30 different cards normally.

So the screenshot reno deck maybe looks too high.

![](http://i64.tinypic.com/ehewlc.jpg)

The left is screened by the version 14.7, the right after 14.7

But i like the left style , it's clear and easy to see the words of the card name.

The right gets shrunk , and hard to see the words.

So is it a bug or it's supposed to be shrunk ?

**Comment by Epix37** [comment]
This happened with 14.9 I think.

**Comment by culinko** [comment]
It looks stretched out for me too in 0.15.1. It's even more stretched out if I use export Screenshot (with info).

**Comment by Epix37** [comment]
Fixed with v0.15.2
