### ISSUE TITLE
Hearthstone Deck Tracker can't open after 0.15.1 update

### ISSUE THREAD

**Issue by zjiang18** [HearthSim/Hearthstone-Deck-Tracker#2549]
HDT worked perfectly for me before, but after 0.15.1 update, it went crashed. At first it will launch, but crash whenever I tried to import, create, or modify a deck. Now it won't even launch. Example crash report attached.
[Crash report 3152016-247.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/290541/Crash.report.3152016-247.txt)
[Crash report 3152016-114.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/290544/Crash.report.3152016-114.txt)

**Comment by Epix37** [comment]
Please try if this version fixes the issue for you: https://github.com/Epix37/HDT-Test/releases/tag/v0.15.2.pre1

**Comment by zjiang18** [comment]
I used the backup files in AppData/Roaming/HearthstoneDeckTracker to replace all .xml files, and HDT worked again. I believe the update damanged some .xml files.
