### ISSUE TITLE
Triple importing the arena decks.

### ISSUE THREAD

**Issue by Vengyr** [HearthSim/Hearthstone-Deck-Tracker#2551]
The tracker imports the same Arena deck 3 times, and if you reload it, it will do the same another 3 times.

**Comment by Epix37** [comment]
Are you using any plugins? I can not reproduce this.

**Comment by Vengyr** [comment]
No plugins. I've changed the import setting to "always ask to import" so this does not happen.

**Comment by Epix37** [comment]
Could you post the log of the tripple import happening?

See here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by Vengyr** [comment]
20:42:39|Info|DeckManager.AutoImportArena >> Found new HERO_08 arena deck!
20:42:39|Info|DeckManager.AutoImportArena >> ...auto saving new arena deck.
20:42:39|Info|MainWindow.SelectDeck >> Switched to deck: Arena 31-05 08:42 (v1.0)
20:42:39|Info|DeckList.ActiveDeck >> Set active deck to: Arena 31-05 08:42 (Mage)
20:42:40|Info|LogReaderManager.Stop >> Stopped LogReaders.
20:42:40|Info|GameV2.Reset >> -------- Reset ---------
20:42:40|Info|Player.Name >> [Player] 
20:42:40|Info|Player.Name >> [Opponent] 
20:42:40|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
20:42:41|Info|LogReaderManager.Restart >> Restarting LogReaders.
20:42:41|Info|LogReader.ReadLogFile >> Found Rachelle.log.
20:42:41|Info|LogReader.ReadLogFile >> Found Arena.log.
20:42:41|Info|LogReader.ReadLogFile >> Found LoadingScreen.log.
20:42:41|Info|GameV2.CurrentMode >> LOGIN
20:42:41|Info|GameV2.CurrentMode >> HUB
20:42:41|Info|GameV2.CurrentMode >> DRAFT
20:42:41|Info|DeckManager.AutoImportArena >> Found new HERO_08 arena deck!
20:42:42|Info|DeckManager.AutoImportArena >> ...auto saving new arena deck.
20:42:42|Info|MainWindow.SelectDeck >> Switched to deck: Arena 31-05 08:42 (v1.0)
20:42:42|Info|DeckList.ActiveDeck >> Set active deck to: Arena 31-05 08:42 (Mage)
20:42:42|Info|LogReader.ReadLogFile >> Found Power.log.
20:42:42|Info|LogReader.ReadLogFile >> Found Power.log.
20:42:43|Info|LogReaderManager.Stop >> Stopped LogReaders.
20:42:43|Info|GameV2.Reset >> -------- Reset ---------
20:42:43|Info|Player.Name >> [Player] 
20:42:43|Info|Player.Name >> [Opponent] 
20:42:43|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
20:42:44|Info|LogReaderManager.Restart >> Restarting LogReaders.
20:42:44|Info|LogReader.ReadLogFile >> Found Rachelle.log.
20:42:44|Info|LogReader.ReadLogFile >> Found Arena.log.
20:42:44|Info|LogReader.ReadLogFile >> Found LoadingScreen.log.
20:42:44|Info|LogReader.ReadLogFile >> Found Power.log.
20:42:44|Info|LogReader.ReadLogFile >> Found Power.log.
20:42:45|Info|GameV2.CurrentMode >> LOGIN
20:42:45|Info|GameV2.CurrentMode >> HUB
20:42:45|Info|GameV2.CurrentMode >> DRAFT

Right now it saved twice. Weird. Used to be stable 3 before.

**Comment by Epix37** [comment]
Pretty sure I found the issue. Could you try this release: https://github.com/Epix37/HDT-Test/releases/tag/v0.15.3.pre1
