### ISSUE TITLE
Sync with Hearthstats

### ISSUE THREAD

**Issue by pr0teck** [HearthSim/Hearthstone-Deck-Tracker#2555]
I had a history of constructed matches during the season.
Then I decided to upload these history to Hearthstats site to have statistic available from the web.
After login/password of Hearthstats setup and Sync all my history was deleted.
I suppose Deck Tracker downloaded empty history from Hearthstats instead of uploading to.
If it's correct behavioir then at least warning should be shown before deleting.

**Comment by Epix37** [comment]
Definitely not the intended behavior.

You can restore backups under `options (advanced) > tracker > backups`.

**Comment by pr0teck** [comment]
Oops, my fault.
Season was finished at the same time so all my matches are in Last Season filter.

**Comment by judge2020** [comment]
HearthStats is no longer supported by HDT, a new synchronization system is planned for HSReplay.
