### ISSUE TITLE
Sorting one-time glitch

### ISSUE THREAD

**Issue by Sombres** [HearthSim/Hearthstone-Deck-Tracker#2559]
While drafting a new arena deck today, this happened:
![hdt_sorting_glitch](https://cloud.githubusercontent.com/assets/15704735/15701790/b2dd173a-27dc-11e6-9afe-2968b313b324.png)
The date format is DD/MM/YY, those in DD-MM format are from 2015. And a deck from today landed at the bottom of the list (there are many others drafted decks in the former format and they are sorted as expected). I tried restarting, changing sorting settings, nothing helped.
Another weird thing is, I use Arena Helper plugin and today for the first time in many many months, a duplicate deck was created.
All of this happened after downloading v0.15.2

**Comment by GiggliG** [comment]
Isnt that how they should be sorted? Your bottom deck is "Arena **Run** xxxx" others are just "Arena xxxx"

**Comment by Epix37** [comment]
Related to https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2551, this is fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/76c0209d0d3842a7991ee7ac7081d6d0a5671d79. There should be another update later today.
