### ISSUE TITLE
C'thun & Yogg counters

### ISSUE THREAD

**Issue by piotr9k** [HearthSim/Hearthstone-Deck-Tracker#2560]
They are never displayed, nowhere to be found, no matter if the setting is set to Always or Auto. There are no other additional 'windows' to add in options that would be specifically counting said cards' attack values or spell numbers.

I don't know what I'm missing...

**Comment by jleclanche** [comment]
I'd say you're missing the counters.

**Comment by Epix37** [comment]
Those counter are displayed on the right side (left of the player deck list) on the overlay. 

Try unlocking the overlay (options > overlay > unlock), they should be displayed in blue. If they are not, try resetting.

**Comment by piotr9k** [comment]
Where exactly?[http://i.imgur.com/JkFWPfS.png](url) This looks the same while playing, as in, no new indicators appear other than what you see there.

**Comment by Epix37** [comment]
This feature is only visible in the **overlay**, not in the deck windows.

**Comment by piotr9k** [comment]
Welp, that explains it. Thanks Epix.
