### ISSUE TITLE
Uneven Permissions V15.3 pre

### ISSUE THREAD

**Issue by tknights2015** [HearthSim/Hearthstone-Deck-Tracker#2561]
I get the uneven permissions when I run as admin or not as admin.
![uneven permissions](https://cloud.githubusercontent.com/assets/16232528/15718098/013a6996-27e7-11e6-87f2-66be5dca0f5f.JPG)

**Comment by Epix37** [comment]
This does not happen on 15.2?

**Comment by Epix37** [comment]
Try starting hearthstone before you start hdt.

**Comment by V3nomEX** [comment]
Hi Epix. Get same issue running 15.2. Have run as admin/non admin, have tried reinstalling HDT as well, still does not resolve issue. For me, error message is prompted right after I finish a match

**Comment by Epix37** [comment]
Hmm.. this should only trigger when you start hearthstone for the first time. I'll try to find the issue and upload a version for you to test later on.

**Comment by Epix37** [comment]
Could you post the hdt log after getting that message? [(see here)](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)

**Comment by V3nomEX** [comment]
Latest log attached: http://pastebin.com/iR1m1HGg

**Comment by Epix37** [comment]
Please see if you are still having issues with this release: https://github.com/Epix37/HDT-Test/releases/tag/v0.15.3.pre2

**Comment by V3nomEX** [comment]
Thx Epix. Will check and let you know

**Comment by tknights2015** [comment]
Will test later today also

**Comment by tknights2015** [comment]
This seem to have been fixed for me in v0.15.3.pre2.

**Comment by V3nomEX** [comment]
Same here, thanks so much Epix!!!

**Comment by wounds** [comment]
I'm having uneven permissions issue on the latest version as well regardless of which client i start first or running as administrator. Even created exceptions on firewall etc. Please help. It sometimes work after 3 times re-opening and closing hearthstone and hdt.

**Comment by TheSaintBol** [comment]
same here
