### ISSUE TITLE
Forced manual update on subsequent update after every automatic update.

### ISSUE THREAD

**Issue by Kiltedbear** [HearthSim/Hearthstone-Deck-Tracker#2562]
For the last several updates I have noticed that after an automatic update, the subsequent update will fail and give a "something went wrong" error and asks me to do a manual update. After the manual update, the next auto-update will work, but then the following will fail again. It's weird and getting to the point where I won't update unless I have to, because the manual updates are getting tedious. I saw somebody else had this same issue and I think was resolved with a new install, however I did a new install with one of the manual updates and after the next auto-update, the following update had the same issue, so I don't think my issue is the same. Why does it work, then not work, then work and then not work, depending on if the last install was manual or automatic?

Creating temp file directory
Downloading latest version... 23323/23323KB (100%)
Extracting files...
Writing AForge.dll
Writing AForge.Imaging.dll
Writing AForge.Math.dll
Writing De.TorstenMandelkow.MetroChart.dll
Writing Garlic.dll
Writing HDTUninstaller.exe
Writing HDTUpdate.exe
There was a problem updating to the latest version. Pressing any key will direct you to the manual download.

**Comment by Epix37** [comment]
There will be a new update system in the somewhat near future.

**Comment by Kiltedbear** [comment]
OK, thx.

**Comment by Epix37** [comment]
Started working on the new updating system. This should get fixed soon.

**Comment by azeier** [comment]
This should be fixed with the new installer. If you didn't upgrade in HDT already, get it here: https://hsdecktracker.net/
