### ISSUE TITLE
Replays Gone From Tracker

### ISSUE THREAD

**Issue by fixedstraightsword** [HearthSim/Hearthstone-Deck-Tracker#2563]
When I go to STATS -> SELECT REPLAY, I see only my most recent game (played today, about an hour ago.) The folder where the replay files are stored still has all my replays, including the most recent one. 
While I have the opportunity: Great work on the tracker, thank you. 
Please see attached:
![deck tracker replay menu](https://cloud.githubusercontent.com/assets/19697326/15726833/cd0d28ea-2807-11e6-807b-e5bc472ddfc2.png)
![deck tracker replay folder](https://cloud.githubusercontent.com/assets/19697326/15726895/28820e70-2808-11e6-933c-683be8207e3b.png)

**Comment by andburn** [comment]
The `Time` filter defaults to `Season` (the current month), so you're only getting June games. Set it to something else e.g. `AllTime`.

**Comment by fixedstraightsword** [comment]
You're right. I feel so dumb dude. Thanks. Papa bless.
