### ISSUE TITLE
Deck tracker only working as an Overlay

### ISSUE THREAD

**Issue by Zanzaa** [HearthSim/Hearthstone-Deck-Tracker#2564]
My deck tracker started to bug out and now it only acts as an overlay. There is no interaction to cards drawn by me, the opponent or anything in general. If i hit the 'Hide in Menu' option, it disappears completely, as if even though I am in the game, it still thinks I'm in the menu. I've tried redownloading, using the older versions, trying the newer versions and nothing has worked. Is there a solution?

**Comment by riQQ** [comment]
https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#not-working
