### ISSUE TITLE
Move stats from a deck to another

### ISSUE THREAD

**Issue by gbalme** [HearthSim/Hearthstone-Deck-Tracker#2565]
Hi,

I have a deck which is a Chaman deck with Chaman cards, but which is identified inside HDT to the warlock class for some reasons. I have now created the correct chaman deck associated with chaman class and want to move the stats (the 18 games played) associated with the first deck to the new one.

How can I do that ?

(If I could just change the class associated to a deck, that would work too because I would just have to change the class of the first deck from warlock to chaman, but I haven't seen any way to do that)

Thank you

**Comment by riQQ** [comment]
You already created #2547.
