### ISSUE TITLE
Export to Hearthstone not working

### ISSUE THREAD

**Issue by lawyiao93** [HearthSim/Hearthstone-Deck-Tracker#2566]
The "Export to Hearthstone" from HDT doesn't work as it will not import some cards into a new deck stating I don't have them but I do.

Is there a solution? Thanks

**Comment by Epix37** [comment]
See here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#exporting

**Comment by lawyiao93** [comment]
thank you very much!
