### ISSUE TITLE
Empty number of turns and duration in "Add new game" dialog reduce average game stats

### ISSUE THREAD

**Issue by RedenCalm** [HearthSim/Hearthstone-Deck-Tracker#2567]
Sometimes I play on my Android phone and, therefore, I'm unable to use HDT. But I'd like to still collect W/L overall stats (and against concrete classes too). So, after playing on phone, I use "Add new game to active deck" feature and add these games by hand. I'm able to remember result (win/loss/draw), opponent's class, my rank and was I on coin on not. But of course, I often don't know number of turns and duration of the game in minutes. They equal to zero by default, it kinda works: I'm able to add game without having to put something random into these fields.

![add-game-dialog](https://cloud.githubusercontent.com/assets/19716844/15759091/119dd6bc-2916-11e6-879a-29a3d2dbfd29.PNG)

But it has disadvantage: average game length calculates wrong.

For example, I played 9 games this season with Control Warrior: 4 on PC and 5 on phone.

![matches-list](https://cloud.githubusercontent.com/assets/19716844/15759090/119cc5a6-2916-11e6-9d99-5ee07e9b8237.PNG)

I played 4 games on PC 54 minutes (15+26+6+7), so, 16 minutes per game. But add 5 "zero-minute" games on phone and what I see in summary stats is "Average game: 6.0 min, 7.1 turns", which is not what you should expect with Control Warrior, you know :)

![wrong-average-stats](https://cloud.githubusercontent.com/assets/19716844/15759089/119ca256-2916-11e6-933e-6364a5c6549f.PNG)

So, I suggest to do something of this:
1. Just not to count 0-minutes and 0-turns games in average game statistics. I think, that makes sense, because you shouldn't want even recorded games with 0-minutes and 0-turns in average stats (like, instant disconnect or concede from opponent, etc.). Also, I guess, it should be kinda easy to fix.
2. Have something like "-" or "null" or something else by default in fields "Turns" and "Duration (min)" in add game dialog. Again, such games shouldn't be counted in average game length stats. I think, first option is better.
3. To be able somehow to import games from Android, maybe, even with proper game length. I guess, that's kinda hard to develop (or it's already developed, but I failed to find it).

**Comment by Epix37** [comment]
I agree the first option is the best way to go.

As for number 3, maybe some day :).
