### ISSUE TITLE
Importing modified basic decks not working

### ISSUE THREAD

**Issue by tknights2015** [HearthSim/Hearthstone-Deck-Tracker#2571]
Changed an existing deck, import did not recognize that the deck has been changed and upon import says " no new deck found"

http://pastebin.com/FfxZ9AzR

**Comment by Epix37** [comment]
any chance a deck version with those cards already exists?

**Comment by tknights2015** [comment]
If you mean another deck, then no unless I archived a deck instead of deleting it. And this would be unlikely as this is a Free to play account and I usually add cards or change the deck when I get new cards on the account.

**Comment by Epix37** [comment]
there's issues with importing updated basic decks I think

**Comment by tknights2015** [comment]
For the record, this was not a basic deck  that was originally.  The import is working now with the same exact deck and changes. Made no app or HS changes.

**Comment by Epix37** [comment]
Weird - closing this for now then.
