### ISSUE TITLE
When exporting the tracker doesn't click on the cards or anything

### ISSUE THREAD

**Issue by 4Prod1gy** [HearthSim/Hearthstone-Deck-Tracker#2574]
When I'm trying to export a deck from my deck tracker it just keeps moving around without clicking anything! I need help and I've had this issue a long time

**Comment by andburn** [comment]
Have you tried [these step in the FAQ](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#exporting-is-not-working-properly--missing-cards)?

**Comment by 4Prod1gy** [comment]
First nothing happened and my decktracker fucked up and deleted all my decks and then i had to restart my computer since nothing was happening but now it's working! Thanks for the help man!
