### ISSUE TITLE
HDT Won't import to Hearthstone

### ISSUE THREAD

**Issue by Jacobx89** [HearthSim/Hearthstone-Deck-Tracker#2577]
I've had this issue since the game updated to include the new formats, For some reason no matter what I do HDT just puts the name of the cards in but only clicks to add one or two of them. eg. Export > clicks on deck helper a heap of times > changes to standard format > types names > only adds 4 cards even though I see them coming up.

THIS IS WHAT ITS DOING = https://youtu.be/NzuUka8ygoo
# What I have tried:
- Resetting Hearthstones settings (HDT on twitter told me it was to do with resolutions) by deleting the settings folder in C:/user/appdata/blizzard/hearthstone settings.txt etc. 
- Re downloading HDT
- Resetting HDTs settings by deleting the entire appdata folder for HDT
- Changing the settings in HDT advanced options to not auto clear, not auto remove cards and changed the speed to Very slow
- Running HDT as Admin
- Windowed/Non-windowed modes
- Multiple resolutions in both windowed and non-windowed
- Tried on both main and secondary monitors

Still no resolve

**Comment by Epix37** [comment]
Try running hdt as admin

**Comment by Jacobx89** [comment]
Tried that, No change.

**Comment by Jacobx89** [comment]
Tried that, no luck

**Comment by Epix37** [comment]
Judging from the video in #2601 (you could just have posted that here ;)), HDT does not get the correct resolution for Hearthstone. Try running it in windowed mode.

**Comment by Jacobx89** [comment]
Tried that no dice

**Comment by Jacobx89** [comment]
I've tried that, Originally the game was running in windowed mode before the issue started happening, The only reason its full screen is because I deleted the hearthstone config folder and it reset the resolutions etc.

**Comment by Jacobx89** [comment]
Does the app not support duel screens? I've just realized that my duel screens are a somewhat recent addition =/

**Comment by Epix37** [comment]
Actually, yeah. It's clicking the deck and search bar just fine, that would not work if there was a resolution problem. But it's definitely not clicking the cards in the correct position though (too far to the top left), which could only be incorrect config settings - but if you reset those that can't be it either.

Multiple screens in general work just fine. Are you maybe using any multi screen software?

**Comment by Jacobx89** [comment]
No, No multi-screen fancy software, Just standard windows 10 duel screens with the right screen being the main screen, Is there a way I can force hearthstone into a specific resolution?

**Comment by Epix37** [comment]
Only from the in-game options menu. Maybe there's software to do it, I don't know.

Try disconnecting the second monitor and see if that helps. Would be a good starting point.
