### ISSUE TITLE
HS crash

### ISSUE THREAD

**Issue by Kroneker** [HearthSim/Hearthstone-Deck-Tracker#2578]
11:56:22|Info|GameV2.Reset >> -------- Reset ---------
11:56:22|Info|Player.Name >> [Player] 
11:56:22|Info|Player.Name >> [Opponent] 
11:56:22|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
11:56:22|Info|HearthStatsAPI.LoadCredentials >> Loading stored credentials...
11:56:30|Info|OverlayWindow.Update >> Refreshed overlay topmost status
11:56:32|Info|MainWindow.SelectDeck >> Switched to deck: Beast Druid (v1.0)
11:56:32|Warning|LogReaderManager.Stop >> LogReaders could not be stopped, stop already in progress.
11:56:32|Info|GameV2.Reset >> -------- Reset ---------
11:56:32|Info|Player.Name >> [Player] 
11:56:32|Info|Player.Name >> [Opponent] 
11:56:32|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
11:56:34|Info|DataIssueResolver.RemoveDuplicateMatches >> Checking for duplicate matches...
11:56:34|Info|BackupManager.Run >> Running BackupManager
11:56:34|Info|BackupManager.Run >> Backup for today already exists
11:56:35|Info|PluginManager.LoadPlugins >> Loading Plugins...
11:56:35|Info|GitHub.CheckForUpdate >> HearthSim/Hearthstone-Deck-Tracker: Checking for updates (current=0.15.2.0, pre-release=False)
11:56:35|Info|OverlayWindow.Update >> Refreshed overlay topmost status
11:56:36|Info|LogReader.ReadLogFile >> Found Rachelle.log.
11:56:36|Info|LogReader.ReadLogFile >> Found Power.log.
11:56:36|Info|LogReader.ReadLogFile >> Found Net.log.
11:56:36|Info|LogReader.ReadLogFile >> Found LoadingScreen.log.
11:56:36|Info|LogReader.ReadLogFile >> Found FullScreenFX.log.
11:56:36|Info|LogReader.ReadLogFile >> Found Power.log.
11:56:38|Info|GitHub.CheckForUpdate >> HearthSim/Hearthstone-Deck-Tracker: We are up-to-date (latest=v0.15.2, pre-release=False)
11:56:38|Info|GameV2.CurrentMode >> TOURNAMENT
11:56:39|Info|DeckImporter.FromConstructed >> Found 7 decks, 1 new
11:56:49|Info|OverlayWindow.Update >> Refreshed overlay topmost status
11:56:54|Info|FullScreenFxHandler.Handle >> Now in queue (04/06/2016 11:56:53)
11:56:54|Info|FullScreenFxHandler.AutoSelectDeckById >> Found selected deck: Beast Druid
11:56:54|Info|FullScreenFxHandler.AutoSelectDeckById >> Already using the correct deck

**Comment by riQQ** [comment]
Does the folder `<HDT dir>\Crash reports` exist and are there any crash logs in it? Are there any error log entries in the windows event viewer (Press `Windows key + R`, input `eventvwr` and confirm. Then go to `windows log > application`)?
