### ISSUE TITLE
Doomcallered C'thun shows a different graphic than normal C'thun

### ISSUE THREAD

**Issue by ericBG** [HearthSim/Hearthstone-Deck-Tracker#2581]
When you show a tooltip of the C'thun generated from Doomcaller, it shows like the bottom portion of its body, as opposed to the head, which is what is shown when you play it in your deck.

**Comment by andburn** [comment]
For reference:

![og_280](https://cloud.githubusercontent.com/assets/5419653/15821121/ca2d77b0-2be5-11e6-96a5-8105fbc5af9d.png) OG_280
![og_279](https://cloud.githubusercontent.com/assets/5419653/15821124/cd66f0aa-2be5-11e6-9a2c-7b5409c331f7.png) OG_279

**Comment by Epix37** [comment]
@andburn are those the coordinates from the game or custom ones?

**Comment by andburn** [comment]
279 is custom I somehow messed it up, so you can replace it with a copy of 280. I'll make a note of it.
