### ISSUE TITLE
Not prioritizing golden cards

### ISSUE THREAD

**Issue by 1m2o** [HearthSim/Hearthstone-Deck-Tracker#2583]
If you don't priotize golden cards and you have like 1 golden and 1 non golden it will add only 1 non golden so it won't import golden card even if it's necessery to complete the deck.

**Comment by riQQ** [comment]
@Epix37 I debugged this and could reproduce it. It doesn't detect the lock correctly. This has worked some time ago, when i made pr #1496.

**Comment by f0qus** [comment]
Is this the reason why it will not detect certain gold cards?  For instance, I modified my deck and dropped a normal Cabal Shadow Priest and added a golden Sylvannas.  The deck list did not update and I get a message about the card not being found, and it does not track stats anymore for this deck.

**Comment by riQQ** [comment]
The old export method was removed.
