### ISSUE TITLE
Deck Tracker starts a different Launcher?

### ISSUE THREAD

**Issue by punica2** [HearthSim/Hearthstone-Deck-Tracker#2587]
Hi,

my Deck Tracker seems to start a different Battle.net Launcher because it always says "Session expired" and I have to login to Battle.net everytime. Additionally, my games are shown in a different order in contrast to when I use the Hearthstone shortcut on my desktop and patches are applied again, even when I have already installed them using the shortcut on my desktop.
Is there a way to fix this?

best regards

**Comment by Epix37** [comment]
HDT starts the launcher and Hearthstone using the `battlenet://` and `battlenet://WTCG` commands.

Maybe try reinstalling the Battle.net app and/or Hearthstone.

**Comment by punica2** [comment]
Running HDT as admin solved the problem.

Thank you!
