### ISSUE TITLE
Frequent crashes in Windows 10

### ISSUE THREAD

**Issue by GunnarStahl** [HearthSim/Hearthstone-Deck-Tracker#2590]
I am experiencing lots of crash while using HDT these days.

I recently updated to Windows 10 (well, I was forced to... lel) and I remarked lots of crashes.

It is sometimes in game that the client freezes. Some other times it's when I am using it (creating, editing decks for instance)

Am I the only one that this stuff happens?

**Comment by riQQ** [comment]
Does the folder `<HDT dir>\Crash reports` exist and are there any crash logs in it? Are there any error log entries in the windows event viewer (Press `Windows key + R`, input `eventvwr` and confirm. Then go to `windows log > application`)?

**Comment by GunnarStahl** [comment]
Yes, there is a single .txt file in the Crash Reports directory. (a big file if you ask me)

It seems there is nothing in the Event viewer though.

What I am experiencing is that program sometimes stop to function at random moment. It freezes and then, I am forced to shut it down.

**Comment by riQQ** [comment]
Okay, so it freezes and doesn't crash. This won't show up in the crash reports. But can you please upload this file never the less.

**Comment by GunnarStahl** [comment]
Just saw that the file are dated from 2015. I had Win 7 at that time.

However, I uploaded a screen capture from my Event Viewer.

![capture](https://cloud.githubusercontent.com/assets/16649527/15906158/a954d6c2-2d85-11e6-99cf-744f53024c0e.PNG)

**Comment by GunnarStahl** [comment]
[THIS IS FROM APPLICATION ERROR]

Nom de l’application défaillante Hearthstone Deck Tracker.exe, version : 0.15.3.0, horodatage : 0x57540435
Nom du module défaillant : KERNELBASE.dll, version : 10.0.10586.306, horodatage : 0x571afb9a
Code d’exception : 0xe0434352
Décalage d’erreur : 0x000bdae8
ID du processus défaillant : 0xd04
Heure de début de l’application défaillante : 0x01d1c18631819afd
Chemin d’accès de l’application défaillante : C:\Hearthstone Deck Tracker\Hearthstone Deck Tracker.exe
Chemin d’accès du module défaillant: C:\WINDOWS\SYSTEM32\KERNELBASE.dll
ID de rapport : b51c3299-bbbe-4471-9886-cd9833bf5cf8
Nom complet du package défaillant : 
ID de l’application relative au package défaillant : 

[THIS IS FROM .NET RUNTIME]

Application : Hearthstone Deck Tracker.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : System.OutOfMemoryException
   à Hearthstone_Deck_Tracker.LogReader.LogReader.ReadLogFile()
   à System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   à System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   à System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   à System.Threading.ThreadHelper.ThreadStart()

**Comment by riQQ** [comment]
Okay, probably same or similar issue as #2590.

**Comment by GunnarStahl** [comment]
Thank you, I will have a look.

**Comment by ruisilveira** [comment]
Im also experiencing freezes on windows 10!
