### ISSUE TITLE
Yogg-Sauron counter is shown in Brawl even though it's turned off

### ISSUE THREAD

**Issue by riQQ** [HearthSim/Hearthstone-Deck-Tracker#2591]
Although i have set `Show Yogg-Saron counter` to never, it is shown in this weeks brawl.

**Comment by Epix37** [comment]
Seems to work fine for me :/.

**Comment by riQQ** [comment]
For reference, it was the `Cloneball!` Tavern Brawl. I don't think I had the problem in the reprise this year. So I'm closing this issue.
