### ISSUE TITLE
Stats for Ranked Mode incomplete

### ISSUE THREAD

**Issue by GiggliG** [HearthSim/Hearthstone-Deck-Tracker#2593]
If you have been using HDT a long time, you'll have stats from the period before HDT recorded the rank. These show up as a rank of "-"

When you view stats and set mode to Ranked, none of these games are included in the stats, because their rank is not a number. Even if you choose the most permissive rank range (L1 to rank 25), they do not get included in the show stats.

I would like to be able to set a default rank (like 20, or even any other number - maybe whatever you think you usually play around), and have them be included whenever the filter range includes that number.

PS: I'll add (admittedly, not for the first time) that it would be _really_ great to have some kind of mass editing facility, to change say rank - but especially region - for large groups of games en masse. 

Edit: it seems there's a little quirkiness about this. Sometimes it does show all the "-" ranked games, and sometimes it doesn't. 
If I change the rank from showing L1 to 25, to, say, 1 to 25, those "-" ranks dont get displayed. If I change it back to L1, they do start being displayed again.

Maybe there should be a "reset to default" there, and in any case the stats for those "-" ranks should be being displayed when the outer rank is 25.

**Comment by Epix37** [comment]
The max rank field can now be left empty to include game without a rank in the statistics.

As for your regions issue: I think you had decks tagged with the region at some point, is that still the case? I could write a plugin for you that will set the region for all matches (without a region) on a deck based on a certain tag. Just let me know what tags exactly you use for which region.
