### ISSUE TITLE
Bug with old players (from beta of HS).

### ISSUE THREAD

**Issue by Sanrinsei** [HearthSim/Hearthstone-Deck-Tracker#2594]
Hi there!
I play in HS from beta-test. All this time I dont reinstall client of game, so it was kept origin from game realese. Few day ago I found HearthStone Deck Tracker, install it and...and HDT dont work. I tried all thins from FAQ, I rewrite all log files. HDT starting, but due game I dont see any things: my cards dont "leave" my deck from HDT client, Import dont work too, I dont see what card enemy play on the left side (his deck in HDT interface). 

I try to find answer, and I had have insigt! My .exe file have "Beta" in his name, so, in my mind, this was a problem for HDT.

After reinstall game, all "Beta" names leaved my files, and HDT work properly. Dont think a lot people can make a deal with this bug, but I told you about it. Maybe, in can be FAQ'ed for future players. 

Thank a lot and top rating for your deck :)

**Comment by Sanrinsei** [comment]
if you need more info you can contact me with battle tag ID SanrinSei#2191 (not AD)

**Comment by Epix37** [comment]
Thanks for letting us know!
