### ISSUE TITLE
Chooses wrong deck for arena

### ISSUE THREAD

**Issue by Vengyr** [HearthSim/Hearthstone-Deck-Tracker#2596]
So before every arena game (in this run at least) it starts with choosing my previous arena deck as an active. Have to re-select my actual deck.

**Comment by Vengyr** [comment]
That's the log
15:41:27|Info|HearthStatsManager.UploadArenaMatchAsync >> success uploading arena match Win vs Shaman, 11.06.2016 15:35:18
15:41:32|Info|DeckManager.AutoImportArena >> Found new HERO_04a arena deck!
15:41:32|Info|DeckManager.AutoImportArena >> ...but we already have that one. Discarding.
15:41:33|Info|GameV2.CurrentMode >> DRAFT
15:41:33|Info|GameEventHandler.HandleInMenu >> Game is now in menu.
15:41:33|Info|OverlayWindow.Update >> Refreshed overlay topmost status
15:41:33|Info|GameResultNotificationWindow..ctor >> Now showing
15:41:33|Info|GameEventHandler.SaveAndUpdateStats >> Saving DeckStats
15:41:35|Info|FullScreenFxHandler.Handle >> Now in queue (11.06.2016 15:41:34)
15:41:35|Info|FullScreenFxHandler.AutoSelectArenaDeck >> Switching to arena deck deck: Arena 10-06 04:29
15:41:35|Info|MainWindow.SelectDeck >> Switched to deck: Arena 10-06 04:29 (v1.0)
15:41:35|Info|DeckList.ActiveDeck >> Set active deck to: Arena 10-06 04:29 (Mage)
15:41:38|Info|LogReaderManager.Stop >> Stopped LogReaders.
15:41:38|Info|GameV2.Reset >> -------- Reset ---------
15:41:38|Info|Player.Name >> [Player] 
15:41:38|Info|Player.Name >> [Opponent] 
15:41:38|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
15:41:39|Info|LogReaderManager.Restart >> Restarting LogReaders.
15:41:39|Info|LogReader.ReadLogFile >> Found Power.log.
15:41:39|Info|LogReader.ReadLogFile >> Found Net.log.
15:41:39|Info|LogReader.ReadLogFile >> Found Rachelle.log.
15:41:39|Info|LogReader.ReadLogFile >> Found Arena.log.
15:41:39|Info|LogReader.ReadLogFile >> Found Power.log.
15:41:39|Info|LogReader.ReadLogFile >> Found LoadingScreen.log.
15:41:39|Info|GameV2.CurrentMode >> DRAFT
15:41:45|Info|GameEventHandler.HandleGameStart >> --- Game start ---
15:41:45|Info|GameV2.Reset >> -------- Reset ---------
15:41:45|Info|Player.Name >> [Player] 
15:41:45|Info|Player.Name >> [Opponent] 
15:41:45|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
15:41:45|Info|TurnTimer.Start >> Starting turn timer
15:41:45|Warning|TurnTimer.Start >> Waiting for player entity
15:41:47|Info|Player.Draw >> [Opponent] id=5, cardId=, cardName=, zonePos=3,Info={turn=0, originalZone=DECK}
15:41:47|Info|Player.Draw >> [Opponent] id=10, cardId=, cardName=, zonePos=1,Info={turn=0, originalZone=DECK}
15:41:47|Info|Player.Draw >> [Opponent] id=11, cardId=, cardName=, zonePos=2,Info={turn=0, originalZone=DECK}
15:41:47|Info|Player.Draw >> [Player] id=38, cardId=AT_094, cardName=Flame Juggler, zonePos=1,Info={turn=0, originalZone=DECK}
15:41:47|Info|Player.Draw >> [Player] id=45, cardId=LOE_047, cardName=Tomb Spider, zonePos=4,Info={turn=0, originalZone=DECK}
15:41:47|Info|Player.Draw >> [Player] id=46, cardId=EX1_595, cardName=Cult Master, zonePos=3,Info={turn=0, originalZone=DECK}
15:41:47|Info|Player.Draw >> [Player] id=48, cardId=EX1_283, cardName=Frost Elemental, zonePos=2,Info={turn=0, originalZone=DECK}
15:41:47|Info|TagChangeActions.SetHeroAsync >> Found hero with id=64
15:41:47|Info|GameEventHandler.SetOpponentHero >> Opponent=Mage
15:41:47|Info|TagChangeActions.SetHeroAsync >> Found hero with id=66
15:41:47|Info|GameEventHandler.SetPlayerHero >> Player=Paladin
15:41:47|Info|GameV2.CurrentMode >> GAMEPLAY
15:41:47|Info|DeckManager.AutoImportArena >> Found new HERO_04a arena deck!
15:41:47|Info|DeckManager.AutoImportArena >> ...but we already have that one. Discarding.
15:41:47|Warning|DeckManager.DetectCurrentDeck >> Cards not found in deck: Flame Juggler (AT_094), Tomb Spider (LOE_047), Cult Master (EX1_595), Frost Elemental (EX1_283)
15:41:51|Info|Player.CreateInHand >> [Player] id=68, cardId=GAME_005, cardName=The Coin, zonePos=5,Info={turn=0, mark=Coin, created=true, originalZone=HAND}
15:41:51|Info|Player.Name >> [Player] Vengyr
15:41:51|Info|Player.Name >> [Opponent] Farasus
15:41:51|Info|Player.Name >> [Opponent] Farasus
15:41:51|Info|GameEventHandler.TurnStart >> --- Mulligan

**Comment by Mdzl** [comment]
+1 from me

I think i got this issue last week (I play on weekends) and today I just got it again. For some reason it keeps coming back to the last arena that already ended (and got nice x-3 score). Not sure why and what cause that

**Comment by Terrorforge** [comment]
+1

I've had this happen multiple times when playing multiple arenas one after another. Last time restarting HS and HDT solved it, but it's pretty annoying to have to do that.

**Comment by Epix37** [comment]
Will be fixed with an update later today.
