### ISSUE TITLE
Frequent freezes caused by Mirror of Doom

### ISSUE THREAD

**Issue by rafzi** [HearthSim/Hearthstone-Deck-Tracker#2597]
When playing "Mirror of Doom" (The mummy board filler from rafaam) there seems to be a high chance of freezing HDT.

Cards are no longer tracked, but the overlay keeps processing events. For example if my board is cleared, I will still be able to hover over the mummy zombies and get the tooltip in the bottom right even though they are gone.

I would estimate maybe 30-50% chance of this freeze occuring when that card is played. HDT also freezes in other situations, but I only noticed a pattern for this scenario.

**Comment by culinko** [comment]
Does this still happen in the newest version?

**Comment by rafzi** [comment]
It sounds related to the fix "•	Fixed an issue where HDT would freeze when after long animations in Hearthstone (Brawl, Harrison Jones, ...). "

Only tested a couple games, but seems fine for now. Will reopen when it happens again.
