### ISSUE TITLE
Hearthstone Deck Tracker Application Not found

### ISSUE THREAD

**Issue by Mattlinq** [HearthSim/Hearthstone-Deck-Tracker#2598]
![screenshot 63](https://cloud.githubusercontent.com/assets/19880540/15987836/8ba1ac94-2fed-11e6-8f06-f0f78725d2f8.png)
When I go to download the zip file on Mozilla Firefox on windows 10 it gives me the response that the file I just downloaded cannot be found. I just want to download the application, can someone help?

**Comment by riQQ** [comment]
Your file association for .zip files is corrupt. See http://answers.microsoft.com/en-us/windows/forum/windows_7-files/i-get-this-application-not-found-after-file/ccb7a697-0ad0-4ac1-afc2-07637dc14551 for more information.
