### ISSUE TITLE
Not clicking on cards during import to game

### ISSUE THREAD

**Issue by Jacobx89** [HearthSim/Hearthstone-Deck-Tracker#2601]
I've had this issue since the game updated to include the new formats, For some reason no matter what I do HDT just puts the name of the cards in but only clicks to add one or two of them. eg. Export > clicks on deck helper a heap of times > changes to standard format > types names > only adds 4 cards even though I see them coming up.

**THIS IS WHAT ITS DOING = https://youtu.be/NzuUka8ygoo**

What I have tried:

- Resetting Hearthstones settings (HDT on twitter told me it was to do with resolutions) by deleting the settings folder in C:/user/appdata/blizzard/hearthstone settings.txt etc.

- Re downloading HDT

- Resetting HDTs settings by deleting the entire appdata folder for HDT and then redownloading it again

- Changing the settings in HDT advanced options to not auto clear, not auto remove cards and changed the speed to Very slow

- Running HDT as Admin

- Changing hearthstones resolutions

Still no resolve :(((( 

Please someone? I haven't played hearthstone since standards release because this wont work

**Comment by Epix37** [comment]
Please don't create multiple issues on the same topic (##2577).

**Comment by Jacobx89** [comment]
Nobody was answering my original one and it was lost in the list
