### ISSUE TITLE
Bug: 10 attack not showing in replay veiwer

### ISSUE THREAD

**Issue by Rosewater1337** [HearthSim/Hearthstone-Deck-Tracker#2605]
10 attack shows as a 1 then a blank space
Here are 2 examples:
[output_log (3).txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/310969/output_log.3.txt)
[output_log (2).txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/310970/output_log.2.txt)

**Comment by gardian06** [comment]
also applies to all minnions with 10 or more stat point, example: deathwing Dragon lord.

though for some reason C'thun "when in play" (see issue here: #2795) shows the correct stat value

**Comment by azeier** [comment]
Local replay support has now been fully removed.
