### ISSUE TITLE
"Noooooooo" cards when importing from websites

### ISSUE THREAD

**Issue by maiklohse** [HearthSim/Hearthstone-Deck-Tracker#2606]
Ever since WotG came out I always get a bunch of "Nooooooooo" cards in my deck when importing from a website. Then I have to manually go in and check which ones they are and substitute - very inconvenient
![unbenannt](https://cloud.githubusercontent.com/assets/13084318/16033961/5f21e480-320f-11e6-8a85-7853eb5f1bad.PNG)

**Comment by jleclanche** [comment]
Which website are you importing from?

**Comment by TimothyLutz** [comment]
update your HDT, use the latest version.

**Comment by Epix37** [comment]
This should be fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/38480bc4bdfa85699f24dd0507475c0ac0eed6e8 (v0.14.8).

**Comment by maiklohse** [comment]
I’ll check now if there is an update available - but usually when HDT tells me there is an update I update right away…..

**Comment by Epix37** [comment]
You can see which version you are using in the bottom left of them "help" screen (button in the titlebar).

**Comment by maiklohse** [comment]
Well I'm running 0.15.3. Seems like it's not 

Von meinem iPhone gesendet

**Comment by Epix37** [comment]
And this happens with newly imported decks? Could you link one with which this happens?

**Comment by maiklohse** [comment]
This one for example http://www.hearthstonetopdecks.com/decks/bigtallguys-yogg-n-load-hunter-deck-list-guide-june-2016-season-27/
I think the "Nooooo" cards were Yogg and King's Elekk
This one : http://www.hearthstonetopdecks.com/decks/kolentos-wotog-standard-control-deathrattle-paladin/
N'zoth is pretty much ALWAYS a "Nooooooo" card when I import decks that have him in it. Also Kor'Kon Elites on Warriors for example. Always seem to be the same (kind of) cards

**Comment by Epix37** [comment]
Both of those decks import completely fine for me :/.

Try manually downloading the latest release again: https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/latest

**Comment by maiklohse** [comment]
And completely delete the old one from the HD beforehand?

Von meinem iPhone gesendet

**Comment by Epix37** [comment]
That, or you can just install it to a different location. All the data is (by default) stored independently.

**Comment by maiklohse** [comment]
Will try once I'm back at home 

Von meinem iPhone gesendet

**Comment by maiklohse** [comment]
Mainly from Hearthstonetopdecks.com. But sometimes also from Hearthpwn. Not sure if I have that problem there though. 

Von meinem iPad gesendet

**Comment by maiklohse** [comment]
So - I downloaded a brand new copy of HDT - when I opened it all my decks were in it already though - so it must pull that data from somewhere on my HD . Went to Hearthstonetopdecks and imported that Yogg Hunter Deck - 4 "Nooooooo" cards
![unbenannt](https://cloud.githubusercontent.com/assets/13084318/16045504/fd3b6158-3248-11e6-9d8b-733bc4639b80.PNG)

**Comment by Epix37** [comment]
Are you using the NetDeck Chrome extension? Try using HDTs built-in importing (`IMPORT > FROM WEB`).

**Comment by maiklohse** [comment]
Yes. Using the extension. That might be it. Will try later. Thanks!

Von meinem iPhone gesendet

**Comment by maiklohse** [comment]
So yeah - using the extension was the culprit. When I use the built in importing everything goes smooth :). Sorry for the confusion!

**Comment by Epix37** [comment]
@n4ru this might be easier to solve on your end. Hearthstonetopdecks is (and maybe other websites are, too) using some weird apostrophes.

**Comment by n4ru** [comment]
I'll check this out tonight.

**Comment by n4ru** [comment]
Actually @Epix37, the problem seems to be on your end this time :)

My extension exports the apostrophes as shown on the site (as `’`, instead of `'`). 

If you'd like I can convert them to regular apostrophes.

**Comment by n4ru** [comment]
Fixed it on my end, but for consistency's sake, maybe convert the apostrophes on your end as well? Looks like you do so with your built-in import but not from NetDeck.
