### ISSUE TITLE
feature request: load deck for opponents

### ISSUE THREAD

**Issue by vaidab** [HearthSim/Hearthstone-Deck-Tracker#2608]
At rank 5 and below I usually know what kind of deck my opponent is playing based on some key cards. I'd love it if I'd be able to load the opponent deck and see what cards he could have right inside hstracker.

Something like: Decks -> Load opponent deck -> same options as when creating a new deck.
Then the deck would have a different color so that I know those are *maybe* cards.

This would help me tremendously.

**Comment by Epix37** [comment]
Likely not something that will be supported by HDT, sorry.

See here for more info: https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues?q=is%3Aissue+deck+prediction+is%3Aclosed

**Comment by kimsey0** [comment]
@azeier: Is this still out of the question? It would be useful for online tournaments with open deck lists.
