### ISSUE TITLE
Opp. Deck vs. Move to New Window

### ISSUE THREAD

**Issue by spacian** [HearthSim/Hearthstone-Deck-Tracker#2612]
If you look at your stats in a new window (through the option at the top) and then proceed to choose the option 'opp. deck' in your match history to see which cards your opponent played, the sidebar with your opponent's deck pops up in the main window, not in the new window.

I find that irritating and counter-intuitive. I went for the new window for a bigger screen, but then have to switch back to the main window to look at the list.

That's just a minor issue though, great job with HDT :)

**Comment by Epix37** [comment]
Will be fixed with the next release.
