### ISSUE TITLE
Reset positions is not working

### ISSUE THREAD

**Issue by TemporalOnline** [HearthSim/Hearthstone-Deck-Tracker#2614]
My Yogg counter, and both my opponents Yogg AND C'thun just disappeared. I tried to reset, to no avail.

I can move and see the overlays, except for those 3, that just disappeared (even if I set all 4 to always show).

I think I see 2 windows that are just the handles, maybe they are my opponent's c'thun and/or yogg(when you set to both always you merge them to 1), but I can only move them around to no effect.

I don't remember if in the past I was able to adjust the secrets window with the "handle" in the bottom right, but right now my opponent's secrets window can't be resized, only moved.

**Comment by Epix37** [comment]
You can resize the secrets under `options > overlay > opponent`.
