### ISSUE TITLE
HDT in Xsplit

### ISSUE THREAD

**Issue by zander93** [HearthSim/Hearthstone-Deck-Tracker#2617]
Hi!

So, I started using HDT yesterday, and it's great. Love the idea of being able to keep track of the cards when I'm playing.
But, I can seem to capture it with my Xsplit GameCaster. When I finish the recording, it only shows the game, as if the HDT wasn't there.

Is there any way I can capture both, the gameplay and stats from HDT?

Thank you in advance !

**Comment by Epix37** [comment]
Yes you can! Have a look here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Streaming-Instructions

**Comment by zander93** [comment]
I should have said it's not for streaming, it's just to record gameplays, nothing more.

**Comment by Epix37** [comment]
Not sure how that works with XSplit, you might be able to do it the same way or otherwise you need to capture your screen instead of just the game. The overlay is a separate window in top of Hearthstone.

**Comment by zander93** [comment]
I was able to do it wit OBS, when instead of recording with the intention of streaming, I choose the option "Just File".

Either way, thank you for your time !
