### ISSUE TITLE
Not saving decks

### ISSUE THREAD

**Issue by vhmbr** [HearthSim/Hearthstone-Deck-Tracker#2618]
Hi there, i've been using HDT for a while, but last week this kinda bug started and i don't know what to do. Basically, when i make a new deck or edit one and then i restart the program, everything gets reset to this: http://i.imgur.com/jX8agOy.png
I know this is probably a stupid issue for some of you guys, but i'm not an expert at this things, and if anyone could help me, i'd appreciate a lot!

One more thing, i'm a brazilian and i don't know how to speak english very well, but i try!

**Comment by riQQ** [comment]
What is reset? The layout?

**Comment by vhmbr** [comment]
If i had created a deck, and then restarted the program, the deck would be deleted, and the stats would be reset to those in the printscreen.

**Comment by vhmbr** [comment]
The window size, layout and position reset too!

**Comment by Epix37** [comment]
This sounds like there's some permission problem. Try running HDT as admin.

**Comment by vhmbr** [comment]
It didn't work, but thank you for helping. If you have any other advice, i'd be grateful!

**Comment by riQQ** [comment]
Duplicate of #2552
