### ISSUE TITLE
lose all my decks and stats (even arena stats)

### ISSUE THREAD

**Issue by Werwolfsoul** [HearthSim/Hearthstone-Deck-Tracker#2619]
also it's begin shut down instead arena rewards window.
[Crash report 1562016-1621.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/323989/Crash.report.1562016-1621.txt)
[Crash report 1562016-1628.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/323993/Crash.report.1562016-1628.txt)
[Crash report 1562016-2119.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/323990/Crash.report.1562016-2119.txt)
[Crash report 1562016-2234.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/323991/Crash.report.1562016-2234.txt)
[Crash report 1762016-016.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/323992/Crash.report.1762016-016.txt)
[Crash report 1862016-210.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/323994/Crash.report.1862016-210.txt)
[Crash report 1862016-1150.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/323995/Crash.report.1862016-1150.txt)
[Crash report 1862016-1831.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/323997/Crash.report.1862016-1831.txt)
[Crash report 1962016-2134.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/323996/Crash.report.1962016-2134.txt)
[Crash report 1962016-2341.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/323998/Crash.report.1962016-2341.txt)

**Comment by Epix37** [comment]
- Delete this folder `C:\Users\Sora\AppData\Local\HearthSim`
- If you can run HDT: go to `options (advanced) > tracker > backups` and restore the latest backup.
- If you can't: go to `%AppData%/HearthstoneDeckTracker` and replace the files with the ones from the latest zip in the `Backup` directory.
