### ISSUE TITLE
Stats are not correctly recorded

### ISSUE THREAD

**Issue by brokenassapp** [HearthSim/Hearthstone-Deck-Tracker#2621]
After the update I still encountered problems regarding match history and stats:
1) The harrison bug still exists: If Harrison destroys a weapon that results in milling cards, the tracker acts normal until the game is finished, then the game usually is not recorded due to that.

2) After the harrison bug, a few consequential games were not recorded and the match history on the client did not reflect any changes at all, even if I added the games myself. Nothing showed up. However, the manually added game was shown on Hearthstats which I was able to correct but the changes did not get synced with the app.

**Comment by Epix37** [comment]
Please post logs of that happening. See here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by brokenassapp** [comment]
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/325684/hdt_log.txt)

**Comment by Epix37** [comment]
The log is reset with each HDT session (that one is basically empty). If you still roughly know when it happened the last time you can try to find the respective log in that folder. Otherwise please post the `hdt_log.txt` right after the issue occours.

**Comment by brokenassapp** [comment]
[hdt_log_1466514574.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/325722/hdt_log_1466514574.txt)
[hdt_log_1466513598.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/325721/hdt_log_1466513598.txt)




I am very sorry but I had attempted to "reboot" the tracker to see if the match history would be refreshed which clearly wasn't the case. I appreciate your quick responses deeply/

**Comment by Epix37** [comment]
From the log it looks like everything was saved just fine. Do you maybe have some filter set that causes the games to not be displayed?

You can reset the constructed filters via `stats > constructed > filters > ... > reset` (in the filters header). Also check `options > tracker > stats > display` if they don't show up in the deck list.

**Comment by brokenassapp** [comment]
Nope. The filter was set to display ALL version, mode and timeframe. 
I opened the bigger log file with notepad and found my shaman opponent Akkser, in which he played doomhammer in that match. That to me, seems to suggest that a log was made for that game but nothing appeared on the client. And when I tried to add blank games to the match history to test the client, those null games did not appear on the client but hearthstats got records of those null games.

**Comment by Epix37** [comment]
Did you try resetting the constructed filters (`stats > constructed > filters > ... > reset`)? The `options > tracker > stats > display` setting has no effect on those. 

There's nothing in the log that would suggest the game was not saved :/.

This is from the last game (against Akkser):
```
13:50:49|Info|GameEventHandler.HandleGameEnd >> Game ended...
13:50:50|Info|GameEventHandler.HandleGameEnd >> Assigned current game to deck: control
13:51:02|Info|GameEventHandler.SaveAndUpdateStats >> Saving DeckStats
```

**Comment by brokenassapp** [comment]
The issue is fixed by resetting the filter. Thank you very much. 
Is it a common issue?

**Comment by Epix37** [comment]
You probably set some filter at some point and didn't notice it today (reset just sets it back to default). It's currently not very clear to see when filters are set - so this is somewhat common, yeah. I'll try to add some way of indicating it.

**Comment by Epix37** [comment]
Actually, this might be the same as #2623. It seems for some reason ranks are not always detected.
