### ISSUE TITLE
Ranked Games aren't showing when Filtered

### ISSUE THREAD

**Issue by Pand3m0nia** [HearthSim/Hearthstone-Deck-Tracker#2623]
Hi there,

After the latest update 0.15.4, my Ranked games don't show when I set the Filter to "Ranked" games, when I change the Filter to "All" the games show there and the games even still have "Ranked" underneath the "Mode" column. I have checked that none of the other options are filtering those games out.

**Comment by Epix37** [comment]
Do those games have ranks?

**Comment by Pand3m0nia** [comment]
It would seem they don't, and there are games before the update that don't show either, so it seems that when the "Rank" isn't detected the app doesn't register the game as "Ranked".

**Comment by Epix37** [comment]
Should be fixed with v0.15.5

**Comment by Pand3m0nia** [comment]
Is there any way to make the past games without a Rank still reflect as Ranked games? Since currently those games aren't counting towards my Ranked statistics?

**Comment by Epix37** [comment]
You can clear the value in the max rank filter or manually set a rank by editing the game.

**Comment by Pand3m0nia** [comment]
Since the Rank is "-" what do I change the Rank Filter to? Since currently it's L1 - 25.

**Comment by Epix37** [comment]
Change it to "L1" - "" (i.e. just leave the second field empty).

**Comment by Pand3m0nia** [comment]
Ah ok, thanks. I initially tried changing it to '0' but it didn't seem to like that.
