### ISSUE TITLE
Latest Version extreme unstable

### ISSUE THREAD

**Issue by F43nd1r** [HearthSim/Hearthstone-Deck-Tracker#2624]
The latest version hangs extremely often, windows then closes it because it is not responding.
This happened while

- starting
- Importing from Web
- Exporting to game
- Saving Decks

I'd love to provide more information on this issue, however I am not sure how I should obtain it.

**Comment by Epix37** [comment]
Probably #2584

**Comment by F43nd1r** [comment]
Ok, I just did the config rename. After reading through the thread the only difference between mine and the others issues is that mine started with 15.5, not earlier.

**Comment by F43nd1r** [comment]
The issue was not fixed. However I could confirm that it is indeed a Memory related issue, and therefore probably a duplicate of #2584. I will continue to follow that issue.
