### ISSUE TITLE
Plugin settings wiped (after update today?)

### ISSUE THREAD

**Issue by 305jeff** [HearthSim/Hearthstone-Deck-Tracker#2627]
I'm not sure if this is what caused it, but I noticed today that the plugin I am testing for hearthscry.com lost my settings and login credentials. I don't know exactly when they were lost, but I believe it was today...presumably after the latest update. Just something to check on - no big deal. Thanks as always!

**Comment by Epix37** [comment]
I think this is more likely a problem with the plugin itself. HDT does not touch any plugin config files.
