### ISSUE TITLE
Importing complete decks - when did that happen?

### ISSUE THREAD

**Issue by CobraA1** [HearthSim/Hearthstone-Deck-Tracker#2628]
So I noticed that importing decks from the last game are complete now? When did that happen? What made it possible?

**Comment by Epix37** [comment]
That happened with v0.15. We get the decks from mono process memory via [HearthMirror](https://github.com/HearthSim/HearthMirror).

**Comment by CobraA1** [comment]
I see I can update existing decks with a new version as well, very good! This definitely makes this a great deck tracker :).

**Comment by Epix37** [comment]
It's a huge improvement, yeah! :D Very happy with it.
