### ISSUE TITLE
when import deck string without Class card

### ISSUE THREAD

**Issue by jzlhll** [HearthSim/Hearthstone-Deck-Tracker#2629]
I read the code in Helper.cs ParseCardString(string cards, bool localizedNames = false).I find that these an issue, here.
					if(string.IsNullOrEmpty(deck.Class) && card.PlayerClass != "Neutral")
						deck.Class = card.PlayerClass;
If a cardstring doesn't have one card from Class, the import deck will be failed.
I think two way to solve it:
1. use async action to let user to write class;but some case cannot do this;
2. another function should be set here.

**Comment by Epix37** [comment]
This is only used for importing from clipboard (card names) and NetDeck. I'm pretty sure something *very* close to 100% of decks on the web have at least one class card. Not worth fixing.
