### ISSUE TITLE
Statistics incorrect numbers error in Stats-Arena Runs-Summary-Played, percentages in legend

### ISSUE THREAD

**Issue by markcd** [HearthSim/Hearthstone-Deck-Tracker#2634]
[Bug] Hearthstone Deck Tracker, Stats-Arena Runs-Summary-Played displays incorrect percentages (underneath the pie chart; show legends must be checked). For example my percentages only add up to 20% (they should add up to 100% as it is the percent you have played each class).

**Comment by Epix37** [comment]
Could you post a screenshot of the stats screen with this issue?

**Comment by riQQ** [comment]
This was fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/d20e98fe04f0c0e5cb0aa017321741a955586fb7.
