### ISSUE TITLE
Last arena game of every run is recorded/can't replay it

### ISSUE THREAD

**Issue by KurtzPT** [HearthSim/Hearthstone-Deck-Tracker#2635]
I did two runs of arena today, and basically my 3rd lost in each of these runs I can't replay the match via deck tracker. (Gray button) Every other match I can replay it.

**Comment by judge2020** [comment]
Old issue regarding local playback of matches, which is no longer maintained. You should now use http://hsreplays.net

**Comment by azeier** [comment]
Local replay support has now been fully removed.
