### ISSUE TITLE
I cant export my decks to hs - i think it has something to do with the new way to search for cards

### ISSUE THREAD

**Issue by jonsson0** [HearthSim/Hearthstone-Deck-Tracker#2637]
Well everything is kinda said in the title, if you can questions pls ask

**Comment by Epix37** [comment]
Make sure you are using the latest version and see here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#exporting

**Comment by jonsson0** [comment]
@Epix37 i have dl the update it asked for itself that enough? or do i have to dl it from github everytime there is a new update?

**Comment by Epix37** [comment]
That should be good, yes. You don't need to manually download new updates.

**Comment by jonsson0** [comment]
@Epix37 How can i show you a clip of what happens?

**Comment by jonsson0** [comment]
https://vid.me/p5FW you can see here, first time failed, but 2nd time is what im talking about..

**Comment by jonsson0** [comment]
@Epix37 
^^

**Comment by riQQ** [comment]
Do you use compatibility mode as described in the FAQ @Epix37 linked?
