### ISSUE TITLE
Feature request: Predict my opponent's deck.

### ISSUE THREAD

**Issue by TemporalOnline** [HearthSim/Hearthstone-Deck-Tracker#2640]
I wish I could add and then archive decks, but IF I labeled them with the Tag "Predict" (or similar) it could be used by HDT to predict my opponent's deck similarly like it already does with drawn cards from my deck to predict the deck I'm running.

I use to let, for instance, the tempostorm meta snapshot open and if I go against a warrior, I open the warrior deck that is first, and so on, but this is time consuming, 90% of my time is used switching through tabs while in my mulligan phase, and if HDT could do it for me, my mulligan phase would so that much smoother.

Of course it is not always a 100% match, (so it should be more forgiving when a different card s not present in any of the "predict" tagged decks) but if I can do it right now, just not as efficiently, I don't see why not incorporate it on HDT.

Also, maybe, if I tag it with a modifier like "Predict:1" use it first no matter what the player plays, unless other decks fist best, OR, "Predict:Always" to always use that deck no matter what...

Thanks.

**Comment by Epix37** [comment]
See https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues?q=is%3Aissue+predict+is%3Aclosed
