### ISSUE TITLE
Memory problem

### ISSUE THREAD

**Issue by Weypare** [HearthSim/Hearthstone-Deck-Tracker#2642]
I closed Hearthstone and suddenly my pc started lagging. I opened the Task Manager and saw this:
 
![screenshot 24](https://cloud.githubusercontent.com/assets/17096718/16474457/b380d78a-3e7f-11e6-98e8-6a7200829e20.png)

After a minute or two the problem disappeared. HDT didn't crash.

**Comment by Epix37** [comment]
See #2584

**Comment by Epix37** [comment]
From #2584 (please continue discussion here):
> please try if [the problem disappears] automatically or if there is something specific that fixies it, like closing hearthstone, starting a game, minimizing HDT, ...
