### ISSUE TITLE
Missing filter "Format" (standard/wild) in statistics

### ISSUE THREAD

**Issue by strauss** [HearthSim/Hearthstone-Deck-Tracker#2646]
Some players (me included) would appreciate a distinguished statistic for standard and wild format. It would be great if you could include a filter on the "Format" field in the statistics.

**Comment by Epix37** [comment]
You can set the format filter when the mode is set to  `Ranked` or `Casual`.

**Comment by strauss** [comment]
Sorry, I didn't know that. Very nice!
