### ISSUE TITLE
Resize the deck view

### ISSUE THREAD

**Issue by iSky67** [HearthSim/Hearthstone-Deck-Tracker#2648]
Hey, i can't find how to resize the deck horizontally since the last update, it was perfect before, now it's way too big i don't even want to use it since it takes too much space on my screen :(

**Comment by culinko** [comment]
Options -> General -> Unlock Overlay.

**Comment by Epix37** [comment]
That's for vertical resizing. You can resize it horizontally via `options > overlay > player/opponent > scaling`.

**Comment by iSky67** [comment]
Thanks alot :) !
