### ISSUE TITLE
Mulliganed cards are sometimes displayed out of order on the overlay deck list

### ISSUE THREAD

**Issue by Laperst** [HearthSim/Hearthstone-Deck-Tracker#2649]
Hello,
You can replace your cards when game starts. Sometimes there is a bug that return higher cost card before less cost card. When i get Dr. Boom and replace him then he is higher then any 6 cost cards (dr boom has 7 mana cost). It is not happening everytime, but very often. That Dr. Boom was example, but only 7+ cards bugs.

**Comment by Epix37** [comment]
I'm not sure I quite understand what the problem is. Could you, step by step, explain what you do and when/where the problem occurs?

**Comment by Laperst** [comment]
Well when game starts and i dont want high cost cards i repleace them and they are back in deck so they are again on right side list maybe its happening only for users which have enabled option disspear card while count is 0 that iam using i hope this is better to understand sorry iam trying the best ;)

**Comment by judge2020** [comment]
Cards disappear when mulligan'd back into deck with "remove cards fro deck when drawn" on. Old issue, likely not a problem anymore.

**Comment by riQQ** [comment]
Screenshots of the issue in #3397.
