### ISSUE TITLE
HDT Crashing after 5 minutes without using it.

### ISSUE THREAD

**Issue by pefp2008** [HearthSim/Hearthstone-Deck-Tracker#2652]
Hi. I'm having problems with HDT right now. 
During a match and/or after ending a match, HDT crashes and closes. It also causes HS to disconnect (somehow).

Attached HDT log file, .net runtime and app error files for your reviewing.

[hdt_log_1467691489.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/347047/hdt_log_1467691489.txt)

[.net runtime.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/347050/default.net.runtime.txt)

[App error.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/347051/App.error.txt)

**Comment by Epix37** [comment]
Should be #2584

**Comment by riQQ** [comment]
Duplicate of #2584.
