### ISSUE TITLE
Thing From Below tracker?

### ISSUE THREAD

**Issue by rrwoods** [HearthSim/Hearthstone-Deck-Tracker#2654]
I love the C'Thun and Yogg counters.  Any chance we might see a Thing From Below cost tracker?  You probably wouldn't even need a separate UI element -- just change the cost right in the decklist! (and maybe turn it green)

**Comment by andburn** [comment]
There is no need to create multiple issues (#2625)

**Comment by rrwoods** [comment]
Oh man I'm really sorry about that >.< ... I thought that maybe I'd created this issue already and searched my email, and thought that when I didn't find anything that I didn't create it.  I'll be sure to search the github itself next time.  *facepalm*
