### ISSUE TITLE
Hearthstats syncing causing deck version conflicts and excessive revision number incrementing

### ISSUE THREAD

**Issue by raikesy** [HearthSim/Hearthstone-Deck-Tracker#2655]
Opened HDT earlier to find one of my decks at v70 when yesterday it was still v1. It seems like there are conflicting versions of the deck stored locally and on hearthstats and it's alternating between them very frequently and increasing the revision number each time. Has happened to several of my decks.
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/352684/hdt_log.txt)

![image](https://cloud.githubusercontent.com/assets/9397714/16662234/62c71008-446e-11e6-924c-e20648e03679.png)

**Comment by Epix37** [comment]
This issue will be fixed with the next update. See https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2641
