### ISSUE TITLE
Blank Arena Runs

### ISSUE THREAD

**Issue by drrelyea** [HearthSim/Hearthstone-Deck-Tracker#2661]
This issue is a duplicate of #2303, which is closed and which I do not know how to re-open. I have exactly the same problem - I have twenty arena runs with full decks but no statistics attached to them at all. I've only deleted a handful of runs (when there was a duplicate deck or something glitched hard), so deletion isn't the culprit. I also am using Arena Helper.

Please let us delete actual runs from the statistics - these twenty make my average seem ridiculous, because 1/5 of all of my arena runs appear to have 0 wins. Hearthstats is entirely accurate and does not include these runs - just HDT seems to have them.

![stats1](https://cloud.githubusercontent.com/assets/5328759/16707131/b4bb1d12-4579-11e6-8d8f-8b153ec90007.PNG)
![stats2](https://cloud.githubusercontent.com/assets/5328759/16707132/b4bd9786-4579-11e6-8102-948c27673dd2.PNG)

**Comment by Epix37** [comment]
- Do you have HDT auto arena importing (`options (advanced) > tracker > importing`) and Arena Helper auto importing enabled? 
- Are the duplicates still created without arena helper (entirely or it's auto importing) enabled?

**Comment by Epix37** [comment]
> Please let us delete actual runs from the statistics - these twenty make my average seem ridiculous, because 1/5 of all of my arena runs appear to have 0 wins.

You can do that by deleting the corresponding deck.

**Comment by Epix37** [comment]
Closed for lack of response.
