### ISSUE TITLE
Not working with latest Hearthstone version

### ISSUE THREAD

**Issue by Vaerton** [HearthSim/Hearthstone-Deck-Tracker#2665]
It says it auto imports for the 'Play' menu, but even if I press Import then from Constructed, no decks show up. There is a 'No deck mode' button, but it won't allow me turn it off, so I'm assuming that might be the problem. Thanks.

**Comment by Epix37** [comment]
The latest Hearthstone update broke a lot of things. Working on it.

**Comment by ChuckJrster** [comment]
Thank you very much sir! I've come to enjoy this app very very much!

**Comment by Vaerton** [comment]
Ok, thank you.

**Comment by radryan** [comment]
@Vaerton I was lost also without it. I solved the problem somewhat by going in options and click on "deck windows" (the 2nd option on left panal). Then just check all the boxes and you'll be able to see your deck and theirs and the timer. Just move where you want them and you have a semi workable fix until the real fix.

**Comment by radryan** [comment]
I also changed the log file directory to "C:\Users\"Your User Name Here"\AppData\Local\Blizzard\Hearthstone\Logs"

**Comment by please55** [comment]
In case this was missed in your review, also issues with the overlay showing attack counter for example or indicators showing turns when card was drawn/mulligan/kept.

**Comment by zigg80** [comment]
Does this fix the issue? I tried changing the log directory and it wouldnt let me

**Comment by Epix37** [comment]
Most major issues should be fixed with v0.15.7 now: 
https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/tag/v0.15.7

**Comment by Epix37** [comment]
Actually fixed with v0.15.8 now
https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/tag/v0.15.8

**Comment by AspectOfDreams** [comment]
Just adding onto this one. I have downloaded both of the newest versions and my games are being recorded but my decks are not being added and it will only show whatever it is that I draw.

**Comment by ChuckJrster** [comment]
Thank you for fixing the issues Epix, I appreciate it, very very much so! Quick question, what's the best way to start the apps, meaning, do or should I start Hearthstone first, then the HDT or HDT then Hearthstone. And, for backing out too? Thx much! Great program! :D
