### ISSUE TITLE
turn always = 0

### ISSUE THREAD

**Issue by yosh0** [HearthSim/Hearthstone-Deck-Tracker#2666]
3:54:48|Info|Player.Draw >> [Opponent] id=45, cardId=, cardName=, zonePos=0,Info={turn=0, originalZone=DECK}
3:54:48|Info|TagChangeActions.StepChange >> Game was already in progress.
3:54:59|Info|Player.PlayToGraveyard >> [Player] id=64, cardId=HERO_08, cardName=Jaina Proudmoore, zonePos=0,Info={turn=0, originalZone=DECK}
3:55:01|Info|TagChangeActions.StepChange >> Game was already in progress.
3:55:01|Info|TagChangeActions.StepChange >> Game was already in progress.
3:55:01|Warning|GameEventHandler.HandleGameEnd >> HandleGameEnd was already called.
3:55:20|Info|GameV2.CurrentMode >> TOURNAMENT
3:55:20|Error|DeckImporter.FromConstructed >> System.ArgumentNullException: Значение не может быть неопределенным.
Имя параметра: source
   в System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   в Hearthstone_Deck_Tracker.Importing.DeckImporter.GetConstructedDecks()
   в Hearthstone_Deck_Tracker.Importing.DeckImporter.FromConstructed()
3:56:05|Info|Help.Hyperlink_RequestNavigate >> [Helper.TryOpenUrl] https://github.com/HearthSim/Hearthstone-Deck-Tracker/

**Comment by Epix37** [comment]
See #2665
