### ISSUE TITLE
HDT not tracking decks since 0.15.8

### ISSUE THREAD

**Issue by AspectOfDreams** [HearthSim/Hearthstone-Deck-Tracker#2668]
So I have checked which version I have and I do indeed have the newest version designed to fix all the errors caused by the patch from earlier.

I'm new to the system so I might be missing something but prior to the patch, HDT was working perfectly. After the patch, it will record cards I draw and enter each win/loss by class and opponent but it will not actually recognize decks nor will it import from constructed.

I was using the new hero so I tried it on other heroes and classes but the result was the same. I have toggled the "Auto" function to its default light blue and white states without any success either way. If I'm missing something simple let me know but I think it's frustrating because I really do enjoy the app.

**Comment by NomdeNet** [comment]
I'm on 15.8 too, and am seeing a similar issue but worse. 
HDT is not detecting decks automatically, it's not updating cards in the tracker during a game, and its either not recording the game when it's over, or recording a game with no result (Turns 0, Result: None).

If it gives a report of missing cards at the start of game, and I switch to the correct deck, that warning doesnt vanish.
Also from the start of a game, the message, "next draw fatigues for 1" appears at the bottom of the decklist and stays there.

Finally if I have "Hide in menu" checked, the decklist appears for a second at the start of a game then vanishes. I have to uncheck that for it to show anything - and then it doesnt work as described above.

**Comment by Epix37** [comment]
1. Restart Hearthstone and HDT
2. Reproduce the issue and post the log here - [see here](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)

**Comment by tknights2015** [comment]
I am seeing the same issues
![7_13](https://cloud.githubusercontent.com/assets/16232528/16810480/3cf6afd8-48e1-11e6-8891-4bae43b052c1.JPG)
[log_1372016-1013.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/361894/log_1372016-1013.txt)

**Comment by NomdeNet** [comment]
Log attached below. I played one game against the Innkeeper, was set toi record practice games, and in stats it shows as Result: None, Turns 0.
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/361921/hdt_log.txt)

**Comment by AspectOfDreams** [comment]
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/362040/hdt_log.txt)

Here you go. I hope it makes sense to you because it just looks like nonsense to me.

**Comment by tknights2015** [comment]
All of my reported issues in this thread are working correctly now.

**Comment by AspectOfDreams** [comment]
Mine are still not so I will keep this open.

**Comment by xaretnapx** [comment]
I am also having these same issues.

**Comment by Epix37** [comment]
Oh, this very likely related to the new hero. Were all of you guys having the issues when playing (against) it?

**Comment by LufgtHuron** [comment]
Experiencing this when going into tavern brawl with no-deck mode. I join a game, to going into showing that I have no deck and I have one draw left to fatigue. Then it picks some seemingly random cards and adds the new cards I draw to it. Going back into no-deck mode again doesn't fix anything, it just gives a popup for a finished game without any classes selected and goes back to not tracking ANYTHING (even board damage).
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/363202/hdt_log.txt)

**Comment by Epix37** [comment]
@NomdeNet Looks like auto deck selection might be causing it in your case. I'll have a look.

**Comment by Epix37** [comment]
Could you guys try if you still have any issues with this build: https://github.com/Epix37/HDT-Test/releases/tag/v0.15.9pre1 (just extract it anywhere and run it)

**Comment by xaretnapx** [comment]
I hardly play with shaman, but I did obtain the new hero... But the issues started for me after the last HDT update. It no longer tracks games or recognizes decks. Thanks for your response! 

    On Thursday, July 14, 2016 7:12 AM, Alexander Zeier <notifications@github.com> wrote:
 

 Could you guys try if you still have any issues with this build: https://github.com/Epix37/HDT-Test/releases/tag/v0.15.9pre1 (just extract it anywhere and run it)—

**Comment by NomdeNet** [comment]
That pre build looks like it's fixed the issue for me.

With it installed, i get a prompt saying a new version is ready to download-  should I let it update, or keep the pre version?

**Comment by Epix37** [comment]
Update to the latest release. It should contain 1 or 2 changes the pre release didn't.

**Comment by xaretnapx** [comment]
After the new update this morning everything seems to be working fine for me again, thank you so much! 

    On Thursday, July 14, 2016 9:07 AM, Alexander Zeier <notifications@github.com> wrote:
 

 Update to the latest release. It should contain 1 or 2 changes the pre release didn't. —

**Comment by NomdeNet** [comment]
Another thank you from me. Great work!

**Comment by MaestroDaVinci** [comment]
Anyone having still the problem? I just started the tracker again and updated it, it constantly loads a random deck and it doesn't track drawn cards.

**Comment by tknights2015** [comment]
Played a game with new Shaman Hero. Did not see any issues and the game recorded correctly.
Updated to latest version by auto download
