### ISSUE TITLE
Order of cards in player's decks have changed in Hearthstone UI

### ISSUE THREAD

**Issue by Mistrelvous** [HearthSim/Hearthstone-Deck-Tracker#2669]
Previously, hearthstone used to sort cards placed in decks in the collection manager by "weapon->spell->minion." E.g. 2 mana cards used to be sorted like so: "Stormforged Axe, then Lava Shock, then Flametongue Totem." But now with the latest Hearthstone patch (5.2.0), all cards of the same mana cost are sorted alphabetically in decks found in the Hearthstone collection manager, regardless of type: "Flametongue Totem, then Lava Shock, then Stormforged Axe." 

It would be awesome if HDT could change the way it sorts the cards in its decklists too, to make it easier for users to quickly see if the decklist in their HDT exactly matches the decklist in their Hearthstone collection. I often check to see if both decklists are the same before queuing into a game.

**Comment by asakurato** [comment]
Just encountered same problem, as I was importing reno deck and it was reordered, it was quite difficult to add missing cards

**Comment by tknights2015** [comment]
I agree, it is very hard to check deck lists with the HDT list in a different order.
