### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by Hezzekiel** [HearthSim/Hearthstone-Deck-Tracker#2671]
The auto import isnt working for me. When I enter Play Mode and try to import the decks it says "no new decks found" even though I have 18 decks. 

> 15:39:41|Info|GameV2.Reset >> -------- Reset ---------
15:39:41|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
15:39:42|Info|OverlayWindow.Update >> Refreshed overlay topmost status
15:39:42|Info|MainWindow.SelectDeck >> Switched to deck: hunter NA (v1.0)
15:39:42|Warning|LogReaderManager.Stop >> LogReaders could not be stopped, stop already in progress.
15:39:42|Info|GameV2.Reset >> -------- Reset ---------
15:39:42|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
15:39:43|Info|BackupManager.Run >> Running BackupManager
15:39:43|Info|BackupManager.Run >> Backup for today already exists
15:39:43|Info|PluginManager.LoadPlugins >> Loading Plugins...
15:39:43|Info|GitHub.CheckForUpdate >> HearthSim/Hearthstone-Deck-Tracker: Checking for updates (current=0.15.8.0, pre-release=False)
15:39:43|Info|BackupManager.Run >> Running BackupManager
15:39:43|Info|BackupManager.Run >> Backup for today already exists
15:39:43|Info|OverlayWindow.Update >> Refreshed overlay topmost status
15:39:43|Info|GitHub.CheckForUpdate >> HearthSim/Hearthstone-Deck-Tracker: We are up-to-date (latest=v0.15.8, pre-release=False)
15:39:43|Info|LogReader.ReadLogFile >> Found LoadingScreen.log.
15:39:44|Info|GameV2.CurrentMode >> LOGIN
15:39:46|Info|LogReader.ReadLogFile >> Found Rachelle.log.
15:39:52|Info|OverlayWindow.Update >> Refreshed overlay topmost status
15:39:54|Info|GameV2.CurrentMode >> HUB
15:39:54|Info|LoadingScreenHandler.CheckMirrorStatus >> Mirror status: Ok
15:39:57|Info|GameV2.CurrentMode >> TOURNAMENT
15:39:57|Error|DeckImporter.FromConstructed >> System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
   bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   bei Hearthstone_Deck_Tracker.Importing.Game.ImportedDeck..ctor(Deck deck, List`1 candidates)
   bei Hearthstone_Deck_Tracker.Importing.DeckImporter.GetImportedDecks(IEnumerable`1 decks)
   bei Hearthstone_Deck_Tracker.Importing.DeckImporter.FromConstructed()
15:40:01|Error|DeckImporter.FromConstructed >> System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
   bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   bei Hearthstone_Deck_Tracker.Importing.Game.ImportedDeck..ctor(Deck deck, List`1 candidates)
   bei Hearthstone_Deck_Tracker.Importing.DeckImporter.GetImportedDecks(IEnumerable`1 decks)
   bei Hearthstone_Deck_Tracker.Importing.DeckImporter.FromConstructed()
15:40:12|Info|OverlayWindow.Update >> Refreshed overlay topmost status
15:40:15|Info|GameV2.CurrentMode >> HUB
15:41:05|Info|MainWindow.ShowImportDialog >> Waiting for TOURNAMENT screen...
15:41:08|Info|OverlayWindow.Update >> Refreshed overlay topmost status
15:41:09|Info|GameV2.CurrentMode >> TOURNAMENT
15:41:09|Error|DeckImporter.FromConstructed >> System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
   bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   bei Hearthstone_Deck_Tracker.Importing.Game.ImportedDeck..ctor(Deck deck, List`1 candidates)
   bei Hearthstone_Deck_Tracker.Importing.DeckImporter.GetImportedDecks(IEnumerable`1 decks)
   bei Hearthstone_Deck_Tracker.Importing.DeckImporter.FromConstructed()
15:41:10|Error|DeckImporter.FromConstructed >> System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
   bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   bei Hearthstone_Deck_Tracker.Importing.Game.ImportedDeck..ctor(Deck deck, List`1 candidates)
   bei Hearthstone_Deck_Tracker.Importing.DeckImporter.GetImportedDecks(IEnumerable`1 decks)
   bei Hearthstone_Deck_Tracker.Importing.DeckImporter.FromConstructed()
15:41:20|Error|DeckImporter.FromConstructed >> System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
   bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   bei Hearthstone_Deck_Tracker.Importing.Game.ImportedDeck..ctor(Deck deck, List`1 candidates)
   bei Hearthstone_Deck_Tracker.Importing.DeckImporter.GetImportedDecks(IEnumerable`1 decks)
   bei Hearthstone_Deck_Tracker.Importing.DeckImporter.FromConstructed()
15:41:46|Error|DeckImporter.FromConstructed >> System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
   bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   bei Hearthstone_Deck_Tracker.Importing.Game.ImportedDeck..ctor(Deck deck, List`1 candidates)
   bei Hearthstone_Deck_Tracker.Importing.DeckImporter.GetImportedDecks(IEnumerable`1 decks)
   bei Hearthstone_Deck_Tracker.Importing.DeckImporter.FromConstructed()
15:41:56|Error|DeckImporter.FromConstructed >> System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
   bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   bei Hearthstone_Deck_Tracker.Importing.Game.ImportedDeck..ctor(Deck deck, List`1 candidates)
   bei Hearthstone_Deck_Tracker.Importing.DeckImporter.GetImportedDecks(IEnumerable`1 decks)
   bei Hearthstone_Deck_Tracker.Importing.DeckImporter.FromConstructed()

**Comment by Strike07** [comment]
I've been having the same problem since yesterday, app can't detect any of my decks.

**Comment by Bo-Jo** [comment]
The same here..... Import will not work at all, nor will HDT recognize any of my decks.... This statred right after the patch...

**Comment by Epix37** [comment]
This looks like an issue with the new hero. Likely the same as https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2668.

**Comment by Hezzekiel** [comment]
Thanks, changing to the normal shaman hero helped and I now can import the decks.

**Comment by Epix37** [comment]
Thanks for the confirmation. I'll release an update later today to fix that issue.

**Comment by kencgo** [comment]
Hi there, i can confirm that removing the new shaman champion resolves the importing issue.

Thanks !

**Comment by Epix37** [comment]
Could you guys try if you still have any issues with this build: https://github.com/Epix37/HDT-Test/releases/tag/v0.15.9pre1 (just extract it anywhere and run it)
