### ISSUE TITLE
Compile v0.15.8 get an error and a warning

### ISSUE THREAD

**Issue by jzlhll** [HearthSim/Hearthstone-Deck-Tracker#2672]
1. Since v0.15.8 changed the lib/HearthMirror.dll ,get a warning:
    PROCESSOR ARCHITECTURE x86 dismatch “MSIL“ reference "hearthMirror,version=1.0.0.0, Culture=netral,processsorArchitecture=MSIL".
   Does it serious?

2. Below is error log, although it is never mind about main app.

4>D:\gitRoot\HDT\Hearthstone-Deck-Tracker-0.15.8\Hearthstone-Deck-Tracker-0.15.8\HDTTests\BoardDamage\EntityHelperTest.cs(22,4,22,25): error CS0200: Property or indexer 'Entity.IsPlayer' cannot be assigned to -- it is read only
4>D:\gitRoot\HDT\Hearthstone-Deck-Tracker-0.15.8\Hearthstone-Deck-Tracker-0.15.8\HDTTests\BoardDamage\EntityHelperTest.cs(30,4,30,19): error CS0200: Property or indexer 'Entity.IsPlayer' cannot be assigned to -- it is read only
4>D:\gitRoot\HDT\Hearthstone-Deck-Tracker-0.15.8\Hearthstone-Deck-Tracker-0.15.8\HDTTests\BoardDamage\EntityHelperTest.cs(42,4,42,19): error CS0200: Property or indexer 'Entity.IsPlayer' cannot be assigned to -- it is read only
4>D:\gitRoot\HDT\Hearthstone-Deck-Tracker-0.15.8\Hearthstone-Deck-Tracker-0.15.8\HDTTests\Hearthstone\SecretTests.cs(51,13,51,33): error CS0200: Property or indexer 'Entity.IsPlayer' cannot be assigned to -- it is read only
4>D:\gitRoot\HDT\Hearthstone-Deck-Tracker-0.15.8\Hearthstone-Deck-Tracker-0.15.8\HDTTests\Hearthstone\SecretTests.cs(55,13,55,35): error CS0200: Property or indexer 'Entity.IsPlayer' cannot be assigned to -- it is read only
4>D:\gitRoot\HDT\Hearthstone-Deck-Tracker-0.15.8\Hearthstone-Deck-Tracker-0.15.8\HDTTests\BoardDamage\EntityHelperTest.cs(76,4,76,19): error CS0200: Property or indexer 'Entity.IsPlayer' cannot be assigned to -- it is read only
4>D:\gitRoot\HDT\Hearthstone-Deck-Tracker-0.15.8\Hearthstone-Deck-Tracker-0.15.8\HDTTests\BoardDamage\BoardStateTest.cs(22,4,22,25): error CS0200: Property or indexer 'Entity.IsPlayer' cannot be assigned to -- it is read only

**Comment by Epix37** [comment]
Turn off building the test solution for now or only build the main project. I had no time yet to fix those.

**Comment by jzlhll** [comment]
Thanks for reply.And what about the warning about MSIL HearthMirror x86 dismatch.v0.15.9 still has.

**Comment by Epix37** [comment]
Not sure, I'm not having that problem.

Try a fresh clone maybe.

**Comment by riQQ** [comment]
Same for me on a fresh clone. Creating the Build Configuration `x86` for the solution solves this problem. @Epix37, can you either build HearthMirror as MSIL / AnyCPU or change the solution to x86 BuildConfiguration?
