### ISSUE TITLE
Downloading update, even manually, is not working

### ISSUE THREAD

**Issue by nicholberry** [HearthSim/Hearthstone-Deck-Tracker#2673]
Your "New Update Available" is not loading, even manually (I've now tried both ways twice) and none of my decks are being recognized as I play hearthstone.  I've even tried using the "not now" button, but still my decks will not load.

**Comment by Epix37** [comment]
Same as https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2668?

**Comment by nicholberry** [comment]
No - I'm getting an error message when downloading the update "There was an error installing the latest update. Press any key to open the website for manual download.". After trying to manually download I still end up with HDT not recognizing that I'm in game... in any mode. It's not recognizing any decks and is repeatedly telling me there is a new download, do I want to download now. I've tried ignoring - closing both HDT and Hearthstone. Still getting nothing. On the manual download, when I try to open the application after the download I get a Windows alert saying that it's interfered with my action because what I'm trying to do could compromise my PC (sorry... didn't write down the exact language). Everything was working fine for me prior to your two most recent updates.

**Comment by nicholberry** [comment]
I would attach a log here, but I'm embarrassed to say (old woman here) I can't recall how to do that.

**Comment by riQQ** [comment]
Drag and drop the log file in the textbox when writing a comment.

**Comment by Epix37** [comment]
Probably duplicate #2562 then?

0.15.7/8 were not working correctly in some cases, that might be what you were experiencing after manually downloding those. Try downloading the latest release again: https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/latest

**Comment by nicholberry** [comment]
Where do I find the log file? 


----- Original Message -----

**Comment by nicholberry** [comment]
After using your link to download one more time (which I also did last night before emailing you), I continue to get the message "New Update Available" and in opening Hearthstone I note there is no tracking or recognition of decks. 

Can you tell me where I can find the log file so I can attach it for you. 

Thanks 

----- Original Message -----

**Comment by Epix37** [comment]
I think you might be starting the wrong version then. Running the latest (v0.15.10) should not show you the "update available" message.

As for the logs, you can find those here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by nicholberry** [comment]
How does one start the wrong version when all I am doing is opening from desktop shortcut to the application? 

Here is the most recent log (from this morning). I hope you find it helpful. Thanks for the guidance on how best to find this. Hopefully I'll remember this next time. 

Thanks for helping me work this through. I thought of uninstalling and reinstalling, but I hate to lose all my saved data/decks. 

Diana 


----- Original Message -----

**Comment by riQQ** [comment]
> 11:34:58 AM|Info|GitHub.CheckForUpdate >> HearthSim/Hearthstone-Deck-Tracker: Checking for updates (current=0.15.6.0, pre-release=False)

You are using an outdated version: 0.15.6.0
You should be good, if you download the latest release manually here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/tag/v0.15.10. Delete the HearthstoneDeckTracker program folder and extract the download one. Your settings and replays are stored in `%APPDATA%\HearthstoneDeckTracker` if you didn't change the settings folder path in the settings.

**Comment by jleclanche** [comment]
@nicholberry Try updating to 1.0: https://hsdecktracker.net/download/

The installer was reworked, this won't happen anymore. Uninstalling/reinstalling should not lose your data; if you want to make sure, look in the folder @riQQ mentioned and back them up.

Closing for now. Reopen if it's still not working after upgrading to 1.0.
