### ISSUE TITLE
Most hunter game history lost

### ISSUE THREAD

**Issue by ScottAllen11** [HearthSim/Hearthstone-Deck-Tracker#2675]
Played 100 ranked games on hunter (NA server) this season, about 75 before the patch. I can understand the last 25 not being recorded due to the HS patch and decks not being recognized. But suddenly (within last 2 days and their updates) now all the hunter games from this season (and most of last season, except 5 games strangely) are missing from my constructed stats. My other classes (paladin and warlock) retained their history. Hunter is my current active deck.

Noticed the missing stats this morning. Restoring the last 3 backups did not fix the stats. On each of these backups, the main screen shows a much too small W-L (different on each backup with no obvious pattern) yet even those games are not showing in the stats. That is, when I view the stats for this season, hunter shows 0 games played and all 0-0's for that row in the class match ups. All time shows 3-2 (should be about 150 games recorded for hunter).

Attaching this morning's backup as well as 3 days ago when I could still see the hunter stats.

[Backup_14072016.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/364008/Backup_14072016.zip)
[Backup_11072016.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/364009/Backup_11072016.zip)

Thanks for checking on this problem. I know you did not expect to be so busy this week!

Scott

**Comment by ScottAllen11** [comment]
Addendum. New games are showing up in the stats. Still no sign of the previous 150 games.

**Comment by Epix37** [comment]
Good news: all the data is still there, it's just not getting displayed for some reason.

I will look into what's causing this tomorrow.

**Comment by Epix37** [comment]
I think I fixed the issue. Try this build: https://github.com/Epix37/HDT-Test/releases/tag/v0.15.10pre1

There is a chance, games played since 15.8/9  may not show up however :/. Definitely the lesser of the two evils though.

**Comment by Epix37** [comment]
This should be fixed with v0.15.10.
