### ISSUE TITLE
HSDT crash on startup

### ISSUE THREAD

**Issue by Mr4nderson** [HearthSim/Hearthstone-Deck-Tracker#2676]
Hello,

I just started using HSDT and I'm really liking it.
Sadly as of today it keeps crashing at startup (see screenshot).
![hsdt crash on startup](https://cloud.githubusercontent.com/assets/20463017/16848612/da158846-49f6-11e6-8600-389277b69c2f.png)

I've already tried the following:
- updating to a new version
- updating .NET framework to 4.6
- deleting all config files and starting fresh
- rebooting 
- restarting Battle.net and HS

Here are some logs.
**HSDT logs**
**after the first crash** (was working fine about 13 hours earlier)
`16:29:07|Info|GameV2.Reset >> -------- Reset ---------`
`16:29:07|Info|OpponentSecrets.ClearSecrets >> Cleared secrets`
`16:29:07|Info|OverlayWindow.Update >> Refreshed overlay topmost status`
`16:29:08|Info|MainWindow.SelectDeck >> Switched to deck: F2P OTK Warrior upgrade (v1.0)`
`16:29:08|Warning|LogReaderManager.Stop >> LogReaders could not be stopped, stop already in progress.`
`16:29:08|Info|GameV2.Reset >> -------- Reset ---------`
`16:29:08|Info|OpponentSecrets.ClearSecrets >> Cleared secrets`

**lastest one** (there are quite a few more but the only difference between them are the timestamps)
`19:00:35|Info|ConfigManager.ConvertLegacyConfig >> changed config values`
`19:00:36|Info|GameV2.Reset >> -------- Reset ---------`
`19:00:36|Info|OpponentSecrets.ClearSecrets >> Cleared secrets`

All logs end with the same line: `xx:xx:xx|Info|OpponentSecrets.ClearSecrets >> Cleared secrets`
There are no Crash Reports in the `<HDT dir>`.

**Windows logs**
(Windows 10 Pro 64-bit latest version)

`.NET runtime`
`Application: Hearthstone Deck Tracker.exe`
`Framework Version: v4.0.30319`
`Description: The process was terminated due to an unhandled exception.`
`Exception Info: exception code c0000005, exception address 62CBC570`

`Application error`
`Faulting application name: Hearthstone Deck Tracker.exe, version: 0.15.9.0, time stamp: 0x57879065`
`Faulting module name: d3d9.dll, version: 10.0.10586.494, time stamp: 0x5775e023`
`Exception code: 0xc0000005`
`Fault offset: 0x0005c570`
`Faulting process ID: 0x4c`
`Faulting application start time: 0x01d1ddeef69a6c30`
`Faulting application path: E:\Eigene Dateien\Downloads\Hearthstone Deck Tracker\Hearthstone Deck Tracker.exe`
`Faulting module path: C:\WINDOWS\SYSTEM32\d3d9.dll`
`Report ID: e81250f0-c0ff-4573-b494-770838df129a`
`Faulting package full name: `
`Faulting package-relative application ID: `

I'm out of ideas and would appreciate any help I can get.

**Comment by Epix37** [comment]
> Faulting module name: d3d9.dll, version: 10.0.10586.494, time stamp: 0x5775e023

This sound slike it might be your graphics card drivers. Try updating/reinstalling those.

**Comment by Mr4nderson** [comment]
Updating the graphics card driver didn't change anything. All error logs look exactly the same.
Is there anything else I can do?

**Comment by riQQ** [comment]
Try these: 

    

 > - First, check to see if the Game is compatible with your version of Windows:
    [Windows 7 Compatibility Center](http://www.microsoft.com/windows/compatibility/windows-7/en-us/default.aspx)
   [Windows Vista Compatibility Center](http://www.microsoft.com/windows/compatibility/windows-vista)

> -    Try running the game in Compatibility mode. If the game is not compatible with your version of Windows, try running the game in Compatibility mode by logging on to the computer as an administrator. Then browse to the games executable file, right-click on the file and click Properties, click the Compatibility tab, place a check in the Run this program in compatibility mode for: and select the version of Windows previous to the your current version. Click OK and then test the game.

  >-  Check for updates to your game software. Some games install other software such as punkbuster that is used to detect cheating. If this software is disabled, or if your PCs settings cause a violation, you may see the APPCRASH error and be kicked out of the game. You can check for known issues and updates for the game by visiting the game publisher’s website. 


  >-  Update Microsoft DirectX. To diagnose DirectX problems and to make sure you have the latest version, see [Diagnosing basic problems with DirectX](http://windows.microsoft.com/en-US/windows7/Diagnosing-basic-problems-with-DirectX)

 >-   Update your drivers. Click the link specific to your version of Windows and follow the steps in the that article to update your Video and Sound card drivers: 
[Update a driver for hardware not installed properly in Vista](http://windows.microsoft.com/en-US/windows-vista/Update-a-driver-for-hardware-that-isnt-working-properly)
[Update a driver for hardware not installed properly in Windows 7](http://windows.microsoft.com/en-US/windows7/Update-a-driver-for-hardware-that-isnt-working-properly)

http://answers.microsoft.com/en-us/windows/forum/windows_7-gaming/appcrash-error-when-playing-some-games/dfc6f06c-a75f-4306-ac85-35dbbf8485a9?tm=1323661425093

**Comment by Mr4nderson** [comment]
I tried all of the above although I use Windows 10 and HSDT was still working yesterday but no luck. 
I might do a system restore. Maybe this will fix the underlying issue.

**Comment by Godf** [comment]
Signed up just to say I'm having completely the same issue. I've submitted few bug reports as suggested at crash window, maybe they will help. HSDT just stopped working after the last update, it crashes for me on startup and nothing helps. I updated everything I could, also reinstalled the HSDT, and still nothing. 
It started when the program updated to the latest version.

**Comment by Godf** [comment]
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
(translation - Object reference does not point to an object instance.)
   в Hearthstone_Deck_Tracker.Stats.DeckStatsList.<>c.<get_DeckStats>b__4_0(DeckStats x)
   в System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   в System.Linq.GroupedEnumerable`3.GetEnumerator()
   в System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   в System.Collections.Concurrent.ConcurrentDictionary`2.InitializeFromCollection(IEnumerable`1 collection)
   в System.Collections.Concurrent.ConcurrentDictionary`2..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   в Hearthstone_Deck_Tracker.Stats.DeckStatsList.get_DeckStats()
   в Hearthstone_Deck_Tracker.Hearthstone.Deck.get_DeckStats()
   в Hearthstone_Deck_Tracker.Hearthstone.Deck.GetRelevantGames()
   в Hearthstone_Deck_Tracker.Hearthstone.Deck.get_WinLossString()
   в Hearthstone_Deck_Tracker.Windows.OverlayWindow.SetWinRates()
   в Hearthstone_Deck_Tracker.Windows.OverlayWindow.Update(Boolean refresh)
   в Hearthstone_Deck_Tracker.Windows.OverlayWindow..ctor(GameV2 game)
   в Hearthstone_Deck_Tracker.Core.get_Overlay()
   в Hearthstone_Deck_Tracker.FlyoutControls.Options.Overlay.OverlayOpponent.Load(GameV2 game)
   в Hearthstone_Deck_Tracker.FlyoutControls.OptionsMain.Load(GameV2 game)
   в Hearthstone_Deck_Tracker.Windows.MainWindow.LoadConfigSettings()
   в Hearthstone_Deck_Tracker.Core.Initialize()
   в Hearthstone_Deck_Tracker.App.App_OnStartup(Object sender, StartupEventArgs e)
   в System.Windows.Application.OnStartup(StartupEventArgs e)
   в System.Windows.Application.<.ctor>b__1_0(Object unused)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Godf** [comment]
I launched "HDTUninstaller" and deleted everything. It helped me, now its working

**Comment by Mr4nderson** [comment]
Sadly the HDTUninstaller crashes as well.

`.NET Runtime`
`Application: HDTUninstaller.exe`
`Framework Version: v4.0.30319`
`Description: The process was terminated due to an unhandled exception.`
`Exception Info: exception code c0000005, exception address 607F4A53`

`Application Error`
`Faulting application name: HDTUninstaller.exe, version: 1.0.0.0, time stamp: 0x5785b10a`
`Faulting module name: d3d9.dll, version: 10.0.10586.494, time stamp: 0x5775e023`
`Exception code: 0xc0000005`
`Fault offset: 0x00054a53`
`Faulting process ID: 0x8dc`
`Faulting application start time: 0x01d1de278d70a4a4`
`Faulting application path: C:\Users\Jonathan\Desktop\Hearthstone Deck Tracker\HDTUninstaller.exe`
`Faulting module path: C:\WINDOWS\SYSTEM32\d3d9.dll`
`Report ID: 92a189bb-d184-4887-92af-8aedb382d848`
`Faulting package full name: `
`Faulting package-relative application ID: `

This is just so weird.

**Comment by riQQ** [comment]
What changed between HDT working and not working? Does HDT 0.15.8 work for you?

**Comment by Epix37** [comment]
Try copying ` C:\WINDOWS\SYSTEM32\d3d9.dll` into the HDT folder.

**Comment by Mr4nderson** [comment]
Copying d3d9.dll into the HDT folder didn't work. 
All the version from 0.15.6 upwards didn't work. (I didn't try the ones below that)

But removing the following Windows updates did work:
KB3174060
KB890830
**KB3172985**

As far as I can tell only the last one is actually changing the d3d9.dll file but I removed all of them just to be sure.
Thanks a lot for all your help.

**Comment by riQQ** [comment]
As reported by multiple user, running `MSI Afterburner` and HDT may cause this crash.
