### ISSUE TITLE
secrets from three classes crashed the tracker

### ISSUE THREAD

**Issue by rrwoods** [HearthSim/Hearthstone-Deck-Tracker#2678]
My opponent played a Yogg-Saron which put one secret into play from each of the three secret classes.  The tracker crashed shortly thereafter.

Where do I find a crash log?

**Comment by riQQ** [comment]
See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues.

**Comment by rrwoods** [comment]
[hdt_log_1468559505.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/366630/hdt_log_1468559505.txt)

**Comment by riQQ** [comment]
There is now crash in your log file. Is this the right one?
>Are there any crash logs in `<HDT dir>\Crash reports`. Attach the ones created at the time your issue occured

**Comment by riQQ** [comment]
Did you look in the windows event viewer (see link above), too?

**Comment by rrwoods** [comment]
Log Name:      Application
Source:        .NET Runtime
Date:          7/15/2016 1:10:06 AM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      rick-asus
Description:
Application: Hearthstone Deck Tracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Collections.Generic.KeyNotFoundException
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib,
Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b77a5c561934e089],[System.Boolean, mscorlib,
Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b77a5c561934e089]].get_Item(System.__Canon)
   at
Hearthstone_Deck_Tracker.OpponentSecrets+<>c__DisplayClass21_0.<Trigger>b__0(Hearthstone_Deck_Tracker.SecretHelper)
   at System.Linq.Enumerable.Any[[System.__Canon, mscorlib,
Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>,
System.Func`2<System.__Canon,Boolean>)
   at Hearthstone_Deck_Tracker.OpponentSecrets.Trigger(System.String)
   at
Hearthstone_Deck_Tracker.Windows.OverlayWindow.GrayOutSecrets(System.Windows.Point)
   at
Hearthstone_Deck_Tracker.Windows.OverlayWindow.MouseInputOnLmbDown(System.Object,
System.EventArgs)
   at Hearthstone_Deck_Tracker.User32+MouseInput.MouseHookDelegate(Int32,
IntPtr, IntPtr)


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-07-15T05:10:06.201062800Z" />
    <EventRecordID>34628</EventRecordID>
    <Channel>Application</Channel>
    <Computer>rick-asus</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: Hearthstone Deck Tracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Collections.Generic.KeyNotFoundException
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib,
Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b77a5c561934e089],[System.Boolean, mscorlib,
Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b77a5c561934e089]].get_Item(System.__Canon)
   at
Hearthstone_Deck_Tracker.OpponentSecrets+&lt;&gt;c__DisplayClass21_0.&lt;Trigger&gt;b__0(Hearthstone_Deck_Tracker.SecretHelper)
   at System.Linq.Enumerable.Any[[System.__Canon, mscorlib,
Version=4.0.0.0, Culture=neutral,
PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1&lt;System.__Canon&gt;,
System.Func`2&lt;System.__Canon,Boolean&gt;)
   at Hearthstone_Deck_Tracker.OpponentSecrets.Trigger(System.String)
   at
Hearthstone_Deck_Tracker.Windows.OverlayWindow.GrayOutSecrets(System.Windows.Point)
   at
Hearthstone_Deck_Tracker.Windows.OverlayWindow.MouseInputOnLmbDown(System.Object,
System.EventArgs)
   at Hearthstone_Deck_Tracker.User32+MouseInput.MouseHookDelegate(Int32,
IntPtr, IntPtr)

</Data>
  </EventData>
</Event>
