### ISSUE TITLE
Crash at starting

### ISSUE THREAD

**Issue by fergab** [HearthSim/Hearthstone-Deck-Tracker#2679]
i got this crash everytime i try to start v0.15.9.  V0.15.8 works 
perfectly
 ![22222222222222222](https://cloud.githubusercontent.com/assets/20472795/16867972/41864c58-4a75-11e6-8560-83d25a9dbad9.jpg)

**Comment by Epix37** [comment]
This should be fixed for the next release. Try if you are still having the issue with this build: https://github.com/Epix37/HDT-Test/releases/tag/v0.15.10pre1

**Comment by fergab** [comment]
this build works! thanks a lot!

**Comment by Epix37** [comment]
Fixed with v0.15.10.
