### ISSUE TITLE
Release v0.15.10 won't install correctly.

### ISSUE THREAD

**Issue by BajczA475** [HearthSim/Hearthstone-Deck-Tracker#2680]
When I try to download and install the update, it forwards me to GitHub to download and install manually. Let me know what other info might be helpful in sussing out why that is happening. Here is a snip of the entire error. 

![capture](https://cloud.githubusercontent.com/assets/15620636/16873970/834c3be0-4a64-11e6-87c0-3b08e7aa68de.PNG)

**Comment by Epix37** [comment]
Duplicate #2562.

There will be a new updater soon, which will solve this.
