### ISSUE TITLE
v0.15.10 Being recognized as malicious and blocked by anti-virus

### ISSUE THREAD

**Issue by lonely-wizard** [HearthSim/Hearthstone-Deck-Tracker#2681]
the exe gets quarantined.

**Comment by Epix37** [comment]
This again :(. Last time we had this, for reference: https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2413

Which AV are you using?


Latest exe on virustotal comes out clean: https://www.virustotal.com/en/file/0e49614f7620f2ac54840a61c9f67a4bd7aef94c05eeb643924b2218d39b100c/analysis/

**Comment by lonely-wizard** [comment]
Avast Free edition. I have since added it to the excluded programs list, but if people aren't noticing the exe removal, they may be experiencing this issue as well.

**Comment by Epix37** [comment]
Closing this for now.
