### ISSUE TITLE
Deck Tracker Loading the same deck every time.

### ISSUE THREAD

**Issue by MaestroDaVinci** [HearthSim/Hearthstone-Deck-Tracker#2683]
Hello i have a problem with Deck tracker and i don't know from what exactly is the problem. For sometime now the deck tracker is constantly loading a random deck which i don't even have in my deck tracker and also it doesn't track my cards. I tried deleting it completely and still the problem occurs,
Here is how it looks inside the game:
http://i.imgur.com/QRgHEen.jpg

This deck is constantly loaded, no matter if i deleted the deck tracker or not. I tried deleting it and downloading it again, the problem still occurs.

Does anyone have a solution?

**Comment by Epix37** [comment]
this is an issue with the current brawl as a result of the changes made on the latest hearthstone update. there is no solution for now, sorry.

**Comment by MaestroDaVinci** [comment]
Well thank you anyway at least.

**Comment by culinko** [comment]
The Tavern Brawls with random decks are using the basic decks at the start of the game. Then all 30 cards go to graveyard and you receive the new random 30 cards. Not sure how should HDT recognize this interaction.

**Comment by Epix37** [comment]
Yes, this happens because of the `SHOW ENTITY`s in the trigger blocks after the initial creation, which were introduced with the last update.

**Comment by Epix37** [comment]
This is now fixed for the next update.
