### ISSUE TITLE
Region is not being detected 

### ISSUE THREAD

**Issue by adnanc** [HearthSim/Hearthstone-Deck-Tracker#2685]
hey Alex, 

I know you have you hands full right now, but when you get a chance can you check this out as well. Region is showing as "Unknown" since the last HS patch.

**Comment by riQQ** [comment]
It's working for me. Does this affect all game modes?

**Comment by Epix37** [comment]
Previously region was detected by some battlenet config as well as by server ip, as a fallback. The logging that contains that ip was removed with the last hearthstone update.

I'll look into finding another reliable way of region detection.

**Comment by adnanc** [comment]
i tried casual, ranked and brawl. all games show up "Unknown". I ran the code as well and Core.Game.CurrentRegion shows "Unknown".

**Comment by adnanc** [comment]
Interesting, wonder why they changed that. Hope you find a way to get the region
