### ISSUE TITLE
v015.10 Gold Progress not tracking

### ISSUE THREAD

**Issue by tknights2015** [HearthSim/Hearthstone-Deck-Tracker#2687]
Gold progress is not tracking in v015.10
[log_1672016-194954.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/367644/log_1672016-194954.txt)

**Comment by Epix37** [comment]
Happens because of https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2685. Fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/62d5beaa671eec82f4efc2241d76e7fa6d24eb74.
