### ISSUE TITLE
the spectator mode can't view the drew, and show me this messges: next drew fatigue for 1

### ISSUE THREAD

**Issue by dyx00001** [HearthSim/Hearthstone-Deck-Tracker#2689]
the spectator mode can't view the drew, and show me this messges: next drew fatigue for 1

**Comment by Werwolfsoul** [comment]
+1
for last few updates THDT it's do nothing in the spectator mode.

**Comment by dyx00001** [comment]
thank you

2016-07-23 19:26 GMT+08:00, Werwolfsoul <notifications@github.com>:
> +1
> for last few updates THDT it's do nothing in the spectator mode.
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2689#issuecomment-234713395


-- 
半之光羽敬上

**Comment by riQQ** [comment]
This is working now.
