### ISSUE TITLE
Import from hearthpwn not working

### ISSUE THREAD

**Issue by prasanna2991** [HearthSim/Hearthstone-Deck-Tracker#2691]
Sample URLs:
http://www.hearthpwn.com/decks/502054-trumps-theorycraft-cthun-druid
http://www.hearthpwn.com/deckbuilder/druid#280:2;282:2;548:2;620:2;633:2;14454:1;27214:1;31110:1;31112:2;31114:2;33121:2;33123:2;33162:2;35189:2;35196:2;35201:1;35212:2

Please let me know if you want more information

**Comment by prasanna2991** [comment]
I am on Windows 10

**Comment by andburn** [comment]
Both links work fine for me on Win10.
Restart HDT and try to import those links again. 
Then post the `hdt_log.txt` file (see [this wiki page](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues) on where to locate the log file).

**Comment by prasanna2991** [comment]
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/372252/hdt_log.txt)

Log file attached. Looks like a 403 forbidden error.

**Comment by andburn** [comment]
weird a 403, must be something strange going on at your end - can't think what though :confused:

**Comment by Epix37** [comment]
Are you behind a proxy?

**Comment by prasanna2991** [comment]
It was because of my firewall, I think. Whitelisting HDT solved the issue. Thanks
