### ISSUE TITLE
Deck export to Hearthstone not working on Windows 10

### ISSUE THREAD

**Issue by prasanna2991** [HearthSim/Hearthstone-Deck-Tracker#2692]
When I try exporting a deck (standard format) to Hearthstone after creating a new deck and selecting "Custom Deck", the following steps occur:
1. Click "Deck Helper" a few times
2. Rename deck (Working properly)
3. Red message shows on screen saying "Use the friends menu to start a conversation with a friend"
4. 0-mana filter gets applied
5. Click on Expansion filter, and select "standard cards"
6. Search for each card, finding no card
7. "Export incomplete" popup on HDT.

I read the [FAQ](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ) and followed these steps:
1. Restart HDT and Hearthstone. Run HDT in administrator mode, and open Hearthstone from HDT.
2. Try all speeds (very low to very high) in fullscreen and windowed modes (on 1920x1080 resolution)
3. Change resolution to 1366x768 (speed: very low)
4. Go to options > tracker > exporting (enable advanced options at the bottom) and increase Wait 0 seconds before starting from 1 second to 2 seconds.

I am on a Windows 10 machine, with no touchscreen display. Display resolution is 1920x1080.

Please let me know if you need more information. Thanks

**Comment by Epix37** [comment]
Try disabling the `options > tracker > exporting > auto clear filters` option.

**Comment by prasanna2991** [comment]
Thanks for the speedy reply Epix. 
I disabled the auto clear filters option. Now the 0-mana filter is not being applied, and the expansion isn't clicked. 
Search is filtering out the correct cards. The cards aren't getting added to the deck though. 
Renaming isn't working properly.

**Comment by tknights2015** [comment]
I have also seen this issue on Windows 7. Just as described above.

**Comment by prasanna2991** [comment]
Downloaded the new version. The import works now. Thanks

**Comment by lhmiranda** [comment]
I would like to reopen this. I'm having this exact issue for the last 2 releases now.
Search filter the cards but none of the cards are getting clicked so they aren't being added to the deck.
