### ISSUE TITLE
Recent Constructed matches in the summary view showing region UNKNOWN

### ISSUE THREAD

**Issue by eshlin** [HearthSim/Hearthstone-Deck-Tracker#2693]
I'm on 0.15.10, but I believe I've been seeing this since the changes last week. I noticed that all my recent Constructed matches show up in the summary view with a region of UNKNOWN. However, if I actually click Edit on the match, the dropdown on the Region shows US.

Here are a few screenshots showing this:

![hdt_unknown_region](https://cloud.githubusercontent.com/assets/866294/16955593/0ee6e786-4d8a-11e6-8402-e9592fbd20be.png)

(Notice the UNKNOWN region in the most recent game. I manually fixed the games older than the most recent one by selecting another region and re-selecting US in the edit mode.)

![hdt_unknown_region_edit](https://cloud.githubusercontent.com/assets/866294/16955604/24119426-4d8a-11e6-8617-ca1e59e1ebae.png)

**Comment by Epix37** [comment]
Duplicate https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2685
