### ISSUE TITLE
Still Sorting Bug

### ISSUE THREAD

**Issue by ProfesorX** [HearthSim/Hearthstone-Deck-Tracker#2695]
In your release v0.15.11 you say "Fixed card sorting to match up with the game again." but,  as you can see in my image, the bug still appears.

It only apears sorted in the "create deck" window, but not in the decks or overlay windows-

http://imgur.com/a/aL8Uf

Sorry my english

**Comment by Epix37** [comment]
Oh, thanks. Reopened #2669.
