### ISSUE TITLE
Can't run the program

### ISSUE THREAD

**Issue by Brocolli123** [HearthSim/Hearthstone-Deck-Tracker#2696]
I just downloaded it and I can't run it. I try opening hearthstone deck tracker but it's not an exe file and it opens in microsoft visual studio, not as an actual program. what is wrong with it

**Comment by andburn** [comment]
Looks like [you have accidentally downloaded the source code](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#no-exe) you need to download the zip from https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/latest
