### ISSUE TITLE
Deck Tracker completely reset

### ISSUE THREAD

**Issue by Yusodus** [HearthSim/Hearthstone-Deck-Tracker#2698]
I got the following Error Message when I opened the program:

########## 21.07.2016 23:37:05 ##########
System.Exception: PlayerDecks.xml is corrupted.
   bei Hearthstone_Deck_Tracker.DeckList.Load()
   bei System.Lazy`1.CreateValue()
   bei System.Lazy`1.LazyInitValue()
   bei System.Lazy`1.get_Value()
   bei Hearthstone_Deck_Tracker.Windows.OverlayWindow.SetDeckTitle()
   bei Hearthstone_Deck_Tracker.Windows.OverlayWindow.Update(Boolean refresh)
   bei Hearthstone_Deck_Tracker.Windows.OverlayWindow..ctor(GameV2 game)
   bei Hearthstone_Deck_Tracker.Core.get_Overlay()
   bei Hearthstone_Deck_Tracker.FlyoutControls.Options.Overlay.OverlayOpponent.Load(GameV2 game)
   bei Hearthstone_Deck_Tracker.FlyoutControls.OptionsMain.Load(GameV2 game)
   bei Hearthstone_Deck_Tracker.Windows.MainWindow.LoadConfigSettings()
   bei Hearthstone_Deck_Tracker.Core.Initialize()
   bei Hearthstone_Deck_Tracker.App.App_OnStartup(Object sender, StartupEventArgs e)
   bei System.Windows.Application.OnStartup(StartupEventArgs e)
   bei System.Windows.Application.<.ctor>b__1_0(Object unused)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Deck Tracker is basically a blank slate right now, everything locally is gone.

**Comment by Epix37** [comment]
Restore the (second to) latest backup, either via `options > tracker > backups` or manually by unzipping the corresponding zip in `%AppData%/HearthstoneDeckTracker/Backups` into `%AppData%/HearthstoneDeckTracker`.

**Comment by Yusodus** [comment]
Thank you! Everything's the way it should be again

**Comment by Epix37** [comment]
:+1:
