### ISSUE TITLE
Suggestion: Track your deathrattle minions that died this game

### ISSUE THREAD

**Issue by PudelCastro** [HearthSim/Hearthstone-Deck-Tracker#2700]
Would it be possible to implement a checkbox option in **Overlay > Player** called _"Display dead deathrattle cards"_ which when ticked in would not be removed from the _Player Overlay_ but instead marked (maybe with a red color, as green is used for currently in hand and greyed out for dead/removed cards)?  

This would **make it easier to at a glance spot which card might be re-summoned if N'Zoth is played**, useful for all N'Zoth deck players.

**Comment by Epix37** [comment]
See #2439
