### ISSUE TITLE
Just a suggestion

### ISSUE THREAD

**Issue by giggioman00** [HearthSim/Hearthstone-Deck-Tracker#2701]
I'm using your tracker from few days and I find it really helpful.
My suggestion is to add a tracker in-game for track the number of played spells (it would be really useful for Yogg players).

In this moment I need to count the number of played spells from my deck (that is useful too). But I think adding some kind of spells tracker just like the C'thun attack/defence tracker would be useful too

Thank you

**Comment by jleclanche** [comment]
There is already a played spell tracker. By default, it shows only when you have yogg'saron in your deck or hand.

Thanks for the feedback!
