### ISSUE TITLE
can't update

### ISSUE THREAD

**Issue by cachirro** [HearthSim/Hearthstone-Deck-Tracker#2702]
![capture](https://cloud.githubusercontent.com/assets/1080782/17079468/279e2780-5109-11e6-8e93-ba47a83a28a9.JPG)

**Comment by Rynvar** [comment]
Search for the **HDTUpdate_new.exe** file and delete it, then retry the update. Seems the update got interrupted once and didn't clean up the file.

**Comment by jleclanche** [comment]
@cachirro Try updating to 1.0: https://hsdecktracker.net/download/

The installer was reworked, this won't happen anymore. Closing for now. Reopen if it's still not working after upgrading to 1.0.
