### ISSUE TITLE
Plugins not turned on after launching HDT

### ISSUE THREAD

**Issue by TheMiziko** [HearthSim/Hearthstone-Deck-Tracker#2703]
Randomly, every 2/3 launches of HDT, tracker automatically turns off plugins, and I need to manually go into options and enable them.
EDIT : And that's what I see after launch in logs 

```
07:39:52|Info|OverlayWindow.Update >> Refreshed overlay topmost status
07:40:12|Info|MainWindow.SelectDeck >> Switched to deck: Arena 23-07 07:08 (v1.0)
07:40:12|Warning|LogReaderManager.Stop >> LogReaders could not be stopped, stop already in progress.
07:40:12|Info|GameV2.Reset >> -------- Reset ---------
07:40:12|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
07:40:21|Info|BackupManager.Run >> Running BackupManager
07:40:21|Info|BackupManager.Run >> Deleting old backup: Backup_16072016.zip
07:40:21|Info|BackupManager.Run >> Creating backup for today
07:40:26|Info|PluginManager.LoadPlugins >> Loading Plugins...
```

**Comment by Epix37** [comment]
Can you reproduce this by starting restarting HDT multiple times? Which plugins are affected?

**Comment by TheMiziko** [comment]
@Epix37 The log is exactly this same after I turn plugins on, and try to restart HDT. All plugins are affected, currently I'm using  3, Treasury, hearth arena uploader, and "arena helper". All of them are turned off after 3/4 relaunch. The most problems occur when I use "launch with windows" option", each time I restart my pc, and HDT launches, plugins are disabled, and after each crash. MY HDT often crashed at the beggining of the game.

That's how my log looks after 1/2 relaunch, where the plugins are still enabled, in this case, I onyl enabled treasury : 
> 09:53:14|Info|OverlayWindow.Update >> Refreshed overlay topmost status
09:53:15|Info|MainWindow.SelectDeck >> Switched to deck: Arena 23-07 07:08 (v1.0)
09:53:15|Warning|LogReaderManager.Stop >> LogReaders could not be stopped, stop already in progress.
09:53:15|Info|GameV2.Reset >> -------- Reset ---------
09:53:15|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
09:53:16|Info|BackupManager.Run >> Running BackupManager
09:53:16|Info|BackupManager.Run >> Backup for today already exists
09:53:16|Info|PluginManager.LoadPlugins >> Loading Plugins...
09:53:16|Info|PluginWrapper.Load >> Loading Treasury
09:53:16|Info|PluginWrapper.IsEnabled >> Enabled Treasury

And sometimes, it launches without this part : 

> 09:53:16|Info|PluginWrapper.Load >> Loading Treasury
09:53:16|Info|PluginWrapper.IsEnabled >> Enabled Treasury

**Comment by Epix37** [comment]
Check if anything in the `%AppData%/HearthstoneDeckTracker/plugins.xml` changes for when it doesn't load.

**Comment by TheMiziko** [comment]
Actually, it appears that, after all crashes and/or pc restart plugins turned off, including change in plugins.xml, and ticking "launch with windows start" on and off fixed the issue, witch is pretty weird.
