### ISSUE TITLE
Can't import decks !

### ISSUE THREAD

**Issue by Loom16** [HearthSim/Hearthstone-Deck-Tracker#2704]
[hdt_log_1469360769.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/380236/hdt_log_1469360769.txt)
I can't import any decks in HDT! When i click import, it stops at that loading screen, as shown in the pic. I tried auto importing, but it does not do anything. I also tried launching the game with the HDT launch hearthstone button, still nothing. Can anyone help me? It takes a looot of time to create the deck manually... Importing worked only once for me, but i didn't do anything specific, I just did the ordinary steps. Please help! (the far right part of the HS screen is hidden but I assure you there is no deck there)

![hearthstone screenshot 07-24-16 11 26 59](https://cloud.githubusercontent.com/assets/20622443/17082781/3ff0dd4e-5192-11e6-9a2f-14f2f8ac3063.png)

I have uploaded the latest hdt log. There are no crash reports and no need to upload windows log files as there are no entries during the time I used HDT.

**Comment by Epix37** [comment]
[Please reproduce the issue and post the log](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues).

**Comment by Loom16** [comment]
Is it ok now? Can you give me any advice?

**Comment by Epix37** [comment]
It looks like HDT is not able to read hearthstones log files. Have a look here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#not-working

**Comment by Loom16** [comment]
Thank you ! I should've checked out the FAQ before posting, sorry.. But it really helped, solved it!

**Comment by Epix37** [comment]
:+1:
