### ISSUE TITLE
Won't show cards left in deck

### ISSUE THREAD

**Issue by Kinnabari** [HearthSim/Hearthstone-Deck-Tracker#2706]
A couple of days ago, the app stopped showing me my entire deck. Instead it just shows cards drawn/discarded/played. I probably clicked a preference somewhere that screwed this up, but for the life of me I can't figure out how to restore this functionality.

**Comment by ksurl** [comment]
click auto at the bottom so it will show your deck automatically. otherwise you have to manually select it every time

**Comment by Epix37** [comment]
Aside from that, make sure you have a deck set as active. See here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#active-deck
