### ISSUE TITLE
HDT not working - not showing cards

### ISSUE THREAD

**Issue by KentusCZ** [HearthSim/Hearthstone-Deck-Tracker#2710]
Hello,

when I start HDT and play a game it only shows my deck on the right side. Nothing happens when I or my opponent plays a card.

**Comment by KentusCZ** [comment]
followed every step: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#not-working

Still not working

**Comment by Epix37** [comment]
> Check if the log files are created at <HearthstoneDir>\Logs and written to.

Are they?

**Comment by KentusCZ** [comment]
They are

**Comment by Epix37** [comment]
Doublecheck HDT is really pointed to that Hearthstone installation, then (with hdt running) play a game and post the log after. See here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by KentusCZ** [comment]
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/387158/hdt_log.txt)

**Comment by Epix37** [comment]
Yeah, HDT is definitely not finding the log files. If Hearthstone is creating and writing to the log files (the Power.log should update a lot during a game) HDT has to be pointed to the wrong installation.
