### ISSUE TITLE
Export funktioniert nicht

### ISSUE THREAD

**Issue by Kalestron** [HearthSim/Hearthstone-Deck-Tracker#2713]
Hallo Epix37,

der Export funktioniert bei mir leider nicht mehr.

Er findet zwar alle Karten (Kartenfilter funktioniert, die jeweils aktuell gesuchte Karte wird aus der Sammlung ausgewählt), aber der eigentliche Export zu Hearthstone schlägt dann fehl.

Am Ende bekomme ich die Meldung über den unvollständigen Export (alle 30 Karten).

Ich habe versuchshalber in den Optionen alle Exportoptionen abgewählt, habe mit den Zeiten experimentiert, immer das gleiche Problem. 

Ich kann dir leider nicht sagen, seit wann genau das nicht mehr geht, muss aber wohl mit einem der letzten Patches zusammenhängen. Ich verwende Win10 und habe sonst keine anderen Programme laufen (außer Battle.net).

VG Kalestron

**Comment by azeier** [comment]
HDT now uses Hearthstones native deck string importing system.
