### ISSUE TITLE
For each match I play, Deck Tracker creates a new version for a specific deck that I'm not using.

### ISSUE THREAD

**Issue by rnklippel** [HearthSim/Hearthstone-Deck-Tracker#2717]
This issue has happened to me since I started using Deck Tracker about 2 months ago. There is a deck that is always shown as active in the list, although I almost never play with it. Whenever I play a match, a new version is created for that deck. If I delete it, the program simply chooses another deck to be the new problematic one. Is this a known issue? Is there a way to solve it?

Here is a portion of the log that is repeated after every match. It always detects a new deck even though nothing was changed in the game.

20:36:01|Info|HearthStatsManager.AddBackgroundActivity >> background process indicator enabled
20:36:01|Error|HearthStatsAPI.PostGameResultAsync >> invalid HearthStatsDeckVersionId
20:36:01|Info|HearthStatsManager.RemoveBackgroundActivity >> background process indicator disabled
20:36:17|Info|GameV2.CurrentMode >> TOURNAMENT
20:36:17|Info|DeckImporter.FromConstructed >> **Found 18 decks, 1 new**
20:36:17|Info|DeckManager.ImportDecks >> Saving Xamã Básico as v236.0 (prev=v235.0).
20:36:18|Info|MainWindow.SelectDeck >> Switched to deck: Xamã Básico (v236.0)
20:36:18|Info|DeckList.ActiveDeck >> Set active deck to: Xamã Básico (Shaman)
20:36:18|Info|GameEventHandler.HandleInMenu >> Game is now in menu.

**Comment by azeier** [comment]
There was a similar issue that was fixed recently, there's a chance this is something similar that I missed. 

Are you on the latest version? 

If you are, please upload the latest data backup (`options (advanced) > tracker > backups > show backup directory`), as well as the actual deck list of the deck in game.

**Comment by rnklippel** [comment]
Yes, I always update to the newest version.

Here is the link for the last backup (the print of the deck is inside the zip file):

[https://dl.dropboxusercontent.com/u/1055359/2idjf9348gr8/Backup_09082016.zip](url) (for some reason I couldn't upload it here directly)

**Comment by azeier** [comment]
Found and fixed the issue!

This will go live with the update for Karazhan (i.e. in the next few days).
