### ISSUE TITLE
SyncPlugins mechanics

### ISSUE THREAD

**Issue by rembound** [HearthSim/Hearthstone-Deck-Tracker#2723]
I tried out Pre-Release v1.0.2, but I don't really understand the need for the SyncPlugins mechanics and see a possible update issue.

First, plugins are copied from `HDT -> APPDATA`. When adding new files to the HDT folder, they are not copied to APPDATA anymore, but they are removed, because the sync mechanics changed source and destination. As in, `APPDATA -> HDT`.

Why not just move everything from `HDT -> APPDATA` every time, without syncing back `APPDATA -> HDT`. Adding updated plugin versions to the HDT folder would update the APPDATA correctly, when there are new files in the plugin-release (There could be obsolete files however).

**Comment by azeier** [comment]
This is mainly an easy way of dealing with the squirrel updating behavior. Opposed to the old updater, it does not overwrite existing files but rather creates a second installation.

The first copy only happens on the initial app start with a verison greater than 0.15.13, to keep existing plugins working.

**Comment by rembound** [comment]
The auto-updater of Arena Helper writes to the old plugin directory, so this would break the updater. After the official release, I can add support for the new plugin directory, but manual installation would be required. The auto-installer would keep popping up, until a newer version is installed.

**Comment by azeier** [comment]
As long as it does not add new files this should not be an issue. Right now it will not update the local file if it's newer than the one in appdata. I was on the verge of changing this to make downgrading possible without restarting HDT twice or manually removing both installation, but this might be a good feature.

**Comment by azeier** [comment]
Also updated files in appdata are not synced correctly as of now. Fixed that with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/d2fabfb5a10e365ceebbdca2a3d584d0e3ada8db.

**Comment by rembound** [comment]
Ah, thanks for clarifying. I assumed it loaded the plugins from the APPDATA directory, so syncing would be redundant.
