### ISSUE TITLE
New Idea: Opponent deck geussing

### ISSUE THREAD

**Issue by rorgier10** [HearthSim/Hearthstone-Deck-Tracker#2729]
When playing verser a opponent, could it be possible to compare their deck to the most popular decks at that moment and predict what will be in his deck. It had to be shown on the deck tracker ofcourse that is a prediction.

For example: I'm playing a zoolock, just like all the matches before. decktracker regignises the first few card my opponent plays and gives the list of the most used meta deck.

It might be way too hard to predict this or way too unbalanced but thought I could share it with you.

**Comment by azeier** [comment]
Likely not something that will be supported by HDT, sorry.

See here for more info: https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues?q=is%3Aissue+deck+prediction+is%3Aclosed

**Comment by pedrotst** [comment]
There is a plugin for this https://github.com/AdnanC/HDT.Plugins.MetaDetector
