### ISSUE TITLE
New Idea: Friends list overlay

### ISSUE THREAD

**Issue by rorgier10** [HearthSim/Hearthstone-Deck-Tracker#2730]
I love decktracker but the only thing that annoys me for over half a year is that my friends list is under the overlay. Is there someway that when you press the friends list button, the overlay disappears untill you hide the friends list again?

**Comment by riQQ** [comment]
- Enable `Advanced options`
- Tick the option `Overlay > Interactivity > Hide deck when friendslist is open`

**Comment by rorgier10** [comment]
I really like that this option was already in here, but there one thing that kinda bugs me, it only hides my deck... I also use the C'Thun and Yogg counters wich overlaps my friends list. It is usable now but still kinda annoying and could be a bit polished.

**Comment by beheh** [comment]
Hey all! After all these years we now have the tech to generally hide parts of overlay interfering with the game:
In the next version of HDT you'll notice that no matter what we/you do in the overlay, if the friends list is open, the overlay will hide the parts that are overlapping the friends list. It's truly as if the friends list was "above" the overlay.
