### ISSUE TITLE
HDT don't work in spectator

### ISSUE THREAD

**Issue by Werwolfsoul** [HearthSim/Hearthstone-Deck-Tracker#2733]
![clipimage](https://cloud.githubusercontent.com/assets/19953370/17435521/2f6c8afe-5b1a-11e6-90a1-53ae8d181a57.jpg)
pls help me fix it. I often use HDT in spectator

**Comment by riQQ** [comment]
Still an issue? It works for me.

**Comment by riQQ** [comment]
Duplicate of #2689
