### ISSUE TITLE
Mana curve shows all cards as minions since 1.0.4

### ISSUE THREAD

**Issue by Zesaric** [HearthSim/Hearthstone-Deck-Tracker#2734]
Don't know if it's just on my machine, but since update 1.0.4, the Mana curve in the lower right corner shows all cards as minions (i.e. green columns). The numbers do add up to 30 so every card is displayed here, but as I said Spells and Weapons are not displayed/colored correctly.

**Comment by Zesaric** [comment]
Correction to my initial post: Weapons are correctly counted, only Spells aren't.

**Comment by azeier** [comment]
Fixed with v1.0.5
