### ISSUE TITLE
Multiple Hearthstone / Battle.net Accounts

### ISSUE THREAD

**Issue by ChuckJrster** [HearthSim/Hearthstone-Deck-Tracker#2736]
Can or should you use the HDT with more than one Hearthstone / Battle.net account? Thanks.

**Comment by azeier** [comment]
Are you talking about multiboxing or just multiple people playing on the same machine at different times?
For the latter you "share" the decks and stats, but other than that it should work just fine. Multiboxing is possible but a little more complex to get going.

**Comment by ChuckJrster** [comment]
Different hearthstone accounts on the same computer. My son & I use the same box. Same & only one profile on my Windows 10 box. Does that make better sense ? I'm currently using HDT but my son would like to use it too. Thx much!

**Comment by azeier** [comment]
The only possible issue then is that there is currently no concept of users/profiles in HDT, so you would be seeing each others decks/stats. If that's not a concern, there should be no problems :).
