### ISSUE TITLE
what is the content needed to manually update the log config?

### ISSUE THREAD

**Issue by AdamAnalytics** [HearthSim/Hearthstone-Deck-Tracker#2742]
I used this website to manually update the log config for hearthstone deck tracker.

https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Setting-up-the-log.config

Before it worked, but this time when I click on "replace the content with this" the page has an error. Can someone paste the content that I need to update the log config or can that link be fixed?

By the way, Hearthstone Deck Tracker is AWESOME and great for arena runs!

Thank you,

Adam

**Comment by azeier** [comment]
Fixed the link.
