### ISSUE TITLE
Tracker slow and crash frequently after update

### ISSUE THREAD

**Issue by GodStopMePls** [HearthSim/Hearthstone-Deck-Tracker#2743]
after my last update it looks like it needs more time to refresh matches,to update deck and when i alt+tab for load manually the correct deck it usually crash

**Comment by azeier** [comment]
Could you post the log when that happens again?
See here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by GodStopMePls** [comment]
problem solved after the newest patch ,ty for your time anyway
