### ISSUE TITLE
New Feature for  Replays - Multiple accounts

### ISSUE THREAD

**Issue by tknights2015** [HearthSim/Hearthstone-Deck-Tracker#2747]
New Feature for replays will not let you claim or add more than one Battlenet account,
Linked an account, thinking I would be able to claim each one.  Deleted the account on HS Replay and now I can't claim the account that I really want to link

**Comment by jleclanche** [comment]
Have you looked at this page? https://hsreplay.net/account/social/connections/

Make **sure** you log out of Battle.net before clicking "Connect a Battle.net account". Let me know if you're still having issues.

**Comment by tknights2015** [comment]
yes, I deleted the original account that I registered so now I get
Signed in as AnonymousUser.  And when I try to login, I get

Account Inactive

This account is inactive.

And there is no way to remove the linked account in HDT or claim another account

**Comment by jleclanche** [comment]
Ah, I see. Account deletes are not instantaneous (so that they can be reverted), but there's a bug that prevents them from being reactivated on log-in. I'll get that fixed - in the mean time, I deleted your account, you should be able to sign up again.

**Comment by azeier** [comment]
To be able to reclaim the account from HDT, edit the `%AppData%/HearthstoneDeckTracker/hsreplay.cache` file and remove the `,"LastUpdated":"TIME"` part. 

I should look like this afterwards: `{"UploadToken":"TOKEN","Status":X,"Username":"USER","Id":ID}`

**Comment by tknights2015** [comment]
This worked.  Thank you
