### ISSUE TITLE
More info about crerated opponent cards

### ISSUE THREAD

**Issue by HugoKornelis** [HearthSim/Hearthstone-Deck-Tracker#2748]
Hi!

Ever since I first encountered HDT I was enthusiastic. It is nice to be able to quickly check on the state of the game without having to do try to memorize everything or without having to coninuously scribble notes.

There's one thing that I still miss, though. When some game effect creates cards in my opponent's hands, HDT marks them as created. And when they are returned cards it also shows me what card it is. But it does not give additional information about other created cards. So now I still do have to track that information myself. Here are some suggestions to improve the information HDT gives on opponent cards:

1. For known cards: Show the card when hovering over it. This would not only apply to returned cards or cards from a Duplicate, Herald Voladzj, etc. But it could also apply to cards created from Nefarian or Thistle Tea after the first of the copies has been revealed.
2. For unknwn cards: Show the card or effect that created it. So hovering over a such a card would e,g, pop up a text "Created by: Mechanical Yeti" - so I know it's a spare part. Or it shows: "Created by: Ethereal Conjurer", and I know it's a spell - and probably a good one because my opponent picked the best out of three,

Would it be very hard to add this as an extra option to HDT? I for one would be extremely grateful!

**Comment by culinko** [comment]
I think what you're suggesting might be similar to #961.

**Comment by azeier** [comment]
Duplicate https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2224.
