### ISSUE TITLE
How do I load an opponent's deck on the overlay?

### ISSUE THREAD

**Issue by RMcD94** [HearthSim/Hearthstone-Deck-Tracker#2749]
Playing same opponent twice in a row (be it AI, ladder or arena) and I know they have the same deck, how do I load it in?

**Comment by TemporalOnline** [comment]
You can't this is a design philosofy of HDT because guessing or even loading an opposite deck could bring HDT to be though of "more than what could be done with pen and paper" and be banished for it.

I myself disagree, but I can see his point.

**Comment by jleclanche** [comment]
It's not really bannable, but for the time being it's out of scope for HDT.

**Comment by RMcD94** [comment]
Oh alright, they should make it so you can use it just for AI then, like adventures
