### ISSUE TITLE
Since claiming account(s) no stats being logged

### ISSUE THREAD

**Issue by ColoradoKnights** [HearthSim/Hearthstone-Deck-Tracker#2752]
Since I've claimed my accounts and assigned them all to deck tracker, no games at all are being recorded in the stats of any type.  When a game completes I get the popup in the bottom corner to share and showing the results but when I go to Stats->Constructed, no matches at all are showing up.  The last ones I have in there were mid-week before I claimed the accounts.  HELP!
![capture](https://cloud.githubusercontent.com/assets/21004035/17643905/f7df0712-6134-11e6-9f36-28c78d2d34b7.gif)

**Comment by ColoradoKnights** [comment]
Forgot to mention I've tried this on two computers and have exactly the same results.

**Comment by azeier** [comment]
- Make sure the mode you are playing is set to record locally (`options > tracker > stats > record`)
- Make sure you don't have any stats filters set - I can't see the bottom few in the screenshot you posted. Since you have stats from mid-week, I assume this is not an issue but I wanted to have said it just in case.
- If neither is the issue, lease play another match and post the log - see here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by ColoradoKnights** [comment]
All the filters are fine...as I can see everything this week PRIOR to claiming account.  I also see that I have the check box for record local replays (attaching that).  I also cleared my log file prior to playing...set the logging level to 1 (at least according to my wife) and am attaching that log here as well.

Thanx!
![capture](https://cloud.githubusercontent.com/assets/21004035/17646555/f28750e2-618b-11e6-9eec-35e3b6acbc66.gif)
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/416839/hdt_log.txt)

**Comment by azeier** [comment]
Pretty sure I found the issue.  Can you confirm this only happens when playing without an active deck?

This seems to be a general bug in the 1.0.5.24 beta, rather than related to the account claiming.

**Comment by ColoradoKnights** [comment]
You are correct.  I just played a game with a named deck and it recorded the stats locally....
![capture](https://cloud.githubusercontent.com/assets/21004035/17649938/7e7c4a00-61fd-11e6-943b-74307546145e.gif)

**Comment by tknights2015** [comment]
Also seeing this issue (ColoradoKnights wife) Appears to be no deck mode.
![no deck mode _ brawl](https://cloud.githubusercontent.com/assets/16232528/17650181/563c41ba-6204-11e6-817e-91b0161afffb.JPG)
[log_1482016-94642.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/417094/log_1482016-94642.txt)

**Comment by tknights2015** [comment]
This is fixed for me in the latest version.

**Comment by ColoradoKnights** [comment]
Yes this also appears to be fixed for me as well.

**Comment by azeier** [comment]
Right, this is fixed with latest update.
