### ISSUE TITLE
Secret Tracker: Competitive Spirit mistakenly greyed out

### ISSUE THREAD

**Issue by jedimaster421** [HearthSim/Hearthstone-Deck-Tracker#2753]
When an opponent starts his turn with a Paladin secret active, and it doesn't trigger, the Secret Tracker will grey out Competitive Spirit even when the opponent has no minions on board. However, Competitive Spirit will only trigger if there are minions it can buff, so it shouldn't be greyed out in that case.

**Comment by azeier** [comment]
I am not able to reproduce this, seems to work fine.

**Comment by manuel-delverme** [comment]
happens to me aswell

**Comment by manuel-delverme** [comment]
[log_2382016-193347.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/433158/log_2382016-193347.txt)
happened again

**Comment by riQQ** [comment]
Can you upload the corresponding .hdtreplay from the Replays sub-folder?

**Comment by manuel-delverme** [comment]
i sent @azeier the power.log is that enough?

**Comment by UrzaMTG** [comment]
I also see this issue regularly. I've attached a ZIP with the replay file.
[UrzaMTG(Shaman) vs Witles(Paladin) 1921-230816.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/433809/UrzaMTG.Shaman.vs.Witles.Paladin.1921-230816.zip)

**Comment by riQQ** [comment]
@manuel-delverme that's fine.

**Comment by rrwoods** [comment]
Apologies for submitting a duplicate.  As this issue isn't open, I didn't see it in my search.

**Comment by azeier** [comment]
reopening this so we stop getting duplicates...

**Comment by vladertel** [comment]
Apologies for submitting a duplicate.
