### ISSUE TITLE
can you import decks from hearthstats into deck tracker ?

### ISSUE THREAD

**Issue by ChuckJrster** [HearthSim/Hearthstone-Deck-Tracker#2756]
I had to format my hard drive & forgot to save my data. My decks are in Hearthstats, so, how or can I import them into HDT? Thanks much!

**Comment by jleclanche** [comment]
@ChuckJrster i see you closed the issue. I don't know if this is fixed for you, but you should know everything hearthstats-related is no longer maintained and may be removed in a future version.
