### ISSUE TITLE
HDT not working.

### ISSUE THREAD

**Issue by Nils1986** [HearthSim/Hearthstone-Deck-Tracker#2759]
Since today HDT stopped working for some reason. When I launch the app, I see that it's loading but nothing appears on my screen even tho the app is in the process manager. I've tried reinstalling the NET. Frame and tried uninstalled HDT but it does the same thing like when I launch the app, loading for a few sec and nothing happens. So I can't launch it, can't uninstall it and have no idea what to do now. Any help? Thx

Edit: Just remembered that I updated my graphic drivers (Nvidia) yesterday, can it be that?

**Comment by azeier** [comment]
- See if you can alt-tab to it - if you can, do so and press Win+Left until you see it.
- Try rebooting if you haven't. 
- If none of that helps, check if HDT creates a log - post it here in that case. See here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by Nils1986** [comment]
I've tried everything but nothing seems to work and it does not create a log. I see the app the process manager with ctrl+alt+del but it never shows up on my screen.

**Comment by Nils1986** [comment]
So I've restored my computer to a save from last sunday (prior to the driver installation) and it works again. Thanks for trying to help me still.

**Comment by Moritasgus** [comment]
Deck Tracker stopped working for me about the same time, I get error saying Hearthstone and Deck Tracker do not have same permissions. My deck list comes up just not active/interactive. Reinstalled 3 or 4 times still same issue
