### ISSUE TITLE
Uneven Permissions (v.1.0.5)

### ISSUE THREAD

**Issue by shybakayen** [HearthSim/Hearthstone-Deck-Tracker#2761]
Hi,

I keep getting the "Uneven Permissions" error on my deck tracker. It was working fine less than 24hrs ago and nothing changed in my system. Should I try reinstalling HS? Because reinstaling HDT didn't help. Is there a simpler solution?

I already tried lauching both applications as admin, tried HS first and HDT second and the other way around and nothing worked. My previous deck overlay is stuck on my screen, but it doesn't update cards nor does it change if I select another deck. Currently running Windows 10, not sure if that matters or not.

Cheers,
Shyba

**Comment by azeier** [comment]
See #2738.

Try starting the Battle.net launcher as admin.

**Comment by azeier** [comment]
Closing in favor of #2738.
