### ISSUE TITLE
HDT Hangs/Crashs on export to HS

### ISSUE THREAD

**Issue by McGootch** [HearthSim/Hearthstone-Deck-Tracker#2764]
When HDT attempts to load a deck into HS with the 'export' function, HDT Hangs. If left, it will add cards to the deck at a rate of approximately (in pairs) 2 cards every 20-30 seconds. HDT will frequently crash during the hang, and has on more than one occasinon caused HS to crash itself as well.

**Comment by McGootch** [comment]
this is specifically related to decks imported with the NetDeck Chrome extension, but I can't confirm/replicate/disprove with other deck import methods

**Comment by McGootch** [comment]
also, meant originally HS itself will crash on the hang. forgive the typos. thanks!

**Comment by azeier** [comment]
Related to https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2584?

**Comment by McGootch** [comment]
unknown, but i will monitor memory usage and post if outside normal range

**Comment by McGootch** [comment]
yup, over 1100mb right now in a heroic battle, trying to get a cap

**Comment by McGootch** [comment]
and it crashed right after that post

**Comment by tknights2015** [comment]
I am seeing this issue also.  Trying to export a deck multiple times multiple crashes.  Only 2 cards added to deck and HDT crashes.

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	HearthstoneDeckTracker.exe
  Problem Signature 02:	1.0.5.28
  Problem Signature 03:	57be06d9
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.6.1076.0
  Problem Signature 06:	56d79fa2
  Problem Signature 07:	403
  Problem Signature 08:	5b
  Problem Signature 09:	System.OutOfMemoryException
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	0b75
  Additional Information 2:	0b75568a0e6063f8cf7482f4e14934ab
  Additional Information 3:	c0ea
  Additional Information 4:	c0ea3fb5f3ebb5e9eecf94b5491c3827

Log file
[log_2682016-115438.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/439836/log_2682016-115438.txt)

**Comment by riQQ** [comment]
Definitely a memory leak.

**Comment by azeier** [comment]
Closing in favor of  #2584.
