### ISSUE TITLE
Unable to claim account on HSReplay

### ISSUE THREAD

**Issue by Xsyanne** [HearthSim/Hearthstone-Deck-Tracker#2766]
When trying to claim account from the options the message gets stuck at "Waiting for HSReplay.net". This may have to do with 2 errors I receive of which you can see a screenshot below. Also attached is the latest hdt_log.

![image](https://cloud.githubusercontent.com/assets/10349879/17829462/4dcdc962-66e2-11e6-809a-32f0b1d9e01b.png)

[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/428155/hdt_log.txt)

**Comment by jleclanche** [comment]
Have you tried restarting hdt and attempting the claim again?

If that doesn't work, email me your hsreplay.cache file in %APPDATA%/HearthstoneDeckTracker/hsreplay.cache to jerome@hearthsim.net and I'll take a further look.

**Comment by Xsyanne** [comment]
Hi, I have tried that several times, as well as rebooting my pc and troubleshooting any potential network issues (none found), to no avail unfortunately. I'll send the respective file via email as instructed. Thanks!

**Comment by Xsyanne** [comment]
Hi,

With regards to issue #2766, please see attached the cache file.

Please note that a moment ago I tethered my 3G connection from my phone
just to test whether it would work on a different network and after
connecting my laptop, I managed to claim the account with no issues. (Only
then was the attached file created as well).

Do let me know if I should mark the issue solved in github, regardless I
just wanted to send you the feedback because you guys have truly developed
an amazing app!

Thank you!
