### ISSUE TITLE
RFC: Shared spec for defining hearthstone decks in HTML

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/Hearthstone-Deck-Tracker#2769]
We have been talking about creating a mini-spec that hearthstone-related websites can follow. A website can declaratively define a deck in html and this will be picked up by deck trackers, scrapers to, for example, quickly import a deck.

We have two proposals right now. This is 100% open to comments from other organizations, authors etc.

Requirements:
- The deck's contents (cards) must be present and be using their hearthstone card ID (`NEW1_030` for Deathwing, for example). 
- The deck's name should be present.
- The deck's class should be present, either as the CardClass enum or the hero id

Here is a list of things which were considered but are _currently_ out of scope. 
- Language (for the deck's name)
- Hearthstone build
- Creation, modification dates etc
- Deck author
- Deck version

These items were rejected in order to make the spec as simple as possible to start with. If the needs for any of these come up in the future, we may amend it.
### Open question: Hero vs. class

Hero makes more sense (eg. for declaring AI decks) but may be harder to deal with for clients as it requires at the very least a lookup table between hero id and class. Class is simpler but has less information. HDT would be fine with both.

---
### Proposal 1: Meta tags

``` html
<meta property="x-hearthstone:deck" content="Patron Warrior"/>
<meta property="x-hearthstone:deck:hero" content="HERO_01"/>
<meta property="x-hearthstone:deck:cards" content="NEW1_030,NEW1_030,EX1_001,EX1_001,..."/>
<meta property="x-hearthstone:deck:url" content="http://www.hearthpwn.com/decks/612030-heroic-crone-1st-attempt"/>
```

This proposal reuses the [OpenGraph syntax](http://ogp.me/). It's very easy to extend and add more attributes in the future.
#### Pros
- Reuses existing spec for storing page metadata
#### Cons
- There doesn't seem to be an obvious way to offer multiple decks per page.
### Proposal 2: In-html containers

``` html
<div
  class="x-hearthstone-decklist"
  data-url="http://www.hearthpwn.com/decks/612030-heroic-crone-1st-attempt"
  data-name="Patron Warrior"
  data-cards="NEW1_030,NEW1_030,EX1_001,EX1_001,..." data-hero="HERO_01"
></div>
```

This embeds the deck in html itself. It is easier to access from Javascript if a website wants to reuse the element to build and display an actual deck on the page. Giving it a class of some form is required to make it easy to scrape out of the page.
The case for multiple decks on a single page is also a lot nicer.
#### Pros
- Multiple decks per page supported
- Easily access the objects from Javascript
#### Cons
- Pollutes the dom.

**Comment by bmichotte** [comment]
I vote for proposal 1.

**Comment by amw2104** [comment]
If someone copies a link to an HSReplay.net replay page from their browser
and paste's it into the HDT import deck field, how will HDT determine which
of the two possible decks should be imported? If we went with Proposal 1
would it be up to the website to determine which deck to place in the
<meta> tag? Perhaps always defaulting to the friendly player's deck would
be a sensible default.

On Mon, Aug 22, 2016 at 2:57 PM, Benjamin Michotte <notifications@github.com

**Comment by jleclanche** [comment]
@amw2104 with proposal 1, multi-deck support is less clear. That's its main downside and why I prefer prop 2.

**Comment by zombie** [comment]
re `hero` vs `class`: adventure decks can be uniquely identified by the name alone "The Crone (Heroic)", so i think `class` being mandatory (with `hero`, etc optional) makes more sense, especially since user decks are the primary use-case.

**Comment by jleclanche** [comment]
That's pretty contrived, requires localization and all.

I think what would possibly make the most sense is making both optional, but relying on class to determine the deck's class (essentially that means class should always be present for class decks).

**Comment by postcasio** [comment]
I think option 2 is better, but consider that most sane representations are going to include the decklist in the HTML, in which case card information can be attached to those list elements instead, avoiding too much duplication and being a bit cleaner (as I personally think having attributes be comma separated lists is a bit gross)

e.g. something like

```html
<div class="x-hearthstone-decklist" data-hero="HERO_01">
  <h1><a href="http://www.hearthpwn.com/decks/612030-heroic-crone-1st-attempt" data-url data-name>Patron Warrior</a></h1>
  <ul>
    <li data-card-id="NEW1_030"><span data-card-count>2</span> Deathwing</li>
    <li data-card-id="EX1_001"><span data-card-count>2</span> Lightwarden</li>
  </ul>
</div>
```

Data attributes could allow two forms: if an attribute has a value, use that value, otherwise use the content of the node (url could also look in the href attribute). Attributes could be specified on the root node (with class x-hearthstone-decklist) and if not present, the parser will look for child nodes.

**Comment by jleclanche** [comment]
@postcasio The problem is two-fold:

1. If that structure is built in JS, then it's not scrapeable without a JS engine (which defeats the point of the spec)
2. It puts very strict requirements on the website's DOM. This may require reworking or implementing a lot of code (eg. some websites straight up use images for decklists).

**Comment by jleclanche** [comment]
It looks like we'll be going for the meta tag proposal. To that end, I've been trying to figure out how to make it work with multiple decks on the same page.

Amendment to the proposal:

* An optional `x-deck-id` html attribute can be added to the meta tags. This ID will uniquely identify a deck with an ID of the website's choosing (for example, a database ID, a UUID, whatever).
* If more than one deck is to be on the page, the `x-deck-id` **must** be specified on all tags.

**Comment by jleclanche** [comment]
We'll be moving forwards with the meta tag proposal regardless of the outcome of the above amendment. Once we get to supporting multiple decks we'll confirm whether that's what's in place.

**Comment by bmichotte** [comment]
I just implemented the import in https://github.com/HearthSim/HSTracker/commit/0d05924df2ee3dec667101eb68b46e9d007a3af3.
Don't you think `card_id:count` is nicer than `card_id,card_id` ?

IE, with your example : 
```
<meta property="x-hearthstone:deck:cards" content="NEW1_030,NEW1_030,EX1_001,EX1_001,..."/>
```
VS
```
<meta property="x-hearthstone:deck:cards" content="NEW1_030:2,EX1_001:2,..."/>
```

**Comment by jleclanche** [comment]
Im not against it, though for now this keeps things simple.

**Comment by bmichotte** [comment]
Also, maybe something like `<meta property="x-hearthstone:deck:type" content="arena|brawl|(ranked|casual)"/>` could be nice

**Comment by azeier** [comment]
## Proposal 1 is implemented and can be used by any website that wants to support HDT importing!

### Required properties:
- `x-hearthstone:deck`:  Name of the deck, HTML encoding is supported
- `x-hearthstone:deck:cards`: Comma separated list of CardId,, multiple copies need to be listed separately. E.g. `CARD_ID1, CARD_ID1` for two copies
- `x-hearthstone:deck:hero`: **CardId** of the the hero, **NOT** the class name (HERO_01, not Warrior)

### Optional properties: 
- `x-hearthstone:deck:url`: source url of the deck, HDT stored the pasted url when importing if not provided.

### Example"
```
<meta property="x-hearthstone:deck" content="Patron Warrior"/>
<meta property="x-hearthstone:deck:hero" content="HERO_01"/>
<meta property="x-hearthstone:deck:cards" content="NEW1_030,NEW1_030,EX1_001,EX1_001,..."/>
<meta property="x-hearthstone:deck:url" content="http://www.hearthpwn.com/decks/612030-heroic-crone-1st-attempt"/>
```

**Comment by waibcam** [comment]
HearthNews ready : https://www.hearthnews.fr/decks/8081 ;)
Keep up the good work guys !

**Comment by bmichotte** [comment]
Thanks for your support @waibcam !

**Comment by azeier** [comment]
Now available on the wiki: 
- [Implementation](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/RFC-Importing---Implementation)
- [Participating websites](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Web-importing)

I'll leave this open for now, for any discussion on e.g. extending functionality.

**Comment by jleclanche** [comment]
I confirmed something neat: Having multiple identical sets of opengraph tags with different values is valid. Github does it, in fact:

```html
    <meta property="og:image" content="https://assets-cdn.github.com/images/modules/open_graph/github-logo.png">
    <meta property="og:image:type" content="image/png">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="1200">
    <meta property="og:image" content="https://assets-cdn.github.com/images/modules/open_graph/github-mark.png">
    <meta property="og:image:type" content="image/png">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="620">
    <meta property="og:image" content="https://assets-cdn.github.com/images/modules/open_graph/github-octocat.png">
    <meta property="og:image:type" content="image/png">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="620">
```

Thus I think we are safe to say that this spec implicitly supports multiple decks by specifying multiple blocks of decks in a row. This isn't implemented in any tracker but there wouldn't be an issue doing so.

I think we're good to close the issue. Discussion can still happen here either way, but this is done and done. Yay!

**Comment by jleclanche** [comment]
Actually, I will reopen this to discuss deck types real quick. The number one request in here has been to add deck types. Since we first worked on this, we found the `DeckType` enum and I would like to use it.

Here is the DeckType enum:

```py
class DeckType(IntEnum):
	"PegasusShared.DeckType"

	UNKNOWN_DECK_TYPE = 0
	NORMAL_DECK = 1
	AI_DECK = 2
	DRAFT_DECK = 4
	PRECON_DECK = 5
	TAVERN_BRAWL_DECK = 6
	FSG_BRAWL_DECK = 7
	HIDDEN_DECK = 1000
```

The values (I'm going from memory, would have to double-check them before putting them into the spec):

* `NORMAL_DECK`: A generic deck that goes in the collection manager.
* `AI_DECK`: A deck that is used by the AI (pve adventures, tutorial etc).
* `DRAFT_DECK`: An arena deck.
* `PRECON_DECK`: I believe these are the 9 preconstructed decks you get when starting the game. I'm not sure they're still used since the collection manager revamp / deck slot increase.
* `TAVERN_BRAWL_DECK`: Your weekly **constructed** brawl deck. This does not include the "randomized" brawl decks and the preconstructed brawl decks; it's only for decks you build yourself in brawl.
* `FSG_BRAWL_DECK`: Likely related to the new fireside gathering stuff in 8.0.0. I don't know how that works.
* `HIDDEN_DECK`: No idea. Internal.

I suspect we can allow all the values except `UNKNOWN_DECK_TYPE`and `HIDDEN_DECK`, default to `NORMAL_DECK` if not found. We should also use the string enum, not its numeric value, to avoid confusion.

This would look like the following:

`<meta property="x-hearthstone:deck:type" content="TAVERN_BRAWL_DECK"/>`

Thoughts?

**Comment by jleclanche** [comment]
Actually, I will reopen this to discuss deck types real quick. The number one request in here has been to add deck types. Since we first worked on this, we found the `DeckType` enum and I would like to use it.

Here is the DeckType enum:

```py
class DeckType(IntEnum):
	"PegasusShared.DeckType"

	UNKNOWN_DECK_TYPE = 0
	NORMAL_DECK = 1
	AI_DECK = 2
	DRAFT_DECK = 4
	PRECON_DECK = 5
	TAVERN_BRAWL_DECK = 6
	FSG_BRAWL_DECK = 7
	HIDDEN_DECK = 1000
```

The values (I'm going from memory, would have to double-check them before putting them into the spec):

* `NORMAL_DECK`: A generic deck that goes in the collection manager.
* `AI_DECK`: A deck that is used by the AI (pve adventures, tutorial etc).
* `DRAFT_DECK`: An arena deck.
* `PRECON_DECK`: I believe these are the 9 preconstructed decks you get when starting the game. I'm not sure they're still used since the collection manager revamp / deck slot increase.
* `TAVERN_BRAWL_DECK`: Your weekly **constructed** brawl deck. This does not include the "randomized" brawl decks and the preconstructed brawl decks; it's only for decks you build yourself in brawl.
* `FSG_BRAWL_DECK`: Likely related to the new fireside gathering stuff in 8.0.0. I don't know how that works.
* `HIDDEN_DECK`: No idea. Internal.

I suspect we can allow all the values except `UNKNOWN_DECK_TYPE`and `HIDDEN_DECK`, default to `NORMAL_DECK` if not found. We should also use the string enum, not its numeric value, to avoid confusion.

This would look like the following:

`<meta property="x-hearthstone:deck:type" content="TAVERN_BRAWL_DECK"/>`

Thoughts?

**Comment by judge2020** [comment]
Deck strings :o

**Comment by jleclanche** [comment]
Yes, deck strings have been added to the spec as well. They replace the `cards` and `hero` properties, although both methods will be supported for a long time (we recommend implementations switch to using deckstrings however).

**Comment by riQQ** [comment]
@jleclanche what's the status of deck types? Can this be closed?

**Comment by jleclanche** [comment]
Closing this yes, since deckstrings are a thing now this doesn't make much sense to support anymore. The documentation is all there in case someone in the future is curious.
