### ISSUE TITLE
Log file could not be updated

### ISSUE THREAD

**Issue by JanloDT** [HearthSim/Hearthstone-Deck-Tracker#2770]
Hi guys,

I recently updated to version 1.0.5 and since then it has given me the error or "could not update log file".
I have then followed the instructions to update it manually and it still gives the error.
I am running HDT as admin, i have restarted the game, as well as uninstalling and reinstalling the tracker.

The latest log file is attached.

Regards,
Janlo
[hdt_log_1471892752.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/430933/hdt_log_1471892752.txt)

**Comment by riQQ** [comment]
Go to `Options > Tracker > Settings` and click `Set Hearthstone path` and select the directory where Hearthstone is installed.

**Comment by azeier** [comment]
It almost looks like your `%LocalAppData%` is not defined, but HDT is installed correctly - so I'm not really sure what's going on.

Open the command promp (Win+R, "cmd") and write `echo %LocalAppData%`. What does it say?

**Comment by JanloDT** [comment]
I am not currently at my machine, but will let you know as soon as i am able to test.
Thank you for the suggestions and responses.

**Comment by JanloDT** [comment]
I have set the Hearthstone path and restarted HDT, unfortunately that did not solve the problem.

When i Echo %LocalAppData% i get a path returned : C;\Users\Cosmo\AppData\Local

I have attached the latest log file, if it could be of any assistance.
[hdt_log_1471966325.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/432862/hdt_log_1471966325.txt)

**Comment by JanloDT** [comment]
I seem to have solved the problem. 
When i look at the error log i see a line "5:31:50 PM|Error|LogConfigUpdater.CheckLogConfig >> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Cosmo\AppData\Local\HearthstoneDeckTracker\app-1.0.5\Blizzard\Hearthstone\log.config'." and since the Echo went up to the AppData node i decided to follow it all the way.
For some reason my Blizzard\Hearthsone\log.config directory was not in the same AppData folder. I copied and pasted it into the app-1.0.5 folder and restarted HDT and the message did not pop up again. 

Thanks you for all the suggestions.

**Comment by azeier** [comment]
While this removes the warning, the `Blizzard\Hearthstone` directory should be (and is) located in `%LocalAppData%` - this is where you manually updated the log.config and where the Hearthstone client looks for it.

It seems that for some reason HDT gets an empty value for `%LocalAppData%` on your system causing it to look at `{CurrentDirectory}\Blizzard\Hearthstone` rathern than `C:\Users\Cosmo\AppData\Local\Blizzard\Hearthstone`.

It's very possible that the underlying issue may causes other problems as well.

**Comment by JanloDT** [comment]
Ah, i see what you mean. any suggestions on what to try?

**Comment by azeier** [comment]
Tbh, I don't really know. The weird part is that HDT is *installed* in %LocalAppData% (and you are getting the correct output). 

If you don't notice other problems - as long as you update the actual log.config whenever HDT says it was updated and you need to restart Hearthstone (shouldn't happen very often) - you might be ok.

**Comment by JanloDT** [comment]
Thanks a lot, lets hope for the best :)
