### ISSUE TITLE
When set to "Wild", still displays Standard decks.

### ISSUE THREAD

**Issue by MT-Arnoldussen** [HearthSim/Hearthstone-Deck-Tracker#2771]
I understand that it is theoretically possible for a Wild deck to consist of only Standard cards, but in 99% of the cases it won't. Could there at least be an option somewhere to not show Standard decks in the Wild section?

If there already is such an option, I apologize, for I could not find it. Regardless, such an option should be turned on by default!

**Comment by azeier** [comment]
There is an option to do that, though it's admittedly a bit hidden. If you press the double arrow button next to the arena/standard/wild filter, you will find a "include 'standard' decks in 'wild' option at the very bottom.
