### ISSUE TITLE
Issues with Hearthstats sync between two computers

### ISSUE THREAD

**Issue by 305jeff** [HearthSim/Hearthstone-Deck-Tracker#2772]
Hey guys! Just some feedback from my experience. I just bought a Surface Pro 4 and installed HSDT. I transferred a backup from my desktop to the Surface and restored the data, copying over all my statistics.

I enabled Hearthstats sync and played 5 games on my Surface and noticed the following after manually syncing both computers:

1) Of the 5 games, only 4 of them appeared on my Desktop after sync. I checked the Hearthstats Dashboard and see all 5, so I don't know why one of them won't complete the sync to my Desktop.

2) The games contain very basic data - no decklists, no replays. This seems odd since when I view the games in the Hearthstats Dashboard, it has a page dedicated to showing Turn by Turn, but it's empty...so maybe that doesn't sync?

3) For some reason, in Stats/Constructed/Matches, it says UNKNOWN for the Region...but if I click Edit, it has "US" selected already. Clicking save fixes it.

4) Every time I sync, even if I do it multiple times in a row, it always says "uploading 32 matches". EDIT: I checked the log and found an error with a bunch of matches from 2015 that were Mode: None. Deleting them fixed this.

So...is Hearthstats just a basic sync with some issues? I read in another thread that creating a symbolic link to Dropbox is the best way. Is that still the best answer? It won't really work because the Desktop and Surface have different resolutions/aspect ratios so the positioning of the overlay will need to be different for each device...but syncing the config file will force them to be the same :(

Thanks again for all your awesome work!

-Jeff

**Comment by 305jeff** [comment]
I got some help in another thread I posted in and ended up using Dropbox with some tricks...I made a mini guide:
https://www.reddit.com/r/hearthstone/comments/4zi860/how_to_sync_hearthstone_deck_tracker_on_multiple/

**Comment by judge2020** [comment]
HearthStats is no longer supported by HDT, a new synchronization system is planned for HSReplay.
