### ISSUE TITLE
Cat Trick (Hunter secret) isn't in the secret tracker

### ISSUE THREAD

**Issue by NightKev** [HearthSim/Hearthstone-Deck-Tracker#2776]

**Comment by azeier** [comment]
Fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/784171b46c1d99500675a1fb75e3570c8359a51c

**Comment by azeier** [comment]
This is now fixed in the latest hsreplay beta build. Live should follow soon.

**Comment by judge2020** [comment]
fixed now
