### ISSUE TITLE
Problem with sync and PlayerDecks.xml

### ISSUE THREAD

**Issue by Sevis** [HearthSim/Hearthstone-Deck-Tracker#2780]
Hello,

When I start HDT I have very old information about my decks and matches.

I push “Start full sync” and after syncing I have actual information about my decks and matches.

I archive some decks, play some matches and close HDT.

Unfortunately, changes not saved. When I start HDT again I have very old information and get this message:

![hdt_error](https://cloud.githubusercontent.com/assets/10126982/18042484/b6766770-6dd2-11e6-8e57-e49d624656c7.jpg)

How I can correct this problems? I need that data after syncing was saved and I can see it after restarting HDT without full sync.

**Comment by judge2020** [comment]
Hearthstats has been discontinued, please see #3235 for the new feature HSReplay is planned to have.

**Comment by judge2020** [comment]
duplicate of #3235
