### ISSUE TITLE
100% known secret is not added to the deck

### ISSUE THREAD

**Issue by HellbringerOnline** [HearthSim/Hearthstone-Deck-Tracker#2781]
When the remaining a single version of the secret, which may be in the your opppnent deck, it is not added to the deck. If the game ends before the secret is opened, it will be not added to the deck.

**Comment by HellbringerOnline** [comment]
![1](https://cloud.githubusercontent.com/assets/14059683/18052709/fec92f6e-6e0c-11e6-8101-2cdf49e7fc4f.PNG)

**Comment by azeier** [comment]
Since secret detection can potentially make mistakes, this is not something I would want to do.
