### ISSUE TITLE
PlayerDecks.xml gets corrupted

### ISSUE THREAD

**Issue by HS-Disq** [HearthSim/Hearthstone-Deck-Tracker#2782]
Hiya,

Since I had a BSOD, everytime I start up the HDT, it says that PlayerDecks.xml got corrupted. I've already removed HDT from my F:\ drive as well as from %appdata%\..\Local\HearthstoneDeckTracker and installed the latest version again, but it still says that it's corrupted.

I sync my decks with HearthStats, so there is no loss of stats or decks, but each change I make with my current decks (deleted or archived) result in it returning.

What can I do now if reinstalling doesn't work for me? I've looked at similar issues, but some are very old and some don't work.

Thanks in advance.

~Disq

**Comment by azeier** [comment]
Try restoring one of HDTs backups from before the BSOD under `options (advanced) > tracker > backups`.

**Comment by HS-Disq** [comment]
Unfortunately, that's not possible. The BSOD happened on the 21st and it seems the tracker only has backups from the last 7 days.

**Comment by HS-Disq** [comment]
Happened again this morning. I can't find where the PlayerDecks.xml is stored, else I can just delete it and sync from Hearthstats again.

**Comment by azeier** [comment]
I think the problem is that the data coming from HearthStats causes HDT to not be able to save the PlayerDecks.xml properly. 

You can find the file under `%AppData%/HearthstoneDeckTracker`.

**Comment by HS-Disq** [comment]
It may have done the trick, I've been removing it from the Local AppData, not the Roaming. Closed, renamed both PlayerDecks.xml and the Backups folder, started, synced, closed and started again. No error so far.

I've lost some data, it seems, but not that big of a deal. I'll let you know if it happens again tomorrow.

**Comment by HS-Disq** [comment]
It is working fine again, thanks Azeier ;)
