### ISSUE TITLE
My HDT deleted itself

### ISSUE THREAD

**Issue by TemporalOnline** [HearthSim/Hearthstone-Deck-Tracker#2783]
As is. My HTD deleted itself. I tried the beta. It was working great. Now, the program is gone, just the files are there.

EDIT: Downloaded the 1.0.5 again. All seems well, just strange my HDT deleted itself.

**Comment by azeier** [comment]
The new updater uninstalls old versions when it updates. What's in `%LocalAppData%/HearthstoneDeckTracker`?

**Comment by TemporalOnline** [comment]
Looks like a backup of 1.0.5.28, another from 1.0.5.29 from yesterday, another dir called packages, squirrelsetup.log and Update.exe.

My problem is that I had all my shortcuts everywhere pointing to the dir inside the hearthstone folder (when I travel, it is easier to copy it all than to keep copying things from everywhere) and it deleted the executable from THERE.

That's why I "panicked" :)

**Comment by azeier** [comment]
The updater shouldn't touch anything outside of `%LocalAppData%/HearthstoneDeckTracker`.

Can you reproduce it? 
- Replace your installation in the Hearthstone folder (that's not a good place to keep things - Hearthstone might decide to remove files it doesn't need)
- delete everything in the the `%LocalAppData%/HearthstoneDeckTracker` folder
- [download and run the 1.0.5.28 installer](https://github.com/HearthSim/HDT-Releases-HSReplay/releases/download/v1.0.5.28/HDT-Installer.exe) - this will start .28 and immediately download .29 in the background, you should see a notification under the title bar after a few seconds

**Comment by TemporalOnline** [comment]
Sorry for the late reply, I was trying to reproduce my conditions, nothing abnormal has happened since then.

I backup my system weekly, so if hearthstone one day decides to delete strange things from its folder, I'm not worried. As I said, it is easier to set both app and path there, then just copy the entire path from my PC to the Note on the fly when I travel or something.

Another thing I usually do to programs I trust and that I have to keep giving permission is to give them admin using another program called "UACpass", which creates a service that runs in admin level and then if it need to update or work it doesn't have to keep bothering me as it used to happen while I had W8(up until last month, looks like it has eased on W10). I don't know if maybe that has something to do with anything, maybe before it didn't have permission to change things on the programs folder and now it has. Just a guess, but anyway, nothing strange has happened now.

If something happens again, I'll keep you posted :)

Thank you!

**Comment by TemporalOnline** [comment]
People... happened again on the update from 1.0.5 to 1.1 :(

**Comment by jleclanche** [comment]
Is it possible your permissions are messed up somehow? Have you ran hdt as admin at some point or some such?

At this point I'd recommend backing up your settings, uninstalling hdt completely, reinstalling it and restoring the settings manually.
