### ISSUE TITLE
Not syncing certain matches with Hearthstone Deck Tracker

### ISSUE THREAD

**Issue by TheOneGodKing** [HearthSim/Hearthstone-Deck-Tracker#2785]
I've been using Hearthstone Deck Tracker by itself. I recently set up at HearthStats account and wanted to sync over the matches and decks that were saved locally on my computer. After syncing, it would only sync certain matches (19 out of 53) and then delete the rest of the matches. The matches it syncs seems to be entirely random from various dates. Any idea what might be happening?

**Comment by judge2020** [comment]
Hearthstats has been discontinued, please see #3235 for the new feature HSReplay is planned to have.

**Comment by judge2020** [comment]
duplicate of #3235
