### ISSUE TITLE
Exporting to hearthstone -> RAM overflow

### ISSUE THREAD

**Issue by SebGlauser** [HearthSim/Hearthstone-Deck-Tracker#2788]
Hi,

First, **thanks** for your job!

I've manage to crash your application. When i'm exporting a deck to hearthstone the application is killed by window; It's seem the application allocate too much.

It's seem that's the bug it's not from your application because the v1.0.5 worked fine last week.
But may be it would help.

win7 64Bits
Hearthstone Deck Tracker 1.0.5

![capture](https://cloud.githubusercontent.com/assets/9332396/18183494/faf9fc76-7094-11e6-9a38-dd5a924d051a.PNG)

**Comment by SebGlauser** [comment]
Update test with the beta.

Exportation worked fine, but sometimes the application freeze and use more than 1.3Go of RAM

Sorry for my english

**Comment by riQQ** [comment]
See #2584.

**Comment by azeier** [comment]
> -test beta: Exportation worked fine.
But sometimes the application freeze and use more than 1.3Go of RAM

Do you still have issues with the download linked here https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2584#issuecomment-243382143?

Closing this in favor of #2584.
