### ISSUE TITLE
[dev question]  what's the line ending style of the whole project 

### ISSUE THREAD

**Issue by jindaxia** [HearthSim/Hearthstone-Deck-Tracker#2790]
CRLF or LF ???
I have some problem in my git client

**Comment by azeier** [comment]
It's supposed to be `LF`, there's some inconsistencies however :/.

**Comment by jindaxia** [comment]
@azeier  OK thanks,

**Comment by jindaxia** [comment]
what the hell some files use CRLF and other files use LF,
example , 
DeckManager.cs   LF
TrayIcon.cs  CRLF

**Comment by azeier** [comment]
>  some inconsistencies

Mainly older stuff is still CRLF

**Comment by jindaxia** [comment]
OK I can send a PR

**Comment by azeier** [comment]
No need. I would rather not merge +30k/-30k PRs. 
And it's something I currently don't want to mess up blame on here over. It's gonna get fixed at some point.
