### ISSUE TITLE
[Joust] C'thun not being tracked properly in hand for relay (default replay)

### ISSUE THREAD

**Issue by gardian06** [HearthSim/Hearthstone-Deck-Tracker#2795]
I was going though a game I had just finished checking the turns. where both of us were playing C'thun. as I was scrolling through, and I came to find out that my opponent actually kept C'thun in his opening hand.
when I stopped at random points checking the attack/health values of both of our C'thun they always said 6/6 even after a C'thun buff was played. though when the C'thun was played the replay showed 2 entries for the play 1 for playing a 6/6 C'Thun, and one for the proper x/x values as though it was buffed right then and there similar to how the replay shows a card buffing another card in play.

I do not think the default replay system includes modifications of cards in hand.

**Comment by azeier** [comment]
@beheh Is this fixable with the current oracle?

**Comment by beheh** [comment]
No, it's because we have two C'Thun Entities. Shouldn't be too hard to just transfer the tags though.

**Comment by jleclanche** [comment]
Tracking in https://github.com/HearthSim/joust/issues/133
