### ISSUE TITLE
Arena decks are imported automatically even though auto-import setting is "manual"

### ISSUE THREAD

**Issue by aalear** [HearthSim/Hearthstone-Deck-Tracker#2796]
My import settings look like this:

![image](https://cloud.githubusercontent.com/assets/361657/18236570/799db1f0-72f5-11e6-95dc-ded03cf798f1.png)

However, every time I start a new arena draft, the deck is automatically imported into HDT at the end of it.

**Comment by azeier** [comment]
Seems to work fine for me, are you using any plugins that might do this?

If not, please reproduce the issue and post the log - see here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by aalear** [comment]
No plugins are enabled, although I have used Arena Helper in the past.

Here's the log from app start to draft to start of game. Also I was apparently wrong above - the import happens not when the draft finishes, but when the first arena game with the new deck begins.

[hdt_log - Copy.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/455367/hdt_log.-.Copy.txt)

Thanks!

**Comment by aalear** [comment]
@azeier Looks like DeckManager.AutoImport now gets called every time current active deck doesn't match whatever is selected in-game, and the default for Arena games is AutoImportSave instead of whatever is in the config.

My local HDT setup seems pretty broken here (unrelated build failures galore and it's 1 a.m. so I'll wrestle with it later), but if I'm reading the code right and assuming I remember how to use config values correctly... I propose changing line 276 in DeckManager.cs from

`AutoImportArena(ArenaImportingBehaviour.AutoImportSave);`

to

`AutoImportArena(Config.Instance.SelectedArenaImportingBehaviour ?? ArenaImportingBehaviour.AutoAsk);`

**Comment by azeier** [comment]
That should do it, thanks.
`AutoImportSave` makes mroe sense over `AutoAsk` since it's the default behavior.
