### ISSUE TITLE
[Localization] Looking for translators

### ISSUE THREAD

**Issue by azeier** [HearthSim/Hearthstone-Deck-Tracker#2797]
# Localization

So this is finally happening!

Most of the localization work is done, only a few dialogs and option related things should be missing.
**Right now, this lives in the [localization branch](https://github.com/HearthSim/Hearthstone-Deck-Tracker/tree/localization).**

**Edit: Strings files have been moved to [HearthSim/HDT-Localization](https://github.com/HearthSim/HDT-Localization)**

If you would like to help out, please read below.
## Adding a new language
- Create a PR here with the following:
  - Modify the `Hearthstone Deck Tracker.csproj` to set it as a dependency on `Strings.resx`.
  - Add a new value + description to `Enums/Language.cs` (this time without the `-`).
- Create a PR over at [HearthSim/HDT-Localization](https://github.com/HearthSim/HDT-Localization) with the following: 
  - Add a new resx file called `Strings.{NAME}.resx`. Make sure to use the correct culture name here (include the `-`). [National Language Support (NLS) API Reference
    ](https://msdn.microsoft.com/en-us/goglobal/bb896001.aspx)
    See https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/dced34cc501215cb5e6916a7dbe17e44cb00026e as reference.
## Translating
- Recommended software: [ResX Resource Manager](https://resxresourcemanager.codeplex.com/)
- Please do post something in here if you want to help out, so that we don't end up with people working on the same parts of the same language.
- Creating a work-in-progress PR is very welcome. 
- Some UI elements might not work too well with strings that are much longer than the english version. Please try to work around this for now and let me know where they are.
## Adding missing localizations
- If anyone wants to help out with this, that's also much appreciated. 
- As mentioned above, some dialogs and options (more specific things like ComboBox items) are still missing localization. Maybe I missed a few other things, too.
- Please take a look at the naming style used in the other commits.
# Translations in progress:
- **zh-CN**: #2793
- **fr-FR**: #2801
- **de-DE**: I started on that a bit, up for grabs
- **ru-RU**:  #2820

**Comment by jindaxia** [comment]
great

**Comment by Drui7** [comment]
Russian, ru-RU: [https://drive.google.com/file/d/0B2_jAjiSYLeCT0ZEamh6aWx6Z00/view](url) (~117kB)

All strings translated. The basis is taken Strings.resx, done with ResX Resource Manager.
Maximum literary translation, as well as about the same on the line width in comparison with the English.

Yes, I have a very bad man, still has not learned to use this site. excuse me. and I have not yet figured out how to connect the file to the project. like so:

Hearthstone Deck Tracker/Enums/Language.cs

```
namespace Hearthstone_Deck_Tracker.Enums
{
	public enum Language
	{
		[Description("English")]
		enUS,
		[Description("German")]
		deDE,
		[Description("Русский")]
		ruRU
		[Description("中文（简体）")]
		zhCN
	}
}
```

and the need to add a lines to  
Hearthstone-Deck-Tracker/Hearthstone Deck Tracker/Hearthstone Deck Tracker.csproj

```
  <EmbeddedResource Include="Properties\Strings.ru-RU.resx">
    <SubType>Designer</SubType>
    <DependentUpon>Strings.resx</DependentUpon>
  </EmbeddedResource>
```

**Comment by Vladsg** [comment]
Drui7 need create pull request

**Comment by rabinhoud2017** [comment]
I want help but im confused.
How can translate to fa-IR

**Comment by azeier** [comment]
- Create a fork of the [HDT-Localization repo](https://github.com/HearthSim/HDT-Localization) (button in the top right) - More info on forks: https://help.github.com/articles/fork-a-repo/
- If you dont have it, download [git](https://git-scm.com/download/win)
- From the command line, in the directory of your choice do `git clone https://github.com/rabinhoud2017/HDT-Localization`
  - If you don't want to use the command line you can also download something like [GitExt](https://gitextensions.github.io/)
- Download and install [ResX](https://github.com/HearthSim/HDT-Localization#recommended-software), then open the `Strings.resx` file in the folder git clone created.
- Add a new language via the button in the top bar.
- Translate :)
- From the folder, in cmd: 
  1. Track your new file: `git add <your new file>`
  2. Commit your new file: `git commit -m "Add Persian translation"`
  3. Push your changes to your fork: `git push`

Repeat steps ii. and iii. until fully translated (or just once at the end)

Finally (or any any point after pushing to your fork for the first time): Create a pull request - there should be a button for that on your fork. Any changes you push to your fork after that will automatically show up in the pull request.

**Comment by rabinhoud2017** [comment]
thank you man. but where is cards description?
this is software menu translate or cards description?

**Comment by azeier** [comment]
Cards names and descriptions are automatically generated from the game files, we don't have a way to add manual translations there.

**Comment by Zawodowiec1532** [comment]
I think this can be closed for now, or move part of description to HearthSim/HDT-Localization.
