### ISSUE TITLE
rename HSReplay project in solution or rename the corresponding repository on github

### ISSUE THREAD

**Issue by chucklu** [HearthSim/Hearthstone-Deck-Tracker#2803]
the location for HSReplay projetc is  Hearthstone-Deck-Tracker\HSReplay-Api\HSReplay\,
and I find therepository for this project is https://github.com/HearthSim/HSReplay-API-Client.

I am using git clone https://github.com/HearthSim/HSReplay-API-Client.git,
and the default folder name is the same as repository name .

I need rename the folder by myself to match Hearthstone-Deck-Tracker\HSReplay-Api\HSReplay\
or I need specify the clone folder name when i am using git clone .

**Comment by azeier** [comment]
Just run `bootstrap.bat`.

**Comment by chucklu** [comment]
excellent,something like https://github.com/HearthSim/HearthMirror/issues/1

the difference between them is?
build event will fetch the latest code from github
the bat  can only run once ,then we need fetch the repository of the project manually

so,which one is better?

**Comment by azeier** [comment]
The pre-build script does that, bootstrap is just for setup.

**Comment by chucklu** [comment]
sorry, i can not understand ,what do you mean "just for setup"?

**Comment by azeier** [comment]
Well, it's a bootstrap script. You run it after cloning to have all the dependencies in place. 

The projects pre-build script keeps them all up to date.

**Comment by chucklu** [comment]
I wonder if can need fetch the latest code from the repository of the project automatically instead of  doing  that manually,since we have three repository to pull

**Comment by azeier** [comment]
It does.

**Comment by chucklu** [comment]
a suggestion for bootstrap.bat.
Could you add pause at the end of the file,the command may be not supported by the computer system.
the pause command can make sure  that the user can see the wrong information


nuget command is not supported on my compuuter 
and git clone will not work properly when I already have the project folder

**Comment by chucklu** [comment]
I have googled for a solution to add nuget to the Environment Path.
https://www.nuget.org/packages/NuGet.CommandLine
https://docs.nuget.org/consume/command-line-reference
https://docs.nuget.org/contribute/setting-up-the-nuget-development-environment

I am not sure,which one is correct,maybe you know where to find the correct document to config the nuget to the command line

**Comment by chucklu** [comment]
I have tried,the second url is the correct one

**Comment by chucklu** [comment]
finally , I config the nuget to the cmd successfully .
the bootstrap.bat works fine ,and I still think add pause at the end of this file would be better
