### ISSUE TITLE
remove the unnecessary function: Drawing Odds

### ISSUE THREAD

**Issue by narucy** [HearthSim/Hearthstone-Deck-Tracker#2804]
This overlay information is totally unnecessary. Everybody knows the odds drawing a particular card in 20 cards deck is 5% obviously. No need display it.

We can hide from Options menu, but software code clean-up is important I believe. Remove junk function for reduce maintenance cost.

**Comment by jleclanche** [comment]
There are no plans to remove it right now, a lot of people actually use it. Maybe later down the line if we see that change.
