### ISSUE TITLE
Duplicate matches

### ISSUE THREAD

**Issue by Thankcobra** [HearthSim/Hearthstone-Deck-Tracker#2807]
Hello guys, I have a problem with HDT (I have the latest version).
Why HDT continues duplicate match? 

![image](https://cloud.githubusercontent.com/assets/235410/18354539/a53b519a-75ee-11e6-9c50-79a073e32a37.png)

Edit:
it happens with deck I edited: https://i.gyazo.com/c3d2426cfebb8ad8f190b0147b211307.png
But I don't understand: I played only with 1.1, not with 1.0 too

**Comment by azeier** [comment]
Probably related to https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2791

**Comment by NomdeNet** [comment]
I think it is, I have both these issues.

**Comment by judge2020** [comment]
Closing issues that are similar to this one where the OP does not respond within 10+ months. If this is a still an issue you are welcome to re-open.
