### ISSUE TITLE
Hearthstone Deck Tracker has two different sets of stats and randomly loads one. 

### ISSUE THREAD

**Issue by marspad** [HearthSim/Hearthstone-Deck-Tracker#2808]
Been using HDT for about a month, and noticed that when I turn it on, it has stats for me playing 11 hours and all the info, then if I close it and open it again, it shows me playing for 18 hours and the stats for the 18 hours. I tried to uninstall HDT and reinstall but it still remembers all my games. I thought starting fresh might solve the issue.

**Comment by judge2020** [comment]
Closing issues that are similar to this one where the OP does not respond within 10+ months.
