### ISSUE TITLE
How can I take a screenshot?

### ISSUE THREAD

**Issue by dzunglv** [HearthSim/Hearthstone-Deck-Tracker#2809]
I normally take screenshots of best moment during the game. It will be nice if I can take screenshot of the game including the overlay.

I assigned the Hot key, and after I press it, I have to switch out of the game by pressing Tab, choose "Save" to save the image, then press OK. It is too complicated in comparison to Steam Screenshot. But the steam screenshot will not capture the overlay.

Is there a better way to make it?

**Comment by Shyran** [comment]
If you look under the Hotkey setup dropdown, where you specify what action to take, you'll want to select "Screenshot" instead of "Game Screenshot" and it will capture the overlay as well.

**Comment by dzunglv** [comment]
Thank you Shyran, but it is not the answer I am looking for. I know how to capture the overlay. The problem is after pressing the hotkey, I have to Switch Tab out of the game (in middle of the match) to press Save photo. I think it is too complicate. I need an Screen Auto-save feature

**Comment by Shyran** [comment]
Sorry, I understand what you are saying now (I have a multi-monitor setup, so I don't have to Alt-Tab out). I will see what I can do in my own branch about being able to select a default action and path for the screencaps so you don't have to tab out like that.

**Comment by dzunglv** [comment]
Thanks so much

**Comment by judge2020** [comment]
Closing issues that are similar to this one where the OP does not respond within 10+ months.
