### ISSUE TITLE
My games are not recorded

### ISSUE THREAD

**Issue by robo88** [HearthSim/Hearthstone-Deck-Tracker#2811]
I just upgraded my deck tracker and since then my games does not recording anymore. My deck is activate but my stats remains at 0 0 ( it's a new deck) and I can't watch the replays because,I think, those games didn't existed(from tracker perspective). Oh, and nothing happens when I'm starting the match (the number who indicates the cards from my hand stays at 0 until the end of the match.

**Comment by riQQ** [comment]
Please post your HDT log (see https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues).

**Comment by robo88** [comment]
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/465498/hdt_log.txt)
![untitled](https://cloud.githubusercontent.com/assets/22118811/18411875/1ef8e208-778a-11e6-99d0-c18a50a47a3f.png)

**Comment by robo88** [comment]
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/465500/hdt_log.txt)

**Comment by robo88** [comment]
I just solve it

**Comment by robo88** [comment]
enter in options press advanced then go in settings   and press set hearthstone path( then u have to select your hearthstone location then restart deck tracker
sry for bad gram

**Comment by Savathar** [comment]
OMG! THANKS! solved my issue!

**Comment by jleclanche** [comment]
Good to see it's solved!
