### ISSUE TITLE
DT not tracking my game and just sitting there

### ISSUE THREAD

**Issue by Savathar** [HearthSim/Hearthstone-Deck-Tracker#2812]
Went through all the options. Have upgraded to latest version. It's been over 2 months that it has stopped tracking my game. Just sits there passively.

**Comment by jleclanche** [comment]
Same issue as https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2811 ?

**Comment by Savathar** [comment]
OMG! THANKS! solved my issue!

**Comment by jleclanche** [comment]
Great!
