### ISSUE TITLE
Tracker not recording all games

### ISSUE THREAD

**Issue by Ssyssse** [HearthSim/Hearthstone-Deck-Tracker#2816]
**EDIT: Solved, filter on**

**Comment by jleclanche** [comment]
Can you take a look at #2811 and see if the same fix works for you?

**Comment by Ssyssse** [comment]
Thanks, I'll try that and report back tomorrow. Also just noticed that it claims that I did not have the coin in any of the games shown which hardly can be correct.

**Comment by Ssyssse** [comment]
Thanks for the fast reply! 

It's get late tho, and there was a filter on (coin was set to no). Thread can be removed.

**Comment by jleclanche** [comment]
Great!
