### ISSUE TITLE
Select deck list for opponent

### ISSUE THREAD

**Issue by TheKushStyle** [HearthSim/Hearthstone-Deck-Tracker#2817]
Hello,
I would like to request a feature.
Would it be possible to add a decktracker for the opponent?
I know you can't get the data of the enemy deck ,but if you can click a deck (Like standard aggro shaman)
And the cards will grey-out (like your own list).
This will come very handy.
Thank you.

**Comment by azeier** [comment]
This is not something we currently want to support. 

See https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues?utf8=%E2%9C%93&q=is%3Aissue%20prediction
