### ISSUE TITLE
About Brawl and the Beta

### ISSUE THREAD

**Issue by TemporalOnline** [HearthSim/Hearthstone-Deck-Tracker#2821]
I just noticed hearthsim posted statistics about the last week's brawl using the HDT beta. But I NEVER received the notification at the end of the brawl (the share link and etc). Neither they appeared at the end of the brawl inside the "latest replays" menu, so I thought you weren't tracking this brawl. Do I need to link accounts to have that? I played 112 games (I was leveling up my warrior and warlock) and looking at the replays from select from stats just about a dozen were uploaded but none can be replayed (again, it has like a dozen from random times).

Everything else seems to be working. Am I doing something wrong?

**Comment by azeier** [comment]
Notifications only show up for modes which have local stats recording enabled. (`options > tracker > stats`)

**Comment by jleclanche** [comment]
@TemporalOnline You don't need to claim your account. The only way they don't get uploaded, is if you have uploading explicitly disabled for that game mode (in the replay section of the stats).
