### ISSUE TITLE
Crashing after roughly 2 minutes.

### ISSUE THREAD

**Issue by Vapour-Trail** [HearthSim/Hearthstone-Deck-Tracker#2822]
Hi.

Deck tracker keeps crashing after roughly two minutes of use, giving me [this generic error message](https://1drv.ms/i/s!AhOz3qba9jh0h0PrXS_0-Zv13mQR) I'm sure we've all seen before. I've tried messing around with compatability settings, and I have checked my .NET version (4.6.1), but to no avail. Here are a couple of computer specs that might be relevant, in case it's a driver problem, or anything.

OS: Windows 10 Home (build 10586.589)
GPU: AMD RX 480
GPU driver: 16.9.1

Thanks for your time.

**Comment by riQQ** [comment]
See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues.

**Comment by Vapour-Trail** [comment]
Thanks for the help.

Here's one of the event viewer logs from one of the crashes.

Faulting application name: HearthstoneDeckTracker.exe, version: 1.0.5.29, time stamp: 0x57c54e0f
Faulting module name: ltc_game32-116096.dll, version: 1.0.0.1, time stamp: 0x57cf4e9b
Exception code: 0xc00000fd
Fault offset: 0x00002e70
Faulting process ID: 0xd0c
Faulting application start time: 0x01d20f4b93153790
Faulting application path: C:\Users\Stuart\AppData\Local\HearthstoneDeckTracker\app-1.0.5.29\HearthstoneDeckTracker.exe
Faulting module path: C:\PROGRA~2\RAPTRI~1\PlaysTV\ltc_game32-116096.dll
Report ID: c969c977-ca84-4925-b87e-f7fbd828cb92
Faulting package full name: 
Faulting package-relative application ID: 

Looks like it's something to do with Raptr,
 which I think is part of my AMD Gaming Evolved installation, but I'm not sure how I can go about trying to fix it. I have attached a Deck Tracker log from the same event, but it doesn't look that weird to me.

[hdt_log_1473942758.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/475800/hdt_log_1473942758.txt)

Thanks for all your help.

**Comment by riQQ** [comment]
As this is a Raptr issue, you can try disabling it or ask their support.

**Comment by judge2020** [comment]
Closing issues that are similar to this one where the OP does not respond within 10+ months.
