### ISSUE TITLE
Call pet error

### ISSUE THREAD

**Issue by psytag** [HearthSim/Hearthstone-Deck-Tracker#2823]
Just started using this program and i payed a game against a hunter and the program didn't consider Call pet as a possible secret when he played one.

PS the program is great!

**Comment by jleclanche** [comment]
Call Pet isn't a secret. Do you mean Cat Trick?

**Comment by psytag** [comment]
Yes sorry for the mix up.

**Comment by azeier** [comment]
Duplicate #2823 then, will be fixed this week.
