### ISSUE TITLE
stats problem

### ISSUE THREAD

**Issue by cachirro** [HearthSim/Hearthstone-Deck-Tracker#2825]
i've noticed this happening every time now.

the main window doesn't updates the stats, for this new deck for example, it shows has if i've never used it, while in game i see the correct score 4-1.

if i close the program and open then it shows 4-1 in main window, some update stats code not running properly.

**Comment by cachirro** [comment]
any comments on this please?

**Comment by judge2020** [comment]
Closing issues that are similar to this one where the OP does not respond within 10+ months.
