### ISSUE TITLE
Secret Tracker not Updated for Karazhan or Recent Arena Hunter Removals

### ISSUE THREAD

**Issue by markcd** [HearthSim/Hearthstone-Deck-Tracker#2830]
Cat trick has not been added to the secret tracker, nor has snipe or dart trap been removed (though they should stay, but grayed out for non-randomly generated cards).

**Comment by riQQ** [comment]
Cat trick is already fixed (see #2776).

**Comment by judge2020** [comment]
Closing issues that are similar to this one where the OP does not respond within 10+ months.
