### ISSUE TITLE
Update checker string display bug

### ISSUE THREAD

**Issue by NightKev** [HearthSim/Hearthstone-Deck-Tracker#2832]
The first start after the 1.1.0 update, the main window looked like this:
![hdt updater bug](https://cloud.githubusercontent.com/assets/849285/18736629/9f8e018a-803d-11e6-9e56-3f45681b053f.png)
It didn't persist after a restart though.

**Comment by azeier** [comment]
This was fixed with the 1.1.0.2 update.
