### ISSUE TITLE
Edit arena stats

### ISSUE THREAD

**Issue by felixeng** [HearthSim/Hearthstone-Deck-Tracker#2834]
If you have already started an arena run and then import the deck to HSdecktracker it does not show the wins you have already gotten. Make it so that you can right click on an arena deck and edit the stats (wins/losses). 

:)

**Comment by Scarborian** [comment]
If you click Stats, and under "Arena Runs", click "Runs & matches", the option to add games is there for you.

**Comment by judge2020** [comment]
Closing issues that are similar to this one where the OP does not respond within 10+ months.
