### ISSUE TITLE
i want to help translate

### ISSUE THREAD

**Issue by cachirro** [HearthSim/Hearthstone-Deck-Tracker#2836]
as in title, i want to help translate but to PT-PT, which sadly isn't on the languages list at all.

do you use crowdin?

**Comment by jleclanche** [comment]
Hey there! 

Take a look at the following repository:

https://github.com/HearthSim/HDT-Localization

If you file a pull request with `String.pt-PT.resx`, that will do the trick.

**Comment by cachirro** [comment]
i never used github, i'm not familiar with the platform, i am sorry, i just use it to report issues,

i do use crowdin in some other projects, and it's a great translation platform.

so, if you can guide me how to help here, i appreciate it.

**Comment by jleclanche** [comment]
ResX Resource Manager is what other translators are using:

https://resxresourcemanager.codeplex.com/

You can download the repository directly (top right, green button), and take example from the other Strings.*.resx files. Then if you don't use github, you can attach a `Strings.pt-PT.resx` file to this issue, and we'll take care of the rest for you.

**Comment by cachirro** [comment]
Thanks man, will give it a try.

**Comment by jleclanche** [comment]
Thanks for your interest! Let me know if you need any more help.

**Comment by cachirro** [comment]
i'm looking at neutral as the base, and german as a help guide, but after done i need to test the file on the program to make needed adjustments.

my question is, i see strings with _, should this be kept or ignored?
like _new for example.

**Comment by azeier** [comment]
Try to keep the underscores, yes. Those are used for Alt+{Key} commands (they are not visible).

**Comment by cachirro** [comment]
is there a way i can export my WIP file to HDT so i can see the results and adjust where needed?

**Comment by azeier** [comment]
Not very easily right now, no. You would have to build HDT locally and modify the pre-build script to not pull the changed from the repo.

**Comment by cachirro** [comment]
ok, so i'll do as much as i can for now, give it to you, and then wait for you to put it in the program, and then check for errors or needed adjustments.

**Comment by cachirro** [comment]
i'm changing some letters for the alt+ function, so i then need to see in the program to see if i repeated some by mistake on a certain screen.

**Comment by cachirro** [comment]
oops, wrong button, sorry i closed this :)
here is the file with what i've done so far, already more than DE, so not bad. I will do more when i see this in app so i have a better idea.

[Strings.pt-PT.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/490026/Strings.pt-PT.zip)

**Comment by azeier** [comment]
Here is a release with that state of the translation in it: https://github.com/azeier/HDT-Test/releases/tag/v1.1.0.3

**Comment by cachirro** [comment]
thanks Azeier, will test it now and add more stuff.

**Comment by cachirro** [comment]
here is today's work:
[Strings.pt-PT.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/491780/Strings.pt-PT.zip)

**Comment by cachirro** [comment]
hey guys, did a little more work on it, here it is:
[Strings.pt-PT.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/491964/Strings.pt-PT.zip)

**Comment by cachirro** [comment]
if you can compile a new release, i would appreciate it.

**Comment by cachirro** [comment]
or if it is possible (i have no idea if it is) point me to instructions to compile it so i can test the files i created.

**Comment by azeier** [comment]
Are you maybe starting the wrong installation?

Here's a new build: https://github.com/azeier/HDT-Test/releases/tag/v1.1.0.3.p1

What stops you from just translating everything and then making all necessary changes at once?

**Comment by cachirro** [comment]
nothing, i just like to see what i'm doing, sorry for my method. i will not bother you again to compile.

**Comment by jleclanche** [comment]
@cachirro No worries. Your help is appreciated.

**Comment by cachirro** [comment]
i go the same error as the other time, i install that build, i select portuguese, i use it with no problems, go to bed, next day program starts with red warning about config.xml being corrupted and backup was restored, and i no longer have portuguese language to chose from.

**Comment by cachirro** [comment]
here is latest update:
[Strings.pt-PT.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/505113/Strings.pt-PT.zip)

please note:
- some how config.xml gets corrupt when i use portuguese (explanation on previous post)
- this string has a typo: MainWindow_Menu_Export_Clpiboard
- several strings are being truncated in options (explanation on previous post)

**Comment by cachirro** [comment]
any comment on my notes?

**Comment by azeier** [comment]
Yeah, sorry for the delay. I'll try to get pack to you later today.

**Comment by cachirro** [comment]
Thanks @azeier

**Comment by cachirro** [comment]
Thanks @azeier 
also, why do you use repeated strings, for example:
Options_Overlay_Opponent_CheckBox_SameScaling
Options_Overlay_Player_CheckBox_SameScaling

both use same text (there are more examples of this), why not use just one entry?
if you need "samescaling" string, read it from X place

this would avoid the possibility of the 2 strings having 2 different texts, when it should be the same

**Comment by azeier** [comment]
- It most likely crashes because "start with windows" launches an HDT version that does not understand the config setting being pt-PT - there is no way around that atm
- The custom build you downloaded here most likely updated, removing the pt-PT option again
- Typo in `MainWindow_Menu_Export_Clpiboard` doesn't really matter, it's not user facing 
- Not sure about truncated string, I'll have  a look tomorrow.
- There's separate strings for `SameScaling` (and in a bunch of other places) for consistency sake. Every UI element get's it's own. There is always the chance the same en-US string is translated differently in some languages.
- I'll get you a build with the updated strings tomorrow.

**Comment by azeier** [comment]
Added pt-PT support for the next release. 

Here is a release with the updated strings: https://github.com/azeier/HDT-Test/releases/tag/v1.1.1
The config will reset if you start the normal HDT release (as of 1.1.1.0), as mentioned above. 

For the cut off stings: That is a problem with the UI that might take some time to solve globally and is one of the reasons I have not bothered with the german translation too much. Kind of a workaround would be to reword some phrases in a shorter fashion, but I'm not sure that's worth it. It will get fixed eventually.

**Comment by riQQ** [comment]
This was added. Main thread at #2797.
