### ISSUE TITLE
HDT isn't showing any of my recent matches.

### ISSUE THREAD

**Issue by FishermanHS** [HearthSim/Hearthstone-Deck-Tracker#2839]
My stats are showing next to the decks: https://gyazo.com/c00ccd189da13dcc42da7c1ef33bcc57

But no matches are showing up in my recent matches: https://gyazo.com/e822d9155cd9b9d5aee4e8e1bcaf9cbb

And it's not showing any stats on this screen either: https://gyazo.com/cd98569fa4157925ed39c592a84bceb8

Is there a way to fix this?

**Comment by azeier** [comment]
You have the filter for the opponent name set on the bottom left.

**Comment by FishermanHS** [comment]
Oh wow I can't believe I missed that. Derp. Thanks man!
