### ISSUE TITLE
HDT Crashing v 1.0.5

### ISSUE THREAD

**Issue by AnonymusA** [HearthSim/Hearthstone-Deck-Tracker#2840]
Greetings! :)

I didn't do anything special today before I started the HDT, yesterday it was working perfectly. If somebody can help or has an idea please send it.

[Crash report 2492016-951.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/491022/Crash.report.2492016-951.txt)

**Comment by azeier** [comment]
Try downloading the latest version (1.1.0): https://hsdecktracker.net/download

**Comment by AnonymusA** [comment]
It works, thank you!

**Comment by azeier** [comment]
Great! :)
