### ISSUE TITLE
Enemy tracking

### ISSUE THREAD

**Issue by panos754** [HearthSim/Hearthstone-Deck-Tracker#2843]
Could u add a feature in replay mode where u can make a Note/Reminder of that game and player. Then the note will appear on your next encounter with the same opponent.
For example, i start a new game and match up to a cntrl warrior named KLOL and he has Deathwing. I have made a note " uses Deathwing and baron" from our previous encounters. When the game is starting after mulligan that small note will appear reminding me that i have played against him 3 times and the msg " uses Deathwing and baron" on the HDT

ty in advance

**Comment by charberg** [comment]
An issue I can see with this is since opponent's visible tag doesn't unique, this could cause notes to appear for a different player, under the same name.

**Comment by judge2020** [comment]
in-hdt Replay is depreciated.

For notes a good issue is #416
