### ISSUE TITLE
Two copies of the same deck / confused after editing on 2 computers

### ISSUE THREAD

**Issue by AfterShockFF** [HearthSim/Hearthstone-Deck-Tracker#2844]
For some reason, hearthstone deck tracker has two copies of the same deck saved for me, called the same thing. I think this is because I edited the deck on my laptop rather than my main computer, and either it didn't pick up the change (so i edited again on my computer), or it saved it as a new deck(?)

Now every time I play the game, even if I select the correct deck as 'use this deck', the game starts, the decklist reverts to the 'wrong' deck listing. Then halfway through the game, it says 'Card not found', then the decklist changes again!

I have tried the HearthStats 'sync' option, but that doesnt seem to solve it.

**Comment by hsPhoebus** [comment]
I'm having the same issue. Whenever I edit a deck and save as a new version (say from 1.3 to 1.4), it copies the deck and creates this confusion during games. I'm editing the deck on the same computer, so it's not necessarily an issue with using two computers. 

The only workaround I've found is to create brand new decks with new names every time I want to edit a deck.

**Comment by judge2020** [comment]
Merging will be handled with #3235

**Comment by judge2020** [comment]
duplicate of #3235
