### ISSUE TITLE
Export to Hearthstone option doesn't work properly when multiple screens are present.

### ISSUE THREAD

**Issue by aaronhsyong2** [HearthSim/Hearthstone-Deck-Tracker#2845]
Only just recently discovered this issue. Double checked by restarting the client and computer, the problem still persists. Not a major, game breaking issue at the moment, but it is a minor disturbance having to turn the display off.

**Comment by riQQ** [comment]
Works for me with Hearthstone in windowed mode.

**Comment by aaronhsyong2** [comment]
Consistently gets 17 cards in the deck. Both windowed and fullscreen.

**Comment by azeier** [comment]
That sounds like it could be the first point here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#exporting

**Comment by aaronhsyong2** [comment]
That sounds like exactly what it was. The fix worked too! Thanks!

**Comment by azeier** [comment]
Great!
