### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by lanfeustdetroy** [HearthSim/Hearthstone-Deck-Tracker#2846]
Hello,
I would like to start by saying that I do not know speak English very well and, suddenly, I use google translation. Sorry if you do not understand everything.

So here I have checked the activation of the overlay at the launch of the computer, at the beginning, everything worked. But one day, he has not launched (There was the icon "loading" but it would not load.). I clicked on the cross (by alt + tab) and I thought I could run it, but no! He told me that the overlay is already launched! And since then, I never managed to start (I restarted my PC 20'000 times !!!) ...
I really would appreciate if you could help me!

**Comment by riQQ** [comment]
https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#not-starting

**Comment by lanfeustdetroy** [comment]
"Is there a log entry in the windows event viewer (Windows start menu > control panel > management tool > event viewer > windows log > application)" No, and now ? What must I do ?

**Comment by riQQ** [comment]
https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#hdt-log-files

**Comment by lanfeustdetroy** [comment]
It's done ! TANKS !

**Comment by riQQ** [comment]
What was the problem?

**Comment by lanfeustdetroy** [comment]
The launch with windows was the problem. I had need to « uninstal » the launche with windows !

 

De : riQQ [mailto:notifications@github.com] 
Envoyé : mercredi, 28 septembre 2016 19:05
À : HearthSim/Hearthstone-Deck-Tracker <Hearthstone-Deck-Tracker@noreply.github.com>
Cc : lanfeustdetroy <joachim@favre-quattropani.ch>; State change <state_change@noreply.github.com>
Objet : Re: [HearthSim/Hearthstone-Deck-Tracker] Crashes (#2846)

 

What was the problem?
