### ISSUE TITLE
Cant import decks using play menu, overlay not visible in match.

### ISSUE THREAD

**Issue by Zanz2** [HearthSim/Hearthstone-Deck-Tracker#2847]
I have no idea what happened, HDT was working properly, with start on windows enabled, then one day it crashed, and i had to launch it manually from then on, i tried reinstalling it but the same thing happens and i cant even import my decks.

**Comment by riQQ** [comment]
See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#not-working.
