### ISSUE TITLE
HDT showing overlay on all Unity games

### ISSUE THREAD

**Issue by kendoka15** [HearthSim/Hearthstone-Deck-Tracker#2848]
Be it Kerbal Space Program or Rimworld, it shows the overlay on those too and I don't see an option to lock it to the Hearthstone exe other than to specify the path, which doesn't fix it.

**Comment by riQQ** [comment]
1. Go to the options
2. Enable `Advanced Options`
3. Go to `Tracker > Settings`
4. Disable `Advanced window search`
