### ISSUE TITLE
All plugins disabled after HDT update

### ISSUE THREAD

**Issue by sebastientromp** [HearthSim/Hearthstone-Deck-Tracker#2849]
Hey all,

It looks like all my plugins become disabled after an HDT update. Does that ring a bell? Could it be some misconfiguration from my side?

I had a look in the logs, and couldn't find anything relevant.

**Comment by riQQ** [comment]
Happened to me, too.

**Comment by Cicor** [comment]
https://gyazo.com/31aefdbac04b109697ddf9de2fb49d6f

When I try to enable my plugins.

What can we do?

**Comment by riQQ** [comment]
@Cicor separate issue and an issue of the plugin itself. Most likely it's out of date.

**Comment by riQQ** [comment]
Happened again with 1.1.1
