### ISSUE TITLE
Two issues: updating, new install.

### ISSUE THREAD

**Issue by 4lh** [HearthSim/Hearthstone-Deck-Tracker#2851]
Hi,

I have two issues to report.

**First issue:**

I was using Hearthstone Deck Tracker since a long time, but I couldn't update it. I got this error mesage when I tried : "There was an error installing the latest update. Press any key to open the website for manual download." I had same issue a few months ago and I was forced to reinstall Tracker each time instead of updating it.

**Second issue:**

I tried to install Hearthstone Deck Tracker on my new system, and got this error message:

"There was a problem updating the log.config.
New log.config settings are required for HDT to function correctly.
Try starting HDT as administrator."

**Comment by azeier** [comment]
1) The new installer has a better updating system - you can download it here: https://hsdecktracker.net/download

2) See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Setting-up-the-log.config
