### ISSUE TITLE
Experiencing some crashing on both Hearthstone and HDT's ends when using HDT

### ISSUE THREAD

**Issue by xtreemmasheen3k2** [HearthSim/Hearthstone-Deck-Tracker#2852]
Never had this issue until just today. Was doing some dailies on the Asia server recently. Was crafting a new deck, and Hearthstone crashed multiple times in the process. Kept crashing when in game as well. Then HDT crashed. I ran Hearthstone without HDT for a few games and I didn't experience any crashing. Soon after I turned HDT back on, Hearthstone crashed again. I'm on the latest Windows 7 update, which was updated on my computer as of 5:00AM today, September 26th 2016 on Western United States time.

I'll try the normal restarting Computer method and stuff and see if that does anything and will update.

**Comment by riQQ** [comment]
https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by Don-Cooper** [comment]
I'm having a similar issue to this one, but far more random and for no apparent reason. The deck tracker seems to crash more often than the game, and will do it particularly when I have the game minimised, but mostly very randomly. On one occasion Hearthestone crashed. The tracker will sometimes crash during Hearthestone.
Second most recent:
[hdt_log_1475072376.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/498270/hdt_log_1475072376.txt)

Just now:
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/498271/hdt_log.txt)

**Comment by azeier** [comment]
Do you get a crash report window in this case or does HDT just say "Stopped responding" (whatever the exact message is windows shows you :)).
