### ISSUE TITLE
Can't create a deck

### ISSUE THREAD

**Issue by panok194** [HearthSim/Hearthstone-Deck-Tracker#2853]
I don't know English, I write through the translator. Sorry!
In the latest update came the ability to choose the interface language, Russian and Chinese. So, when you select one of these languages is not possible to create a new deck. If you include the English such an opportunity appears again! Tried on two different computers, the result is the same.
Thank you!

**Comment by azeier** [comment]
Thanks for the report. This will be fixed with the next update.
