### ISSUE TITLE
Question: where are datas saved?

### ISSUE THREAD

**Issue by 4lh** [HearthSim/Hearthstone-Deck-Tracker#2854]
Hi,

I reinstalled my system and I would like to know where Hearthstone Deck Tracker datas are saved to import them from my previous hard disk. Datas such as: configuration, decks, replays, stats.

Thanks.

(I separated my threads because I would like an answer to this one.)

**Comment by andburn** [comment]
By default data is stored in `C:\Users\<your_username>\AppData\Roaming\HearthstoneDeckTracker`.
You can open this directory quickly by pressing `Windows Key + R`  then type `%APPDATA%\HearthstoneDeckTracker` followed by the *OK* button.

**Comment by 4lh** [comment]
Hi,

I found this directory already, but all files are exactly the same than they were on my previous system (same number, same size). So, they must not contain datas about my decks, stats, replays, and my configuration.

**Comment by azeier** [comment]
Are you on the non-installer build (i.e. the one extracted from the zip)? If so, did you change the data storage location? See if `options (advanced) > tracker > settings > save data in AppData` is disabled.

**Comment by 4lh** [comment]
I was on the non-installer build. That option wasn't enabled, I clicked _Open appdata folder_ and found the directory. Thanks, my problem is solved.
