### ISSUE TITLE
Remove ALL stats??

### ISSUE THREAD

**Issue by OriginalOrion** [HearthSim/Hearthstone-Deck-Tracker#2855]
I was deleting all my decks on the tracker to start over with my stats, but i didn't delete the stats with some of the decks when i deleted the deck. Now i have no decks but still some stats, how do i completely get rid of all stats. I have deleted all the files and re installed and they are still there.

**Comment by azeier** [comment]
If you go to `stats > constructed > matches` you can use `ctrl-A` to select everything and then click `delete` at the bottom.

**Comment by OriginalOrion** [comment]
Thanks alot!
