### ISSUE TITLE
Hearthstone crashing often

### ISSUE THREAD

**Issue by Veggo1665** [HearthSim/Hearthstone-Deck-Tracker#2858]
Since I allowed it to save replays on HSreplay.net, HDT has been causing hearthstone to crash every few minutes. Often it crashes at the start of a game. Any help would be really appreciated.

[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/499725/hdt_log.txt)

**Comment by riQQ** [comment]
Anything in the windows logs (https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#windows-log-files)?

**Comment by Veggo1665** [comment]
This was listed as an application error.

Faulting application name: Hearthstone.exe, version: 1.0.0.14406, time stamp: 0x579375ff
Faulting module name: ntdll.dll, version: 10.0.14393.103, time stamp: 0x57b7e09e
Exception code: 0xc0000374
Fault offset: 0x000d9841
Faulting process ID: 0x22dc
Faulting application start time: 0x01d21a0224976018
Faulting application path: C:\Program Files (x86)\Hearthstone\Hearthstone.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report ID: 0e0fbbf8-a3ff-4d27-a35c-7311d093cc39
Faulting package full name: 
Faulting package-relative application ID: 

Thanks

**Comment by riQQ** [comment]
Is there any error with the source `.NET Runtime` in the logs?

**Comment by Veggo1665** [comment]
No. Not that I could find.

**Comment by riQQ** [comment]
Error code 0xC0000374 is STATUS_HEAP_CORRUPTION - A heap has been corrupted. @azeier does this have something to do with HearthMirror?

**Comment by azeier** [comment]
@riQQ What makes you come to that conclusion (idea)?

**Comment by riQQ** [comment]
It's only happening in combination with HDT, so it's either the overlay or HearthMirror imo.

@Veggo1665 does this still occur, if you disable the overlay?

**Comment by azeier** [comment]
HearthMirror seems the least likely to me, "interaction" with Hearthstone is completely passive.

**Comment by Veggo1665** [comment]
Sorry for late reply, I was away over the weekend. Yes, if I hide the overlay it stops the crashes!
