### ISSUE TITLE
Cards won't show up when you create/edit deck under Chinese UI

### ISSUE THREAD

**Issue by AlanStark909** [HearthSim/Hearthstone-Deck-Tracker#2860]
Hi, I am a chinese user. big fan of HDT.
Chinese UI is a fantastic news for me, but I find that I can't create or edit decks under Chinese UI.
You can check my screenshots below.
![qq 20160929221506](https://cloud.githubusercontent.com/assets/19162584/18957664/842842e2-8692-11e6-9a18-7537a2ddb583.png)
![qq 20160929221533](https://cloud.githubusercontent.com/assets/19162584/18957687/98327f14-8692-11e6-969e-021dd44c3fe9.png)
Hope it's a easy to fix issue.

THX guys.

**Comment by AlanStark909** [comment]
Ah, sorry. I say this bug has been noticed. I Ctrl+F ‘Chinese’ before I rise this issue.
Glad you have already working on it.

**Comment by riQQ** [comment]
Are you talking about #2853?
