### ISSUE TITLE
Maelstrom Portal Text

### ISSUE THREAD

**Issue by Spedwards** [HearthSim/Hearthstone-Deck-Tracker#2861]
When you hover over Maelstrom Portal to get the stats, the card text contains underscores instead of spaces.

![Image][1]

  [1]: https://i.imgur.com/K1Fyw2p.png

**Comment by jleclanche** [comment]
@azeier Do you get these descriptions yourself, from hearthstonejson or from hs-data? We fix it in hsjson:
https://github.com/HearthSim/HearthstoneJSON/blob/master/generate.py#L90

**Comment by azeier** [comment]
HearthDb uses hsdata.
