### ISSUE TITLE
Coin: No vs. No

### ISSUE THREAD

**Issue by sdlorimor** [HearthSim/Hearthstone-Deck-Tracker#2862]
When looking at stats for a deck, clicking on the drop-down menu for "coin" reveals two options: No and No.  

The first "No" should read "Yes", as when I use this option to search through the list of matches all of the options list the Coin as "Yes".

Screenshots available upon request.

**Comment by azeier** [comment]
Heh, I like this one.

Thanks for the report. Will be fixed with the next update.

**Comment by sdlorimor** [comment]
Thanks for the quick attention and fix.
