### ISSUE TITLE
Sync between two PCs (issue synce Hearthstats servers were down)

### ISSUE THREAD

**Issue by BorjaSR97** [HearthSim/Hearthstone-Deck-Tracker#2864]
Hey, HDT synched my stats between computers but since the Hearthstats servers were down i have problems to have my stats correctly in the two PC's. How can i solve this? I press the button "force sync full" but there was any change (and in the Hearthstats page i have like 20 matches more).

**Comment by judge2020** [comment]
HearthStats is no longer supported, a HSReplay solution is planned.
