### ISSUE TITLE
Replays no longer include deck lists

### ISSUE THREAD

**Issue by foxor** [HearthSim/Hearthstone-Deck-Tracker#2865]
Replays are useful for analyzing misplays, and I appreciate the new and improved replay viewer.

However, replays are also useful for seeing what cards other people are playing, and how it influences their plays earlier in the game.  When a game goes to fatigue, you used to be able to get a read on almost every card in their deck, but now that information is much more cumbersome to acquire.

Perhaps you could have a link next to the "download xml" button?

**Comment by azeier** [comment]
We temporarily disabled deck lists on HSReplay.net for performance reasons. They should come back very soon.

**Comment by foxor** [comment]
Oh!  Thanks!
