### ISSUE TITLE
Automatically "not-using" deck when a not used card occurs.

### ISSUE THREAD

**Issue by OzanKurt** [HearthSim/Hearthstone-Deck-Tracker#2867]
I want to keep using my active deck, please fix this issue since v1.0.5.

**Comment by azeier** [comment]
Do you have auto deck importing enabled? (`options (advanced) > tracker > importing`)

With that, this should not be an issue.

The alternative is turning off auto importing at the bottom of the decks list.

**Comment by OzanKurt** [comment]
No, I don't use auto import.

The thing is I make changes on my decks casually, lately the DT is detecting a card which is not in the deck and automatically switching to "no deck mode".

Best regards,
Oz

**Comment by OzanKurt** [comment]
Okay thanks.
