### ISSUE TITLE
log in battle.net to claim replays NOT support china zone

### ISSUE THREAD

**Issue by sufre** [HearthSim/Hearthstone-Deck-Tracker#2869]
the default url is 
https://us.battle.net/login/zh/?ref=https://us.battle.net/account/management/&app=bam&cr=true

plz add support to switch battlenet zone

**Comment by jleclanche** [comment]
Can you give more details on what's broken/where?

**Comment by jleclanche** [comment]
Issue moved to [HearthSim/HSReplay.net #82](https://github.com/HearthSim/HSReplay.net/issues/82) via [**ZenHub**](https://www.zenhub.com/)

**Comment by sufre** [comment]
when i finished a game, i upload the replay to hsreplay server by click the popup right-bottom,
then opetions ->replays ->claim accout ->log in with battle.net

i upload my replay with my game in china zone, but the "log in with battle.net" page leed me to the US zone log in system, i cant log in with my china zone account now

**Comment by jleclanche** [comment]
@sufre Could you try logging in using this version of the website?

https://dev.hsreplay.net/

I switched the default zone to china there. Let me know if it works, and let me know your Battletag as well. If it does work, I'll try to figure something out.
