### ISSUE TITLE
The Localization for Hearthstone Deck Tracker cause a bug when edit deck

### ISSUE THREAD

**Issue by dyx00001** [HearthSim/Hearthstone-Deck-Tracker#2870]
when I chose the language with the chinese I can't edit deck beacause all cards can't view in interface ！
@azeier

**Comment by azeier** [comment]
This will be fixed with the next update.

See https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2853

**Comment by dyx00001** [comment]
thanks！

2016-10-03 16:21 GMT+08:00, Alexander Zeier <notifications@github.com>:
> This will be fixed with the next update.
>
> See https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2853
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2870#issuecomment-251051041


-- 
半之光羽敬上
