### ISSUE TITLE
Opponent tracker not tracking on Mac

### ISSUE THREAD

**Issue by strayydogg** [HearthSim/Hearthstone-Deck-Tracker#2872]
The opponent tracker on the left side is not displaying the cards played. The percent chance to draw and cards in hand etc are working.

**Comment by azeier** [comment]
This is the window deck tracker. You wanna post over at https://github.com/HearthSim/HSTracker.

**Comment by azeier** [comment]
Issue moved to [HearthSim/HSTracker #629](https://github.com/HearthSim/HSTracker/issues/629) via [**ZenHub**](https://www.zenhub.com/)
