### ISSUE TITLE
After latest update, updater crashes with the following output

### ISSUE THREAD

**Issue by NITRO86sp** [HearthSim/Hearthstone-Deck-Tracker#2873]
```
Creating temp file directory
Downloading latest version... 26472/26472KB (100%)
Extracting files...
System.AggregateException: One or more errors occurred. ---> System.Exception: E
rror extracting the downloaded file. ---> System.IO.IOException: The file 'HDTUp
date_new.exe' already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Bo
olean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at HDTUpdate.Program.CopyFiles(String dir, String newPath)
   at HDTUpdate.Program.<Update>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at HDTUpdate.Program.<Update>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at HDTUpdate.Program.Main(String[] args)
---> (Inner Exception #0) System.Exception: Error extracting the downloaded file
. ---> System.IO.IOException: The file 'HDTUpdate_new.exe' already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Bo
olean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at HDTUpdate.Program.CopyFiles(String dir, String newPath)
   at HDTUpdate.Program.<Update>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at HDTUpdate.Program.<Update>d__2.MoveNext()<---

There was an error installing the latest update. Press any key to open the websi
te for manual download.
```

**Comment by azeier** [comment]
I'd recommend switching to the new installer/updater: https://hsdecktracker.net/download

The old one has quite a few issues and will probably not see too much maintenance.

That said, the workaround there is probably to delete the `HDTUp
date_new.exe` file.

**Comment by NITRO86sp** [comment]
Alright. But it installed on the local app folder and everything looks restored, where are the settings/decks/config files located for future backups?

**Comment by Binori** [comment]
Exactly, new version installer doesn't respect old HDT settings about custom Data folder so you lose all settings, decks etc. and have to copy them manually. This is very annoying.

**Comment by azeier** [comment]
As @Binori said, yes. That functionality does no longer exist in the new installer because of the way the updating works. 

If you *need* data at a different location you will have to stick with the zip version of HDT. Otherwise, moving everything to `%AppData%/HearthstoneDeckTracker` will restore all decks/stats.

**Comment by kimfranken** [comment]
I had the same crash on mine, so I downloaded and installed "HDT-Installer.exe" as recommended obove. However this just starts HDT (1.1.1)? I don't see any visual representation that it is actually installing anything. When I then quit HDT and restart it through my start menu the previous version gets launched (1.1.0). How do I permanently install the newest version?

**Comment by azeier** [comment]
The installer should create a new shortcut on your desktop / in your start menu.

**Comment by kimfranken** [comment]
Well it didn't do that. AS i said above, there was no visual representation that an installation was going it, it just launched HDT after some time. Is this intended? Where is the new version installed to?

**Comment by azeier** [comment]
That's the expected behavior, yes

You could try uninstalling (via windows `Programs and Features`) and reinstalling. 

HDT is installed to `%LocalAppData%/HearthstoneDeckTracker`. 

If you want to manually create a shortcut, you need to set the target to `C:\Users\{USER}\AppData\Local\HearthstoneDeckTracker\Update.exe --processStart "HearthstoneDeckTracker.exe"` and "Start in" to `C:\Users\{USER}\AppData\Local\HearthstoneDeckTracker\app-1.1.1`.

"Start in" might be an issue if the shortcut does not auto regenerate on updates - which it should.

**Comment by eshlin** [comment]
Thanks for the helpful above details and context; in a similar situation as above where I have the data in a different directory, but did want to mention that the workaround of deleting the `HDTUpdate_new.exe` file as suggested above did allow me to avoid the error above/finish the update.
