### ISSUE TITLE
Decks are not activated automatically anymore

### ISSUE THREAD

**Issue by Ervith92** [HearthSim/Hearthstone-Deck-Tracker#2874]
Hello, some time ago after update (which allowed you to delete folder where hdt was unpacked, didn't remember which version it was) when i'm starting a game, decks are not activated automatically. It shows active deck which i played before and shows error 'cards not found in deck' (example: if i start game with dragon warrior it shows mid hunter which is active in hdt). If i set an active deck i want to play manually, it works good. Also when i reinstalled hdt and deleted all my settings it worked normally but when i copied my settings back it doesnt work again. Someone know whats wrong with it? Or maybe there is option im missing?

**Comment by azeier** [comment]
Make sure you have "auto" enabled at the bottom of the decks list.
