### ISSUE TITLE
AppData\Roaming\HearthstoneDeckTracke to *\HearthstoneDeckTracker

### ISSUE THREAD

**Issue by mssign** [HearthSim/Hearthstone-Deck-Tracker#2876]
C:\Users\User\AppData\Roaming\HearthstoneDeckTracker   - так необходимо хранить настойки, плагины здесь?
было бы здорово если вернете возможность хранения настроек в папке с программой, то есть по пути установки.

**Comment by Vladsg** [comment]
please on English

**Comment by azeier** [comment]
Please keep it in english here.

Google Translate
> so you need to keep the tincture, plugins here? it would be great if you return the ability to store settings in the program folder, ie the installation path.

WIth the installer version of HDT changing the data directory is not possible for technical reasons. You can download a portable verison here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/tag/v1.1.1.0 - This has those features enabled.

The updater on that one has a few issues and will likely not see much maintenance (and is worse in general). For reference: https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2873
