### ISSUE TITLE
No Card Text displayed

### ISSUE THREAD

**Issue by Thrombin** [HearthSim/Hearthstone-Deck-Tracker#2877]
I think this happened when Standard came in but I've been getting no card text when hovering over cards in the Deck Tracker (either the tracker itself or the overlay). I get the name at the top and whether it is a spell or minion at the bottom but nothing in between.

**Comment by azeier** [comment]
- See if reinstalling helps
- Could be a DPI issue - if you have it set to something above 100% try fiddling with it a bit.

**Comment by Thrombin** [comment]
Thanks for the reply. I found out what it was: the Card Language under General Options had not been selected.

I don't remember that being an option previously. I guess it must have been introduced at some point and, not selecting a value, left all the cards blank!
