### ISSUE TITLE
update bug 

### ISSUE THREAD

**Issue by nsk** [HearthSim/Hearthstone-Deck-Tracker#2878]
Creating temp file directory
Downloading latest version... 26472/26472KB (100%)
Extracting files...
System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.Exception: Error extracting the downloaded file. ---> System.IO.IOException: Le fichier 'HDTUpdate_new.exe' existe déjà.
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   à System.IO.File.Copy(String sourceFileName, String destFileName)
   à HDTUpdate.Program.CopyFiles(String dir, String newPath)
   à HDTUpdate.Program.<Update>d__2.MoveNext()
   --- Fin de la trace de la pile d'exception interne ---
   à HDTUpdate.Program.<Update>d__2.MoveNext()
   --- Fin de la trace de la pile d'exception interne ---
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à HDTUpdate.Program.Main(String[] args)
---> (Exception interne #0) System.Exception: Error extracting the downloaded file. ---> System.IO.IOException: Le fichier 'HDTUpdate_new.exe' existe déjà.
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   à System.IO.File.Copy(String sourceFileName, String destFileName)
   à HDTUpdate.Program.CopyFiles(String dir, String newPath)
   à HDTUpdate.Program.<Update>d__2.MoveNext()
   --- Fin de la trace de la pile d'exception interne ---
   à HDTUpdate.Program.<Update>d__2.MoveNext()<---

There was an error installing the latest update. Press any key to open the website for manual download.

**Comment by riQQ** [comment]
See  #2873.
