### ISSUE TITLE
Can't find the directory

### ISSUE THREAD

**Issue by truongdx271** [HearthSim/Hearthstone-Deck-Tracker#2881]
after i run the installer, HDT open. But i can't find the shortcut...
Where is the default directory? How can i find it in my laptop?

**Comment by MrWaz** [comment]
I've the same issue here.. no shortcut created (Win 10)

As a workaround, the program is in 
`C:\Users\<YourUserName>\AppData\Local\HearthstoneDeckTracker\app-1.1.1`

**Comment by andburn** [comment]
This is a Squirrel (the installer library) issue, there seems to be problem creating shortcuts on some computers (https://github.com/Squirrel/Squirrel.Windows/issues/509).

The best work around is to create your own shortcut with the following target:
```
C:\Users\<User>\AppData\Local\HearthstoneDeckTracker\Update.exe --processStart "HearthstoneDeckTracker.exe"
```
This should still work after any HDT updates.

**Comment by judge2020** [comment]
Not an HDT issue, should close.
