### ISSUE TITLE
Plugin loading information reset after each launch/restart

### ISSUE THREAD

**Issue by TheMiziko** [HearthSim/Hearthstone-Deck-Tracker#2884]
Hello ! So, in my files, even after enabling my plugins in HDT, and restarting my pc, the plugins.xml file resets it to "false"
`<?xml version="1.0" encoding="utf-8"?>
<ArrayOfPluginSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <PluginSettings>
    <FileName>C:\Users\TheMiziko\AppData\Local\HearthstoneDeckTracker\app-1.1.1\Plugins\Treasury\Hearthstone Treasury.dll</FileName>
    <IsEnabled>false</IsEnabled>
    <Name>Treasury</Name>
  </PluginSettings>
  <PluginSettings>
    <FileName>C:\Users\TheMiziko\AppData\Local\HearthstoneDeckTracker\app-1.1.1\Plugins\Zero to Heroes\ZeroToHeroesPlugin.dll</FileName>
    <IsEnabled>false</IsEnabled>
    <Name>Zero to Heroes</Name>
  </PluginSettings>
</ArrayOfPluginSettings>`

And I'm including logs from startup :)
[log_10102016-81652.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/518878/log_10102016-81652.txt)

It seems to be related to using some of the "advanced options" or startup on launch :)

In addition to that, some of my games were not recorder, even tho i had my tracker launched, and started the game, cards didn't update

**Comment by azeier** [comment]
Likely related to updates. https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2849 will be fixed with the next one.

**Comment by judge2020** [comment]
closed in favor of #2849 and fixed by now
