### ISSUE TITLE
0-0 arena run/ deleting incomplete runs

### ISSUE THREAD

**Issue by waimaster** [HearthSim/Hearthstone-Deck-Tracker#2885]
I have a couple runs that the tracker didn't fully record because I wasn't running it, it would be nice to have an option to delete all run with less than 3 losses or 12 wins or just have incomplete runs not count into the stats ( I am pretty sure they currently do). Deleting all games from a run just leaves it as 0-0, I'd really like to delete those runs entirely. The 0-0 runs do not have a time, so selecting anything but "all time" does exclude them but it's not a very clean solution.

**Comment by andburn** [comment]
You need to delete the associated arena decks, and possibly restart HDT.

**Comment by waimaster** [comment]
Oh, thanks alot :)
