### ISSUE TITLE
problem after autorestore from latest backup

### ISSUE THREAD

**Issue by Werwolfsoul** [HearthSim/Hearthstone-Deck-Tracker#2886]
i had 4 runs in arena yesterday.
today HDT autorestored from latest backup at the start. 
arenas, that i played yesterday, there, but without stats. it is like very important for my statistic in general... before, when HDT crashed i just added missing matches from my notes for complete stats.
now i cant add games from my notes to this arenas 'cos they don't have any games at all and I can't find them in stats window.
how can I add matshes to 0-0 arena?
it's kinda important to me 'cos it's affect all my arena stats, that I keep more then year. especially 'cos two of them was priest runs - I didn't had many priest runs, so that's a huge affect for my stats.
sry for my English and thx for reading that.

**Comment by riQQ** [comment]
`Stats > Area > Runs & matches > Add game` to add games.
Do you have a crash report (see https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues).

**Comment by Werwolfsoul** [comment]
![1](https://cloud.githubusercontent.com/assets/19953370/19277043/07302bb2-8fe1-11e6-927c-2d79acb8017b.png)
tnx for answer anyway.

**Comment by jleclanche** [comment]
@azeier how do you do region detection? You can use the account_hi value like we do on the site

**Comment by azeier** [comment]
@jleclanche Decks don't have a region, it's deduced from the games played.
