### ISSUE TITLE
Constructed Stats: Tenth "Other" Class?

### ISSUE THREAD

**Issue by kingskybomber14** [HearthSim/Hearthstone-Deck-Tracker#2894]
I went into my stats and was looking at my ranked stats when i noticed something strange: There were ten classes on the "opponents" pie chart, which makes no sense, seeing that i was filtering to include ranked mode only. This only included the US region. Switching to include all regions meant that there were 2 ranked games played against other. If this helps at all, the last time i played on another region was during WOG.
Also, the coin thing says no and no because i'm still on version 1.1.0, as I've been unable to update.
![screenshot 326](https://cloud.githubusercontent.com/assets/9788077/19413767/7d1c1922-9305-11e6-8166-decb1baf8dff.png)

**Comment by riQQ** [comment]
Have you checked if there are any games with no or an invalid opponent class in the `Matches` view?

**Comment by kingskybomber14** [comment]
Yeah, i found some weird thing from a while ago where the tracker though my priest deck was a deck ( for a surprisingly large number of games) and one of those games had no opponent listed.  In one of those games, no enemy class was listed, and it seems like the opponent either disconnected or conceded immediately after i played northshire cleric on turn 1.
