### ISSUE TITLE
Prince Malcheazar appears while in mulligan on MAC client

### ISSUE THREAD

**Issue by TemporalOnline** [HearthSim/Hearthstone-Deck-Tracker#2898]
https://www.reddit.com/r/hearthstone/comments/57xq6f/prince_malchezaar_appears_in_the_deck_tracker/

**Comment by jleclanche** [comment]
Issue moved to [HearthSim/HSTracker #642](https://github.com/HearthSim/HSTracker/issues/642) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jleclanche** [comment]
I'm moving this to the macOS issue tracker seeing as HDT already uses PTL. Thanks!
