### ISSUE TITLE
Crash every action i take

### ISSUE THREAD

**Issue by Elgard** [HearthSim/Hearthstone-Deck-Tracker#2901]
Since the update "replay feature" my hdt crash evrery action i take:
Edit name --> crash
Edit Deck ---> crash
Open stat --->crash
Delete Deck ---> crah...

can you help me?

**Comment by jleclanche** [comment]
Could you attach a log? Instructions here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by Gost24** [comment]
Instead of making a new thread Ill post my log since im basically having the same issue.
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/546017/hdt_log.txt)

**Comment by Gost24** [comment]
[hdt_log_1477168240.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/546018/hdt_log_1477168240.txt)

posting the next one most recent just in case

**Comment by riQQ** [comment]
Can you check for crash logs and errors in the windows event viewer (see https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues).

**Comment by Gost24** [comment]
[hdt2.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/546020/hdt2.txt)

**Comment by Gost24** [comment]
Is that good enough?

**Comment by riQQ** [comment]
Yes, that's good enough.

**Comment by Gost24** [comment]
anything?

**Comment by riQQ** [comment]
@azeier said he's rewriting the log readers, that are causing this issue.

**Comment by Gost24** [comment]
ahh ok so expect an update?

**Comment by azeier** [comment]
I'm not sure yet that will actually be the solution. This is a difficult one. 

This is a bit of a shot in the dark, but try deleting the "Logs" folder within your hearthstone installation, see if that helps.

**Comment by Elgard** [comment]
i tryed, disinstalled, cleared with cc cleaner and reinstalled but same issue.
BUT
a couple of deays ago i installed this verision:
https://hearthstats.net/uploader?locale=en
and now it works fine :D
