### ISSUE TITLE
Deck version saves wrong way

### ISSUE THREAD

**Issue by meetblake** [HearthSim/Hearthstone-Deck-Tracker#2909]
I have multiple deck versions(v1.0, v1.1, v1.2, and so on),
I notice that when I edit the old version deck and it can't be save as the orignal version.
For example,If I have three versions of deck(v1.0,v1.1 and v1.2),
when I edit the  deck v1.0 and It can just be saved as current(v1.2) or the new(v1.3),
It's not any change for deck v1.0, but sometimes I really want to edit the old version.

**Comment by culinko** [comment]
This is #999, which has been merged to #1010.
