### ISSUE TITLE
Enhancement: Localization for tooltips

### ISSUE THREAD

**Issue by sgkoishi** [HearthSim/Hearthstone-Deck-Tracker#2910]
There is no tooltips in the translation repo. 
When people open the setting menu, the tooltips are not given in resx.
The strings like "Works for mobile devices (Laptop, Tablet, ...) only." can not be translated.

**Comment by azeier** [comment]
Translating the tooltips is not quite as easy, they are generated from Hearthstone files.

**Comment by andburn** [comment]
@azeier you scanned it too fast 😉 
Its the UI tooltips, checkboxes, buttons etc. that @gyrodrill wants translated

**Comment by azeier** [comment]
Oh I thought this was talking about both.

**Comment by sgkoishi** [comment]
Fixed in 2017.
https://github.com/HearthSim/HDT-Localization/commit/bbe4c0eb1777891659f4ad7658a340f101faa9ea
