### ISSUE TITLE
Version 1.1.1.1 doesn't export well

### ISSUE THREAD

**Issue by havohavo** [HearthSim/Hearthstone-Deck-Tracker#2914]
The new v1.1.1.1 does not export well the decks. One card is put on deck, like 3 cards not, again one card is ok, 3 not. Giving you an unfinished deck.

**Comment by azeier** [comment]
See if you find a solution here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#exporting

**Comment by havohavo** [comment]
Yes! Thank you. It worked with making hearthstone.exe compatible with Windows 7
