### ISSUE TITLE
HDT crash after each game (last update only)

### ISSUE THREAD

**Issue by Amaiar** [HearthSim/Hearthstone-Deck-Tracker#2921]
Up until last update, HDT worked fine for me, but today I was about to play some games when I started to see the overlay freeze at some points. With some observation, I realised that after a whole match without issues, right after resetting the cards drawn and all that stuff, that'd be the moment when it freezes. When I tried to Alt+Tab or maximise the window, it'd just show the frozen overlay over a black rectangle (the same exact size than my Hearthstone window), and if I tried to click on it, windows would give me the "HDT.exe has stopped working" message.

I have Windows 7 64bits and HDT version 1.1.1. Hearthstone and battle.net are also up-to-date. Any clues on what could have happened? As I said, it worked perfectly fine last time I played (some days ago).

Also, is there any way to revert to a previous version without losing the Decks stored? Maybe I can try that while the issue is solved

**Comment by judge2020** [comment]
> Also, is there any way to revert to a previous version without losing the Decks stored? Maybe I can try that while the issue is solved

If you go to `%userprofile%\AppData\Local\HearthstoneDeckTracker` you will see folders labeled `app-x.x.x`, x.x.xbeing the version. If you go into that version's folder you can run `HearthstoneDeckTracker.exe` and it will keep your decks but use an older version.

![1](http://i.imgur.com/lDyCHF1.png)

Report back if the problem stops occurring when using an older version, we could figure out which commit caused the issue.
