### ISSUE TITLE
I can't use HDT, although it worked up untill now

### ISSUE THREAD

**Issue by Aramorn** [HearthSim/Hearthstone-Deck-Tracker#2925]
So my HDT worked just fine until 2 days ago when it says that HDT has stopped working. I want to mention that along that message the following appears too: „The instruction at 0x61b69aeb referenced memory at  0x000000001. The memory could not be read. Click on OK to terminate the program” 
I have reinstalled the program and it worked again, only to find the next day the same error. I even went to app data to try an older version but that failed also. Need help, since HDT makes wonders for me in Hearthstone. Thanks in advance!

**Comment by riQQ** [comment]
Please provide logs: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues.

**Comment by Aramorn** [comment]
[log HDT.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/564848/log.HDT.txt)

**Comment by Aramorn** [comment]
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/564863/hdt_log.txt)

**Comment by riQQ** [comment]
Any crash logs or anything in the windows event logs (see link above)?

**Comment by Aramorn** [comment]
[HDT error.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/565795/HDT.error.txt)
  Here are the crash logs

**Comment by riQQ** [comment]
The faulting module that is causing the crash is part of your graphics driver.
Did you update your graphics driver or change any graphics setting in your driver before the crashes started?

**Comment by Aramorn** [comment]
I do not think so. I have not installed or updated anything. Today I did try to install a newer version of framework but that also failed... I think I will reinstall windows one of these days if I can't solve it.

**Comment by riQQ** [comment]
You could try updating your graphics driver first.

**Comment by Aramorn** [comment]
I have AMD Radeon HD 8330 and AMD Radeon HD 8600M Series. It says that I already have the latest update. Anyhow, thanks for your help so far!

**Comment by riQQ** [comment]
Does HDT crash when Hearthstone is not running?

**Comment by Aramorn** [comment]
Yes, whether I was playing Hearthstone or not. And now I am out of clues... I haven't done anything whatsoever - install or uninstall, or change some programs - and it works just as if nothing has happened. HDT loves to play with my feelings.

**Comment by riQQ** [comment]
For reference, content  of the logged crash event:
```
Faulting application name: HearthstoneDeckTracker.exe, version: 1.1.1.1, time stamp: 0x580f878a
Faulting module name: amdocl.dll, version: 10.0.1573.4, time stamp: 0x5417655c
Exception code: 0xc0000005
Fault offset: 0x00479aeb
Faulting process id: 0x10d0
Faulting application start time: 0x01d234d1224c23d8
```
