### ISSUE TITLE
Deck archive isn't available

### ISSUE THREAD

**Issue by hagehun** [HearthSim/Hearthstone-Deck-Tracker#2926]
I updated to 0.18.3 (1327) and the deck directory option is missing in the preferences-»Game menu.
I tried to find it but had no luck. Because of that (I guess) the tracker has no deck database. Why is the deck data diretrory option out? How shouls I reach it otherwise?

**Comment by riQQ** [comment]
This is the wrong place. Create an issue over there: https://github.com/HearthSim/HSTracker/.
