### ISSUE TITLE
minor issue

### ISSUE THREAD

**Issue by Werwolfsoul** [HearthSim/Hearthstone-Deck-Tracker#2927]
![clipboard2](https://cloud.githubusercontent.com/assets/19953370/19931787/7bbb75b8-a116-11e6-8269-e40dbb88edee.png)
is this only me? It's not a big deal, but I feel I should write about it anyway.

**Comment by riQQ** [comment]
What is your problem, exactly? The missing classes?

**Comment by Werwolfsoul** [comment]
that is all classes I played. there was no stats for shaman and warlock, as u can see from "average wins per class" diagram.
does 30 mage games looks like 10%? sum of all not = 100% it's 10+6+3+2+2+1+0=24%
it's ok in the "opponents" diagram.
p.s. sry for so long. didn't think the issue could be unclear.

**Comment by riQQ** [comment]
Sorry, my bad, I didn't really look at the numbers. I can reproduce this problem by setting a custom start time.

**Comment by riQQ** [comment]
Duplicate of #2634
