### ISSUE TITLE
lost replays, can't upload more

### ISSUE THREAD

**Issue by 17inchcorkscrew** [HearthSim/Hearthstone-Deck-Tracker#2928]
HSReplay account settings says I have no associated upload client, HDT client says my account is registered and it will upload automatically.

**Comment by jleclanche** [comment]
Sounds like you claimed your account with a different Battle.net account as the one you logged in with?

Do you have multiple battletags by any chance? (like an alt or something) - if you do, give me both battletags and ill merge them.

**Comment by 17inchcorkscrew** [comment]
My HSReplay account says it's YrObtSvt#1637, which is the only bnet account I've used.

**Comment by jleclanche** [comment]
@17inchcorkscrew sorry for the delay, we were at blizzcon.

I think this might be fixed now; your battletag was an empty string for some reason. Can you check again?

**Comment by 17inchcorkscrew** [comment]
Thanks, but nothing changed. My account still says it has no associated client, my client still says my account is registered, and it still won't upload replays.

**Comment by 17inchcorkscrew** [comment]
Sorry for bumping this, but is there any way my client can reclaim my HSReplay account or just claim another one?

**Comment by 17inchcorkscrew** [comment]
I really loved the feature and would very much like to be able to use it again.

**Comment by jleclanche** [comment]
@17inchcorkscrew Can you email me your zipped config directory (found in `%APPDATA%`)? My email is jerome at hearthsim dot net - I'll look into this for you today

**Comment by jleclanche** [comment]
@17inchcorkscrew ping :)

**Comment by jleclanche** [comment]
I'm closing this. Please shoot me an email and reopen if you want to follow up on it.
