### ISSUE TITLE
HS filled with HDT chroma key copy and cant close。

### ISSUE THREAD

**Issue by sdbds** [HearthSim/Hearthstone-Deck-Tracker#2929]
i open HS without HDT，but it filled with HS。
even i use recovery HS i cant fix it。
![image](https://cloud.githubusercontent.com/assets/8085926/19956510/80a6b53a-a1c8-11e6-83bd-7a3796505c64.png)

**Comment by sdbds** [comment]
i solve it ，just restart my computer...

**Comment by riQQ** [comment]
Clicking it once should have helped, too. It's described in the options.
