### ISSUE TITLE
Allow Harthstone Brawl decks to have more than 2 of each card

### ISSUE THREAD

**Issue by grellth** [HearthSim/Hearthstone-Deck-Tracker#2930]
Example: 
This weeks Hearthstone Brawl lets you choose 10 cards and creates 3 copies of each.
It would be nice to use HDT for tracking cards available and percentages.

**Comment by andburn** [comment]
You can. Disable the *Constructed card limits* check box at the bottom of the card list.

![con_card_limit](https://cloud.githubusercontent.com/assets/5419653/20001148/bd639920-a272-11e6-9e7e-4a24304cb18b.png)

You are right though, it would make sense to have this disabled by default for tavern brawl.
