### ISSUE TITLE
cant find exe after installing ANYWHERE

### ISSUE THREAD

**Issue by LeetCodes** [HearthSim/Hearthstone-Deck-Tracker#2933]
after i installed it, i cant find the exe anywhere, looked in both program files and in appdata and searched my computer but i cant find the exe to run it anywhere.. old version without installer still works but cant run the installer version, can anyone please help?

**Comment by riQQ** [comment]
See #2881.

**Comment by judge2020** [comment]
Were you able to find the directory? @LeetCodes 

From #2881, if you paste this into the run box (windows key+r)

```
%appdata%\..\Local\HearthstoneDeckTracker
```

You should see folders named app-x.x.x, the exe is located in there. 

![img](https://judge2020.me/bYMNp.png)

**Comment by judge2020** [comment]
Should place icon on desktop and entry in start menu

**Comment by GuiParisi** [comment]
Hey. Thx a lot Judge. Even after following these steps I can't find the thing. No .exe anywhere in the folder (which was secret btw, yeah, I'm pretty illiterate compared to most ppl from this community, prolly).
