### ISSUE TITLE
How to save my decks and history when i reinsall windows.Where all informaation located?

### ISSUE THREAD

**Issue by ZergShadow** [HearthSim/Hearthstone-Deck-Tracker#2938]
How to save my decks and history when i reinsall windows.Where all informaation located?

**Comment by riQQ** [comment]
Your data is stored in `%AppData%/HearthstoneDeckTracker`.

**Comment by judge2020** [comment]
closed in favor of #3235

**Comment by judge2020** [comment]
duplicate of #3235
