### ISSUE TITLE
HDT Constantly Crashing right after the latest update

### ISSUE THREAD

**Issue by MaestroDaVinci** [HearthSim/Hearthstone-Deck-Tracker#2941]
Today i had to use the tracker and i needed it to add a deck from the web to hearthstone i tried and it constantly is crashing it gets around the 13th card and then it just crashes, there is no error or anything it just crashes. I tried opening it again and again and again and again it constantly crashes.

Is there an issues that i don't know or a solution?

**Comment by riQQ** [comment]
Checked all points on this list: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues?

**Comment by riQQ** [comment]
Solved? What was the solution?

**Comment by MaestroDaVinci** [comment]
Where does it say solved? I closed it because the HDT worked a bit slow, but it worked.

**Comment by riQQ** [comment]
That's why I wrote it as a question. In your first post you said it was crashing constantly. Has it stopped crashing? What did you change?

**Comment by MaestroDaVinci** [comment]
That is what i'm trying to tell you i didn't change anything it just stopped crashing i don't know what t tell you.

**Comment by riQQ** [comment]
Okay, thanks for the clarification.
