### ISSUE TITLE
Show information how much this card is useful in current deck

### ISSUE THREAD

**Issue by Lucas83** [HearthSim/Hearthstone-Deck-Tracker#2943]
When you're new player in hearthstone and when you don't have much cards then you don't really know how much popular or useful is card for a specific character you create. Recently I found at heartharena.com/tierlist numbers next to each card. How about use this information and shows it next to card name, to find out which cards are good or weak in currently used deck?

**Comment by riQQ** [comment]
The Hearth Arena tierlist is only meaningful for Arena. If you want help drafting, you can try https://github.com/rembound/Arena-Helper.

**Comment by culinko** [comment]
Reminds me of #446, but that one takes the data from your past matches, rather than global data of other players.

**Comment by judge2020** [comment]
This is now a feature in HSReplay! https://hsreplay.net/decks

**Comment by XBagon** [comment]
I feel like this feature would be also useful in the client for the user's own decks, just based on the games you played yourself. I would love to have all the features of
> https://hsreplay.net/decks
locally to optimize my decks currently in the making.
