### ISSUE TITLE
Some questions.

### ISSUE THREAD

**Issue by hasnogaems** [HearthSim/Hearthstone-Deck-Tracker#2947]
https://twitter.com/hsdecktracker/status/631780286502670336
It says "the manacurve can also display overload". What manacurve? Where? Is it in options somewhere?
Also isnt there a plugin for tracking from twitch streams for viewers?

**Comment by judge2020** [comment]
I'm pretty sure this was removed, as I can't find it anywhere, and that tweet was from '15.

**Comment by riQQ** [comment]
It's still there. After enabling `Advanced options` in the options, there's the option `Show mana curve` in the `Tracker > General` tab. You can see the mana curve below the deck list in the main window. To see the overload curve change the selection in the drop-down list from `Mana` to `Overload`.

>Also isnt there a plugin for tracking from twitch streams for viewers?

Can you clarify what you mean by that?
