### ISSUE TITLE
SignTool error : Missing filename.

### ISSUE THREAD

**Issue by chucklu** [HearthSim/Hearthstone-Deck-Tracker#2948]
in the post-build event command line 
signtool sign /tr http://timestamp.digicert.com /a /f "..\..\..\HearthSimCodeSigningCert.pfx" /p %HearthSimCert% "..\Hearthstone Deck Tracker/\*.exe"

when i build the project under release mode,I got the error :SignTool error : Missing filename.

**Comment by jleclanche** [comment]
You shouldn't be building a signed release, as you don't have a certificate for it.

**Comment by chucklu** [comment]
I can find seven signtool.exe in my disk c:
C:\Users\Administrator\.nuget\packages\squirrel.windows\1.4.4\tools
C:\Users\Administrator\.nuget\packages\squirrel.windows\1.4.2\tools
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin
C:\Program Files (x86)\Windows Kits\10\bin\x64
C:\Program Files (x86)\Windows Kits\8.1\bin\arm
C:\Program Files (x86)\Windows Kits\8.1\bin\x64
C:\Program Files (x86)\Windows Kits\8.1\bin\x86

I am using C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin,

**Comment by jleclanche** [comment]
It's not about the program, you are missing the certificate. HearthSim LLC holds a certificate for Hearthstone Deck Tracker and distributes a signed copy off hsdecktracker.net, but if you want to build your own copy you don't need that.

**Comment by chucklu** [comment]
@jleclanche ,the project have three mode ,Debug,Release and Squirrel,
so,which one shouid I build with?

yeah,I can not find the file under project HearthSimCodeSigningCert.pfx

**Comment by jleclanche** [comment]
Debug is probably what you want.

**Comment by chucklu** [comment]
@jleclanche so, when to use Squirrel mode?

**Comment by jleclanche** [comment]
Squirrel is one of our release modes. It's for distribution only.

**Comment by chucklu** [comment]
@jleclanche thank you very much
