### ISSUE TITLE
Auto Update Fails

### ISSUE THREAD

**Issue by ltrippany** [HearthSim/Hearthstone-Deck-Tracker#2951]
For the last ~3 versions of this the automatic update always fails because 'HDTUpdate_new.exe' already exists. I see this file is created during the update so I don't understand why it complains about it? Deleting it allows it to update it and recreate, but when a new version is released it goes back to complaining that it exists.

**Comment by riQQ** [comment]
See #2873.

**Comment by ltrippany** [comment]
Ah, how exactly do I actually switch to the new installer though? When I download the one linked from that page it just launches HDT without prompting any installs.

**Comment by riQQ** [comment]
There should be a new shortcut on your desktop to launch HDT. If not, see #2881.

**Comment by jleclanche** [comment]
Closing - please reopen if you're still having issues.
