### ISSUE TITLE
Stats not being tracked for certain decks

### ISSUE THREAD

**Issue by pjbingham** [HearthSim/Hearthstone-Deck-Tracker#2955]
Most decks record stats fine, but a small few record no stats at all - they remain as 'NO STATS' no matter how many games are played (and the decks are otherwise being detected fine - they're being tracked in-game - cards played etc. - fine).

I haven't completely pinned down the pattern but I _think_ it's to do with decks with names that are the same as decks that have previously been deleted.

Sometimes, cloning the deck and deleting the offending one sorts the issue (the clone then goes on to collect stats normally), but sometimes it doesn't.

Also, often the games themselves can be found in the list of matches... but sometimes not... and often, when they are there, they appear to be associated with the correct deck, even though the deck itself shows as 'NO STATS'

Sorry this is all a bit vague, but it's all I've been able to work out so far.  Happy to spend the time helping with the troubleshooting and/or forward whatever files you need - please advise next steps.

**Comment by judge2020** [comment]
Are you still experiencing this @pjbingham?
