### ISSUE TITLE
Deck tracker is broken for me 

### ISSUE THREAD

**Issue by xactorock** [HearthSim/Hearthstone-Deck-Tracker#2956]
I had installed deck tracker to free space when I come back to reinstall it my decks do not import automatically and I also do not have a layout showing up

**Comment by riQQ** [comment]
Try this: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#not-working.

**Comment by xactorock** [comment]
I do not have a touch screen computer

**Comment by xactorock** [comment]
That says if some are I have none and it will not even import deck names 
Or any overlay at all

**Comment by xactorock** [comment]
Ok I fixed it I had to redo the path to the hearthstone director y

**Comment by charberg** [comment]
Seems like this issue can be closed.
