### ISSUE TITLE
Missing HeartStats button

### ISSUE THREAD

**Issue by smith666** [HearthSim/Hearthstone-Deck-Tracker#2957]
Hi, im trying to install app on new computer, i dont know why but i dont see heartstats button.
![image](https://cloud.githubusercontent.com/assets/283391/20461537/6918e49c-af01-11e6-9483-168a2844c60a.png)

**Comment by riQQ** [comment]
Go to the options and enable `Advanced options`. Then go to `Tracker > Settings` and enable `Show HearthStats` menu.

**Comment by Flobbes** [comment]
Maybe this option should be better accessable?
I just wanted to open a bug report as well.

Any reason why this isn't enabled by default any more?

**Comment by azeier** [comment]
HearthStats is no longer maintained by the new owner (or in HDT) and we are working on a better solution.
