### ISSUE TITLE
Deck Tracker crashes when i try open stats

### ISSUE THREAD

**Issue by AngelKing13** [HearthSim/Hearthstone-Deck-Tracker#2960]
It used to work fine, but now every time i try open the stats page it crashes, everything else works fine, tracker overlay in games is fine its just when i click the stats page the whole thing crashes.

**Comment by judge2020** [comment]
Is there a stack-trace that pops up? if so. copy it to hastebin or pastebin.

**Comment by riQQ** [comment]
See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues.

**Comment by AngelKing13** [comment]
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/609861/hdt_log.txt)

**Comment by riQQ** [comment]
Can you check this point, please: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#windows-log-files?

**Comment by AngelKing13** [comment]
Ah i dont know what im looking for here, so im going to give up, thanks for helping though :)
