### ISSUE TITLE
Stats are not recorded for some games

### ISSUE THREAD

**Issue by szymontrapp** [HearthSim/Hearthstone-Deck-Tracker#2962]
In the last few days, I noticed that some games are not recorded in stats. Replays for those games are available but stats don't take them into account.

I played 2 games this morning and only the second game (against warrior) was recorded in stats. The first one (hunter) is missing. Both games were casual, played with the same deck.

I'm attaching the log file.
[log_23112016-74522.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/609281/log_23112016-74522.txt)

**Comment by azeier** [comment]
Judging from the log, the game should have been recorded fine. Make sure you don't have any stats filters set that might cause it to be hidden.

**Comment by szymontrapp** [comment]
Are all those options ins stats? I have Ranked, Arena, Brawl, Casual and Friendly ticked. My lost matches were all either Ranked or Casual.

Advanced options are:
Off: Discard game if deck does not match cards, Discard games with zero turns
On: Record local replays, Keep stats when deleting a deck, Show deck stats in a separate window

Anything more I should check?

**Comment by riQQ** [comment]
The filters on the left in the stats window.

**Comment by szymontrapp** [comment]
Ok, that was it. I feel silly. Thanks for help.
