### ISSUE TITLE
Spellbender not grayed out

### ISSUE THREAD

**Issue by Confoundit** [HearthSim/Hearthstone-Deck-Tracker#2963]
I was playing the current tavern brawl (Valeera's Bag of Burgled Spells) and I noticed an issue with Spellbender.  My opponent had a secret up and I hadn't tested for Spellbender yet.  I cast Cobra Shot and then used a Roaring Torch on a second minion.  I think that both would have triggered Spellbender if that were the active secret.  However, at the end of my turn, Spellbender hadn't been grayed out.  Ultimately, his secret must have been Mirror Entity.

**Comment by riQQ** [comment]
Did your opponent have a full board?
