### ISSUE TITLE
DefaultDeckStats.xml missing from AppData Folder

### ISSUE THREAD

**Issue by menace97** [HearthSim/Hearthstone-Deck-Tracker#2964]
#417: Error upating to v0.6.0 by @jayhall (closed)

This was the only issue I could find regarding a missing DefaultDeckStats.xml file in the AppData Folder, so I thought I would reference it as I did above.

I used to have one, as I look through some of my backups, but only recently I noticed that only that particular file was missing from the usual same files in the AppData Folder. I haven't noticed any strange behavior, but since the file is missing, I came here to find out what I should do to recreate it.

Using Issue #417 as a reference, @azeier suggested:

> "The file should usually just be created, yea. Not sure what the problem is.
> 
> go to "%appdata%/hearthstonedecktracker" (press WIN+R to bring up the run dialog and paste the path there)
> create a file called "DefaultDeckStats.xml"
> open it and paste
> DefaultDeckStats/DefaultDeckStats (**<>** removed, as wasn't showing up)
> save and everything should be fine."

I did exactly as @azeier suggested, but haven't noticed anything really different happening. Again though, nothing negative was occurring before - not that I am aware of.

Is this a file that I should just leave with pasted data from the above quote in the contents, or should I use an old backup of a version of DefaultDeckStats.xml?

_It looks very similar of course to the data I see in DeckStats.xml, and that file is there and seems to have all the data of cards, decks, games, previews, etc._

**Comment by azeier** [comment]
Are you having any issues due to it not existing? It might not be created if there's no data to store in it.

**Comment by menace97** [comment]
Thanks very much for responding @azeier - much appreciated! I haven't noticed anything wrong or different to be honest, I just thought it was odd that it didn't get re-created... but maybe it isn't necessary? Is this an important/necessary file? Or is this been essentially sent to DeckStats.xml now?

I'll include my latest logs if there might be something that looks wrong to you, thanks very much for your help!
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/614029/hdt_log.txt)
[hdt_log_1480067599.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/614030/hdt_log_1480067599.txt)

**Comment by azeier** [comment]
Matches played without an active deck are stored in DefaultDeckStats. If HDT doesn't need to create it it won't be created :P. I'm also fairly sure the condition for generating it changed since v0.6.0.

I'm gonna close this since it's not actually an issue.

**Comment by menace97** [comment]
Thank you for the help Alexander @azeier :)
