### ISSUE TITLE
uneven permissions

### ISSUE THREAD

**Issue by arielrahamim** [HearthSim/Hearthstone-Deck-Tracker#2966]
Hello , iv'e been getting this error : 
![image](https://cloud.githubusercontent.com/assets/23728768/20627850/6e75dd86-b32b-11e6-8e49-48b20bc59242.png)
i tried to run them as admin but no luck.
any thing i can do to fix it?

**Comment by azeier** [comment]
Duplicate of #2738.

There are a few suggestions over in that issue, please give them a shot.
In short though: We don't know what might be causing this on some machines.

**Comment by blaice** [comment]
Same issue btw.  Posted in link.
