### ISSUE TITLE
Can't get Hearthstone tracker to work.

### ISSUE THREAD

**Issue by Vitskugga** [HearthSim/Hearthstone-Deck-Tracker#2967]
Hi!
I can't get Hearthstone tracker to work! It doesn't recognise when I'm playing any games or doesn't screenshot my decks or anything.
It only notices if Hearthstone is running or not.
What do I do and how do I do it so it works correctly?

**Comment by azeier** [comment]
See here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#not-working
