### ISSUE TITLE
Overlay not showing

### ISSUE THREAD

**Issue by maw004** [HearthSim/Hearthstone-Deck-Tracker#2972]
Followed all the steps in FAQ but overlay not appearing. Log looks fine:

11:16:57 AM|Info|Core.Initialize >> HDT: 1.1.1.2, Operating System: Windows 10 Pro 10586, .NET Framework: 394254
11:16:58 AM|Info|Updater.StartupUpdateCheck >> Checking for updates
11:16:58 AM|Info|Updater.GetReleaseUrl >> Downloading releases file
11:16:59 AM|Info|Updater.GetReleaseUrl >> using 'live' release: https://github.com/HearthSim/HDT-Releases
11:17:01 AM|Info|Updater.SquirrelUpdate >> Checking for updates (ignoreDelta=False)
11:17:04 AM|Info|Updater.SquirrelUpdate >> No new updated available
11:17:04 AM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
11:17:05 AM|Info|ThemeManager.LoadThemes >> Found theme: classic
11:17:05 AM|Info|ThemeManager.LoadThemes >> Found theme: dark
11:17:05 AM|Info|ThemeManager.LoadThemes >> Found theme: frost
11:17:05 AM|Info|ThemeManager.LoadThemes >> Found theme: minimal
11:17:05 AM|Info|GameV2.Reset >> -------- Reset ---------
11:17:05 AM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
11:17:06 AM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
11:17:07 AM|Info|MainWindow.SelectDeck >> Switched to deck: test (v1.0)
11:17:07 AM|Warning|LogReaderManager.Stop >> LogReaders could not be stopped, stop already in progress.
11:17:07 AM|Info|GameV2.Reset >> -------- Reset ---------
11:17:07 AM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
11:17:07 AM|Info|BackupManager.Run >> Running BackupManager
11:17:07 AM|Info|BackupManager.Run >> Backup for today already exists
11:17:07 AM|Info|PluginManager.LoadPlugins >> Loading Plugins...
11:17:07 AM|Info|ApiWrapper.UpdateAccountStatus >> Checking account status...
11:17:08 AM|Info|ApiWrapper.UpdateAccountStatus >> Id=0, Username=, Status=Anonymous
11:17:30 AM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
11:17:31 AM|Info|LogReader.ReadLogFile >> Found LoadingScreen.log.
11:17:31 AM|Info|GameV2.CurrentMode >> LOGIN
11:17:35 AM|Info|LogReader.ReadLogFile >> Found Rachelle.log.
11:17:46 AM|Info|LogReader.ReadLogFile >> Found FullScreenFX.log.
11:17:50 AM|Info|GameV2.CurrentMode >> HUB
11:17:50 AM|Info|LoadingScreenHandler.CheckMirrorStatus >> Mirror status: Ok
11:17:58 AM|Info|Core.UpdateOverlayAsync >> Exited game
11:17:58 AM|Info|Core.UpdateOverlayAsync >> Reset region
11:17:58 AM|Info|LogReaderManager.Stop >> Stopped LogReaders.
11:17:58 AM|Info|GameV2.Reset >> -------- Reset ---------
11:17:58 AM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
11:17:59 AM|Info|LogReaderManager.Restart >> Restarting LogReaders.
11:18:01 AM|Info|MainWindow.Window_Closing >> Shutting down...
11:18:01 AM|Info|LogReaderManager.Stop >> Stopped LogReaders.

Kindly assist. Thanks in advance. :)

**Comment by xactorock** [comment]
I had this problem try re routing the application to the hearthstone folder

**Comment by xactorock** [comment]
That worked for me anyway

**Comment by maw004** [comment]
Could you share how you did that? Was it through advanced settings? I tried that and pointed to D:\Hearthstone which was sitting in my secondary drive. still nothing.

**Comment by xactorock** [comment]
I went options settings set hearthstone path

**Comment by xactorock** [comment]
Sorry if it does not work

**Comment by maw004** [comment]
Nvm I got it to work. Did the config replacement thingy and then cleared the app data then suddenly it appeared after 3 days! Thanks all.
