### ISSUE TITLE
arena deck stuck as active deck, won't record new matches

### ISSUE THREAD

**Issue by KnowWon** [HearthSim/Hearthstone-Deck-Tracker#2973]
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/615039/hdt_log.txt)
have tried restarting hearthstone and deck tracker in every order i can 
after i do an arena run find that i can't get rid of the rewards pop up that comes after tried saving it and closing it but still kept popping up then when i play constructed it doesn't record the games and still shows the arena deck list and says the cards aren't in the deck.
i ticked the box to stop the pop up coming up and did another arena run but now the rewards popup hasn't displayed and i am stuck wiht the arena deck list. this happened before and i reinstalled a fresh copy over the top but as soon as i did an arena run saw the problem come back. 
many thanks for any time you spend looking at this issue

**Comment by KnowWon** [comment]
nb: the new matches were recorded have found them listed under the arena runs which it still thinks is active deck

**Comment by azeier** [comment]
Is the `AUTO` mode at the bottom of the deck list enabled (blue)?

**Comment by KnowWon** [comment]
thanks that worked perfectly knew i must have accidentally clicked something. you're a star
