### ISSUE TITLE
Stats - wrong best deck

### ISSUE THREAD

**Issue by szymontrapp** [HearthSim/Hearthstone-Deck-Tracker#2974]
My stats show unexpected deck as the best deck. It shows "Custom Hunter" deck with 31-29 wins (52%). To me, the best deck should be "Custom Mage" with 21-16 record (57%). There's also a paladin deck with the win percentage better than hunter.

The only filter I have set is Time to Current Season. But changing this doesn't matter - still hunter is selected as better even though mage has better percentage.

I'm attaching a screenshot as well.
![hs wrong best deck](https://cloud.githubusercontent.com/assets/17664507/20657564/9f8cfd66-b4eb-11e6-8fa9-138f81e78cea.PNG)

**Comment by jfmario** [comment]
I am having the same issue. I am wondering if it simply counting most wins rather than best record?

**Comment by azeier** [comment]
This happens because the "best deck" logic is factoring in the number of games. The reason being that your deck with `19-1` stats is actually a lot better than your `1-0` deck, even though the latter has the higher winrate. 

We should probably change the factor probably needs to be logarithmic.

**Comment by GustavoFischer** [comment]
Yes, please. It always shows a deck other than the one I consider the "best". I agree about giving weight to the number of games played (and maybe a cutoff of minimum X games, like it's done in the CompetitiveHS reddit :) ). Do you accept pull requests?

**Comment by Mercury48** [comment]
I gave it some thought and I came up with a pretty nice and super-simple formula to calculate which the best performing deck is.

I want to check with you guys, though. The formula works pretty nicely even when the number of games (with a given deck) is really small (1, 2... games). That said, I still think that such a small sample of games should not be taken into consideration when we talk about statistics.

So, I suggest that I add a condition nonetheless. Something like: "number_of_games_played >= x"

If you agree with me, what do you propose that the value of 'x' should be? maybe 5 or 10 games in order to account for them? what do you think?

**Comment by Mercury48** [comment]
to give you an idea, the formula is as simple as:	Games / (Loses + 1)

this takes into account not only **win-rate** but **number of games** as well without throwing things off-balance. I include a .txt with some calculations I've already put down to check it's results.

In short, this formula calculates indexes, then I will compare them and use the greater number.
It will make calculations like this:
a) 5 wins out of 8 games (for short 5/8) -> index = 2
b) 31/60 -> 2
c) 21/37 -> 2.17
(there are more calculations within the .txt.)

When there is a draw, the deck with the largest sample (most games) will be the one to be picked.
for example, the program would pick (in that order):

44/50 (7.14) **>** 18/20 (6.6) **>** 7/8 (4) **>** 21/37 (2.17) **>** 31/60 (2) **>** 5/8 (2) **>** 9/20 (1.66)

as you see, the formula prioritizes stable results like 44/50 over 18/20 even though the later has technically a higher win rate (90% vs. 88%).

I believe that it is really balanced, safe and simple and it will help the players know their efficiency
Does it look good? Should I go ahead and implement it?

[formula_behavior_calculations.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1978063/formula_behavior_calculations.txt)

**Comment by azeier** [comment]
That looks good. Should definitely be an improvement overt the current formula.
