### ISSUE TITLE
i found bug in gam history sorting

### ISSUE THREAD

**Issue by ZergShadow** [HearthSim/Hearthstone-Deck-Tracker#2975]
When i sort this week, not all replays are seen that have seen in "all time  or current season".Sometimes 1-2 days missing.

**Comment by ZergShadow** [comment]
someone had that problem?

**Comment by riQQ** [comment]
Can you post screenshots to demonstrate the issue?

**Comment by judge2020** [comment]
Are you looking within Hearthstone Deck Tracker or are you looking through your games on HSreplay.net ?

**Comment by ZergShadow** [comment]
deck tracker "this week"  and 1 day mising that only appear in curent season.this issue was 2 times.

**Comment by riQQ** [comment]
I can't reproduce this. Could you provide your `PlayerDecks.xml`, `DefaultDeckStats.xml` and `DeckStats.xml`?

**Comment by ZergShadow** [comment]
https://drive.google.com/file/d/0B3i5r1GJTCBDazVCamJDOUJiWlU/view?usp=sharing
https://drive.google.com/file/d/0B3i5r1GJTCBDNXBaX3NieVcxYUk/view?usp=sharing
https://drive.google.com/file/d/0B3i5r1GJTCBDNU42Y1BHX1Y1Q1k/view?usp=sharing

**Comment by ZergShadow** [comment]
hey

**Comment by ZergShadow** [comment]
hey

**Comment by riQQ** [comment]
I can't reproduce this even with setting back my windows time to the 29th november. Can you give specific instruction to reproduce this?

**Comment by ZergShadow** [comment]
27 november dissapear

**Comment by riQQ** [comment]
Okay, i can reproduce the issue.
