### ISSUE TITLE
update problem

### ISSUE THREAD

**Issue by sisonoio** [HearthSim/Hearthstone-Deck-Tracker#2976]
whatever i do, like uninstalling 1.1.1 version and deleting all hdt folders from appdata/local and appdata/roaming, the new version after using this installer [https://hsdecktracker.net/download/] is always still 1.1.1 and never 1.1.2. what should i do?

**Comment by azeier** [comment]
The latest version is 1.1.1.2, not 1.1.2. The splash screen shows only the first three digits.
