### ISSUE TITLE
Secrets of Gadgetzan

### ISSUE THREAD

**Issue by Drui7** [HearthSim/Hearthstone-Deck-Tracker#2977]
Upgrade is about to. The last time the support of the new secret hunter made a very long time. 
Please think in advance about how it will look to support new secret code, with the first to upgrade to mark the release of an update, it was already possible to see these secrets in HDT.
These secrets are known and will definitely be introduced in the game:
http://www.hearthhead.com/cards/getaway-kodo
http://www.hearthhead.com/cards/hidden-cache
http://www.hearthhead.com/cards/potion-of-polymorph

**Comment by azeier** [comment]
Yup. Can't do anything before we have game data.

**Comment by judge2020** [comment]
Overall these won't be that hard:

Potion of polymorph works in the same as Mirror entity. Will have to remove the check for a full board as polymorph will always trigger on minion play. 

Getaway kodo works like avenge, just will need to add a indicator that the card is `card returned`, as we do already with return to hand cards.

hidden cache also works like potion/mirror, when a minion is played.

**Comment by Drui7** [comment]
@judge2020 
I hope you're right
