### ISSUE TITLE
HSD options selected won't save/reset

### ISSUE THREAD

**Issue by Kahly** [HearthSim/Hearthstone-Deck-Tracker#2978]
I am having issues trying to save my options in the deck tracker. When I go to options and select everything I want the next time I close and open it again all the options have been reset. Same goes for deleting decks. I tried deleting a deck and then tried deleting all of them and when I close HDT and open it again they are all back. I tried uninstalling and reinstalling hoping it would help but that didn't do anything either. Is there a save button somewhere I am missing? It's very frustrating. Thanks!

**Comment by azeier** [comment]
Sounds like HDT has no permission to write to files. Try running HDT as admin.

**Comment by Kahly** [comment]
That did not work either.

**Comment by azeier** [comment]
Please do this:
- Restart HDT
- Delete a deck/change options
- Open the appdata folder (see here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)
- Close HDT
- Upload the hdt_log.txt (after closing hdt!) as described in the link above.

**Comment by Kahly** [comment]
Not sure if I did this right.

[log_29112016-171719.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/620379/log_29112016-171719.txt)

**Comment by azeier** [comment]
Looks good. It's definitely a permissions issue:
> Access to the path 'C:\Users\Angel\AppData\Roaming\HearthstoneDeckTracker\...' is denied.

Go to that path (one level up from where there Log folder was), rightclick on the `HearthstoneDeckTracker` folder and check the `Security` tab. Make sure "Full control" is set for your current user.

**Comment by Kahly** [comment]
I'm enclosing a screenshot. As far as I can tell I have full permissions. I'm so confused!


[cid:9a488b6a-8372-499e-85f4-e7eabbcc018f]


________________________________

**Comment by azeier** [comment]
Attaching screenshots via email doesn't work sadly. You can directly upload them on github though.

**Comment by Kahly** [comment]
Oops...

![users](https://cloud.githubusercontent.com/assets/24258194/20732065/de93a5c6-b65a-11e6-80ff-6727fad09c33.jpg)

**Comment by azeier** [comment]
That's the properties for the HDT shortcut, not the `C:\Users\Angel\AppData\Roaming\HearthstoneDeckTracker` folder. Check that one :).

**Comment by Kahly** [comment]
Ok, this time?

![users2](https://cloud.githubusercontent.com/assets/24258194/20732756/29855888-b65e-11e6-9fde-265bc8021bbc.jpg)

**Comment by azeier** [comment]
Yeah that looks good.. Not sure what's going on here :/.

**Comment by Kahly** [comment]
Well at least I know I'm not losing my mind. Is there any way to just delete or reset to factory defaults or something so I can try to start over? I tried uninstalling but when I installed it again it was still the same and had all my decks from previously etc.

**Comment by azeier** [comment]
You could try renaming the `C:\Users\Angel\AppData\Roaming\HearthstoneDeckTracker` folder and running HDT again. If it can save changes, try copying the files from the renamed one over (without HDT running).

**Comment by Kahly** [comment]
Omg it worked. All I did was rename it and then open it. Thank you so much! 
*knock on wood*

**Comment by azeier** [comment]
Awesome :). Glad we figured it out!
