### ISSUE TITLE
I'm confused, does the program self update or not?

### ISSUE THREAD

**Issue by Tranberry** [HearthSim/Hearthstone-Deck-Tracker#2981]
Opening HDT and getting the release notes/update notes do not say 'download/update here' or 'update done' anywhere I can spot.

Am I blind or just stupid?

**Comment by jleclanche** [comment]
HDT updates in the background by default. If you're seeing release notes, the update's already happened.

**Comment by Tranberry** [comment]
I'm going to be bold and reword my Issue:

Feature request: Add notable text that tell the user that the program is auto updating in the background.

**Comment by jleclanche** [comment]
Do you mean that it's not made obvious enough that HDT has been updated when you see the release notes?

**Comment by jleclanche** [comment]
If that's the case we can probably stuff in an "HDT has been updated to x.y.z" somewhere but I thought we did that already.

**Comment by Tranberry** [comment]
I'm saying that I looked for that and didn't see it, but I'm used to programs that doesn't do what you think it would.
