### ISSUE TITLE
Show how many Jade Idols are in the deck

### ISSUE THREAD

**Issue by garyking** [HearthSim/Hearthstone-Deck-Tracker#2986]
Similar to how playing Elise shows that the Map or Golden Monkey are in the deck, playing Jade Idol and shuffling 3 copies into the deck should show that the deck has 3 copies.

Sometimes in a fatigue game, I shuffle 3 or 6 or even more copies into the deck, and I'd hate to draw the last copy, not knowing that it's the last, and playing it rather than re-shuffling 3 copies back into the deck.

**Comment by edasaki** [comment]
+1 pretty significant thing to keep track of, hope it's added soon!

**Comment by azeier** [comment]
Should be pretty easy to add.

**Comment by samcoy3** [comment]
+1 this is important functionality and presumably easy to implement

**Comment by garyking** [comment]
@azeier does it perhaps also make sense to add a counter for the next Jade Golem size, for both the player and opponent? Similar to the C'Thun tracker, where it only appears for the player if they have a Jade card in their deck, or for the opponent when they play a Jade card.

**Comment by speedytr** [comment]
yes these counters will be great

**Comment by Marzeke** [comment]
The tracker adds extra Jade Idols, but the moment you draw one, it goes back to showing just one more in the deck
