### ISSUE TITLE
"Hidden Cache" secret not greying out

### ISSUE THREAD

**Issue by garyking** [HearthSim/Hearthstone-Deck-Tracker#2987]
If the opponent is Hunter and plays a secret, then after I play a minion, "Hidden Cache" should grey out from the list of secrets.

**Comment by azeier** [comment]
Yes, this is listed as a known issue in the update notes.

We do not always know whether the opponent has a minion in hand, and figuring it out (as far as possible) probably requires extensive logic.

Not sure what to do about it yet.  @judge2020 Suggested some indicator for "possibly grayed out".

**Comment by garyking** [comment]
So the secret will not activate if the opponent does not have any minions in their hand after I play a minion, so it becomes difficult to determine if the secret did not activate because it's not Hidden Cache, or if the opponent simply does not have a minion in hand? Ah, okay.

**Comment by judge2020** [comment]
fixed in #3131

**Comment by mmiat** [comment]
i still have this issue

**Comment by riQQ** [comment]
Hidden Cache can only be greyed out if your opponent plays a minion, that was in his hand when you played a minion.
