### ISSUE TITLE
[MAC] Cannot switch back to regular theme (with full card images)

### ISSUE THREAD

**Issue by mo-kaya** [HearthSim/Hearthstone-Deck-Tracker#2988]
Hi,

After the latest 11-30 update, the theme has changed to minimal. Want to revert back to regular theme but can't do it on Mac. Any help appreciated. Thanks.

![screen shot 2016-12-02 at 01 55 07](https://cloud.githubusercontent.com/assets/23221158/20825522/955f0358-b832-11e6-82ec-11583e820ed9.png)

**Comment by riQQ** [comment]
This is a HSTracker isssue. Post there: https://github.com/HearthSim/HSTracker.

**Comment by azeier** [comment]
Issue moved to [HearthSim/HSTracker #689](https://github.com/HearthSim/HSTracker/issues/689) via [**ZenHub**](https://www.zenhub.com/)
