### ISSUE TITLE
Deck screenshot crashes HDT

### ISSUE THREAD

**Issue by madperso** [HearthSim/Hearthstone-Deck-Tracker#2989]
So, I'm running into a really weird problem.  While trying to send a Screenshot with info, my deck tracker kept crashing because it cannot find the path to the folder entitled "Bars".  After doing some research, I found the folder in my AppData folder and found that every I boot up the Tracker, the folder gets deleted from the location.

**Comment by azeier** [comment]
This is fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/94ea5e34ad79181c267f9dc79e444f68479971d7. There should be a new release fairly soon.

**Comment by azeier** [comment]
Fixed with v1.1.3
