### ISSUE TITLE
HDT doesn't recognize several MSG cards, currently freezing potion.  causes it to crash.

### ISSUE THREAD

**Issue by Radiohawk58** [HearthSim/Hearthstone-Deck-Tracker#2991]

**Comment by xrandalxflagg** [comment]
Same here. Mine does not recognize any mtg cards. no crashing though

**Comment by judge2020** [comment]
Are you on the latest version 1.1.2? All of the Mean streets cards were added a day ago.

**Comment by xrandalxflagg** [comment]
yeah when I make a deck they are there but when it tracks things is says they are not in the deck

**Comment by Radiohawk58** [comment]
I'm on 1.1.2 as well, cards show up in the app, but when I play a game it says card not found and reverts to only showing cards drawn - crashes intermittently after.

**Comment by azeier** [comment]
Could you guys upload logs for games where that happens?
https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by Radiohawk58** [comment]
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/628953/hdt_log.txt)

**Comment by Radiohawk58** [comment]
Nothing shows up recently under crash reports, however, I experience often "...Has encountered a problem" Windows box, with the options below of either close the program now or wait for it to open.  I'll try and find something in Windows files.

**Comment by judge2020** [comment]
That's also extremely weird, an HDT crash should be handled by the custom stacktrace box which also allows you to submit errors

**Comment by Radiohawk58** [comment]
Sry, finding events in Windows event viewer is apparently way above my level of training in Windows 10.  Can't seem to get it to sort correctly.  Is there maybe a video somewhere I might view to accomplish that?  I know a streamer or 2 that have had similar issues, they just reboot app and move on.  But I'm sure you'd like the bug fixed :).

**Comment by azeier** [comment]
Could you upload your `PlayerDecks.xml` file? It's in the same directory as the "Logs" folder.

**Comment by Radiohawk58** [comment]
http://pastebin.com/SrUPqrYE

**Comment by azeier** [comment]
That doesn't look right. Can you zip and upload the file? e.g. http://zippyshare.com - you might be able to just attack it here, too/

**Comment by Radiohawk58** [comment]
wouldn't let me, github said we don't support that file type (.xml)

**Comment by Radiohawk58** [comment]
http://www94.zippyshare.com/v/kEFFTvMC/file.html

**Comment by Radiohawk58** [comment]
Log Name:      Application
Source:        .NET Runtime
Date:          11/23/2016 12:54:34 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-K50DVCR
Description:
Application: HearthstoneDeckTracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OutOfMemoryException
   at Hearthstone_Deck_Tracker.LogReader.LogReader.ReadLogFile()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-11-23T20:54:34.048046800Z" />
    <EventRecordID>12665</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-K50DVCR</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: HearthstoneDeckTracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OutOfMemoryException
   at Hearthstone_Deck_Tracker.LogReader.LogReader.ReadLogFile()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

</Data>
  </EventData>
</Event>

**Comment by Radiohawk58** [comment]
oops, sorry!  meant to use zippy for that.

**Comment by azeier** [comment]
Yeah that out of memory crash is a known issue I still don't know how to fix (or why it happens) :(

As for the importing/selection issue, give this build a try please: https://github.com/azeier/HDT-Test/releases/download/v1.1.2.3/Hearthstone.Deck.Tracker-v1.1.2.3.zip

It looks like the deck you are having issues with only contains 29 cards and HDT has a bug (which I hopefully just fixed :)), where it doesn't detect the difference in decks "that way around".

**Comment by Radiohawk58** [comment]
it contains 30 or Hearthstone would not let me play it :), just HDT didn't recognize it.
I'll try the new build, thx very much.

**Comment by azeier** [comment]
I meant HDT only has 29 cards for the deck, somewhere one got lost.

**Comment by Radiohawk58** [comment]
Sry, was feable attempt @ comic relief.  Downloaded file, can you refresh my memory on how to replace properly?

**Comment by azeier** [comment]
You can just unzip it anywhere and run the exe. No need your current installation.

**Comment by Radiohawk58** [comment]
i did that, and it created a folder within my downloads file "hearthstone.deck.tracker-v1.1.2.3", and when i dbl click on the exe file to open it opens 1.1.2 instead.

**Comment by azeier** [comment]
The splash screen always just shows the first 3 digits. I think the full version number is only ever printed in the log. Or you can check the exe > properties > details too.

**Comment by Radiohawk58** [comment]
okay, so just use it for a while and report back if there are further hangs/crashes etc.?

**Comment by azeier** [comment]
That version should mainly fix HDT not recognizing cards (not properly importing decks). Let me know if you still notice that, e.g. with your druid deck.

**Comment by xrandalxflagg** [comment]
thanks for pointing me here, i just reinstalled and it seems to be fixed.

**Comment by azeier** [comment]
@xrandalxflagg That's with the release I linked above?

**Comment by Radiohawk58** [comment]
still not showing "Virmen Sensei" for me. (only 29 cards in deck)

**Comment by azeier** [comment]
@Radiohawk58 can you post the logs since you launched 1.1.2.3 for the first time?

**Comment by Radiohawk58** [comment]
Odd, I manually edited the deck within HDT, and is now working (showing and registering) w/it in the deck

**Comment by Radiohawk58** [comment]
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/629040/hdt_log.txt)

**Comment by azeier** [comment]
Did you by any chance start HDT mid-game before you manually fixed it? It looks like it auto imported 2 other decks just fine now.

**Comment by Radiohawk58** [comment]
i didn't start midgame, but i did edit deck midgame.  When i launched HDT i didn't look for the card, but when the game started opening hand included Virmen Sensei and HDT didn't have it  so i tried to manually add it and it worked :)

**Comment by psychomax13** [comment]
1.1.2.3 seems fixed. now it works for me as well. before that, it wouldn't recognize the decks

**Comment by xrandalxflagg** [comment]
i am having the same problem with the new build. going to reboot then relaunch the new build, maybe something was up with the old version being active.

**Comment by azeier** [comment]
@xrandalxflagg have you tried logging out of hearthstats? That seems to have helped in #2992

**Comment by azeier** [comment]
Should be fixed with v1.1.3

**Comment by Heelythegreat** [comment]
I'm still having the issue...

**Comment by azeier** [comment]
@Heelythegreat are you logged in to hearthstats?

**Comment by Heelythegreat** [comment]
@azeier 

Uh. So, a week ago, I wasn't and had the issue. I read somewhere that I should login to HS.

I did, and it worked for a lil while then stopped working. Yeah, I was and I logged out and now it doesn't do it anymore. All good.

Do you know if Hearthstats plans on ever updating or is that just done with?

**Comment by jleclanche** [comment]
Hearthstats is essentially dead and unmaintained. I doubt it'll change.

**Comment by judge2020** [comment]
Hearthstats has been removed, and MSOG cards no doubt work.
