### ISSUE TITLE
auto-imported deck versions don't show up in webclient 

### ISSUE THREAD

**Issue by EvaLok** [HearthSim/Hearthstone-Deck-Tracker#2994]
auto-importing a deck (using the auto-import option, eg: modifying a deck in the hearthstone client and then going to the play screen) increments the version in the local client but that version does not show up in the web client

**Comment by azeier** [comment]
By web client you mean HearthStats? That is not going to be fixed, as HearthStats is no longer maintained. We are slowly deprecating the integration and are going to be working on a better replacement system soon.

**Comment by EvaLok** [comment]
Yes I was referring to HearthStats.. does this mean that the data is still pushed to a database but HearthStats doesn't display it properly, or that it's not being pushed to a database at all when this bug occurs? Somewhat related, will you be moving the match data over into the new system, or will it all be lost / can we export it ourselves to import into the new system?

**Comment by azeier** [comment]
The auto importing from Hearthstone is a rather new feature that does not have the HearthStats logic as part of it. That said, if you have all the auto uploading for it enabled, decks/versions should still be uploaded as soon as you play (upload) the first match with them.

We will try to move all data as complete as possible. Anything that's stored locally in HDT should be no problem.
