### ISSUE TITLE
Jade Golem size counter

### ISSUE THREAD

**Issue by s0urc3d3v3l0pm3nt** [HearthSim/Hearthstone-Deck-Tracker#2995]
A jade golem counter like the one for c'thun would be very useful.

**Comment by disshishkov** [comment]
hm, it's  built in game feature already. When you hover to card it says: "summon x/x jade golem" where **x** is your counter

**Comment by HoopyHobo** [comment]
Still seems useful if you're playing AGAINST a Jade Golem deck.

**Comment by s0urc3d3v3l0pm3nt** [comment]
@disshishkov I requires you to have a Jade card in your hand; however, which means if you are running a deck with few Jade cards the card text is not very useful

**Comment by Jasel95** [comment]
I just posted a similar request, so though I agree with @s0urc3d3v3l0pm3nt that this feature would be useful, I apologize for the repetition and hope that my post doesn't seem tedious to those whom might read it after already seeing this one.

**Comment by judge2020** [comment]
Has been implemented with #3037
