### ISSUE TITLE
Can't see MSG cards, can't update client.

### ISSUE THREAD

**Issue by LeeOh21** [HearthSim/Hearthstone-Deck-Tracker#2997]
I skipped the update because I was playing something else and the HDT icon was on top of everything, now MSG cards are displayed as "NOOOOOOOOO" and I can't get the program to update. I tried uninstalling, deleting Appdata, and downloading HDT again, but every time I open it I always see my decks and the same problem with the MSG cards. Any way to update or to make a hard reset? I don't have a problem losing my stats.

Cheers,

**Comment by azeier** [comment]
Cards there were not found with the pre-update version will always be "NOOO...". Try just importing the decks again with the latest version installed.

**Comment by LeeOh21** [comment]
Ok, I got it. Importing the decks again fixed it. Thank you!

**Comment by azeier** [comment]
Perfect :).
