### ISSUE TITLE
tracker unable to see new cards and then takes them out of the deck after

### ISSUE THREAD

**Issue by xrandalxflagg** [HearthSim/Hearthstone-Deck-Tracker#2999]
So my tracker is being strange. It is updated to the latest.

I can import any deck that includes the new cards or create one. I play 1 match and even though it shows the cards on the deck list to the right of the overlay, it states "warning cards not found in deck." Then, when I look back at the deck in the tracker it is there but short the new cards. 
This morning the new cards are gone from the saved deck. I have included a file from last night and today.
thank you.
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/629021/hdt_log.txt)

[hdt_log_1480736911.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/629019/hdt_log_1480736911.txt)

**Comment by azeier** [comment]
#2991
