### ISSUE TITLE
Deck Tracker Not working at all

### ISSUE THREAD

**Issue by KuriousG** [HearthSim/Hearthstone-Deck-Tracker#3002]
Hi,

So i was using the previous version of the tracker for a long while and everything worked fine. Every time I tried to automatically update it would fail and request that I do it manually. I've honestly been super lazy about it and said when the expansion came out I'd update. I downloaded the new exe file and ran it. It kept crashing so I uninstalled all HSDT files from my computer. I than reinstalled and now after I launch the program it says it has uneven permissions (yes, it is being ran in admin mode), loads a random deck list and than doesn't change when I play, draw, or discard cards. All help is appreciated.

Thanks!

**Comment by azeier** [comment]
See #2738.
