### ISSUE TITLE
Turn Timer

### ISSUE THREAD

**Issue by Grimfyre** [HearthSim/Hearthstone-Deck-Tracker#3003]
Hello,

I just installed HDT to help me remember what cards are left in my deck. However there is a turn timer near the "end" turn button that is annoying.

I've checked the options on the HDT program and cant find a setting to toggle it off. Furthermore I did find old posts showing where the "timer" setting is....however the program doesn't even look like that anymore.

Anyone know how to toggle the timer off and on? Thanks!

**Comment by riQQ** [comment]
There's a search option in the options. Search for `timer` or go directly to `Options > Overlay > General > Hide timers`.
