### ISSUE TITLE
HDT crashing on install/startup

### ISSUE THREAD

**Issue by Helper45** [HearthSim/Hearthstone-Deck-Tracker#3007]
I tried to install HDT but it keeps giving me "The type initalizer for 'System.Net.ServicePointManager' threw an exception
[SquirrelSetup.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/629714/SquirrelSetup.txt)

**Comment by azeier** [comment]
This sounds like an issue with the .NET Framework installation. Try reinstalling it.

**Comment by judge2020** [comment]
Have you installed HDT successfully since this? @Helper45
