### ISSUE TITLE
Deck Tracker does not counts in-hand buffs for C'Thun

### ISSUE THREAD

**Issue by ThePlayer14** [HearthSim/Hearthstone-Deck-Tracker#3008]
Although it may not be an issue, but I noticed that the C'Thun Counter only counts Cultist buffs, but not Smuggler buffs. and I guess it should count in-hand buffs seperately or merged with Cultist buffs.

**Comment by azeier** [comment]
HDT is not actually counting/calculating any C'Thun stats, but rather just printing what Hearthstone is counting. So this is likely not something that can be fixed.

That said, I don't think it's necessary to count in-hand buffs to C'Thun at all:
- If C'Thun gets buffed in the opponent hand we have no way of if it was actually C'Thun that was buffed, let alone by how much without logic for each card that does so (the game does not expose buff values, just that things are buffed). 
- If C'Thun get's buffed in the player hand you can just look at the card itself to see the stats, no need for the counter.
