### ISSUE TITLE
Shuffled jade idol should work like forgotton torch?

### ISSUE THREAD

**Issue by wsfung** [HearthSim/Hearthstone-Deck-Tracker#3010]
I thought the deck tracker would show the jade idols that are shuffled in my deck similar to how forgotton torch works but it doesnt seem to be the case(or may be I have to change my setting?)

Also is there a plan of adding a jade idol size counter(showing how big the next jade idol is for both sides) like the cthun buff and yogg spell counters?

**Comment by azeier** [comment]
Are you on v1.1.4? It should be working with that build.
If not please upload a log of a game where it doesn't - see here https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues.

Jade Counter: https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2995
