### ISSUE TITLE
The storm guardian

### ISSUE THREAD

**Issue by Laastwish** [HearthSim/Hearthstone-Deck-Tracker#3012]
shaman 5 mana 5/5 deathrattle minion doesn't show when shuffled into the deck

**Comment by azeier** [comment]
Can you get me a log of that? It should be working with v1.1.4.
See here for how to get the log: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by azeier** [comment]
Nvm. Found the problem.

**Comment by judge2020** [comment]
fixed in #3030
