### ISSUE TITLE
HearthPwn import not working anymore

### ISSUE THREAD

**Issue by ADarkHero** [HearthSim/Hearthstone-Deck-Tracker#3014]
Hi, since the last update (1.1.4) I'm not able to import decks from hearthpwn anymore. Other sites like TempoStorm seem to work tho. 

Here some Screenshots:
https://i.imgur.com/UG6Y2Sr.png
https://i.imgur.com/7pWcdJc.png

**Comment by azeier** [comment]
Importing from That url works fine for me. Maybe a temp. connection problem?

**Comment by judge2020** [comment]
What region are you in? Someone else working with hearthpwn importing said it didn't work from the EU but worked from U.S.

However, @azeier is EU too so that doesn't make much sense.

**Comment by azeier** [comment]
Closing this for now. It doesn't seem to be a very wide spread problem and I'm not sure we can do much about it.
