### ISSUE TITLE
Deck resetting

### ISSUE THREAD

**Issue by kingdru** [HearthSim/Hearthstone-Deck-Tracker#3019]
Whenever I use this list : http://www.hearthpwn.com/decks/695796-s33-justsaiyans-legend-top-1-jade-druid-mean 

after I draw a jade behemoth the entire list deletes all the jade cards in the deck.

**Comment by azeier** [comment]
Maybe #2992?

**Comment by judge2020** [comment]
Also make sure you are on the latest version of HDT.

**Comment by rebreanu** [comment]
same problem here, I have latest version

**Comment by judge2020** [comment]
Seems to have been fixed ![img](https://judge2020.me/oO7x6Y.png)
