### ISSUE TITLE
Show full card images in the tooltips

### ISSUE THREAD

**Issue by anonymous555** [HearthSim/Hearthstone-Deck-Tracker#302]
I've got a patch working that shows full card images in tooltips, below existing text.  Let me know if you want it.
![hs_full_images](https://cloud.githubusercontent.com/assets/8370128/4331515/6db82938-3fc6-11e4-9699-5692975da74e.png)

**Comment by Jup200** [comment]
It would be great show full card in the tooltip ...and/or to "simplified" tooltip add rarity of the card (common, rare, epic)

**Comment by Cu8eR** [comment]
@Epix37 - could you please add this?

**Comment by beheh** [comment]
This was completed back in #4213.
