### ISSUE TITLE
Level filter in stats disappeared in 1.1.4

### ISSUE THREAD

**Issue by DerfelKadarn** [HearthSim/Hearthstone-Deck-Tracker#3020]
Since the update to 1.1.4 I can't see the filter by level on the stats screen. See screenshot. Now there is a filter by Turns instead?

<img width="183" alt="screenshot 2016-12-09 17 55 00" src="https://cloud.githubusercontent.com/assets/9398286/21067373/ca7bdc94-be38-11e6-929a-a3924bb85eb2.png">

**Comment by azeier** [comment]
Do you mean rank? Switch the mode to 'Ranked' and you should see it.

**Comment by DerfelKadarn** [comment]
Thanks, makes sense. Closing
