### ISSUE TITLE
HDT opens but doesn't work

### ISSUE THREAD

**Issue by Demonsuji** [HearthSim/Hearthstone-Deck-Tracker#3021]
I have gotten the uneven permissions message, ran HDT and Hearth as admin, as well as both run as admin individually.  Downloading an older version and updating again after a complete uninstall and deleting all files, and running as admin and in compatibility mode for windows 8(i'm on Win10) allowed it to work for exactly 1 game, it now often gets stuck on no-deck and doesn't even keep track of cards played or possible secrets or anything(the overlay is visible, just not doing anything).  When I'm able to force it to use a deck on occasion, it doesn't keep track of what cards have been played or the stats for wins/losses.  This has become a very annoying problem over the past week and I hope someone can help.  :(

**Comment by azeier** [comment]
See #2738. We sadly don't really know what the problem is :/.
