### ISSUE TITLE
[Feature Request] Show attack and defense stat of next Jade Golem summoned (for either opponent's side)

### ISSUE THREAD

**Issue by Jasel95** [HearthSim/Hearthstone-Deck-Tracker#3022]
I don't know how feasible this is, but I know it would be really helpful to me both as a player playing with and against Jade Golem decks to be aware of the stats of the next (or last and simply do the math myself) Jade Golem summoned on each side of the field. I would hope this would end up as some sort of counter, similar to how C'thun's stats and Yogg or Arcane Giant's spell counts are tracked. Gives me an idea of whether another Jade Golem will make any immediate impact on the board or not (this would be useful in situations such as trying to determine whether I should spend my turn fishing through my deck to find these cards or simply use the ones in my hand). If there is no Jade Golem summoning card in hand (and/or a deathrattle summoning Jade card on the field), then I am stuck hoping that I remember what the last summoned Jade Golem's stats were. Thank you very much already for everything you've done and for taking the time to read my request. I apologize if it was too long or not appropriate; I've never sent one of these before. Thanks, again.

**Comment by Jasel95** [comment]
A similar post was already made by @s0urc3d3v3l0pm3nt , so I would simply like to give him credit for his suggestion and apologize if anyone finds my request unnecessary/annoying. Thank you for your time.

**Comment by azeier** [comment]
No worries :). Closing in favor of #2995 though.
