### ISSUE TITLE
Can't turn off some things on the tracker that I don't want to see

### ISSUE THREAD

**Issue by SantonGames** [HearthSim/Hearthstone-Deck-Tracker#3023]
I downloaded HDT recently because I am trying to use it to have a decklist on my stream but I do not want the turn timer or the numbers over my opponents card or anything else other than the deck list showing. I have tried basically unchecking nearly every option in the settings and I still can't get these two to go away. Am I missing something?

**Comment by judge2020** [comment]
The setting for this would be in **Overlay -> General**

![image](http://i.imgur.com/gSe5soQ.png)

you'll want some of these checked, as checking them turns the features off.
