### ISSUE TITLE
Problem on 4k monitor

### ISSUE THREAD

**Issue by HACKHERS** [HearthSim/Hearthstone-Deck-Tracker#3024]
Hey, I quick looked setting but I can't found something like size. I can't even see the cards on 4k monitor they are so small. So maybe advanced options for ratio could help if there isn't any.

**Comment by riQQ** [comment]
The is a scaling option for the overlay (`Options > Overlay> Player / Opponent`).

**Comment by HACKHERS** [comment]
Oh sorry, I see now but it could be more %200 not perfectly enough maybe %250 ?

**Comment by azeier** [comment]
You can edit these two values in the `%AppData%/HearthstoneDeckTracker/config.xml` to set it higher than 200: 
```
  <OverlayOpponentScaling>100</OverlayOpponentScaling>
  <OverlayPlayerScaling>100</OverlayPlayerScaling>
```

Make sure to close HDT before editing it.
