### ISSUE TITLE
Is there any way to reset everything?

### ISSUE THREAD

**Issue by exoticmonkey02** [HearthSim/Hearthstone-Deck-Tracker#3025]
I messed with some of my settings a little too much, and was wondering if there's any way to start over with a clean slate. I tried uninstalling and reinstalling, and that didn't work, so I came here. Any help is greatly appreciated! :D

**Comment by riQQ** [comment]
The is a scaling option for the overlay (`Options > Overlay> Player / Opponent`).

**Comment by HACKHERS** [comment]
Oh sorry, I see now but it could be more %200 not perfectly enough maybe %250 ?

**Comment by ViezeVingertjes** [comment]
You can also delete the .xml files related to statistics, it will be as good as new. This is the way i've done it and it works like a charm. (They can be found in the appdata directory)

**Comment by judge2020** [comment]
A fix has been posted, you can delete the `%AppData%\HearthstoneDeckTracker` folder.
