### ISSUE TITLE
Cannot claim hsreplay.net account

### ISSUE THREAD

**Issue by osoviejo** [HearthSim/Hearthstone-Deck-Tracker#3026]
I'm logged into hsreplay.net under my battle tag--the same Blizzard account that I play under with HDT.  When I launch HDT 1.1.4 (which otherwise works fine in all respects), the HDT error panel reports:

"Error retrieving HSReplay account status" and "Webrequest to obtain upload-token failed."

The first part is probably okay, since I haven't claimed my account via HDT.  So, I go into Options/Tracker/Replays and see "Account Status: Anonymous."  When I click on "CLAIM ACCOUNT," the HDT error panel reports:

"Error claiming account" and "Webrequest to obtain upload-token failed."

Looking at the log, there is the token creation error (can provide more, but this appears to be the crux of the issue):

```
3:26:41 AM|Info|Core.Initialize >> HDT: 1.1.4.0, Operating System: Windows Server 2012 R2 Datacenter 9600, .NET Framework: 394271
3:26:41 AM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
3:26:42 AM|Info|ThemeManager.LoadThemes >> Found theme: classic
3:26:42 AM|Info|ThemeManager.LoadThemes >> Found theme: dark
3:26:42 AM|Info|ThemeManager.LoadThemes >> Found theme: frost
3:26:42 AM|Info|ThemeManager.LoadThemes >> Found theme: minimal
3:26:42 AM|Info|GameV2.Reset >> -------- Reset ---------
3:26:42 AM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
3:26:44 AM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
3:26:46 AM|Info|MainWindow.SelectDeck >> Switched to deck: Warrior.03 (v1.0)
3:26:46 AM|Warning|LogReaderManager.Stop >> LogReaders could not be stopped, stop already in progress.
3:26:46 AM|Info|GameV2.Reset >> -------- Reset ---------
3:26:46 AM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
3:26:47 AM|Info|BackupManager.Run >> Running BackupManager
3:26:47 AM|Info|BackupManager.Run >> Backup for today already exists
3:26:47 AM|Info|PluginManager.LoadPlugins >> Loading Plugins...
3:26:47 AM|Info|GitHub.CheckForUpdate >> HearthSim/Hearthstone-Deck-Tracker: Checking for updates (current=1.1.4.0, pre-release=False)
3:26:48 AM|Info|ApiWrapper.UpdateAccountStatus >> Checking account status...
3:26:48 AM|Info|ApiWrapper.GetUploadToken >> Requesting new upload token...
3:26:48 AM|Info|GitHub.CheckForUpdate >> HearthSim/Hearthstone-Deck-Tracker: We are up-to-date (latest=v1.1.4, pre-release=False)
3:26:48 AM|Error|ApiWrapper.GetUploadToken >> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
```

.NET Framework 4.6.1.  I have no issue making SSL/TLS connections from the browser, I'm running with Administrator privileges, and no events were logged.  Thanks!

**Comment by azeier** [comment]
Hard to tell what this could be. Are you going through a proxy/vpn?

**Comment by osoviejo** [comment]
No, direct connection.  Have no connectivity issues.  Is there anything I can do to get more detail of the failure on my end?  Could this be tested outside the app using curl or some such?

**Comment by jleclanche** [comment]
It might be related to TLS configuration on your machine. It's also possible you're legitimately being MITM'd and it's being caught. The former seems more likely... but it wouldnt necessarily be reproducible with curl, it could be specific to c#.

**Comment by osoviejo** [comment]
Ran an SSL Labs browser test that shows TLS 1.2 is enabled and working (all flavors of SSL are disabled).  Anything in particular I should look at regarding TLS configuration?

**Comment by judge2020** [comment]
Still an issue @osoviejo?

**Comment by osoviejo** [comment]
Yes, still an issue.  I'm back on my Win 8.1 machine, and it's behaving the same way.  Tried flushing all things HDT, and reinstalling to no avail.

**Comment by riQQ** [comment]
Still an issue after the fix @osoviejo?

**Comment by osoviejo** [comment]
Still an issue.  It’s been my intent for some time to debug this on my machine, I just haven’t had a chance to get to it yet, and haven’t played much lately either.  Still intend (driven mostly by curiosity), just not sure when.

**Comment by jleclanche** [comment]
Closing, I don't think there's anything we can do about this.

For those landing here through Google, here is how to claim your account on HSReplay.net:

https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#claim-account
