### ISSUE TITLE
Unable to create a new deck

### ISSUE THREAD

**Issue by Drewbee01** [HearthSim/Hearthstone-Deck-Tracker#3028]
Whenever I try to manually create a new deck it is unable to be saved
I first noticed this bug after I updated to MSG and I have all the updates so far

**Comment by judge2020** [comment]
What is the error message? Can you provide HDT logs if possible? [Instructions](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#hdt-log-files)

**Comment by Drewbee01** [comment]
I am able to create the deck but whenever i try to save the deck the save button doesn't work
No error message pops up, instead when I click the save button it just doesn't save.

**Comment by judge2020** [comment]
Please provide the HDT logs. You can find the HDT logs by looking [here](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#hdt-log-files).
