### ISSUE TITLE
Deck Tracker is crashing after every game.

### ISSUE THREAD

**Issue by tknights2015** [HearthSim/Hearthstone-Deck-Tracker#3029]
Deck Tracker is crashing after every game.
Error message:  Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	HearthstoneDeckTracker.exe
  Application Version:	1.1.4.0
  Application Timestamp:	5843ec33
  Fault Module Name:	MSVCR120_CLR0400.dll
  Fault Module Version:	12.0.52512.0
  Fault Module Timestamp:	5525ef9d
  Exception Code:	c00000fd
  Exception Offset:	0006bf20
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	f0db
  Additional Information 2:	f0db75c9e4d3eb9dcaf334f0ed04d076
  Additional Information 3:	a7bd
  Additional Information 4:	a7bd9d3c56a1e20895e6bdb2e3358545

[hdt_log_1481767426.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/653611/hdt_log_1481767426.txt)

**Comment by riQQ** [comment]
Is there a corresponding event with source `.NET Runtime` in the windows logs?

**Comment by azeier** [comment]
Yeah this looks like the same issue we are getting every now and again. 

Does this happen with a completely clean install of HDT?
- Close HDT
- Go to `%AppData%` and rename the `HearthstoneDeckTracker` folder
- Download and run [the latest version](https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/download/v1.1.4/Hearthstone.Deck.Tracker-v1.1.4.zip)
- Don't change any settings or install any plugins

**Comment by tknights2015** [comment]
The clean install seems to have fixed this as of now.
