### ISSUE TITLE
White-Eyes Still not tracking correctly

### ISSUE THREAD

**Issue by onixalmighty** [HearthSim/Hearthstone-Deck-Tracker#3030]
I'm still not getting the image of the storm defender to show up in my deck after white eyes dies in-game.

**Comment by azeier** [comment]
https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3012

The next update will fix it.

**Comment by onixalmighty** [comment]
Awesome, thanks. Is there any chance you're working on a Jade Idol tracker?
Or a game tracker that lets you track winrates over types of decks; for
example, I'm playing a shaman thats 6-0 over highlander warlock but 0-2
against OTK warlock, and I'd like to be able to track those separately.

**Comment by azeier** [comment]
Not me personally, but that is being worked on, yes! :)

**Comment by onixalmighty** [comment]
Manic Soulcaster isn't tracking correctly.

**Comment by azeier** [comment]
Will also be fixed with the next update.
