### ISSUE TITLE
[BUG] HDT lost cards in deck!

### ISSUE THREAD

**Issue by chip83** [HearthSim/Hearthstone-Deck-Tracker#3031]
HDT lost card when restarted. I see my deck to 18 cards (over 30) when i restart HDT.
I have tried to unistall HDT, make a clean with ccleaner and re-install, but with no result.
Any suggestion?

Thanks.

**Comment by azeier** [comment]
Are you logged in to hearthstats?

**Comment by chip83** [comment]
yes

**Comment by judge2020** [comment]
This may be because it detects those 18 cards in your deck when you press play in-game.

**Comment by azeier** [comment]
HearthStats is not update for MSG and deck syncing will break your decks. Logging out should fix your issue.

**Comment by chip83** [comment]
Thanks, I try.

**Comment by azeier** [comment]
No you should not log in again, HearthStats is pretty broken right now.

**Comment by chip83** [comment]
any news for when HearthStats work again?

**Comment by judge2020** [comment]
@chip83 Hearthstats likely won't be coming back, as it is not actively being developed and Mean Streets cards haven't been added in yet.

**Comment by judge2020** [comment]
Closed in favor of #3235

**Comment by judge2020** [comment]
duplicate of #3235
