### ISSUE TITLE
All my games history, stats and decks erased

### ISSUE THREAD

**Issue by MaximeDonut** [HearthSim/Hearthstone-Deck-Tracker#3033]
I have opened my tracker today and found that everything disappeared.  All stats since almost 2 years of play are gone.

Here is my log.
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/658878/hdt_log.txt)

**Comment by azeier** [comment]
See if there are any backups you can restore under `options (advanced) > tracker > backups`.

**Comment by MaximeDonut** [comment]
Thank I did, but lost a day worth of stats. Still better than nothing :)

**Comment by azeier** [comment]
That's something :). Sorry about the day.
