### ISSUE TITLE
Start Launcher / Hearthstone doesn't work

### ISSUE THREAD

**Issue by yechotest** [HearthSim/Hearthstone-Deck-Tracker#3036]
Hi,

When i launch HS Deck tracker, and wanna start Hearthstone automatically, a message appears saying that i need an application to start battlenet and a square to tick-off which is written "always use this application" and no software below it (when i click on a random spot, the message disappear and HS doesn't launch).

Here's the message i receive on the debug window : "PM|Debug|XmlManager.Save >> File saved: C:\Users\Utilisateur\AppData\Roaming\HearthstoneDeckTracker\config.xml"

What can i do to solve this problem, and start Hearthstone automatically when i start HS Deck Tracker.

Thank you for advance.

PS : I'm using the ver. 1.1.4

**Comment by azeier** [comment]
The most likely fix will be reinstalling Hearthstone and/or the Battle.net launcher.

Note: you do not need to launch Hearthstone though HDT. Launching it normally works just fine.

**Comment by yechotest** [comment]
Thank you for the answer.

I knew that i can launch both separately. I'm just too lazy and wanna automate and save time. 

Will try reinstalling both.

**Comment by judge2020** [comment]
Are you still having this problem?
