### ISSUE TITLE
Gadgetzan Cards do not appear for me

### ISSUE THREAD

**Issue by ppncosta** [HearthSim/Hearthstone-Deck-Tracker#3041]
Instead of the actual cards, it appears as NOOOOOOOOOOO. and I can't select the cards I want mannualy

**Comment by gyrodrill** [comment]
Maybe you need to update to the latest version from releases page?
[https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases](url)

**Comment by phixius1** [comment]
I have the same problem (downloaded the lastest version)
![problem](https://cloud.githubusercontent.com/assets/24706776/21410674/87e06b12-c7b0-11e6-8b7c-9899075845a2.jpg)

**Comment by azeier** [comment]
Please post logs of an HDT session where decks with this problem are imported.
https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by judge2020** [comment]
Are you still having these issues?
