### ISSUE TITLE
Jade Golem Couner

### ISSUE THREAD

**Issue by Marzeke** [HearthSim/Hearthstone-Deck-Tracker#3042]
The counter doesn't increase from 1/1

**Comment by emeraldskies** [comment]
![hearthstone screenshot 12-22-16 08 06 07](https://cloud.githubusercontent.com/assets/24718083/21428113/066b2bb2-c81e-11e6-9aab-0a454d3c7c42.png)

Example of Jade Golem Counter bug. The counter appeared when opponent first summoned a golem, but never incremented when further golems were summoned. In image: counter at 1, golem visible with more than 1 health.

**Comment by emeraldskies** [comment]
Sorry - wasn't thinking and used ingame screengrab function instead of a normal screencapture.

**Comment by azeier** [comment]
Will be fixed with the next update.

**Comment by azeier** [comment]
This is now fixed on the installer version of HDT.
