### ISSUE TITLE
Cannot move the jade golem counter

### ISSUE THREAD

**Issue by TemporalOnline** [HearthSim/Hearthstone-Deck-Tracker#3043]
When I try the unlock, the "handle" for the jade golem counter does not appear. Also, I assume you are using only one counter (as only one appear even if I say "never" to one side, and "always" to the other), as only one appears as "1/1" in my lower left  side, and I assume it is "opponent/mine" as opposed to the C'thun counter which is each player's "attack/defense" current C'thun.

**Comment by rrwoods** [comment]
I have no problem with both counters appearing, but I still can't move the counter.

**Comment by tknights2015** [comment]
I can't move the counter either.

**Comment by TheGoblinHero** [comment]
I have only chtun counter appears when I unlock the overlay (even if the jade counter were already displayed). This feature needs attention.

**Comment by azeier** [comment]
The counters are currently tied together. Moving the C'Thun counter will move the Jade counter.
