### ISSUE TITLE
C'Thun counter don't count Grimy Gadgeteer as a buff on C'Thun

### ISSUE THREAD

**Issue by Mousefr** [HearthSim/Hearthstone-Deck-Tracker#3044]
### Expected Behavior
C'Thun counter should display Grimy Gadgeteer buff

### Actual Behavior
C'Thun counter was showing 8 power when C'Thun was at 10 power

### Steps to reproduce behavior
- play Grimy Gadgeteer and he has to buff C'Thun
- Check your C'Thun counter not displaying the correct number

Screenshot from replay:

![buff](https://cloud.githubusercontent.com/assets/24726187/21446003/44c1f47e-c8c1-11e6-89b6-e82f19d903ba.jpg)

**Comment by judge2020** [comment]
Confirmed:

![screenshot](http://i.imgur.com/lUMaREu.jpg)

**Comment by azeier** [comment]
See #3008. Not feasible.
