### ISSUE TITLE
Installation File Not Running

### ISSUE THREAD

**Issue by sseugg** [HearthSim/Hearthstone-Deck-Tracker#3047]
I have used hsdecktracker for about six months now, and it has worked perfectly but just recently it stopped working. I couldn't find out the issue so I decided to uninstall and reinstall but now I can't even install it again. Whenever I run the HDT-Installer file nothing happens. No background processes, no events in the windows application event log. Nothing. I have tried everything I can think of: I have uninstalled any other programs I've installed since I started having issues, I have updated my .NET framework, I have tried running it as a regular user and an administrator (both of those in compatibility mode for service pack 2 and not in compatibility mode) but still nothing happens. One thing I noticed is that when I manually run it as an administrator, it pops up a dialogue box that asks me to run it as a regular user but then nothing after that. Any help would be greatly appreciated

**Comment by judge2020** [comment]
Can you see if there are any files in 'c:\Users\YOURUSER\appdata\local\HearthstoneDeckTracker' or '%appdata%\HearthstoneDeckTracker'? The installer places files there.

Sent from my iPhone

On Dec 24, 2016, at 1:31 PM, sseugg <notifications@github.com<mailto:notifications@github.com>> wrote:


I have used hsdecktracker for about six months now, and it has worked perfectly but just recently it stopped working. I couldn't find out the issue so I decided to uninstall and reinstall but now I can't even install it again. Whenever I run the HDT-Installer file nothing happens. No background processes, no events in the windows application event log. Nothing. I have tried everything I can think of, and have updated my .NET framework, I have tried running it as a regular user and an administrator (both of those in compatibility mode for service pack 2 and not in compatibility mode). One thing I noticed is that when I manually run it as an administrator, it pops up a dialogue box that asks me to run it as a regular user but then nothing after that. Any help would be greatly appreciated

-

**Comment by sseugg** [comment]
@judge2020 I just checked and there is a folder in the location you specified, but it only has three files in it: .dead, SquirrelSetup.log, and Update.exe. I tried running the Update executable but I ran into the same problem as the installation file. No response. What would you recommend doing from here? (also thanks for the help)

**Comment by azeier** [comment]
Could you upload the SquirrelSetup.log file?

**Comment by sseugg** [comment]
This is the entire .txt file:

2016-12-24 12:02:23> Program: Starting Squirrel Updater: 
2016-12-24 12:02:47> Program: Starting Squirrel Updater:

**Comment by azeier** [comment]
Can you try running the installer again and check then check that log?
