### ISSUE TITLE
HDT showing overlay but not tracking

### ISSUE THREAD

**Issue by lexblow** [HearthSim/Hearthstone-Deck-Tracker#3049]
## Before we start
- Please doublecheck there is no existing issue for your problem/feature request.  
- Please delete any obsolete sections (including this one) from this template before submitting your issue.

### Expected Behavior
Describe the expected behavior here

### Actual Behavior
Describe the actual behavior here

### Steps to reproduce behavior
- Step 1
- Step 2

### Log/Screenshots
If applicable, provide a log of the session where the problem occoured.  
See here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by lexblow** [comment]
Installed HDT in a recently formated PC. The os win 7 is on SSD C:\ and hearthstone is under a 1TB SATA HD D:\games\hearthstone. HDT is installed under D:\downloads\. It shows The overlay but does not track, nor import. The game path is already set as described in The help section, and the config.xml is already correct. What should i do next? Please help!

**Comment by lexblow** [comment]
For no reason, it worked after a turn off of the system.

**Comment by riQQ** [comment]
If Hearthstone is already running, when HDT is started for the first time, Hearthstone has to be restarted so that HDT can work.
