### ISSUE TITLE
Stats Missing after Recconect During Game

### ISSUE THREAD

**Issue by Maxamune** [HearthSim/Hearthstone-Deck-Tracker#3050]
## Bug report
Playing Arena or Constructed. Internet has a 1 second disconnect reconnect (Windows 7 Issue). Litteraly 1 second every hour on the hour. But that's not your issue yours is that the deck tracker continues to track fine since it lost nothing that was played etc. However, after the match it simply omits the results from constructed or arena.

### Expected Behavior
To continue to track the game and cards, which it did. To count the game as a win or loss afterwards.

### Actual Behavior
Hearthstone reconnect 1-5seconds. No plays are cards are missed as HS replays the fractional time loss. Tracker continues to work fine. Track the correct cards etc. But! At end of match. The Arena stats are not updated. There's still a recording of the match, just no update result. Also the statics screen shows as if the game was never played either. This happens in constructed too.

**Steps to reproduce behavior**
1 - Have the windows 1 Hour on the Hour Disconnect 1 sec issue.
1a - Or disable adapter in windows setting, and re-enable very quickly in the  Network & Sharing Center (Win 7)
(Note that if you pull your modem and reconnect or similar, that will cause a different problem as Deck Tracker will miss too much. I found disable/enable adapter; rapidly works)
2 - Continue to play the game until the end. As Deck Tracker will continue to work fine.
3 - Check Arena / Constructed stats afterwards to see missing game/stats.

**Log/Screenshots**
If it happens again (10th time). I can get you an twitch recording (OBS) of the event as best I can on this computer.

**Comment by Maxamune** [comment]
Side note. You don't entirely need to fix this issue. It would be nice to at least be able to edit the arena deck stats. So when it does miss a game thru an issue or forgot to turn deck tracker on; that it lets you edit it back to the correct win/loss. So example the run this happened on it said 5-2. Let me edit and correct it to read 6-2 as an option. Barring that. Let it detect the current stat of the deck and go, oh hey, it's at 6-2 not 5-2 that I last saw it at. Then auto update it.

**Comment by judge2020** [comment]
Should be able to edit replay stats
