### ISSUE TITLE
Cannot find "appdata" options in "settings"

### ISSUE THREAD

**Issue by YanTS** [HearthSim/Hearthstone-Deck-Tracker#3055]
## Before we start
There are lots of mentions of "Save data in AppData" option in issues, but I cannot find it.
My HDT installation tells me that it's version is v1.1.5 (under Help). It does not offer me an update.

## Bug report
"AppData" options are searcheable in "Search", but couldn't be found in "Settings"

### Expected Behavior
I expect to see "Save config in AppData" and "Save data in AppData" options under Options > Tracker > Settings (with Advanced options on).

### Actual Behavior
I do not see those options (while I see other green options).
But I can see them after I go to Options > Search > search for "appdata".

### Steps to reproduce behavior
Go to Options > Search > search for "appdata". See 2 search results (for example "[Adv.] Tracker > Settings: Save config in AppData"). Click on the first result. Get jumped to Options > Tracker > Settings, get Advanced options on (if it was off), but cannot see those appdata settings here.

### Log/Screenshots

![image](https://cloud.githubusercontent.com/assets/10176922/21568755/29949c30-cec8-11e6-97eb-15bd83b2e6b7.png)

Actually I was trying to establish full sync between different Win 10 machines. I was almost fine with "just sync one folder via external cloud like Google Drive". But I cannot find a way to get HDT to move-store all the data in installation folder. Is there any current action plan on how to do this.
Also, the issue mentioned here is still an issue - options can be searched, but cannot be accessed.

**Comment by azeier** [comment]
That options only exist in the portable build for technical reasons.

We don't reocmmend using the portable build, but you can download it here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases

We will add a proper syncing system soon, fwiw.
