### ISSUE TITLE
Unit Test "EliteHearthstone" Failing

### ISSUE THREAD

**Issue by Gamic** [HearthSim/Hearthstone-Deck-Tracker#3056]
The EliteHearthstone Unit Test is attempting to pull a deck list from http://www.elitehearthstone.net/deck-7918-patron-warrior/. However, when I run the test no deck list is pulled back from the site. When I try to follow the link I'm taken to a parked hosting page. (The same seems to be true for Google Speed Test on that page). 

Is this just an issue with me, or is the elite hearthstone website no longer available?

**Comment by riQQ** [comment]
It's unavailable for me, too.

**Comment by jleclanche** [comment]
Yeah it's not available. I think we can remove support for it.
