### ISSUE TITLE
Using the old replay viewer

### ISSUE THREAD

**Issue by garyking** [HearthSim/Hearthstone-Deck-Tracker#3066]
Is it possible to use the old replay viewer? The one that's offline rather than the online one? One thing I liked about that one is that each move made was shown as a discrete action, whereas in the new one, it seems like everything is one seamless animation, since there's a scroll bar at the bottom which we can use to scroll through the game.

**Comment by judge2020** [comment]
Yes, it is possible to use the old replay viewer, however you should know it hasn't been maintained for a few months. 

Enable advanced settings -> Tracker -> Replays and enable old replay viewer.

**Comment by jleclanche** [comment]
@garyking arrow up/down will go to previous/next action on HSReplay.net. Does that help?

**Comment by garyking** [comment]
@judge2020 What known bugs are there with the old replay viewer? Or possible bugs that can crop up in the future? Also, I noticed that my hand is at the top of the replay and the opponent is at the bottom, even when this wasn't the case before. It should be flipped to reflect the position in the actual game.

@jleclanche Yes up/down arrow helps. Although it'd still be nice to have a scrollable list of events so I can scroll it and immediately see where Flamestrike was used, for instance, and click to get there.

**Comment by jleclanche** [comment]
@garyking noted. Theres an event log which you can enable with the gear icon; it's super buggy right now though, which is why it's not very obvious. We'll add scrolling and click-to-go when we do a second pass on it.
