### ISSUE TITLE
My Deck is not Appearing

### ISSUE THREAD

**Issue by footanki** [HearthSim/Hearthstone-Deck-Tracker#3068]
## Before we start
- Please doublecheck there is no existing issue for your problem/feature request.  
- Please delete any obsolete sections (including this one) from this template before submitting your issue.

### Expected Behavior
My selected deck should be appearing and should be tracked throughout the game.

### Actual Behavior
Deck is not appearing.

### Steps to reproduce behavior
- Step 1: Launch Deck Tracker
- Step 2: Select a deck
- Step 3: Launch HS
- Step 4: Play a game
![hearthstone screenshot 01-06-17 09 59 30](https://cloud.githubusercontent.com/assets/24960776/21721564/daed609c-d3f6-11e6-8612-1394d27daddf.png)

**Comment by riQQ** [comment]
Please provide a log (https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#hdt-log-files).

**Comment by xFrootLoops** [comment]
Mine is not working either. I am currently using a Dell XPS 15. This is my log;

11:17:36 PM|Info|Core.Initialize >> HDT: 1.1.6.1, Operating System: Windows 10 Home 14393, .NET Framework: 394802
11:17:37 PM|Info|Updater.StartupUpdateCheck >> Checking for updates
11:17:37 PM|Info|Updater.GetReleaseUrl >> Downloading releases file
11:17:37 PM|Info|Updater.GetReleaseUrl >> using 'live' release: https://github.com/HearthSim/HDT-Releases
11:17:38 PM|Info|Updater.SquirrelUpdate >> Checking for updates (ignoreDelta=False)
11:17:39 PM|Info|Updater.SquirrelUpdate >> No new updated available
11:17:39 PM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
11:17:40 PM|Info|ThemeManager.LoadThemes >> Found theme: classic
11:17:40 PM|Info|ThemeManager.LoadThemes >> Found theme: dark
11:17:40 PM|Info|ThemeManager.LoadThemes >> Found theme: frost
11:17:40 PM|Info|ThemeManager.LoadThemes >> Found theme: minimal
11:17:40 PM|Info|GameV2.Reset >> -------- Reset ---------
11:17:40 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
11:17:41 PM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
11:17:42 PM|Info|MainWindow.SelectDeck >> Switched to deck: Arena 07-02 08:50 (v1.0)
11:17:42 PM|Warning|LogReaderManager.Stop >> LogReaders could not be stopped, stop already in progress.
11:17:42 PM|Info|GameV2.Reset >> -------- Reset ---------
11:17:42 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
11:17:43 PM|Info|BackupManager.Run >> Running BackupManager
11:17:43 PM|Info|BackupManager.Run >> Backup for today already exists
11:17:43 PM|Info|PluginManager.LoadPlugins >> Loading Plugins...
11:17:43 PM|Info|ApiWrapper.UpdateAccountStatus >> Checking account status...
11:17:43 PM|Info|ApiWrapper.UpdateAccountStatus >> Id=0, Username=, Status=Anonymous

**Comment by riQQ** [comment]
Check this: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#not-working.

**Comment by xFrootLoops** [comment]
I have tried all the steps listed above and the tracker still does not show up. Very unfortunate.

**Comment by riQQ** [comment]
So there are log files in the Hearthstone dir?
