### ISSUE TITLE
HDT crash when brawl start

### ISSUE THREAD

**Issue by HSfan** [HearthSim/Hearthstone-Deck-Tracker#3073]
When i start brawl, HDT chashes. It begins at previous weeks brawl start.
[Crash report 1212017-249.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/700389/Crash.report.1212017-249.txt)
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/700390/hdt_log.txt)

**Comment by beheh** [comment]
This should be fixed with v1.1.6.
