### ISSUE TITLE
Doesn't update automatically

### ISSUE THREAD

**Issue by Alexandru111** [HearthSim/Hearthstone-Deck-Tracker#3074]
## Before we start
- Please doublecheck there is no existing issue for your problem/feature request.  
- Please delete any obsolete sections (including this one) from this template before submitting your issue.

### Expected Behavior
Describe the expected behavior here

### Actual Behavior
Describe the actual behavior here

### Steps to reproduce behavior
- Step 1
- Step 2

### Log/Screenshots
If applicable, provide a log of the session where the problem occoured.  
See here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by Alexandru111** [comment]
Hi, I'm a bit of a noob with solving some simple tasks as these. 
 When I click on the "download new update" it gives some error and points out to do it manually. I then click the link to this site and download the win.rar. My question is, how do I proceed from there to update my Hs decktracker ? I have extracted it where it was downloaded but it hasn't been updated.

**Comment by riQQ** [comment]
You have to replace the folder from where you are running HDT.

**Comment by Alexandru111** [comment]
So delete the old one and extract the zip.rar again ? Won't that lose me the data, decklists and all ?

**Comment by riQQ** [comment]
Your data is stored at `%APPDATA%\HearthstoneDeckTracker` by default. If you haven't disabled storing your data in appdata, you should be good (This advanced option is only available in the portable / no-installer version).
