### ISSUE TITLE
HDT does not change deck automatically

### ISSUE THREAD

**Issue by Shuashan** [HearthSim/Hearthstone-Deck-Tracker#3075]
Hi,

since a few weeks (not sure if it started exactly with the latest update) HDT is not recognising and changing the deck I play automatically. If I change my deck in HS and start a new game (ranked, casual, even brawl, doesnt matter), HDT notices that the cards I draw do not belong to the deck which is shown on the right, but it does not automatically recognize the deck I am actually playing and it does not change to this deck. This worked perfectly in the past, but now I have to go into HDT manually and set the actual deck I am playing to active.
Maybe it is something in the settings, but I did not change anything there for months and I did not find anything related to this issue which I could change.

Any help is much appreciated, thanks a lot for this great tool!

**Comment by royard** [comment]
You should make sure the "auto deck selection" feature is turned on (right click the tracker icon in your taskbar).

**Comment by Shuashan** [comment]
thx man, the solution was as simple as that, I was too blind to see the auto deck selection feature ^^

thanks a lot for your help, this "bug" can be closed.

**Comment by riQQ** [comment]
You can close it yourself at the bottom with the button `Close issue`.
