### ISSUE TITLE
[Suggestion] Hotkeys

### ISSUE THREAD

**Issue by ericR-123** [HearthSim/Hearthstone-Deck-Tracker#3077]
When Options menu is open **Escape** key closes it just like the back arrow would.
When a deck is highlited **F2** opens the rename dialogue

This makes it behave more intuitively like a windows program should.

**Comment by judge2020** [comment]
We already have similar controls in Settings -> advanced options -> hotkeys. You can bind a key to "edit active deck" in which it'll open the deck for editing and you can change it from there.

The hotkeys menu could be improved with more hotkey actions such as closing the options menu like you've said.

**Comment by ericR-123** [comment]
Great, thank you!
