### ISSUE TITLE
Imp master image glitch

### ISSUE THREAD

**Issue by kadavr95** [HearthSim/Hearthstone-Deck-Tracker#3080]
Imp master card art (file EX1_597.png) image glitch.

In-game file
![image](https://cloud.githubusercontent.com/assets/8514685/21958514/4ef11d3c-dac1-11e6-882e-2e2b8e304c3a.png)

Full art
![image](https://cloud.githubusercontent.com/assets/8514685/21958523/712f756a-dac1-11e6-8a33-e77e58072662.png)

**Comment by azeier** [comment]
@jleclanche

https://art.hearthstonejson.com/v1/tiles/EX1_597.png
https://art.hearthstonejson.com/v1/256x/EX1_597.jpg

**Comment by judge2020** [comment]
seems to be fixed
