### ISSUE TITLE
Unable to import decks from Hearthstonetopdecks

### ISSUE THREAD

**Issue by tknights2015** [HearthSim/Hearthstone-Deck-Tracker#3082]
Unable to import decks from Hearthstonetop decks. Receiving error message "Could not find a deck on ....

Deck URLs
http://www.hearthstonetopdecks.com/decks/muzzys-legend-pirate-rogue-january-2017-season-34/
http://www.hearthstonetopdecks.com/decks/xixos-questing-miracle-rogue-wesg-2016/

[log_1612017-153532.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/709543/log_1612017-153532.txt)
![deck import errror](https://cloud.githubusercontent.com/assets/16232528/22001363/df4619d2-dc01-11e6-92a2-a2582f99c8a7.JPG)

**Comment by mudzereli** [comment]
I'm getting the same issue.

**Comment by judge2020** [comment]
![img](https://i.imgur.com/sjOQzUk.png)

> Hey, yeah I just changed how the cards list in each deck. Cards were wrapped with an <a> tag, and I've changed that to just being a \<li> with only the card name being linked. I hope this isn't too much trouble to fix.
