### ISSUE TITLE
Arena rewards dialog doesn't auto complete and even accept card names in russian localization

### ISSUE THREAD

**Issue by dedamoroz** [HearthSim/Hearthstone-Deck-Tracker#3083]
Subject appears only in russian localization, if I switch to another localization it works as intended.
Languages of cards are english and russian, try to change primary and secondary languages between these = nothing changes.

Screenshots:
http://i.imgur.com/jpnMoG2.png
http://i.imgur.com/rapzrxK.png

**Comment by riQQ** [comment]
This was fixed by https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/c740cd6e0644b461bfe1e09a7d707db03ba8354f.
