### ISSUE TITLE
HDT not importing anymore

### ISSUE THREAD

**Issue by maiklohse** [HearthSim/Hearthstone-Deck-Tracker#3087]
The tracker stopped being able to imprt decks all of a sudden. Normally just having the URL In the clipboard worked. But now even inserting the correct URL yields no results

![unbenannt](https://cloud.githubusercontent.com/assets/13084318/22181097/88430a78-e084-11e6-801a-bbdc4e639a6f.PNG)

**Comment by riQQ** [comment]
Duplicate of #3082.

**Comment by judge2020** [comment]
Will be fixed with next release. Importing does not work with HearthstoneTopDecks as of now.
