### ISSUE TITLE
Stats not being collected in Casual Play

### ISSUE THREAD

**Issue by Tubasaurus** [HearthSim/Hearthstone-Deck-Tracker#3089]
Hi folks,

I have been unable to get stats in Casual Play for a while now.  It does upload the replays ... 

My version is HDT 1.1.6

Attached are two screen shots showing settings and basic image.

Thanks for the help .. not sure if I am just missing something or if this is a bug.

Allan

![23 jan - no stats](https://cloud.githubusercontent.com/assets/25292556/22228620/54c43a88-e1a0-11e6-9461-9fdc72084eb3.jpg)

![23 jan - no stats - settings](https://cloud.githubusercontent.com/assets/25292556/22228621/54c54f90-e1a0-11e6-8e1d-c3bde3b50030.jpg)

**Comment by azeier** [comment]
You have `DISPLAY` in the second screenshot set to `Ranked`

**Comment by Tubasaurus** [comment]
Thank you very much.

I had a feeling it was Chair-Keyboard-Interface.

Have a good night
