### ISSUE TITLE
Spectator mode glitch

### ISSUE THREAD

**Issue by XzicaX** [HearthSim/Hearthstone-Deck-Tracker#3091]
I use HDT for about 7 months and today, whenever i join a spectator game all cards appear as created so when someone plays it it disappear from the list

tried to backup but nothing,

any ideas how to fix it?

**Comment by riQQ** [comment]
Is this still happening?

**Comment by XzicaX** [comment]
I fixed it, thanks


________________________________
De: riQQ <notifications@github.com>
Enviado: sábado, 23 de setembro de 2017 11:31
Para: HearthSim/Hearthstone-Deck-Tracker
Cc: XzicaX; Author
Assunto: Re: [HearthSim/Hearthstone-Deck-Tracker] Spectator mode glitch (#3091)


Is this still happening?
