### ISSUE TITLE
Overlay issues.

### ISSUE THREAD

**Issue by Steel-Blade** [HearthSim/Hearthstone-Deck-Tracker#3096]
I update HDT to v1.1.6 and some of the overlay features are disabled and I can't re activated them.

The timers next to the "End Turn" are gone.

The card marks for mulligan, returned, created, the coin, etc do not show anymore on opponents hand.

The deck list on right side its stack, it doesn't track which cards you have, it doesn't gray them out or remove them, but if you mouse over it, it does shows the tooltip popup.
I uninstalled the app and reinstalled few times but nothing works.
I upgraded to windows 10 recently, is the app not compatible maybe?

Any idea of what the problem may be?

Regards

**Comment by riQQ** [comment]
Looks like your option were reset.

**Comment by Steel-Blade** [comment]
I don't know what you mean by that.
I have looked at the settings under options many times and to the best of my knowledge I didn't hide the features I am missing.

Your comment really doesn't help me.

Can you be more specific?

**Comment by riQQ** [comment]
See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#not-working.

**Comment by Steel-Blade** [comment]
I have already read them, nothing helped.

I discovered the extra folder in roaming that does not gets removed when you uninstall the program.

What I eventually did was delete the config.xml from \AppData\Roaming\HearthstoneDeckTracker and everything was working properly again.
