### ISSUE TITLE
Cat in a Hat has wrong art

### ISSUE THREAD

**Issue by NightKev** [HearthSim/Hearthstone-Deck-Tracker#3097]
Unfortunately I forgot to take a screenshot before I played it, but it had the `Babbling Book` art when it was in my decklist. If it happens again I'll update with a screenshot.

(`Cat in a Hat` being the token generated from `Cat Trick`, it got put into my hand with `Vanish`).

**Comment by beheh** [comment]
See https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/Resources/Tiles/KAR_004a.png (same as https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/Resources/Tiles/KAR_009.png).
