### ISSUE TITLE
Cards created by (or replaced by) Renounce Darkness not listed until they drawn

### ISSUE THREAD

**Issue by ThePlayer14** [HearthSim/Hearthstone-Deck-Tracker#3100]
### Expected Behavior
HDT should display the new cards created/replaced by Renounce Darkness, if it's possible, instead of showing the previous cards as "played" (greyed out) except Neutral cards

### Actual Behavior
If Renounce Darkness were played, all cards except Neutral cards are shown as "played" (greyed out)
and the replaced cards appear when drawn, but after they played, they disappear from the tracker

### Steps to reproduce behavior
Make Warlock deck with Renounce Darkness and Warlock cards, along with Neutral cards
Play Renounce Darkness and see the results
### Notes
If possible to implement this tracking, it would be nice, as the draws are not surprises.

**Comment by judge2020** [comment]
You know which class you get and will draw from in your deck, but the cards are surprises.

**Comment by judge2020** [comment]
I don't think this type of tracking is possible to implement. The cards you switch into aren't sent to your client, and if they did, would not be shown in HDT as it would be an info leak.

**Comment by judge2020** [comment]
Closing because you do not know what cards you are going to receive with renounce.
