### ISSUE TITLE
Fix/Warn deck exporting on touch enabled devices

### ISSUE THREAD

**Issue by azeier** [HearthSim/Hearthstone-Deck-Tracker#3103]
Exporting on touch enabled devices causes the search bar to jump around [(wiki)](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#exporting).
Either alternate between search bars when exporting or show warning to use win7 compatibility mode.

**Comment by judge2020** [comment]
Possibly detectable with 
```C#
Windows.Devices.Input
              .PointerDevice.GetPointerDevices()
              .Any(p => p.PointerDeviceType == Windows.Devices.Input.PointerDeviceType.Touch);
```

**Comment by azeier** [comment]
HDT now uses Hearthstones native deck string importing system.
