### ISSUE TITLE
Notify of missed damage/lethal

### ISSUE THREAD

**Issue by vassijoseph** [HearthSim/Hearthstone-Deck-Tracker#3105]
Find instances of missed damage/ missed lethals

Like missing a Patches charge or roping and missing damage that has no cost, not by playing a card, just attacking with a minion with no debuffs.

Missed lethals is probably harder as it requires actual emulation but I think since replays are already stored it could be possible to find instances of missing damage with a minion.

Thank you for your great work.

**Comment by judge2020** [comment]
This would be a great plugin, however many players wouldn't want this to be in the app already. Blizzard might also not like it if it's directly bundled with HDT as it decreases required thought.

[plugin reference](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Creating-Plugins) | [Basic plugin tutorial](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Basic-plugin-creation-tutorial)

**Comment by vassijoseph** [comment]
I'm not talking about on screen alerts of lethal with minions, I'm talking about being able to review such instances that happened in the past through the replay files.
I opened the replay values and really all it's about is being able to interpret those files, finding minions that didn't attack face in a turn where there was no negative side effect to attacking.(no secrets, no taunts, no random effects like ogre brute's)

**Comment by judge2020** [comment]
Something for HSreplay would be better over at the [HSreplay](https://github.com/HearthSim/HSReplay.net) repository however that is a good idea.

**Comment by jleclanche** [comment]
We're really unlikely to do this in HSReplay.net any time soon, because it requires quite a lot of processing to do right.

If someone wants to implement something like this on top of the HSReplay format I s'pose it would be cool, but I'm going to close this issue as it's simply not a feasible project on our side atm (and wouldn't be in HDT either way).
