### ISSUE TITLE
move games from arena to ranked

### ISSUE THREAD

**Issue by mmiat** [HearthSim/Hearthstone-Deck-Tracker#3107]
HDT has not correctly recognized my last games, so 5 of them is under arena and not under ranked
can I move them?

**Comment by judge2020** [comment]
Yes. go into your stats page and view the matches tab. On the selected game, click edit:

![image](https://cloud.githubusercontent.com/assets/8601934/22991594/cf893830-f38a-11e6-93b5-cdda861db1e0.png)

Next, in the dialog change the `Mode` dropdown to Ranked/Casual.

![image](https://cloud.githubusercontent.com/assets/8601934/22991640/fb1ffd4e-f38a-11e6-86e2-d4867ec05eae.png)

**Comment by mmiat** [comment]
thanks, but...
it's still in ranked even if it is showed under Arena :o
and if I try to change to arena and then to ranked nothing changes
very strange

**Comment by mmiat** [comment]
already ranked...

![screenshot 2017-02-15 23 01 08](https://cloud.githubusercontent.com/assets/11910225/23021474/72a7a40e-f44c-11e6-97ef-ce5f91885ac3.png)

**Comment by mmiat** [comment]
I've solved editing DeckStats.xml file:
1. moved <game> under right <deck>
2. changed <HsDeckId>
3. changed <DeckName>
I hope these changes are enough and all is ok
