### ISSUE TITLE
[Suggestion] Auto-search opponents deck in real time on Hearthpwn

### ISSUE THREAD

**Issue by blksith0** [HearthSim/Hearthstone-Deck-Tracker#3112]
YOu know what Im sayin?
As they play cards, you filter.

**Comment by ViezeVingertjes** [comment]
I think this could be a neath feature. It will probably never be exact a heartpwn deck, but if it's close the name might suggest what kind of player it is.

**Comment by judge2020** [comment]
Lucky for you, there is already a plugin that aims for this functionality called [Advisor](https://github.com/djdookie/Advisor). Instead of looking through Hearthpwn it uses Metastats:

> First, the import function of Advisor allows you to quickly import hundreds of standard archetype decks from MetaStats.net. Currently the top 5 played standard decks of each archetype and each class of the last 7 days are imported.
