### ISSUE TITLE
Incompatible with Windows 7?

### ISSUE THREAD

**Issue by nicholberry** [HearthSim/Hearthstone-Deck-Tracker#3114]
I can no longer get HDT to open from shortcut and can't find it in my windows explorer. I ran a windows trouble shooter which, when all was said and done, gave me Troubleshooting Complete report: "Incompatible Application". 

I'm running Windows 7 Home Premium version 6.1. It ran on this laptop up until the newest update.

**Comment by mmiat** [comment]
I've version 1.1.6 with W7 Pro 64bit SP1, no problems

**Comment by nicholberry** [comment]
I can't even tell you the version I have because I cannot open it. Guess I'll just uninstall and reinstall. It seems like it had something to do with updates of Windows and HDT occurring concurrently. I haven't used that laptop for almost a week so when I opened it they both updated at the same time. thanks for the reply 

----- Original Message -----
