### ISSUE TITLE
Cannot turn off No-Deck Mode

### ISSUE THREAD

**Issue by mvelic** [HearthSim/Hearthstone-Deck-Tracker#3118]
## Bug report
I turned on No-Deck Mode using the "button" at the bottom of the app (I am on Windows 10), and now I cannot turn it off. Clicking and right-clicking the No-Deck Mode "button" is not turning off that option. Neither is closing and restarting the application.

### Expected Behavior
I expect to be able to turn off No-Deck Mode by clicking the button at the bottom of the application.

### Actual Behavior
Clicking the No-Deck Mode "button" does not toggle the option. It remains on.

### Steps to reproduce behavior
1. Install on Windows 10.
2. Click the No-Deck Mode "button" at the bottom of the main application screen. (Toggles on.)
3. Re-click the No-Deck Mode "button". (Remains toggled on.)
 
### Log/Screenshots
![image](https://cloud.githubusercontent.com/assets/1065914/23579722/6feffa6e-00c1-11e7-8f61-e6be29762df6.png)

**Comment by mvelic** [comment]
I've also checked the Settings for an alternative way to turn this off, and have yet to find anything. I looked at the config file, and nothing popped out at me as the obvious choice as well.

**Comment by azeier** [comment]
Try clicking "use" on any deck.

**Comment by azeier** [comment]
This behavior will be fixed with the next update.

**Comment by mvelic** [comment]
Right-clicking a constructed deck and selecting Use did turn off the option, thank you!
