### ISSUE TITLE
Hearthstone Deck Tracker App is hidden

### ISSUE THREAD

**Issue by heymozart** [HearthSim/Hearthstone-Deck-Tracker#3123]
Moi guys, I have a big problem...

My program is hidden, I already done the usual Windows 10 things to get back the HDT-app window, but nothing worked. Here you can see, which steps I already took: https://www.technipages.com/bring-off-screen-window-back-onto-screen 

Ingame I got no problems seeing my overlay, but in usual desktop mode I dont find the program.

When I maximize the window like it is explained in the link above my screen gets dark (no blackscreen, only really dark and I still can see my taskbar of windows).

What I also tried to fix it:
- repair MS framework
- reinstalled HDT
- turning antimalware programs off
- start HDT as admin and in compatibility mode(s)
- reboot my pc
- prayed to all gods I know, that HDT suddenly starts to work again ;)

I apologize for any mistakes in my grammar and writing, english is not my mother tongue.

Greetings from Germany, 
heymozart

**Comment by Discordia2014** [comment]
I have exactly the same problem, I was hoping to find an answer in the forum but I see that few issues are answered.

**Comment by judge2020** [comment]
[Not-Working](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#its-not-detecting-cards-i-or-my-opponent-play)

**Comment by heymozart** [comment]
Hey Discordia, did you use two screens?

**Comment by Discordia2014** [comment]
I use two screens but for a long time, the error came to me yesterday.

**Comment by heymozart** [comment]
Same here, I only used my main screen opened the program and after that i plugged my secondary screen in and it worked.... Since then it worked everyday straight. 

Try this workaround!

**Comment by Discordia2014** [comment]
For a moment it seemed to work, but then the interface disappeared again. I think I will go to format the pc, this already takes me all day and part of yesterday, I would have finished before if I had formatted.

**Comment by Discordia2014** [comment]
Funny, after formatting the same problem continues.

Windows 10 x64 - fully updated
Drivers - fully updated
New Blizzard App
New Hearthstone
New Hearthsone Deck Tracker

The problem first appeared when I updated my pc (windows, programs, drivers), maybe the reason is the latest windows update.

**Comment by nicki118** [comment]
Same here, did you found a solution?
