### ISSUE TITLE
Tracker App opens but when HS Launches -> I cannot see my deck or app at all

### ISSUE THREAD

**Issue by otakebi** [HearthSim/Hearthstone-Deck-Tracker#3126]
I open the tracker app. Select my deck and launch Hearthstone. Then Deck tracker completely disappears in game. No deck or stats or anything even though the app is still running in the back ground.

**Comment by Discordia2014** [comment]
I have exactly the same problem, I was hoping to find an answer in the forum but I see that few issues are answered.

**Comment by judge2020** [comment]
see [Not-Working](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#its-not-detecting-cards-i-or-my-opponent-play)

**Comment by Discordia2014** [comment]
I use two screens but for a long time, the error came to me yesterday.

**Comment by dmac303** [comment]
none of these issues help, i have the same problem, It keeps track of my win ratio and everything but it like the overlay has been sent to the back and cant bring it over hte game

**Comment by Bond2King** [comment]
I have the same problem as dmac303 at least.  The overlay isn't properly staying on top of the hearthstone window.  It gets sent to the back like a normal unrelated window would be when hearthstone is brought into focus.  Pressing Alt + Esc to send the HS window back brings it up temporarily, but once you click into HS it's gone again.

**Comment by Discordia2014** [comment]
Funny, after formatting the same problem continues.

Windows 10 x64 - fully updated
Drivers - fully updated
New Blizzard App
New Hearthstone
New Hearthsone Deck Tracker

The problem first appeared when I updated my pc (windows, programs, drivers), maybe the reason is the latest windows update.

**Comment by Bond2King** [comment]
The issue started for me with a new PC this week, my first with Windows 10, to add to that theory.

**Comment by dmac303** [comment]
yea i did the same, i deleted and reinstalled HS, HSdecktracker and still the same problem. Im truly clueless as to what else to do or what could be causing this problem.

**Comment by JoniSykes** [comment]
Tried all suggestions in linked article, nothing works. 
I can briefly see flashes of the overlay if I toggle some of the checkboxes in the settings menu of HDT.
My issues started with Un'Goro update. Not Windows.

**Comment by Discordia2014** [comment]
@JoniSykes [https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3143](url)

**Comment by dmac303** [comment]
whatever that link is doesnt work...

**Comment by dmac303** [comment]
does anyone know of any other deck tracker that shows the cards you have in ur deck ?

**Comment by riQQ** [comment]
This is the correct link: #3143

**Comment by judge2020** [comment]
closed in favor of #3143
