### ISSUE TITLE
When using Windows+G on computer, it will not record the deck tracker.

### ISSUE THREAD

**Issue by GamingGaodzilla** [HearthSim/Hearthstone-Deck-Tracker#3129]
Simple enough, I can't find a way to record the deck tracker at all. I did look into the streaming thing on the wiki, but that doesn't help, since im recording though the build - in recording software, , so i'm wondering if you can record it at all. i am using a windows computer to do this.

**Comment by judge2020** [comment]
I don't think recording with Game Bar is possible at the moment. The game bar can only record a single window, which limits it to only capturing either HDT or HS. It also can't record pure desktop footage.

**Comment by judge2020** [comment]
Not supported by Game Bar
