### ISSUE TITLE
counters suggestion/request and confusion

### ISSUE THREAD

**Issue by Dushku** [HearthSim/Hearthstone-Deck-Tracker#3132]
I was curious as to why the jade and C'thun counters are formatted as X/X. The numbers seem to always be the same. So I'm curious why not display as a single number, which will be larger/more legible?

Also, I was wondering if a new counter could be added for N'Zoth decks: Number of deathrattles that have died. I'm playing a shaman N'Zoth deck and I'm trying to keep my board under control so that I don't miss N'Zoth resurrects. Does that make sense?

Anyways, thank you for taking the time to read this.

**Comment by judge2020** [comment]
It's 8/8 to stay in line with the Hearthstone format of defining what a minion is 8 attack / 8 heath. Maybe there could be an option to display a single number.

For N'zoth, there is a great plugin that does just this: [Graveyard Tracker](https://github.com/RedHatter/Graveyard#readme). 

[Instructions](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Available-Plugins#method-1-drag-and-drop) to install plugins

**Comment by Dushku** [comment]
Thank you for this! It's quite perfect. I appreciate you taking the time to provide links too. Very thoughtful!

**Comment by Dushku** [comment]
I've just come to realize that Blade of C'thun can lead to C'thun having asymmetric stats. So that would not need to be addressed.
