### ISSUE TITLE
Crash on collection screen

### ISSUE THREAD

**Issue by beheh** [HearthSim/Hearthstone-Deck-Tracker#3136]
A [user on reddit](https://www.reddit.com/r/hearthstone/comments/627as6/hearthstone_deck_tracker_crashing_on_collection/) is reporting a consistent crash on the collection screen. User reports he's reinstalled. I've attached the log files, the last few seem to suddenly end.

[Logs.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/880484/Logs.zip)

Any idea what he can try?

**Comment by fbibeau** [comment]
Same here. Win 10 x64.

**Comment by azeier** [comment]
The latest log is from version 1.1.7. Downloading the latest update might fix it - https;//hsdecktracker.net/download/

**Comment by judge2020** [comment]
Should be fixed by now.
