### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by vayo28** [HearthSim/Hearthstone-Deck-Tracker#3137]
Hello, some time ago I have a problem, I play on 2 servers (NA and EU) and the tracker does not differentiate that, save the games but does not change the server and I have to do it manually which is a bit annoying, is there any way fix?? Thank you!

**Comment by jleclanche** [comment]
I don't understand, what is the tracker not doing exactly?

**Comment by judge2020** [comment]
@jleclanche I believe he means inside HDT's stats page, it doesn't detect different regions when recording games.

@vayo28 **the next release** *should* fix region detection, [this commit](https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/776efd0f7fd8603b75d5cc1a9075f23dcb686748) improves it and will be included with the next release.

**Comment by vayo28** [comment]
judge2020 thanks!!
