### ISSUE TITLE
Mass Deck Deletes

### ISSUE THREAD

**Issue by Nedmarc** [HearthSim/Hearthstone-Deck-Tracker#3138]
Is there a way to remove all saved decks without having to click each one and select delete?   It would be a nice feature to select all and remove.

**Comment by judge2020** [comment]
This is currently possible.
select one deck, then either ctrl+click or shift+click to select multiple decks.

Then hit the DELETE key on the keyboard. you will get an message box like this 

![img](https://judge2020.me/qZzyA.png)

to select all you can go to the top of the decks and click the top one, then scroll all the day down and shift+click the bottom one then press delete.
