### ISSUE TITLE
How can we merge the deck stats from 2 or more PCs?

### ISSUE THREAD

**Issue by iamatsundere** [HearthSim/Hearthstone-Deck-Tracker#3139]
Hi. as I posted on the title of the issue, I want to merge the statistics from two or more PCs because of playing the game on many devices but I still want to check my completed data. I tried to adding some data in the DeckStats.xml file in ../AppData/Roaming/HeathstoneDeckTracker but it seemed not to work. I also changed the id of the deck when merging but not thing happened. So if anyone did this before, please help me!

**Comment by judge2020** [comment]
Currently merging two is hard, it needs to be done by hand. A system is in the works that will sync decks and stats with HSReplay.

**Comment by disshishkov** [comment]
does hsreplay.net support already stats sync?

**Comment by azeier** [comment]
not yet

**Comment by judge2020** [comment]
closed in favor of #3235

**Comment by judge2020** [comment]
duplicate of #3235
