### ISSUE TITLE
Deck Tracker froze my computer, now Battle.Net can't find my games

### ISSUE THREAD

**Issue by MuphynMan** [HearthSim/Hearthstone-Deck-Tracker#3140]
I installed HDT today, and was testing it out. It imported decks just fine, but wasn't responding to cards me or my opponent played, so I followed steps outlined here, as prescribed
https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Setting-up-the-log.config

Then I restart hearthstone, the computer froze. After restarting, I went to the launcher, and all games I had (including hearthstone) are either uninstalled or not found, so I have to go into the directory to find if they exist.

What happened? Why did it happen? I just changed the log.config and it's like my battle.net files all blew up.

**Comment by riQQ** [comment]
This is not a HDT problem.
