### ISSUE TITLE
where to find

### ISSUE THREAD

**Issue by 10302311** [HearthSim/Hearthstone-Deck-Tracker#3142]
where to find the heartstone deck tracker because i cant find it in this video https://www.youtube.com/watch?v=nybcA1c7qbc&t=17s At 1:10

**Comment by judge2020** [comment]
The installer at https://hsdecktracker.net will place a shortcut on your desktop for opening HDT, and put it in your program list.

![img](https://judge2020.me/gPXBZ.png)

**Comment by 10302311** [comment]
Thank you to much!
