### ISSUE TITLE
Overlay isn't appearing in-game

### ISSUE THREAD

**Issue by SirThomasII166** [HearthSim/Hearthstone-Deck-Tracker#3144]
The deck tracker has been working fine up until the past week or so. It tracks my deck stats fine but the overlay isn't appearing during the game. When I change the options of the deck tracker it appears with the changes, but as soon as I click on my Hearthstone window the overlay disappears again. I'm using two monitors if that makes any difference.

I've tried all the steps listed in the FAQ and nothing has worked.
I've attached a log file of a recent game where this issue was present.

[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/892520/hdt_log.txt)

**Comment by azeier** [comment]
Duplicate #3143.
