### ISSUE TITLE
suggestion "do not upload the game less than 2 or 3 turns"

### ISSUE THREAD

**Issue by chucklu** [HearthSim/Hearthstone-Deck-Tracker#3146]
I concede 2 game and win the third game in causal mode,just want to keep the winrate around 33%.
Then  I will meet the opponent who is easier to defeat to complete the daily task.
so,the game conceded by me at the start of the game is not meaningful.

I hope you will not upload the game conceded at the first 3 turns.
I also found the news at hsreplay.net,you will using the data uploaded to analysis.

maybe you can give us a selection,to set the turns number.When the game's turn is smaller than the setting,you will not uploaded the game record.

**Comment by azeier** [comment]
There is a "Discard games with zero turns" option under `options > tracker > stats`. I'm not something more complex is necessary.

**Comment by chucklu** [comment]
No, I need you record the game end with 0 turns in local,but not uploaded to website.
I need to check if I have conceded 2 games in causal to decide whether continue concede or defeat the opponent

**Comment by azeier** [comment]
I don't think this is necessary. Uploading those games is fine, you can temp. (or permanently) disable casual uploading if you know you don't want to upload them.
