### ISSUE TITLE
Deck Tracker not detecting game start/end

### ISSUE THREAD

**Issue by Averlath** [HearthSim/Hearthstone-Deck-Tracker#3151]
Hello. Today, my Deck Tracker wasn't working properly. It wasn't detecting when the game was starting or ending. It shows my deck and detects which one it is, but doesn't update when I draw a card or anything. Says myself and my oponent are still at 30 cards in the deck, etc.

I saw that there was a thread just like this, in which it was suggested to replace a file in "%LocalAppData%/Blizzard/Hearthstone/log.config" with a file given, but the link no longer worked.

Screenshot: http://imgur.com/a/Cr49o

**Comment by azeier** [comment]
See #3150
