### ISSUE TITLE
Issue with Patches the Pirate.

### ISSUE THREAD

**Issue by FeelsSameMan** [HearthSim/Hearthstone-Deck-Tracker#3152]
The deck tracker does not always correctly recognize that Patches the Pirate has been pulled out of the deck by another Pirate.

The deck tracker should show that Patches the Pirate is no longer in the deck after he has been pulled out

Sometimes the deck tracker does not appropriately show that Patches the Pirate is no longer in the deck.

I have no method of reproducing the bug, it just randomly occurs sometimes.

Hopefully these screenshots work. The first one is the screenshot of the second Pirate that I played in that game after Patches the Pirate was already gone. The second screenshot is of the deck tracker showing Patches the Pirate is still in my deck while you can see that I am already well into fatigue with zero cards left in my deck.
![hearthstone screenshot 04-05-17 01 13 00](https://cloud.githubusercontent.com/assets/26918415/24692573/51fc9822-199f-11e7-8464-60d6010a0cb1.png)
http://prntscr.com/esm2fr

**Comment by azeier** [comment]
Could you upload the log the next time you encounter this issue? See here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by tenth-planet** [comment]
@azeier here's a log where i played Patches and the bug occured [https://gist.github.com/tenth-planet/53b826898d9baf6728ccb86cb8799df9](gist)

**Comment by tenth-planet** [comment]
And here's a [replay](https://hsreplay.net/replay/QxBGhmhs5L4yQV7Ar4xcw5)

**Comment by azeier** [comment]
Fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/7a4b195f7df74fc6e0dd40ada248a9099a795176
