### ISSUE TITLE
Incorrect Detection of Wild/Standard Decks

### ISSUE THREAD

**Issue by chiefstank** [HearthSim/Hearthstone-Deck-Tracker#3154]
It mistakes the deck I'm trying to export to as Wild when it's set to Standard.

I am exporting decks from websites to Hearthstone. One example is from hearthpwn (http://www.hearthpwn.com/decks/766908-s37-thijs-murloc-shaman) but have tried 5-6 different ones. When exporting deck to Hearthstone From Web, I select a Standard deck in HS but HDT detects it as Wild deck and fails to Export. Same thing happens if I Import the deck from Web FIRST and then Export to HS. 

Can reproduce of 5-6 decks tested from hearthpwn.

Included is a screenshot of the error as well as two log files from today. I am using the most updated version of HDT. I can manually add all cards to the deck in HS without issue (not a wild deck).

![untitled2](https://cloud.githubusercontent.com/assets/6421187/24715544/8bafe2cc-19e0-11e7-90dd-a81a1948b6fe.png)

**Comment by azeier** [comment]
This will fix itself tomorrow when the rotation happens.

Workaround for now: create a wild deck in game and convert it to standard after the export is complete.
