### ISSUE TITLE
Deck Tracker doesn't track Tavern Brawl custom decks.

### ISSUE THREAD

**Issue by FlamingFox911** [HearthSim/Hearthstone-Deck-Tracker#3155]
### Expected Behaviour
Deck tracker should track Tavern Brawl decks, even if they are Wild/Custom Decks.

### Actual Behaviour
Just shows deck list. Which ain't bad, but it doesn't show what has been drawn.

### Steps to Reproduce
Do this weeks Tavern Brawl.

**Comment by jedimaster421** [comment]
Can confirm I'm also having this issue. It's also missing the turn timer; it doesn't show the cards played by the opponent, and the record of the game in the stats chart is missing almost all the information about the game.

**Comment by chucklu** [comment]
I have met this problem too,HDT just record the deck in the background,do not show the deck automatically.
When I try to switch to another random deck, it will auto check deck and switch to the correct one

**Comment by azeier** [comment]
I think this is fixed?

**Comment by judge2020** [comment]
Likely fixed with https://github.com/HearthSim/HearthMirror/commit/f8db00814bfbfcbcef79b82f1893af747f4b75be in HearthMirror

**Comment by riQQ** [comment]
This is working for me now with v1.4.5.
