### ISSUE TITLE
All imported decks and lists are gone, but tracker still works?

### ISSUE THREAD

**Issue by Kiltedbear** [HearthSim/Hearthstone-Deck-Tracker#3159]
Straight forward here. Yesterday I believe or the day before I got a server connection error of some sort and my deck lists were gone in DT. I didn't screenshot it. I shut it down and then restarted and got the same error. I left it running and played some. After about 15 minutes I realized that my deck list overlays were working in the game and thought it had restarted or something. I went back out to the tracker and the error was gone, but all my deck lists were still blank. I restarted it several times and lists are still not there, however, the weird part is that my lists still work in the game. It still recognizes which list I am playing and what cards I am drawing. The whole thing. It's like the lists in the tracker app are invisible but still present. I can't select them, change them or anything else. I haven't tried creating or importing and saving a new one for fear it may overwrite my large existing list of decks I already have. I do not have a log file since I didn't have it selected in options. I do now and it only shows actions the tracker took this morning. Is there a more permanent log somewhere? I looked in the install folder and didn't see anything. Current version is V1.2.1
### Log/Screenshots
If applicable, provide a log of the session where the problem occurred.  
See here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues
![image](https://cloud.githubusercontent.com/assets/12203829/24758281/e68e8fb6-1aaf-11e7-9c41-a7327c2a1aa5.png)

**Comment by azeier** [comment]
They are most likely behind the "wild" tab. HDT is already in post rotation mode.

**Comment by Kiltedbear** [comment]
You are exactly right! Didn't know that happened. Thanks!
