### ISSUE TITLE
Quests bring up secret tracker

### ISSUE THREAD

**Issue by RMan360** [HearthSim/Hearthstone-Deck-Tracker#3160]
If an opponent plays a quest, the secret tracker displays and will stay up until the quest is completed
### Expected Behavior
Quest is played. no secret tracker response as no secret has been played
### Actual Behavior
Quest is played. Secret tracker responds and displays all possible secrets from opponents class. will continue to grey out secrets until no options remain and will only go away once quest has resolved
### Steps to reproduce behavior
- Step 1 Have opponent play quest card

**Comment by azeier** [comment]
Fixed by https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/9b217a419d94b5d89342c140f190ad8e04002c5a. Update coming likely within the next 12 hours.

**Comment by azeier** [comment]
Fixed with v1.2.2
