### ISSUE TITLE
Opponent's overlay shrunk (witdh) and won't come back.

### ISSUE THREAD

**Issue by TemporalOnline** [HearthSim/Hearthstone-Deck-Tracker#3161]
Ever since the new expansion, my opponent's deck overlay now is like 20 px and I can only move it and its height, but not its width.

Everything else (including opponent's secrets - apart from detecting quests as secrets) is working normally.

**Comment by azeier** [comment]
See if changing `options > overlay > opponent > scaling` helps.

**Comment by TemporalOnline** [comment]
I tried that and it didn't work, but then I restarted the computer (because I've gone to the grocery store) and now it is working again. I have no idea what happened.

**Comment by azeier** [comment]
👍
