### ISSUE TITLE
Arena helper does not work when hero selected.

### ISSUE THREAD

**Issue by zhufengtom** [HearthSim/Hearthstone-Deck-Tracker#3163]
![360 20170407103156779](https://cloud.githubusercontent.com/assets/23748359/24783342/644211d4-1b7e-11e7-96ce-982413697374.jpg)

**Comment by riQQ** [comment]
See https://github.com/rembound/Arena-Helper/issues/116.

**Comment by rembound** [comment]
Thanks for reporting! I have fixed it in the latest release.

`HsLogReaderConstants` was changed into `LogConstants`

**Comment by azeier** [comment]
Closing since this is not an HDT issue.
