### ISSUE TITLE
Doesn't show tracker overlay in game

### ISSUE THREAD

**Issue by PuppetMaster000** [HearthSim/Hearthstone-Deck-Tracker#3164]
When the update for ungoro hit, the tracker worked fine. But ever since I woke up and (I think) the tracker updated, I can't get the overlay to show in game. I tried resetting overlay position, unlocking, ticking/unticking the hide options etc... The scores still register wins and losses, but the overlay doesn't show.
I don't know if this helps but here is the log as well.
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/905505/hdt_log.txt)

**Comment by azeier** [comment]
#3143
