### ISSUE TITLE
Overlays do not show up

### ISSUE THREAD

**Issue by Fierceblock** [HearthSim/Hearthstone-Deck-Tracker#3172]
My cards do not show up when I'm playing.

Sometimes they show up when I hit lock/unlock, but then when I minimize HDT, they disappear from the game.

I've tried every option in general and settings.  I don't want windowed mode.  Help.

**Comment by azeier** [comment]
See #3143

**Comment by Fierceblock** [comment]
Ah sorry didn't search good enough.  Thanks.
