### ISSUE TITLE
Show "created from" origin

### ISSUE THREAD

**Issue by MadGarfield** [HearthSim/Hearthstone-Deck-Tracker#3173]
### Actual Behavior

Today, when I use Mage deck，I ran into a N'Zoth priest,and he gained one or two "gift" cards from my rest deck each turn ,so after several turns, his hand had so many "gift " cards,that I can hardly tell which one the "gift" card came from. So,I had no idea whehter he had stolen my "Ice block ". Is it possible to show the "gift" card comes from when mouse moves over it?

**Comment by riQQ** [comment]
See #2224.

**Comment by judge2020** [comment]
Closed in favor of the origin tracking in #2224
