### ISSUE TITLE
HDT crash after start importing or editing deck

### ISSUE THREAD

**Issue by speedytr** [HearthSim/Hearthstone-Deck-Tracker#3175]
HDT started crashing in deck edit (or after import) in my two different laptops. Whenever I try to edit a deck or import a deck from heartpwn (didnt try any other site) HDT freeze for a couple of second then crash. Other than this behavior everything is working normal. This problem started after updating windows 10 to creators update or HDT version 1.2 (I did these update at the sametime).

**Comment by riQQ** [comment]
Please provide logs. See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues (sections `HDT crash logs` and `Windows log files`)

**Comment by speedytr** [comment]
It started to behave normal maybe it was a problem with hearthpwn
