### ISSUE TITLE
HDT (1.2.2) Shows decklist but behind Hearthstone Window

### ISSUE THREAD

**Issue by Jigglybaby** [HearthSim/Hearthstone-Deck-Tracker#3176]
When I opened Hearthstone along with HDT, I noticed it wasn't displaying the active deck when I was playing a game, or the gold progress. I switched to window mode and noticed when I was moving the window mode Hearthstone, I could see the decklist sliding along with the window but it would go behind the window (same thing with the gold progress).

**Comment by Madi921** [comment]
Yeah, same here. :\

**Comment by azeier** [comment]
See #3143
