### ISSUE TITLE
Suggested Feature: Track games played on mobile

### ISSUE THREAD

**Issue by killjoy01** [HearthSim/Hearthstone-Deck-Tracker#3178]
Or does this already work?

I would imagine not, because I assume you need to launch it through the app.

**Comment by judge2020** [comment]
For Android there is https://github.com/HearthSim/arcane_tracker however it seems the last few updates have broke it.

I've been looking into getting logging enabled on iOS however haven't found anything yet.

**Comment by azeier** [comment]
Nothing that will or can happen in the scope of HDT.

As judge said, there is an android tracker which broke in the last couple of hearthstone updates but blizzard is looking into the issue (https://twitter.com/ywoo_dev/status/849730791303069701). 

iOS requires at least a jailbroken device, not sure if it's even possible then.
