### ISSUE TITLE
feature request: (re)assign match to another deck

### ISSUE THREAD

**Issue by sshilovsky** [HearthSim/Hearthstone-Deck-Tracker#3179]
One can edit match data in the stats table. Sometimes a deck in match record happens to be unidentified (none) for some reason. It would be useful to be able to assign a deck to this match.

### Screenshot

http://hmp.me/7kp

**Comment by sshilovsky** [comment]
Ok I just wondered what does that "move" button do, and it turned out that it does exactly what I want here. Sry for false report :) The issue is now that the deck name is not updated until HDT is restarted.

**Comment by judge2020** [comment]
GitHub rehost:

![IMG](http://i.hmp.me/m/fa2168662e091ed9ec7700f6fbf70b92.png)
