### ISSUE TITLE
Deck Trecker work, but do`t show any information in game.

### ISSUE THREAD

**Issue by WvWvWvWvWvW** [HearthSim/Hearthstone-Deck-Tracker#3181]
It`s looks like it hide.
I can see all information when i Alt - Tab on Deck trecker. When i Alt - Tab back to game it hide.

**Comment by WvWvWvWvWvW** [comment]
before last game update all was fine

**Comment by judge2020** [comment]
See #3143

**Comment by WvWvWvWvWvW** [comment]
Thx. Runing as admin solved it for me.

**Comment by WvWvWvWvWvW** [comment]
Thx. Runing as admin solved it for me.
