### ISSUE TITLE
Plugin Collection Tracker 0.5.2 not working in HDT 1.2.2

### ISSUE THREAD

**Issue by ElfoOscuro** [HearthSim/Hearthstone-Deck-Tracker#3185]
## Bug report
I get an error message when using Collection Tracker 0.5.2 plugin in HDT 1.2.2.

### Expected Behavior
Plugin working

### Actual Behavior
Plugin not working

### Steps to reproduce behavior
- Step 1
Install Collection Tracker 0.5.2 plugin from https://github.com/adriencarbonne/Hearthstone-Collection-Tracker/releases
- Step 2
Run plugin

### Log/Screenshots
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/908409/hdt_log.txt)

**Comment by judge2020** [comment]
Hey, that plugin is no longer maintained by its original creator. We forked it and the HearthSim community is maintaining it at:

https://github.com/HearthSim/Hearthstone-Collection-Tracker

However please note we have not yet added Un'Goro implementation and the plugin is probably completely broken at the moment. It will likely be updated within 24 hours of this comment.

**Comment by judge2020** [comment]
@ElfoOscuro it has now been updated for ungoro and should work.

There is also continuous importing so you no longer have to click "import" each time.

**Comment by ElfoOscuro** [comment]
Thank you very much.
