### ISSUE TITLE
HDT not opening only on first installation

### ISSUE THREAD

**Issue by stretch97** [HearthSim/Hearthstone-Deck-Tracker#3187]
## Before we start
- Please doublecheck there is no existing issue for your problem/feature request.  
- Please delete any obsolete sections (including this one) from this template before submitting your issue.

### Expected Behavior
The tracker starts normally.

### Actual Behavior
When i try to start the Tracker, it crashes, it open the process on Win 7 x64 but then it crashes. Before Un'Goro it worked fine, but now i have to reinstall everytime the tracker to open it. When i close it and try to open it after the installation it crashes again. i've already tried to delete all files about HDT and do a clean installation.

### Steps to reproduce behavior
- Step 1 Start HDT
- Step 2 It doesn't open

**Comment by chucklu** [comment]
maybe you can upload the log file,you can find the log file by https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by stretch97** [comment]
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/908460/hdt_log.txt)
Here it is

**Comment by chucklu** [comment]
@stretch97  please check the crash log

**Comment by stretch97** [comment]
I resolved, i had no crash logs but i just ran the deck tracker from the folder 1.2.2 instead of the main folder.
Hope this will help someone

**Comment by judge2020** [comment]
^Means it's likely a problem with the Updater (checking for updates before opening) being unable to open the exe.

**Comment by azeier** [comment]
Glad you managed to find a solution.
Alternatively you can also try using the portable build: https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/latest
