### ISSUE TITLE
Overlay is gone

### ISSUE THREAD

**Issue by sarasker** [HearthSim/Hearthstone-Deck-Tracker#3190]
### Expected Behavior
To see the overlay durings matches
### Actual Behavior
Not seeing any overlay during matches for the past couple days. I thought it had to do with the new cards, cause i was experiencing something similar the first days of the expansion but now the overlay is completely gone

### Log/Screenshots
[hdt_log_1491858294.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/911556/hdt_log_1491858294.txt)

**Comment by riQQ** [comment]
See #3143.

**Comment by sarasker** [comment]
i saw 3143, didnt help....

**Comment by judge2020** [comment]
Run as administrator
