### ISSUE TITLE
Misdirection + Vaporize - SECRET GRAY OUT BUG!

### ISSUE THREAD

**Issue by Zawodowiec1532** [HearthSim/Hearthstone-Deck-Tracker#3191]
Situation on board:
- Hunter vs Mage
- Hunter have secret "Misdirection" and 0 minions (can have more, but then must hit Mage in face).
- Mage have secret "Vaporize" + 1 Minion on board (can have more, but then must hit Mage in face).

Expected Behavior:
- After Mage attack Hunter with this 1 minion, he will face himself because of hunter secret.
- Vaporize will not trigger, it shouldn't gray out in SecretTracker..

Actual Behavior:
- In this case Vaporize will not trigger, but its graying out in SecretTracker.

**Comment by justinkb** [comment]
Took a quick look at the code.

Fix should be to add a check if it's even it's even opponent's turn in the file "Hearthstone DeckTracker/Hearthstone/Secrets/OpponentSecrets.cs" or to whatever calls functions from it.

Specific vaporize check is on line 137, but likely you'd want to pre-fix other similar potential bugs by not even trying to "zero" these secrets on one's one turn.
