### ISSUE TITLE
I don't know what is happening HDT Crashed

### ISSUE THREAD

**Issue by kendyzin** [HearthSim/Hearthstone-Deck-Tracker#3195]
Hey guys.
I'm in trouble with my HDT. Since almost two weeks my HDT chashed, it isn't getting the deck for the gameplays, I've already unistalled and installed dozens of time but it is not working at all.  
I was importing the decks from the game to the HDT but the program didn't find the decks, so I deleted all my decks in the game and imported the decks from the hearthpwn to the HDT to export to the game after this, and one more time it didn't work.
Have already anyone pass by this problem or knows how to fix it?
Thanks guys.

**Comment by riQQ** [comment]
Please provide logs. See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues (sections `HDT crash logs` and `Windows log files`).
