### ISSUE TITLE
Exporting to hearthstone exports 2 copies of card instead of 1

### ISSUE THREAD

**Issue by LuisNavarroOlivares** [HearthSim/Hearthstone-Deck-Tracker#3196]
## Bug report
Exporting since last update sometimes export the wrong number of one low cost card. The decklist contains only 1 copy of that card, but 2 are being exported to HS. The most expensive card of the deck is skiped (as it has already 30 cards). HDT doesnt't show any issues or warnings.

Happened 4 times with different decks. Always duplicated a 2 or 3 cristal cost card, and always skipped the last card of the deck.

### Expected Behavior
Expected to get Antonidas into my Exodia mage instead of 2 copies of frostbolt ;)

### Actual Behavior
See above.

### Steps to reproduce behavior
-Creating a deck in HDT.
-Exporting the deck to HS.

### Log/Screenshots
From the current log file:

7:34:35 PM|Info|ExportingActions.AddCardToDeck >> Adding Frostbolt(1), in collection: 2 normal, 2 golden
7:34:44 PM|Info|ExportingActions.AddCardToDeck >> Adding Archmage Antonidas(1), in collection: 1 normal, 0 golden

...but, the deck got two frostbolts and 0 Antonidas.

Thanks for your efforts!

**Comment by riQQ** [comment]
See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#exporting.

**Comment by azeier** [comment]
HDT now uses Hearthstones native deck string importing system.
