### ISSUE TITLE
Blizzard App transparent

### ISSUE THREAD

**Issue by killjoy01** [HearthSim/Hearthstone-Deck-Tracker#3198]
**Expected Behavior**
The Blizzard app should be displaying correctly, allowing me to log in to Hearthstone using it.

**Actual Behavior**
It's completely transparent, not allowing my to access any buttons or log in or anything. It's still there because links to twitch are accessible.

**Comment by jleclanche** [comment]
What does this have to do with HDT?

**Comment by killjoy01** [comment]
It never happened before I installed it. HDT likely caused it.

**Comment by jleclanche** [comment]
HDT doesn't do anything with Battle.net. Does it happen if HDT is not running?

**Comment by killjoy01** [comment]
It never doesn't happen anymore

**Comment by jleclanche** [comment]
If HDT isn't running and you're getting this, there's no chance that this is an HDT issue. You can try reinstalling ~~Battle.net~~ *Blizzard App*, idk.

**Comment by killjoy01** [comment]
k
