### ISSUE TITLE
Deck-Tracker does not recognise start of game

### ISSUE THREAD

**Issue by JackCandem** [HearthSim/Hearthstone-Deck-Tracker#3199]
### Expected Behavior
HS-Deck-Tracker selects deck/shows deck/tracks cards when game starts

### Actual Behavior
deck list only shows up when deactivating "hide in menue" but does not track mine or enemies deck.  
gold (wins x/3 x/100g) always shows up, even ingame and is of course incorrect.

reinstalling both decktracker and HS and restarting PC n the process does nothing

### Log/Screenshots
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/917867/hdt_log.txt)

**Comment by azeier** [comment]
See here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#its-not-detecting-cards-i-or-my-opponent-play

**Comment by JackCandem** [comment]
I had a second Hearthstone folder which I did not knew of which was not active (and empty) but in a very similar filepath (programfiles instead of programfiles86) after deleting the wrong HS folder and correcting the path it works. thanks !
