### ISSUE TITLE
[Question] Disabling card tracking

### ISSUE THREAD

**Issue by brico54** [HearthSim/Hearthstone-Deck-Tracker#3200]
Hey,
I was wondering if there is any way to get the deck tracker to not track? :P I'd assume this feature is present, but I can't find anything in the options to do it.

I realise this tool is supposed to track your deck and do other fancy stuff, and as such might be overkill for my purpose, but that's all I really want: A static list of my deck. I've already managed to disable everything, except that the deck list gets updated as I draw cards throughout the game.

**Comment by azeier** [comment]
This is not possible, sorry. You generate screenshots of your decks however via `EXPORT > SCREENSHOT`, if that helps somehow.
