### ISSUE TITLE
Overlay not showing after un'goro expansion.

### ISSUE THREAD

**Issue by Anralle** [HearthSim/Hearthstone-Deck-Tracker#3206]
After un'goro expansion the overlay is not showing at all, however before i tried to reinstall everything, changed the hearthstone path and so on, it showed for a moment while I was changing opacity, but when I clicked on hs, it disappeared. In my logs there is something that repeats constantly: PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
Is this something wrong?
I've tried this already: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Setting-up-the-log.config . Didn't work.
Thanks for any help!

**Comment by azeier** [comment]
See #3143
