### ISSUE TITLE
Wrong match log entry for friendly challenge

### ISSUE THREAD

**Issue by hoerny** [HearthSim/Hearthstone-Deck-Tracker#3208]
When I accept a friendly challenge (there is no problem if I initiate the request) the match log entry (in Stats/Constructed/Matches) is written from my opponent point of view:
- the class icons are switched (Class/vs)
- for the opponent name I have my name
- for the Result 'Loss' is written though I'd won the game
- my deck name is properly written

Thanks for checking it.

**Comment by azeier** [comment]
Is this consistent? Can you provide a log? [See here](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)

**Comment by hoerny** [comment]
Hi,

I haven't tried if it's reproducible, I only had this scenario once.
I attached hdt log. As I see the 1st GameEventHandler.SetPlayerHero is correct, the 2nd is not (the case when I accepted the friendly challenge), I played paladin that game.

[hdt_log_1492423023.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/925326/hdt_log_1492423023.txt)

**Comment by riQQ** [comment]
Probably the same as #3573 

```
8:35:45 PM|Info|GameEventHandler.HandleGameStart >> --- Game start ---
8:35:45 PM|Info|GameV2.Reset >> -------- Reset ---------
8:35:45 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
8:35:45 PM|Info|TurnTimer.Start >> Starting turn timer
8:35:45 PM|Warning|TurnTimer.Start >> Turn timer is already running
8:35:45 PM|Info|OverlayWindow.Update >> Refreshed overlay topmost status
8:35:49 PM|Info|TagChangeActions.SetHeroAsync >> Found hero with id=64
8:35:49 PM|Info|GameEventHandler.SetOpponentHero >> Opponent=Paladin
8:35:49 PM|Info|TagChangeActions.SetHeroAsync >> Found hero with id=66
8:35:49 PM|Info|GameEventHandler.SetPlayerHero >> Player=Warlock
8:35:49 PM|Info|GameV2.CacheMatchInfo >> hoerny vs Megaboci
8:35:50 PM|Info|GameV2.CurrentMode >> GAMEPLAY
8:35:50 PM|Info|Player.Draw >> [Player] id=14, cardId=LOE_017, cardName=Keeper of Uldaman, zonePos=1,Info={turn=0, originalZone=DECK}
8:35:50 PM|Info|Player.Draw >> [Player] id=25, cardId=CS2_092, cardName=Blessing of Kings, zonePos=2,Info={turn=0, originalZone=DECK}
8:35:50 PM|Info|Player.Draw >> [Player] id=10, cardId=KAR_077, cardName=Silvermoon Portal, zonePos=3,Info={turn=0, originalZone=DECK}
```
