### ISSUE TITLE
Not tracking cards

### ISSUE THREAD

**Issue by mtkx11** [HearthSim/Hearthstone-Deck-Tracker#3210]
so. the overlay works and the deck is the same but when i enter a game the tracker wont update (such as when i draw or they play a secret) i have looked throght the setting and found no reason why it isnt working.

**Comment by azeier** [comment]
See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#not-working

**Comment by judge2020** [comment]
Are you still having issues?
