### ISSUE TITLE
Deck tracker issue.

### ISSUE THREAD

**Issue by Zenkii** [HearthSim/Hearthstone-Deck-Tracker#3213]
## Bug report
hey everyone! i have a problem with my deck tracker not showing my top decks as well as secret possibility. Its like it thinks i'm in the menu when i'm actually in a ranked game. Here is why i believe so.

When i click "Hide in menu" While being in-game it disappears. So i think that the deck tracer thinks i'm in the menu when i'm actually in a ranked game of Hearthstone.

**Comment by azeier** [comment]
See #3143
