### ISSUE TITLE
Secret overlay doesnt scale

### ISSUE THREAD

**Issue by superyot** [HearthSim/Hearthstone-Deck-Tracker#3216]
### Expected Behavior
Secret overlay should scale with opponent scaling

### Actual Behavior
It doesnt scale at all with any scaling

### Steps to reproduce behavior
Scale opponent / player and see no difference

**Comment by azeier** [comment]
`options (advanced) > overlay > opponent > secret scaling`

**Comment by casper** [comment]
There is no "secret scaling" in the Opponent section. The scaling setting only changes the opponent card overlay. How do I scale the secret overlay without "secret scaling"?

![image](https://user-images.githubusercontent.com/25386/37745071-83b295a6-2d7b-11e8-8cc3-a6823f4d47ed.png)

**Comment by casper** [comment]
Never mind. For those trying to figure it out: there is an "Advanced" checkbox at the bottom of the Options panel. It needs to be checked first for the rest of the options to appear.
