### ISSUE TITLE
it appears that hearthstone and hdt do not have the same permissions

### ISSUE THREAD

**Issue by Stylised** [HearthSim/Hearthstone-Deck-Tracker#3219]
### Expected Behavior
HDT overlay reveals deck

### Actual Behavior
I get the error it appears that hearthstone and hdt do not have the same permissions and deck does not show. Dice and draw % still shows

### Steps to reproduce behavior
- Step 1 Open HDT

### Log/Screenshots
If applicable, provide a log of the session where the problem occoured.  
[hdt_log_1492772697.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/946851/hdt_log_1492772697.txt)

**Comment by riQQ** [comment]
See #2738.

**Comment by UglyCreature** [comment]
@riQQ You are referencing a post with no solution. I am also having this same issue, I read the post you linked and nothing helped. Any idea as to why? Clean HS install, Clean hdt install.

**Comment by riQQ** [comment]
There is no solution yet, but this is a duplicate. Please post further message in the linked issue.

**Comment by judge2020** [comment]
closed in favor of #2738.
