### ISSUE TITLE
Deck tracker not on top after tabbing

### ISSUE THREAD

**Issue by npftd** [HearthSim/Hearthstone-Deck-Tracker#3220]
## Bug report
When I tab out of Hearthstone, and tab back in, the deck tracker is not 'on top'.

### Expected Behavior
Deck tracker should always be shown in Hearthstone, even when you tab in and out.

### Actual Behavior
As above, it just disappears randomly after tabbing. The manual fix for this is Options -> Click "Hide (completely)" -> Unclick "Hide (completely)". But this "fix" does not last very long.

**Comment by riQQ** [comment]
See #3143.

**Comment by judge2020** [comment]
closed in favor of #3143
