### ISSUE TITLE
Since update 1.2.3 the stats wont be tracked

### ISSUE THREAD

**Issue by Curliz** [HearthSim/Hearthstone-Deck-Tracker#3225]
Since the update to 1.2.3, the stats wont be tracked just the wins and loses.

when I open the stats window constructed it dosnt show any stats nor matches of the current season since the update to version 1.2.3 (4thApril)

**Comment by riQQ** [comment]
Check your filters.

**Comment by Curliz** [comment]
![sshot](https://cloud.githubusercontent.com/assets/27973644/25442130/7a4abaf0-2aa4-11e7-988a-c132ea44fb3d.png)

**Comment by riQQ** [comment]
I'm talking about this:
![stats_filer](https://cloud.githubusercontent.com/assets/3404787/25447072/01f05078-2ab4-11e7-90f7-161e224d62a3.png)

**Comment by Curliz** [comment]
Thank you for the help but it isn't the filters. it just shows the stats before the update, afterwards there was no tracking of stats. except the wins and loses where shown in the Menu where you can select your decks beside the deck name. 

since the update i've played over 100 games

![sshot](https://cloud.githubusercontent.com/assets/27973644/25447338/1a2521a4-2ab5-11e7-98ab-6b434eef5314.png)

**Comment by azeier** [comment]
You have coin and region filters set on that screenshot.

**Comment by Curliz** [comment]
yeah that was the problem.
Thank you very much for you help
