### ISSUE TITLE
Export issue: writting spell problem

### ISSUE THREAD

**Issue by alex388** [HearthSim/Hearthstone-Deck-Tracker#3227]
## Bug report
Since the previous version, the export is doing really bad, making writing errors, so no finding cards, and making spell errors in the name of the deck.
Before that version, I din't have any problem.

### Expected Behavior
Export

### Actual Behavior
It searches the cards with writing errors, putting symbols like ":"

### Steps to reproduce behavior
- Just export to hearthstone

### Log/Screenshots
[hdt_log_1493341426.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/963231/hdt_log_1493341426.txt)

**Comment by judge2020** [comment]
Can you see if lowering export speed helps? `options (advanced)` -> `tracker` -> `exporting`

**Comment by alex388** [comment]
Normal (60ms)
But I have proved with all values. The error I see is misspelling

**Comment by azeier** [comment]
Check if any of this helps: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#exporting

**Comment by alex388** [comment]
I've tested all the solutions there azeier, the problem continues. =/

**Comment by azeier** [comment]
HDT now uses Hearthstones native deck string importing system.
