### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Seminko** [HearthSim/Hearthstone-Deck-Tracker#3228]
## Bug report
HSDT keeps crashing.

### Expected Behavior
Not crashing

### Actual Behavior
Crashing

### Steps to reproduce behavior
- Step 1 - open deck tracker
- Step 2 - wait 15 seconds
- Step 3 - observe the crash

### Log/Screenshots
Název chybující aplikace: HearthstoneDeckTracker.exe, verze: 1.2.3.3010, časové razítko: 0x58ee7d71
Název chybujícího modulu: KERNELBASE.dll, verze: 6.1.7601.23714, časové razítko: 0x58bf87bb
Kód výjimky: 0xe0434352
Posun chyby: 0x0000c54f
ID chybujícího procesu: 0x233c
Čas spuštění chybující aplikace: 0x01d2c0545f379072
Cesta k chybující aplikaci: C:\Users\Seminko\AppData\Local\HearthstoneDeckTracker\app-1.2.3\HearthstoneDeckTracker.exe
Cesta k chybujícímu modulu: C:\Windows\syswow64\KERNELBASE.dll
ID zprávy: dd503336-2c47-11e7-9179-005056c00008

Aplikace: HearthstoneDeckTracker.exe
Verze Framework: v4.0.30319
Popis: Proces byl ukončen z důvodu neošetřené výjimky.
Informace o výjimce: System.OutOfMemoryException
   na HearthWatcher.LogReader.LogFileWatcher.ReadLogFile()
   na System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   na System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   na System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   na System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   na System.Threading.ThreadHelper.ThreadStart()

[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/965342/hdt_log.txt)

**Comment by riQQ** [comment]
See #3054.
