### ISSUE TITLE
Feature Request: separate decklist and win/loss stats for each deck version that sees play.

### ISSUE THREAD

**Issue by Tzoshirzup** [HearthSim/Hearthstone-Deck-Tracker#3229]
Would it be possible to add the ability to separately retain the stats and decklist for each and every version of a deck. Recording each version of the deck that sees play in at least one game. I've spent a couple days grinding, playing 40-50 or so games with a deck then changing one or two cards but that stats record doesn't separate how well each version of the deck did or show the previous list and or cards changed. 

I've had a read through the help section and FaQ and can't seem to find the feature if it already exists but I'd imagine it'd be much appreciated and of great help to deck build builders who want to go the 100 games before changing a card route to refining a deck.

**Comment by Tzoshirzup** [comment]
It could be implemented so it has to be manually turned on for a deck and have a manually set limit to deck versions to avoid it exploding the information stored.

**Comment by riQQ** [comment]
Are you talking about the Stats window or the deck overview in the main window?
For the deck overview, you can change what's displayed in the options (`Tracker > Stats > Display: Versions`)

**Comment by NightKev** [comment]
As far as I can tell everything works exactly how you want it to, so this seems to be a non-issue now.
