### ISSUE TITLE
Export to Clipboard ignores Secondary language

### ISSUE THREAD

**Issue by Drakonluke** [HearthSim/Hearthstone-Deck-Tracker#3233]
Case 1,
**If English is the primary language**, selecting "Export" -> "Copy names to clipboard" doesn't take in account the secondary language but only uses English.

Case 2,
But, if English is chosen as secondary language and another language as Primary, then the program asks to choose an export language.

Please, add support for Secondary Language if English is set as Primary to make Case 1 work like Case 2.

**Comment by azeier** [comment]
The case 2 behavior does not exist, exporting always uses the primary language.
