### ISSUE TITLE
Options help

### ISSUE THREAD

**Issue by the1crookie** [HearthSim/Hearthstone-Deck-Tracker#3236]
I can't seem to find the option to turn off the hearthstones over the opponents hand to tell how many cards are in his hand.  It is really intrusive and not something I want.

**Comment by the1crookie** [comment]
I can't seem to find the option to turn off the hearthstones over the opponents hand to tell how many cards are in his hand.  It is really intrusive and not something I want.

**Comment by riQQ** [comment]
`Options > Overlay > General`: Check `Hide card-age` and `Hide card-marks`.
