### ISSUE TITLE
'Card Age' is misinterpreted by DT creators

### ISSUE THREAD

**Issue by s1ww** [HearthSim/Hearthstone-Deck-Tracker#3239]
'Card Age' description in Deck Tracker is used for pinning number of max mana/next round when card was drawed, not for showing the actual Age of card in hand.

I have spent more than hour searching option that enables real display of cards age and this time was wasted.

Need of that information was a reason why I have installed DT after all,  "how many turns the card remains in opponents hand", where newely drawed cards have age of 0.

Did you skipped that obvious option intentionally?
M.S

**Comment by azeier** [comment]
How would that be different "turn drawn"?
(Given, the option naming is confusing)

**Comment by s1ww** [comment]
I have turned it off at all, what value have information that drawed card has number 14 ? it makes chaos, drawed cards should have number 0, to make interpretation instant and easy. E.g. If any card in hand would get big value, then we know that opponent is keeping some special ace.

**Comment by azeier** [comment]
Changing values would make it very hard to keep track of specific cards.

And as I said, there is really not much difference between the two methods. With the current implementation you can tell your opponent is keeping something special if he has a low number in hand on turn 15 just the same.

I don't see any point in changing this, sorry.

**Comment by s1ww** [comment]
Uninstalling then. I cant watch this solution.
