### ISSUE TITLE
HDT crashes on start

### ISSUE THREAD

**Issue by lepatrice** [HearthSim/Hearthstone-Deck-Tracker#3240]
HDT worked fine for all the time but today after I left the computer for lunch I found HDT crashed. I tried to restart hdt but it crashed on start. After that i restartet the computer (win10), again HDT crashed at start. Also I uninstalled it and deleted the remaining files manually. After new installation, and restarting the computer it crashed again while starting HDT. So no I don't know what to do.

8:18:30 PM|Info|Core.Initialize >> HDT: 1.2.5.3045, Operating System: Windows 10 Pro 15063, .NET Framework: 460798
8:18:30 PM|Info|Updater.StartupUpdateCheck >> Checking for updates
8:18:30 PM|Info|Updater.GetReleaseUrl >> Downloading releases file
8:18:41 PM|Info|Updater.GetReleaseUrl >> using 'live' release: https://github.com/HearthSim/HDT-Releases
8:18:45 PM|Info|Updater.SquirrelUpdate >> Checking for updates (ignoreDelta=False)
8:18:48 PM|Info|Updater.SquirrelUpdate >> No new updated available
8:18:49 PM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
8:18:49 PM|Info|ConfigManager.ConvertLegacyConfig >> changed config values
8:18:49 PM|Info|ThemeManager.LoadThemes >> Found theme: classic
8:18:49 PM|Info|ThemeManager.LoadThemes >> Found theme: dark
8:18:49 PM|Info|ThemeManager.LoadThemes >> Found theme: frost
8:18:49 PM|Info|ThemeManager.LoadThemes >> Found theme: minimal
8:18:49 PM|Info|GameV2.Reset >> -------- Reset ---------
8:18:49 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
8:18:50 PM|Info|HsReplayDecks.LoadFromDisk >> Loading data from disk...
8:18:50 PM|Info|HsReplayDecks.Load >> Loaded from disk: 
8:18:50 PM|Info|HsReplayDecks.Load >> Cached data was not found or stale. Fetching latest...
8:18:50 PM|Info|ApiWrapper.GetAvailableDecks >> Fetching available decks...
8:18:50 PM|Info|ApiWrapper.GetUploadToken >> Requesting new upload token...
8:18:50 PM|Info|GameV2.Reset >> -------- Reset ---------
8:18:50 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
8:18:50 PM|Info|BackupManager.Run >> Running BackupManager
8:18:50 PM|Info|BackupManager.Run >> Creating backup for today
8:18:50 PM|Info|PluginManager.LoadPluginsFromPath >> Loading Plugins...
8:18:50 PM|Info|Helper.GetCurrentRegion >> Region: EU
8:18:50 PM|Info|BackupManager.Run >> Running BackupManager
8:18:50 PM|Info|BackupManager.Run >> Backup for today already exists

I also tried to delete the config.xml

that is what I found in the Windows log

Programm HearthstoneDeckTracker.exe, Version 1.2.5.3045 kann nicht mehr unter Windows ausgeführt werden und wurde beendet. Überprüfen Sie den Problemverlauf in der Systemsteuerung "Sicherheit und Wartung", um nach weiteren Informationen zum Problem zu suchen.
 Prozess-ID: 32f4
 Startzeit: 01d2c69529ede459
 Beendigungszeit: 3
 Anwendungspfad: C:\Users\Patrick\AppData\Local\HearthstoneDeckTracker\app-1.2.5\HearthstoneDeckTracker.exe
 Berichts-ID: c991c69e-b082-4136-8f73-b1009c69ccd8
 Vollständiger Name des fehlerhaften Pakets: 
 Auf das fehlerhafte Paket bezogene Anwendungs-ID: 

I also tried to start HDT as Admin and in the compatibility mode.

any idea?

**Comment by riQQ** [comment]
Please provide a windows event log with the source `.NET Runtime`. See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues.

**Comment by BrotherDylan** [comment]
Any update? I am having the same issue on the Mac version. It just started yesterday after the update was released. I am unable to create a windows event log. Is there a way to do that on a mac?

**Comment by azeier** [comment]
You wanna to go https://github.com/HearthSim/HSTracker for mac.
