### ISSUE TITLE
Can't use touch to scroll lists

### ISSUE THREAD

**Issue by Troldann** [HearthSim/Hearthstone-Deck-Tracker#3243]
### Expected Behavior
Dragging my finger (with a touchscreen) on a list, for example the list of decks or the list of cards in a deck or the options screen will scroll the window akin to using a mousewheel or precision touchpad gesture.

### Actual Behavior
The tracker just moves selection based on where I'm touching without doing any scrolling actions. It seems as if it's treating my touch as a cursor hover possibly? I don't know enough about the Windows Touch APIs to know for certain.

### Steps to reproduce behavior
- Step 1
Using a touchscreen try to scroll a list as one would expect with an iOS or Android device
- Step 2
The scrolling doesn't happen

### Log/Screenshots
https://www.youtube.com/watch?v=PTldkAHA_As [https://www.youtube.com/watch?v=PTldkAHA_As](url)

**Comment by azeier** [comment]
This will be fixed with the next update.
