### ISSUE TITLE
[feature request] Filter replays by particular cards

### ISSUE THREAD

**Issue by krzikalla** [HearthSim/Hearthstone-Deck-Tracker#3244]
I am looking for a feature that lists (and thus lets me investigate) only those replays, where a certain card plays a role. Such a feature would be great in order to evaluate the impact of a card.

The filter should contain a field for the card name and some check boxes (maybe a radio button): 
* card mulliganed
* card drawn 
* card played

**Comment by azeier** [comment]
Issue moved to [HearthSim/HSReplay.net #283](https://github.com/HearthSim/HSReplay.net/issues/283) via [**ZenHub**](https://www.zenhub.com/)
