### ISSUE TITLE
import from web

### ISSUE THREAD

**Issue by Darkreapertv** [HearthSim/Hearthstone-Deck-Tracker#3245]
## Before we start
- Please doublecheck there is no existing issue for your problem/feature request.  
- Please delete any obsolete sections (including this one) from this template before submitting your issue.

### Expected Behavior
Import from web dont import new deck list once your at the site

### Actual Behavior
When you click on import from web it imports last deck that was imported not new deck from the page your on

### Steps to reproduce behavior
- Step 1 import from web loads last deck imported 
- Step 2 import from web again same issue

### Log/Screenshots
If applicable, provide a log of the session where the problem occoured.  
See here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by jleclanche** [comment]
Which website are you using it? Can you include an url?

**Comment by azeier** [comment]
Sounds like you still have the old url in your clipboard. Try copying the new one before clicking import again.
