### ISSUE TITLE
After renaming my deck HStracker crashes

### ISSUE THREAD

**Issue by TheRamenGod** [HearthSim/Hearthstone-Deck-Tracker#3246]
## Before we start
- Please doublecheck there is no existing issue for your problem/feature request.  
- Please delete any obsolete sections (including this one) from this template before submitting your issue.

### Expected Behavior
Describe the expected behavior here

### Actual Behavior
Describe the actual behavior here

### Steps to reproduce behavior
- Step 1
- Step 2

### Log/Screenshots
If applicable, provide a log of the session where the problem occoured.  
See here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by TheRamenGod** [comment]
never mind I restart HStracker and it's there

**Comment by TheRamenGod** [comment]
never mind still broken and I reinstalled feels bad man

**Comment by azeier** [comment]
HSTracker as in the OSX one?

**Comment by jleclanche** [comment]
Please direct macOS HSTracker bugs here: https://github.com/HearthSim/HSTracker

With more details if you will :)
