### ISSUE TITLE
Stats Completely Gone

### ISSUE THREAD

**Issue by txbobcat33** [HearthSim/Hearthstone-Deck-Tracker#3247]
When I open HDT, all of my deck stats are completely gone.  I have backups that are listed on the settings page except none of them will open and I cannot get back the stats that I had yesterday.

4:36:55 PM|Info|Core.Initialize >> HDT: 1.2.5.3045, Operating System: Windows 10 Pro 15063, .NET Framework: 460798
4:36:56 PM|Info|Updater.StartupUpdateCheck >> Checking for updates
4:36:56 PM|Info|Updater.GetReleaseUrl >> Downloading releases file
4:36:56 PM|Info|Updater.GetReleaseUrl >> using 'live' release: https://github.com/HearthSim/HDT-Releases
4:36:57 PM|Info|Updater.SquirrelUpdate >> Checking for updates (ignoreDelta=False)
4:36:57 PM|Info|Updater.SquirrelUpdate >> No new updated available
4:36:58 PM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
4:36:58 PM|Info|ThemeManager.LoadThemes >> Found theme: classic
4:36:58 PM|Info|ThemeManager.LoadThemes >> Found theme: dark
4:36:58 PM|Info|ThemeManager.LoadThemes >> Found theme: frost
4:36:58 PM|Info|ThemeManager.LoadThemes >> Found theme: minimal
4:36:58 PM|Info|GameV2.Reset >> -------- Reset ---------
4:36:58 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
4:36:59 PM|Info|HsReplayDecks.LoadFromDisk >> Loading data from disk...
4:36:59 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
4:36:59 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
4:37:00 PM|Info|MainWindow.SelectDeck >> Switched to deck: egg (v1.0)
4:37:00 PM|Info|GameV2.Reset >> -------- Reset ---------
4:37:00 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
4:37:01 PM|Info|BackupManager.Run >> Running BackupManager
4:37:01 PM|Info|BackupManager.Run >> Backup for today already exists
4:37:01 PM|Info|PluginManager.LoadPluginsFromPath >> Loading Plugins...
4:37:01 PM|Info|PluginWrapper.Load >> Loading Arena Helper
4:37:01 PM|Info|Plugin.LoadData >> Arena Helper: Using userdata version of tierlist
4:37:01 PM|Info|PluginWrapper.IsEnabled >> Enabled Arena Helper
4:37:01 PM|Info|Helper.GetCurrentRegion >> Region: US
4:37:01 PM|Info|BackupManager.Run >> Running BackupManager
4:37:01 PM|Info|BackupManager.Run >> Backup for today already exists
4:37:01 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
4:37:01 PM|Info|LogWatcherManager.OnLogFileFound >> FullScreenFX
4:37:01 PM|Info|LogWatcherManager.OnLogFileFound >> LoadingScreen
4:37:01 PM|Info|LogWatcherManager.OnLogFileFound >> Rachelle
4:37:01 PM|Info|ApiWrapper.UpdateAccountStatus >> Checking account status...
4:37:01 PM|Info|HsReplayDecks.Load >> Loaded from disk: Count=1590, ServerTS=5/12/2017 1:22:44 AM, Downloaded=5/11/2017 8:58:32 PM Age=19:38:28.6418406
4:37:01 PM|Info|HsReplayDecks.Load >> Complete: Count=1590, ServerTS=5/12/2017 1:22:44 AM, Downloaded=5/11/2017 8:58:32 PM Age=19:38:28.6418406
4:37:01 PM|Info|GameV2.CurrentMode >> LOGIN
4:37:01 PM|Info|GameV2.CurrentMode >> HUB
4:37:01 PM|Info|GameV2.CurrentMode >> TOURNAMENT
4:37:01 PM|Info|GameV2.CurrentMode >> HUB

**Comment by riQQ** [comment]
Please check the filters.

**Comment by txbobcat33** [comment]
All the filters are set to All.

**Comment by pagem** [comment]
Was there a fix for this issue?

I just noticed that since last update my stats are gone under the stats tab. Nothing for Arena or Constructed.

I had this same problem several years ago and it seemed to go away.

Note: I don't use the full stats much these days instead I use the stat pane that appears when you select a deck. But I wanted to know fuller stats across all matches today when I noticed this issue.

**Comment by riQQ** [comment]
So your decks still have stats?

**Comment by Thrombin** [comment]
I currently have this problem. All of my decks are showing "NO STATS" under them.  I played with a deck yesterday and it showed stats while I was playing but when I logged in today it was back to 0-0. Now it's showing stats again but it's the only deck that is!

**Comment by riQQ** [comment]
Have you checked this https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#games-andor-stats-are-not-being-saved?

**Comment by Thrombin** [comment]
Display was set to Today only. That explains it!

Thanks.
