### ISSUE TITLE
start of the week

### ISSUE THREAD

**Issue by mmiat** [HearthSim/Hearthstone-Deck-Tracker#3249]
if I set "show this week" I've no results
but if I set "show today" I can see my matches

**Comment by mmiat** [comment]
today (sunday) the same issue

**Comment by jleclanche** [comment]
Take a look at your windows localization settings, make sure the first day of the week setting is set to monday. If you are on the en-us locale, it will be Sunday by default.

http://freewindowsvistatutorials.com/changeFirstDayOfTheWeekWhenWeeksStartInWindows7.php

**Comment by mmiat** [comment]
I'm italian, my fist day of the week is monday
but even if it were sunday, "this week" should always show at least "today" matches

**Comment by mmiat** [comment]
i've tried to change card language in italian, but this week still starts from sunday
