### ISSUE TITLE
Suggestion about track the card back used by opponent int every game

### ISSUE THREAD

**Issue by chucklu** [HearthSim/Hearthstone-Deck-Tracker#3250]
Just a suggestion.
I play the game  in casual mode most time.
I will concede the game when I meet someone who is not using the original car back.
When I replay the game or check the stats,it would be better if you can provide the information about the card back the opponent used.
I need to check whether I concede every time when I met the opponent who was not using the original card back.

**Comment by jleclanche** [comment]
We have this info on HSReplay.net but we're not displaying it anywhere.
