### ISSUE TITLE
How does HDT know my cards?

### ISSUE THREAD

**Issue by Johnny112233** [HearthSim/Hearthstone-Deck-Tracker#3252]
Hi,
i'm using HDT for quite a while now and i'm very happy with it.
A long while ago i read somewhere, that HDT only uses visual components to recognize which card you drew.
Why i got some doubts in that is, that HDT often know which card i am drawing even before i can see it.

The same thing is with the new method to import cards into HS. I really like that it is showing the missing cards now before you create the deck in game. But how does HDT know which cards i don't have before i tried to create the deck?
It can't be historical data because i was crafting some cards while HDT showed me my missing cards. After trying to re-import again, HDT already knew that i had some of the missing cards now.

Can you explain me the method how this works? I'm not a programmer myself but i was just interested in how things work :)

**Comment by jleclanche** [comment]
Card data is available in the HS log files, through a very powerful `Power.log` file:

https://github.com/jleclanche/fireplace/wiki/How-to-enable-logging

Collection etc are available in-memory, HDT knows how to find it.

**Comment by jleclanche** [comment]
Feel free to swing by [the Discord server](https://discord.gg/hearthsim) if you have more questions!
