### ISSUE TITLE
Taking a snap shot of hearthstone to include what visual changes of the deck tracker

### ISSUE THREAD

**Issue by HartnettMichael** [HearthSim/Hearthstone-Deck-Tracker#3256]
If we can make a toggle option to include the visuals provided by the deck tracker to be a part of the print screen taken by hearthstone.

**Comment by azeier** [comment]
It's not (easily) possible to add this to default screenshots, but you can use `Screenshot` hotkey under  `options (advanced) > tracker > hotkeys` for it.
