### ISSUE TITLE
HDT fails to export correctly following install of Wacom intuos drivers on Windows 10

### ISSUE THREAD

**Issue by rjthompson** [HearthSim/Hearthstone-Deck-Tracker#3259]
## Bug report
When exporting to HS from HDT, only a portion of the deck is created. This started after installation of Wacom Intuos tablet. This coincides with a bug that causes the HS collections search bar to behave inconsistently. The problem was rectified by disabling the "Touch Keyboard and Handwriting Panel" service.

### Expected Behavior
On export HDT creates the full deck

### Actual Behavior
On export HDT creates only a portion of the deck

### Steps to reproduce behavior
- Install wacom intuos drivers
- Export decklist from HDT to HS in my collection manager

### Log/Screenshots
Logs show deck is exported successfully, despite this not being the case.

**Comment by azeier** [comment]
See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#exporting

**Comment by azeier** [comment]
I also just realized fixing that will no longer be necessary with the addition of native deck string importing in the next update! Yay!

**Comment by rjthompson** [comment]
Thanks, my bad for not seeing this!

**Comment by azeier** [comment]
No longer an issue :).
