### ISSUE TITLE
Secrets sometimes greyed out incorrectly

### ISSUE THREAD

**Issue by garyking** [HearthSim/Hearthstone-Deck-Tracker#3262]
I was playing a game vs. Mage, and they played two Ice Blocks from their deck. They then played Primordial Glyph and then the secret that they got from it. Ice Block was greyed out in HDT, but the secret was in fact Ice Block.

So, if the secret is a generated card, then it should not be greyed out in the HDT panel.

**Comment by tympollack** [comment]
On a related note, hunter had a secret down and Hidden Cache did not grey out after I played a minion (though Snipe worked correctly).

**Comment by garyking** [comment]
@tympollack That's a problem that can't be fixed as far as I know, since HDT doesn't know if the opponent has a minion in their hand.

**Comment by tympollack** [comment]
@garyking Ahh that's true lol. Thanks for helping my brain grok.

**Comment by azeier** [comment]
https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/5a25bc54665c8e7266ebbd6687e5834afe6e89cb Fixes this
