### ISSUE TITLE
Add a filter for Rank in the Stats list

### ISSUE THREAD

**Issue by Apophany** [HearthSim/Hearthstone-Deck-Tracker#3263]
Having looked through previous issues, it seems that HDT used to support filtering by rank in the constructed stats (#692):

![image](https://cloud.githubusercontent.com/assets/13717772/26529747/b7def0b6-43bd-11e7-84f0-65c94e9a69cf.png)

I guess at some point this was removed. I'm running v1.2.5 and all I see is:

![image](https://cloud.githubusercontent.com/assets/13717772/26529763/23438a4c-43be-11e7-914c-49ea0f7b49b2.png)

I do believe this is genuinely useful feature that should be reintroduced. Normally statistics for decks between say, r10-20 are not as applicable to decks played at say legend - r5. Not just because of differing skill levels, but also due to different deck compositions at higher ranks vs lower.

Thanks

**Comment by azeier** [comment]
The filter still exists, you need to select "Ranked" as the game mode and it will show up. It's a bit unintuitive at the moment, sorry.

**Comment by Apophany** [comment]
Oh cool! I didn't realise this. Feel free to close the issue. Thanks
