### ISSUE TITLE
Crash after using new export copy button multiple times

### ISSUE THREAD

**Issue by djdookie** [HearthSim/Hearthstone-Deck-Tracker#3265]
## Bug report
Even if I start HDT with admin privileges, when I click one of the two copy deck buttons in the new export section multiple times HDT crashed with the following exception:

> System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))
>    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
>    at System.Windows.Clipboard.Flush()
>    at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
>    at System.Windows.Clipboard.SetDataInternal(String format, Object data)
>    at System.Windows.Clipboard.SetText(String text, TextDataFormat format)
>    at System.Windows.Clipboard.SetText(String text)
>    at Hearthstone_Deck_Tracker.FlyoutControls.DeckExport.DeckExportViewModel.<CopyAll>d__24.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Expected Behavior
No crash after copying  a decklist

### Actual Behavior
Clicking one of the new copy buttons twice leads to a HDT crash. Everytime, reproducible

### Steps to reproduce behavior
1. Rightclick a deck and chose export
2. Click one of the two copy buttons multiple times

### Environment
I use Microsoft Windows 10 x64 v1703

**Comment by azeier** [comment]
I can click it an arbitrary number of times without anything happening.

https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/e70c222057e615165de54ed4bcedcdcf2817b9ae should however take care of it.

**Comment by djdookie** [comment]
Thanks.

**Comment by djdookie** [comment]
https://stackoverflow.com/questions/12769264/openclipboard-failed-when-copy-pasting-data-from-wpf-datagrid

According to this thread, instead of 
`Clipboard.SetText(data);`
the usage of
`Clipboard.SetDataObject(data);`
should fix that common WPF issue.

**Comment by azeier** [comment]
Perfect, thanks :).
