### ISSUE TITLE
Freezes and Crashes of the Game

### ISSUE THREAD

**Issue by scred666** [HearthSim/Hearthstone-Deck-Tracker#3269]
After the last update of Hearststone, the game completely freezes when you work with your wonderful addon, or just crashes, without the add-on everything is completely ok.
What to do in this situation?
Thank you.
[hdt_log_1496485927.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1049550/hdt_log_1496485927.txt)
[hdt_log_1496470268.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1049548/hdt_log_1496470268.txt)
[hdt_log_1496470190.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1049551/hdt_log_1496470190.txt)
[hdt_log_1496428784.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1049549/hdt_log_1496428784.txt)
[hdt_log_1496428669.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1049547/hdt_log_1496428669.txt)

Windows Logs

Приложение: Hearthstone.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: код исключения c0000005, адрес исключения 778B49FD

Приложение: Hearthstone.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: код исключения c0000005, адрес исключения 691941F4

Имя сбойного приложения: Hearthstone.exe, версия: 8.2.0.19506, метка времени: 0x579375ff
Имя сбойного модуля: ntdll.dll, версия: 10.0.15063.0, метка времени: 0xa82cc161
Код исключения: 0xc0000374
Смещение ошибки: 0x000d9a8a
Идентификатор сбойного процесса: 0x1d04
Время запуска сбойного приложения: 0x01d2dbca5ab5763f
Путь сбойного приложения: D:\Games\Hearthstone\Hearthstone.exe
Путь сбойного модуля: C:\WINDOWS\SYSTEM32\ntdll.dll
Идентификатор отчета: bd2f3243-df59-4e17-8da0-d998aa6ffd56
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 

Имя сбойного приложения: Hearthstone.exe, версия: 8.2.0.19506, метка времени: 0x579375ff
Имя сбойного модуля: igd10umd32.dll, версия: 9.17.10.4459, метка времени: 0x573dfc10
Код исключения: 0xc0000005
Смещение ошибки: 0x000141f4
Идентификатор сбойного процесса: 0x2fb4
Время запуска сбойного приложения: 0x01d2dbca222f8984
Путь сбойного приложения: D:\Games\Hearthstone\Hearthstone.exe
Путь сбойного модуля: C:\WINDOWS\system32\igd10umd32.dll
Идентификатор отчета: aea96f8c-3d62-4a37-aeb8-3d4c0f1132f2
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 

Имя сбойного приложения: Hearthstone.exe, версия: 8.2.0.19506, метка времени: 0x579375ff
Имя сбойного модуля: ntdll.dll, версия: 10.0.15063.0, метка времени: 0xa82cc161
Код исключения: 0xc0000005
Смещение ошибки: 0x000449fd
Идентификатор сбойного процесса: 0x24cc
Время запуска сбойного приложения: 0x01d2dbca4598159f
Путь сбойного приложения: D:\Games\Hearthstone\Hearthstone.exe
Путь сбойного модуля: C:\WINDOWS\SYSTEM32\ntdll.dll
Идентификатор отчета: a8db88a2-4e61-488f-8521-dfcdb38117fc
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом:

**Comment by azeier** [comment]
Try reinstalling HDT and rebooting

**Comment by scred666** [comment]
It seems to help
I did not think that I could help, did not reinstall even

TU

**Comment by azeier** [comment]
cool :)

**Comment by scred666** [comment]
Sorry, but problem is back

**Comment by azeier** [comment]
Same suggestions again.

If it doesn't help I don't know what it might be, sorry.

**Comment by scred666** [comment]
https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1049921/hdt_log.txt

Mb someone can help

**Comment by GAFBlizzard** [comment]
I'm having the same or a similar problem.  Since the last couple of days, HDT seems to crash every other match or so without recording the match.  It never happened before.  Let me know if there is any crash info I can report.

**Comment by GAFBlizzard** [comment]
Stack trace:

System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Hearthstone_Deck_Tracker.LogReader.Handlers.FullScreenFxHandler.Handle(LogLine logLine, IGame game)
   at Hearthstone_Deck_Tracker.LogReader.LogWatcherManager.OnNewLines(List`1 lines)
   at HearthWatcher.LogWatcher.<Start>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by azeier** [comment]
You need to update HDT to the latest version.

**Comment by GAFBlizzard** [comment]
Sorry, you are correct.  After updating the crashes seem to have stopped.  Thanks!
