### ISSUE TITLE
Proposal: Store new deckstrings in Deck objects

### ISSUE THREAD

**Issue by djdookie** [HearthSim/Hearthstone-Deck-Tracker#3270]
Like with unique deck GUIDs, I think it would be useful to additionally store the new unique HS deckstrings in `Hearthstone_Deck_Tracker/Hearthstone/Deck` objects.
(https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/Hearthstone/Deck.cs)

Then just save them while importing or creating new decks with e.g. `Hearthstone Deck Tracker/Hearthstone/DeckSerializer.cs`

Exchanging deckstrings should always be quite easy then, because it holds all decklist information.

**Comment by azeier** [comment]
Why? All the information is already there.

**Comment by djdookie** [comment]
It is a helpful meta information without the need of any conversions.
For example, you don't need to convert the decklist information into a deckstring if you want to export the deck via deckstring. Conversions between deckstring and decklist can be faulty, the deckstring cannot.

I think it is even the better GUID, because it identifies a deck uniquely while holding it's complete decklist at the same time. The GUID is randomly generated and has nothing to to with the decks content.

**Comment by azeier** [comment]
But what's the usecase where that information needs to be stored rather than converted on demand? Faulty conversions seem very unlikely.

I could maybe see a case when you are building a new system to use them as the primary way to store decks, but switching over to it or storing them in addition seems unnecessary.

Using it instead of the GUID does not work with the current system because decks have the same GUID across versions.

**Comment by djdookie** [comment]
Ah ok, I see the necessity of GUIDs.
On demand conversion is a good way here, if you rarely do exports to deckstrings.
For convenience reasons, one could give Deck a property named Deckstring which returns it's deckstring using the DeckSerializer.Serialize() method. Then you don't store double information and have easy access without the need to use Helper classes/methods.
Just an idea. ;)

**Comment by azeier** [comment]
Convenience would make sense if it's something that's frequently used (like `"someString".Trim()` instead of `StringHelper.Trim("someString")`), but I don't really see myself accessing a `deck.DeckString` property very often after the initial implementation.

**Comment by djdookie** [comment]
It could be useful for addon devs like me!
But this is what we have extension methods for. ;)
Thanks nevertheless.
