### ISSUE TITLE
The problem is back

### ISSUE THREAD

**Issue by scred666** [HearthSim/Hearthstone-Deck-Tracker#3274]
I already created a ticket. They answered me and it helped, but the problem returned.
Link to the old report: https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3269
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1049921/hdt_log.txt)

**Comment by azeier** [comment]
please dont open duplicate issues
