### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by XAlevy** [HearthSim/Hearthstone-Deck-Tracker#3280]
When i try to install HDT apeears error
![error](https://user-images.githubusercontent.com/25296688/26843147-865dfeea-4aef-11e7-8ee1-0451443edfb6.png)

LOG
[error.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1055938/error.txt)

**Comment by azeier** [comment]
There is a problem with the .NET Framework installation on your system. Specifically, this file `C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll` seems to be missing.

 Try running the [Microsoft .NET Framework Repair Tool](https://www.microsoft.com/en-us/download/details.aspx?id=30135) and/or reinstalling the latest .NET Framework if you are on Windows 8 or lower.

**Comment by XAlevy** [comment]
thanks you
you help me very much <3
