### ISSUE TITLE
Exporting request

### ISSUE THREAD

**Issue by grobson13** [HearthSim/Hearthstone-Deck-Tracker#3290]
Any chance of going back to the old export method until the bug is fixed where you get stuck in the collection manager after importing a deck into hearthstone with the new feature?

**Comment by judge2020** [comment]
This bug is a problem for Hearthstone itself. HDT no longer interacts with HS when exporting so there is nothing we can do to fix it.

About going back to the old exporting method: 

https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3287#issuecomment-307339091 by @azeier 

> We don't be adding back the old exporting system, sorry. It's something I really don't want to maintain when there's an official system in place that does the job (with this exception) better than ours in the first place.
> You'll have to ask Blizzard for it. They have a way in arena now to remove golden cards, adding the same thing for constructed is not unreasonable.
> Closing this since the original issue is a problem with Hearthstone, not HDT.
