### ISSUE TITLE
There must be good if deck from each region in one account not mixed together in the data. 

### ISSUE THREAD

**Issue by hvernanda** [HearthSim/Hearthstone-Deck-Tracker#3292]
Edit:
Sorry, my comment didn't appear properly.
As i mentioned in the title and thanks to judge2020 about the explanation, the deck from each Region mixed together in the stats. It is difficult to decide where is my stat from Region Asia for instance or from America maybe. So, it is must be good if each regions has its own data.
Sorry for my bad english

**Comment by azeier** [comment]
What are you trying to say?

**Comment by judge2020** [comment]
He likely doesn't want stats data from different regions on the same account mixed together, A "profiles" or regions-type system maybe. @azeier

**Comment by azeier** [comment]
I see - I thought there was an issue for that actually. It's something I'd like to have at some point. At the moment you can only filter your stats `STATS > CONSTRUCTED/ARENA` by region.

**Comment by hvernanda** [comment]
@azeier Ahh, I see. i just realize that there is a filter for region on the left. Thank you
