### ISSUE TITLE
Inherit Windows 8/10 system color for the UI color.

### ISSUE THREAD

**Issue by judge2020** [HearthSim/Hearthstone-Deck-Tracker#3294]
An interesting feature to consider implementing is to have HDT inherit the Windows 10 system color for the main UI color. 

![image](https://user-images.githubusercontent.com/8601934/27082131-84e5dcc8-5011-11e7-9a83-a80643ce8640.png)

#### Technical:

There's a value at the key  `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM`

DWORD `ColorizationColor` 

Stored as a decimal, turned hexadecimal and removing the first two characters  (eg `c400b7c3` -> `00b7c3`) gives the current dominate color the user has chosen.

This could be an option in settings to have it inherit Windows color, or it could be enabled by default to give Windows 10 the feeling of unification between apps (which is Microsoft's plan).

**Comment by azeier** [comment]
Done via #3387
