### ISSUE TITLE
After ctrl+tab the buttons in the menu do not react.

### ISSUE THREAD

**Issue by paulmurza** [HearthSim/Hearthstone-Deck-Tracker#3298]
## Before we start
- Please doublecheck there is no existing issue for your problem/feature request.  
- Please delete any obsolete sections (including this one) from this template before submitting your issue.

### Expected Behavior
Describe the expected behavior here

### Actual Behavior
Describe the actual behavior here

### Steps to reproduce behavior
- Step 1
- Step 2

### Log/Screenshots
If applicable, provide a log of the session where the problem occoured.  
See here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by azeier** [comment]
Works completely fine for me. What does ctrl-tab even do?

**Comment by judge2020** [comment]
ctrl+tab in most applications is switching the currently selected item, in chrome and web browsers it's the current tab.

**Comment by azeier** [comment]
Right, but it has no effect in HDT.

**Comment by paulmurza** [comment]
Ctro+tab brings overwolf over hearthstone to work together. The round menu appears for me if I press ctrl +tab, after that the round buttons around are not coloured, yoi can practically see hearthstone through them and have no functionality

**Comment by azeier** [comment]
I think you have the wrong repo then, we don't use or have anything to do with overwolf.
