### ISSUE TITLE
Feature Request: Most likely card(s) opponent will play next turn.

### ISSUE THREAD

**Issue by krieg7b** [HearthSim/Hearthstone-Deck-Tracker#3303]
## Section in the opponents overlay window showing:
- Cards they can play next turn based on hero and predicted deck type.  
- Sorted by card most likely to be played based on deck type and board state.

## Description of feature:
HDT can either use decks from the users deck list of access HearthStats to get most popular decks. 
It can then predict based on mana count, Hero, and cards already played, what card(s) the opponent will most likely play next turn.
This would give the user the same very valuable incites that the serious hearthstone experts and hearthstone geniuses do in their heads. It will make them more aware of what they should try and play around and what they should try and play into.

**Comment by azeier** [comment]
Not something we will be doing, sorry.

See here for more information: https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues?q=is%3Aissue+prediction+is%3Aclosed

**Comment by judge2020** [comment]
similar

#2729 #2640 #263 #21 #6

**Comment by krieg7b** [comment]
Read your posts. Hadn't thought through the implications. 
Agree with the reasoning...
Keep up the good work.
