### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by githubuser98374** [HearthSim/Hearthstone-Deck-Tracker#3310]
## Bug report
HDT crashes whenever i try to start it. Last time it worked for me was July 13th. I've try uninstall/re-install with no luck.

### Log/Screenshots
System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. Den angivne fil blev ikke fundet.
File name: 'System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at Hearthstone_Deck_Tracker.Utility.BackupManager.CreateBackup(String fileName)
   at Hearthstone_Deck_Tracker.Utility.BackupManager.Run()
   at Hearthstone_Deck_Tracker.Core.<Initialize>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

---

8:20:16 PM|Info|Core.Initialize >> HDT: 1.3.5.3102, Operating System: Windows 7 Professional 7601, .NET Framework: 394271
8:20:16 PM|Info|Updater.StartupUpdateCheck >> Checking for updates
8:20:16 PM|Info|Updater.GetReleaseUrl >> Downloading releases file
8:20:17 PM|Info|Updater.GetReleaseUrl >> using 'live' release: https://github.com/HearthSim/HDT-Releases
8:20:18 PM|Info|Updater.SquirrelUpdate >> Checking for updates (ignoreDelta=False)
8:20:19 PM|Info|Updater.SquirrelUpdate >> No new updated available
8:20:19 PM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
8:20:20 PM|Info|ThemeManager.LoadThemes >> Found theme: classic
8:20:20 PM|Info|ThemeManager.LoadThemes >> Found theme: dark
8:20:20 PM|Info|ThemeManager.LoadThemes >> Found theme: frost
8:20:20 PM|Info|ThemeManager.LoadThemes >> Found theme: minimal
8:20:20 PM|Info|GameV2.Reset >> -------- Reset ---------
8:20:20 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
8:20:20 PM|Info|OverlayWindow.SetTopmost >> Hearthstone window not found
8:20:21 PM|Info|GameV2.Reset >> -------- Reset ---------
8:20:21 PM|Info|OpponentSecrets.ClearSecrets >> Cleared secrets
8:20:21 PM|Info|BackupManager.Run >> Running BackupManager
8:20:21 PM|Info|BackupManager.Run >> Creating backup for today
8:20:21 PM|Info|HsReplayDecks.Load >> Loaded from disk: Count=1078, ServerTS=6/25/2017 4:15:21 PM, Downloaded=6/25/2017 8:18:21 PM Age=00:01:59.9577993
8:20:21 PM|Info|HsReplayDecks.Load >> Complete: Count=1078, ServerTS=6/25/2017 4:15:21 PM, Downloaded=6/25/2017 8:18:21 PM Age=00:01:59.9577993

**Comment by riQQ** [comment]
Try to repair or reinstall the .NET Framework.

**Comment by githubuser98374** [comment]
That solved the problem. Thank you!
