### ISSUE TITLE
Classes with no stats in arena should show as "0% of total" in summary

### ISSUE THREAD

**Issue by fdela** [HearthSim/Hearthstone-Deck-Tracker#3311]
In Stats → Menu → Arena Runs → Summary → Classes, when there is no arena run recorded for a certain class, it should show "Runs: 0 (0% of total)" instead of "Runs:  (% of total)".
For instance:

![image](https://user-images.githubusercontent.com/29602664/27600779-54332484-5b6d-11e7-9b90-fee3500db68e.png)

**Comment by mgiuffrida** [comment]
these fields in `ArenaClassStats.xaml` are bound to `Runs` and `PickedPercent` from `ClassStats.cs`. why don't they resolve to `"0"` for a `0` value?

also, there shouldn't be a space before the `%` ([line 47](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/2074efbb715a8b7dd828e06af5d77c7eb7b77ea9/Hearthstone%20Deck%20Tracker/Controls/Stats/Arena/ArenaClassStats.xaml#L47)). e.g.:

```
Runs: 5 (10 % of total)
           ^
```

should really be

```
Runs: 5 (10% of total)
```

**Comment by fdela** [comment]
> also, there shouldn't be a space before the %

Note some languages mandate a space before the % sign (e.g. French)

**Comment by azeier** [comment]
Fixed this to now say `Runs: 0 (0% of total)`. Also removed the accidental space, it's correct in most cases without.
