### ISSUE TITLE
Please add option to make export to HearthStone ignore golden cards

### ISSUE THREAD

**Issue by Zesaric** [HearthSim/Hearthstone-Deck-Tracker#3317]
Since the new deck copy feature in HS, it seems impossible to export decks as standard cards only. Once you have a golden card, it is automatically included.

Is there any way

**Comment by judge2020** [comment]
Hearthstone handles what type of card to add to your deck, be it golden or regular. HDT cannot modify what type HS imports.

For more information see
#3290

 https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3287#issuecomment-307339091

**Comment by Zesaric** [comment]
OK thanks for the feedback. I have been searching whether this topic was discussed already but obviously have missed the threads you linked. So sorry for opening a duplicate issue.
