### ISSUE TITLE
Unable to click the export button

### ISSUE THREAD

**Issue by igameking** [HearthSim/Hearthstone-Deck-Tracker#3319]
![1](https://user-images.githubusercontent.com/29981826/27962638-cbbeb424-6332-11e7-8c04-bf6095d90c92.PNG)

That's what looks like, the button doesnt working, I cant click it.
If i try to import and after export to hearthstone doesnt work either.

**Comment by azeier** [comment]
You need a (selected) deck to export. 

Import/export are from the point of view of HDT. Exporting a deck gives you e.g. the deck code for it.
