### ISSUE TITLE
NOOOOOOOO Several Decks

### ISSUE THREAD

**Issue by Twinkielock** [HearthSim/Hearthstone-Deck-Tracker#3320]
## 
Haven't played in about 2 months.  Several of my decks are showing "Noooooooo"

### Expected Behavior
No NOOOOOOO Cards

### Actual Behavior
Describe the actual behavior here

### Steps to reproduce behavior
- Launcehd HDT at let it auto update
- Play Hearthstone

### Log/Screenshots

![image](https://user-images.githubusercontent.com/9260145/27997073-f088f7ae-64b5-11e7-83d2-e522089b72b6.png)

Also, should auto deck by blue or white?  It's been  a while and I forget.  

Thanks

**Comment by azeier** [comment]
HDT wasn't on the latest version when these decks were imported. Make sure you are on 1.3.5, then delete/import decks again. 

'Auto' should be blue.

**Comment by Twinkielock** [comment]
Thank you for the quick response!  I auto update every time the game launches.   Where can I manually download 1.3.5?

Thanks again!

**Comment by azeier** [comment]
You can get it here: https//hsdecktracker.net

**Comment by Twinkielock** [comment]
Thanks for the link!  One last question, the decks I had were Ungoro decks (my version isn't that old)  So the cards should be recognizable.   I just wanted to confirm before I manually install the new version.  (Don't want to make anything worse)  

Thanks
