### ISSUE TITLE
Opponent cards not shown

### ISSUE THREAD

**Issue by TristanCP** [HearthSim/Hearthstone-Deck-Tracker#3321]
### Expected Behavior
I expect opponent cards to be shown on a left overlay when he plays them

### Actual Behavior
No cards are shown, the top left overlay says 30 cards in deck, 0 cards drawn during all game.

### Steps to reproduce behavior
Play a game with regular HDT settings.

### Log/Screenshots
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1139711/hdt_log.txt)

**Comment by azeier** [comment]
The log looks fine for the most part. Try restarting HDT and hearthstone.

**Comment by TristanCP** [comment]
Ok, thanks. After restart, it's all fixed   :)
