### ISSUE TITLE
Building in Visual Studio 2015

### ISSUE THREAD

**Issue by xBerga95** [HearthSim/Hearthstone-Deck-Tracker#3324]
Hi, I'm trying to build HDT from Visual Studio 2015 but when I launch bootstrap.bat I get a lot of errors while compiling.

I've already added nuget.exe and I added msbuild.exe to my path in order to compile.

At the beginning of the script output I get the following:
`AVVISO: Impossibile trovare file progetto C:\mypath\Hearthstone-Deck-Tracker\HearthDb\HearthDb\HearthDb.csproj.
AVVISO: Impossibile trovare file progetto C:\mypath\Hearthstone-Deck-Tracker\HearthMirror\HearthMirror\HearthMirror.csproj.
AVVISO: Impossibile trovare file progetto C:\mypath\Hearthstone-Deck-Tracker\HSReplay-Api\HSReplay\HSReplay.csproj.`

Translated in English it's roughly "WARNING: Unable to locate the project file XXX".

That's the output right before the 184 compiling errors.

`CoreCompile:
  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /platform:x86 /errorreport:prompt /define:DEBUG;TRACE /highentropyva+ /reference:"C:\Program Files (x
  86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Microsoft.CSharp.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll" /
  reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFrame
  work\v4.5\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.dll" /reference:"C:\Program Files (x86)\Refe
  rence Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Net.Http.dll" /reference:"
  C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Sy
  stem.Xml.Linq.dll" /debug+ /debug:full /filealign:512 /out:obj\x86\Debug\HearthDb.dll /subsystemversion:6.00 /resource:CardDefs.xml,HearthDb.CardDefs.xml /target:library /utf8output Card.cs CardDe
  fs\CardDefs.cs CardDefs\Entity.cs CardDefs\EntourageCard.cs CardDefs\PlayRequirement.cs CardDefs\Power.cs CardDefs\Tag.cs CardDefs\TriggeredPowerHistoryInfo.cs CardIds.cs Cards.cs Deckstrings\Deck
  .cs Deckstrings\DeckSerializer.cs Deckstrings\InvalidDeckException.cs Deckstrings\VarInt.cs Enums\Dictionaries.cs Enums\Enums.cs Info.cs Properties\AssemblyInfo.cs "C:\Users\user\AppData\Local\Te
  mp\.NETFramework,Version=v4.5.AssemblyAttributes.cs"`

I can attach the full output if needed.

**Comment by azeier** [comment]
You need VS2017

**Comment by xBerga95** [comment]
You were right! Thanks for your help.
