### ISSUE TITLE
Renounce Darkness should include new cards in your hand in the deck list

### ISSUE THREAD

**Issue by mgiuffrida** [HearthSim/Hearthstone-Deck-Tracker#3326]
### Expected Behavior
When playing Renounce Darkness, any class cards in your hand will be replaced with cards from the randomly selected class. These new replacement cards should be listed in the deck list during play.

### Actual Behavior
The new cards in your hand are not shown in the deck tracker.

### Steps to reproduce behavior
1. Play Warlock with Renounce Darkness (I did this in Arena)
2. Play Renounce Darkness

**Comment by judge2020** [comment]
Pretty sure this is intended, as those cards did not originate from your deck. 

We could have them appear with the "gift box"/"created" icon but adding 10 cards to the list will make it extremely cramped and you may end up not being able to read the card names.

**Comment by judge2020** [comment]
If you were referring to cards in the deck (not yet drawn): #3100

**Comment by mgiuffrida** [comment]
Are the replacement cards added to the deck list once they're drawn? (Is it just the new cards in hand that "did not originate from your deck" or is that all cards?)

A bit confusing since cards *inserted* into your deck, e.g. by [Raptor Hatchling](http://hearthstone.gamepedia.com/Raptor_Hatchling) or [Elise Trailblazer](http://hearthstone.gamepedia.com/Elise_Trailblazer), do appear in the list. Then again, I guess the cards added to your hand from the Un'Goro Pack spell itself don't get added to the list.

I know there's an option for showing/hiding "gift" cards in your opponent's deck list ("Include created cards"); maybe something similar for your own deck list would be nice.

**Comment by azeier** [comment]
I think the `options > player > Include cards created in hand` option should work here. It should show those cards in the list once drawn and remove them again once played.

**Comment by mgiuffrida** [comment]
Makes sense. I doubt I'll have another Renounce Darkness anytime soon to test with, so feel free to close this if you think it's WAI.

**Comment by azeier** [comment]
👍
