### ISSUE TITLE
Feature request : ability to enter/select the deck type you've faced after each game

### ISSUE THREAD

**Issue by TristanCP** [HearthSim/Hearthstone-Deck-Tracker#3327]
## Feature request

Although this application is almost perfect, I think it lacks the ability to distinguish between the deck types you've faced when you look at your stats.

These deck types wouldn't have to be pre-filled. After each game, the user would enter the deck type he faced or select among the ones he already entered.

On the stat screen, you could click on any matchup to see the decomposition. For example you are on your "Freeze Mage" stats, you click on the druid matchup which is 5-5, and you see this : 
Anaconda druid : 2-0
Aggro druit : 3-0
Jade druid : 0-5

which is quite useful to know.

**Comment by soeltjen** [comment]
There is a plugin that does what you are looking for here: https://github.com/andburn/hdt-plugin-endgame

**Comment by TristanCP** [comment]
Thanks for the information, but can a plugin interacts with stats screens ? Because it looks like this one is not.
