### ISSUE TITLE
Mana Geode is missing the Elemental Tag

### ISSUE THREAD

**Issue by KarlmitC** [HearthSim/Hearthstone-Deck-Tracker#3335]
I just recognized that Mana Geode's tag of "Minion" wasn't changed to "Elemental" since the update.

**Comment by Zawodowiec1532** [comment]
It's already fixed. :)
https://github.com/HearthSim/hsdata/commit/e3b02346a86a379c303b0452c461d4376e7a46ef#diff-1f607b74f44e25a910ce5388280dffa7R28967

**Comment by judge2020** [comment]
Will be fixed with next HDT release.
