### ISSUE TITLE
Cant add Arena game manually

### ISSUE THREAD

**Issue by NomdeNet** [HearthSim/Hearthstone-Deck-Tracker#3337]
I just played my first game of an arena with a new deck. For some reaosn the game wasnt recorded, but a replay was created.

When I go to arena runs -> Runs & matches, this deck doesnt show up (no games played), and I cant find a way to add a game manually. 

Is this a bug, or is there something I'm missing?

The deck itself does exist in HDT. I just cant add any games to it.

**Comment by riQQ** [comment]
An arena deck with no matches shows up at the bottom of the list.
