### ISSUE TITLE
Proposal: Ignore archived decks for automatic deck selection

### ISSUE THREAD

**Issue by djdookie** [HearthSim/Hearthstone-Deck-Tracker#3339]
Since I use archived decks for a plugin, I don't want them to get selected by the automatic deck selection, if I have a duplicate or a nearly similar deck in the archive.
So I wish I had an option to exclude archived decks from the automatic deck selection.

I also think this should be the true meaning of archive: you don't want to actively use those decks. Additionally this could boost your autodeck selection algorithm if you have a big archive of older decks.

Cheers.

**Comment by azeier** [comment]
Auto select does ignore archived decks. Automatic importing will unarchive decks if it finds an exact match, instead of creating a new one. Which I think is the correct behavior. 

Depending on what your plugin does, adding a custom tag to decks might be a better solution.
