### ISSUE TITLE
Proposal: Make Arena decks exportable via deckstring and rightclick

### ISSUE THREAD

**Issue by djdookie** [HearthSim/Hearthstone-Deck-Tracker#3340]
We recently got the great feature to export (and import) decks via deckstring. Additionally for standard decks we can now click right mouse button and export the deckstring via context menu -> export. 

Unfortunately, both isn't working for Arena decks.

If you want to play Arena with a friend and he want's to see your decklist while spectating, or you just want to export arena decks for another reason, the right click and export as deckstring method should be the fastest and easiest here.

**Comment by azeier** [comment]
HDT has a screenshot feature, including one click uploads to imgur, that suits the "share to look at" usecase a lot better.

I don't think export as deckstring makes much sense on arena decks.

**Comment by djdookie** [comment]
It makes sense if you play Arena with a friend and he also wants to see your deck in HDT while in spectator mode.
