### ISSUE TITLE
If I open friend's list while a game is loading, then the opponent's deck list won't appear

### ISSUE THREAD

**Issue by garyking** [HearthSim/Hearthstone-Deck-Tracker#3349]
I hit "Play" to find a new Ranked game. I then open my friend's list while the scroller animates. (I have the setting enabled where the opponent's deck list will disappear while the friend's list is open.) I then close the friend's list before a new game has been found. The opponent's deck list now does not appear unless I restart HDT.

**Comment by azeier** [comment]
Does opening and closing the friends list again help?

**Comment by garyking** [comment]
Yep that fixed it.
