### ISSUE TITLE
Problem starting Battle.net launcher/Hearthstone.

### ISSUE THREAD

**Issue by baterflyrity** [HearthSim/Hearthstone-Deck-Tracker#3351]
# Error with the button "START LAUNCHER/HEARTHSTONE".

### Expected Behavior
I don't want to start Blizzard launcher+HDT+Hearthstone. It takes too many actions. So i wanna use this useful feature to start the game by pressing "START LAUNCHER/HEARTHSTONE". 

### Actual Behavior
But it gives me the error while Windows says that no battlenet protocol handler found.

## Solution
As it was messaged in error's window I've created battlenet protocol on my PC. I think the problem was due to rename of the launcher. Here is an attached registry file wich registers necessary protocol. Just download it, change paths to Blizzard launcher and run.

[BattlenetReserve.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1194757/BattlenetReserve.zip)

**Comment by judge2020** [comment]
can you try:

Win+R

try URL protocol handlers like `blizzard://` or `blizzardapp://`

and report if they open the blizzard app?

If possible we can add in handling for old and new battle.net installations.

**Comment by baterflyrity** [comment]
@judge2020 Seems like i don't have any blizzard protocols on my PC. After launcher's update everything turned into simply links, e.x. "...\Games\Hearthstone\Hearthstone Beta Launcher.exe".

I suggest:
1) Start Hearthstone Beta Launcher.exe.
2) Monitor till Blizzard agent transforms into Blizzard app.
3) Start Hearthstone.exe.
###### and the same for protocols...

**Comment by judge2020** [comment]
We actually don't launch the exe's to start game processes, the exe's on your system like Hearthstone and the beta launcher will open battle.net if it wasn't passed any login arguments.

https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/Utility/Helper.cs#L343

```cs
Process.Start("battlenet://WTCG");
```

If the new blizzard app doesn't register any protocols the launch HS system may need to be changed.

**Comment by Zawodowiec1532** [comment]
For me its working fine, maybe some error occurred for you while installing Battle.net app?
By default there is registered URI Protocol for battle.net app, not for "Beta Launcher" in Hearthstone folder.
Screen: http://i.imgur.com/IHGoL4U.png
I checked it on fresh installation.. just got new PC week ago. :)

**Comment by baterflyrity** [comment]
I strongly don't understand why did the launcher install different on our systems, Zawodowiec1532.

But i think it would be useful to leave here how to add this protocol manually.
