### ISSUE TITLE
Confusing units for time in "My Games" section

### ISSUE THREAD

**Issue by Ming-Hua** [HearthSim/Hearthstone-Deck-Tracker#3358]
### Expected Behavior
Intuitive time units used in the time column for the "My Games" section of the main window

### Actual Behavior
- When the game is almost one day old (presumably 23 to 24 hours), some times the time is shown "0 days ago", which is quite confusing
- It also shows "1 hours ago", "1 days ago" and so on instead of the singular "1 hour ago" and "1 day ago"

### Steps to reproduce behavior
- Play games and wait 23 hours, I guess

**Comment by azeier** [comment]
Should be fixed with the next release.
