### ISSUE TITLE
Error: Replays not uploading

### ISSUE THREAD

**Issue by NomdeNet** [HearthSim/Hearthstone-Deck-Tracker#3361]
### Expected Behavior
when viewing a game in stats, i click the replay button and the game gets uploaded to hsreplay.
OR When going to Replays -> latest Replays and clicking a game, it gets uploaded.

### Actual Behavior
An error message popped up, and the replay was not uploaded.

### Steps to reproduce behavior
see expected and actual behaviour above. Happens every time.

**Comment by azeier** [comment]
We're working on it, not entirely sure what's going on yet.

**Comment by azeier** [comment]
Should be working again now!

**Comment by NomdeNet** [comment]
It is! thanks.
