### ISSUE TITLE
Capturable overlay not containing visuals

### ISSUE THREAD

**Issue by Bert-Proesmans** [HearthSim/Hearthstone-Deck-Tracker#3364]
## Bug report
The capturable overlay window does not contain any visuals, according to Windows and OBS. The visuals ARE visible above the game itself.
I noticed by restarting the game after i got it working that the overlay sort of resets itself to an empty state.

### Expected Behavior
The capturable overlay contains the deck tracker visuals at all time.

### Actual Behavior
The capturable overlay only shows deck tracker visuals when manually activated AFTER the game started. It's necessary to wait until the game has started before activating the option `Show capturable overlay window`.

### Steps to reproduce behavior
1. Start HDT
2. Follow instructions for OBS from [here](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Streaming-Instructions)
3. Discover through OBS that the overlay window contains no visuals (only magenta color)

### Log/Screenshots

[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1217702/hdt_log.txt)

**Comment by azeier** [comment]
I don't seem to be able to reproduce this. What do your overlay > general options look like?

Does resetting your config (rename `%AppData%/HearthstoneDeckTracker/config.xml` without HDT running) help?

**Comment by Bert-Proesmans** [comment]
Gonna try renaming the config.
The attachment is a screenshot of my overlay>general settings.
![general options](https://user-images.githubusercontent.com/2027877/29212202-85394736-7e9d-11e7-807a-a96867b45e91.PNG)

**Comment by Bert-Proesmans** [comment]
Resetting configuration results in the same issue.
I attached a video of only the capturable overlay window by OBS. 
The video was made by getting OBS to see the contents of the overlay window followed by closing hdt and hearthstone. I started the video recording then hdt and started hearthstone through hdt.
A glimpse of activation (visible artifacts) is seen between 24 and 25 seconds, maybe you can do something with it. The sound is an indication of when the game enters lobby and ends when the daily quests appear.
Also another log of hdt is attached.
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1217781/hdt_log.txt)
[video](https://youtu.be/1qKhUo4hOZA)

**Comment by Dushku** [comment]
I've been having this issue also. I'm using Windows 7 with Aero disabled. I was told by OBS staff that enabling Aero would solve this. I have not tried that yet, as I found a "workaround." Quotes due to intermittent results.

My workaround involved telling OBS Studio to Game Capture both HS and HDT Capturable Overlay. I'm told with Aero on, I can do this with Window Capture as expected. Even still, I have to launch and relaunch HS, HDT, and OBSS in different orders, multiple times to achieve the desired results.

Not sure where the problem lies, but wanted to share my experience.

**Comment by Bert-Proesmans** [comment]
I got a guaranteed workaround by opening OBS, HS and HDT. Afterwards enabling the separate capturable overlay window. 
As long as that option is enabled AFTER HS goes into lobby it works. Starting HS has an effect on the capturable window which erases it's buffer contents. I guess the panel/device is invalidated which causes the overlay to autoreset but the capturable window doesn't receive this notification through its message pump. The result of this is that the window still points to an invalidated screen buffer.

**Comment by Bert-Proesmans** [comment]
I looked into it again and updated the streaming instructions page on the WIKI. I don't have any issues anymore capturing the overlay on stream.
