### ISSUE TITLE
Problem launching HS Deck Tracker.

### ISSUE THREAD

**Issue by sizzle55** [HearthSim/Hearthstone-Deck-Tracker#3366]
Hi have searched the site for this problem but have came up empty.  When I click to open HS Deck Tracker my mouse will spin as it's launching the program but then it will stop.  When I try to launch the program it will show up in Windows task manager under processes but then auto close.  I uninstalled the program deleted all the files linked to HS Deck Tracker.  After I download it and go to launch the installer it won't open or launch, I have removed all software keys from windows registry, deleted temp folder, and did a repair on .NET Framework.  After all this I went and downloaded the files, the installer still won't launch. In the two images attacked you can see what is happening when it is trying to install, the other image is what comes up in add or remove program as it being installed.  I'm running HS Deck Tracker on Windows and have made sure I have downloaded the windows version.  Any ideas or help is much appreciated and thanks.

![deck tracker installing](https://user-images.githubusercontent.com/30943978/29237164-ea70814c-7edd-11e7-9f38-e01b6c664ee5.PNG)

![deck tracker version](https://user-images.githubusercontent.com/30943978/29237169-0b79030a-7ede-11e7-834f-a48808f57299.PNG)

**Comment by Zawodowiec1532** [comment]
Have you updated windows? Try to turn off all other applications during installation. Do you have atleast Framework 4.5?
