### ISSUE TITLE
trouble detect decks

### ISSUE THREAD

**Issue by Justcraftme** [HearthSim/Hearthstone-Deck-Tracker#3367]
I have made the thing with the log file and nothing happened
Can anyone help me please?

**Comment by judge2020** [comment]
Did you follow https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Setting-up-the-log.config completely?

**Comment by Justcraftme** [comment]
Yeah i did it twice and nothing happened

**Comment by judge2020** [comment]
If you open and close Hearthstone, then open the log config, what does it have in it?

**Comment by Justcraftme** [comment]
There is the log of HDT

**Comment by Justcraftme** [comment]
you know the [BOB] thing

**Comment by Justcraftme** [comment]
HDT Say "heartstone restart required
and when i restart, nothing happen

**Comment by azeier** [comment]
- Close both
- Start HDT
- Start Hearthstone
- Enter the "Play" menu
- Start a match
- Upload the log - https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues
