### ISSUE TITLE
NEW EXPANSION not included

### ISSUE THREAD

**Issue by Completin** [HearthSim/Hearthstone-Deck-Tracker#3368]
I've just installed the lastes version on my mac, but it doesnt create decks since there aren't any cards from the Frozen throne expansion. I don't know exactly if its a bug, but I have reinstalled the client like 4 times and nothing. 

 Best regards

**Comment by cfeduke** [comment]
Found this from the Discord: https://github.com/HearthSim/HSTracker-Beta/releases/tag/1.1.0-beta1 (listed as untested)

**Comment by jleclanche** [comment]
This is the repository and issue tracker for the mac version: https://github.com/HearthSim/HSTracker

The beta linked above by @cfeduke has support for the expansion. It should be released very soon hopefully.
