### ISSUE TITLE
Hearthstone Deck Tracker has an interaction with new cards that can be considered cheating.

### ISSUE THREAD

**Issue by TheGuyWithANameJeff** [HearthSim/Hearthstone-Deck-Tracker#3369]
In the newest expansion titled "Knights of the Frozen Throne" we got so called "Death Knight cards" acquirable by the Lich King or Arfus. One of this cards is Death Grip that steals a random minion card from opponents deck and places it into your hand. Unfortunately HS Deck Tracker can say what card was stolen. By paying attention to our cards list we can tell what card was taken from us and placed into opponents hand - it is obviously a cheat, because players that don't use HS Deck Tracker have no way of telling. I advise fixing the issue. 

We saw this mechanic of HS Deck Tracker detecting cards that leave our (or more importantly our opponents') decks before. Cards like Hemet when played fill the way we see opponents deck with all discarded cards, but never before it gave players a real advantage.

**Comment by azeier** [comment]
The card stolen by Death Grip is revealed in game as well.

It is turned over just before entering the hand and visible in the history.
