### ISSUE TITLE
New Frozen Throne Cards not found

### ISSUE THREAD

**Issue by WantToRecall** [HearthSim/Hearthstone-Deck-Tracker#3370]
### Expected Behavior
I read that the new Frozen Throne cards are already implemented. So when I go to Decks -> Deck Manager and click "Edit" on my deck I should be able to choose the new cards.

### Actual Behavior
They are not in there. I don't even have the Column (at the right of the search field).

### About me
Using HSTracker 1.0.2 on Mac OS. Hearthstone is in Spanish but that shouldn't affect this one.

### Log/Screenshots
![bildschirmfoto 2017-08-14 um 18 30 32](https://user-images.githubusercontent.com/31012417/29281296-bc7f488e-811e-11e7-959c-27edb3d71a4b.png)

**Comment by azeier** [comment]
This is the repository and issue tracker for the mac version: https://github.com/HearthSim/HSTracker

This beta version has support for the expansion: https://twitter.com/hstracker_mac/status/896283985504030720. It should be released very soon hopefully.
