### ISSUE TITLE
HDT does not account for Snipe non-offering in Arena

### ISSUE THREAD

**Issue by Gorilla801** [HearthSim/Hearthstone-Deck-Tracker#3372]
## Bug report

Snipe no longer available in arena as of July 10.

https://us.battle.net/hearthstone/en/blog/20904301

HDT does not take this into account when attempting to resolve Hunter secrets.

### Expected Behavior

Snipe greyed out automatically when playing vs. Hunter in Arena.

### Actual Behavior

Snipe remained lit among possible secrets until all secrets were resolved.

### Steps to reproduce behavior

Play Arena vs. Hunter.  Hunter plays a secret.

**Comment by azeier** [comment]
Fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/5a25bc54665c8e7266ebbd6687e5834afe6e89cb
