### ISSUE TITLE
Please bring back the old export method

### ISSUE THREAD

**Issue by Zesaric** [HearthSim/Hearthstone-Deck-Tracker#3375]
I know that in some thread (which I wasn't able to find right now) it said that with the built-in export in HS, you do not want to maintain the previous export function. Which I understand if the built-in function was reliable.

Unfortunately that is not the case:
When exporting a deck from HDT to HS, an error msg _"Your copied deck is not valid for this play mode"_ appears. Needless to say that I made sure to export only Standard to Standard and only Wild to Wild. Still, the error appears most of the time.

Considering that the built-in function also prioritizes golden cards even if the player does not want it to, it has to be said that the previous export function was vastly superior to the current built-in one. This is why I beg you to bring back the old export method as an alternative option for those users facing the downsides described above.

**Comment by azeier** [comment]
We won't be adding the old method back sorry.

As far as I know the native method should be very reliable. Can you post the full deck string (including all the comments) for a deck you are having this issue with?

**Comment by Zesaric** [comment]
Sure, the full deck string from when I encountered the issue most recently (today) is below.
However, this is just one example. In general, I'd say 60-70 % of my exports run into the above mentioned error message.

### Test
# Class: Warlock
# Format: Wild
# Year of the Mammoth
#
# 2x (1) Possessed Villager
# 2x (1) Power Overwhelming
# 2x (1) Voidwalker
# 1x (2) Defile
# 2x (3) Darkshire Councilman
# 2x (3) Imp Gang Boss
# 2x (3) Shadow Bolt
# 1x (4) Blastcrystal Potion
# 2x (4) Crystalweaver
# 1x (4) Hellfire
# 1x (4) Ravenous Pterrordax
# 2x (4) Shadowflame
# 2x (4) Voidcaller
# 2x (5) Despicable Dreadlord
# 2x (5) Doomguard
# 1x (6) Kabal Trafficker
# 1x (9) Mal'Ganis
# 1x (10) Bloodreaver Gul'dan
#
AAEBAf0GB+fLAv2/ArYH58EC7L8Cwg+X0wIL9q4CzgYwtKwC8BGSB8e7ApMBjg73zQL3BAA=
#
# To use this deck, copy it to your clipboard and create a new deck in Hearthstone
# Generated by HDT - https://hsdecktracker.net

**Comment by Zesaric** [comment]
Sorry BTW for the large and bold font, that wasn't deliberate.
I presume it's because the string from HDT adds all these # characters?

**Comment by riQQ** [comment]
Add ``` before and after the deck string.

**Comment by azeier** [comment]
The list you posted only has 29 cards, that's why it's not working.

**Comment by Zesaric** [comment]
Ah, thanks for the explanation, so that's why.

And as the most common export for me is an opponent deck, I run into the error so often because they are hardly ever complete. Bad luck for me I guess! ;-)

**Comment by azeier** [comment]
I'll add a warning in the export window if hearthstone won't be able to import it.

Your easiest workaround will probably be to complete the deck in HDT.

**Comment by Zesaric** [comment]
Yeah, the warning is probably a good idea, thanks for considering this! And thanks also for the workaround tip, I had the same thought when you explained the reason for the error! :)
