### ISSUE TITLE
Skulking geist side effect (may be not appreciated by Blizzard).

### ISSUE THREAD

**Issue by TristanCP** [HearthSim/Hearthstone-Deck-Tracker#3377]
### Expected Behavior
I expect not to be able to see all 1 cost spells destroyed by Skulking geist in the opponent cards when he has not played them yet. It's quite useful and satisfying, but it reveals you informations the game hasn't shown you.

### Actual Behavior
The contrary happens, all 1 cost spells destroyed by geist suddenly appear in the opponent card list.

### Steps to reproduce behavior
* Play a game vs a rogue having 2 hallucinations.
* Play Skulking geist
* Watch the hallucinations appear in the cards like if they had been played.

**Comment by azeier** [comment]
Hearthstone shows you which cards were destroyed in the history (bar on the left).

**Comment by TristanCP** [comment]
Oh ok, sorry  :)
