### ISSUE TITLE
Update "Reporting Issues" screenshots to include advanced settings checkbox

### ISSUE THREAD

**Issue by azeier** [HearthSim/Hearthstone-Deck-Tracker#3383]
https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by Zawodowiec1532** [comment]
https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues/a2759101d406c194438bc46b97dba1949daa6f5f

**Comment by azeier** [comment]
Thanks!
