### ISSUE TITLE
Not finding the Hearthstone Window, overlay is able to be moved, admin, no antivirus or desktop composition

### ISSUE THREAD

**Issue by LongLiveTA** [HearthSim/Hearthstone-Deck-Tracker#3385]
### Expected Behavior
Overlay expected to display.

### Actual Behavior
Overlay does not display.

### Steps to reproduce behavior
Hearthstone is a fresh install on a new pc. The directory is not the default directory. I went to the Deck Tracker, Advanced>Settings>Set Hearthstone Path and set the correct directory. Overlay does not show. The deck tracker itself however imports my decks into itself though. Changed permission to everyone and gave full control, disabled windows UAC, opened in admin, restarted the pc. That did not work still. The log file shows that the deck tracker cannot find the hearthstone window. Deleted all content within the appdata>roaming>hearthstone deck tracker folder and restarted pc. Still same issue.

### Log/Screenshots
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1236800/hdt_log.txt)

**Comment by riQQ** [comment]
Could you please post your solution? Thanks.
