### ISSUE TITLE
Arena stats only aggregate up to 88 runs

### ISSUE THREAD

**Issue by NobleHelium** [HearthSim/Hearthstone-Deck-Tracker#3386]
### Expected Behavior

I expect the arena stats to take into account all runs within the selected time period.

### Actual Behavior

The arena stats only take into account the last 88 runs within the selected time period if there are more than 88 games.

### Steps to reproduce behavior

Have an account with more than 88 arena runs on record and choose "All Time" in the arena stats time period selector.

### Log/Screenshots

88 runs for games since 10/28/2015:
![image](https://user-images.githubusercontent.com/1309973/29497412-3e2ba176-85b5-11e7-967f-8b0b8056a076.png)

88 runs for games since 6/1/2016:
![image](https://user-images.githubusercontent.com/1309973/29497429-648c428a-85b5-11e7-8770-ba4446789e93.png)

88 runs for games since 1/1/2017:
![image](https://user-images.githubusercontent.com/1309973/29497443-9cd0f8a2-85b5-11e7-86bd-773ea259099b.png)

### Game Version
I observed this issue in v1.4.0.

**Comment by riQQ** [comment]
Works for me. You're only filtering for a starting time. When was your first run played?
