### ISSUE TITLE
hdt dont get saved.

### ISSUE THREAD

**Issue by chopper214** [HearthSim/Hearthstone-Deck-Tracker#3392]
## Bug report
I try to delete all my decks, as soon as I close the program it all comes back. and the game data of past 2 months didn't get saved as well. i tried to reinstall the program but it didn't help, run as admin. deleting the hdt folder all tried but non helps. can someone help me

**Comment by riQQ** [comment]
Please post a hdt log: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#hdt-log-files.
