### ISSUE TITLE
Classic cards can not be added as arena rewards

### ISSUE THREAD

**Issue by HugoKornelis** [HearthSim/Hearthstone-Deck-Tracker#3394]
### Expected Behavior
After finishing an arena run, I was awarded with a non-golden Shadowflame. I wanted to record this reward but was unable to.

### Actual Behavior
After I had typed "Shadowflame" in the rewards dialog and tried to save, I got an error message; "Invalid card name: Shadowflame".

### Steps to reproduce behavior
1. Finish an arena run (or go into Stats / Arena / Runs & Matches / Edit rewards)
2. In the entry box for card #1, type Shadowflame
3. Click Save

### Log/Screenshots
![25-8-2017 1-21-30](https://user-images.githubusercontent.com/13858053/29693071-dbe1b8d4-8933-11e7-97f0-35fe12c12f17.png)
![25-8-2017 1-21-50](https://user-images.githubusercontent.com/13858053/29693073-df2ad9bc-8933-11e7-90cc-9473398a1496.png)
![hearthstone screenshot 08-25-17 01 07 28](https://user-images.githubusercontent.com/13858053/29693077-e12f0dbe-8933-11e7-9e16-5631e44c5518.png)

**Comment by Gorilla801** [comment]
Identical issue occurs when "Counterspell" is offered as a reward.

**Comment by PhateREF** [comment]
The same issue with Naturalize.

**Comment by HugoKornelis** [comment]
I was going to comment that all these cards have in common that they are Rare and from the Classic set. However, the report by PhateREF changed that - Naturalize is also a Classic card, but it's of Common rarity.

**Comment by azeier** [comment]
Fixes for the next update.

This is an issue with Classic cards in general, I gave classic the wrong set in https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/c740cd6e0644b461bfe1e09a7d707db03ba8354f#diff-172b9c7f07647c2b2b261c97f5e5bff5R11 - which allows basic cards to be added instead of classic ones.

**Comment by judge2020** [comment]
fixed in 184d6a, reopen if this still occurs.
