### ISSUE TITLE
Board Attack Counter + Shadow Reflection bug

### ISSUE THREAD

**Issue by Dushku** [HearthSim/Hearthstone-Deck-Tracker#3396]
### Expected Behavior
Board attack counter is accurate.

### Actual Behavior
Board attack counter does not account for minions play as Shadow Reflections.

### Steps to reproduce behavior
Play Valeera the Hollow. Play a Shadow Reflected minion. Board attack counter does not account for the minion that was played via Shadow Reflection.

I first noticed this regarding the HDT addon called Graveyard. It doesn't log minions that were Shadow Reflections either.

### Log/Screenshots
http://i.imgur.com/IpRE1vs.jpg

**Comment by azeier** [comment]
Fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/f48fcae3084d350d5b2c5450ba56cef8966916e3
