### ISSUE TITLE
blank friends list

### ISSUE THREAD

**Issue by flutulash** [HearthSim/Hearthstone-Deck-Tracker#3400]
Decktracker is causing my hearthstone list to be blank. I tried reinstalling. I didn't switch regions. I contacted a blizzard employee as I thought it was a bug in hearthstone, but it seems that whenever i play the game without the tracker my list is visible.

Here is an example>
![hearthstone screenshot 08-30-17 19 02 27](https://user-images.githubusercontent.com/31486516/29888111-615ed382-8dc8-11e7-9f26-c547bab6aa90.png)
I don't really know what to do to fix it, if anyone can help me, I would appreciate it. Thank you.

**Comment by judge2020** [comment]
This is a known Hearthstone client bug, see https://github.com/HearthSim/hs-bugs/issues/790
