### ISSUE TITLE
HDT Can't see Hearthstone and my decks

### ISSUE THREAD

**Issue by Eraser94** [HearthSim/Hearthstone-Deck-Tracker#3401]
## Bug report
My HDT after windows reinstall stop working. I can run battlenet and hearthstone from hdt, but it can't see my decks and my game.

### Expected Behavior
HDT should see my decks and show me hdt interface in game

### Actual Behavior
Nothing happens

### Log/Screenshots
[hdt_log_1504122026.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1264909/hdt_log_1504122026.txt)

**Comment by riQQ** [comment]
https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#not-working

**Comment by Eraser94** [comment]
I did everything from this link

**Comment by riQQ** [comment]
Is the overlay working in the menus when `Options > Overlay > General > Hide in menu` is disabled?
Post a HDT log of a session playing vs AI.

**Comment by Eraser94** [comment]
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1286993/hdt_log.txt)
Reinstall HDT and Hearthstone. Did every point from link a few times. Still have problem )

**Comment by riQQ** [comment]
Please post your `log.confg` from `%appdata%\HearthstoneDeckTracker`.

**Comment by Eraser94** [comment]
[config.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1287007/config.zip)

**Comment by riQQ** [comment]
```xml
<HearthstoneDirectory>D:\Games\Hearthstone</HearthstoneDirectory>
<HearthstoneLogsDirectoryName>Hearthstone_Data</HearthstoneLogsDirectoryName>
```

- Go to options
- Enable `Advanced options`
- Go to `Tracker > Settings`
- Push the button `Set Hearthstone Log Directory`
- Select the `Logs` subfolder of the Hearthstone directory.

**Comment by Eraser94** [comment]
OOOOH SHIT. Thx u, bro

**Comment by riQQ** [comment]
I'll assume this is fixed ;)
