### ISSUE TITLE
About Secret Reminder in Arena

### ISSUE THREAD

**Issue by songhuadan88** [HearthSim/Hearthstone-Deck-Tracker#3402]
Maybe this is not a bug, but I want to check it.

The arena has been in standard mode, which means some secrets, like Duplicate, cannot appear in the arena. Then, why such secrets will appear in the secret reminder when playing in Arena?

Thank  you~

**Comment by riQQ** [comment]
Because there might be legacy decks, that where drafted some time ago, containing secrets that were rotated to wild in the mean time.

**Comment by songhuadan88** [comment]
@riQQ  but this situation is really rare, isn't it?
If this the only reason, I think it is better to remind secrets in arena as in the standard mode.

Or, we can have a switch in the Option, configuring this.
Afterall, thank you~~

**Comment by Zawodowiec1532** [comment]
I think it should display only secrets from standard and "IF" all secrets are grayed out, but opponent still have secret for this class, then display wild ones (and hide standard grayed out list).

**Comment by LizardDude** [comment]
This has been bugging me for the last couple of versions. The odds of encountering a Wild Secret in Arena are minuscule.

(Zawodowiec1532's idea is good.)

**Comment by azeier** [comment]
This is definitely a bug, wild secrets are not intended to show up in arena.
