### ISSUE TITLE
Holy Wrath not listed as a card for arena awards

### ISSUE THREAD

**Issue by AndySweet** [HearthSim/Hearthstone-Deck-Tracker#3408]
### Expected Behavior
In Arena Rewards screen, type in Holy Wrath as the name of card in the reward.  Expected to auto-complete and accept that card.

### Actual Behavior
No Auto-complete, and after typing card and trying to save, got error, in valid card name.

**Comment by jleclanche** [comment]
Duplicate of #3394.
