### ISSUE TITLE
HSdecktracker stopped working

### ISSUE THREAD

**Issue by GoldAnanas** [HearthSim/Hearthstone-Deck-Tracker#3409]
Hi,
First of all, i've to say that on my computer i never manage to launch hsdecktracker. I've tried with older version, delete the appdata files of hsdecktracker and i always got this error :
![capture d ecran 1](https://user-images.githubusercontent.com/31634992/30039195-060c7296-91ce-11e7-94a6-ad39655eb790.png)
In english : "Hearthstone Deck Tracker has stopped working"
I tried to reinstall .net framework but i'm not sure it has any effect on Windows 10.
❤️  Sry for my english   ❤️  
PS : I also have read the other posts of ppl with the same error as me.

**Comment by riQQ** [comment]
Please post the corresponding windows logs: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#windows-log-files.

**Comment by GoldAnanas** [comment]
Nom du journal :Application
Source :       .NET Runtime
Date :         05/09/2017 21:34:49
ID de l’événement :1026
Catégorie de la tâche :Aucun
Niveau :       Erreur
Mots clés :    Classique
Utilisateur :  N/A
Ordinateur :   DESKTOP-1PS36UR
Description :
Application : HearthstoneDeckTracker.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : code d'exception c0000005, adresse d'exception 00000000

XML de l’événement :
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-09-05T19:34:49.151570600Z" />
    <EventRecordID>1490</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-1PS36UR</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application : HearthstoneDeckTracker.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : code d'exception c0000005, adresse d'exception 00000000
</Data>
  </EventData>
</Event>

**Comment by judge2020** [comment]
exception c0000005 is access violation.

**Comment by GoldAnanas** [comment]
So what should i do ?

**Comment by Zawodowiec1532** [comment]
Try run it as Admin.

**Comment by GoldAnanas** [comment]
Nom du journal :Application
Source :       .NET Runtime
Date :         06/09/2017 16:39:54
ID de l’événement :1026
Catégorie de la tâche :Aucun
Niveau :       Erreur
Mots clés :    Classique
Utilisateur :  N/A
Ordinateur :   DESKTOP-1PS36UR
Description :
Application : HearthstoneDeckTracker.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : code d'exception c0000005, adresse d'exception 00000000

XML de l’événement :
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-09-06T14:39:54.446254300Z" />
    <EventRecordID>1513</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-1PS36UR</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application : HearthstoneDeckTracker.exe
Version du Framework : v4.0.30319
Description : le processus a été arrêté en raison d'une exception non gérée.
Informations sur l'exception : code d'exception c0000005, adresse d'exception 00000000
</Data>
  </EventData>
</Event>

**Comment by GoldAnanas** [comment]
I still have the exact same issue when i open the app as admin with my antivirus disabled

**Comment by GoldAnanas** [comment]
Up

**Comment by Zawodowiec1532** [comment]
Update your windows and install .NET Framework - atleast 4.5
If this doesnt help try run it in Safe Mode.
After you do that and its still crashing then paste log again.

**Comment by GoldAnanas** [comment]
Hi, the app is working with safe mode but not in "normal" mode.

**Comment by GoldAnanas** [comment]
Have you any idea how to solve this ? I've made all W10 updates.

**Comment by Zawodowiec1532** [comment]
It means that your non-microsoft services, drivers and applications may cause it (In safe mode they are not loaded). Try to update your windows, Install framework 4,5, because you have only 4.0. Then clean-up your computer - uninstall suspicious things which you dont need and try with disabled antivirus?

**Comment by Zawodowiec1532** [comment]
Have you managed to launch installer?

**Comment by riQQ** [comment]
Have you tried the latest portable release: https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/latest?

**Comment by GoldAnanas** [comment]
So i tried to reinstall framework but it still crashed so i surrended. I ll try with the new release !

**Comment by Zawodowiec1532** [comment]
Have you tested portable version like riQQ says?

**Comment by riQQ** [comment]
Can you post the event with the category `Application Error`: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#windows-log-files?

Try reinstalling / updating your graphics card driver.

**Comment by GoldAnanas** [comment]
Sorry but i've given up.
Thanks very much for your help !
