### ISSUE TITLE
HSDecktracker don't show the stat of this season

### ISSUE THREAD

**Issue by SnakeEater2845** [HearthSim/Hearthstone-Deck-Tracker#3410]
I can't see in the stats menu any of my game, it's like the tracker didn't work but at the same time i can see in the main page all the game i played. The last game that I can see in the stas menù is the last of the past season.

### Log/Screenshots

As you can see here there are all the games I played this season with a single deck
![immagine2](https://user-images.githubusercontent.com/31636084/30040038-b6716bb8-91d9-11e7-8411-aee731c66281.jpg)
While here there is nothing
![immagine](https://user-images.githubusercontent.com/31636084/30040039-b68941e8-91d9-11e7-9ce0-8cd9067d50ba.jpg)

**Comment by riQQ** [comment]
You have are filtering for rank L1 to 5.

**Comment by SnakeEater2845** [comment]
Thx, I didn't see the filter was on 5, my bad
