### ISSUE TITLE
Lightwarden not available as an arena card reward

### ISSUE THREAD

**Issue by DiegoVV** [HearthSim/Hearthstone-Deck-Tracker#3411]
## Bug report
Lightwarden was not listed as card reward after an arena. Trying to input its name resulted in a invalid name error.

### Expected Behavior

Input the name and be able to save the arena results.

### Actual Behavior

Trying to input its name resulted in a invalid name error. The only option available after typing Light was Lightbomb

### Steps to reproduce behavior

Finish an arena, then try to write Lightwarden as a valid card reward

### Log/Screenshots

Sorry, forgot to screenshot :(

**Comment by Zawodowiec1532** [comment]
Duplicate of #3394
