### ISSUE TITLE
¿How can I hide the indicator that shows the turn cards?

### ISSUE THREAD

**Issue by AlbertLorenzo** [HearthSim/Hearthstone-Deck-Tracker#3413]
I mean this. Sorry for my bad english :)

![sin titulo](https://user-images.githubusercontent.com/18718619/30173265-6383fcc0-93f7-11e7-8bf4-379f09d7bd6f.png)

I know I can hide the numbers but I want to hide the whole circle

**Comment by azeier** [comment]
You can disable those via `options > overlay > general > hide card marks/age`
