### ISSUE TITLE
Switching UI language doesn't refresh Decks UI

### ISSUE THREAD

**Issue by fdela** [HearthSim/Hearthstone-Deck-Tracker#3416]
After changing UI language in Options → Tracker → Appearance, decks UI isn't refreshed (HDT restart required).
NB: the "ALL" string is not translated (translatable?)
 
![image](https://user-images.githubusercontent.com/29602664/30474020-88a94332-9a02-11e7-9b23-411264d535af.png)

![image](https://user-images.githubusercontent.com/29602664/30474447-011ce87c-9a04-11e7-8e9c-963f15cc11d4.png)

**Comment by Zawodowiec1532** [comment]
HearthSim/HDT-Localization#36
