### ISSUE TITLE
Malfurion the Pestil (bug)

### ISSUE THREAD

**Issue by Forknon** [HearthSim/Hearthstone-Deck-Tracker#3422]
![2017-09-18 13 01 55](https://user-images.githubusercontent.com/32041599/30537530-a81f1c4c-9c72-11e7-9145-bae8b959bf54.png)

**Comment by azeier** [comment]
Issue moved to [HearthSim/HSTracker #882](https://github.com/HearthSim/HSTracker/issues/882) via [**ZenHub**](https://www.zenhub.com/)
