### ISSUE TITLE
Error: Invalid URI after update

### ISSUE THREAD

**Issue by 29988122** [HearthSim/Hearthstone-Deck-Tracker#3424]
## Bug report
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
### Expected Behavior
The tracker successfully executed after update.

### Actual Behavior

Program stuck at splash screen, showing this error

### Steps to reproduce behavior
Normally start the app.
No idea, it just happened after latest upgrade. 

########## 9/20/2017 1:58:10 PM ##########
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at Hearthstone_Deck_Tracker.UITheme.CreateWindowsAccentStyle(Boolean changeImmediately)
   at Hearthstone_Deck_Tracker.UITheme.InitializeTheme()
   at Hearthstone_Deck_Tracker.Core.<Initialize>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by riQQ** [comment]
Please post the corresponding HDT log. See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#hdt-log-files.

**Comment by 29988122** [comment]
Sorry, I thought crashlog's enough..

2:04:14 PM|Info|Config.Load >> Moved config to local
2:04:14 PM|Info|Core.Initialize >> HDT: 1.4.3.3257, Operating System: Windows 10 Education 15063, .NET Framework: 460798
2:04:14 PM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...

The hdt_log.txt under program folder only showed these line. 
The one under appdata\roaming folder are much longer, please check the attached file.

Thank you for developing this masterpiece!
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1316759/hdt_log.txt)

**Comment by Zawodowiec1532** [comment]
Have you set application accent to "Windows Accent" after update?
Can you post your config file? Also do you have in HDT folder "WindowsAccent.xaml" file? (In %appdata%).

**Comment by azeier** [comment]
Fixed with [v1.4.4](https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/tag/v1.4.4). You will sadly have to manually update (overwrite your installation).

**Comment by 29988122** [comment]
Yes, I can confirm that the issue's gone. Surprised that how fast and energetic you are on the bugfix. I often took days to fix even a simple bug on my own project..

Thank you again, been using the tracker since v0.10.11 and you guys rocks.
