### ISSUE TITLE
A second window opens with starting of HDT

### ISSUE THREAD

**Issue by dwarfnose** [HearthSim/Hearthstone-Deck-Tracker#3425]
### Expected Behavior
I expect only the main window to be there, like before the update.

### Actual Behavior
Every time HDT is started a small second window opens, too. 
This window is not reacting to any clicks on his buttons. It's not shown in task manager and process explorer, only at the desktop, like shown in the screenshot.

### Steps to reproduce behavior
It's every time even with a restart of HDT and Windows. And after deinstall and new install.

I don't have any entries in the win-log for .net frameworks

### Log/Screenshots
![screenshot](https://user-images.githubusercontent.com/32141947/30661203-8c428072-9e43-11e7-9724-fcdfb9018aa7.png)
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1318833/hdt_log.txt)

edit 28.09.2017:
It seems my Nvidia driver is/was the culprit. after an update to the newest version (376.62 -> 385.69), the second window is gone.
so you could close this issue

**Comment by riQQ** [comment]
Thanks for the feedback.
