### ISSUE TITLE
Exporting in secondary language

### ISSUE THREAD

**Issue by Drakonluke** [HearthSim/Hearthstone-Deck-Tracker#3428]
### Expected Behavior
Case 1:
**Export** -> **Copy Names to Clipboard** -> click on Secondary Language (**Italian**) should give italian names in the clipboard

Case 2:
Right-click on a **deck** -> **Export** (or **Export** -> **To hearthstone**) should give an option to use secondary language names (like "case 1" choice)

### Actual Behavior
Case 1: Names copied in clipboard are in english anyway
Case 2: No choice of exporting, only english right away.

### Steps to reproduce behavior
The behavior is consistent in version 1.4.3

### Log/Screenshots
Not necessary.

**Comment by Drakonluke** [comment]
Short story: I tried to export a deck for an Italian speaking friend. Since the Export to Hearthstone feature didn't give me the choice of exporting in Italian, I tried to copy the italian names on the clipboard, but it didn't work.
I think that the Export to Hearthstone should give the option to use the secondary language. The Copy names to Clipboard is simply not working anymore.

**Comment by Zawodowiec1532** [comment]
**Workaround:** It's little buggy, but it's possible to copy names in Italian language. Use your "Case 1" scenario. In options you need to set for example: "Primary language: Italian, Secondary only 1 checkbox selected with English." - Restart your application after changing card language.

**Problem:** While in selecting language dialogue buttons are reversed.. And if there are selected multiple languages it's showing only 2 of them.

Thanks for report. :)

**Comment by Drakonluke** [comment]
Thank you for the answer!
And my compliments for the good job so far!
