### ISSUE TITLE
Overlay displayed in wrong game

### ISSUE THREAD

**Issue by raspi** [HearthSim/Hearthstone-Deck-Tracker#3429]
## Bug report
HDT is displayed in wrong game. 

### Expected Behavior
Overlay shows in HS.

### Actual Behavior
Overlay shows in wrong game. "Flash hearthstone on turn start" also flashes the wrong game.

### Steps to reproduce behavior
* Open Steam
* Install TransportDefender http://store.steampowered.com/app/685310/Transport_Defender/
* Start TransportDefender
* Start HDT
* Start HS

![hsdeckbug2](https://user-images.githubusercontent.com/132441/30932143-4e484ff4-a3cf-11e7-88ba-b5e1a06373fe.jpg)

**Comment by riQQ** [comment]
Enable `Options > Advanced Options` and check if `Tracker > Settings > Advanced Window Search` is disabled.

**Comment by raspi** [comment]
That fixed it.
