### ISSUE TITLE
Flavor Text uses system font color, low visibility with customized windows themes

### ISSUE THREAD

**Issue by CountOverride** [HearthSim/Hearthstone-Deck-Tracker#3430]
## Bug report
The font color of the flavor text entry is virtually invisible when using a light on dark windows theme and becomes mostly unreadable if gray in tone. My best guess (noob programmer, not skilled enough to work on the issue myself quite yet) is that that text is taking the system font color as it's source rather than a predetermined one like the rest of the text in the program. setting a constant color for that should fix the issue as far as I know. I'd attach a screenshot, but the internal screenshot mechanism in hearthstone decided not to have the UI of HDT included when i tried to get one. I'll use an external one if needed at a later time.

### Expected Behavior
Flavor text on card hover should be visible despite having customized Windows 7 theme font color.

### Actual Behavior
Flavor text font color is a low visibility over the background color mid gray (which matches my system font color) and makes the text unreadable. That feature becomes unuseable with windows theme customization if using a light text on dark theme.

### Steps to reproduce behavior
Have a custom theme for Windows 7 that uses a lighter, non-black font color, or change system font color to one without customizing theme, and it should appear.

**Comment by Zawodowiec1532** [comment]
ps. atm you can press "Print Screen" and then Ctrl + V in paint to get screenshot with UI. :)
