### ISSUE TITLE
(Bug) My deck and my opponent's deck won't show.

### ISSUE THREAD

**Issue by Chesseron** [HearthSim/Hearthstone-Deck-Tracker#3431]
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1343066/hdt_log.txt)
This bug is that i cant see my deck or oppenents deck when he plays cards. I can still see his cards(what turn drawed, mulliganed, etc.) I have tried tinkering in the HDT settings but to no avail. I cant replicate this bug, it just happens as soon as a game starts and HDT is running. bug started happening around the new tavern brawl (around 9/27/17, brawl called encounter at the crossroad)

**Comment by riQQ** [comment]
```
9:44:49 PM|Info|Core.Initialize >> HDT: 1.4.1.3242, Operating System: Windows 10 Home 15063, .NET Framework: 460798
[...]
9:45:14 PM|Error|TrayIcon..ctor >> Cant find tray icon at "C:\Users\Muhamadjon\AppData\Local\HearthstoneDeckTracker\app-1.4.1\Images\HearthstoneDeckTracker16.ico"
9:45:16 PM|Error|Card.Background >> Image builder failed: Object reference not set to an instance of an object.
```
Your installation is missing files and you're on an old version. Please reinstall / update HDT.
