### ISSUE TITLE
Can't see Card Marker Age

### ISSUE THREAD

**Issue by Golundo** [HearthSim/Hearthstone-Deck-Tracker#3433]
![30173265-6383fcc0-93f7-11e7-8bf4-379f09d7bd6f](https://user-images.githubusercontent.com/32426650/31051779-630450ce-a626-11e7-9b8b-633cc0b24c2c.png)
Currently on 1.4.3
For some reason I cannot see the Card age like in the picture. It use to work fine but about 1month ago it started to not show in games. Tried Enable/Disable  > overlay > general > hide times didn't work, 
Tried  Enable/Disable  > overlay > opponent > Hide card age don't work. Tried Reinstalling Decktracker and also reinstalling Hearthstone. Tried Erasing Decktracker folder in AppData folder reinstall, that didn't work either. Am i missing something? did that feature get removed? Need help please! thats most important feature for me.
I cannot even see the Circle box surrounding the numbers

**Comment by Zawodowiec1532** [comment]
Options > Overlay > Opponent > UNCHECK:
Hide card-age
Hide card-marks

**Comment by Golundo** [comment]
Not working...

**Comment by Zawodowiec1532** [comment]
Can you upload your config file?
Do you have `Opacity` in `Options > Overlay > Opponent` value set to diffrent than 0?

**Comment by Golundo** [comment]
Nope. Thanx for trying to help but obviously I played with all of those settings. I don't think its option issue been resetting and reinstalling DT. Heres my config file I hope its the right one.

**Comment by Zawodowiec1532** [comment]
Just tried your config and I can see Card Markers. :/
- Try run HDT as Admin.
- Try portable version(?).
- Are you using any other software which may cause such behaviour? Especially those with Overlays, like  for example Overwolf. Could you try with only HDT + Hearthstone launched?
Also after playing a game attach HDT Log. Thanks.

**Comment by Golundo** [comment]
Running as Admin don't work
I don't know where I can find portable version.
Not using any particular software.
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1347474/hdt_log.txt)
 It worked fine untill around the frozen throne update.
Heres my Log file hope it helps, and again thanks for helping me! but no luck yet =(

**Comment by Zawodowiec1532** [comment]
https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases

Can you check those HDT versions? If you say that previous one worked fine, could you check which one?
ps. skip 1.4.3 version. :P

**Comment by riQQ** [comment]
Are the decks in the overlay working or is the overlay completely invisible?

**Comment by Golundo** [comment]
Timer and Card/Fatigue Counter worked fine, but the Deck overlay didn't show. For now its working on window mode after reinstailling HS and DT to 1.4.4 but when I switch to Full screen markers dissapear again =(

**Comment by riQQ** [comment]
Which resolution are you using?

**Comment by riQQ** [comment]
How did you resolve it?
