### ISSUE TITLE
Feature request : implemented

### ISSUE THREAD

**Issue by TristanCP** [HearthSim/Hearthstone-Deck-Tracker#3438]
Just to say my feature request here, which was obviously needed and not only by me, was closed for a wrong reason without any further reading from the closer : https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3327

But hopefully, there are some more clever people at hsreplay who have implemented the feature on the web site (the new "matchups" tab with the "archetype" column), so nice !

**Comment by riQQ** [comment]
You should have posted this in the original issue.
