### ISSUE TITLE
Arena reward card name auto-complete / check doesn't recognise Arcane Intellect

### ISSUE THREAD

**Issue by sprossiter** [HearthSim/Hearthstone-Deck-Tracker#3439]
### Expected Behavior
The auto-complete / checker for card names (when entering arena rewards and probably used elsewhere) recognises all card names.

### Actual Behavior
It didn't recognise Arcane Intellect. (I tried a few alternative spellings in case there was a typo your end, but nothing....)

### Steps to reproduce behavior
Try to enter Arcane Intellect as card name in arena rewards screen.

**Comment by riQQ** [comment]
Arcane Intellect is a card from the basic set. It can't be obtained by rewards or packs.

**Comment by Zawodowiec1532** [comment]
It's already fixed in https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/c736bc82f70facb2c838cdb6167993529419cb2a

**Comment by riQQ** [comment]
@Zawodowiec1532 you're mixing up classic and basic set.

**Comment by sprossiter** [comment]
Yeah my bad: it was a card reward for levelling mage but, because it came at the end of my Arena run, I thought it was somehow an Arena reward.

I guess there's still a (very low priority) bug in that it should ideally tell you something like "Basic cards cannot be granted as Arena rewards" rather than "That card doesn't exist".

**Comment by Zawodowiec1532** [comment]
@riQQ Yeah, I just didn't look at card name :D
