### ISSUE TITLE
Wrong Arena Deck import time

### ISSUE THREAD

**Issue by sauce-code** [HearthSim/Hearthstone-Deck-Tracker#3441]
### Expected Behavior

When importing an arena deck, I used the default Arena Deck Name Template:
`Arena {Date dd-MM hh:mm}`

so the expected name was 

> Arena 06-10 21:37

### Actual Behavior
But the he actual deck name was
> Arena 06-10 09:37

So if I play multiple Arena Decks a day, for example some in the morning, some in the afternoon/evening,  the deck naming will reult in a non-chronological order.

### Log/Screenshots
![image](https://user-images.githubusercontent.com/9353871/31296411-7670a37c-aae2-11e7-9db0-af7b94ff257a.png)
![image](https://user-images.githubusercontent.com/9353871/31296423-820696b0-aae2-11e7-9039-d408d5d5d49e.png)

**Comment by Zawodowiec1532** [comment]
Edit this to: "Arena {Date dd-MM HH:mm}"

https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings

**Comment by sauce-code** [comment]
Thanks, problem solved..

Anyway, woudn't it be more intuitive to set the default format to 24h instead of 12h ?
I guess that would meet a more international standard.

**Comment by Zawodowiec1532** [comment]
It is already default. I guess it just didnt change after update.

https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/Config.cs#L135
