### ISSUE TITLE
HDT Deck Overlay not Showing

### ISSUE THREAD

**Issue by Chairos88** [HearthSim/Hearthstone-Deck-Tracker#3442]
### Expected Behavior
Opponent and Player Deck being drawn on screen

### Actual Behavior
Space is actually reserved (observable through "unlock overlay"  option, jade golem and secret counters correctly show

### Log/Screenshots
Already running HDT in administrator mode. Tried to launch it in compatibility mode for windows 7 and windows 8. I'm Actually on windows 10.

Config.xml: <VisibleOverlay>false</VisibleOverlay> This line seems fishy. Even if i set it to "true" it still goes back to being false, event with HDT not running.

[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1364604/hdt_log.txt)

[Windows Application Error.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1364611/Windows.Application.Error.txt)
[Windows .NET Runtime.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1364612/Windows.NET.Runtime.txt)

![22343943_10214229358756538_1608278122_o](https://user-images.githubusercontent.com/32594277/31307964-39f71872-ab6e-11e7-99f2-964ef72105e4.jpg)

Needed to take a picture of the screen since when HS is in foreground the printscreen function only takes it and not the overlay.

**Comment by riQQ** [comment]
Is the error / crash related to this issue?
Which line is fishy?
Could you post your config.xml file?

**Comment by Chairos88** [comment]
Sorry, it didn't show the tag correctly. I'll update config.xml as soon as I can. The tag that seems fishy is the visible overlay one. It' set to false and can't be made true in any way I tried.

**Comment by riQQ** [comment]
Have you enabled the `Cards` item at `Options > Overlay > Player / Opponent`?

**Comment by Chairos88** [comment]
It wasn't enabled. Now it's enabled but the issue still occurs. Is a system restart required?
