### ISSUE TITLE
Fix start Hearthstone with new beta battle.net app

### ISSUE THREAD

**Issue by azeier** [HearthSim/Hearthstone-Deck-Tracker#3448]

**Comment by Zawodowiec1532** [comment]
I think it's bugged in beta and we can't do much about it atm. :/
Even tried to rename blizz app to "Battle.net.exe" from "Battle.net.beta.exe", to be sure it will use URI Protocols from registry, but it's only changing tab to Hearthstone and not launching it. If you have any ideas then tell me :D
![g](https://user-images.githubusercontent.com/540256/31748880-7113e400-b476-11e7-85c3-313211e95850.png)
