### ISSUE TITLE
The HDT doesn't work for 

### ISSUE THREAD

**Issue by edwardssn** [HearthSim/Hearthstone-Deck-Tracker#3450]
### Actual Behavior

the tracker doesn't work for version 9.2.0.22017 on Mac OS. I upgraded HDT today. HDT does launch but nothing happens in game.

**Comment by riQQ** [comment]
This is the repository for the tracker for Windows. See https://github.com/HearthSim/HSTracker/issues/886 for the correct repository and exactly your issue.
