### ISSUE TITLE
Attack counter displays incorrect values

### ISSUE THREAD

**Issue by riQQ** [HearthSim/Hearthstone-Deck-Tracker#3451]
## Bug report
This was reported by multiple users on Discord.

### Expected Behavior

Correct values

### Actual Behavior

Incorrect  values

### Steps to reproduce behavior

Circumstances are not yet clear.

### Log/Screenshots

![attack counter bugged](https://user-images.githubusercontent.com/3404787/31755916-49f2dbc6-b4a1-11e7-8c42-7551b65ffcd9.jpg)

![attack counter bugged](https://user-images.githubusercontent.com/3404787/31756072-37401e98-b4a2-11e7-8ed4-580a76fc2f92.png)

**Comment by MGK82** [comment]
First idea after seeing the screenshots: Shifter Zerus on your own hand is counted as 1 atk, no matter its form when played.

**Comment by riQQ** [comment]
That's probably it, thanks for the hint.

**Comment by azeier** [comment]
Fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/f48fcae3084d350d5b2c5450ba56cef8966916e3
