### ISSUE TITLE
Installation problems Windows 10

### ISSUE THREAD

**Issue by ienamas** [HearthSim/Hearthstone-Deck-Tracker#3452]
## Bug report
My portable pc refuses to install hdt

### Expected Behavior

Install it?
### Actual Behavior

When i click on HDT installer nothing happens. In the programs list,in control panel, the app appears but i cannot run it. I believe the problem come from .NET framework. I have actually installed 5+ version. 
![problema  #hdt](https://user-images.githubusercontent.com/32929599/31769333-71cff76e-b4d3-11e7-961d-fde76257b036.png)

**Comment by Zawodowiec1532** [comment]
- Have you tried portable version of HDT? https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/download/v1.5.1/Hearthstone.Deck.Tracker-v1.5.1.zip
- Have you launched installator as Admin?

**Comment by ienamas** [comment]
i've tried both your solutions. When i click on hdt in the portable version, it stops to work.

**Comment by ienamas** [comment]
Nome registro: Application
Origine:       Application Error
Data:          19/10/2017 17:58:38
ID evento:     1000
Categoria attività:(100)
Livello:       Errore
Parole chiave: Classico
Utente:        N/D
Computer:      DESKTOP-FT0D17E
Descrizione:
Nome dell'applicazione che ha generato l'errore: Hearthstone Deck Tracker.exe, versione: 1.5.1.3284, timestamp: 0x59e7141d
Nome del modulo che ha generato l'errore: unknown, versione: 0.0.0.0, timestamp: 0x00000000
Codice eccezione: 0xc0000005
Offset errore 0x06432f68
ID processo che ha generato l'errore: 0x24c0
Ora di avvio dell'applicazione che ha generato l'errore: 0x01d348f31fca3df1
Percorso dell'applicazione che ha generato l'errore: C:\Users\simon\Desktop\Hearthstone Deck Tracker\Hearthstone Deck Tracker.exe
Percorso del modulo che ha generato l'errore: unknown
ID segnalazione: 1ff31c4b-4efd-47b7-9bc9-29ec00a16bc9
Nome completo pacchetto che ha generato l'errore: 
ID applicazione relativo al pacchetto che ha generato l'errore: 
XML evento:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-10-19T15:58:38.192626900Z" />
    <EventRecordID>397659</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-FT0D17E</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Hearthstone Deck Tracker.exe</Data>
    <Data>1.5.1.3284</Data>
    <Data>59e7141d</Data>
    <Data>unknown</Data>
    <Data>0.0.0.0</Data>
    <Data>00000000</Data>
    <Data>c0000005</Data>
    <Data>06432f68</Data>
    <Data>24c0</Data>
    <Data>01d348f31fca3df1</Data>
    <Data>C:\Users\simon\Desktop\Hearthstone Deck Tracker\Hearthstone Deck Tracker.exe</Data>
    <Data>unknown</Data>
    <Data>1ff31c4b-4efd-47b7-9bc9-29ec00a16bc9</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

Nome registro: Application
Origine:       .NET Runtime
Data:          19/10/2017 17:58:37
ID evento:     1026
Categoria attività:Nessuna
Livello:       Errore
Parole chiave: Classico
Utente:        N/D
Computer:      DESKTOP-FT0D17E
Descrizione:
Applicazione: Hearthstone Deck Tracker.exe
Versione framework: v4.0.30319
Descrizione: il processo è stato terminato a causa di un'eccezione non gestita.
Informazioni sull'eccezione: codice eccezione c0000005, indirizzo eccezione 06432F68

XML evento:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-10-19T15:58:37.853105200Z" />
    <EventRecordID>397658</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-FT0D17E</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Applicazione: Hearthstone Deck Tracker.exe
Versione framework: v4.0.30319
Descrizione: il processo è stato terminato a causa di un'eccezione non gestita.
Informazioni sull'eccezione: codice eccezione c0000005, indirizzo eccezione 06432F68
</Data>
  </EventData>
</Event>

**Comment by riQQ** [comment]
Does it work, when you start Windows in Safe Mode?

**Comment by ienamas** [comment]
Yes, it does. How could i make it works in windows normal mode?

**Comment by riQQ** [comment]
So this is similar to #3409.

I don't really know, what is causing this.  It has to be some process that is running in normal mode and isn't running in safe mode.

**Comment by Zawodowiec1532** [comment]
- Disabling antivirus helps?

**Comment by ienamas** [comment]
Unfortunately, not.

**Comment by riQQ** [comment]
Can you please provide a minidump:
- Create this registry key `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps`
- Start HDT and let it crash
- Upload the crash dump from `%LocalAppData%\CrashDumps\`
- By deleting the registry key, crash dump creation is turned off again.

**Comment by ienamas** [comment]
![registro](https://user-images.githubusercontent.com/32929599/31834588-bbe2c268-b5ce-11e7-8c30-c91e17dae616.png)
this is what i see,what must i do? i'm not really expert.

**Comment by riQQ** [comment]
That should be enough. Check the folder mentioned above for crash dumps.
If there aren't any, check if there's a key `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\Windows Error Reporting\LocalDumps`

**Comment by ienamas** [comment]
![registro 2](https://user-images.githubusercontent.com/32929599/31834924-f1cb57ea-b5cf-11e7-978c-7527573dc688.png)
there isn't second key you posted. Must i create it?

**Comment by riQQ** [comment]
Yes, create it and then do the steps i posted above.

**Comment by ienamas** [comment]
i created the missing key, i don't know how to go on. How do i complete this passage:
Zip and upload the crash dump from %LocalAppData%\CrashDumps\

**Comment by riQQ** [comment]
`Windows + R` and paste the path. This should open the folder with the crash dumps, if there are any.

**Comment by ienamas** [comment]
The archive is too big to update. So this is it


![crashdumps 1](https://user-images.githubusercontent.com/32929599/31839732-abb8b9f6-b5e2-11e7-921d-05701f4f0391.png)

**Comment by riQQ** [comment]
Upload it here: http://www.zippyshare.com/

**Comment by ienamas** [comment]
http://www83.zippyshare.com/v/EWwUsWzv/file.html

**Comment by riQQ** [comment]
Looks like something in your AMD OpenCL driver is crashing. Try reinstalling or updating your graphics card drivers.
```
STACK_TEXT:  
WARNING: Frame IP not in any known module. Following frames may be wrong.
05e0d240 642db35b 00000ccf 05f03d28 05f06880 0x11d2260
05e0d264 642de34f 05e0d298 00000001 05e9e3d0 amdocl12cl+0xb35b
05e0d29c 642da5a4 00000001 05e9e3d0 00000cce amdocl12cl+0xe34f
05e0d2c4 642f6d42 00000000 05e9e3d0 00000cce amdocl12cl+0xa5a4
05e0d2d8 67988266 011fa9b0 05e6c858 05e9e3d0 amdocl12cl+0x26d42
05e0d2f8 674e480d 011fa9b0 05e6c858 05e9e3d0 amdocl+0x698266
05e0d8a0 674a1237 05e6c858 05e0db18 00000000 amdocl+0x1f480d
05e0db40 674ad956 011d1dac 011c2528 05e0db60 amdocl+0x1b1237
05e0dd00 674a20ef 05e0dd70 011c2528 00000000 amdocl+0x1bd956
05e0dd90 674bd1cc 05ef80f0 011d1d98 00000000 amdocl+0x1b20ef
05e0df08 674bf846 012123b8 00000002 05e0dfb8 amdocl+0x1cd1cc
05e0df58 674bc1e6 00000000 674a3ed6 00000000 amdocl+0x1cf846
05e0df80 6748c312 00000000 6748c2b0 05e0dfc0 amdocl+0x1cc1e6
05e0df90 73fc10a2 00000000 00000000 05e0dfb8 amdocl+0x19c312
05e0dfc0 73fc3cab 05e0dfd4 10004f90 73fd50c4 OpenCL+0x10a2
05e0e3e8 77b9f830 73fd50c4 00000000 00000000 OpenCL+0x3cab
05e0e410 75b855e7 73fd50c4 73fc3c00 00000000 ntdll!RtlRunOnceExecuteOnce+0x70
05e0e428 73fc3d44 73fd50c4 73fc3c00 00000000 KERNELBASE!InitOnceExecuteOnce+0x17
05e0e44c 1000b981 00000000 00000000 05e0e470 OpenCL+0x3d44
05e0e878 1000c066 00000000 00000000 05e0e8b8 amf_wic_jpeg_decoder32+0xb981
05e0f8c0 1000abf8 100dbe48 0000000b b878d2e7 amf_wic_jpeg_decoder32+0xc066
05e0f8f0 1000ace5 b878d303 10004f90 01200228 amf_wic_jpeg_decoder32+0xabf8
05e0f914 10007d55 10004f98 05e0f934 770c8744 amf_wic_jpeg_decoder32+0xace5
05e0f920 770c8744 100dc260 770c8720 51da7cff amf_wic_jpeg_decoder32+0x7d55
05e0f934 77bb582d 100dc260 0fad4c10 00000000 kernel32!BaseThreadInitThunk+0x24
05e0f97c 77bb57fd ffffffff 77bd637d 00000000 ntdll!__RtlUserThreadStart+0x2f
05e0f98c 00000000 10004f90 100dc260 00000000 ntdll!_RtlUserThreadStart+0x1b
```

**Comment by ienamas** [comment]
I have installed hdt without graphic drivers installed and it seems to work.Then i re-installed AMD drivers and hdt opens whitout problems.

**Comment by riQQ** [comment]
Glad it works now ;)

**Comment by ienamas** [comment]
Thanks for your support. It took us 2-3 days but we made it. =D
