### ISSUE TITLE
Settings for plug-ins (e.g. Graveyard) won't open

### ISSUE THREAD

**Issue by virtenebris** [HearthSim/Hearthstone-Deck-Tracker#3454]
### Expected Behavior
When clicking on "Settings" within the plug-ins, a pop-up menu would appear to adjust the behavior of the plug-in.

### Actual Behavior
Nothing. Clicking on "Settings" had no effect.

### Steps to reproduce behavior
Install the latest Graveyard plug-in, go to Tracker > Plugins, select the plug-in, set it to Enabled, click "Settings".

**Comment by azeier** [comment]
Duplicate https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3453
