### ISSUE TITLE
HDT on iMac doesnt Auto-detect deck anymore

### ISSUE THREAD

**Issue by egokaite** [HearthSim/Hearthstone-Deck-Tracker#3459]
### Log/Screenshots

A couple of days ago HDT stopped working completely, in particular it doesnt autodetect decks anymore and it doesnt record any result. Tried to unistall and install it again but nothing seems to work

**Comment by judge2020** [comment]
This is the windows tracker, please file at https://github.com/HearthSim/HSTracker/issues.
