### ISSUE TITLE
Fatespinner dying resets deck tracker

### ISSUE THREAD

**Issue by halfmassed** [HearthSim/Hearthstone-Deck-Tracker#3460]
## Bug report
This has occurred three consecutive times so far in my arena run (Priest-Druid arena), on 10/26.

### Expected Behavior
When I play Fatespinner and it dies, it shouldn't affect the deck tracker in any way. 

### Actual Behavior
After my Fatespinner dies, a warning appears "WARNING: Fatespinner not found in deck" and the deck tracker resets, as if I were not using a known deck. If I try to click "Use" for the arena deck during that same game, the warning instantly reappears and the deck tracker resets again. 

The tracker also doesn't log the game where this occurs in the stats section. The trackers starts working normally again after the game ends, and tracks any arena game where Fatespinner doesn't die normally.

### Steps to reproduce behavior
Has happened three consecutive times so far. Try playing a Fatespinner and killing it off.

**Comment by jakeypoo** [comment]
Happening to me as well, just as halfmassed describes. 
Can't use the tracker in arena after fatespinner dies.
