### ISSUE TITLE
Collection Tracker no longer working properly

### ISSUE THREAD

**Issue by Tim15xScope** [HearthSim/Hearthstone-Deck-Tracker#3465]
## Bug report
Collection Tracker Plugin no longer working properly after recent updates.

### Expected Behavior

When managing a collection, the flip switches in Collection Tracker no longer trigger.

### Actual Behavior

Nothing, app stays in previous state, regardless of switch.

### Steps to reproduce behavior

1) Click on "Manage Set Collection"
2) Click on either switch at top (Show all or Non-golden)
3) Results below no longer change after Step 2

### Log/Screenshots

![screenshot](https://user-images.githubusercontent.com/33187954/32139485-e93e830e-bc0f-11e7-90dc-786190ae5811.png)

**Comment by judge2020** [comment]
This is a problem for the [collection tracker repo](https://github.com/HearthSim/Hearthstone-Collection-Tracker). I am currently looking into a fix for this.
