### ISSUE TITLE
Deck Tracker Premium/Standard Not Updating

### ISSUE THREAD

**Issue by kazvorpal** [HearthSim/Hearthstone-Deck-Tracker#3467]
## Bug report

Am I supposed to add freeform text to the direct Bug Report section, or just count on the "expected/actual behavior" section below? I paid to upgrade to Premium a few days ago, and not only is it lagging behind on stats by perhaps a day and a half (or else it's actually failing to track most of my games, I am only HOPING they will eventually show up), but starting at that point my local Deck Tracker non-premium stats are lagging behind by hours or more, when I'm pretty sure they used to be updated almost immediately after a match. I seem to remember playing a match and then seeing that the stats had updated for it, regularly, before that.

Note: They are showing up in the replays, just not in the stats.

### Expected Behavior
I expect Deck Tracker to update stats to my local client almost immediately, and my premium stats online within a few hours.

### Actual Behavior
Deck Tracker has not updated my premium stats online for perhaps 36 hours, and has not updated my local client stats all morning, perhaps longer...I wasn't expecting to have to track it myself, so I'm not certain how long. Local deck tracker was lagging behind by hours yesterday, too, but I THINK it finally updated yesterday's, by this morning.

### Steps to reproduce behavior
This has been an ongoing problem since almost exactly when I upgraded to the ostensible premium deck tracker, so in that sense I can reproduce it, yes.

While the Premium page claimed it only is delayed a few hours, perhaps a day or so is actually normal? If so, the bug there is simply the text telling me it should only take a few hours. But the local Deck Tracker is definitely slower updating than it used to be, although I don't see why that would happen from updating to premium.

### Log/Screenshots
I can provide the logs if necessary.
Here's a screen shot of my decks on Premium. It claims to have updated Hunter 17 hours ago, so it's at least been that long since it updated. But I believe that about 24 hours ago I switched from Hunter (which was losing horribly) to Shaman for a couple of matches, and that hasn't shown up. I also played Warlock and Pirate Warrior within the last 14 hours or so, both last night and this morning, no update. I have a Warlock deck with maybe a 90% win rate since I built it, I'm eager to see the stats for it.

Speaking of which, why do the decks all just say the class, and not the name of the deck? That kinda sucks for eyeballing which decks work well.

Post Script: It says "Last updated 27 minutes ago", yet isn't showing the ranked standard matches I played with Warrior and Warlock from this morning, nor Warlock and Shaman from last night.

![image](https://user-images.githubusercontent.com/381119/32181025-d42fa30c-bd69-11e7-8b51-c0ff936f180b.png)

**Comment by jleclanche** [comment]
@kazvorpal It's easier to reach us at contact@hsreplay.net -- we're on blizzcon prep right now, so I can't look into this immediately, but can you check if this is still an issue? our stats were paused for 24 hours the other day...

**Comment by riQQ** [comment]
Closing as this is a hsreplay.net issue
