### ISSUE TITLE
Cursor not showing for OBS Streaming

### ISSUE THREAD

**Issue by Chiken410** [HearthSim/Hearthstone-Deck-Tracker#3468]
### Bug report

 Expected Behavior
I'm using the 20.1.1 windows version of OBS to stream, and I checked the "Capture Cursor" box in the properties of the capturable overlay, and unchecked it in the Hearthstone window's properties. According to the instructions at https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Streaming-Instructions, this should let the cursor be seen over the overlay.

### Actual Behavior
The cursor does not show up at all. The cursor only shows up when I check the "Capture Cursor" box for the Hearthstone source, but the cursor goes underneath the overlay.
### Steps to reproduce behavior
Set up the sources for Hearthstone and the overlay, then hover mouse over the Hearthstone window.

### Log/Screenshots
N/A

**Comment by Reithan** [comment]
I am also having this issue

**Comment by dom39fr** [comment]
Hi, I am having the exact same issue with latest HDT and OBS 20.1.3 (x64) Windows 7... 
I followed the instructions and enabled mouse cursor on the HDT overlay and disabled on Hearthstone sources but this only has the consequence to make it disappear all together...

Is there a solution to this problem ?

**Comment by ZacharyConlyn** [comment]
I, too, am having this issue.
