### ISSUE TITLE
How I can redirect HDT to anotner folder with stats data?

### ISSUE THREAD

**Issue by Sevis** [HearthSim/Hearthstone-Deck-Tracker#3469]
I use HDT on 2 computers and I need copy stats data from one to another.
I would like create stats folders in microsoft one drive and use this folder on both computers. Than I no need to copy stats data.
How I can choose not default (another) folder for stats data?

**Comment by riQQ** [comment]
- Option 1
  - Download the portable version here https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/latest
  - Enable advanced options
  - there's a button in the options to change the folder
- Option 2
  - use a symlink

**Comment by Sevis** [comment]
What is the simlink? How I can get an use it?

**Comment by riQQ** [comment]
http://lmgtfy.com/?q=symlink+windows
