### ISSUE TITLE
Marin the Fox is down as "NOOOOOOOOOO!"

### ISSUE THREAD

**Issue by ericBG** [HearthSim/Hearthstone-Deck-Tracker#3473]
### Expected Behavior
Marin to be tracked properly as an actual card.

### Actual Behavior
A "NOOOOOOO!" card is placed in your HDT deck.

### Steps to reproduce behavior
Place Marin in a deck.

**Comment by azeier** [comment]
Working on it

**Comment by azeier** [comment]
Fixed
