### ISSUE TITLE
Can not access plugin settings

### ISSUE THREAD

**Issue by JoeMama2** [HearthSim/Hearthstone-Deck-Tracker#3474]
### Expected Behavior

Change a plugin setting.
### Actual Behavior

Nothing
### Steps to reproduce behavior

Click on settings when a plugin is enabled in Options

**Comment by azeier** [comment]
This is an issue with whatever plugin you are talking about.

**Comment by JoeMama2** [comment]
I have every plugin I have tried does not work. When I click on setting in options. So I don't think it's a plugin problem.
