### ISSUE TITLE
Overlay option keeps unchecking itself

### ISSUE THREAD

**Issue by Doomelf** [HearthSim/Hearthstone-Deck-Tracker#3477]
## Bug report

**Expected Behavior**

When I click on "Remove cards if none remaining" in the Overlay -> Player section it should stay checked. The problem remains after making a clean install of Windows.

**Actual Behavior**

Every time I open HDT the option is not checked.

**Steps to reproduce behavior**

1. Make sure the box is checked and then close HDT;
2. Reopen the program and navigate to Overlay -> Player;
3. The box should not be checked.

**Logs / Screenshots**

[2.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1471680/2.txt)
[1.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1471681/1.txt)

There are no windows error and crash report logs.

**Comment by riQQ** [comment]
Set the `log level` to 1 in `Options > Tracker > Logging` and post another log, please.

**Comment by Doomelf** [comment]
[Log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1472003/Log.txt)

**Comment by riQQ** [comment]
Sorry, forgot to the following:
- change the setting
- quit HDT
- then post the log

**Comment by Doomelf** [comment]
[Log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1472019/Log.txt)

**Comment by riQQ** [comment]
The line for HDT closing is missing, have you really closed hDT? Is the process gone (see Task Manager)?
`|Info|MainWindow.Window_Closing >> Shutting down...`

**Comment by Doomelf** [comment]
I did it again step by step and the log remains the same. Yes, the process in Task Manager is gone. The line you wrote was not found in the log.

**Comment by riQQ** [comment]
If that line isn't there, your config won't be saved. It's very strange, that this line doesn't appear in your log. This means the code saving the config on quitting HDT isn't executed. So it won't save any options your changing. Is that true?

It works for me.

**Comment by Doomelf** [comment]
It is saving every other change in options I make, except this one. Very peculiar indeed.

**Comment by riQQ** [comment]
Can you try changing `<RemoveCardsFromDeck>false</RemoveCardsFromDeck>` in `%appdata%\HearthstoneDeckTracker\config.xml` from `false` to `true`, while HDT is closed?

**Comment by Doomelf** [comment]
It worked! After changing the code HDT started saving this setting and it no longer unchecks itself after restarting the program. Thank you 👍
