### ISSUE TITLE
HDT stopped working due to different user privilegues

### ISSUE THREAD

**Issue by m-klingelhoefer** [HearthSim/Hearthstone-Deck-Tracker#3478]
### Expected Behavior

HDT working as usual
### Actual Behavior

HDT does not track cards, wins or anything else, sometimes giving error code like that HS was started with other user privilegues such as admin rights, which should not be the case.
### Steps to reproduce behavior

After every start of HDT it is not working, sometimes giving the error message mentioned above

**Comment by jleclanche** [comment]
Have you tried starting HDT as admin?

HDT needs access to Hearthstone's memory, which needs same-user access but is sometimes blocked by policies or other software. Running HDT as admin should fix this.
