### ISSUE TITLE
Add support for Dungeon Runs

### ISSUE THREAD

**Issue by stephanechorne** [HearthSim/Hearthstone-Deck-Tracker#3493]
In dungeon run mode HSDT currently only shows the cards drawn during a match and there's no way to import the deck.

It would be nice if HSDT automatically imported and updated your dungeon run deck as you're progressing. Thanks!

**Comment by azeier** [comment]
Actively being worked on.

**Comment by azeier** [comment]
Looking for testers for this.

Deck selection and deck updating when picking loot should be working.
Deck list and stats filtering is still on the todo list.

Download the development build here: https://github.com/HearthSim/HDT-dev-builds/releases/latest/
This build will replace your current HDT installation and automatically update to the stable release once that is available.

**Comment by Urtgard** [comment]
Played a few runs without problems.

It shows the passive buffs in the decklist. Is there a option to hide them?

**Comment by stephanechorne** [comment]
How do you get it to show the whole deck? I'm on `v1.5.7-dev3362` and didn't notice any difference in dungeon runs.

**Comment by azeier** [comment]
Pushed a new update to the dev release (either enable the checkbox in the bottom right or just reinstall from the link above).

This fixed a bug where importing the warlock deck wouldn't work correctly and adds dungeon and brawl support to the deck picker UI.

@stephanechorne Were you playing warlock by any chance? If so see if the new build fixes it. Otherwise could you upload a log? See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by stephanechorne** [comment]
Ah that's why. I was indeed only playing Warlock 🙂 Works now, thanks!

**Comment by azeier** [comment]
@Urtgard Showing the passive buffs is intended currently. Hiding them is a bit more complicated / ugly. I'll keep it in mind though - if there's more feedback about it I'll have a look again.

**Comment by azeier** [comment]
Pushed another update.

- Fixed an issue where dungeon deck importing wouldn't work sometimes
- Added menu options for disabling dungeon deck importing, name template and excluding passives (`options (advanced) > tracker > importing`) 

@Urtgard - found an easy way to add that afterall :P

**Comment by azeier** [comment]
Released with v1.5.7.

Thanks for testing guys.

**Comment by jnierodzik** [comment]
Will this make it's way into the Mac version soon?

**Comment by judge2020** [comment]
cc @HearthSim/hstracker ^
