### ISSUE TITLE
HDT crashing at startup

### ISSUE THREAD

**Issue by floskan** [HearthSim/Hearthstone-Deck-Tracker#3494]
Every single time i start HDT, it crashes. It worked before so either it's a recent patch for HDT itself or a windows update that messed it up. I tried repairing my Windows installation, verifying my .NET framework, installing the latest drivers for my GPU and finally using the zipped version of HDT but NOTHING works. I submitted a log in case someone can help me. 

[hdt_log_1512947256.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1546176/hdt_log_1512947256.txt)

**Comment by riQQ** [comment]
Please provide crash logs and windows logs (see https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues)

**Comment by floskan** [comment]
My application error : 
Felet uppstod i programmet med namn: HDTUninstaller.exe, version 1.0.0.0, tidsstämpel 0x5a28c07c
, felet uppstod i modulen med namn: d3d9.dll, version 10.0.16299.98, tidsstämpel 0xe2fbf0fc
Undantagskod: 0xc0000096
Felförskjutning: 0x000481d1
Process-ID: 0x34b8
Programmets starttid: 0x01d3720bb0b89d36
Sökväg till program: C:\Users\n0rbe\Desktop\Hearthstone Deck Tracker\HDTUninstaller.exe
Sökväg till modul: C:\WINDOWS\SYSTEM32\d3d9.dll
Rapport-ID: 63d16f55-c725-4194-a163-2ced769de0a7
Fullständigt namn på felaktigt paket: 
Program-ID relativt till felaktigt paket: 

.Net framework error: 
Tillämpningsprogram: Hearthstone Deck Tracker.exe
Framework-version: v4.0.30319
Beskrivning: Processen avslutades på grund av ett ohanterat undantag.
Undantagsinformation: undantagskod c0000096, undantagsadress 676E81D1

**Comment by riQQ** [comment]
Try up- or downgrading your graphics card driver.

**Comment by floskan** [comment]
Didn't work either up or down. I guess all that's left is reformatting.

**Comment by riQQ** [comment]
You can try updating DirectX. Which windows version are you using?

**Comment by floskan** [comment]
I'm using the very latest windows 10 update, and my directx is up to date. Feels like i might have a bad driver somewhere in my system or something, since i can't get it to work no matter what.

**Comment by riQQ** [comment]
See #2676, there's a workaround that could help you.

**Comment by oompaloomp** [comment]
My HDT crash when iuse Dust Utility
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1560534/hdt_log.txt)

**Comment by azeier** [comment]
@oompaloomp You should report that on the [Dust Utility repo](https://github.com/CLJunge/Spawn.HDT.DustUtility).

**Comment by floskan** [comment]
So, it worked after i reformatted my entire computer. Still worth it though. :)

**Comment by riQQ** [comment]
You could have tried uninstalling that one update but okay.

**Comment by ActionJacksonATL** [comment]
I cannot get HDT to "work": the program loads, shows all of my decks, but it's very slow, and the overlay only shows 0/30.  Was working fine last night.

Tried uninstalling/reinstalling but didn't resolve the issue.
