### ISSUE TITLE
Secret Betrayal Greyed Out after Druid Hero Power attacks Rogue

### ISSUE THREAD

**Issue by TheOssumOpossum** [HearthSim/Hearthstone-Deck-Tracker#3495]
### Expected Behavior

Sudden Betrayal should not grey out after a hero attacks the Rgoue

### Actual Behavior

Sudden Betrayal greyed out after attacking the enemy hero with Druid's Hero Power. Before attacking with the hero, I attacked with a singular minion on board and the hero power did not grey out.

### Steps to reproduce behavior

Attack a Rogue with the Druid Hero Power (or maybe other classes and weapons) while Secret Betrayal is up and there is a minion on board

### Log/Screenshots

https://hsreplay.net/replay/pYUK6S5zXTACVKptzr9FwF, turn 9 for druid

**Comment by azeier** [comment]
Fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/510051701186da5f343af60f307172a67946a502 for the next release.

Leaving this open for the time being.

**Comment by azeier** [comment]
Fixed with v1.5.7
