### ISSUE TITLE
Missing Arena Decks

### ISSUE THREAD

**Issue by Moiddes** [HearthSim/Hearthstone-Deck-Tracker#3498]
Hi guys,

I'm trying to use the HDT for recording my questionable success in Arena for K&C. However, HDT seems to delete my arena decks for no apparent reason. 
As long as the deck is active, HDT has it but  afterwards it's nowhere to be found.
What can I do?

**Comment by Zawodowiec1532** [comment]
Maybe you have enabled option to auto archive your arena decks?
`Options -> General -> Auto archive deck after arena match`
