### ISSUE TITLE
Recent Matches not showing up

### ISSUE THREAD

**Issue by sauce-code** [HearthSim/Hearthstone-Deck-Tracker#3499]
### Expected Behavior
I played a few matches with my Dragon priest deck, they should show up in the matches / stats screen.

### Actual Behavior
only 1 of 7 matches showed up.

### Steps to reproduce behavior
Just play some games and check the recent matches screen. It happens more often.

### Log/Screenshots
![grafik](https://user-images.githubusercontent.com/9353871/33965647-fb8b6312-e05c-11e7-9d90-5d00ca10ba62.png)
this is the main problem.. only 1 match shows up..

![grafik](https://user-images.githubusercontent.com/9353871/33965693-2b2b2378-e05d-11e7-8708-0290b0aa5fc9.png)
Here is the "active deck only filter" on. Still missing 6 matches.

![grafik](https://user-images.githubusercontent.com/9353871/33965706-39952486-e05d-11e7-97cf-67b63063ca6b.png)

**Comment by riQQ** [comment]
You are filtering for `Coin: No`

**Comment by sauce-code** [comment]
JEEZ

**Comment by sauce-code** [comment]
Shame on me. Just delete this.

**Comment by sauce-code** [comment]
This literally drove me crazy.

**Comment by riQQ** [comment]
Should get better when #3248 is implemented
