### ISSUE TITLE
Deck Overlay Not Appearing

### ISSUE THREAD

**Issue by CrystalBearer** [HearthSim/Hearthstone-Deck-Tracker#3500]
### Issue:
The deck overlays for both Player and Opponent decks do not appear when "locked in". However, if you unlock the "Move/Resize Objects" option, they appear until re-locked in.

###Attempts to Resolve:
Appeared on a clean install.
Re-Installed HDT and reset all settings.
Issue appears in all game types.
Issue appears in Fullscreen and Windowed modes.

### Log/Screenshots

<img width="1080" alt="show" src="https://user-images.githubusercontent.com/34528670/33973181-59a6972c-e036-11e7-9cec-5d34c862ea0a.png">
<img width="1080" alt="no show" src="https://user-images.githubusercontent.com/34528670/33973182-59fe6f10-e036-11e7-866c-3ca4ad02d23d.png">

**Comment by CrystalBearer** [comment]
Note: The battery level still appears, but the rest of the overlay does not (as shown in the screenshots).

**Comment by riQQ** [comment]
You have `Hide decks` enabled

**Comment by CrystalBearer** [comment]
I am ashamed,
