### ISSUE TITLE
Cards revealed by Spiteful Summoner not showing up.

### ISSUE THREAD

**Issue by sauce-code** [HearthSim/Hearthstone-Deck-Tracker#3501]
### Expected Behavior

My opponent played a [Spiteful Summoner](http://media-hearth.cursecdn.com/avatars/356/458/76881.png). During its battlecry a [Meteor](https://d1u5p3l4wpay3k.cloudfront.net/hearthstone_gamepedia/7/71/Meteor%2855558%29.png) got revealed, summoning a [Scaled Nightmare](http://media-hearth.cursecdn.com/avatars/333/900/33152.png). So the Meteor should show up in the enemy deck list, greyed out. On the screenshot you can see that it worked for [Dragon's Fury](http://media-hearth.cursecdn.com/avatars/356/229/76963.png), revealed by a lost joust from [Raven Familiar](http://media-hearth.cursecdn.com/avatars/356/226/76885.png).

### Actual Behavior

The revealed Meteor didn't show up in the enemy deck list.

### Steps to reproduce behavior

Wasn't able to reproduce yet, since not many people play Spiteful Summoner and i don't have any friends.

### Log/Screenshots

![grafik](https://user-images.githubusercontent.com/9353871/33981957-1b490900-e0af-11e7-8e0e-77ddab19b812.png)
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1558426/hdt_log.txt)

**Comment by azeier** [comment]
Fixed with v1.5.10
