### ISSUE TITLE
Wrong Psychic Scream artwork

### ISSUE THREAD

**Issue by sauce-code** [HearthSim/Hearthstone-Deck-Tracker#3502]
### Expected Behavior

Playing versus priest. Priest palys Psychic scream.

### Actual Behavior

Psychic Scream uses wrong artwork. Instead of its own its using the Dragon's Fury artwork.

### Steps to reproduce behavior

Just play Psychic Scream.

### Log/Screenshots

![grafik](https://user-images.githubusercontent.com/9353871/33984250-38110328-e0b7-11e7-84ed-40bb53b1607f.png)

**Comment by riQQ** [comment]
See HearthSim/HearthstoneJSON#55

**Comment by riQQ** [comment]
Fixed in v1.5.11.
