### ISSUE TITLE
Dead man's hand issue

### ISSUE THREAD

**Issue by eonia89** [HearthSim/Hearthstone-Deck-Tracker#3509]
### Expected Behavior

When this card is used, deck tracker should correctly record what's put back into the deck.
### Actual Behavior

It used to recognise the created cards by dead man's hand, but it doesn't any longer.

**Comment by eonia89** [comment]
Oh, the notes today say the issue with this card has been fixed. So, I will give it a go!

**Comment by riQQ** [comment]
Duplicate of #3507
