### ISSUE TITLE
Importing complete data on a new pc

### ISSUE THREAD

**Issue by Atralb** [HearthSim/Hearthstone-Deck-Tracker#3517]
Hi there, just wanted to thank all people working on this project first, that is a real great job !

My issue is that i want to get all my existing data from my old computer back on a new one i just bought but i dont wanna mess things up so i'm asking here before trying. I know there are some (2?) existing threads dealing with this issue, but one is from 2015 and reading both threads anyway, i can't fully understand how to basically get the exact same data as in the old one. 

The solution with transfering the Appdata HDT folder isn't possible anymore and some talked about a portable build, but I really can't figure out how does this work. I mean, even if it is a "portable" version, i didnt install this version on my old computer so it won't be able to track my past data, right ?

So, i'm creating another thread to ask if anybody could explain to me more precisely how you can manage to recover hdt data on a new computer. Thanks very much

**Comment by riQQ** [comment]
Copying the folder `%appdata%\HearthstoneDeckTracker` should transfer all your settings and plugins. I don't know a reason why this shouldn't be possible anymore.

**Comment by Atralb** [comment]
Hi, thanks for the answer.

I gotta admit I didnt test on my end and trusted someone who said that in this thread, starting from the march 17, 2017 message : https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/2942 "This doesn't work anymore, since the AppData configs don't exist now. Any alternative?"

I assumed that the statement was true since people answering werent contesting it. Isn't it ?

Thanks

**Comment by riQQ** [comment]
Just try it, it most certainly works.

**Comment by Atralb** [comment]
It worked, thanks :)
