### ISSUE TITLE
Problems with deck stats

### ISSUE THREAD

**Issue by BigBaadBob** [HearthSim/Hearthstone-Deck-Tracker#3524]
Im using  HDT for quite a while now (on different devices) - its an amazing tool - thank your for that!

But i have an issue since a few days: 
 I want to see how im doing against different matchups but my deck stats are only showing the last games (maybe the last 24 hours?). I checked every option about 3-4 times and i dont know why this happens.
When i start a game it show the correct "in-game stats", like "Druid 3-2" or so - but not in the program itself so i cant get an overview about the matchups.

Any ideas beside reinstalling HDT- i would love not to loose all my stats.

**Comment by Zawodowiec1532** [comment]
Hey. :)

Maybe you have set some filters? On left side there is panel with that, there is filter named "Time".

**Comment by BigBaadBob** [comment]
Wow! Thats it! I searched for 2 hours total i think, tried everything out but totally overlooked this! 
Thx man! (bit embarassing though ;) )
