### ISSUE TITLE
Problem with portable version

### ISSUE THREAD

**Issue by Sevis** [HearthSim/Hearthstone-Deck-Tracker#3529]
Hello,

I use portable version on 2 computers. Some time ago it work fine.

I use folder on OneDrive to store program data.

But now if I run program on another computer on the first computer  statistic is disappear and I see the screen: "enter to play menu...".

I delete all files on onedrive folder with program data, but it not help.

How I can correct this problem? I need that program work on 2 computers...

**Comment by riQQ** [comment]
What did you changed before it stopped working?

**Comment by Sevis** [comment]
Nothing changed. Sometimes was problem with sinc and get message about 2 copy of files on data folders, one from one computers and 2 from another

**Comment by riQQ** [comment]
> But now if I run program on another computer on the first computer statistic is disappear and I see the screen: "enter to play menu...".

What do you mean by that? Can you post a screenshot?

**Comment by riQQ** [comment]
Are the files
- DeckStats.xml
- DefaultDeckStats.xml
- PlayerDecks.xml
- config.xml

in the folder of your `Hearthstone Deck Tracker.exe` or in the `%appdata%\HearthstoneDeckTracker` folder?

**Comment by Sevis** [comment]
I check folders... and my data in %appdata%\HearthstoneDeckTracker now.
I go to the otinons\settings click "SET DATA PATH" and choose folder on onedrive, but I no got  message about restart tracker and data folder not changed. why is it?

P.S.:
I'm download portable zip-archive from here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/tag/v1.5.11

**Comment by Sevis** [comment]
Thanks, for helping, I disable this options and tracker work correctly on both computers now.
