### ISSUE TITLE
Secret window size doesnt scale with anything

### ISSUE THREAD

**Issue by machomier** [HearthSim/Hearthstone-Deck-Tracker#3534]
## Bug report
Secret window doesnt resize in --> 
options - overlay - player - scaling OR options - overlay - opponent - scaling
The player overlay with all cards resizes with opponent size scale
Also on another topic i fount the answer bein this:
options (advanced) > overlay > opponent > secret scaling
However i can't find any advanced options or ''secret scaling''

### Expected Behavior
Resizing secret window with opponent size scale slider.

### Actual Behavior
The player overlay with all cards resizes with opponent size scale

### Steps to reproduce behavior
?

**Comment by riQQ** [comment]
![](https://user-images.githubusercontent.com/3404787/34854476-37fe7390-f73a-11e7-8e02-378705655429.png)
