### ISSUE TITLE
Enemy Card Tooltips BUG

### ISSUE THREAD

**Issue by AmberDrake** [HearthSim/Hearthstone-Deck-Tracker#3540]
## Bug report
Enemy card list is invisible but it's tooltips are still visible after hovering over the area they recently were.

### Log/Screenshots
![1](https://user-images.githubusercontent.com/26504748/34916712-f6424512-f955-11e7-98ee-8b5334f852b9.PNG)
![2](https://user-images.githubusercontent.com/26504748/34916714-f817eb4e-f955-11e7-9205-a219f6c54341.PNG)
![3](https://user-images.githubusercontent.com/26504748/34916715-f92da5dc-f955-11e7-9f6e-406df00316c4.PNG)

**Comment by Zawodowiec1532** [comment]
I can't reproduce this :/
Any exactly steps what to do?

**Comment by riQQ** [comment]
And please provide screenshots of your overlay options.
