### ISSUE TITLE
Add alert on friendly challenge

### ISSUE THREAD

**Issue by screamer19** [HearthSim/Hearthstone-Deck-Tracker#3541]
Greetings!

I'm surprised this is not already in the tracker, since the function is there for something else.

Hsdt can popup the hearthstone window/flash the program on the task bar if the user wants to be alerted when a match starts, or when their turn begins. If a user is issued a friendly challenge from someone on their friends list, would it not be possible to have a setting in notifications that allows them to be alerted in a similar way?

**Comment by Zawodowiec1532** [comment]
Options -> Tracker -> General -> Alerts

**Comment by screamer19** [comment]
bump :)

**Comment by Kylael** [comment]
Hey there.

I'm currently looking for a way to add a sound whenever I get challenged in HS. I was advised to ask for help there, and I step upon this thread when I was about to make a new one. Please I'm absolutely new to Github (and I have absolutely 0 experience in coding or dev in general for that matter), just notify me if I'm in the wrong place and where I can reach out for help.

Cheers !

**Comment by riQQ** [comment]
@Kylael please open a separate issue.
