### ISSUE TITLE
Deck Tracker crashes on startup

### ISSUE THREAD

**Issue by adania87** [HearthSim/Hearthstone-Deck-Tracker#3542]
Haven't played hearthstone in about a month, went to play and loaded up decktracker like usual except this time as soon as it loads it crashes with the windows error message "Hearthstone deck tracker has stopped working" 

I tried uninstalling it and reinstalling but it made no difference, i googled as best i could for a solution and i have .net 4.5 installed since i saw that mentioned around the place. 

Here is the log from the appdata folder:

3:10:34 PM|Info|Core.Initialize >> HDT: 1.5.11.3443, Operating System: Windows 10 Home 16299, .NET Framework: 461308
3:10:34 PM|Info|Updater.StartupUpdateCheck >> Checking for updates
3:10:34 PM|Info|Updater.GetReleaseUrl >> Downloading releases file
3:10:34 PM|Info|Updater.GetReleaseUrl >> using 'live' release: https://github.com/HearthSim/HDT-Releases
3:10:36 PM|Info|Updater.SquirrelUpdate >> Checking for updates (ignoreDelta=False)
3:10:37 PM|Info|Updater.SquirrelUpdate >> No new updated available
3:10:37 PM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
3:10:37 PM|Info|ThemeManager.LoadThemes >> Found theme: classic
3:10:37 PM|Info|ThemeManager.LoadThemes >> Found theme: dark
3:10:37 PM|Info|ThemeManager.LoadThemes >> Found theme: frost
3:10:37 PM|Info|ThemeManager.LoadThemes >> Found theme: minimal
3:10:37 PM|Info|GameV2.Reset >> -------- Reset ---------
3:10:37 PM|Info|HsReplayDecks.Load >> Loaded from disk: 
3:10:37 PM|Info|HsReplayDecks.Load >> Cached data was not found or stale. Fetching latest...
3:10:37 PM|Info|ApiWrapper.GetAvailableDecks >> Fetching available decks...
3:10:40 PM|Info|OverlayWindow.SetTopmost >> Hearthstone window not found
3:10:41 PM|Info|GameV2.Reset >> -------- Reset ---------
3:10:42 PM|Info|BackupManager.Run >> Running BackupManager
3:10:42 PM|Info|BackupManager.Run >> Backup for today already exists
3:10:42 PM|Info|PluginManager.LoadPluginsFromPath >> Loading Plugins...
3:10:42 PM|Info|LogWatcherManager.Start >> Using Hearthstone log directory 'C:\Program Files (x86)\Hearthstone\Logs'
3:10:42 PM|Info|ApiWrapper.UpdateAccountStatus >> Checking account status...
3:10:42 PM|Info|HsReplayDecks.Load >> Writing hsreplay_decks.cache to disk...
3:10:42 PM|Info|HsReplayDecks.Load >> Complete: Count=3199, ServerTS=1/17/2018 2:49:19 PM, Downloaded=1/17/2018 3:10:42 PM Age=00:00:00.0480083
3:10:42 PM|Info|ApiWrapper.UpdateAccountStatus >> Id=0, Username=, Status=Anonymous

Any help or ideas?

Thanks

**Comment by riQQ** [comment]
Please check the windows event logs and post the found entries here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#windows-log-files.
