### ISSUE TITLE
Stats not updating under deck names.

### ISSUE THREAD

**Issue by dlall915** [HearthSim/Hearthstone-Deck-Tracker#3543]
### Expected Behavior
Win-loss stats under deck names update after each match.

### Actual Behavior
Since updating to 1.5.11, the win-loss stats under deck names have not been updating unless I change decks. Though the updated stats do show up in other areas off the application as seen in the screenshot.

### Log/Screenshots
![2018-01-18 09_28_49-](https://user-images.githubusercontent.com/6889012/35102956-70a985de-fc32-11e7-9557-b544b06ef922.png)
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1643147/hdt_log.txt)

**Comment by Zawodowiec1532** [comment]
Are you sure it started in 1.5.11 update?

**Comment by riQQ** [comment]
I can confirm this behavior. I thought this bug has been around a long time.
