### ISSUE TITLE
HDT Tournament Mode

### ISSUE THREAD

**Issue by ruthnaebeck** [HearthSim/Hearthstone-Deck-Tracker#3552]
**Feature Request**
Create a way for HDT to track deck lists during tournaments and notify a player if their opponent played a card not on their submitted deck list.

Reference - https://twitter.com/ZalaeHS/status/957489279306891264

**Comment by CLJunge** [comment]
Sounds like a feature that should be implemented into a plugin.

**Comment by azeier** [comment]
Yep. Definitely not a HDT feature.

**Comment by chWolfgang** [comment]
Does anyone know if someone is developing a plug-in that does this? (Or something close?)
