### ISSUE TITLE
Question: How do change the install directory.

### ISSUE THREAD

**Issue by kiruaner** [HearthSim/Hearthstone-Deck-Tracker#3553]
## Bug report

Program always installs to C:\ probably because AppData is located there.

I already tried to download project from github, find some properties to change the install path, but I did neither find the file, nor an executable to start the program after fixing the path.
Is there a way to install to other directories ?

**Comment by azeier** [comment]
You can download the latest release as a portable version here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/latest

Download the "Hearthstone.Deck.Tracker-vX.X.X.zip" file under assets instead of clicking on the big fat link. You can just unzip that anywhere you like.

**Comment by kiruaner** [comment]
Amazing, thanks for quick reply, it is working
