### ISSUE TITLE
Migrations for separating dependency assemblies external to HSDT project

### ISSUE THREAD

**Issue by Latency** [HearthSim/Hearthstone-Deck-Tracker#3556]
## Request

  Migrate out HearthWatcher into its own repo like other dependency assemblies found within HSDT.
  Similar with Update & Uninstaller.  Tests reside with each associated project.

  Consider using my new build configurations and/or start packing dependency assemblies as NuGet packages w/ versioning **making build & release easier to maintain and bootstrap on initial deployment**.

  Requires explicit configuration within IDE to target package manager target URI @ GitHub\HearthSim\\<project>\?  for .nupkg's.

 Consider package locations consistent across all projects for reference.

 Willing to do the job if approved!

**Comment by azeier** [comment]
As I said in #3535, I've been working on moving all the non HDT specific logic (i.e. pretty much everything but the UI and decks/stats) into a separate project. That includes the watchers and the resource generator.
