### ISSUE TITLE
Words with national letters displayed with two fonts

### ISSUE THREAD

**Issue by ensisnoctis** [HearthSim/Hearthstone-Deck-Tracker#3558]
### Expected Behavior
Card names should be displayed with uniform font in desktop app and in-game hover.

### Actual Behavior
Some national/non-ASCII letters are displayed with a different, thin font. Myself having set card language to polish, I confirm the problem to happen with letters ąćęłńśźż (every polish national letter except ó).

### Steps to reproduce behavior
1. Select and copy this deck code:
```
### Font Party
AAEBAaIHFfIFigfaCvcMyQ/cD88V+asCqa8CoLcC+L0CuccCwMwCw84CzdMCi+ECnOICneICnuIC0OMCl+cCAAA=
```
2. Open Hearthstone Deck Tracker.
3. Go to Options > [Tracker] > General > [Card Language] > Primary and change to Polish.
4. Notice a setting below: "Use default font for non-latin languages". It does not have any effect on the problem.
5. Restart app.
6. Click IMPORT > FROM DECK CODE. Copied deck code from step 1 should now be recognised. Click Save only.
7. _Hover cursor_ on cards in the DECK column, look at their names.

The same issue with font exists while hovering cards in-game.

### Log/Screenshots
![HDT font issue](https://user-images.githubusercontent.com/19998579/35676105-d728996c-074a-11e8-9e32-8da59d899a83.png)

**Comment by azeier** [comment]
Looks like this might be an issue with the font not supporting bold for those letters? The card tiles look fine.

**Comment by ensisnoctis** [comment]
Indeed, the problem is found only in the card name area pointed by arrow (in app and in game). In every other place (like card list, card descriptions) letter are displayed correctly (like the ń on the above screenshot).

**Comment by ensisnoctis** [comment]
This fixed the app, but in-game the letters are still distinct.

**Comment by riQQ** [comment]
Are talking about the overlay? Can you provide a screenshot?

**Comment by ensisnoctis** [comment]
The overlay doesn't appear on the screenshots (both made by Hearthstone and GeForce Experience/NVidia Shadowplay), so instead I took some photos.
https://ibb.co/dChnwS
https://ibb.co/gWXWO7

**Comment by Zawodowiec1532** [comment]
Thanks for photos, you could always press "Print Screen", paste it to paint and save.
We are working on it. :)
