### ISSUE TITLE
Can't see any of my decks and its not taking new ones.

### ISSUE THREAD

**Issue by K3nm** [HearthSim/Hearthstone-Deck-Tracker#3567]
### Expected Behavior
Open HDT without any problem and like i usually did before.

### Actual Behavior
It open but it doesn't show anything is in blank and it didn't take my decks.

### Steps to reproduce behavior
Just oppening the HDT

### Log/Screenshots

Screenshots:

![image](https://user-images.githubusercontent.com/8028045/36128901-45d2587a-102a-11e8-8faa-f394a0af951d.png)

![image](https://user-images.githubusercontent.com/8028045/36128941-709538e8-102a-11e8-80e2-94ec898e316a.png)

Log:

[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1718274/hdt_log.txt)

**Comment by riQQ** [comment]
https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#no-stats
