### ISSUE TITLE
[BUG] Does not recognize DK Paladin as Paladin Class for stats [WILD]

### ISSUE THREAD

**Issue by jnpablodi** [HearthSim/Hearthstone-Deck-Tracker#3572]
### Expected Behavior
Matchup against player using DK Paladin should show as "VS Paladin" on stats

### Actual Behavior
Stats show class as "other", matches list is empty for both "Class" and "VS"

**Comment by riQQ** [comment]
Can you provide the hdt log file at the time this happened? (https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#hdt-log-files)

**Comment by riQQ** [comment]
Duplicate of #3398
