### ISSUE TITLE
Deck tracker switched roles between me and my opponent

### ISSUE THREAD

**Issue by wsfung** [HearthSim/Hearthstone-Deck-Tracker#3573]
## Bug report

I just had a game as dragon control priest against a spiteful druid. For some reason, after the loss, tracker recorded me winning as druid against priest.

**Comment by riQQ** [comment]
Could you provide the corresponding HDT log file, please: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#hdt-log-files.

**Comment by wsfung** [comment]
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1773942/hdt_log.txt)

Does this work? I dragged and dropped the file last time and it said uploading but didnt show up.

**Comment by riQQ** [comment]
And which of those games in the log was tracked incorrectly?

**Comment by wsfung** [comment]
There was one druid game on 26 feb. The deck I used was asmodai control priest. The opponent was saintshing, which is my battletag.

**Comment by riQQ** [comment]
Could you please post a screenshot of the stats window with game in question highlighted?
Was it the game started at 10:04:10 AM?

**Comment by wsfung** [comment]
![image](https://user-images.githubusercontent.com/1085499/36956843-a289ca92-1ffe-11e8-989b-023959b4ef96.png)

No, it started at 18:01 on 26 Feb.

**Comment by riQQ** [comment]
Could you upload a zip of the folder `%appdata%\HearthstoneDeckTracker\Logs` please? The log file you uploaded doesn't contain the game that was tracked incorrectly.

**Comment by riQQ** [comment]
![Overlays switched](https://user-images.githubusercontent.com/3404787/37112608-353d7640-2243-11e8-87d4-e305f05cfc67.png)

**Comment by wsfung** [comment]
Sorry for the late reply. Here is the log files. 

https://nofile.io/f/Gr4U38PJ8e7/Logs.7z

**Comment by riQQ** [comment]
```
6:01:44 PM|Info|GameEventHandler.HandleGameStart >> --- Game start ---
6:01:44 PM|Info|GameV2.Reset >> -------- Reset ---------
6:01:44 PM|Warning|Helper.GetRegionByServerIp >> Unknown IP: 24.105.24.65
6:01:44 PM|Info|TurnTimer.Start >> Starting turn timer
6:01:44 PM|Warning|TurnTimer.Start >> Turn timer is already running
6:01:44 PM|Info|TagChangeActions.SetHeroAsync >> Found hero with id=70
6:01:44 PM|Info|GameEventHandler.SetOpponentHero >> Opponent=Priest
6:01:44 PM|Info|TagChangeActions.SetHeroAsync >> Found hero with id=72
6:01:44 PM|Info|GameEventHandler.SetPlayerHero >> Player=Druid
6:01:45 PM|Info|GameV2.CacheMatchInfo >> saintshing vs Jorge
6:01:45 PM|Info|GameV2.CurrentMode >> GAMEPLAY
```

**Comment by riQQ** [comment]
Duplicate of 3145
