### ISSUE TITLE
Does not track some decks/game results

### ISSUE THREAD

**Issue by Moldavone** [HearthSim/Hearthstone-Deck-Tracker#3579]
## Bug report
Hello,

It happens sometimes that the HS Deck Tracker does not track the deck I'm using, and after the game ends no result is recorded, as if I didn't play that game. In the overlay I only see the cards that I have drawn (like I'm in spectator mode), and not the whole deck . It happened recently in arena, it has recorded the first win, but after that it just stopped recording same arena run games, so in the Deck Tracker that arena run remained at 1-0.

Any help is highly appreciated.

Regards,
Moldavone.

### Expected Behavior
Track my deck in the in-game overlay, and record the outcome of the game

### Actual Behavior

Does not track the deck, only the drawn cards are shown in the overlay. Game result is not recorded.

### Log/Screenshots

Please find attached the latest logs when this happened, together with the config file.
[config.xml.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1794138/config.xml.txt)
[hdt_log_1520526922.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1794135/hdt_log_1520526922.txt)
[hdt_log_1520524949.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1794167/hdt_log_1520524949.txt)
[hdt_log_1520525793.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1794168/hdt_log_1520525793.txt)
[hdt_log_1520525913.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1794169/hdt_log_1520525913.txt)

**Comment by riQQ** [comment]
From the logs it looks like you weren't using a deck, so the game wasn't assigned to the deck.

**Comment by Moldavone** [comment]
What do you mean I was not using a deck? I was playing arena, with the same deck as the first game that was recognized by the HDT.

**Comment by riQQ** [comment]
From the log `hdt_log_1520526922.txt` started at 5:18:37 PM, there is only one game in the log. The deck was definitely not "used" in HDT (= HDT was in no-deck mode):
```
5:26:37 PM|Info|GameEventHandler.HandleLoss >> --- Game was lost! ---
5:26:37 PM|Info|TurnTimer.Stop >> Stopping turn timer
5:26:37 PM|Info|GameEventHandler.HandleGameEnd >> Game ended...
5:26:37 PM|Info|GameEventHandler.HandleGameEnd >> Format: 
5:26:37 PM|Info|GameStats.GameEnd >> Current Game ended after 9 turns
5:26:37 PM|Info|GameEventHandler.HandleGameEnd >> Assigned current deck to default Warrior deck.
```

**Comment by Moldavone** [comment]
I'm no software expert, that's why I came to this forum. What I'm saying is that I was playing arena, nothing changed, HDT stopped recognizing my deck/game results after the first game.

**Comment by riQQ** [comment]
As per `hdt_log_1520524949.txt` you played a Brawl, where HDT switched to no-deck mode. You'll have to deactivate no-deck mode for HDT to automatically select the deck you're playing.

**Comment by Moldavone** [comment]
Thank you for your advice. As I'm new to HDT, how do I deactivate the no-deck mode?

**Comment by riQQ** [comment]
Blue = no-deck mode active. Click the button to deactivate it.

![no_deck_mode](https://user-images.githubusercontent.com/3404787/37256724-fcca2c80-255e-11e8-845b-1177adbba6aa.png)

**Comment by Moldavone** [comment]
Thanks a lot for the help.
