### ISSUE TITLE
Tracker Alerts no longer working

### ISSUE THREAD

**Issue by Disruptedzz** [HearthSim/Hearthstone-Deck-Tracker#3582]
^Title. 
actually one works, it pop ups and flashes when a game is starting, but never does anything after that.

[hdt_log_1520878804.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1804121/hdt_log_1520878804.txt)
[hdt_log_1520879558.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1804124/hdt_log_1520879558.txt)

**Comment by azeier** [comment]
Fixed with v1.5.13
