### ISSUE TITLE
Game Outcome not displaying / detected.

### ISSUE THREAD

**Issue by JanloDT** [HearthSim/Hearthstone-Deck-Tracker#3583]
Game outcome not displaying or counting in deck stats.
Shows outcome as None.

Tracking is enabled.

This occurred in Standard Rank play, 

![capture](https://user-images.githubusercontent.com/21181134/37307570-1138bab6-2644-11e8-83f0-74d64710178e.PNG)

All games were Victories.  

[hdt_log_1520884943.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1804416/hdt_log_1520884943.txt)

**Comment by zlajag** [comment]
Same here, tried reinstall, clear registry etc but it didn't help.

**Comment by Zeusisontheloose** [comment]
I have the same problem as well tried the same things

**Comment by InfernalDark** [comment]
Updating the tracker fixed it for me.

**Comment by azeier** [comment]
Fixed with v1.5.13
