### ISSUE TITLE
Game outcome not recording, opponent's cards not showing turn drawn/mulligan status

### ISSUE THREAD

**Issue by Mourn69** [HearthSim/Hearthstone-Deck-Tracker#3584]
## Bug report
My last several games have not properly recorded the game outcome (it is showing as "none" in the pie chart area.  In the list of matches it is also not showing the opponent.  Also, when my opponent mulligans cards, I do not see the "m" on the card and all cards drawn are showing turn 0 rather than the actual turn the card was drawn.

### Expected Behavior
Win/Loss properly recorded and displayed in the "My Games" area and the list of matches.

Opponent's cards properly showing the turn drawn and mulligan status.

### Actual Behavior
See above

### Steps to reproduce behavior
I can reproduce this by playing a ranked game.  I have tried two different decks.

### Log/Screenshots
[hdt_log_1520886635.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1804475/hdt_log_1520886635.txt)
[hdt_log_1520884970.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1804480/hdt_log_1520884970.txt)
[hdt_log_1520882675.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1804482/hdt_log_1520882675.txt)
[hdt_log_1520879040.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1804484/hdt_log_1520879040.txt)

**Comment by InfernalDark** [comment]
Update the tracker, fixed all issues for me.

**Comment by azeier** [comment]
Fixed with v1.5.13
