### ISSUE TITLE
HDT not tracking wins and losses

### ISSUE THREAD

**Issue by squire-indiana** [HearthSim/Hearthstone-Deck-Tracker#3585]
### Expected Behavior
HDT normally tracks the wins and loses of each deck.

### Actual Behavior
Since the last update (1.5.13), any games completed are marked as neither "win" nor "loss", but with "none" instead.

### Steps to reproduce behavior
It happens every time I complete a game since the last update.

### Log/Screenshots
![hdt](https://user-images.githubusercontent.com/37314810/37315064-4c162c24-2660-11e8-937f-8e45df763a0a.png)

**Comment by azeier** [comment]
Make sure you're on hearthstone 10.4.0 and try restarting both.

**Comment by squire-indiana** [comment]
Thank you for your prompt reply. Absolutely right, Hearthstone updated and everything is working right again.

**Comment by azeier** [comment]
Great :)
