### ISSUE TITLE
Auto Update doesn't word since v1.15.13

### ISSUE THREAD

**Issue by LegolasZ8** [HearthSim/Hearthstone-Deck-Tracker#3593]
Hi everybody,

if I try to use the auto upgrade functionality i do always get the the following notification.
_____________________________________________________________________________________________
Creating temp file directory
Downloading latest version... 0%
System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.Exception: Error download the file. ---> System.Net.WebException: Die Anfrage wurde abgebrochen: Es konnte kein geschützter SSL/TLS-Kanal erstellt werden..
   bei System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   bei System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   bei System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei HDTUpdate.Program.<Update>d__2.MoveNext()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei HDTUpdate.Program.<Update>d__2.MoveNext()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei HDTUpdate.Program.Main(String[] args)
---> (Interne Ausnahme #0) System.Exception: Error download the file. ---> System.Net.WebException: Die Anfrage wurde abgebrochen: Es konnte kein geschützter SSL/TLS-Kanal erstellt werden..
   bei System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   bei System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   bei System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei HDTUpdate.Program.<Update>d__2.MoveNext()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei HDTUpdate.Program.<Update>d__2.MoveNext()<---

There was an error downloading the latest update. Press any key to open the website for manual download.
_____________________________________________________________________________________________

Does someone knows how I can solve this issue? I do not want to update manually everytime :-D

Thank you very much and kind regards
LegolasZ8

**Comment by azeier** [comment]
See #3587.

This will be fixed with updates after 1.5.14
