### ISSUE TITLE
[Request] tracking dead deathrattle minions and murlocs

### ISSUE THREAD

**Issue by sauce-code** [HearthSim/Hearthstone-Deck-Tracker#3598]
Hi there!

I searched for a similar issue open but couldn't find one. It would be great to have a feature to count the number of deathrattle minions and murlocs which died this game.

When playing N'Zoth decks or anyfin decks its sometimes a bit confusing to count how many deathrattle minions died so far. In this case it would be awesome to have a counter to look at.

It should work the same way as the C'Thun, spell or jadegolem counter: 
![grafik](https://user-images.githubusercontent.com/9353871/37558788-cfcbedda-2a19-11e8-894a-72b06198d443.png)

So the auto option would simply search for a N'Zoth or Anyfin in your deck and if found, automatically show it the same way as the other counters. Of course the same for the enemy deck, so if your opponent plays N'Zoth or an Anyfin, the same counter should show off (N'Zoth counter for your opponent, murloc counter for both players since anyfin summons dead murlocs from both sides). Have in mind a deathrattle coutner for the oppenent makes sometimes sense even after he played his N'Zoth, since another one can be created by other sources.

Would be awesome to see that kind of feature in the future and thank your for putting all this effort into this application!

**Comment by azeier** [comment]
There's a plugin for that: https://github.com/RedHatter/Graveyard

**Comment by sauce-code** [comment]
my life just became better
