### ISSUE TITLE
 .

### ISSUE THREAD

**Issue by ZeKillPix** [HearthSim/Hearthstone-Deck-Tracker#3599]

**Comment by riQQ** [comment]
Apparently you didn't copy everything. Reinstalling should fix it.

**Comment by ZeKillPix** [comment]
i unistall HSDT and HS and i reinstall HS and HSDT and it's don't work

**Comment by riQQ** [comment]
Are you using the portable or the installer version?

**Comment by ZeKillPix** [comment]
installer

**Comment by riQQ** [comment]
Please post the content of the latest version subfolder in `%LOCALAPPDATA%\HearthstoneDeckTracker`.

**Comment by MaeveLaOuf** [comment]
@riQQ You should close this ticket no ?
