### ISSUE TITLE
Uneven permissions

### ISSUE THREAD

**Issue by Kroweer574** [HearthSim/Hearthstone-Deck-Tracker#3601]
## Bug report
It appears that Hearthstone and HDT have not the same permissions, but even if i run both of them, as administrator it keeps saying me this, and when i enter a game HDT is just not doing anything.

### Steps to reproduce behavior
Load HDT

### Log/Screenshots

![captur34543a](https://user-images.githubusercontent.com/37517052/37570793-8c431bd4-2af4-11e8-83b3-51bbfbf4520a.JPG)

**Comment by azeier** [comment]
See #2738
