### ISSUE TITLE
HDT cannot automatically update and doesn't recognize victory and losses

### ISSUE THREAD

**Issue by v-shvets** [HearthSim/Hearthstone-Deck-Tracker#3605]
## Bug report
It actually looks like two separate bugs but as they appeared at he same time I'll report them as one bug.

### Expected Behavior

Application is updated without problems and Win/Loss is correctly displayed

### Actual Behavior

As soon as I open HDT it reports me that there is a new version. When I'm trying to download it I got the following error:
System.AggregateException: One or more errors occurred. ---> System.Exception: Error download the file. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.

Moreover, after I downloaded installer for the latest version (1.5.14) and install it, message is still appearing each time I open HDT. And the version that is showed on the start up is 1.5.11.
Another issue is that for almost all tracked games I'm getting None status instead of Win or Loss

### Steps to reproduce behavior

It reproduces each time

### Log/Screenshots

![image](https://user-images.githubusercontent.com/8191718/37676873-da996b9c-2c81-11e8-9c9f-5a268f341967.png)
![image](https://user-images.githubusercontent.com/8191718/37676941-120793ce-2c82-11e8-9559-64e9bd2f4f87.png)

**Comment by azeier** [comment]
Make sure to actually run the version you downloaded. 

If you downloaded the installer it will have created a new shortcut on your desktop you need to use.

To update the portable build you need to download the "Hearthstone.Deck.Tracker-v1.5.14.zip" here https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases and overwrite all files in your installation directory.

**Comment by v-shvets** [comment]
Thanks, I've eventually also noticed that I have two different versions installed. 
But why cannot portable version update itself as it did before?

**Comment by ceceita** [comment]
it's not a real bug , it was caused by this https://githubengineering.com/crypto-removal-notice/ was a change by github to make connections more secure when downloading files and that blocked the updates from version < 1.15.13 to version > 1.15.14.
I think if you manualy update, next time you can use the autoupdater like in the past.

**Comment by azeier** [comment]
Exactly right. The 1.5.14 updater will work fine for the next update.
