### ISSUE TITLE
Trouble with arena helper

### ISSUE THREAD

**Issue by jjmisperfect** [HearthSim/Hearthstone-Deck-Tracker#3606]
![default](https://user-images.githubusercontent.com/37617498/37703623-fffba2ba-2cfe-11e8-96e4-0e340f422c14.png)
What is going on with this n\a on the value card?

**Comment by ceceita** [comment]
You have last version ? 0.8.8
https://github.com/rembound/Arena-Helper/releases
if you have last version i think you have to open the issue on plugin page
https://github.com/rembound/Arena-Helper/issues

**Comment by azeier** [comment]
As ceceita said. You should file an issue on the plugin repo.
