### ISSUE TITLE
UI elements wrongly placed on ultra wide screens

### ISSUE THREAD

**Issue by Braintelligence** [HearthSim/Hearthstone-Deck-Tracker#3613]
### Expected Behavior

Correct placement of deck tracker overlay ui elements within the main gaming monitor, which sports a resolution of 3440x1440 (UWQHD).

### Actual Behavior

Only the leftmost ui element (enemy played cards and so on) is correctly placed. The enemy card indicators that show which card was drawn on which turn is misplaced and also the rightmost ui element showing your deck cards is so far on the right, that it moved to my third monitor on the right.

### Steps to reproduce behavior

Use UWQHD monitor as gaming monitor, while also using another monitor on the right side of it (not sure if secondary monitor is necessary for this effect).

**Comment by riQQ** [comment]
Related to #3445

**Comment by Braintelligence** [comment]
More like a duplicate I guess. Sorry, I really tried to find a similar problem. But that ticket seems to not include the resolution or any other buzzword I tried...

**Comment by Braintelligence** [comment]
I can confirm: Setting DPI scaling from 125% back to 100% moves all the ui elements to where they should be.

Maybe it would be possible to create a checkbox in the deck tracker settings to move the ui elements to the left by those proportions?

I can't use that screen productively at 100% dpi scaling with that resolution.

**Comment by riQQ** [comment]
Have you tried https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3445#issuecomment-348691225

**Comment by riQQ** [comment]
The last part of the comment I was talking about / linked:
> Furthermore, turning on this compatibility option for the HDT executable ("override high DPI scaling behaviour") seems to force the issue and allow me to use mixed scaling (requires a restart of HDT to take effect)
> ![image](https://user-images.githubusercontent.com/97427/33515994-a829d586-d7cf-11e7-93d1-43bfb71750b3.png)

**Comment by Braintelligence** [comment]
@riQQ Works perfectly, thank you very much!
