### ISSUE TITLE
no scroll bars

### ISSUE THREAD

**Issue by sauce-code** [HearthSim/Hearthstone-Deck-Tracker#3615]
The scroll bars in options submenus are gone. Restarting HDT didn't change anything.

![grafik](https://user-images.githubusercontent.com/9353871/38221274-ed934260-36de-11e8-9281-6d85cc918e6b.png)

![grafik](https://user-images.githubusercontent.com/9353871/38221279-f46626ca-36de-11e8-9f03-11ece7380135.png)

![grafik](https://user-images.githubusercontent.com/9353871/38221282-fbd57ff0-36de-11e8-9dfc-bf3d82d06161.png)

Plz bring back. I miss them :'-(

**Comment by Zawodowiec1532** [comment]
@azeier https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/c6a802359fbf130a1d9ea81d4e4101f0a8295144#diff-7ed894ea4bf43b6c0380e2a5aaa261c1L49
