### ISSUE TITLE
hsreplay.net error cant update collecton

### ISSUE THREAD

**Issue by Marrarus** [HearthSim/Hearthstone-Deck-Tracker#3618]
### Expected Behavior

openng collecton should result n updatng the collecton for hsreplay.net
### Actual Behavior

the red error marker appeared showing 2 errors:
1: HSReplay.net error
2: could not update your collection. Please try agan later.

collection update stays saing last update 7 days ago(which was the first upload date)
### Steps to reproduce behavior

everytime i open collection the same error appears again. leaving the pack openng screen has the same result

**Comment by Marrarus** [comment]
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1872377/hdt_log.txt)
log file previous upload didnt worked properly

**Comment by judge2020** [comment]
Are you able to visit [hsreplay.net](https://hsreplay.net) through your browser? Is there a Cloudflare challenge/captcha page first?

**Comment by Marrarus** [comment]
no nothing like that. i can use it like normaly i dont have to do any capture or cliudflare and im default logged in.

**Comment by ryansv** [comment]
I get the same error, I've attached my log as well.

**Comment by azeier** [comment]
Logging out and back in under `options > hsreplay.net > my account` should fix this.

**Comment by Marrarus** [comment]
that worked yes
