### ISSUE TITLE
Calendar Picker for Custom dates starts on previous year

### ISSUE THREAD

**Issue by Drahkir** [HearthSim/Hearthstone-Deck-Tracker#3619]
### Expected Behavior
When I click the calendar picker to set a custom date I would expect it to default to the current month and year, instead it defaults to current month and last year.

### Log/Screenshots

![image](https://user-images.githubusercontent.com/245618/38361786-92e77cae-389c-11e8-954b-54b791fd2f57.png)

**Comment by azeier** [comment]
It defaults to 2018 for me. Is your machine time set to 2017 maybe?

**Comment by riQQ** [comment]
It defaults to 2018 for me, too.

**Comment by Drahkir** [comment]
I'm certain my machine time was correct because I only noticed this issue by comparing it with my machine time.

**Comment by ceceita** [comment]
shows 2018 for me , never used that function..

**Comment by Drahkir** [comment]
I've checked a couple times since then and it seems fine.  I'm not sure what happened that first time, but the bug has seen been unreprodudicible.  Feel free to close this issue.
