### ISSUE TITLE
No longer working/updating/connecting to HS

### ISSUE THREAD

**Issue by desctx** [HearthSim/Hearthstone-Deck-Tracker#3621]
Logged in one morning a few days ago and nothing worked. Checked paths, AV and reinstalled... no joy.

### Log/Screenshots
hdt_log.txt

8:40:34 AM|Info|Core.Initialize >> HDT: 1.6.0.3575, Operating System: Windows 10 Home 16299, .NET Framework: 461308
8:40:34 AM|Info|Updater.StartupUpdateCheck >> Checking for updates
8:40:34 AM|Info|Updater.GetReleaseUrl >> Downloading releases file
8:40:34 AM|Info|Updater.GetReleaseUrl >> using 'live' release: https://github.com/HearthSim/HDT-Releases
8:40:35 AM|Info|Updater.SquirrelUpdate >> Checking for updates (ignoreDelta=False)
8:40:35 AM|Info|Updater.SquirrelUpdate >> No new updated available
8:40:35 AM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
8:40:35 AM|Info|ThemeManager.LoadThemes >> Found theme: classic
8:40:35 AM|Info|ThemeManager.LoadThemes >> Found theme: dark
8:40:35 AM|Info|ThemeManager.LoadThemes >> Found theme: frost
8:40:35 AM|Info|ThemeManager.LoadThemes >> Found theme: minimal
8:40:35 AM|Info|GameV2.Reset >> -------- Reset ---------
8:40:37 AM|Info|OverlayWindow.SetTopmost >> Hearthstone window not found
8:40:38 AM|Info|GameV2.Reset >> -------- Reset ---------
8:40:38 AM|Info|BackupManager.Run >> Running BackupManager
8:40:38 AM|Info|BackupManager.Run >> Backup for today already exists
8:40:38 AM|Info|PluginManager.LoadPluginsFromPath >> Loading Plugins...
8:40:38 AM|Info|LogWatcherManager.Start >> Using Hearthstone log directory 'D:\Program Files (x86)\Battle.net\Hearthstone\Logs'
8:40:38 AM|Info|ApiWrapper.UpdateUploadTokenStatus >> Checking token status...
8:40:38 AM|Info|HsReplayDecks.Load >> Loaded from disk: Count=2656, ServerTS=4/7/2018 2:06:28 PM, Downloaded=4/7/2018 10:30:40 AM Age=22:09:58.1720222
8:40:38 AM|Info|HsReplayDecks.Load >> Complete: Count=2656, ServerTS=4/7/2018 2:06:28 PM, Downloaded=4/7/2018 10:30:40 AM Age=22:09:58.1730233
8:40:38 AM|Info|ApiWrapper.UpdateUploadTokenStatus >> Token is not claimed
8:40:53 AM|Info|Help.Hyperlink_RequestNavigate >> [Helper.TryOpenUrl] https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by desctx** [comment]
Really? nothing? After trying every troubleshooting solution for this issue (and any related) I could find on this "forum", I decided to POST my problem and get nothing but crickets. I realize my problem may be pretty generic but considering I am running a fully updated Windows 10 on a new machine and did NOTHING to cause this problem other than START MY MACHINE one morning I figured I MIGHT not be alone and MAYBE I could get SOME advice.. I guess not. This game, along with your plug-in are not worth this effort... good luck to you.

**Comment by jleclanche** [comment]
@desctx You're running a free tool, with free plugins that aren't maintained by the HDT developers, and reported a crash on a high traffic issue tracker. You're not entitled to anything you think you're entitled to and need to seriously check your attitude at the door.
