### ISSUE TITLE
Arena class options

### ISSUE THREAD

**Issue by SelaO** [HearthSim/Hearthstone-Deck-Tracker#3622]
I'm making a plugin and I want to know which classes are in the options when starting a new arena. I'm looking at https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/c505c4682d26a31c4e7f16cd1c88a685afe4d88a/HearthWatcher/ArenaWatcher.cs and I don't see any event for that. 

Is there such event or a way to get that info? 

Also, do plugins have internet access privilege? Will I be able to make rest calls?

**Comment by ceceita** [comment]
im not a code expert but i think you can try look here, i dont know if there are new ways to do it ..
https://github.com/rembound/Arena-Helper
http://rembound.com/projects/arena-helper
Arena-Helper is a plugin that supports plugins ..

**Comment by SelaO** [comment]
The problem is arena helper is very laggy, so I'd rather not have it as a dependency.

**Comment by ceceita** [comment]
im bad at code mb you can check how arena helper detects it using HearthMirror [ i see you posted there ]

**Comment by Zawodowiec1532** [comment]
https://github.com/rembound/Arena-Helper/blob/master/Plugin.cs#L1291
