### ISSUE TITLE
Cat Trick still in secrets tracker in Standard

### ISSUE THREAD

**Issue by ericrbg** [HearthSim/Hearthstone-Deck-Tracker#3628]
### Expected Behavior
Cat Trick not to appear as it's no longer in standard.

### Actual Behavior
Cat trick still appears.

### Steps to reproduce behavior
Play against a hunter with a secret up.

### Log/Screenshots
![image](https://user-images.githubusercontent.com/37984851/38710545-e38cfcca-3eb8-11e8-9b8f-4c56f5e13d95.png)

**Comment by azeier** [comment]
Are you on 1.6.2?
