### ISSUE TITLE
Dungeon tracker wrongfully tracking dungeon cards as presents

### ISSUE THREAD

**Issue by Nusirra** [HearthSim/Hearthstone-Deck-Tracker#3633]
## Bug report
Created a new fresh dungeon run. Then, the tracker begun to see the cards in hand as presents, aswell any card drawed.
Freshly reinstalled the tracker, same results. 
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1910063/hdt_log.txt)
![screenshot_69](https://user-images.githubusercontent.com/38371213/38765156-05f9de74-3f93-11e8-96e5-5a7ef4812522.png)

**Comment by NightKev** [comment]
An interesting thing I noticed is that when I used Tracking it correctly noted me drawing the card I picked (I don't think it noticed the two cards I didn't pick being removed from the deck, though I didn't pay close attention).

**Comment by azeier** [comment]
Fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/3658172744b84a8c7100b9467b5a59aaa4f2d26c

**Comment by azeier** [comment]
Should be fixed with v1.6.4.
