### ISSUE TITLE
Cards added to deck/hand by Shudderwock not tracked

### ISSUE THREAD

**Issue by ltybcs** [HearthSim/Hearthstone-Deck-Tracker#3634]
When Shudderwock play battle cry of Elise the Trailblazer, Un'Goro pack do not shown in Deck Tracker.

**Comment by azeier** [comment]
Implemented with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/277392dc00098e8af22b42c4015a38c5584d37be

**Comment by azeier** [comment]
Should be fixed with v1.6.4.
