### ISSUE TITLE
A reference to the "....exe" could not be added.Please make sure that the file is accessible and that it is a valid assembly or COM component.

### ISSUE THREAD

**Issue by SelaO** [HearthSim/Hearthstone-Deck-Tracker#3635]
I'm trying to follow the instructions here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Basic-plugin-creation-tutorial

But I'm getting: 

![image](https://user-images.githubusercontent.com/21977571/38766924-ddea56b2-3fe1-11e8-937d-87ba46e04ba1.png)

I tried to follow some similar questions on SO, like this: https://stackoverflow.com/questions/3456758/a-reference-to-the-dll-could-not-be-added or to register the dll/exe(?) but they don't work.

So how can I reference HDT?

**Comment by riQQ** [comment]
You need to reference the exe file in an app folder: `%LOCALAPPDATA%\HearthstoneDeckTracker\app-1.6.3\HearthstoneDeckTracker.exe`, the one you're trying to reference is just a C++ Starter / Updater exe generated by Squirrel.
