### ISSUE TITLE
Could not update your collection. Please try again later.

### ISSUE THREAD

**Issue by anonymous555** [HearthSim/Hearthstone-Deck-Tracker#3636]
## Bug report
Everything was working fine until the last release.  Now I always get

Could not update your collection. Please try again later.

Replays still get uploaded properly.  Just the collection does not update.

### Expected Behavior

update collections
### Actual Behavior

Can't update collection
### Steps to reproduce behavior

Every time
### Log/Screenshots

None needed.

**Comment by riQQ** [comment]
Try logging out and back in again in the options.

**Comment by anonymous555** [comment]
Its fixed now please close.  Happened without needed to relog.

**Comment by azeier** [comment]
We had and fixed a server side issue that was causing this.
