### ISSUE TITLE
Far Sight causes drawn card to not be tracked

### ISSUE THREAD

**Issue by poopynuke** [HearthSim/Hearthstone-Deck-Tracker#3637]
when playing as shaman drawing a card with far sight doesn't update deck tracker it still thinks its in the deck

**Comment by azeier** [comment]
Fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/93cab94bad43a730be468c50b9eab66632457469.

This is a bug in Hearthstone.

**Comment by anikun2k10** [comment]
id like to add, which ive noticed is missing from original post, is the card that is drawn is being considered as if it were one that was randomly given vs drawn from the deck as it pops up on the deck tracker with the gift box icon

**Comment by azeier** [comment]
Should be fixed with v1.6.4.
