### ISSUE TITLE
Deck tracker no longer functioning correctly after installing the latest patch.

### ISSUE THREAD

**Issue by Keazra** [HearthSim/Hearthstone-Deck-Tracker#3639]
## Bug report
The deck tracker seems to be broken as of the most recent patch.

### Expected Behavior
Deck tracker to track my deck as cards are drawn.

### Actual Behavior
Deck tracker doesn't remove cards as they're drawn. When cards are shuffled back to the deck (i.e. after mulligan), they get added to the list of cards in my deck.

Happens in the Dungeon Run mode; haven't tested other modes so far.

### Steps to reproduce behavior
This happened after I went to the latest version of HDT.

**Comment by judge2020** [comment]
Please include a log file with your report: [instructions](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues).

**Comment by riQQ** [comment]
Same as #3633?

**Comment by Keazra** [comment]
Apologies, here are the two most recent logs (and a snapshot of the issue occurring). In the picture, you can see that the deck tracker is showing an additional copy of Holy Light as being in the deck. Things get even crazier looking when you do any kind of deck manipulation.

![49f2a4d073927d4333b414bfa90a0ab3](https://user-images.githubusercontent.com/38389279/38784266-e9321678-40e9-11e8-9db7-1bb215fb6931.jpg)

[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1913471/hdt_log.txt)
[hdt_log_1523832069.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1913472/hdt_log_1523832069.txt)

@riQQ This is the same issue, I believe, but it doesn't seem to be fixed for me yet. Granted, I'm not sure if the change was pushed out to the release version yet!

**Comment by riQQ** [comment]
The fix hasn't been released yet.

**Comment by Keazra** [comment]
Noted!
