### ISSUE TITLE
The card "hand of salvation" in last rotation.

### ISSUE THREAD

**Issue by zhufengtom** [HearthSim/Hearthstone-Deck-Tracker#3643]
The "Arena only" card of  Paladin, "hand of salvation" is in last rotation.

**Comment by zhufengtom** [comment]
"Arena only" card.

**Comment by zhufengtom** [comment]
The Paladin opponent played a secret in Arena，HDT say the secret may be  "hand of salvation". But the "Arena only" card of Paladin, "hand of salvation" is not exsit now.

**Comment by beheh** [comment]
I don't think this is relevant anymore, we use a new system where we can update the active arena sets on the server side and those BlizzCon secrets have rotated.
