### ISSUE TITLE
Variance in Games Played in HSTracker vs HSReplay.net

### ISSUE THREAD

**Issue by GETNIT** [HearthSim/Hearthstone-Deck-Tracker#3649]
My goal is to get an accurate view of my deck stats on HSReplay.net. However, the number of games played listed in my HSTracker (19) is not the same as what's showing in www.hsreplay.net (<5). It indicates that I've played less than 5 games, even though it's clearly more in the tracker. I've included screenshots that will clearly show it's the same deck, and it appears as though the filters are not causing this. Any guidance is greatly appreciated.

![odd paladin hsreplay net](https://user-images.githubusercontent.com/38505695/38948433-73563792-42f4-11e8-8a54-c5a7b87c1551.jpg)
![odd palidan hstracker](https://user-images.githubusercontent.com/38505695/38948436-7701bd6c-42f4-11e8-8780-cefa438c6b2e.jpg)
![odd paladin hsreplay net deckversion](https://user-images.githubusercontent.com/38505695/38948562-cfb8d5ee-42f4-11e8-85ed-6964f1061209.jpg)

**Comment by jleclanche** [comment]
Hey there,
This isn't really the spot to report this, an easier way is to contact us at contact@hsreplay.net.
I've had this issue happen to myself before however and it's (usually) related to HDT not correctly auto-detecting the current deck. You could check your latest replays, see if the full deck is available on the right of the replay. If that's the issue, the fix it to ensure the deck has been imported correctly into HDT.

I believe @azeier is working on improving deck autodetection. If that's the issue it should get better in the future.
