### ISSUE TITLE
Please add to the assembly for x64

### ISSUE THREAD

**Issue by Drui7** [HearthSim/Hearthstone-Deck-Tracker#3650]
![default](https://user-images.githubusercontent.com/3121957/38953724-1315c562-4369-11e8-9f28-7344ab05cd98.png)
this simple setup and the application is assembled for x64.
Note, in the Task Manager, "Microsoft Visual Studio" has in the brackets a record of "32 bits", and HDT does not have this record, since the application for x64
![default](https://user-images.githubusercontent.com/3121957/38953853-789a5c36-4369-11e8-8db9-e2b38f43df2e.png)
I ask to add an executable file for x64 in .zip together with the executable file for x86 by the link:
https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases

**Comment by azeier** [comment]
Hearthstone is a 32bit process and you can not access that from a 64bit one.
