### ISSUE TITLE
HDT won't save previous session stats!

### ISSUE THREAD

**Issue by kckc45kch** [HearthSim/Hearthstone-Deck-Tracker#3652]
[hdt_log_1524094978.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1926125/hdt_log_1524094978.txt)

So here's the problem.
My HDT can't save stats from my previous session. It only saves the stats from the current session and decks from a very long time ago. Everytime I restart HDT, the stats always shows only the decks from that 'long time ago'. It never saves my previous session and these 'long time ago' decks always appeared although I've already delete it.

**Comment by riQQ** [comment]
`System.UnauthorizedAccessException: Access to the path 'C:\Users\Kevin\AppData\Roaming\HearthstoneDeckTracker\hsreplay_decks.cache' is denied.`

HDT can't access anything under the path `C:\Users\Kevin\AppData\Roaming\HearthstoneDeckTracker`. Check your permissions for this path.

**Comment by riQQ** [comment]
https://www.google.com/search?q=windows+edit+permissions

**Comment by kckc45kch** [comment]
I've already allow them all without changing it.

**Comment by riQQ** [comment]
Almost certainly you made a mistake somewhere.
Alternatively you can try running HDT as admin.
