### ISSUE TITLE
Direhorn Hatchling isn't tracking

### ISSUE THREAD

**Issue by KenReels** [HearthSim/Hearthstone-Deck-Tracker#3655]
I've seen this happen both on streams and to myself on multiple occasions Direhorn Hatchling doesn't properly track. Pictured is a victory screen where I have no cards in my deck but the tracker still says I have two Hatchlings.
![decktrackerdirehornproof](https://user-images.githubusercontent.com/17842799/39090308-bcb1b0f8-45a9-11e8-90d0-f8b636b413a5.jpg)

**Comment by riQQ** [comment]
Duplicate of #3644
