### ISSUE TITLE
HDT won't start/insta-crashes on execution.

### ISSUE THREAD

**Issue by xBetterDays** [HearthSim/Hearthstone-Deck-Tracker#3662]
windows 7 64-bit (dunno if this matters so, there.)
If I make any mistakes with the proper format for asking help, I'm sorry, this is the first time I ask help here as this is also the first HDT does this.

Deck tracker was alright a few days ago, I was gonna play then suddenly it crashes.

I've tried uninstall/reinstall but doesn't seem to help, downloaded .net frameworks, didn't do anything as well.

Here's what the crash says:
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	HearthstoneDeckTracker.exe
  Application Version:	1.6.4.3608
  Application Timestamp:	5ad5381b
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.23677
  Fault Module Timestamp:	589c9620
  Exception Code:	c06d007e
  Exception Offset:	0000c54f
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789
```

**Comment by riQQ** [comment]
Is there a corresponding error with the source `.NET Runtime`?

**Comment by xBetterDays** [comment]
Hey sorry it took some time to reply, i tried the sfc /scannow and .net repair tool, nothing seems to be corrupted/

**Comment by riQQ** [comment]
You still haven't answered this:
> Is there a corresponding error with the source .NET Runtime?

**Comment by xBetterDays** [comment]
Ohhh sorry I thought I answered it with ".net repair tool", uhmm I'm not sure how to check errors in the source .Net runtime...

**Comment by riQQ** [comment]
I was probably not clear enough. In the windows event viewer there's the column `Source`. I want to know if there is another error next to the error you posted, that has the source `.NET Runtime`.

**Comment by xBetterDays** [comment]
Since it was quite a while since the first error and was pretty hard to find that specific one, I just launched the HDT again, error popped up and then i went to the event viewer, not sure if this is what you're exactly looking for though.

![capture](https://user-images.githubusercontent.com/38785643/40046190-e3f4318c-585e-11e8-8783-ae507ebc77fe.PNG)

**Comment by riQQ** [comment]
Does it crash if you run Windows in safe mode?

**Comment by riQQ** [comment]
It's most likely a driver or another program causing this problem. Did you update or install a new software just before this happened? You can check the list of other programs causing issues: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#other-programs

**Comment by xBetterDays** [comment]
Now that you've mentioned updating or installing a software, I think it might had something to do with the video card driver. during that time I've updated my video card driver only for it to crash mid-installation (often what happens to me and some people I know when they update via GeForce experience instead of manual installation). this caused my PC to have problems, it wasn't reading the video card after the crash, had to system recovery then manually uninstall-reinstall the working driver version. After that HDT won't start, but recently I was able to install the latest driver (3 updates after), was hoping HDT would work after that, but still didn't.

**Comment by riQQ** [comment]
Turn on Windows Error Reporting: Create this registry key `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps`, start HDT, and upload the crash dump from `%LocalAppData%\CrashDumps`.
By deleting the registry key, crash dump creation is turned off again.

**Comment by xBetterDays** [comment]
I can't seem to be able to upload the file here since it uses a ".dmp" extension and the instruction is quite unclear... I found the registry folder of `LocalDumps` but unsure where to make a registry key here.

**Comment by riQQ** [comment]
Use some one-click-hoster like zippyshare to upload one of those dump files.

**Comment by xBetterDays** [comment]
[Here's](https://www91.zippyshare.com/v/yOYfbPPO/file.html) the most recent .dmp file.

**Comment by riQQ** [comment]
Same stack trace as in https://superuser.com/questions/1320142/net-crash-wpfgfx-v0400-dll-dmp-included. Try installing https://support.microsoft.com/en-us/help/4019990/update-for-the-d3dcompiler-47-dll-component-on-windows

```
0899de88 61c42442 c06d007e 00000000 00000001 KERNELBASE!RaiseException+0x58
0899dee4 61c090e4 61cec688 61cf8000 0899df9c wpfgfx_v0400!__delayLoadHelper2+0x16c
0899df5c 61c04aac 0899dfec 0899dfe0 068737e8 wpfgfx_v0400!_tailMerge_D3DCOMPILER_47_dll+0xd
0899e020 61c04faf 05c3cb08 00000984 0899e044 wpfgfx_v0400!CD3DDeviceLevel1::CompilePipelineVertexShader+0xb4
0899e050 61c05051 0899e44c 00000002 0899e07c wpfgfx_v0400!CHwSurfaceRenderTargetSharedData::DerivePipelineShader+0x4d
0899e080 61bf9b09 0899e44c 00000002 0899e4f4 wpfgfx_v0400!CHwShaderCache::GetHwShader+0x5a
0899e098 61bf989d 0899e4f4 f56879f6 0899e5bc wpfgfx_v0400!CHwShaderPipelineBuilder::GetHwShader+0x1e
0899e114 61bf96e1 00000000 0899e5bc 05c35024 wpfgfx_v0400!CHwShaderPipeline::InitializeForRendering+0xd7
0899e510 61bf9742 00000000 0899e5bc 05c35020 wpfgfx_v0400!CHwSurfaceRenderTarget::ShaderAcceleratedFillPath+0x78
0899e538 61bfdab6 00000000 0899e5bc 05c35020 wpfgfx_v0400!CHwSurfaceRenderTarget::AcceleratedFillPath+0x1e
0899e890 61bfdc54 066ecd4c 07f80c40 066eced0 wpfgfx_v0400!CHwSurfaceRenderTarget::FillPathWithBrush+0x328
0899e9f8 61bfddec 066ecd4c 066ecfb8 07f80c40 wpfgfx_v0400!CHwSurfaceRenderTarget::FillPath+0x18e
0899ea84 61bfde85 066ecd4c 066eced0 066ecfb8 wpfgfx_v0400!CHwSurfaceRenderTarget::DrawPathInternal+0x151
0899eaa8 61bf5c75 06924ca8 066ecd4c 066ecfb8 wpfgfx_v0400!CHwSurfaceRenderTarget::DrawPath+0x25
0899eacc 61bdca8c 06924ca8 066ecd4c 066ecfb8 wpfgfx_v0400!CHwTextureRenderTarget::DrawPath+0x25
0899eb08 61bdf1c3 00000001 07f80c40 0899eb38 wpfgfx_v0400!CDrawingContext::FillOrStrokeShape+0xa5
0899eb94 61bdfddb 07f80c40 05b7ac78 00000000 wpfgfx_v0400!CDrawingContext::DrawShape+0x130
0899ebbc 61bdfe33 05b7ac78 00000000 07f80c28 wpfgfx_v0400!CDrawingContext::DrawGeometry+0x81
0899ec74 61bd5b9b 066eccb8 0666f9b0 61bd5b50 wpfgfx_v0400!CMilSlaveRenderData::Draw+0x37b
0899ec94 61bd5b0e 066eccb8 0666f9b0 61bd5950 wpfgfx_v0400!CMilVisual::RenderContent+0x3c
0899ed54 61bd5908 0899ed6c 066eccb8 00000000 wpfgfx_v0400!CDrawingContext::PreSubgraph+0x799
0899ed80 61bd8e7c 0666fae0 066eccd0 06a337b0 wpfgfx_v0400!CGraphIterator::Walk+0x4e
0899edc8 61c9d3db 0666fae0 0899edf4 0899ee48 wpfgfx_v0400!CDrawingContext::DrawVisualTree+0x166
0899ee08 61bf2deb 05b6f240 0899ee48 066eccb8 wpfgfx_v0400!CMilVisualBrushDuce::DrawIntoBaseTile+0x7b
0899ee5c 61bf344d 0899efe8 0899f028 0899ef98 wpfgfx_v0400!CTileBrushUtils::GetIntermediateBaseTile+0x103
0899f0c4 61bd47d7 05b6f240 06a337c8 05badf38 wpfgfx_v0400!CMilTileBrushDuce::GetBrushRealizationInternal+0x488
0899f0e4 61bd7a44 05b6f240 0899f104 00000000 wpfgfx_v0400!CMilBrushDuce::GetBrushRealizationNoRef+0x41
0899f108 61bfdd99 00000001 00000000 05b6f240 wpfgfx_v0400!CBrushResourceRealizer::EnsureRealization+0x74
0899f18c 61bfde85 05b6efd4 05b6f158 05b6f240 wpfgfx_v0400!CHwSurfaceRenderTarget::DrawPathInternal+0xf2
0899f1b0 61bfdeb9 0a5ca4c0 05b6efd4 05b6f240 wpfgfx_v0400!CHwSurfaceRenderTarget::DrawPath+0x25
0899f1d8 61bdcbcf 0a5ca4c0 05b6efd4 05b6f240 wpfgfx_v0400!CHwDisplayRenderTarget::DrawPath+0x29
0899f2a8 61bdca8c 082113f0 05b6efd4 05b6f240 wpfgfx_v0400!CMetaRenderTarget::DrawPath+0x10a
0899f2e4 61bdf1c3 00000001 0899f3b8 0899f314 wpfgfx_v0400!CDrawingContext::FillOrStrokeShape+0xa5
0899f370 61bdf874 0899f3b8 06a337b0 00000000 wpfgfx_v0400!CDrawingContext::DrawShape+0x130
0899f550 61bdf905 066e76b0 0899f5f8 0899f5a8 wpfgfx_v0400!CDrawingContext::DrawRoundedRectangle+0x157
0899f61c 61bd5b9b 05b6ef40 0666fb78 61bd5b50 wpfgfx_v0400!CMilSlaveRenderData::Draw+0x215
0899f63c 61bd5b0e 05b6ef40 0666fb78 61bd5950 wpfgfx_v0400!CMilVisual::RenderContent+0x3c
0899f6fc 61bd5908 0899f714 05b6ef40 00000000 wpfgfx_v0400!CDrawingContext::PreSubgraph+0x799
0899f728 61bd8e7c 068462c0 05b6ef58 05b6ef40 wpfgfx_v0400!CGraphIterator::Walk+0x4e
0899f770 61c0d9f5 068462c0 067a5b1c 0899f86c wpfgfx_v0400!CDrawingContext::DrawVisualTree+0x166
0899f814 61bd9770 068462c0 0821140c 067a5b1c wpfgfx_v0400!CDrawingContext::Render+0x2f4
0899f884 61bd9848 0899f8ab 068e5908 0899f94b wpfgfx_v0400!CSlaveHWndRenderTarget::Render+0x1db
0899f8ac 61bd3b22 0899f94b 068e5908 00000000 wpfgfx_v0400!CRenderTargetManager::Render+0x40
0899f8c4 61bd3977 0899f94b 068e5910 61bd39e0 wpfgfx_v0400!CComposition::Render+0x1f
0899f930 61bd3a23 0899f94b 068e5910 61bd39e0 wpfgfx_v0400!CComposition::ProcessComposition+0x173
0899f94c 61bd3a6b 0899f967 00000001 06729f30 wpfgfx_v0400!CComposition::Compose+0x3f
0899f968 61bd366f 068e5910 06729f30 61bd3640 wpfgfx_v0400!CPartitionThread::RenderPartition+0x25
0899f980 61c1096f f56860f6 00000000 00000000 wpfgfx_v0400!CPartitionThread::Run+0x4e
0899f9a8 7650336a 06729f30 0899f9f4 77529902 wpfgfx_v0400!CPartitionThread::ThreadMain+0x2f
0899f9b4 77529902 06729f30 7fc7ba38 00000000 kernel32!BaseThreadInitThunk+0xe
0899f9f4 775298d5 61c10940 06729f30 00000000 ntdll!__RtlUserThreadStart+0x70
0899fa0c 00000000 61c10940 06729f30 00000000 ntdll!_RtlUserThreadStart+0x1b
```

**Comment by xBetterDays** [comment]
I don't know why but it works now after I've uninstalled the latest .net framework I had (4.7.2) and installed the 4.5.2 you advised. Still confused as to why this is, since shouldn't it also work with the latest (4.7.2)?

anyway I appreciate everything you've done for me, thanks for the help! cheers!

![capture](https://user-images.githubusercontent.com/38785643/40276213-b11cb8ac-5c36-11e8-9187-e4734d8bc7bf.PNG)

**Comment by riQQ** [comment]
> Still confused as to why this is, since shouldn't it also work with the latest (4.7.2)?

Yes, it should. But i don't know a fix for this. It's definitely a .NET Framework issue.

I'm closing this as you're fine with the workaround.

**Comment by nebcanuck** [comment]
As of this week, Hearthstone Deck Tracker won't work without .net 4.7 or higher, and once installed HDT crashes on startup. Is there any newer workaround for this?

**Comment by riQQ** [comment]
Please post a separate issue with logs. See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues (sections `HDT crash logs` and `Windows log files`)

**Comment by nebcanuck** [comment]
> Please post a separate issue with logs. See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues (sections `HDT crash logs` and `Windows log files`)

Will do!

-Ben
