### ISSUE TITLE
When HDT gets App Update it forgets it has a shortcut in taskbar.

### ISSUE THREAD

**Issue by SOLiNARY** [HearthSim/Hearthstone-Deck-Tracker#3666]
When you pin HDT to taskbar in Windows 10, and launch it from there, App can be accessed by clicking that shortcut.
But if HDT gets updated & you launch it from taskbar with old shortcut, it shows HDT as new app & shows it in different temporary shortcut & clutters space in taskbar.
With every update it gets annoying to unpin old one & repin new shortcut.

### Expected Behavior
When launching updated app, HDT must be accessed via old pinned shortcut.

### Actual Behavior
When launching updated app, HDT is shown in different pinned shortcut (not the one you clicked).

### Steps to reproduce behavior
Pin the HDT to taskbar, wait for app to be updated, launch shortcut from taskbar.

**Comment by ceceita** [comment]
https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3632

**Comment by riQQ** [comment]
This has to be investigated further as Squirrel should support this:
https://github.com/Squirrel/Squirrel.Windows/blob/b25c9fa1e4d60f8969137532a95bd53bb5a8de1f/src/Squirrel/UpdateManager.ApplyReleases.cs#L418

**Comment by riQQ** [comment]
Adding this code at the start of HDT should fix the problem according to the linked issue.

```cs
[DllImport("shell32.dll", SetLastError = true)]
static extern void SetCurrentProcessExplicitAppUserModelID([MarshalAs(UnmanagedType.LPWStr)] string AppID);

SetCurrentProcessExplicitAppUserModelID("com.squirrel.PackageName.ExeName");
```

**Comment by ScottAllen11** [comment]
Over a year of this annoying issue, any chance we can we fix it soon? I've also complained to Twitch. Their app does the same thing.

**Comment by riQQ** [comment]
Manually unpinning and pinning again once after the update to v1.9.1 (when it's released) is necessary to fix this for existing pins.
