### ISSUE TITLE
Allow hiding HSReplay.net collection syncing banner

### ISSUE THREAD

**Issue by kimsey0** [HearthSim/Hearthstone-Deck-Tracker#3667]
Hearthstone Deck Tracker currently includes a banner advertising HSReplay.net collection syncing. However, unlike other banners in the app, there doesn't seem to be a way to hide this one. It keeps taking up space that would otherwise have been used for the deck list, even after you have set up and are actively using collection syncing. There is no checkbox to hide the banner in the settings menu, and I haven't been able to get the `HideCollectionSyncingBanner` configuration item (in `config.xml`) working.

Hearthstone Deck Tracker should include an easy way to hide the banner, preferably a small cross in the upper right corner of the banner or alternatively a checkbox in the settings menu.

![collectionsyncingbanner](https://user-images.githubusercontent.com/984760/39583561-ab1b2342-4ef0-11e8-9260-14b05b11123b.PNG)

**Comment by azeier** [comment]
We might revisit that in the future but it's gonna stay persistent for the time being.

**Comment by kimsey0** [comment]
@azeier: Can you explain the reasoning for that? I understand that you need to refer people to HSReplay.net to sell subscriptions, but once people have signed up and use HSReplay.net, the banner only worsens the user experience for Hearthstone Deck Tracker by making it possible to see fewer decks in the deck list.
