### ISSUE TITLE
the tracker crashes every time I start a game

### ISSUE THREAD

**Issue by Oby953** [HearthSim/Hearthstone-Deck-Tracker#3669]
## Bug report
While in the main menu the tracker works just fine but as soon as i start the game it shuts down with no message whatsoever. If i try to restart it, it won't work.
This happens always since the 1.6.3 update

### Log/Screenshots

[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1976506/hdt_log.txt)

**Comment by riQQ** [comment]
Please provide crash logs. See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues (sections `HDT crash logs` and `Windows log files`)

**Comment by Oby953** [comment]
There was no crash log. I uninstalled the programme, deleted the folder and
reinstalled it and it seems to have worked
