### ISSUE TITLE
Standard deck got classified as brawl deck after Brawliseum

### ISSUE THREAD

**Issue by t-giese** [HearthSim/Hearthstone-Deck-Tracker#3671]
After playing the current Tavern Brawl, the list I use in standard (which was the same as I used in the brawl) got classified as a brawl deck. It is very unclear to me how I can revert this. If there is no way to revert this, there definitely should be one and if there is a way, it has to be much more clear how to do it.

Thanks in advance.

**Comment by azeier** [comment]
You should be able to just rightclick the deck and remove the brawl tag under "quick set tag"

**Comment by t-giese** [comment]
Thanks for the answer, I of course looked there and thought I could do
that, but there is actually no possibility to remove the tag directly. What
works on the other hand is giving it a favorite tag and removing that tag
again. That way the brawl tag gets removed. But that's basically exactly
what I'm saying, that is nowhere near intuitive and should be changed.

Alex Zeier <notifications@github.com> schrieb am So., 6. Mai 2018, 20:18:

**Comment by azeier** [comment]
This behavior should be fixed with the next release. Decks will not be tagged as brawl if they have any non-brawl games.
