### ISSUE TITLE
Hearthstone Deck Tracker not opening whatsoever

### ISSUE THREAD

**Issue by RMXdotEXE** [HearthSim/Hearthstone-Deck-Tracker#3672]
Essentially, the problem here is that HDT was working a couple of days ago, but all of a sudden does not work anymore. My Event Viewer doesn't even log me trying to open HDT.

I can't really reproduce it; it kind of just happened. I'm sure I didn't do anything to change the behavior of HDT intentionally.

No logs are even created in %appdata%\HearthstoneDeckTracker\Logs. My last log was on 4/28, the last day that my HDT stopped working.

I went through the FAQ several times and have spent hours troubleshooting but nothing has worked.

Will provide files upon request.

**Comment by riQQ** [comment]
Do you see the process starting in the task manager?

**Comment by RMXdotEXE** [comment]
I don't see the process starting in Task Manager, either as a Process or a Service.

**Comment by riQQ** [comment]
Please check the windows event log and post the entries you found: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#windows-log-files

**Comment by RMXdotEXE** [comment]
I actually don't even see an entry in the Windows Event Viewer. I filtered by .NET Frametime and Application Error.

**Comment by riQQ** [comment]
Is there a file named SquirrelSetup.log in `%LocalAppData%\HearthstoneDeckTracker`. Could you upload it?

**Comment by RMXdotEXE** [comment]
Sure! 
[SquirrelSetup.log](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2027015/SquirrelSetup.log)

**Comment by RMXdotEXE** [comment]
That was in the directory you gave me. The final two entries are me trying to run the updater in hopes to fix it, but nothing happened.

**Comment by riQQ** [comment]
Try renaming the folder `%LOCALAPPDATA%\HearthstoneDeckTracker` and reinstalling.

**Comment by RMXdotEXE** [comment]
I fixed the problem, but doing a strange solution:

I noticed there were three folders, each with a different version of the app.

The most recent, app-1.6.5, didn't have any files in its folder except Images and Plugins.

I tried copy-pasting everything from a previous version into that folder, but that didn't work.

Next, I tried just deleting the app-1.6.5 folder, and that ran the Deck Tracker, installing app-1.6.6.

It seems my problem is fixed, and my decks are still there.

I appreciate all the help though, but do you know why HDT could have broken like this?

**Comment by riQQ** [comment]
Looks like the HDT version wasn't downloaded completely. But that's just a guess.

**Comment by beheh** [comment]
Looks like this is resolved.
