### ISSUE TITLE
playerdeck.xml was corrupted but restored from latest backup

### ISSUE THREAD

**Issue by smthwicked** [HearthSim/Hearthstone-Deck-Tracker#3678]
On May 10, I played many arenas. 
Today i received the following message: playerdeck.xml was corrupted but restored from latest backup. This is likely due to an unexpected shutdown.
Backups are generated on the first start of each day, so there may be lost data.
We are very sorry for the inconvenience. :( 
I'm very upset. My yesterday's statistics disappeared. Yesterday's backup was created w/o these games. 
How do I restore my stats?

**Comment by smthwicked** [comment]
There is last log:
[hdt_log_1524148168.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/1994992/hdt_log_1524148168.txt)

**Comment by smthwicked** [comment]
All my games was downloaded at hsreplay.net

**Comment by riQQ** [comment]
If there is no backup, there is no way to restore the stats.
