### ISSUE TITLE
monster hunter event not detecting the deck

### ISSUE THREAD

**Issue by geraldo22** [HearthSim/Hearthstone-Deck-Tracker#3680]
this bug#3658, that was already closed, happens to me and i noticed that there is no longer a milestone for it,why?

https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3658

**Comment by azeier** [comment]
Because it's fixed. Make sure you're on the latest version - download on https://hsdecktracker.net.

Please don't open new issues to comment on issues. Just comment on the issue.

**Comment by geraldo22** [comment]
ups my bad, i thought i couldn't comment on it

**Comment by geraldo22** [comment]
just installed the latest version but it persists... what am i doing wrong?
will showing you logs help

**Comment by riQQ** [comment]
Yes, post a log please.

**Comment by geraldo22** [comment]
well... this is awkward but i noticed that i had the import option disabled...

i fell bad for making you guys waist your time with me, im so sorry :S

**Comment by riQQ** [comment]
Thanks for reporting back. Glad you found the issue.
