### ISSUE TITLE
New feature idea for alerts

### ISSUE THREAD

**Issue by OnceUPop** [HearthSim/Hearthstone-Deck-Tracker#3685]
Hey, i am curious if this is possible from a technical point and if it is, if there is a practical reason it should not be implemented.

Today we have the option to make hearthstone popup whenever your turn starts.
We also have the option to make hearthstone flash when you get a incoming friendly challenge.

Question 1: Is it technically possible to make hearthstone popup whenever you get a friendly challenge?

Question 2: Is it technically possible to make hearthstone popup whenever you recieve a message from a friend? 

Many people ask you if you want to play 80G quest, and if you don't answer, they will ask the next friend on their list instead of challenging you.
Because the way it works now, i always miss the flashing alert in HDT because that window is minimized (browsing the web/watching youtube)

If this is not technically possible/or this is a feature you don't want to implement because it would put more load on blizzards servers (more inactive players hanging out in main menu) could you atleast add the option for a SOUND alert in HDT? 

The flashing alert is not good enough, since it's so easy to miss.
I would LOVE to get the popup option for friendly challenges and incoming messages.
But if not, PLEASE add the option of a SOUND alert in HDT.

Really appreciate all your hard work, HDT is an amazing tool :)

**Comment by CLJunge** [comment]
I'll take a look at this.

**Comment by OnceUPop** [comment]
:)
