### ISSUE TITLE
Lost all over 2 years of stats

### ISSUE THREAD

**Issue by PanterA60** [HearthSim/Hearthstone-Deck-Tracker#3691]
Hey,

Like the title say i lost of all my stats. Don't know if were some update or something, but this moment i only have stats for the recently matches i played.

Yes, already restore for the last backup but no luck. Something i noticed in deck tracker folder it was some corrupted files. I deleted then, copy the last ones for the backup rar and still nothing

![9474431d888dd061409eabf7aba62f06](https://user-images.githubusercontent.com/39570954/40505688-f29b5816-5f8c-11e8-9f48-53a78887c232.png)

For example, i have more then 5900 matches recorded by deck tracker.

![123](https://user-images.githubusercontent.com/39570954/40506149-7b53d93e-5f8e-11e8-80d5-85ea9c98e6b8.png)

And inside the deck tracker itself only show no more then 300.

![12a9b1e6187ee91ed84317d1767cdeb4](https://user-images.githubusercontent.com/39570954/40506100-55d6be2e-5f8e-11e8-8a1b-0d3228cf5b03.png)

Any help is welcome.
Thanks.

**Comment by riQQ** [comment]
Check the filters.

**Comment by PanterA60** [comment]
The filters are ok. They are defined to "all" and "all time".

**Comment by riQQ** [comment]
Please post a screnshot of the stats window.

**Comment by PanterA60** [comment]
![untitled](https://user-images.githubusercontent.com/39570954/40510000-2d8d82ea-5f93-11e8-9e97-9ee294f39d1f.png)

**Comment by PanterA60** [comment]
Ah, sorry.

![33222806_1668614793233979_7673568817926111232_n](https://user-images.githubusercontent.com/39570954/40533648-50bf470e-5ffb-11e8-8301-3699e98d0e89.png)

The problem must be something more deep than some settings. That deck "Jade Druid(a)" if i remember well, had >500 games played. Now have this:

![1](https://user-images.githubusercontent.com/39570954/40534083-be9d3c8a-5ffc-11e8-9fc8-87f913963929.png)

![3211](https://user-images.githubusercontent.com/39570954/40534088-c0866f6c-5ffc-11e8-8e5e-6c85d06a461a.png)

**Comment by Eisigerhauch** [comment]
I have the same issue which extends to arena stats. Some runs seem to be in a cut off period and are displayed like this:
![hrsstatdistortion](https://user-images.githubusercontent.com/40520986/41810251-d0972f70-76fb-11e8-9af7-320d7ef145d3.PNG)
 other runs aren't displayed or counted at all.

**Comment by riQQ** [comment]
@Eisigerhauch these are just Arena decks with no matches

**Comment by riQQ** [comment]
@PanterA60 your stats files got corrupted, see the first screenshot in your first post. This can happen if the computer crashes / is turned of while HDT is writing the stats files.

**Comment by riQQ** [comment]
This shouldn't happen again starting with 1.7.6 (see b04f47268f540739364fc5f6798f56e46881b3b7).

**Comment by riQQ** [comment]
The stats in the screenshot were all recorded after corruption of the original stats files, so there is nothing else going on. This issue is fixed.
