### ISSUE TITLE
Can you make it possible to remove tags like Brawl from decks?

### ISSUE THREAD

**Issue by DMW150** [HearthSim/Hearthstone-Deck-Tracker#3695]
Is there anyway to remove tags like Brawl from decks that I don't want _in the Brawl tab_ . For example, I used my standard decks in Heroic Tavern Brawl, and as intended my deck would go to the brawl tab. But I wanna have all my decks in Standard tab again but cant remove the Brawl tag.
![screenshot_33](https://user-images.githubusercontent.com/33665341/40882305-d81eed7e-66ab-11e8-983f-7d1c2655a31d.png)

**Comment by ceceita** [comment]
workaround here 

> What works on the other hand is giving it a favorite tag and removing that tag again

https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3671

**Comment by azeier** [comment]
This behavior should be fixed with the next release. Decks will not be tagged as brawl if they have any non-brawl games.
