### ISSUE TITLE
Dungeon runs are listed as "Monster Hunt" in deck tracker

### ISSUE THREAD

**Issue by asakurato** [HearthSim/Hearthstone-Deck-Tracker#3697]
Haven't fount same issue opened here. So basically, every new dungeon run started is named Monster Hunt instead of Dungeon Run like it used to. See screenshot
![capture](https://user-images.githubusercontent.com/20476454/40981227-8141b0d0-68eb-11e8-876d-42c0d357b79d.JPG)

**Comment by SamB** [comment]
This code seems a bit off: https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/bcd4ce2a66f0cb9919a315452c6ede0337a090ab/Hearthstone%20Deck%20Tracker/Hearthstone/DungeonRun.cs#L25-L26

There doesn't seem to be any attempt to check whether or not we're actually dealing with a Monster Hunt before doing this replacement in the template, so naturally it's always performed, and our Dungeon Runs get renamed too...
