### ISSUE TITLE
Seeping Ooze Recruits Are Not Permanently Removed From Deck

### ISSUE THREAD

**Issue by jk2112** [HearthSim/Hearthstone-Deck-Tracker#3699]
### Expected Behavior
Recruited Creatures should be permanently removed from the deck

### Actual Behavior
When I recruit creatures with Seeping Ooze (duplicating the deathrattle of Kathrena or Silver Vanguard), the creature is temporarily removed from the deck, but is added back in next turn.

### Steps to reproduce behavior
Use AAECAR8IxQj4CMLOAobTAufhApziArbqAoDzAguNAcbCAuvCAsrDApvLApzNAtPNAt3SAuHjAu3qAvLxAgA=
Or any deck with Seeping Ooze, Kathrena, and Silver Vanguard. Play Ooze to recruit a creature.

### Log/Screenshots

[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2077777/hdt_log.txt)

**Comment by azeier** [comment]
Fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/6f0173c5e4c56fc305e9c9cc5cc956e3eb97fa7b
