### ISSUE TITLE
HS Deck Tracker - Failed to extract

### ISSUE THREAD

**Issue by LynxWagner** [HearthSim/Hearthstone-Deck-Tracker#3703]
## Bug report
HDT-Installer.exe 
Installation has failed 
Failed to extract installer

### Expected Behavior

When I try to open the installer it shows this message
just try opening the installer

### Actual Behavior

I get an error message the first time I tried to install

### Steps to reproduce behavior

just open the installer

### Log/Screenshots
I have absolutely nothing from the deck tracker inside my computer, so I have no log

**Comment by riQQ** [comment]
Can you post a Screenshot of the error message? Does it mention a log?

**Comment by LynxWagner** [comment]
[https://imgur.com/a/094U7L8](url)

**Comment by LynxWagner** [comment]
[https://imgur.com/2rf38tS](url) error

**Comment by riQQ** [comment]
Can you upload the file `%LOCALAPPDATA%\HearthstoneDeckTracker\SquirrelSetup.log`
