### ISSUE TITLE
hearthstone deck tracker has stopped working!!

### ISSUE THREAD

**Issue by itachiHS** [HearthSim/Hearthstone-Deck-Tracker#3706]
logs:
Log Name:      Application
Source:        Application Error
Date:          6/16/2018 1:41:45 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      kasaii-PC
Description:
Faulting application name: Hearthstone Deck Tracker.exe, version: 1.6.6.3629, time stamp: 0x5b0461fe
Faulting module name: KERNELBASE.dll, version: 6.1.7601.17514, time stamp: 0x4ce7bafa
Exception code: 0xc06d007e
Fault offset: 0x0000b727
Faulting process id: 0xf48
Faulting application start time: 0x01d40566ff130c57
Faulting application path: C:\Users\kasaii\Downloads\Hearthstone.Deck.Tracker-v1.6.6\Hearthstone Deck Tracker\Hearthstone Deck Tracker.exe
Faulting module path: C:\Windows\syswow64\KERNELBASE.dll
Report Id: 3ead263a-715a-11e8-992d-acb57d8a5005
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-06-16T11:41:45.000000000Z" />
    <EventRecordID>2723</EventRecordID>
    <Channel>Application</Channel>
    <Computer>kasaii-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Hearthstone Deck Tracker.exe</Data>
    <Data>1.6.6.3629</Data>
    <Data>5b0461fe</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>6.1.7601.17514</Data>
    <Data>4ce7bafa</Data>
    <Data>c06d007e</Data>
    <Data>0000b727</Data>
    <Data>f48</Data>
    <Data>01d40566ff130c57</Data>
    <Data>C:\Users\kasaii\Downloads\Hearthstone.Deck.Tracker-v1.6.6\Hearthstone Deck Tracker\Hearthstone Deck Tracker.exe</Data>
    <Data>C:\Windows\syswow64\KERNELBASE.dll</Data>
    <Data>3ead263a-715a-11e8-992d-acb57d8a5005</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        .NET Runtime
Date:          6/16/2018 1:41:43 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      kasaii-PC
Description:
Application: Hearthstone Deck Tracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c06d007e, exception address 752EB727

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-06-16T11:41:43.000000000Z" />
    <EventRecordID>2722</EventRecordID>
    <Channel>Application</Channel>
    <Computer>kasaii-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: Hearthstone Deck Tracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c06d007e, exception address 752EB727
</Data>
  </EventData>
</Event>

**Comment by riQQ** [comment]
See #3662.

**Comment by itachiHS** [comment]
ty it works now :)
