### ISSUE TITLE
Deck Tracker not Launching Hearthstone

### ISSUE THREAD

**Issue by JiveArtifact** [HearthSim/Hearthstone-Deck-Tracker#3708]
### Expected Behavior
I expected to press the "Launch Hearthstone" button and have the Hearthstone app open with the deck tracker active.

### Actual Behavior
Nothing happened - the "Start Hearthstone" button was gray for a second but then returned to its original state without the Hearthstone app having been opened. 

### Steps to reproduce behavior
Just clicking on start Hearthstone.
I've tried the other steps for it not working, such as changing the path, but none of it has worked so far. -

**Comment by CLJunge** [comment]
Same for me

**Comment by azeier** [comment]
Looks like blizzard changed something about the procotols. Don't have time to investigate right now, but this is the command that is no longer working: https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/master/Hearthstone%20Deck%20Tracker/Utility/HearthstoneRunner.cs#L52

**Comment by CLJunge** [comment]
I'll take a look.

**Comment by azeier** [comment]
The "name" hasn't changed. `battlenet://WTCG` still open the hearthstone tab on the launcher.

**Comment by azeier** [comment]
Since we can still launch the battle.net client via `battlenet://` the easiest fix is probably:
1. Run `battlenet://` (already happens)
2. Wait for the process (already happens)
3. Get `Battle.net.exe` path via the running process
4. Run `<full_path>/Battle.net.exe --exec="WTCG"`

I'm not sure how to best work around the Battle.net.beta client though. Is that the same executable?

**Comment by azeier** [comment]
I guess we actually know whether we find the `Battle.net` or `Battle.net.beta` process and thus find the correct executable path regardless. The above approach will work.

**Comment by CLJunge** [comment]
The command is actually 'Battle.net.exe --exec="launch WTCG"'. Just installed the beta version and the default and beta client are now running under the same name. So that shouldn't be a problem. I'll implement a fix.

**Comment by azeier** [comment]
Gonna leave this open actually until the release it out, to prevent duplicates.

There should be a release around noon PST tomorrow.

**Comment by azeier** [comment]
Fixed with v1.6.8
