### ISSUE TITLE
Can't move game with no deck to a deck

### ISSUE THREAD

**Issue by Jonius7** [HearthSim/Hearthstone-Deck-Tracker#3711]
### Expected Behavior
When in the Constructed -> Matches window, selecting a game where deck is "none' and clicking the "Move" button, to then select the deck, should move the game to the selected deck (and version)

### Actual Behavior
Game does not get updated, stays at "none" deck.

### Steps to reproduce behavior
<Select any game (even a game that already has a deck assigned to it), click "Move" select a deck and version and nothing happens

### Log/Screenshots
![2018-06-28 14_14_26-hearthstoneoverlay](https://user-images.githubusercontent.com/1049415/42012843-9ca25fec-7add-11e8-8c90-7328cc836a1a.png)

**Comment by riQQ** [comment]
If i remember correctly, you can see that the game was indeed moved after restarting. So this is a UI update problem.

**Comment by riQQ** [comment]
Fixed in v1.10.5 by 7a27a7b4b7e14ab1690366553f485cefaaec5cbb.
