### ISSUE TITLE
'None'

### ISSUE THREAD

**Issue by bluesh34** [HearthSim/Hearthstone-Deck-Tracker#3713]
It says 'None' in the field which is normally the opponent's name in 'Latest Replays' and when I click on that match it says 'The uploaded file is not a valid replay'.  This issue only started recently.  This app is bugged as hell for me as of like 1 or 2 days ago.  You guys just made some changes or something?  If so, it's even worse than before (unless the problem is with my pc) and it wasn't even performing that well before.  Nice app when it decides to work though.

**Comment by beheh** [comment]
Could you please share the URL of the replays here (the ones that say "The uploaded file is not a valid replay")?
