### ISSUE TITLE
unable to connect my twitch

### ISSUE THREAD

**Issue by cannotbeatme1** [HearthSim/Hearthstone-Deck-Tracker#3716]
kind of losing my mind trying to get this to work. everytime i click "twitch extension" on the advanced options on my deck tracker, it never updates to tell me something different its always the same. it only gives me the option to connect to my twitch account. well... ive done that already. ive also enabled it on my twitch extension. there is no fucking reason it shouldnt work. IVE EVEN RUN IT AS ADMIN AND REDOWNLOADED> AHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by azeier** [comment]
You wanna try this "asking for help" thing again? Maybe include a screenshot of your deck tracker and hsreplay.net settings page.
