### ISSUE TITLE
Collection wont update

### ISSUE THREAD

**Issue by DrBonzay** [HearthSim/Hearthstone-Deck-Tracker#3725]
## Bug report
Collection wont update, even if I open/close it, log out and relog.

Error message:
Could not update your collection. Please try again later.
If this problem persists please try logging out and back in under 'options > hsreplay.net > my account'

### Expected Behavior
Update collection

### Actual Behavior
I get the error message and the collection wont update

**Comment by azeier** [comment]
Is this still an issue with v1.6.9?

**Comment by DrBonzay** [comment]
@azeier Nope, its solved.
Thanks!
