### ISSUE TITLE
Error to install deck tracker (Windows 7 pro)

### ISSUE THREAD

**Issue by SrBananaPhone12** [HearthSim/Hearthstone-Deck-Tracker#3728]
Hello guys, i am having a error to install deck tracker in my PC.
Always when i try to install by HDT installer appear that icon in my taskbar, after a few seconds this close and nothing happen. Can anyone know how to solve that problem?
(screenshot is the icon)
![screenshot_2](https://user-images.githubusercontent.com/41092486/42544667-79d926ca-8489-11e8-98c6-9a984c73dfd7.png)

**Comment by riQQ** [comment]
https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues
