### ISSUE TITLE
Shifter Zerus and attack/health swap bugs.

### ISSUE THREAD

**Issue by CCTrainXD** [HearthSim/Hearthstone-Deck-Tracker#3731]
## Bug report
When Shifter Zerus' transforms into a card that swaps stats at the end of turn, it retains those swapped stats when played for another minion.
### Expected Behavior
Stats are erased, and the transformation effect overrides and the new minion should have its own stats. Not sure how that works.

### Actual Behavior
Stats remain the same throughout transformations. If zerus transformed into a 3/8 gilnean royal guard, it turns into an 8/3 Gilnean Royal Guard(Worgen form) and all future transformations retain this 8/3 statline. 

### Steps to reproduce behavior
Wait for shifter zerus to transform into a card that swaps attack/health at the end of turn. End turn. At the start of your turn, note stats of the transformed zerus.
### Log/Screenshots
Minion affected by the 2 mana neutral 1/4 Spell dmg +1  swapper. In hand.
![hearthstone screenshot 07-11-18 17 45 23](https://user-images.githubusercontent.com/28812825/42601473-b5cdd914-8533-11e8-963f-6642c800770c.png)
On the board after playing it.
![hearthstone screenshot 07-11-18 17 45 39](https://user-images.githubusercontent.com/28812825/42601475-b5dfc9ee-8533-11e8-9a27-3713bbf351be.png)

Minion affected by the 3 mana hunter card with 2/5 stealth swapper. In hand.
![hearthstone screenshot 07-11-18 17 54 37](https://user-images.githubusercontent.com/28812825/42601505-d39cddaa-8533-11e8-8688-b00c96a877c8.png)

When played on the board.
![hearthstone screenshot 07-11-18 17 54 52](https://user-images.githubusercontent.com/28812825/42601506-d3aaa4d0-8533-11e8-8325-0d04a19ba8fa.png)

**Comment by riQQ** [comment]
Did you mean to post to https://github.com/HearthSim/hs-bugs?

**Comment by CCTrainXD** [comment]
Right. I'm tired, my bad..
