### ISSUE TITLE
problem with the installasion

### ISSUE THREAD

**Issue by ahmedzamin11** [HearthSim/Hearthstone-Deck-Tracker#3732]
i got some problems with the installasion of hearthstone deck tracker when i open the HDT-Installer
its show me the icon
![problem](https://user-images.githubusercontent.com/41154701/42633028-7a93769a-85df-11e8-8f8d-7bc17e5e6860.PNG)
 then she show me this
![problem 2](https://user-images.githubusercontent.com/41154701/42633045-84ac198e-85df-11e8-8041-ba7d92eb5a18.PNG)

**Comment by riQQ** [comment]
Post log files (Windows and setup): https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues
