### ISSUE TITLE
Hearthstone icon does not flash when your turn starts

### ISSUE THREAD

**Issue by ChanmanV** [HearthSim/Hearthstone-Deck-Tracker#3735]
### Expected Behavior
The flashing icon to blink so you know it's your turn to go. 

### Actual Behavior
The flashing icon does not turn on when the timer reaches the set amount. The alerts just don't seem to work.

### Steps to reproduce behavior
Set the "On Turn Start: Flash" setting to be on and wait for it to flash when your turn begins. It never flashes.

### Log/Screenshots
Here is the intercom ticket - https://app.intercom.io/a/apps/lhrr2hfa/inbox/inbox/all/conversations/17315625693

**Comment by azeier** [comment]
This is working fine for me.
