### ISSUE TITLE
Mecha Jaraxxus

### ISSUE THREAD

**Issue by themuffinboyy** [HearthSim/Hearthstone-Deck-Tracker#3739]
Using Mecha Jaraxxus causes the tracker to not auto-select decks.

**Comment by azeier** [comment]
Please make sure you are on v1.6.9 an post a log after a game where this happens. See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues

**Comment by themuffinboyy** [comment]
Sorry, this is happening on the Mac version.

**Comment by azeier** [comment]
Ah. I see you opened an issue on the correct project now. I'll close this.
