### ISSUE TITLE
Won't run with hearthstone after update

### ISSUE THREAD

**Issue by BayouBulldog** [HearthSim/Hearthstone-Deck-Tracker#3744]
When I boot up hdt and hearthstone together, I get a message saying they are conflicting.  It says I need to set one to administrator or something.  I'm not tech savvy.  Don't know what to do about it.  Everything worked fine before the update.

**Comment by Zawodowiec1532** [comment]
Try right click on HDT icon and press "Run as administrator".

**Comment by BayouBulldog** [comment]
Thanks for the tip... it seems like all it took was turning off hdt and rebooting it.  Now it seems to work fine.  Like I said, I'm definitely not tech savvy... lol.

**Comment by riQQ** [comment]
For reference: seems to be #2738
