### ISSUE TITLE
HDT crashes if I have the overlay open on a second monitor and a game ends

### ISSUE THREAD

**Issue by Fratley1863** [HearthSim/Hearthstone-Deck-Tracker#3752]
### Expected Behavior

The program to work the same as if it were minimized. 

### Actual Behavior

The program crashed. Screen went black and had flashes of static color and caused errors in all other tabs open on the second monitor. 

### Steps to reproduce behavior

If I have hearthstone open and end a game while the overlay is up on the other monitor, this will occur every time.

### Log/Screenshots

[hdt_log_1533680051.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2268412/hdt_log_1533680051.txt)

**Comment by riQQ** [comment]
Please provide logs. See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues (sections `HDT crash logs` and `Windows log files`)

**Comment by Fratley1863** [comment]
Saw no HDT crash logs, it seems like HDT simply caused everything else to crash including Hearthstone itself. Here are the windows logs from the two occurrences, the first when it happened, the second when I recreated it.

Log Name:      Application
Source:        Application Error
Date:          07-Aug-18 19:19:35
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-9RS50DL
Description:
Faulting application name: nvspcaps64.exe, version: 3.6.0.74, time stamp: 0x5909f95b
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000000
Faulting process id: 0x1fc8
Faulting application start time: 0x01d42e8acebe6bcb
Faulting application path: C:\Program Files\NVIDIA Corporation\ShadowPlay\nvspcaps64.exe
Faulting module path: unknown
Report Id: a271b7fd-498a-4ae4-a996-b32beb212ffc
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-08-07T23:19:35.251354700Z" />
    <EventRecordID>6642</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-9RS50DL</Computer>
    <Security />
  </System>
  <EventData>
    <Data>nvspcaps64.exe</Data>
    <Data>3.6.0.74</Data>
    <Data>5909f95b</Data>
    <Data>unknown</Data>
    <Data>0.0.0.0</Data>
    <Data>00000000</Data>
    <Data>c0000005</Data>
    <Data>0000000000000000</Data>
    <Data>1fc8</Data>
    <Data>01d42e8acebe6bcb</Data>
    <Data>C:\Program Files\NVIDIA Corporation\ShadowPlay\nvspcaps64.exe</Data>
    <Data>unknown</Data>
    <Data>a271b7fd-498a-4ae4-a996-b32beb212ffc</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Application Hang
Date:          07-Aug-18 19:20:47
Event ID:      1002
Task Category: (101)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-9RS50DL
Description:
The program chrome.exe version 68.0.3440.84 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 2134
 Start Time: 01d42e8c181bd488
 Termination Time: 9
 Application Path: C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
 Report Id: e57ec9f8-d8ca-4f95-a30f-9cc6162550f2
 Faulting package full name: 
 Faulting package-relative application ID: 

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Hang" />
    <EventID Qualifiers="0">1002</EventID>
    <Level>2</Level>
    <Task>101</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-08-07T23:20:47.693354700Z" />
    <EventRecordID>6649</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-9RS50DL</Computer>
    <Security />
  </System>
  <EventData>
    <Data>chrome.exe</Data>
    <Data>68.0.3440.84</Data>
    <Data>2134</Data>
    <Data>01d42e8c181bd488</Data>
    <Data>9</Data>
    <Data>C:\Program Files (x86)\Google\Chrome\Application\chrome.exe</Data>
    <Data>e57ec9f8-d8ca-4f95-a30f-9cc6162550f2</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Binary>55006E006B006E006F0077006E0000000000</Binary>
  </EventData>
</Event>

Log Name:      Application
Source:        Application Hang
Date:          07-Aug-18 19:21:05
Event ID:      1002
Task Category: (101)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-9RS50DL
Description:
The program Hearthstone.exe version 12.0.0.25770 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 8c8
 Start Time: 01d42e9c46b34a7b
 Termination Time: 4294967295
 Application Path: C:\Program Files (x86)\Hearthstone\Hearthstone.exe
 Report Id: 51a3d14d-580e-4544-9197-635f3c201447
 Faulting package full name: 
 Faulting package-relative application ID: 

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Hang" />
    <EventID Qualifiers="0">1002</EventID>
    <Level>2</Level>
    <Task>101</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-08-07T23:21:05.215165000Z" />
    <EventRecordID>6651</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-9RS50DL</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Hearthstone.exe</Data>
    <Data>12.0.0.25770</Data>
    <Data>8c8</Data>
    <Data>01d42e9c46b34a7b</Data>
    <Data>4294967295</Data>
    <Data>C:\Program Files (x86)\Hearthstone\Hearthstone.exe</Data>
    <Data>51a3d14d-580e-4544-9197-635f3c201447</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Binary>54006F00700020006C006500760065006C002000770069006E0064006F0077002000690073002000690064006C00650000000000</Binary>
  </EventData>
</Event>

**Comment by riQQ** [comment]
Can you try disabling Nvidia ShadowPlay?

**Comment by Fratley1863** [comment]
Disabled ShadowPlay and can no longer recreate the errors. Thank you for your help!
