### ISSUE TITLE
Hearthstone Deck Tracker either sometimes disables or starts without the plugins turned on.

### ISSUE THREAD

**Issue by 1ll3g4l** [HearthSim/Hearthstone-Deck-Tracker#3753]
## Bug report
There has been multiple times where I go and unpack packs and the plugin isn't turned on, as to how it happens I sadly don't know, all I know is that it has happened to me at least multiple times now.

### Expected Behavior

Be turned on when the program is running, ALWAYS.

### Actual Behavior

Turned off

### Log/Screenshots
https://transfer.sh/FIyQh/hdt_log.txt - most recent
https://transfer.sh/u6P9M/hdt_log_1528293160.txt - before most recent

**Comment by riQQ** [comment]
Can you check the modification date and content of the file `%appdata%\HearthstoneDeckTracker\plugins.xml` after enabling the plugins and closing HDT.

**Comment by 1ll3g4l** [comment]
This happened again, and I went and check it was set to "false", after enabling it was set back to "true" again, and stayed on but the problem I am having is that it randomly happens and I really don't know why, I might just reset configurations settings and such back to default again, it would kind of suck to not have the pity timers correctly tho.

**Comment by riQQ** [comment]
I don't think resetting your config will help here. 
I think we'll have to improve logging or analyze the source code.

**Comment by 1ll3g4l** [comment]
I honestly don't know anymore I am going to switch to something else to track my packs, this is just too unreliable at this point
