### ISSUE TITLE
Boomsday not available as pack type in Arena reward dialogue

### ISSUE THREAD

**Issue by ShotFromGuns** [HearthSim/Hearthstone-Deck-Tracker#3757]
### Expected Behavior
Boomsday would be auto-selected as the type of pack reward for completing an Arena run as of expansion launch (12 p.m. Central/GMT-5 August 7, 2018), or at least available in the drop-down menu.

### Actual Behavior
The post-run reward tracking dialogue still defaults to Witchwood (the previous expansion), and Boomsday is not available as an option.

### Steps to reproduce behavior
Play through an Arena run.

**Comment by riQQ** [comment]
Duplicate of #3749

**Comment by ShotFromGuns** [comment]
Ugh, that's what I get for only checking open issues. Thanks!
