### ISSUE TITLE
The deck tracker stops updating anymore after playing some matches...

### ISSUE THREAD

**Issue by ElektroStudios** [HearthSim/Hearthstone-Deck-Tracker#3758]
## Bug report
The deck tracker stops updating anymore after playing some matches.

I mean, the visual part where HDT tracks and shows your cards at the top-right corner in Hearthstone while you are in a current match, it stops updating after playing some matches.

It sometimes happens after playing one match, other times after playing 4 or 5... seems random.

The only workaround is to close and re-open HDT during the current match, then it will work again... until the problem happens again randomly after some matches.

### Steps to reproduce behavior

1. With Hearthstone running, run HDT.
2. Start a match with another player in ranked or unranked mode.
3. Continue playing new matches, at some point you will see that the deck tracker does not update anymore for the current match... and for newer matches.

### Log/Screenshots
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2276051/hdt_log.txt)

The log file has logged two matches, the first one its all ok, the second match the visual deck tracker stopped working from the start.

**Comment by riQQ** [comment]
Player and opponent are switched up here, too. Might be cause of this issue.
```
3:17:01 PM|Info|GameV2.CurrentMode >> TOURNAMENT
3:17:01 PM|Info|DeckImporter.FromConstructed >> Found 11 decks, 0 new
3:17:01 PM|Info|GameEventHandler.HandleInMenu >> Game is now in menu.
3:17:01 PM|Info|TurnTimer.Stop >> Stopping turn timer
3:17:01 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
3:17:01 PM|Info|GameEventHandler.SaveAndUpdateStats >> Set CurrentGameStats.GameMode to Casual
3:17:01 PM|Info|GameEventHandler.SaveAndUpdateStats >> Saving DefaultDeckStats
3:17:03 PM|Info|FullScreenFxHandler.Handle >> Now in queue (8/9/2018 3:17:02 PM)
3:17:03 PM|Info|DeckImporter.FromConstructed >> Found 11 decks, 0 new
3:17:03 PM|Info|FullScreenFxHandler.AutoSelectDeckById >> Found selected deck: MechaThun Druid
3:17:03 PM|Info|FullScreenFxHandler.AutoSelectDeckById >> Already using the correct deck
3:17:15 PM|Info|GameEventHandler.HandleGameStart >> --- Game start ---
3:17:15 PM|Info|GameV2.Reset >> -------- Reset ---------
3:17:15 PM|Info|TurnTimer.Start >> Starting turn timer
3:17:15 PM|Warning|TurnTimer.Start >> Waiting for player entity
3:17:15 PM|Info|TagChangeActions.SetHeroAsync >> Found hero with id=43
3:17:15 PM|Info|GameEventHandler.SetOpponentHero >> Opponent=Druid
3:17:15 PM|Info|TagChangeActions.SetHeroAsync >> Found hero with id=45
3:17:15 PM|Info|TagChangeActions.SetHeroAsync >> Found hero with id=77
3:17:15 PM|Info|GameEventHandler.SetPlayerHero >> Player=Warrior
3:17:16 PM|Info|GameV2.CurrentMode >> GAMEPLAY
3:17:16 PM|Info|Player.Draw >> [Opponent] id=26, cardId=, cardName=, zonePos=1,Info={turn=0, originalZone=DECK, hasOutstandingTagChanges=true, hidden=true, OriginalController=1}
3:17:16 PM|Info|Player.Draw >> [Opponent] id=21, cardId=, cardName=, zonePos=2,Info={turn=0, originalZone=DECK, hasOutstandingTagChanges=true, hidden=true, OriginalController=1}
3:17:16 PM|Info|Player.Draw >> [Opponent] id=40, cardId=, cardName=, zonePos=3,Info={turn=0, originalZone=DECK, hasOutstandingTagChanges=true, hidden=true, OriginalController=1}
3:17:16 PM|Info|Player.Draw >> [Opponent] id=36, cardId=, cardName=, zonePos=4,Info={turn=0, originalZone=DECK, hasOutstandingTagChanges=true, hidden=true, OriginalController=1}
3:17:16 PM|Info|Player.CreateInHand >> [Opponent] id=79, cardId=GAME_005, cardName=The Coin, zonePos=5,Info={turn=0, mark=Coin, created=true, originalZone=HAND, hasOutstandingTagChanges=true, OriginalController=1}
3:17:45 PM|Info|GameEventHandler.HandleTurnStart >> --- Opponent turn 1 ---
3:17:50 PM|Info|GameEventHandler.HandleTurnStart >> --- Player turn 1 ---
3:17:50 PM|Info|Player.Draw >> [Opponent] id=31, cardId=, cardName=, zonePos=6,Info={turn=1, originalZone=DECK, hasOutstandingTagChanges=true, hidden=true, OriginalController=1}
3:17:55 PM|Info|GameEventHandler.HandleTurnStart >> --- Opponent turn 2 ---
3:17:59 PM|Info|GameEventHandler.HandleOpponentHeroPower >> OpponentHeroPower (id:CS2_102 turn:2 from:-1)
3:18:02 PM|Info|GameEventHandler.HandleTurnStart >> --- Player turn 2 ---
3:18:02 PM|Info|Player.Draw >> [Opponent] id=11, cardId=, cardName=, zonePos=7,Info={turn=2, originalZone=DECK, hasOutstandingTagChanges=true, hidden=true, OriginalController=1}
3:18:06 PM|Info|GameEventHandler.HandlePlayerHeroPower >> PlayerHeroPower (id:CS2_017_HS1 turn:2 from:-1)
```

**Comment by ElektroStudios** [comment]
Will the developer(s) support this issue?.

**Comment by azeier** [comment]
Here's a test build with a potential fix and improved logging that should help us figure out what's going on: https://github.com/HearthSim/HDT-dev-builds/releases/download/v1.7.5-dev3680/HDT-Installer.exe

This version will overwrite your current HDT installation but keep all stats/settings and will update to the next full release once it's available. 

Please let us know whether you still experience the same issues with this release and include new logs if you do.

**Comment by ElektroStudios** [comment]
Hi, thanks for support this issue. I'm writting this comment because I answered to the other issue with Baku ( https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3743#issuecomment-412299982 ) but I can't play to test this other problem until some hours later after now, I'm not ignoring this problem, I will test it in some hours and say whether it still happen or not. I will edit this comment then.

**Comment by azeier** [comment]
I'm fairly confident this is the same underlying issue as #3743.

**Comment by ElektroStudios** [comment]
Ok so I tried the debug version for a couple of hours, I played about 20 games, at first I was hopeful that the error would not happen, because during the first hours playing everything went well, however, in the last game (which is also the last game recorded in the log) the problem happened again, my deck tracker wan't updated.

Here is the log:

[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2280668/hdt_log.txt)

PD: the last logged match  starts at line 3479.

**Comment by riQQ** [comment]
Could you also post your `<Hearthstone-Installation>/Logs/Power.log` file?

**Comment by ElektroStudios** [comment]
Of course, here is the Power.log, It had a size of 20 mb so I cutted it, in this log you can see the last two matches with player name: De3#2127

[Power_.log](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2280683/Power_.log)

Those are the same last two matches recorded in the hdt_log.txt that I provided above. The second match with that player is when the problem has occured in HDT.

**Comment by azeier** [comment]
The log above still uses version 3680. Can you try version 3681 I linked here? https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3743#issuecomment-412306182

**Comment by azeier** [comment]
Since this is *very* like the same issue as https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3743 I'm going to close this to keep the conversation over there. If it turns out they are separate issues we can reopen this.
