### ISSUE TITLE
Magnetic minion played as buff triggers Explosive Runes

### ISSUE THREAD

**Issue by beheh** [HearthSim/Hearthstone-Deck-Tracker#3759]
## Bug report

From https://twitter.com/SamSquatchGamin/status/1027541960289124352:
> [...] if you magnetise a minion with one on the board it triggers the explosive runes secret on the deck tracker, but not in game

### Expected Behavior
When a Magnetic minion is played as the buff, it should not remove Explosive Runes from the list of possible secrets.

### Actual Behavior
Explosive Runes was removed from the list of possible secrets after a Magnetic minion was played as the buff.

### Steps to reproduce behavior
Trivial.

### Log/Screenshots
None.

**Comment by azeier** [comment]
Fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/3084764c84f707d8141210401b9b96141f30da7b
