### ISSUE TITLE
Augmented Elekk + Fal'dorei Strider Shows Only 3 Spooders

### ISSUE THREAD

**Issue by OttoTheEmperor** [HearthSim/Hearthstone-Deck-Tracker#3760]
### Expected Behavior

Instead of creating 6 spider ambushes after playing Augmented Elekk and Strider.......
### Actual Behavior

Tracker only shows 3 ambushes in deck, as opposed to the expected 6.

### Log/Screenshots

[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2277089/hdt_log.txt)

**Comment by drake5000** [comment]
I can confirm that

**Comment by DOSD-Tutorials** [comment]
I would expand this to ANY cards that are duplicated by Augmented Elekk, not just Fal'dorei Strider. Any combo with Elekk are not reflected, i.e. Lab Recruiter, The Darkness, etc.

**Comment by azeier** [comment]
Fixed with v1.8.7.
