### ISSUE TITLE
Unable to import decks

### ISSUE THREAD

**Issue by JoeBarouneD** [HearthSim/Hearthstone-Deck-Tracker#3761]
Hi, the deck Tracker is unable to import/update decks from url (i tested from Hearthstonetopdecks).

This was introduced since the last update.
Edit : other imports works, so i suspect the website to have changed their coding.

Here is the log : 
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2277400/hdt_log.txt)

**Comment by azeier** [comment]
Ever since deck codes were introduced importing from urls is no longer maintained and will likely be removed eventually. 

You can paste deck codes you copy from any website into hdt.

**Comment by JoeBarouneD** [comment]
I find the update function of websites useful to stick to a deck that is updated on the same webpage.
