### ISSUE TITLE
Failure to detect Battle.net is running

### ISSUE THREAD

**Issue by JoeBarouneD** [HearthSim/Hearthstone-Deck-Tracker#3762]
Hi, since 2 or 3 updates, my HDT is unable to launch the game, even if the launcher is starting, it doesn't launch the game, and i get an error message saying that an error happened.

[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2277497/hdt_log.txt)

**Comment by riQQ** [comment]
Does `Win + R` and entering `battlenet://` to start Battle.net if it's not running?

**Comment by azeier** [comment]
It seems to work fine for me so the protocol generally still works.

This is likely an issue with your Hearthstone and/or Battle.net installation. Try reinstalling those.

**Comment by azeier** [comment]
Got another report of this. Looks like HDT fails to detect that the bnet process is running.
![image](https://user-images.githubusercontent.com/7737910/44005294-15df1074-9e26-11e8-8f6e-85135c60a6da.png)

**Comment by Meadowvale** [comment]
I am not an experienced computer user but I am having the same issue
![hdt error](https://user-images.githubusercontent.com/42660007/44557853-9daa7000-a738-11e8-9f0e-aab335097025.jpg)

Does Win+R battlenet:// start battlenet if it's not running? - Yes, launches Battlenet
Does running <insert-path-to-battle-net-exe-here>\Battle.net.exe --exec="launch WTCG" (replace the path with the path on your system) start Hearthstone? - No, it starts Battlenet
any simple "this is what you do" help would be greatly appreciated.
