### ISSUE TITLE
Card tooltip fails to reflect changes to evolved entity

### ISSUE THREAD

**Issue by ChanmanV** [HearthSim/Hearthstone-Deck-Tracker#3763]
This is a bug ticket where change entity on an evolve is not being handled properly.

Here is the customer support ticket this issue is originating from:

https://app.intercom.io/a/apps/lhrr2hfa/inbox/inbox/conversation/17943402798

It's been confirmed by Benedict that it's not a Twitch Extension issue.

**Comment by beheh** [comment]
Fixed by 50745f3797b5182c5bee75f803ed6e6c842cf5e8.
