### ISSUE TITLE
Baku / Genn aren't tracked after beeing revealed at game start

### ISSUE THREAD

**Issue by riQQ** [HearthSim/Hearthstone-Deck-Tracker#3771]
### Expected Behavior
Baku / Genn aren't tracked after beeing revealed at game start

### Actual Behavior
Baku / Genn being tracked

### Steps to reproduce behavior
Trivial

### Log/Screenshots
![oyrigvyh](https://user-images.githubusercontent.com/3404787/44239166-4e07f980-a1b8-11e8-86ff-7017347e855e.jpg)

**Comment by azeier** [comment]
IIRC, this is not consistent?

**Comment by riQQ** [comment]
Duplicate of #3692

**Comment by azeier** [comment]
I haven't seen it not working lately 😅
