### ISSUE TITLE
Whizbang the Wonderful cards appear as gifted in the opponents deck

### ISSUE THREAD

**Issue by beheh** [HearthSim/Hearthstone-Deck-Tracker#3773]
## Bug report

Looks like opposing Whizbang decks aren't completely fixed as of v1.7.5.
From https://twitter.com/Mathyoushs/status/1030509070497800192.

### Expected Behavior
The cards should appear as usual, without a gift icon.

### Actual Behavior
The cards appeared with a gift icon.

### Steps to reproduce behavior
Play against a Whizbang deck.

### Log/Screenshots
![grafik](https://user-images.githubusercontent.com/929769/44299136-81e63a80-a2f0-11e8-98e0-0499f779c8cd.png)

**Comment by beheh** [comment]
Can someone else reproduce this?

**Comment by Evgeniy-Pol** [comment]
I had the same behavior in 1.7.5.

Don't know if it helps - link for the replay:
https://hsreplay.net/replay/uTGkXbNDsZhGwf5hdGsxFo
All cards in mage's deck were marked as gifted.

**Comment by riQQ** [comment]
Can confirm

**Comment by azeier** [comment]
Unless there's a bug in the current implementation, I'm pretty much out of ideas for reliable ways of detecting this.

**Comment by azeier** [comment]
Looking at the powerlog from the replay above, the current implementation *should* work. So this is likely just a bug in https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/a437e722f1894087695aeab0366340ffa494a400

**Comment by riQQ** [comment]
Fixed by https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/c052ff87bb3885099829b42dec77f3d45b28f6b9 and https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/c052ff87bb3885099829b42dec77f3d45b28f6b9
