### ISSUE TITLE
Hearthstone deck tracker ios dont import mystifix decks... HELP #boomsday #bug #decktracker

### ISSUE THREAD

**Issue by ranynoui** [HearthSim/Hearthstone-Deck-Tracker#3775]

**Comment by ranynoui** [comment]
my warlock deck is import auto from hs to deck tracker but mystifix doesnt work (in ios) because on my windows one my mystifix deck is auto import from hs to deck tracker then i can see my decklist  while playing but not in ios 
HELPPP

**Comment by riQQ** [comment]
This bug tracker is for HDT and HDT is windows only.
