### ISSUE TITLE
HSDT don't record stats

### ISSUE THREAD

**Issue by JoeBarouneD** [HearthSim/Hearthstone-Deck-Tracker#3777]
Hi, my HSDT don't record any match in the stats menu, but keeps the decks scores actualised under them.
Is it a bug ?
![image](https://user-images.githubusercontent.com/42234198/44717176-a5617000-aabc-11e8-9ea3-777c6e963d92.png)
![image](https://user-images.githubusercontent.com/42234198/44717188-aeead800-aabc-11e8-885c-46f94e69dac5.png)

**Comment by azeier** [comment]
You are filtering to "Format: Wild" in the top screenshot.

**Comment by JoeBarouneD** [comment]
oh my bad !
sorry !
