### ISSUE TITLE
cannot figure out how to update HSReplay.net collection

### ISSUE THREAD

**Issue by Mord3th** [HearthSim/Hearthstone-Deck-Tracker#3785]
### Expected Behavior
When going into my collection after crafting a few new cards, I expected hsreplay.net to reflect these changes.  I am using the latest beta linked from Twitter.

### Actual Behavior
So far, my new cards are not listed in my collection.

### Steps to reproduce behavior
I keep quitting Hearthstone and Hearthstone Deck Tracker and re-opening both, then reload hsreplay.net.

### Log/Screenshots
Not sure which log would be applicable or where it is.

**Comment by riQQ** [comment]
You are probably a macOS user of https://github.com/HearthSim/HSTracker. Try logging out and logging back in. If this doesn't help, open an issue in the linked project, this is for Windows only.
