### ISSUE TITLE
Decks keep getting re-imported after being deleted or achieve

### ISSUE THREAD

**Issue by Icehole70** [HearthSim/Hearthstone-Deck-Tracker#3786]
## Bug report
Having the problem with around 17 decks. If i deleted or archive any deck as soon I go in to the play menu with in HS all decks that have been deleted or achieve show back up in HDT.

Even after uninstalling then removing/deleting the everything then installing a new copy/blank copy of HDT with nothing showing in it and not log in to HSReplay.net, as soon as go in to the play menu of HS all decks show up again.

### Expected Behavior

Decks to stay deleted or achieve

### Actual Behavior

Old unwanted decks are be re-imported back in to HDT after being deleted or achieve

### Steps to reproduce behavior

Having HDT open and going in to the play menu

### Log/Screenshots

[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2357631/hdt_log.txt)

Around line 37 in the log file you can see the old decks being imported
![hdt-bug](https://user-images.githubusercontent.com/21951696/45168797-c5321b80-b1c1-11e8-9b03-fc1a442d403b.gif)

**Comment by Icehole70** [comment]
- [ looks like someone else is having the same problem] #3774

**Comment by riQQ** [comment]
Duplicate of #3787
