### ISSUE TITLE
 Decks keep getting re-imported after being deleted

### ISSUE THREAD

**Issue by Icehole70** [HearthSim/Hearthstone-Deck-Tracker#3787]
## Bug report
Having the problem with around 17 decks. If i deleted or archive any deck as soon I go in to the play menu with in HS all decks that have been deleted show back up in HDT.

Even after uninstalling then removing/deleting the everything then installing a new copy/blank copy of HDT with nothing showing in it and not log in to HSReplay.net, as soon as go in to the play menu of HS all decks show up again.

### Expected Behavior

Decks to stay deleted

### Actual Behavior

Old unwanted decks are be re-imported back in to HDT after being deleted

### Steps to reproduce behavior

Having HDT open and going in to the play menu

### Log/Screenshots

Around line 37 in the log file you can see the old decks being imported
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2357750/hdt_log.txt)

![hdt-bug](https://user-images.githubusercontent.com/21951696/45169190-ada76280-b1c2-11e8-8b17-d24aaa52f6e4.gif)

**Comment by ceceita** [comment]
i think is becouse you have whizbang deck , and it imports all the recipes again..

**Comment by Icehole70** [comment]
Yup that looks like that it is, removing the Whizbang deck from HS and then deleting the extra decks from HDT so far they are not coming back when I go in to the play menu. Also looks like if you archive the extra decks they will stay archive, have not testing this to much also not sure what happen to them if I play a game using Whizbang.

Thanks for the info, I feel less crazy now.

**Comment by Icehole70** [comment]
Another idea would be to put a tag on the Whizbang decks or to make them look a little bit different from a normal constructed deck.

**Comment by beheh** [comment]
Hello, this behaviour will change with the next version of HDT as Whizbang decks will only be imported on-demand per-deck, once you start a game with Whizbang. So the old behaviour of a single Whizbang importing them all will go away.

Leaving this open until the next release has shipped.

**Comment by beheh** [comment]
The rework launched today in HDT v1.23.11!
