### ISSUE TITLE
HS Deck tracker update 12.2.0.26757

### ISSUE THREAD

**Issue by Doomelf** [HearthSim/Hearthstone-Deck-Tracker#3796]
After the tracker was updated for patch 12.2 it stopped tracking cards.

**Comment by chWolfgang** [comment]
I seem to have this issue as well. It selects the deck fine, but is not tracking cards.

**Comment by Doomelf** [comment]
Exactly the same behavior as in my tracker.

**Comment by Deventhor** [comment]
Same issue here. Tracker works as per usual up until entering into a match... at which point it detects and sets the correct deck as active, but after that... nothing. No detection of mulliganed cards, no highlighting what's in my hand, no hand/deck size updates. Just a static decklist.

Have gone through the suggested fixes (restarting, setting log.configs up, updating the game path, etc). Nothing has solved the issue.

**Comment by riQQ** [comment]
Please provide the HDT log corresponding to this problem. See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#hdt-log-files.

**Comment by cleeeeeeeeeetus** [comment]
I have been having the same issue as well.  Opponents' deck is not tracked, and neither are my cards (in terms of cards played/left to draw, etc.  I've attached my most recent HDT log.  Thanks in advance for the diligence. 

[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2444492/hdt_log.txt)

**Comment by azeier** [comment]
Thanks for the logs guys. I have a good idea what the issue is, let me see if I can reproduce it.

**Comment by Deventhor** [comment]
> 
> 
> Thanks for the logs guys. I have a good idea what the issue is, let me see if I can reproduce it.

You're a star, Azeier!

**Comment by cleeeeeeeeeetus** [comment]
> Thanks for the logs guys. I have a good idea what the issue is, let me see if I can reproduce it.

Happy to help.  Let us know if we can provide any other information!

**Comment by cleeeeeeeeeetus** [comment]
> Thanks for the logs guys. I have a good idea what the issue is, let me see if I can reproduce it.

Just a quick/minor update.  I uninstalled the live version of HDT and installed a previous version - 1.7.5 - and extracted the contents to a folder.  I ran "Hearthstone Deck Tracker.exe" as admin and everything works correctly as it used to.  

Just an observation.

**Comment by azeier** [comment]
I just released v1.7.7, which should fix this. Let me know if you still have any issues after updating (restarting will force an update).

**Comment by cleeeeeeeeeetus** [comment]
> I just released v1.7.7, which should fix this. Let me know if you still have any issues after updating (restarting will force an update).

Working as intended.  Thanks for the super quick fixes.

**Comment by Deventhor** [comment]
> 
> 
> > I just released v1.7.7, which should fix this. Let me know if you still have any issues after updating (restarting will force an update).
> 
> Working as intended. Thanks for the super quick fixes.

Confirmed. Once again, Azeier, you are a star!

**Comment by riQQ** [comment]
Fixed by https://github.com/HearthSim/HearthMirror/commit/13c46ec332d090112f8d1e6cc2efa59c31cf51cc
