### ISSUE TITLE
Deck Tracker stopped working after hitting Legend

### ISSUE THREAD

**Issue by Tr4cker** [HearthSim/Hearthstone-Deck-Tracker#3798]
Decktracker worked fine, then I hit Legend and it stopped tracking played cards/opponent's cards, and card marks/card age. Only the timer is still working. When I spectate someone everything is shown properly. Didn't change anything (except for downloading the latest update recently) and already tried resetting settings, client, game, etc. 

Any tips?

Cheers!

**Comment by azeier** [comment]
I released v1.7.7 about an hour ago to fix a bunch of deck tracking issues. Make sure you update to that.

If it still doesn't work with v1.7.7 please reproduce the issue once more and post the logs here. See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#hdt-log-files

**Comment by Tr4cker** [comment]
Thanks, didn't notice 1.7.7 was out. Going to sleep now but will retest tomorrow. Thanks for your fast response azeier!

**Comment by turbo0180** [comment]
I have this problem.

**Comment by TheCat93** [comment]
I have this problem mee too.

**Comment by azeier** [comment]
I can't do anything without logs. Please see my post above.

**Comment by replaythegame** [comment]
Same problem. "Decktracker worked fine, then I hit Legend and it stopped tracking played cards/opponent's cards, and card marks/card age."

[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2446747/hdt_log.txt)

**Comment by replaythegame** [comment]
> I can't do anything without logs. Please see my post above.
Same problem. "Decktracker worked fine, then I hit Legend and it stopped tracking played cards/opponent's cards, and card marks/card age."
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2446770/hdt_log.txt)

**Comment by replaythegame** [comment]
I tried to re-install 2 or 3 time but still doesn't fix..

**Comment by replaythegame** [comment]
> Thanks for the log!
> 
> Since I'm not close to legend currently I sadly can't test this myself.
> I'm fairly confident I fixed the issue from your log, @replaythegame, however I don't know whether there are more issues hiding underneath.
> 
> (Anyone with this problem) Please install this development build and let me know if you still have the same issue and include the log: https://github.com/HearthSim/HDT-dev-builds/releases/download/v1.7.7.3773/HDT-Installer.exe
> 
> This will just replace your current HDT installation (retain all config and stats) and automatically update to the next full release.

That's work ! Thanks a lot

**Comment by azeier** [comment]
Thanks for testing @replaythegame!

Rolling out v1.7.8 now. Let me know if there are more issues.

**Comment by Tr4cker** [comment]
@azeier Just got home from work, started deck tracker and saw the update/patch notes. Just wanted to thank you once more for the amazing support! Great work. *tips hat*
