### ISSUE TITLE
Deck Tracker stopped working after hitting Legend

### ISSUE THREAD

**Issue by donggiring** [HearthSim/Hearthstone-Deck-Tracker#3799]
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2445458/hdt_log.txt)
[hdt_log_1538640503.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2445459/hdt_log_1538640503.txt)

here is my log
 deck tracker stop

**Comment by TheCat93** [comment]
I have the same problem

**Comment by azeier** [comment]
Duplicate of #3798
