### ISSUE TITLE
When Tracking is played, discarded cards may be revealed by HDT

### ISSUE THREAD

**Issue by HugoKornelis** [HearthSim/Hearthstone-Deck-Tracker#3802]
### Expected Behavior
Opponent plays Tracking. List of opponent cards adds tracking (as played) but doesn't change afterwards.

### Actual Behavior
Opponent plays Tracking. List of opponent cards adds tracking (as played), but also reduces the number of Ambush cards left in opponent decks by one.

### Steps to reproduce behavior
Opponent plays Fal'Dorei Spider to shuffle three Spider Ambush! cards in their deck. These are shown by HDT in the opponent deck.
Opponent plays Tracking and one of the cards offered is a Spider Ambush!
HDT shows that number of Spider Ambush! remaining in opponent deck is reduced. I should not have this information.

### Log/Screenshots
https://hsreplay.net/replay/ofQwGZ8Au2c4g79rHdjKb3 (turn 9).
The replay does not show that the number of Spider Ambush! cards left in the opponent deck was lowered on my screen. However, it does show that HDT was able to "sniff" that one of the discarded cards was a Spider Ambush!

**Comment by ceceita** [comment]
this is a infoleak at hearthstone , but a fix on hdt can hide it .. 
I reported to blizzard in the past , i dont know why they dont want to fix it

**Comment by Jonysegal** [comment]
Unable to reproduce, possible Blizzard closed the data leak.
