### ISSUE TITLE
HDT crashes each time post game

### ISSUE THREAD

**Issue by fagnerffcs** [HearthSim/Hearthstone-Deck-Tracker#3812]
Log on HDT Folder

8:38:21 PM|Info|Core.Initialize >> HDT: 1.7.10.3778, Operating System: Windows 10 Home 17134, .NET Framework: 461808
8:38:21 PM|Info|Updater.StartupUpdateCheck >> Checking for updates
8:38:21 PM|Info|Updater.GetReleaseUrl >> Downloading releases file
8:38:23 PM|Info|Updater.GetReleaseUrl >> using 'live' release: https://github.com/HearthSim/HDT-Releases
8:38:29 PM|Info|Updater.SquirrelUpdate >> Checking for updates (ignoreDelta=False)
8:38:33 PM|Info|Updater.SquirrelUpdate >> No new updated available
8:38:33 PM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
8:38:34 PM|Info|ThemeManager.LoadThemes >> Found theme: classic
8:38:34 PM|Info|ThemeManager.LoadThemes >> Found theme: dark
8:38:34 PM|Info|ThemeManager.LoadThemes >> Found theme: frost
8:38:34 PM|Info|ThemeManager.LoadThemes >> Found theme: minimal
8:38:34 PM|Info|GameV2.Reset >> -------- Reset ---------
8:38:37 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
8:38:39 PM|Info|MainWindow.SelectDeck >> Switched to deck: Gaara Shudderwock (v1.2)
8:38:39 PM|Info|GameV2.Reset >> -------- Reset ---------
8:38:41 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
8:38:41 PM|Info|BackupManager.Run >> Running BackupManager
8:38:41 PM|Info|BackupManager.Run >> Backup for today already exists
8:38:41 PM|Info|PluginManager.LoadPluginsFromPath >> Loading Plugins...
8:38:41 PM|Info|Helper.GetCurrentRegion >> Region: US
8:38:41 PM|Info|BackupManager.Run >> Running BackupManager
8:38:41 PM|Info|BackupManager.Run >> Backup for today already exists
8:38:41 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
8:38:41 PM|Info|LogWatcherManager.Start >> Using Hearthstone log directory 'C:\Program Files (x86)\Hearthstone\Logs'
20:38:41|Info|LogWatcherManager.OnLogFileFound >> FullScreenFX
20:38:41|Info|LogWatcherManager.OnLogFileFound >> Rachelle
20:38:41|Info|LogWatcherManager.OnLogFileFound >> LoadingScreen
8:38:41 PM|Info|HSReplayNetOAuth.UpdateAccountData >> Updating account data...
20:38:41|Info|LogWatcherManager.OnLogFileFound >> Power
8:38:42 PM|Info|HsReplayDecks.Load >> Loaded from disk: Count=2393, ServerTS=11/1/2018 9:16:27 PM, Downloaded=11/1/2018 7:41:11 PM Age=00:57:30.6349562
8:38:42 PM|Info|HsReplayDecks.Load >> Complete: Count=2393, ServerTS=11/1/2018 9:16:27 PM, Downloaded=11/1/2018 7:41:11 PM Age=00:57:30.6359529
8:38:42 PM|Info|GameEventHandler.HandleGameStart >> --- Game start ---
8:38:42 PM|Info|GameV2.Reset >> -------- Reset ---------
8:38:42 PM|Info|GameV2.UpdatePlayers >> Fhighlander#1787 [PlayerId=2] vs Dopeassfuggd#1833 [PlayerId=1]
8:38:42 PM|Info|TurnTimer.Start >> Starting turn timer
8:38:42 PM|Warning|TurnTimer.Start >> Waiting for player entity
8:38:43 PM|Info|TagChangeActions.SetHeroAsync >> Found hero with id=64
8:38:43 PM|Info|GameEventHandler.SetOpponentHero >> Opponent=Shaman
8:38:43 PM|Info|TagChangeActions.SetHeroAsync >> Found hero with id=66
8:38:43 PM|Info|GameEventHandler.SetPlayerHero >> Player=Shaman
8:38:43 PM|Info|GameV2.CurrentMode >> GAMEPLAY
8:38:43 PM|Info|Player.Draw >> [Opponent] id=20, cardId=, cardName=, zonePos=0,Info={turn=0, originalZone=DECK, hidden=true, OriginalController=1}
8:38:43 PM|Info|Player.Draw >> [Opponent] id=5, cardId=, cardName=, zonePos=0,Info={turn=0, originalZone=DECK, hidden=true, OriginalController=1}
8:38:43 PM|Info|Player.Draw >> [Opponent] id=17, cardId=, cardName=, zonePos=0,Info={turn=0, originalZone=DECK, hidden=true, OriginalController=1}
8:38:43 PM|Info|Player.Draw >> [Player] id=46, cardId=LOOT_358, cardName=Grumble, Worldshaker, zonePos=1,Info={turn=0, originalZone=DECK, hasOutstandingTagChanges=true, OriginalController=2}
8:38:43 PM|Info|Player.Draw >> [Player] id=52, cardId=EX1_245, cardName=Earth Shock, zonePos=2,Info={turn=0, originalZone=DECK, hasOutstandingTagChanges=true, OriginalController=2}
8:38:43 PM|Info|Player.Draw >> [Player] id=57, cardId=GIL_622, cardName=Lifedrinker, zonePos=3,Info={turn=0, originalZone=DECK, hasOutstandingTagChanges=true, OriginalController=2}
8:38:43 PM|Info|Player.Draw >> [Player] id=35, cardId=UNG_025, cardName=Volcano, zonePos=4,Info={turn=0, originalZone=DECK, hasOutstandingTagChanges=true, OriginalController=2}
8:38:43 PM|Info|Player.CreateInHand >> [Player] id=68, cardId=GAME_005, cardName=The Coin, zonePos=5,Info={turn=0, mark=Coin, created=true, originalZone=HAND, hasOutstandingTagChanges=true, OriginalController=2}
8:38:43 PM|Info|HSReplayNetOAuth.UpdateAccountData >> Found account: Fhighlander#1787
8:38:43 PM|Info|HSReplayNetOAuth.UpdateTwitchUsers >> Fetching twitch accounts...
8:38:44 PM|Info|HSReplayNetOAuth.UpdateTwitchUsers >> Saved 0 account(s): 
8:38:59 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
8:39:12 PM|Info|Player.Draw >> [Opponent] id=4, cardId=, cardName=, zonePos=0,Info={turn=0, mark=Mulliganed, mulliganed=true, originalZone=DECK, OriginalController=1}
8:39:12 PM|Info|Player.Mulligan >> [Opponent] id=20, cardId=, cardName=, zonePos=0,Info={turn=0, originalZone=DECK, hidden=true, OriginalController=1}
8:39:12 PM|Info|Player.Draw >> [Opponent] id=15, cardId=, cardName=, zonePos=0,Info={turn=0, mark=Mulliganed, mulliganed=true, originalZone=DECK, OriginalController=1}
8:39:12 PM|Info|Player.Mulligan >> [Opponent] id=5, cardId=, cardName=, zonePos=0,Info={turn=0, originalZone=DECK, hidden=true, OriginalController=1}
8:39:17 PM|Info|Player.CreateInSetAside >> [Opponent] id=69, cardId=GIL_692e, cardName=Curse of Ur, zonePos=0,Info={turn=1, mark=Created, created=true, hasOutstandingTagChanges=true}
8:39:17 PM|Info|Player.CreateInPlay >> [Opponent] id=69, cardId=GIL_692e, cardName=Curse of Ur, zonePos=0,Info={turn=1, mark=Created, created=true, originalZone=PLAY, hasOutstandingTagChanges=true, OriginalController=1}
8:39:21 PM|Info|GameEventHandler.HandleTurnStart >> --- Opponent turn 1 ---
8:39:21 PM|Info|Player.Draw >> [Opponent] id=11, cardId=, cardName=, zonePos=0,Info={turn=1, originalZone=DECK, hidden=true, OriginalController=1}
8:39:28 PM|Info|GameEventHandler.HandleOpponentHeroPower >> OpponentHeroPower (id:CS2_049 turn:1 from:-1)
8:39:28 PM|Info|Player.CreateInPlay >> [Opponent] id=70, cardId=CS2_052, cardName=Wrath of Air Totem, zonePos=1,Info={turn=1, mark=Created, created=true, originalZone=PLAY, hasOutstandingTagChanges=true, OriginalController=1}
8:39:31 PM|Info|GameEventHandler.HandleTurnStart >> --- Player turn 1 ---
8:39:31 PM|Info|Player.Draw >> [Player] id=59, cardId=BOT_411, cardName=Electra Stormsurge, zonePos=6,Info={turn=1, originalZone=DECK, hasOutstandingTagChanges=true, OriginalController=2}
8:39:36 PM|Info|GameEventHandler.HandleTurnStart >> --- Opponent turn 2 ---
8:39:36 PM|Info|Player.Draw >> [Opponent] id=7, cardId=, cardName=, zonePos=0,Info={turn=2, originalZone=DECK, hidden=true, OriginalController=1}
8:39:39 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
8:39:42 PM|Info|Player.Play >> [Opponent] id=17, cardId=UNG_201, cardName=Primalfin Totem, zonePos=1,Info={turn=2, originalZone=DECK, hasOutstandingTagChanges=true, OriginalController=1}
8:39:45 PM|Info|Player.CreateInPlay >> [Opponent] id=72, cardId=UNG_201t, cardName=Primalfin, zonePos=2,Info={turn=2, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
8:39:47 PM|Info|GameEventHandler.HandleTurnStart >> --- Player turn 2 ---
8:39:47 PM|Info|Player.Draw >> [Player] id=62, cardId=EX1_245, cardName=Earth Shock, zonePos=7,Info={turn=2, originalZone=DECK, hasOutstandingTagChanges=true, OriginalController=2}
8:39:55 PM|Info|GameEventHandler.HandlePlayerHeroPower >> PlayerHeroPower (id:CS2_049 turn:2 from:-1)
8:39:55 PM|Info|Player.CreateInPlay >> [Player] id=73, cardId=CS2_050, cardName=Searing Totem, zonePos=1,Info={turn=2, mark=Created, created=true, originalZone=PLAY, OriginalController=2}
8:39:57 PM|Info|GameEventHandler.HandleTurnStart >> --- Opponent turn 3 ---
8:39:57 PM|Info|Player.Draw >> [Opponent] id=29, cardId=, cardName=, zonePos=0,Info={turn=3, originalZone=DECK, hidden=true, OriginalController=1}
8:40:05 PM|Info|GameEventHandler.HandleOpponentHeroPower >> OpponentHeroPower (id:CS2_049 turn:3 from:-1)
8:40:05 PM|Info|Player.CreateInPlay >> [Opponent] id=74, cardId=NEW1_009, cardName=Healing Totem, zonePos=4,Info={turn=3, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
8:40:11 PM|Info|Player.Play >> [Opponent] id=15, cardId=GIL_530, cardName=Murkspark Eel, zonePos=1,Info={turn=3, mark=Mulliganed, mulliganed=true, originalZone=DECK, hasOutstandingTagChanges=true, OriginalController=1}
8:40:16 PM|Info|Player.PlayToGraveyard >> [Player] id=73, cardId=CS2_050, cardName=Searing Totem, zonePos=0,Info={turn=3, mark=Created, created=true, originalZone=PLAY, OriginalController=2}
8:40:16 PM|Info|Player.CreateInPlay >> [Opponent] id=76, cardId=UNG_201t, cardName=Primalfin, zonePos=3,Info={turn=3, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
8:40:19 PM|Info|GameEventHandler.HandleTurnStart >> --- Player turn 3 ---
8:40:19 PM|Info|Player.Draw >> [Player] id=40, cardId=UNG_025, cardName=Volcano, zonePos=8,Info={turn=3, originalZone=DECK, hasOutstandingTagChanges=true, OriginalController=2}
8:40:27 PM|Info|Player.Play >> [Player] id=62, cardId=EX1_245, cardName=Earth Shock, zonePos=0,Info={turn=3, originalZone=DECK, OriginalController=2}
8:40:28 PM|Info|Player.PlayToGraveyard >> [Player] id=62, cardId=EX1_245, cardName=Earth Shock, zonePos=0,Info={turn=3, originalZone=DECK, OriginalController=2}
8:40:33 PM|Info|GameEventHandler.HandlePlayerHeroPower >> PlayerHeroPower (id:CS2_049 turn:3 from:-1)
8:40:33 PM|Info|Player.CreateInPlay >> [Player] id=78, cardId=CS2_052, cardName=Wrath of Air Totem, zonePos=1,Info={turn=3, mark=Created, created=true, originalZone=PLAY, hasOutstandingTagChanges=true, OriginalController=2}
8:40:36 PM|Info|GameEventHandler.HandleTurnStart >> --- Opponent turn 4 ---
8:40:36 PM|Info|Player.Draw >> [Opponent] id=33, cardId=, cardName=, zonePos=0,Info={turn=4, originalZone=DECK, hidden=true, OriginalController=1}
8:40:47 PM|Info|Player.PlayToGraveyard >> [Player] id=78, cardId=CS2_052, cardName=Wrath of Air Totem, zonePos=0,Info={turn=4, mark=Created, created=true, originalZone=PLAY, OriginalController=2}
8:40:48 PM|Info|Player.Play >> [Opponent] id=7, cardId=ICC_912, cardName=Corpsetaker, zonePos=1,Info={turn=4, originalZone=DECK, hasOutstandingTagChanges=true, OriginalController=1}
8:40:53 PM|Info|GameEventHandler.HandleTurnStart >> --- Player turn 4 ---
8:40:53 PM|Info|Player.Draw >> [Player] id=54, cardId=LOOT_373, cardName=Healing Rain, zonePos=8,Info={turn=4, originalZone=DECK, hasOutstandingTagChanges=true, OriginalController=2}
8:40:58 PM|Info|Player.Play >> [Player] id=68, cardId=GAME_005, cardName=The Coin, zonePos=0,Info={turn=4, mark=Coin, created=true, originalZone=HAND, OriginalController=2}
8:40:59 PM|Info|Player.PlayToGraveyard >> [Player] id=68, cardId=GAME_005, cardName=The Coin, zonePos=0,Info={turn=4, mark=Coin, created=true, originalZone=HAND, OriginalController=2}
8:41:01 PM|Info|Player.Play >> [Player] id=35, cardId=UNG_025, cardName=Volcano, zonePos=0,Info={turn=4, originalZone=DECK, OriginalController=2}
8:41:06 PM|Info|Player.PlayToGraveyard >> [Player] id=35, cardId=UNG_025, cardName=Volcano, zonePos=0,Info={turn=4, originalZone=DECK, OriginalController=2}
8:41:06 PM|Info|Player.PlayToGraveyard >> [Opponent] id=70, cardId=CS2_052, cardName=Wrath of Air Totem, zonePos=0,Info={turn=4, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
8:41:06 PM|Info|Player.PlayToGraveyard >> [Opponent] id=17, cardId=UNG_201, cardName=Primalfin Totem, zonePos=0,Info={turn=4, originalZone=DECK, OriginalController=1}
8:41:06 PM|Info|Player.PlayToGraveyard >> [Opponent] id=72, cardId=UNG_201t, cardName=Primalfin, zonePos=0,Info={turn=4, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
8:41:06 PM|Info|Player.PlayToGraveyard >> [Opponent] id=74, cardId=NEW1_009, cardName=Healing Totem, zonePos=0,Info={turn=4, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
8:41:06 PM|Info|Player.PlayToGraveyard >> [Opponent] id=76, cardId=UNG_201t, cardName=Primalfin, zonePos=0,Info={turn=4, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
8:41:06 PM|Info|Player.PlayToGraveyard >> [Opponent] id=7, cardId=ICC_912, cardName=Corpsetaker, zonePos=0,Info={turn=4, originalZone=DECK, OriginalController=1}
8:41:11 PM|Info|GameEventHandler.HandleTurnStart >> --- Opponent turn 5 ---
8:41:11 PM|Info|Player.Draw >> [Opponent] id=26, cardId=, cardName=, zonePos=0,Info={turn=5, originalZone=DECK, hidden=true, OriginalController=1}
8:41:19 PM|Info|GameEventHandler.HandleOpponentHeroPower >> OpponentHeroPower (id:CS2_049 turn:5 from:-1)
8:41:19 PM|Info|Player.CreateInPlay >> [Opponent] id=82, cardId=NEW1_009, cardName=Healing Totem, zonePos=2,Info={turn=5, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
8:41:20 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
8:41:24 PM|Info|Player.Play >> [Opponent] id=29, cardId=ICC_466, cardName=Saronite Chain Gang, zonePos=1,Info={turn=5, originalZone=DECK, hasOutstandingTagChanges=true, OriginalController=1}
8:41:26 PM|Info|Player.CreateInPlay >> [Opponent] id=84, cardId=ICC_466, cardName=Saronite Chain Gang, zonePos=2,Info={turn=5, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
8:41:28 PM|Info|GameEventHandler.HandleTurnStart >> --- Player turn 5 ---
8:41:28 PM|Info|Player.Draw >> [Player] id=41, cardId=LOOT_516, cardName=Zola the Gorgon, zonePos=7,Info={turn=5, originalZone=DECK, hasOutstandingTagChanges=true, OriginalController=2}
8:41:33 PM|Info|GameEventHandler.HandlePlayerHeroPower >> PlayerHeroPower (id:CS2_049 turn:5 from:-1)
8:41:33 PM|Info|Player.CreateInPlay >> [Player] id=85, cardId=NEW1_009, cardName=Healing Totem, zonePos=1,Info={turn=5, mark=Created, created=true, originalZone=PLAY, OriginalController=2}
8:41:38 PM|Info|GameEventHandler.HandleTurnStart >> --- Opponent turn 6 ---
8:41:38 PM|Info|Player.Draw >> [Opponent] id=9, cardId=, cardName=, zonePos=0,Info={turn=6, originalZone=DECK, hidden=true, OriginalController=1}
8:41:46 PM|Info|GameEventHandler.HandleOpponentHeroPower >> OpponentHeroPower (id:CS2_049 turn:6 from:-1)
8:41:46 PM|Info|Player.CreateInPlay >> [Opponent] id=86, cardId=CS2_050, cardName=Searing Totem, zonePos=5,Info={turn=6, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
8:41:49 PM|Info|Player.Play >> [Opponent] id=9, cardId=EX1_162, cardName=Dire Wolf Alpha, zonePos=3,Info={turn=6, originalZone=DECK, hasOutstandingTagChanges=true, OriginalController=1}
8:41:49 PM|Info|Player.CreateInSetAside >> [Opponent] id=88, cardId=EX1_162o, cardName=Strength of the Pack, zonePos=0,Info={turn=6, mark=Created, created=true, hasOutstandingTagChanges=true}
8:41:49 PM|Info|Player.CreateInPlay >> [Opponent] id=88, cardId=EX1_162o, cardName=Strength of the Pack, zonePos=0,Info={turn=6, mark=Created, created=true, originalZone=PLAY, hasOutstandingTagChanges=true, OriginalController=1}
8:41:49 PM|Info|Player.CreateInSetAside >> [Opponent] id=89, cardId=EX1_162o, cardName=Strength of the Pack, zonePos=0,Info={turn=6, mark=Created, created=true, hasOutstandingTagChanges=true}
8:41:49 PM|Info|Player.CreateInPlay >> [Opponent] id=89, cardId=EX1_162o, cardName=Strength of the Pack, zonePos=0,Info={turn=6, mark=Created, created=true, originalZone=PLAY, hasOutstandingTagChanges=true, OriginalController=1}
8:41:54 PM|Info|Player.Play >> [Opponent] id=33, cardId=EX1_586, cardName=Sea Giant, zonePos=1,Info={turn=6, originalZone=DECK, hasOutstandingTagChanges=true, OriginalController=1}
8:41:58 PM|Info|Player.PlayToGraveyard >> [Player] id=85, cardId=NEW1_009, cardName=Healing Totem, zonePos=0,Info={turn=6, mark=Created, created=true, originalZone=PLAY, OriginalController=2}
8:42:03 PM|Info|GameEventHandler.HandleTurnStart >> --- Player turn 6 ---
8:42:03 PM|Info|Player.Draw >> [Player] id=56, cardId=ICC_466, cardName=Saronite Chain Gang, zonePos=8,Info={turn=6, originalZone=DECK, hasOutstandingTagChanges=true, OriginalController=2}
8:42:12 PM|Info|Player.Play >> [Player] id=40, cardId=UNG_025, cardName=Volcano, zonePos=0,Info={turn=6, originalZone=DECK, OriginalController=2}
8:42:17 PM|Info|Player.PlayToGraveyard >> [Player] id=40, cardId=UNG_025, cardName=Volcano, zonePos=0,Info={turn=6, originalZone=DECK, OriginalController=2}
8:42:18 PM|Info|Player.PlayToGraveyard >> [Opponent] id=82, cardId=NEW1_009, cardName=Healing Totem, zonePos=0,Info={turn=6, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
8:42:18 PM|Info|Player.PlayToGraveyard >> [Opponent] id=29, cardId=ICC_466, cardName=Saronite Chain Gang, zonePos=0,Info={turn=6, originalZone=DECK, OriginalController=1}
8:42:18 PM|Info|Player.PlayToGraveyard >> [Opponent] id=84, cardId=ICC_466, cardName=Saronite Chain Gang, zonePos=0,Info={turn=6, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
8:42:18 PM|Info|Player.RemoveFromPlay >> [Player] id=88, cardId=EX1_162o, cardName=Strength of the Pack, zonePos=0,Info={turn=6, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
8:42:18 PM|Info|Player.PlayToGraveyard >> [Opponent] id=86, cardId=CS2_050, cardName=Searing Totem, zonePos=0,Info={turn=6, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
8:42:18 PM|Info|Player.CreateInSetAside >> [Opponent] id=92, cardId=EX1_162o, cardName=Strength of the Pack, zonePos=0,Info={turn=6, mark=Created, created=true, hasOutstandingTagChanges=true}
8:42:18 PM|Info|Player.CreateInPlay >> [Opponent] id=92, cardId=EX1_162o, cardName=Strength of the Pack, zonePos=0,Info={turn=6, mark=Created, created=true, originalZone=PLAY, hasOutstandingTagChanges=true, OriginalController=1}
8:42:18 PM|Warning|TagChangeActions.ZoneChangeFromOther >> unhandled zone change (id=88): 5 -> 4
8:42:22 PM|Info|Player.Play >> [Player] id=52, cardId=EX1_245, cardName=Earth Shock, zonePos=0,Info={turn=6, originalZone=DECK, OriginalController=2}
8:42:22 PM|Info|Player.PlayToGraveyard >> [Opponent] id=92, cardId=EX1_162o, cardName=Strength of the Pack, zonePos=0,Info={turn=6, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
8:42:22 PM|Info|Player.PlayToGraveyard >> [Opponent] id=89, cardId=EX1_162o, cardName=Strength of the Pack, zonePos=0,Info={turn=6, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
8:42:23 PM|Info|Player.PlayToGraveyard >> [Player] id=52, cardId=EX1_245, cardName=Earth Shock, zonePos=0,Info={turn=6, originalZone=DECK, OriginalController=2}
8:42:24 PM|Info|Player.PlayToGraveyard >> [Opponent] id=9, cardId=EX1_162, cardName=Dire Wolf Alpha, zonePos=0,Info={turn=6, originalZone=DECK, OriginalController=1}
8:42:27 PM|Info|GameEventHandler.HandleTurnStart >> --- Opponent turn 7 ---
8:42:27 PM|Info|Player.Draw >> [Opponent] id=23, cardId=, cardName=, zonePos=0,Info={turn=7, originalZone=DECK, hidden=true, OriginalController=1}
8:42:33 PM|Info|GameEventHandler.HandleOpponentHeroPower >> OpponentHeroPower (id:CS2_049 turn:7 from:-1)
8:42:33 PM|Info|Player.CreateInPlay >> [Opponent] id=94, cardId=NEW1_009, cardName=Healing Totem, zonePos=3,Info={turn=7, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
8:42:38 PM|Info|Player.Play >> [Opponent] id=4, cardId=EX1_067, cardName=Argent Commander, zonePos=1,Info={turn=7, mark=Mulliganed, mulliganed=true, originalZone=DECK, hasOutstandingTagChanges=true, OriginalController=1}
8:42:48 PM|Info|GameEventHandler.HandleTurnStart >> --- Player turn 7 ---
8:42:48 PM|Info|Player.Draw >> [Player] id=49, cardId=EX1_575, cardName=Mana Tide Totem, zonePos=7,Info={turn=7, originalZone=DECK, hasOutstandingTagChanges=true, OriginalController=2}
8:42:52 PM|Info|Player.Play >> [Player] id=54, cardId=LOOT_373, cardName=Healing Rain, zonePos=0,Info={turn=7, originalZone=DECK, OriginalController=2}
8:42:57 PM|Info|Player.PlayToGraveyard >> [Player] id=54, cardId=LOOT_373, cardName=Healing Rain, zonePos=0,Info={turn=7, originalZone=DECK, OriginalController=2}
8:42:57 PM|Info|GameEventHandler.HandlePlayerHeroPower >> PlayerHeroPower (id:CS2_049 turn:7 from:-1)
8:42:57 PM|Info|Player.CreateInPlay >> [Player] id=97, cardId=NEW1_009, cardName=Healing Totem, zonePos=1,Info={turn=7, mark=Created, created=true, originalZone=PLAY, OriginalController=2}
8:42:59 PM|Info|GameEventHandler.HandleTurnStart >> --- Opponent turn 8 ---
8:42:59 PM|Info|Player.Draw >> [Opponent] id=19, cardId=, cardName=, zonePos=0,Info={turn=8, originalZone=DECK, hidden=true, OriginalController=1}
8:43:13 PM|Info|GameEventHandler.HandleOpponentHeroPower >> OpponentHeroPower (id:CS2_049 turn:8 from:-1)
8:43:13 PM|Info|Player.CreateInPlay >> [Opponent] id=98, cardId=CS2_050, cardName=Searing Totem, zonePos=5,Info={turn=8, mark=Created, created=true, originalZone=PLAY, OriginalController=1}
8:43:14 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
8:43:16 PM|Info|Player.Play >> [Opponent] id=11, cardId=GIL_586, cardName=Earthen Might, zonePos=0,Info={turn=8, originalZone=DECK, hasOutstandingTagChanges=true, OriginalController=1}
8:43:17 PM|Info|Player.CreateInSetAside >> [Opponent] id=100, cardId=GIL_586e, cardName=Storm Hardened, zonePos=0,Info={turn=8, mark=Created, created=true, hasOutstandingTagChanges=true}
8:43:17 PM|Info|Player.CreateInPlay >> [Opponent] id=100, cardId=GIL_586e, cardName=Storm Hardened, zonePos=0,Info={turn=8, mark=Created, created=true, originalZone=PLAY, hasOutstandingTagChanges=true, OriginalController=1}
8:43:17 PM|Info|Player.PlayToGraveyard >> [Opponent] id=11, cardId=GIL_586, cardName=Earthen Might, zonePos=0,Info={turn=8, originalZone=DECK, OriginalController=1}
8:43:23 PM|Info|Player.Play >> [Opponent] id=26, cardId=EX1_586, cardName=Sea Giant, zonePos=1,Info={turn=8, originalZone=DECK, hasOutstandingTagChanges=true, OriginalController=1}
8:43:28 PM|Info|GameEventHandler.HandleTurnStart >> --- Player turn 8 ---
8:43:28 PM|Info|Player.Draw >> [Player] id=34, cardId=GIL_581, cardName=Sandbinder, zonePos=7,Info={turn=8, originalZone=DECK, hasOutstandingTagChanges=true, OriginalController=2}
8:43:59 PM|Info|GameEventHandler.HandleLoss >> --- Game was lost! ---
8:43:59 PM|Info|TurnTimer.Stop >> Stopping turn timer
8:43:59 PM|Info|GameEventHandler.HandleGameEnd >> Game ended...
8:44:00 PM|Info|GameEventHandler.HandleGameEnd >> Format: Standard
8:44:00 PM|Info|GameStats.GameEnd >> Current Game ended after 8 turns
8:44:00 PM|Info|GameEventHandler.HandleGameEnd >> Assigned current game to deck: Gaara Shudderwock
8:44:00 PM|Info|GameEventHandler.LogIsComplete >> GOLD_REWARD_STATE not found
8:44:00 PM|Info|LogUploader.Upload >> Uploading -703895119...
8:44:00 PM|Info|LogUploader.TryUpload >> Creating upload request...
8:44:03 PM|Info|LogUploader.TryUpload >> Upload Id: 9DV3XZSovwZ8PMU7ypp9oZ
8:44:07 PM|Info|LogUploader.TryUpload >> Upload complete
8:44:07 PM|Info|LogUploader.Upload >> -703895119 complete. Success=True
8:44:11 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
8:44:15 PM|Info|GameV2.CurrentMode >> TOURNAMENT
8:44:15 PM|Info|DeckImporter.FromConstructed >> Found 14 decks, 0 new
8:44:15 PM|Info|GameEventHandler.HandleInMenu >> Game is now in menu.
8:44:15 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.
8:44:15 PM|Info|GameEventHandler.SaveAndUpdateStats >> Saving DeckStats
8:44:16 PM|Info|OverlayWindow.SetTopmost >> Overlay is topmost after 1 tries.

Event Viewer on Windows 10 shows me this:
HearthstoneDeckTracker.exe version 1.7.10.3778 stopped working and it was closed...
 ID do Processo: a050
 Hora de Início: 01d4723bf8f465de
 Hora de Término: 6
 Caminho do Aplicativo: USER_DATA\AppData\Local\HearthstoneDeckTracker\app-1.7.10\HearthstoneDeckTracker.exe
 ID do Relatório: ccf9b4ab-9203-4406-89c5-e510ac36b0a9
 Nome completo do pacote com falha: 
 ID do aplicativo relativo ao pacote com falha:

**Comment by riQQ** [comment]
Is there another event in the windows event logs? This one doesn't contain the infos I need.

**Comment by fagnerffcs** [comment]
> Is there another event in the windows event logs? This one doesn't contain the infos I need.

No entry related to .NET Framework.

**Comment by riQQ** [comment]
Could you post a screenshot of the entry, you copied above? Is there any more information?

**Comment by fagnerffcs** [comment]
After Windows update, the problem was solved o.o
