### ISSUE TITLE
Use HDT API to prevent Hearthstone from logoff due AFK ?

### ISSUE THREAD

**Issue by ElektroStudios** [HearthSim/Hearthstone-Deck-Tracker#3814]
Hi. Sorry but I don't know where to ask this.

I'm not experienced with HDT API, but recently I've developed a simple .NET project on which I use **HDT's HearthMirror** API to alert me when I receive a Friend Challenge (and a _80 Gold Challenge_, which is not implemented in HearthMirror).

Now I would like to know whether **HDT** API provides something to prevent Hearthstone from finishing the game session due AFK. You know, after 30 minutes without touching the Hearthstone screen (better said, without touching a button in-game), it automatically logs off due in-game inactivity.

I ask this, because it is very known that a specific popular bot for Hearthstone is capable to prevent this, then, I wonder whether **HDT** API provides a public member/method to do this, or whether it can be provided in the future, or whether someone could guide me in the right direction to achieve this by myself.

Well, the thing is that some people like me could need to stay always connected to the game, regardless of whether we are inactive for more than 30 minutes, and of course I do not want to use and to pay for said bot only to be able to achieve this.

Please note that this kind of functionality couldn't be considered against **Blizzard**'s EULA, it would be a functionality that would not give me any advantage or trick against other players, just an helper tool to stay connected to the game regardless of the internal inactivity timer of the game.

I don't get how that said bot avoids the IDLE timer, it's apparently clear that said bot sends a kind of awake signal to the hearthstone process, but how it does?. I also thought about handling the **WM_ENTERIDLE** window message of the window procedure (**WndProc**) of Hearthstone process, but not sure how to do it "safely" (read: within **Blizzard** EULA) and anyway reading the **Microsoft** docs it seem that window message is not helpful to prevent IDLE state, but to do the opposite thing, and I don't see that exists any window message like "WM_EXITIDLE".

Thanks for read.

**Comment by riQQ** [comment]
Right now there is no way to do this via the HDT API and i doubt there will be a way, because this is borderline imo.

You should be able to programatically input keyboard / mouse events to Hearthstone via C#.

**Comment by azeier** [comment]
I agree this is pretty borderline and we won't support it, sorry.

**Comment by ElektroStudios** [comment]
It's ok, thank you both for answers.
