### ISSUE TITLE
Deck not having its STATS updated as it should be.

### ISSUE THREAD

**Issue by Tike22** [HearthSim/Hearthstone-Deck-Tracker#3815]
## Bug report
If this problem was already fixed please direct me.
### Expected Behavior
I go to the STATS to just to check up on a specific deck to see how i'm doing as getting more games in.

### Actual Behavior
STATS screen is barely updating, I say barely because at one point it actually added some wins and losses, but it's still not up to date

### Log/Screenshots

![hdt 1](https://user-images.githubusercontent.com/38795270/48045709-76701600-e15f-11e8-834a-1a0381e1b86c.PNG)
![hdt 2](https://user-images.githubusercontent.com/38795270/48045713-7a039d00-e15f-11e8-98cf-eca4ae26abc2.PNG)

**Comment by riQQ** [comment]
Filtering issue
