### ISSUE TITLE
Daily win tracker

### ISSUE THREAD

**Issue by rakudeb** [HearthSim/Hearthstone-Deck-Tracker#3819]
The daily win tracker on the main menu is not working anymore since the last update earlier this week.

**Comment by riQQ** [comment]
Duplicate of #3816

**Comment by rakudeb** [comment]
Aah I suck so much at searching, I swear I spent like 10 minutes wondering if it was just me because I couldn't find any recent post of this problem. Thanks for the help, keep going ! Cheers.

**Comment by riQQ** [comment]
No worries, for the next time: usually opening the closed issues and checking the last 10 should be enough to find a recent issue.
