### ISSUE TITLE
Copyright issues about images

### ISSUE THREAD

**Issue by agneng** [HearthSim/Hearthstone-Deck-Tracker#3824]
Hi
I am trying to develop desktop application like "Hearthstone-Deck-Tracker" for Warcraft III.
I need to use some icons/images from the game. Project will be free and open source. I want to ask how "Hearthstone-Deck-Tracker" received permission to use images from Hearthstone.
Are they free to use for non-commercial and open source projects ?

**Comment by agneng** [comment]
Well , class icons and card images are great example for that. Deck tracker using class icons and card images from Hearthstone.

**Comment by riQQ** [comment]
http://us.blizzard.com/en-us/company/about/legal-faq.html
https://www.reddit.com/r/hearthstone/comments/3sttta/blizzard_hearthstone_and_copyright/

**Comment by agneng** [comment]
Thanks 👍
