### ISSUE TITLE
HDT doesn't launch since version 1.7.8

### ISSUE THREAD

**Issue by orphangg** [HearthSim/Hearthstone-Deck-Tracker#3828]
### Expected Behavior
Launch latest HDT version (1.7.12)

### Actual Behavior
After installing and clicking on Hearthstone Deck Tracker.exe, nothing happens

### Log/Screenshots

[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2617166/hdt_log.txt)
[hdt_log_1543262047.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2617168/hdt_log_1543262047.txt)

Here are two logs. The first one when I want to launch ver 1.7.12. The second one when I launch ver 1.7.8

Thanks for your help !

**Comment by riQQ** [comment]
@orphangg is there anything in the Windows event log? (https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#windows-log-files)

**Comment by orphangg** [comment]
IN .NET RUNTIME
- 11/26/18 at 8:49:26 PM

> Application : Hearthstone Deck Tracker.exe
> Version du Framework : v4.0.30319
> Description : le processus a été arrêté en raison d'une exception non gérée.
> Informations sur l'exception : System.IO.DirectoryNotFoundException
>    à System.IO.__Error.WinIOError(Int32, System.String)
>    à System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
>    à System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare)
>    à MS.Internal.AppModel.SiteOfOriginPart.HandleFileSource(Boolean)
>    à MS.Internal.AppModel.SiteOfOriginPart.GetStreamAndSetContentType(Boolean)
>    à MS.Internal.AppModel.SiteOfOriginPart.GetStreamCore(System.IO.FileMode, System.IO.FileAccess)
>    à System.IO.Packaging.PackagePart.GetStream(System.IO.FileMode, System.IO.FileAccess)
>    à System.IO.Packaging.PackWebResponse+CachedResponse.GetResponseStream()
>    à System.IO.Packaging.PackWebResponse.GetResponseStream()
>    à System.IO.Packaging.PackWebResponse.get_ContentType()
>    à System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(System.Uri, System.IO.Stream, System.Windows.Media.Imaging.BitmapCacheOption, System.Guid ByRef, Boolean ByRef, System.IO.Stream ByRef, System.IO.UnmanagedMemoryStream ByRef, Microsoft.Win32.SafeHandles.SafeFileHandle ByRef)
>    à System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(System.Uri, System.Uri, System.IO.Stream, System.Windows.Media.Imaging.BitmapCreateOptions, System.Windows.Media.Imaging.BitmapCacheOption, System.Net.Cache.RequestCachePolicy, Boolean)
>    à System.Windows.Media.Imaging.BitmapFrame.CreateFromUriOrStream(System.Uri, System.Uri, System.IO.Stream, System.Windows.Media.Imaging.BitmapCreateOptions, System.Windows.Media.Imaging.BitmapCacheOption, System.Net.Cache.RequestCachePolicy)
>    à System.Windows.Media.ImageSourceConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext, System.Globalization.CultureInfo, System.Object)
>    à MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateObjectWithTypeConverter(MS.Internal.Xaml.ServiceProviderContext, System.Xaml.Schema.XamlValueConverter`1<System.ComponentModel.TypeConverter>, System.Object)
>    à MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateFromValue(MS.Internal.Xaml.ServiceProviderContext, System.Xaml.Schema.XamlValueConverter`1<System.ComponentModel.TypeConverter>, System.Object, System.Xaml.XamlMember)
>    à MS.Internal.Xaml.Runtime.PartialTrustTolerantRuntime.CreateFromValue(MS.Internal.Xaml.ServiceProviderContext, System.Xaml.Schema.XamlValueConverter`1<System.ComponentModel.TypeConverter>, System.Object, System.Xaml.XamlMember)
>    à System.Xaml.XamlObjectWriter.Logic_CreateFromValue(MS.Internal.Xaml.Context.ObjectWriterContext, System.Xaml.Schema.XamlValueConverter`1<System.ComponentModel.TypeConverter>, System.Object, System.Xaml.XamlMember, System.String, MS.Internal.Xaml.Runtime.IAddLineInfo)
> 
> Informations sur l'exception : System.Windows.Markup.XamlParseException
>    à System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
>    à System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
>    à System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
>    à System.Windows.Application.LoadComponent(System.Object, System.Uri)
>    à Hearthstone_Deck_Tracker.App.InitializeComponent()
>    à Hearthstone_Deck_Tracker.App.Main()

- 11/26/18 at 8:49:51 PM

> Application : Hearthstone Deck Tracker.exe
> Version du Framework : v4.0.30319
> Description : le processus a été arrêté en raison d'une exception non gérée.
> Informations sur l'exception : System.IO.DirectoryNotFoundException
>    à System.IO.__Error.WinIOError(Int32, System.String)
>    à System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
>    à System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare)
>    à MS.Internal.AppModel.SiteOfOriginPart.HandleFileSource(Boolean)
>    à MS.Internal.AppModel.SiteOfOriginPart.GetStreamAndSetContentType(Boolean)
>    à MS.Internal.AppModel.SiteOfOriginPart.GetStreamCore(System.IO.FileMode, System.IO.FileAccess)
>    à System.IO.Packaging.PackagePart.GetStream(System.IO.FileMode, System.IO.FileAccess)
>    à System.IO.Packaging.PackWebResponse+CachedResponse.GetResponseStream()
>    à System.IO.Packaging.PackWebResponse.GetResponseStream()
>    à System.IO.Packaging.PackWebResponse.get_ContentType()
>    à System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(System.Uri, System.IO.Stream, System.Windows.Media.Imaging.BitmapCacheOption, System.Guid ByRef, Boolean ByRef, System.IO.Stream ByRef, System.IO.UnmanagedMemoryStream ByRef, Microsoft.Win32.SafeHandles.SafeFileHandle ByRef)
>    à System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(System.Uri, System.Uri, System.IO.Stream, System.Windows.Media.Imaging.BitmapCreateOptions, System.Windows.Media.Imaging.BitmapCacheOption, System.Net.Cache.RequestCachePolicy, Boolean)
>    à System.Windows.Media.Imaging.BitmapFrame.CreateFromUriOrStream(System.Uri, System.Uri, System.IO.Stream, System.Windows.Media.Imaging.BitmapCreateOptions, System.Windows.Media.Imaging.BitmapCacheOption, System.Net.Cache.RequestCachePolicy)
>    à System.Windows.Media.ImageSourceConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext, System.Globalization.CultureInfo, System.Object)
>    à MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateObjectWithTypeConverter(MS.Internal.Xaml.ServiceProviderContext, System.Xaml.Schema.XamlValueConverter`1<System.ComponentModel.TypeConverter>, System.Object)
>    à MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateFromValue(MS.Internal.Xaml.ServiceProviderContext, System.Xaml.Schema.XamlValueConverter`1<System.ComponentModel.TypeConverter>, System.Object, System.Xaml.XamlMember)
>    à MS.Internal.Xaml.Runtime.PartialTrustTolerantRuntime.CreateFromValue(MS.Internal.Xaml.ServiceProviderContext, System.Xaml.Schema.XamlValueConverter`1<System.ComponentModel.TypeConverter>, System.Object, System.Xaml.XamlMember)
>    à System.Xaml.XamlObjectWriter.Logic_CreateFromValue(MS.Internal.Xaml.Context.ObjectWriterContext, System.Xaml.Schema.XamlValueConverter`1<System.ComponentModel.TypeConverter>, System.Object, System.Xaml.XamlMember, System.String, MS.Internal.Xaml.Runtime.IAddLineInfo)
> 
> Informations sur l'exception : System.Windows.Markup.XamlParseException
>    à System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
>    à System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
>    à System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
>    à System.Windows.Application.LoadComponent(System.Object, System.Uri)
>    à Hearthstone_Deck_Tracker.App.InitializeComponent()
>    à Hearthstone_Deck_Tracker.App.Main()

**Comment by orphangg** [comment]
IN APPLICATION ERROR

- 11/26/18 at 8:49:27 PM

> Nom de l’application défaillante Hearthstone Deck Tracker.exe, version : 1.7.12.3781, horodatage : 0x5be9990c
> Nom du module défaillant : KERNELBASE.dll, version : 10.0.17134.407, horodatage : 0xade8d4fe
> Code d’exception : 0xe0434352
> Décalage d’erreur : 0x00111812
> ID du processus défaillant : 0x188
> Heure de début de l’application défaillante : 0x01d485c122b2517b
> Chemin d’accès de l’application défaillante : C:\Download\Hearthstone.Deck.Tracker-v1.7.12\Hearthstone Deck Tracker.exe
> Chemin d’accès du module défaillant: C:\WINDOWS\System32\KERNELBASE.dll
> ID de rapport : 8b865117-79c1-4e8e-a4a3-2b2b8027ceef
> Nom complet du package défaillant : 
> 

- 11/26/18 at 8:49:51 PM

> Nom de l’application défaillante Hearthstone Deck Tracker.exe, version : 1.7.12.3781, horodatage : 0x5be9990c
> Nom du module défaillant : KERNELBASE.dll, version : 10.0.17134.407, horodatage : 0xade8d4fe
> Code d’exception : 0xe0434352
> Décalage d’erreur : 0x00111812
> ID du processus défaillant : 0x1cb4
> Heure de début de l’application défaillante : 0x01d485c132078276
> Chemin d’accès de l’application défaillante : C:\Download\Hearthstone.Deck.Tracker-v1.7.12\Hearthstone Deck Tracker.exe
> Chemin d’accès du module défaillant: C:\WINDOWS\System32\KERNELBASE.dll
> ID de rapport : 47b34611-c665-4cb9-9688-0104d5a80ebb
> Nom complet du package défaillant : 
>

**Comment by orphangg** [comment]
I currently use the ver. 1.7.8 downloaded from github. No later version works.

**Comment by riQQ** [comment]
It looks like you didn't extract the zip properly.

**Comment by orphangg** [comment]
Sorry, the answer is very late. I unzipped with default options and it worked perfectly with ver. 1.7.13.
Thanks a lot for time wasted for me =)
