### ISSUE TITLE
HDT doesn't work after installing a fresh copy of WIN10

### ISSUE THREAD

**Issue by andr3wbfox** [HearthSim/Hearthstone-Deck-Tracker#3829]
### Log/Screenshots
[hdt_log_1542131402.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620541/hdt_log_1542131402.txt)
[hdt_log_1542131485.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620542/hdt_log_1542131485.txt)
[hdt_log_1542132016.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620543/hdt_log_1542132016.txt)
[hdt_log_1542132776.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620544/hdt_log_1542132776.txt)
[hdt_log_1542132885.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620545/hdt_log_1542132885.txt)
[hdt_log_1542134676.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620546/hdt_log_1542134676.txt)
[hdt_log_1542134784.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620547/hdt_log_1542134784.txt)
[hdt_log_1542136585.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620548/hdt_log_1542136585.txt)
[hdt_log_1542192048.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620549/hdt_log_1542192048.txt)
[hdt_log_1542194020.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620550/hdt_log_1542194020.txt)
[hdt_log_1542382351.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620551/hdt_log_1542382351.txt)
[hdt_log_1542472349.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620552/hdt_log_1542472349.txt)
[hdt_log_1542555607.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620553/hdt_log_1542555607.txt)
[hdt_log_1542625109.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620554/hdt_log_1542625109.txt)
[hdt_log_1542625305.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620555/hdt_log_1542625305.txt)
[hdt_log_1542717467.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620556/hdt_log_1542717467.txt)
[hdt_log_1543143764.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620557/hdt_log_1543143764.txt)
[hdt_log_1543151263.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620558/hdt_log_1543151263.txt)
[hdt_log_1543155007.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620559/hdt_log_1543155007.txt)
[hdt_log_1543156808.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620561/hdt_log_1543156808.txt)
[hdt_log_1543157928.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620562/hdt_log_1543157928.txt)
[hdt_log_1543161577.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620563/hdt_log_1543161577.txt)
[hdt_log_1543238983.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620564/hdt_log_1543238983.txt)
[hdt_log_1543258412.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620565/hdt_log_1543258412.txt)
[hdt_log_1543312792.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620566/hdt_log_1543312792.txt)
[hdt_log_1543312976.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620567/hdt_log_1543312976.txt)
[hdt_log_1543322528.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620568/hdt_log_1543322528.txt)
[hdt_log_1543324554.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620569/hdt_log_1543324554.txt)
[hdt_log_1543327395.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620570/hdt_log_1543327395.txt)
[hdt_log_1543329307.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620571/hdt_log_1543329307.txt)
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620572/hdt_log.txt)
[hdt_log_1542127325.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620573/hdt_log_1542127325.txt)
[hdt_log_1542127372.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620574/hdt_log_1542127372.txt)
[hdt_log_1542127515.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620575/hdt_log_1542127515.txt)
[hdt_log_1542128024.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620576/hdt_log_1542128024.txt)
[hdt_log_1542129970.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2620577/hdt_log_1542129970.txt)

**Comment by azeier** [comment]
This is being handled elsewhere.
