### ISSUE TITLE
Whizbang ruins my decktracker

### ISSUE THREAD

**Issue by Nudnud9** [HearthSim/Hearthstone-Deck-Tracker#3831]
Bug report

Expected Behaviour
I expected the deck tracker to automatically assign the correct whizbang deck and display it correctly.

Actual Behaviour
It glitches out, it keeps showing the seen/drawn cards but it keeps appearing/disappearing constantly. drops fps.

Steps to reproduce behaviour
this is consistently happening but ONLY with whizbang, when i use any other deck it works perfectly. i tried many things and i cant fix it.

please help...

**Comment by azeier** [comment]
This is probably an issue with the latest hearthstone patch and will fix itself once the expansion is released. HDT automatically detects which possible decks whizbang *should* have (the recipes), however the majority of these decks currently contain cards from the new expansion and blizzard added a temporary serverside override.

**Comment by Nudnud9** [comment]
this is weird because the decktracker works for my friends, but if you say it'll be fixed when the expansion comes out i'll believe you. thanks :)

**Comment by hurryupweredreaming** [comment]
Any updates?

**Comment by Nudnud9** [comment]
it still doesnt work with whizbang...

**Comment by hurryupweredreaming** [comment]
Now it works for me

**Comment by Nudnud9** [comment]
damn...why's it always gotta be me

**Comment by riQQ** [comment]
Post the log file please: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#hdt-log-files

**Comment by Nudnud9** [comment]
nvm i know why it happens...

**Comment by riQQ** [comment]
Would you please share what you found out. Thank you.

**Comment by Barragek0** [comment]
This is happening for me still
