### ISSUE TITLE
Spirit of the Dead copies don't show in deck tracker

### ISSUE THREAD

**Issue by bigyihsuan** [HearthSim/Hearthstone-Deck-Tracker#3841]
### Expected Behavior
Copies created by Spirit of the Dead should show up in the tracker for my deck with a gift icon.

### Actual Behavior
Copies from Spirit of the Dead do not show up, even though they exist.

### Steps to reproduce behavior
1. Play Spirit of the Dead.
2. Kill a friendly minion. The copy will not show up in the tracker.

### Log/Screenshots
Right before Spirit procs. There is a Dead Ringer on board, and another in deck:
![](https://i.imgur.com/j3mMS04.jpg)

After Spirit procs. I draw the other Dead Ringer (2 mana in hand), but the copy does not appear as a gift in the tracker:
![](https://i.imgur.com/MZkeTuc.jpg)

**Comment by bigyihsuan** [comment]
I'd also like to note that if you draw the copy from the Spirit, it shows up in the tracker as a gift.

**Comment by trebonius0** [comment]
This is still not fixed :/

**Comment by bigyihsuan** [comment]
Perhaps this is similar to that bug with Elekk and the currently fixed interactions?
