### ISSUE TITLE
Overlay misaligned / sections cut off

### ISSUE THREAD

**Issue by DoctorRye** [HearthSim/Hearthstone-Deck-Tracker#3844]
### Expected Behavior
Overlay to be moved freely when unlocked

### Actual Behavior
1. Default position of overlay appears to be set to a different monitor resolution. 
2. There appearss to be a cut off point on the right where parts of the overlay are hidden when moved past a certain point.
3. The numbers which track the turn a card was drawn on are misaligned and cannot be moved

### Steps to reproduce behavior
I have a laptop connected to a second monitor (on which I play hearthstone). I have tried changing which monitor (i.e. my laptop screen or my monitor) is my main via display settings but this does not help. 

### Log/Screenshots
![7595210bb6b236976ae8a1f9ea261f6a](https://user-images.githubusercontent.com/3404787/50384348-0b08e600-06c4-11e9-890f-3716e8c94509.jpg)

**Comment by riQQ** [comment]
Can you check if this is the same issue as #3445 for you?
