### ISSUE TITLE
Snipe is still excluded from Arena

### ISSUE THREAD

**Issue by pisq** [HearthSim/Hearthstone-Deck-Tracker#3849]
### Expected Behavior
Snipe should be listed when opponent Hunter plays a Secret

### Actual Behavior
Snipe is not listed among possible Secrets

**Comment by junsix** [comment]
https://playhearthstone.com/en-us/blog/22835076/arena-updates-december-19-2018

If you see this blog, you can check that the snipe is banned in arena.

**Comment by dunlapm** [comment]
According to that article, snipe is listed as allowed in arena.

> The following cards are once again available in Arena picks

**Comment by riQQ** [comment]
Fixed by #3860
