### ISSUE TITLE
Wrong secret prediction: Misdirection is erroneously greyed out

### ISSUE THREAD

**Issue by antiphp** [HearthSim/Hearthstone-Deck-Tracker#3850]
In the last game there was a wrong secret prediction.

### Expected Behavior
Show misdirection secret

### Actual Behavior
It predicted rat trap which was false

[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2717215/hdt_log.txt)
[iWejVuXKFnfjUE4Z74ubtF.hsreplay.xml.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/2717217/iWejVuXKFnfjUE4Z74ubtF.hsreplay.xml.txt)

**Comment by ceceita** [comment]
https://hsreplay.net/replay/iWejVuXKFnfjUE4Z74ubtF#turn=12b

minion attacking and die to explosive trap marks missdirection checked but is not ..

**Comment by Jetz72** [comment]
https://us.forums.blizzard.com/en/hearthstone/t/deck-tracker-broken/9020

https://hsreplay.net/replay/9itxWBwK993yAmtVY5Qx9X

User claims Misdirection was cleared as a possibility when they attacked the enemy hero, even though a Freezing Trap triggered first to prevent the attack.

**Comment by beheh** [comment]
Might also be resolved by #3964, if that ever lands.
