### ISSUE TITLE
HDT (run as administrate) Bug 

### ISSUE THREAD

**Issue by MSGCryWolf** [HearthSim/Hearthstone-Deck-Tracker#3868]
**This the my most recent log file. I've already tried reinstalling the app and run the program as administrater. I'm all out of options on how to get this issue fixed. Is there anyone who can help me with this please.**

11:43:17 AM|Info|Core.Initialize >> HDT: 1.8.0.3804, Operating System: Windows 10 Home 17134, .NET Framework: 461808
11:43:17 AM|Info|Updater.StartupUpdateCheck >> Checking for updates
11:43:17 AM|Info|Updater.GetReleaseUrl >> Downloading releases file
11:43:18 AM|Info|Updater.GetReleaseUrl >> using 'live' release: https://github.com/HearthSim/HDT-Releases
11:43:18 AM|Info|Updater.SquirrelUpdate >> Checking for updates (ignoreDelta=False)
11:43:18 AM|Info|Updater.SquirrelUpdate >> No new updated available
11:43:18 AM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
11:43:19 AM|Info|ThemeManager.LoadThemes >> Found theme: classic
11:43:19 AM|Info|ThemeManager.LoadThemes >> Found theme: dark
11:43:19 AM|Info|ThemeManager.LoadThemes >> Found theme: frost
11:43:19 AM|Info|ThemeManager.LoadThemes >> Found theme: minimal
11:43:19 AM|Info|GameV2.Reset >> -------- Reset ---------
11:43:21 AM|Info|OverlayWindow.SetTopmost >> Hearthstone window not found
11:43:23 AM|Info|GameV2.Reset >> -------- Reset ---------
11:43:23 AM|Info|BackupManager.Run >> Running BackupManager
11:43:23 AM|Info|BackupManager.Run >> Creating backup for today
11:43:23 AM|Info|PluginManager.LoadPluginsFromPath >> Loading Plugins...
11:43:23 AM|Info|LogWatcherManager.Start >> Using Hearthstone log directory 'A:\Games\Hearthstone\Logs'
11:43:23 AM|Info|ApiWrapper.UpdateUploadTokenStatus >> Checking token status...
11:43:23 AM|Info|HsReplayDecks.Load >> Loaded from disk: Count=2504, ServerTS=2/8/2019 1:39:37 AM, Downloaded=2/7/2019 9:47:19 PM Age=1.13:56:04.4593172
11:43:23 AM|Info|HsReplayDecks.Load >> Cached data was not found or stale. Fetching latest...
11:43:23 AM|Info|ApiWrapper.GetAvailableDecks >> Fetching available decks...
11:43:23 AM|Info|ApiWrapper.UpdateUploadTokenStatus >> Token is not claimed
11:43:24 AM|Info|HsReplayDecks.Load >> Writing hsreplay_decks.cache to disk...
11:43:24 AM|Info|HsReplayDecks.Load >> Complete: Count=2506, ServerTS=2/9/2019 4:22:12 PM, Downloaded=2/9/2019 11:43:24 AM Age=00:00:00.0090357
11:43:27 AM|Info|HSReplayNetOAuth.Authenticate >> Authenticating with HSReplay.net...
11:43:27 AM|Error|HSReplayNetOAuth.Authenticate >> System.Net.HttpListenerException (0x80004005): The format of the specified network name is invalid
   at HSReplay.OAuth.CallbackListener.Create(Int32[] ports) in C:\projects\hearthstone-deck-tracker\HSReplay-Api\HSReplay\OAuth\CallbackListener.cs:line 70
   at HSReplay.OAuth.OAuthClient.GetAuthenticationUrl(Scope[] scopes, Int32[] ports) in C:\projects\hearthstone-deck-tracker\HSReplay-Api\HSReplay\OAuth\OAuthClient.cs:line 106
   at Hearthstone_Deck_Tracker.HsReplay.HSReplayNetOAuth.<Authenticate>d__30.MoveNext() in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\HsReplay\HSReplayNetOAuth.cs:line 58
11:43:27 AM|Info|ErrorManager.AddError >> New error: Could not authenticate with HSReplay.net
Please try running HDT as administrator (right-click the exe and select 'Run as administrator').
If that does not help please try again later.

**Comment by riQQ** [comment]
The relevant error is:
System.Net.HttpListenerException (0x80004005): The format of the specified network name is invalid

Press Windows + R and enter `cmd` to open the command line. In the command line run the command `ping localhost` and post the ouput here.

**Comment by MSGCryWolf** [comment]
ping localhost isn't showing up on my cmd line

**Comment by MSGCryWolf** [comment]
> The relevant error is:
> System.Net.HttpListenerException (0x80004005): The format of the specified network name is invalid
> 
> Press Windows + R and enter `cmd` to open the command line. In the command line run the command `ping localhost` and post the ouput here.

![cmd](https://user-images.githubusercontent.com/47203247/52673470-ea545400-2eee-11e9-93b3-9e69e88aaffb.JPG)

**Comment by riQQ** [comment]
I haven't see this issue before and searching the web, I couldn't find someone with exactly the same issue. For me it looks like it's a configuration problem of your system.
Have you changed any system settings, are using firewall / anti-virus / tuning software? Has this problem started recently or was it always this way?

**Comment by MSGCryWolf** [comment]
> I haven't see this issue before and searching the web, I couldn't find someone with exactly the same issue. For me it looks like it's a configuration problem of your system.
> Have you changed any system settings, are using firewall / anti-virus / tuning software? Has this problem started recently or was it always this way?

I just downloaded it for the first time. I've tried other options still nothing worked.

**Comment by riQQ** [comment]
- run the command line as administrator (Press Windows + R and enter `cmd`, right click the entry and click `Run as administrator`)
- run the command `netsh http add iplisten ipaddress=127.0.0.1`

Does that fix your problem?
