### ISSUE TITLE
HDT crashes on start

### ISSUE THREAD

**Issue by MicroElf** [HearthSim/Hearthstone-Deck-Tracker#3872]
HDT crashes everytime right on start. I tried to delete and reinstall it after reboot but still the same.
What should I do?

Сигнатура проблемы:
  Имя события проблемы:	APPCRASH
  Имя приложения:	HearthstoneDeckTracker.exe
  Версия приложения:	1.8.0.3804
  Отметка времени приложения:	5c5a3317
  Имя модуля с ошибкой:	KERNELBASE.dll
  Версия модуля с ошибкой:	6.1.7601.17514
  Отметка времени модуля с ошибкой:	4ce7bafa
  Код исключения:	c06d007e
  Смещение исключения:	0000b727
  Версия ОС:	6.1.7601.2.1.0.256.48
  Код языка:	1049
  Дополнительные сведения 1:	0a9e
  Дополнительные сведения 2:	0a9e372d3b4ad19135b953a78882e789
  Дополнительные сведения 3:	0a9e
  Дополнительные сведения 4:	0a9e372d3b4ad19135b953a78882e789

Ознакомьтесь с заявлением о конфиденциальности в Интернете:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0419

Если заявление о конфиденциальности в Интернете недоступно, ознакомьтесь с его локальным вариантом:
  C:\Windows\system32\ru-RU\erofflps.txt

**Comment by riQQ** [comment]
See #3662
