### ISSUE TITLE
HDT crash

### ISSUE THREAD

**Issue by Neiss** [HearthSim/Hearthstone-Deck-Tracker#3875]
For the past month, upon opening HDT it simply disappears after loading. No errors shown. The icon remains in system tray until I hover over it, then it disappears aswell. I 'm using Windows 10.

**Comment by riQQ** [comment]
Please provide logs. See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues (sections `HDT crash logs` and `Windows log files`)

**Comment by Neiss** [comment]
Logs from today's crash:

11:46:37 AM|Info|Core.Initialize >> HDT: 1.8.1.3806, Operating System: Windows 10 Enterprise 17134, .NET Framework: 461808
11:46:37 AM|Info|Updater.StartupUpdateCheck >> Checking for updates
11:46:37 AM|Info|Updater.GetReleaseUrl >> Downloading releases file
11:46:37 AM|Info|Updater.GetReleaseUrl >> using 'live' release: https://github.com/HearthSim/HDT-Releases
11:46:40 AM|Info|Updater.SquirrelUpdate >> Checking for updates (ignoreDelta=False)
11:46:42 AM|Info|Updater.SquirrelUpdate >> No new updated available
11:46:42 AM|Info|SplashScreenWindow.ShowConditional >> Showing splashscreen...
11:46:42 AM|Info|ThemeManager.LoadThemes >> Found theme: classic
11:46:42 AM|Info|ThemeManager.LoadThemes >> Found theme: dark
11:46:42 AM|Info|ThemeManager.LoadThemes >> Found theme: frost
11:46:42 AM|Info|ThemeManager.LoadThemes >> Found theme: minimal
11:46:42 AM|Info|GameV2.Reset >> -------- Reset ---------
11:46:46 AM|... 1 duplicate messages
11:46:46 AM|Info|BackupManager.Run >> Running BackupManager
11:46:46 AM|Info|BackupManager.Run >> Deleting old backup: Backup_14022019.zip
11:46:46 AM|Info|BackupManager.Run >> Creating backup for today
11:46:46 AM|Info|PluginManager.LoadPluginsFromPath >> Loading Plugins...
11:46:46 AM|Info|Helper.GetCurrentRegion >> Region: EU
11:46:46 AM|Info|BackupManager.Run >> Running BackupManager
11:46:46 AM|Info|BackupManager.Run >> Backup for today already exists
11:46:46 AM|Info|LogWatcherManager.Start >> Using Hearthstone log directory 'C:\Program Files (x86)\Hearthstone\Logs'
11:46:46 AM|Info|LogWatcherManager.OnLogFileFound >> FullScreenFX
11:46:46 AM|Info|LogWatcherManager.OnLogFileFound >> LoadingScreen
11:46:46 AM|Info|LogWatcherManager.OnLogFileFound >> Achievements
11:46:46 AM|Info|HSReplayNetOAuth.UpdateAccountData >> Updating account data...
11:46:46 AM|Info|HSReplayNetOAuth.UpdateToken >> Refreshing token data...
11:46:47 AM|Info|HsReplayDecks.Load >> Loaded from disk: Count=1918, ServerTS=3/9/2019 6:44:45 PM, Downloaded=3/9/2019 9:05:16 PM Age=1.14:41:30.8578694
11:46:47 AM|Info|HsReplayDecks.Load >> Cached data was not found or stale. Fetching latest...
11:46:47 AM|Info|ApiWrapper.GetAvailableDecks >> Fetching available decks...
11:46:47 AM|Info|HSReplayNetOAuth.SaveTokenData >> Saved token data
11:46:47 AM|Info|GameV2.CurrentMode >> LOGIN
11:46:47 AM|Info|GameV2.CurrentMode >> HUB
11:46:47 AM|Info|GameV2.CurrentMode >> PACKOPENING
11:46:47 AM|Info|GameV2.CurrentMode >> HUB

**Comment by Neiss** [comment]
Windows Log Files:
Log Name:      Application
Source:        .NET Runtime
Date:          11-Mar-19 11:46:47 AM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-GBNHBEJ
Description:
Application: HearthstoneDeckTracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 09F071A0

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-03-11T09:46:47.966888500Z" />
    <EventRecordID>20847</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-GBNHBEJ</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: HearthstoneDeckTracker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 09F071A0
</Data>
  </EventData>
</Event>

**Comment by Neiss** [comment]
Log Name:      Application
Source:        Application Error
Date:          11-Mar-19 11:46:48 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-GBNHBEJ
Description:
Faulting application name: HearthstoneDeckTracker.exe, version: 1.8.1.3806, time stamp: 0x5c7d589a
Faulting module name: GTII-OSD.dll, version: 2.0.3.2, time stamp: 0x5be93476
Exception code: 0xc0000005
Fault offset: 0x000371a0
Faulting process id: 0x4384
Faulting application start time: 0x01d4d7ef517558d2
Faulting application path: C:\Users\kosti\AppData\Local\HearthstoneDeckTracker\app-1.8.1\HearthstoneDeckTracker.exe
Faulting module path: C:\Program Files (x86)\ASUS\GPU TweakII\GTII-OSD\x86\GTII-OSD.dll
Report Id: fde9d387-3ca1-4a95-8f8b-0b5df89fe710
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-03-11T09:46:48.168181100Z" />
    <EventRecordID>20848</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-GBNHBEJ</Computer>
    <Security />
  </System>
  <EventData>
    <Data>HearthstoneDeckTracker.exe</Data>
    <Data>1.8.1.3806</Data>
    <Data>5c7d589a</Data>
    <Data>GTII-OSD.dll</Data>
    <Data>2.0.3.2</Data>
    <Data>5be93476</Data>
    <Data>c0000005</Data>
    <Data>000371a0</Data>
    <Data>4384</Data>
    <Data>01d4d7ef517558d2</Data>
    <Data>C:\Users\kosti\AppData\Local\HearthstoneDeckTracker\app-1.8.1\HearthstoneDeckTracker.exe</Data>
    <Data>C:\Program Files (x86)\ASUS\GPU TweakII\GTII-OSD\x86\GTII-OSD.dll</Data>
    <Data>fde9d387-3ca1-4a95-8f8b-0b5df89fe710</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by Neiss** [comment]
Disabling ASUS GPU Tweak II OSD overlay seems to stop HDT from crashing for now.

**Comment by riQQ** [comment]
Thanks for the feedback. Gpu tools have a history of causing problems.
