### ISSUE TITLE
Error when trying to export screenshot of decklist to imgur

### ISSUE THREAD

**Issue by Zeprido** [HearthSim/Hearthstone-Deck-Tracker#3879]
### Expected Behavior

Image successfully uploaded to imgur and link to image provided.
### Actual Behavior

"Error uploading. Please try again later and/or upload manually. Started happening with last update.
### Steps to reproduce behavior

Try to upload to imgur

**Comment by riQQ** [comment]
This happens from time to time when the API limit is hit. Either upload it manually or try again later.
