### ISSUE TITLE
Old collections aren't synching properly

### ISSUE THREAD

**Issue by dlmoushey** [HearthSim/Hearthstone-Deck-Tracker#3884]
## Bug report
Karazhan, Old Gods, League of Explorers, Grand Tournament, Blackrock, GVG, Naxx aren't updating the collection properly

### Expected Behavior

Expected the automatic collection synch to accurately report my collection. All of the sets, not just the recent ones.

### Actual Behavior

Synchs recent collections and some of wild, but not whole set.

### Steps to reproduce behavior

Synch is that way currently. I've tried restarting my system and the client and it didn't help.

### Log/Screenshots

![Collection](https://user-images.githubusercontent.com/38014066/55663517-ea851780-57ec-11e9-8a7d-ced375e5eb41.PNG)

**Comment by ceceita** [comment]
have you tried to show the wild cards in the collection ?
If i remember well the collection is read from memory , so i think if one opens the collection without changing the game filters , the wild card data is not load in memory and so is not updated.

**Comment by dlmoushey** [comment]
I don’t think that is the issue as I got 16 gvg cards in there. But doesn’t matter: logged in today and the whole collection was correct. Don’t know what caused the blip or what fixed it but fine now.

**Comment by riQQ** [comment]
Was your collection correctly displayed before the problem or is it only working now?

**Comment by dlmoushey** [comment]
My collection was incorrectly displayed when I noted the problem. When it appeared fixed it was fixed on all fronts. It’s possible there was an inbetween where it was half working but I missed it. I did check the collections pages for the missing cards and they were not there when I had the issue - it wasn’t just displaying 0 when the cards were in place: they weren’t there in the tracker.

**Comment by dlmoushey** [comment]
And the tracker worked properly since I first installed it until I noted the problem, and as far as I know is working correctly again. Just a weird blip.
