### ISSUE TITLE
HDT just wouldnt open and now wouldnt even install 

### ISSUE THREAD

**Issue by cosmonaut98** [HearthSim/Hearthstone-Deck-Tracker#3885]
### Expected Behavior
should justr

### Actual Behavior
-I opened HDT after a while and the application wouldnt load, so I uninstalled it and tried installing it again, but now every time I try to launch the installer it shows me a dialogue box saying, "windows cannot access the specified device, path, or file. you may not have the appropriate permission to access the item", even though full authority option has been selected

**Comment by riQQ** [comment]
Are there any HDT logs corresponding to this problem? See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#hdt-log-files.

Can you post a screenshot of the error message?
