### ISSUE TITLE
Template placeholder text appears instead of card description in Rise of Shadows card tool tip

### ISSUE THREAD

**Issue by foresto** [HearthSim/Hearthstone-Deck-Tracker#3886]
### Expected Behavior
Opponent card tool tip should show the card's description text.

### Actual Behavior
Template text placeholders appeared instead of expected text.

### Steps to reproduce behavior
Let opponent play Crystal Stag, then mouse hover over that card's name in the HDT overlay.

### Log/Screenshots
![hdt](https://user-images.githubusercontent.com/322134/55851667-6e514380-5b0e-11e9-9dd4-692263c72661.png)

**Comment by azeier** [comment]
Fixed with https://github.com/HearthSim/HearthDb/commit/9e4a9ed2fc5697527d6e63d9abceee3779aa3137#diff-25619e84a677149158e8ebe1037ca863R108.

Going to release an update later today.
