### ISSUE TITLE
Augmented Elekk + Bombs - not counting extra bombs

### ISSUE THREAD

**Issue by BuckyBilson** [HearthSim/Hearthstone-Deck-Tracker#3887]
### Expected Behavior
Augmented Elekk + Wrenchcalibur should increment the bombs in enemy deck by 2
Augmented Elekk + Clockwork Goblin should increment the bombs in enemy deck by 2
Augmented Elekk + Seaforium Bomber should increment the bombs in enemy deck by 2

### Actual Behavior
Augmented Elekk + Wrenchcalibur increments the bombs in enemy deck by 1
Augmented Elekk + Clockwork Goblin increments the bombs in enemy deck by 1
Augmented Elekk + Seaforium Bomber increments the bombs in enemy deck by 1

### Steps to reproduce behavior
Play Augmented Elekk and follow up with any bomb-planting card.

**Comment by beheh** [comment]
This is another specific case of #3760.

**Comment by azeier** [comment]
Fixed with v1.8.7.
