### ISSUE TITLE
Jan'alai tooltip broken on overlay

### ISSUE THREAD

**Issue by dairelavelle1** [HearthSim/Hearthstone-Deck-Tracker#3888]
### Expected Behavior

when less than 8 damage has been dealt with the hero power: "(X left!)" where X is 8 minus the damage dealt so far
when 8 or more damage is dealt: "ready!"

### Actual Behavior

always says "((0) left!)@ (Ready!)"

### Steps to reproduce behavior

Play a game of hearthstone with Jan'alai in the deck

### Log/Screenshots

[hdt_log_1554912352.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/3064743/hdt_log_1554912352.txt)
![Screenshot_33](https://user-images.githubusercontent.com/32362675/55895146-77482080-5bb3-11e9-9920-e5905dd0f9c9.png)

**Comment by azeier** [comment]
Fixed with https://github.com/HearthSim/HearthDb/commit/9e4a9ed2fc5697527d6e63d9abceee3779aa3137#diff-25619e84a677149158e8ebe1037ca863R108.

Going to release an update later today.

**Comment by riQQ** [comment]
Duplicate of #3886
