### ISSUE TITLE
Secrets not using correct sets in Arena

### ISSUE THREAD

**Issue by ebigunso** [HearthSim/Hearthstone-Deck-Tracker#3889]
## Bug report
Secret overlay in Arena is incorrectly using secrets from standard, where it should actually be using sets currently implemented in Arena.

### Expected Behavior
Secrets are chosen from current Arena sets

### Actual Behavior
Secrets are chosen from standard

### Steps to reproduce behavior
Play Arena with Hearthstone Deck Tracker overlay on, and encounter an opponent who plays a secret

### Log/Screenshots
![HSReplaySecretBug](https://user-images.githubusercontent.com/13187653/55895407-13474b80-5bf7-11e9-842b-7dd96355578b.png)

**Comment by azeier** [comment]
Should be fixed with v1.8.6.
