### ISSUE TITLE
Bomb Counter Request

### ISSUE THREAD

**Issue by abrownhearth** [HearthSim/Hearthstone-Deck-Tracker#3891]
Request from Customer: "I would like to request there be a Bomb counter for the new Warrior cards similar to Yogg's spell counter."

Field would trigger if Clockwork Goblin, Seaforium Bomber, or Wrenchcalibur are recognized in a Standard deck and would show how many Bombs are currently in opponent's deck.

**Comment by azeier** [comment]
This should just be in the opponents deck list, not a counter.
