### ISSUE TITLE
Get the opponent BattleTag name?

### ISSUE THREAD

**Issue by ElektroStudios** [HearthSim/Hearthstone-Deck-Tracker#3897]
As you can see this is not a bug report, but a question to the devs... and this is the only way I know to contact them, excuse me.

My question is:
Can I get the fully qualified opponent BattleTag name in the format: USERNAME#NUMBER through the HDT/HearthMirror API?. ﻿Could you please mention the fully qualified namespace of the member, and/or give a code example?.

I found [same question](https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/1685) but it is from year 2015 and it is related to the HDT user-interface, not the API, and maybe in this time something has changed and maybe this feature finally got included...

Thanks for read.

**Comment by riQQ** [comment]
Via method call `HearthMirror.Reflection.GetMatchInfo().Player.BattleTag` or as property on the game object `Hearthstone_Deck_Tracker.Hearthstone.GameV2.MatchInfo.Player.BattleTag`.

**Comment by ElektroStudios** [comment]
Thank you
