### ISSUE TITLE
Low FPS with Hearthstone Deck Tracker

### ISSUE THREAD

**Issue by TioHell** [HearthSim/Hearthstone-Deck-Tracker#3899]
Hello, when i have HDT opened my Hearthstone fps drop from 150+ to 30 at max, i tryed all i could find in google and here to try fix it and nothing happened, any tip of what i can try to do?

**Comment by riQQ** [comment]
You should specifiy the things you tried otherwise it's hard to help.

Have you checked this:
> Does it go back to normal if you enable `options > overlay > hide (completely)`?

**Comment by TioHell** [comment]
> You should specifiy the things you tried otherwise it's hard to help.
> 
> Have you checked this:
> 
> > Does it go back to normal if you enable `options > overlay > hide (completely)`?

As i said literally everything so yes but i got it solved out, had to enable windows aero and worked out fine as expected :)

**Comment by riQQ** [comment]
Then you didn't, because that was mentioned in one of the other threads.
