### ISSUE TITLE
Main windows is not visible

### ISSUE THREAD

**Issue by Hegi** [HearthSim/Hearthstone-Deck-Tracker#3901]
Main window is nowhere to be found. Even if I go to and right-click on the try icon and click on the show button, the focues "goes somewhere" however the main window is not appearing. Also the "thumbnail" for the main window is "empty". (See screenshot below)

![image](https://user-images.githubusercontent.com/4586311/56857754-4d2a8880-693f-11e9-8e37-44d30444cb6b.png)

**Comment by riQQ** [comment]
Does the overlay work?
Does the second point from the following link help: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#main-window?

**Comment by Hegi** [comment]
The overlay works, however the main window, like I've said is not visible,
so I can't pull it up to verify your question.
Is there some setting in a config file where I can override the
width/height and position of the main window?

**Comment by riQQ** [comment]
That's exactly what i linked you:
> Open the file %appdata%\HearthstoneDeckTracker\config.xml with a text editor and check the elements TrackerWindowLeft and TrackerWindowTop. If they are big or negative, close HDT, set them to zero and start again.

**Comment by Hegi** [comment]
Thank you @riQQ. That fixed the problem!
