### ISSUE TITLE
Shimmerfly Wrong Tooltip 

### ISSUE THREAD

**Issue by IvanGivingStun** [HearthSim/Hearthstone-Deck-Tracker#3902]
Tooltip for hunter's shimmerfly shows 3 beasts of pet call

**Comment by riQQ** [comment]
Probably, the meta data of that card is incorrect.
![grafik](https://user-images.githubusercontent.com/3404787/56992637-cb369b80-6b9a-11e9-8525-9f7fa00585c8.png)
