### ISSUE TITLE
Unable to install. Error

### ISSUE THREAD

**Issue by Firstaftergodvampir** [HearthSim/Hearthstone-Deck-Tracker#3907]
Hello, I can not install the application, an error
![Скрин](https://user-images.githubusercontent.com/50342415/57256211-b6587d00-705e-11e9-8419-60438214e675.png)
[SquirrelSetup.log](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/3149898/SquirrelSetup.log)

**Comment by riQQ** [comment]
Exeption code is 80131506. There's #3001 and #2340 with the same exception code, but not really a solution. I don't really know how to solve this, sorry.
