### ISSUE TITLE
Deleted an arena run (I have a backup) and want to add matches

### ISSUE THREAD

**Issue by Reachground** [HearthSim/Hearthstone-Deck-Tracker#3909]
Let's start by saying that this is totally my mistake. I was clearing out old data and accidentally also removed my magnificent 12 win arena.

It's still available in an old backup that I made a copy off so I imported the deck to the new save. I thought everything was good but realized that the matches didn't go along with the deck. Is there a way to export/import those specific matches without doing it manually?

Thanks

**Comment by riQQ** [comment]
Only by manually copying them in the XML files. But that's not easy to do.

**Comment by Reachground** [comment]
Oh well, it was my bad anyway. Thanks for replying!
