### ISSUE TITLE
My warlock deck is not recognized by deck trakker nor can it be imported

### ISSUE THREAD

**Issue by nicholberry** [HearthSim/Hearthstone-Deck-Tracker#3911]

**Comment by riQQ** [comment]
Please provide more information. Which version are you using? What do you mean by 'not recognized'. Are there any error messages? Why can't it be imported?

**Comment by nicholberry** [comment]
Hi there. 


Hearthstone Deck Tracker v 1.8.9

Not Recognized: Deck Tracker shows me all my standard/wild and arena decks EXCEPT my Zoo Warlock

When I try to import to Deck Tracker I get an error message that says "no new decks found"

I tried to screen shot my Deck Tracker Standard decks page to show that it doesn't appear, but for some reason Deck Tracker doesn't like it's picture taken. (probably operator error, but I have no clue why that would be)

Here's a screen shot of my Standard Deck list as of 15 minutes ago. 

I hope this is helpful. I'm sure if I was more techy I could be more useful, but alas - just an old woman hanging in there. 


Thanks

Diana

**Comment by nicholberry** [comment]
My attachment got dropped - here you go.

**Comment by riQQ** [comment]
I think you can't attach files via email replay.
Can you export your deck in Hearthstone, delete it and reimport it. Maybe this helps.

**Comment by nicholberry** [comment]
What do you mean "export your deck in Hearthstone". I'm unaware of any way to export FROM Hearthstone to Deck Tracker (I only see the option to import or export from Deck Tracker). Is there a way to do this?

If you're suggesting I delete it and rebuild it in Deck Tracker and then export it I could have done that at the start but it doesn't explain why Deck Tracker isn't recognizing it in the first place. That isn't a reasonable solution. 


sorry to have bothered you. I'll find a work around.

**Comment by riQQ** [comment]
Yes, this is probably a bug. Check the advanced options if you have auto importing turned on.
If you want to find out the cause of this bug, it's going to be hard to pinpoint. If you're up to some to investigating we can try.

This is just a workaround I'm proposing. If you hover over the deck in Hearthstone there is a button to copy the deck string. After that you can import it via deckstring in HDT.
![screenshot](https://user-images.githubusercontent.com/3404787/58357978-3d8a5b00-7e7d-11e9-8396-7d717fc57c20.png)

**Comment by nicholberry** [comment]
Thanks for your persistence. I decided just to replicate the deck in HDT and then export it as Zoo Warlock 1. It seems to be tracking it now. Not sure what happened but there's probably no reason to pursue this further. 


Thank you.
