### ISSUE TITLE
Could not auto-import "The Great Dalaran Heist (Risde of Shadows)" dungeon deck

### ISSUE THREAD

**Issue by kazumaverdao** [HearthSim/Hearthstone-Deck-Tracker#3914]
### Expected Behavior
HDT should probably auto-import (and also auto-update) decks for the "The Great Dalaran Heist" adventure, as it properly does with Rastakhan Rumble deck.

### Actual Behavior
In Rastakhan Rumble adventure it works perfectly. Creates a new deck with the main cards, then auto-updates once I go through the session, including the "relique" cards. It does not happen in Rise of Shadows expansion adventure. Does not automatically create a new deck, and can't import the deck I'm playing in the current session.

### Steps to reproduce behavior
Just play "The Great Dalaran Heist" dungeon.

### Log/Screenshots

<!--- See here: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues
[hdt_log_1558810381.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/3219632/hdt_log_1558810381.txt)
![hdt rastakhan rumble run](https://user-images.githubusercontent.com/17756495/58373574-a10c9b00-7f06-11e9-8c0a-8308aae02a78.jpg)
![hdt the great dalaran heist run](https://user-images.githubusercontent.com/17756495/58373575-a1a53180-7f06-11e9-908c-f1a6e3634718.jpg)

**Comment by kazumaverdao** [comment]
![hdt the great dalaran heist run](https://user-images.githubusercontent.com/17756495/58373584-bc77a600-7f06-11e9-86f4-8325fb76b02e.jpg)
![hdt rastakhan rumble run](https://user-images.githubusercontent.com/17756495/58373597-dfa25580-7f06-11e9-9a2b-77220e0bb36c.jpg)
[hdt_log_1558810381.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/3219639/hdt_log_1558810381.txt)

**Comment by riQQ** [comment]
Should be fixed with 1.8.10.

**Comment by Glitchex** [comment]
well its not working still. It worked for a day and then stopped again. Ive reinstalled and did all the help guides ideas, but nothing works, it keeps showing only cards played and not the full deck.

**Comment by riQQ** [comment]
@Glitchex it's working for me. Please open a new issue with a detailed description what you're doing and what exactly isn't working.
