### ISSUE TITLE
Tracker Fails to Record Changes Made to Deck in Tavern Encounter of Dalaran Heist

### ISSUE THREAD

**Issue by anhjoseph** [HearthSim/Hearthstone-Deck-Tracker#3915]
## Bug report
When progressing through a chapter in Dalaran Heist, player has a Tavern Encounter after the 3rd and 5th bosses. Any changes made to player's deck in the Encounter will not be registered by the tracker.

### Expected Behavior
Edits are recorded and saved to current Dalaran Heist Run to continue using Tracker beyond the third boss.

### Actual Behavior
Due to deck changes not being recorded, Tracker fails to use the correct deck and instead reverts to old behavior with one of the 3 original starting decks.

### Steps to reproduce behavior
Play Heist with Tracker until Tavern Encounter

**Comment by Glitchex** [comment]
funny thing is that it was working the first day and then later that night this bug started for what reasons are unknown... I guess its just poorly coded? Who knows. Could be something Blizzard did, seeing how they are lazy and cant create a deck tracker of their own for paying customers. Sad, really.

**Comment by Glitchex** [comment]
I uninstalled this deck tracker seeing how its only lagged my game as well as itself ever since Ive used it. Anyone know of a different tracker please?

**Comment by Glitchex** [comment]
For real though... I did every help guide and even reinstalled it about 10 times and it still lags itself so bad that it cant even log me out of it lol. Plz fix this lawl.

**Comment by riQQ** [comment]
Do you know which changes cause this? Removing cards? Modifying the cost of cards? Adding cards? I haven't encountered this problem yet. 

Do you have a log of that session? See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#hdt-log-files.

**Comment by anhjoseph** [comment]
Hm, now seems to be working perfectly likely was something I was doing on my end causing the issue. Thank you nonetheless!

**Comment by Glitchex** [comment]
Yeah it got fixed for me as well, but then after the 2nd tavern bob on this run its back to not showing cards in deck, only cards when drawn.

**Comment by Glitchex** [comment]
Here is my hdt_log.txt for when it happened tonight. Its alot to go through but I can see where a few problems are located.
[hdt_log_1559274832.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/3239704/hdt_log_1559274832.txt)
