### ISSUE TITLE
Arena Helper Doesn't Auto-Pick

### ISSUE THREAD

**Issue by mjmora87** [HearthSim/Hearthstone-Deck-Tracker#3916]
## Bug report
I use Arena Helper and about half the time I use it, it won't auto-pick cards. I can tell immediately that it is not going to when I'm at the hero selection screen. If it's going to function properly, when I select one of the heroes, in the app that hero will increase in size. If the app isn't going to function properly, the heroes size will not increase. When selecting cards, the cards will not be automatically selected and I will manually have to do so.

Thank you for your help!

**Comment by riQQ** [comment]
Please post your issue at the issue tracker for Arena Helper: https://github.com/rembound/Arena-Helper/issues.
