### ISSUE TITLE
More information for Bounced or Generated cards in opponent's hand

### ISSUE THREAD

**Issue by abrownhearth** [HearthSim/Hearthstone-Deck-Tracker#3954]
When opponent generates a card for their hand, currently there is only a gift icon. If several turns go by, it would be nice to be able to see how they received that card if I mouseover the gift icon in their hand. (Card generated by Bazaar Mugger, for example)

(Request from The Pope#1717 in Discord)

**Comment by buh6173** [comment]
It's been 8 months, and zero update on this.

**Comment by riQQ** [comment]
This was implemented with 43e078cc03f4580cfc533297a042a94bee269ad1 in 1.12.6

**Comment by buh6173** [comment]
> 
> 
> This was implemented with [43e078c](https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/43e078cc03f4580cfc533297a042a94bee269ad1) in 1.12.6

Partially, but not fully. As pointed out in the Discord, while players can now see what cards generated what cards in the hand, we don't know for certain what cards exactly were generated.

For example, for Twisted Knowledge, it would be nice for the hint text to say "Warlock card" for each card generated by Twisted Knowledge. However, this is not as critical as another issue: when the player should know _exactly_ what the card is.

For this example, let's say the opponent uses Expired Merchant and discards Mountain Giant. When Expired Merchant dies, two Mountain Giants will be added to the hand. However, HDT will only say that the cards were "added by Expired Merchant", even though the player (and HDT) should know full well that they are both Mountain Giants. Other examples include Acornbearer's squirrels, anything that generates a Lackey, the minion cloned by Sathrovarr, anything Tak Nozwhisker added into the hand, Archmage Antonidas's fireballs, etc.

HDT currently has the functionality to tell what card exactly is in someone's hand (for instance, if Sap is played on Expired Merchant, HDT will display that the card in the hand is Expired Merchant, not that it was "generated by Sap"). As such, it should hopefully be not as much of an issue to code card-generators to display the exact card when appropriate.

**Comment by riQQ** [comment]
Tracking your proposal in the separate issue #4088.

Closing this one as it is implemented as defined in the opening post.
