### ISSUE TITLE
what should i do? it don't show decks at all

### ISSUE THREAD

**Issue by pasha2281337** [HearthSim/Hearthstone-Deck-Tracker#3962]
what should i do? it don't show decks at all

i installed programm correctly, but it doesn't work. it starts with hs but doesn't show decks

![image](https://user-images.githubusercontent.com/22530101/64921161-57eb9a00-d7c8-11e9-9909-e7b3b5179549.png)

help me pls

**Comment by riQQ** [comment]
Have you followed the hint and entered the play menu?

If yes, please provide the HDT log corresponding to this problem. See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#hdt-log-files.
