### ISSUE TITLE
In-game overlay does not show entire deck

### ISSUE THREAD

**Issue by SirSpookleton** [HearthSim/Hearthstone-Deck-Tracker#3965]
#  Bug report
In-game overlay does not show me my entire deck in the deck-list, only cards as they are drawn.

### Expected Behavior
For my entire deck to be shown.

### Actual Behavior
Doesn't show entire deck.

### Steps to reproduce behavior
No clue.

**Comment by riQQ** [comment]
See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/FAQ#only-drawn
