### ISSUE TITLE
HDT freezing when starting Hearhstone

### ISSUE THREAD

**Issue by ThanosMoist** [HearthSim/Hearthstone-Deck-Tracker#3969]
Hello,
HDT freezes whenever I start the game, followed by the message "... stopped working."
Any fixes?

**Comment by goldenmane** [comment]
+1 new update broke it

**Comment by Kyrisys** [comment]
+1 new update broke it

**Comment by ScroungerHS** [comment]
Yep, same here.  Application needs an update itself.

**Comment by Montblanc0** [comment]
Is there any way we could get a debug log?

**Comment by Shuhasu** [comment]
having the same issue

**Comment by InFlamesForever** [comment]
Got the issue too, started after the latest update.

**Comment by azeier** [comment]
v1.8.20 should fix this.
