### ISSUE TITLE
Today's update 1.8.20 causes hearthstone to ignore mouse & keyboard input

### ISSUE THREAD

**Issue by foresto** [HearthSim/Hearthstone-Deck-Tracker#3970]
Before today's HDT update, I was able to play Hearthstone (including the new Hallow's End version 15.4.0.34670) with HDT. Since HDT updated itself to 1.8.20, Hearthstone still launches, but it ignores all mouse and keyboard input,

If I launch Hearthstone standalone instead of via HDT, this does not happen.

I'm playing on Linux via Lutris, in case that matters. I have been doing so for half a year, so I'm surprised to have this problem all of a sudden.

**Comment by foresto** [comment]
Found a Wine registry setting that works around the problem:

    Windows Registry Editor Version 5.00
    [HKEY_CURRENT_USER\Software\Wine\X11 Driver]
    "UseTakeFocus"="N"

I haven't found docs for this settings, but it seems to work.

**Comment by azeier** [comment]
I'm gonna guess this is related to Hearthstone upgrading to a newer unity version.

**Comment by riQQ** [comment]
I'm voting for closing this and continuing in the HDT on Linux mega thread: #2511

**Comment by azeier** [comment]
👍
