### ISSUE TITLE
Arena Import with Dual Class broken

### ISSUE THREAD

**Issue by JoeBarouneD** [HearthSim/Hearthstone-Deck-Tracker#3971]
As the title say, the arena importing feature is broken cause, i think, is the new Dual Class arena.

Thanks !

**Comment by azeier** [comment]
Has been fixed with https://github.com/HearthSim/HearthMirror/commit/34418d72b55fa3bc406d3305471bc54fcddc3c71 and will be in the next release, probably in a couple of hours.
