### ISSUE TITLE
Avenge doesn't show up as possible Paladin secret in Arena

### ISSUE THREAD

**Issue by franklin1l** [HearthSim/Hearthstone-Deck-Tracker#3974]
![Przechwytywanie](https://user-images.githubusercontent.com/7831358/68085447-7e7d9700-fe41-11e9-8416-102f927b9eff.PNG)
Pretty much what is in the title. When playing in Arena against Paladin the only options showed by tracker are Getaway Kodo, Compepetive Spirit and Sacred Trial.

**Comment by Fink23** [comment]
Same bug for me as well.
