### ISSUE TITLE
Battlegrounds mode support

### ISSUE THREAD

**Issue by aardvark42** [HearthSim/Hearthstone-Deck-Tracker#3977]
Some limited ability to show information for the new Hearthstone Battlegrounds mode would be useful. There's three categories I can think of offhand:

1) Available cards in each tier. (at least current & next, to inform upgrade decisions; possibly just everything at once) Personally, I'm constantly alt-tabbing into Firefox to view the full list of cards available in each tier to see what I could get and what tiers I may want to upgrade to. The simplest thing to do here would be to just straight-up list everything available on-screen as it is essentially your available "deck", but with sub-headings for each tier. (also showing probabilities would be good, but I don't know if that information is actually available; e.g. chance of seeing tier n vs. n-1 in a roll; n+1 for discovers & Toki)

2) Secrets. Only one hero has access to secrets at the moment. This is of limited use because all combat is fully automatic, so counter-play is difficult, but this info could theoretically be useful for planning future battles. In any case, implementing this would be able to take advantage of some existing functionality. The list of available secrets is here:
https://www.hearthpwn.com/cards?filter-name=secret&filter-include-card-text=y&filter-set=1117&filter-type=5&display=3

3) Other players' last seen boards. It could be super helpful to remember the last board that was seen for opponents, especially in the late game. This could be really helpful to make decisions on hero powers, positioning, etc., and this is the sort of thing that people often use trackers for: remembering bits of mundane info to avoid needing pen & paper or a non-awful memory.

Simply having a boring overlay list of all available cards by tier with no interactivity would be useful by itself, as a minimum viable feature. The only info from the client needed to implement this would be to know when the mode has started.

**Comment by azeier** [comment]
Currently working on (3)!

**Comment by Avenroot** [comment]
I would also love to see some stats tracking history of where you finished and the points +/- received.  Along with that knowing what Hero I played as would be nice.  That way I can see a history of heroes I have chosen and the history of my playing them.

**Comment by azeier** [comment]
(1) and (3) are implemented. I don't think (2) is really all that relevant, since even if you know that you're up against Akazamzarak, you have no way of knowing which or how many secrets he may or may not have. And at the time of combat this has no impact.
