### ISSUE TITLE
[Bug Report] Battlegrounds The Tracker Does Not Always Track the Last Known Board State

### ISSUE THREAD

**Issue by Charleezy** [HearthSim/Hearthstone-Deck-Tracker#3980]
## Bug report
Battlegrounds Last Known Board Not Always Tracked

### Expected Behavior

I expect the tracker to have an accurate reflection of my opponent's last known board but maybe 20% of the time the board state is not tracked.

### Actual Behavior

~20% of the time the board state is not tracked. Perhaps it keeps a previous record of the board state for that player, or if there is no known board state, it records nothing at all.

### Steps to reproduce behavior

I think everyone is having the same issue. Collins mentioned on stream how the tracker doesn't always track the last known board. I think Tides has mentioned the same thing and asked chat for help.

### Log/Screenshots

None ATM

**Comment by azeier** [comment]
Looks like what we're using to trigger the snapshotting isn't always reliable. Looking into this.
