### ISSUE TITLE
Turn Timers for Battlegrounds

### ISSUE THREAD

**Issue by Charleezy** [HearthSim/Hearthstone-Deck-Tracker#3981]
I think a turn timer could be useful for figuring out how powerful you should be on any given turn. You can track the early turns with gold but after 10 gold they start to blur together.  

I recall this was a feature in the original HDT for classic hearthstone so I was thinking maybe this could be done if there's enough interest, for battlegrounds too.

**Comment by azeier** [comment]
The description sounds like a turn counter, rather than a timer? In which case this has been added with v1.10.0.
