### ISSUE TITLE
Concedes are not logged properly in stats

### ISSUE THREAD

**Issue by mcbexx** [HearthSim/Hearthstone-Deck-Tracker#3983]
## Bug report
If the opponent concedes, the match stat overview does not list it as a "Win", but as "None" instead. If you yourself concede, the game is not logged in stats at all.

### Expected Behavior
Tracking of conceded games as Win or Loss respectively

### Actual Behavior
See above.

### Steps to reproduce behavior
As far as I can tell, either player conceding.

### Log/Screenshots

![HearthstoneDeckTracker_aiRyrceZPN](https://user-images.githubusercontent.com/56156474/70587954-a9d76c80-1bcb-11ea-9b26-c8025541127a.png)

**Comment by riQQ** [comment]
Please provide the HDT log corresponding to this problem. See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#hdt-log-files.

**Comment by beheh** [comment]
Is this still an issue as per v.1.9.6?

**Comment by mcbexx** [comment]
Hi,no, looks like concedes are now properly logged as wins/losses. Am 17.12.2019 15:01 schrieb Benedict Etzel <notifications@github.com>:Is this still an issue as per v.1.9.6?

**Comment by beheh** [comment]
Thanks for confirming that!
