### ISSUE TITLE
Attack on board and player played cards section bugged

### ISSUE THREAD

**Issue by Kummo33** [HearthSim/Hearthstone-Deck-Tracker#3984]
![tracker bug](https://user-images.githubusercontent.com/53865835/70660456-58f07280-1cb6-11ea-8a2a-275ba7c3ff00.jpg)

As you can see from the screenshot, the attack on board for both me and my opponent is incorrect and the number of my played cards isn't greyed out like normal.

In the beginning of the arena game, the attack numbers were shown correctly, but after a few turns it turns buggy like this. It has happened almost every game since the new expansion release. Not sure what causes it.

I'm using the latest Dec 10 deck tracker release.

**Comment by azeier** [comment]
Please check if this issue persists with v1.9.6

**Comment by Kummo33** [comment]
Nice. It's fixed with the Dec 12 release. All good now.
