### ISSUE TITLE
Select version 1.0 hides the version list

### ISSUE THREAD

**Issue by ForceRockWONG** [HearthSim/Hearthstone-Deck-Tracker#3985]
### Expected Behavior
The dropdown is hidden and we can't select the other version anymore

### Actual Behavior
The dropdown is still shown

### Steps to reproduce behavior
Create a deck with version 1.0 and 1.1
Select version 1.1
Select version 1.0
Try to select 1.1 again

**Comment by riQQ** [comment]
I can't reproduce. Neither with an existing nor a newly created deck. Can you record your screen while reproducing this problem?

**Comment by ForceRockWONG** [comment]
Happy new year!
And sorry for the late response.

Thank you @riQQ  .
I couldn't repro this as well now...
I had a deck with at least 5 versions,  1.0 to 1.4   . And I couldn't see the list to select the version once I clicked on 1.0. And I had to select 1.0/1.1/2.0 when updating it to save.
It could be a one time issue. 
Please feel free to close this.
