### ISSUE TITLE
Add invoke Galakrond counter

### ISSUE THREAD

**Issue by kimsey0** [HearthSim/Hearthstone-Deck-Tracker#3986]
Another counter request, similar to the one implemented for C'Thun back in the day: How many times have you and your opponent invoked Galakrond. It could cut off after four.

**Comment by chWolfgang** [comment]
FWIW: I second this idea.

**Comment by Lightczx** [comment]
I really want this feature to be implemented

**Comment by azeier** [comment]
Coming soon!
