### ISSUE TITLE
Bombs placed in opponent's deck aren't being counted properly when drawn.

### ISSUE THREAD

**Issue by abrownhearth** [HearthSim/Hearthstone-Deck-Tracker#3988]
### Expected Behavior
When my opponent draws a bomb, I expect the counter of bombs in their decklist to go down by 1.

### Actual Behavior
When my opponent draws a bomb, the number of bombs in their decklist doesn't change.

### Steps to reproduce behavior
Play Bomb generating cards and wait for them to be drawn.

**Comment by ErichNiem** [comment]
Hi just noticed this too, will this be fixed.
