### ISSUE TITLE
"Show card flavor text on mouseover" not working properly

### ISSUE THREAD

**Issue by xavierdtd** [HearthSim/Hearthstone-Deck-Tracker#3990]
### Expected Behavior

The tooltip reads, "board/hand" yet it only works for minions on the board. Hovering over a card in your hand doesn't cause the flavor text box to show.

**Comment by xavierdtd** [comment]
y'all are just going to ignore this, huh?

**Comment by xavierdtd** [comment]
okay thanks guys, glad to see you pay attention.

**Comment by xavierdtd** [comment]
are you working on a fix for this at all? @azeier

**Comment by xavierdtd** [comment]
fuck you guys for ignoring me.

**Comment by Zawodowiec1532** [comment]
🤦‍♂️
