### ISSUE TITLE
Please run HS and HDT as admin!?! broken deck tracker.

### ISSUE THREAD

**Issue by ryannmerrell** [HearthSim/Hearthstone-Deck-Tracker#3992]
Every time I start hearthstone deck tracker one of a couple of things happens. Typically I get a message prompting me to run both programs as an administrator because they have different permissions. If not that, then it opens normally and goes into no deck mode, but will not come out of no deck mode unless I close hearthstone. My deck tracker has also stopped updating any new decks I've made. I've done fresh reinstalls and scanned hearthstone for errors. I have confirmed the correct locations for log files and double-checked the permissions of both programs through my antivirus. I have also just disabled the anti-virus. Nothing seems to work. Also, I do not code but can't find any information on this that has been posted recently. This all started when HDT got an update for galakrond interactions and stuff.

**Comment by riQQ** [comment]
Please provide the HDT log corresponding to this problem. See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#hdt-log-files.
