### ISSUE TITLE
Winrate Won't show

### ISSUE THREAD

**Issue by YourExposed** [HearthSim/Hearthstone-Deck-Tracker#3995]
### Expected Behavior
What did you expect to happen?: I expected the winrate to be shown above my deck

### Actual Behavior
What did actually happen?: My deck was not shown above my deck

### Steps to reproduce behavior
Can you reproduce it? How?: No idea, I just recently re-installed the tracker because i've been getting back into hearthstone. I currently have 11 games logged on my pirate warrior deck.  (12 after screenshot)
![Hearthstone Screenshot 01-03-20 22 32 18](https://user-images.githubusercontent.com/46252449/71760903-61813680-2e79-11ea-9033-05127732cf84.png)

### Log/Screenshots
See attached file >

**Comment by YourExposed** [comment]
Oops, just realized print screen doesn't show hstracker, uploading a second screenshot

**Comment by YourExposed** [comment]
![4b50921ca5164db7f735e91a94528bba](https://user-images.githubusercontent.com/46252449/71760956-e1a79c00-2e79-11ea-837d-094dcc5f74b7.jpg)

**Comment by riQQ** [comment]
Have you checked the option?
![option](https://user-images.githubusercontent.com/3404787/71764473-97113880-2ee8-11ea-8942-d47d0b76a3dc.png)

**Comment by YourExposed** [comment]
That fixed it, thank you. I was looking in the wrong spot.
