### ISSUE TITLE
Feature Request: Card Flavor Text on Mouseover (hand)

### ISSUE THREAD

**Issue by xavierdtd** [HearthSim/Hearthstone-Deck-Tracker#4003]
Card Flavor text shows up when hovering over a minion on board, and that's a great feature! I would love to be able to have that happen for cards held in hand as well. Hovering over a card in hand currently does not trigger any flavor text box.

**Comment by azeier** [comment]
Please do not create duplicate issues.

**Comment by xavierdtd** [comment]
so how about you actually take into account what I'm saying then? simple, really.

**Comment by riQQ** [comment]
Duplicate of #3990
