### ISSUE TITLE
HDT window freezes after some time.

### ISSUE THREAD

**Issue by omgfrost** [HearthSim/Hearthstone-Deck-Tracker#4005]
### Log/Screenshots

Hello,
Every now and then i got this:
![Xrex1Mc](https://user-images.githubusercontent.com/3404787/74478996-b66b9000-4eae-11ea-8b01-f4f1e6ec42d7.png)
completely screwed up window in which can't do anything but tray icon close and run it again.
Logs attached.
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/4184905/hdt_log.txt)

**Comment by riQQ** [comment]
Did this happen after opening a pack? Have you maybe noticed a behavioral pattern before this bugs happens?

**Comment by omgfrost** [comment]
> Did this happen after opening a pack? Have you maybe noticed a behavioral pattern before this bugs happens?

Nope, no opening packs related. It's just during running hearthstone as normal, play as normal and after a match when i go consulting deck tracker i can't click, i can't do anything but close the tray icon and restart it. Sad. Please fix.

**Comment by riQQ** [comment]
There might be nothing in the logs for this issue. Could you please post another log and the exact time it happened when it occurs again? We might be able to crossreference the logs and find something.
Without more information this is going to be a tough one.

**Comment by omgfrost** [comment]
i've noticed that if i dont click x to close and send to systray the deck tracker is working and not freezing and all the stats remain unstuck. i'll attach the log again because i'd like to leave it in the systray.
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/4203729/hdt_log.txt)

**Comment by omgfrost** [comment]
Here we go again...made bunch of games...hdt in systray and here it is: https://i.imgur.com/5eTJxQi.png
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/4204315/hdt_log.txt)
