### ISSUE TITLE
Wrath Weaver is listed as a Demon instead of Other in BG tier 1

### ISSUE THREAD

**Issue by Maldini999** [HearthSim/Hearthstone-Deck-Tracker#4006]
## Bug report
Wrath Weaver is listed as a Demon instead of Other in BG tier 1

### Expected Behavior

Wrath Weaver to be listed as Other in BG tier 1

**Comment by busches** [comment]
It has demon synergy, same reason Pack Leader is listed as beast in tier 3.

**Comment by azeier** [comment]
This is working as intended.
