### ISSUE TITLE
[Feature Request] Add Hakkar, the Soulflayer tracker

### ISSUE THREAD

**Issue by Doomelf** [HearthSim/Hearthstone-Deck-Tracker#4016]
It would be nice if there was a way to keep track of the total damage corrupted bloods currently in the opponent's deck would do.

**Comment by riQQ** [comment]
Can't you just multiply the Corrupted Bloods in the opponents deck list by 3?

**Comment by Doomelf** [comment]
Or maybe have the tracker list the number of bloods in his deck then? Just like how it keeps track of the other counters.
