### ISSUE TITLE
How to diable the compare heroes hsreplay button/banner?

### ISSUE THREAD

**Issue by gendalv** [HearthSim/Hearthstone-Deck-Tracker#4020]

**Comment by dnarik** [comment]
Same question - I don't get the overlay for minions in different tavern tiers unless I click on this pop-up, and I don't want to

**Comment by azeier** [comment]
You can disable it under `options > tracker > notifications > show hero notification at start of battlegrounds games`.

The minions overlay will also show up once you pick a hero, regardless of whether you click the toast.
