### ISSUE TITLE
Bombs not tracked correctly

### ISSUE THREAD

**Issue by WildMonkeyLover** [HearthSim/Hearthstone-Deck-Tracker#4021]
### Expected Behavior
Keep proper track of bombs in opponent's deck.

### Actual Behavior
The count does not go down when a bomb is drawn by opponent.

### Steps to reproduce behavior
Always happens.

### Log/Screenshots
N/A

**Comment by abrownhearth** [comment]
Duplicate Issue: https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3988

**Comment by riQQ** [comment]
Duplicate of #3988
