### ISSUE TITLE
Can't build: HearthMirror repository not found

### ISSUE THREAD

**Issue by RedHatter** [HearthSim/Hearthstone-Deck-Tracker#4022]
I'm attempting to build HDT from source but when I run bootstrap I get the follow errors. It looks like the HearthSim/HearthMirror repository doesn't exist anymore. Did it move or something?

```
git : Cloning into 'HearthMirror'...
At C:\Users\Timothy Johnson\Desktop\Hearthstone-Deck-Tracker-master\bootstrap.ps1:26 char:1
+ git clone "https://github.com/HearthSim/HearthMirror" "HearthMirror"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Cloning into 'HearthMirror'...:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
remote: Repository not found.
fatal: repository 'https://github.com/HearthSim/HearthMirror/' not found
```

**Comment by azeier** [comment]
Should be available again now.

**Comment by icetbr** [comment]
It disappeared again

**Comment by sneadsd** [comment]
I'm running into this issue now. I've only been able to find broken links to the HearthMirror repo.

**Comment by riQQ** [comment]
@sneadsd HearthMirror is not open source anymore. But the HDT build should download a compiled HearthMirror.dll.
