### ISSUE TITLE
Missing Card Art Since Newest Update

### ISSUE THREAD

**Issue by DanTheMan1830** [HearthSim/Hearthstone-Deck-Tracker#4024]
### Expected Behavior

In both the deck viewer and the in-game overlay, the card images & titles are supposed to be visible.

### Actual Behavior

The card art in the deck viewer, as well as in the in-game overlay for both me and my opponent's decks, is completely missing. There are also no card titles.

### Steps to reproduce behavior

This has happened since the newest update, I tried exiting the program and restarting it, as well as making a trivial change to my deck for the program to refresh as described in a similar bug report, but it wasn't fixed.

### Log/Screenshots

![2020-04-01 (1)](https://user-images.githubusercontent.com/25014576/78172149-cc0f2780-7412-11ea-8d78-421ff19687a0.png)
![2020-04-01 (2)](https://user-images.githubusercontent.com/25014576/78172151-cd405480-7412-11ea-8419-451b9b1915d5.png)

**Comment by azeier** [comment]
Try reinstalling. You can download the installer from https://hsreplay.net/downloads

**Comment by DanTheMan1830** [comment]
That fixed it, thanks!
