### ISSUE TITLE
System.TypeLoadException crash every time I run the program

### ISSUE THREAD

**Issue by nenko91** [HearthSim/Hearthstone-Deck-Tracker#4025]
## Bug report
The program gets crash report every time I start it.
It works if I don't close the crash report window. But if I close it, it terminates the program.

### Log/Screenshots

![hsCrash](https://user-images.githubusercontent.com/20682403/78183830-3a82d280-7471-11ea-9c1d-15a58b10c261.png)

**Comment by riQQ** [comment]
It's the Endgame plugin. Remove it or make sure you have the latest version of the plugin.

**Comment by azeier** [comment]
This should no longer happen as of https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/0ff2281f467536f88c01c832eea65cd1ea535f31
