### ISSUE TITLE
HDT not working in battleground when millhouse played

### ISSUE THREAD

**Issue by shyuni4u** [HearthSim/Hearthstone-Deck-Tracker#4026]
### Expected Behavior
Turn count and overlay working

### Actual Behavior
Turn count and overlay not working

### Log/Screenshots
![millhouse](https://user-images.githubusercontent.com/17681984/78231460-ccd8b400-750d-11ea-803c-b92db66514b0.png)

**Comment by azeier** [comment]
Fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/ffdf7e9bf5101a3e6cb2f788142c3766625065ec
