### ISSUE TITLE
Mage Secret tracker incorrectly grays out Mirror Image and Explosive Runes when a Dormant minion is played.

### ISSUE THREAD

**Issue by JustinDao** [HearthSim/Hearthstone-Deck-Tracker#4030]
### Expected Behavior
- Mirror Image and Explosive Runes do not become grayed out. 

### Actual Behavior
- Mirror Image and Explosive Runes become grayed out. 

### Steps to reproduce behavior
- Demon Hunter (you) vs. Mage
- Mage plays a secret
- Play Imprisoned Antaen

### Log/Screenshots
![image](https://user-images.githubusercontent.com/1694659/78842063-df426a00-79b3-11ea-9aa7-80b2fc3fbde3.png)

**Comment by azeier** [comment]
After some quick testing, the only "on play" secrets that can not trigger on dormant minions are:
- Snipe
- Explosive Runes
- Potion of Polymorph
- Repentance

Any secrets that don't directly affect the played minion still trigger:
- Mirror Entity
- Ambush
- Frozen Clone
- Hidden Cache
