### ISSUE TITLE
Secret tracker doesn't show Netherwind portal for mage secrets.

### ISSUE THREAD

**Issue by Trimutius** [HearthSim/Hearthstone-Deck-Tracker#4033]
## Bug report
Secret tracker doesn't show Netherwind portal for mage secrets.
### Expected Behavior
Netherwind portal should show up in all modes.

### Actual Behavior
Only 6 secrets instead of 7 are seen in Standard at least.

### Steps to reproduce behavior
Opponent plays a mage secret

**Comment by azeier** [comment]
Fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/9a78f6dbcb9acb6b5644f7e3b573bd39817bf1c1 (will be in the next update)

**Comment by artsev** [comment]
When the release is planned?

**Comment by azeier** [comment]
Sorry for the delay here. This has been fixed with v1.10.8.
