### ISSUE TITLE
Allow filtering games by rank

### ISSUE THREAD

**Issue by garyking** [HearthSim/Hearthstone-Deck-Tracker#4034]
This is a feature request.

Please allow us to filter games by rank. I think I can recall that we could do that before the new ranked system; but now, it seems like the option is no longer available?

**Comment by riQQ** [comment]
You have to select Mode = Ranked to filter for Leagues. Or do you want to filter for 1-5 Bronze league?

**Comment by garyking** [comment]
Okay thanks, that did it.
