### ISSUE TITLE
Kael'thas Sunstrider Leaking When Drawn By Opponent

### ISSUE THREAD

**Issue by abrownhearth** [HearthSim/Hearthstone-Deck-Tracker#4045]
Expected Behavior
Kael'thas Sunstrider should only show on opponent's decklist when played.

### Actual Behavior
Kael'thas Sunstrider appeared in opponent's decklist before being played.

### Steps to reproduce behavior
Play against someone with the card in their deck.

### Log/Screenshots
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/4546942/hdt_log.txt)
[Power.log](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/4546944/Power.log)

**Comment by willmiao** [comment]
This is not a bug.

From your logs, `Kael'thas Sunstrider` is drawn by `Fungal Fortunes` and then is discarded since it's a minion. Before it is discarded it is revealed to both players.
