### ISSUE TITLE
Whizbang Decks Issue (NoShow/"Reload Loop")

### ISSUE THREAD

**Issue by x-ProgrammEd-x** [HearthSim/Hearthstone-Deck-Tracker#4046]
### Expected Behavior
Whizbang decks are recognized and displayed properly

### Actual Behavior
Hello, I am sitting on v 1.10.8 and for the love of me can't bring the feature to work since initial release with v. 1.7.x - neither import (how to do it? is it manual?) nor recognition. As soon as I play Whizzbang HDT seems to be stuck in kind of a "deck reload loop", briefly displaying played (not a deck) cards for both, me and my opponent, then the card lists disappear. This happens over and over and is very distracting. Sometimes it does this for a few minutes and then a window pops up, saying it "can not identify deck" and gives me the option to select a deck or set to "use no deck". I'm struggling to describe it, please watch the youtube video (link below) for a better understanding (screen capture recorded with CamStudio).

Also, I can not find the option for recognition of Whizbang decks in settings - is there one?

Sadly it has always been like that for me. I've had it now and thus I am reporting it here.

[https://youtu.be/djIqTKKRGU8](url)

Any help would be appreciated

**Comment by ceceita** [comment]
https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/3779

try this ...
1 - remove the whizbang deck from your decks in the game
2 - if you have old whizbang decks already imported in the tracker delete them from tracker
3 - if you have deck autoimport disabled , enable it ( with advanced options marked , settings- tracker - importing - auto import new decks )
4 - go in game and create a whizbang deck , wait a bit and check if the autoimport found and imported all the whizbang recipes .. 
5- if it worked you can disable the autoimport if you want it turned off.
6- don't delete whizbang decks , you notice them by the "blizzard names" they have , but if you want you can delete other decks created by you and imported with autoimport.

If you dont want to view all the whizbang recipes in the tracker and becouse archive decks is bugged too , you must put them a tag like "whizbang" and filter them out.
If you fix the problem , after i can explaing the filter part better if you dont find how to do that yourself..

Sry for my bad english.

**Comment by x-ProgrammEd-x** [comment]
Hi, just quickly chiming in. Seems your procedure has solved the issue, thanks.

**Comment by Barragek0** [comment]
I'm borrowing a whizbang deck from a friend so I can't do the workaround, anything else I could do to fix this issue?

**Comment by x-ProgrammEd-x** [comment]
The Issue is back and persists despite the workaround. Any news on this?

**Comment by Dalarrus** [comment]
This issue has returned.

**Comment by beheh** [comment]
Hey all, I have some good news: Starting in the coming version of HDT, we will be automatically importing any Whizbang deck directly from the game, the moment Whizbang selects it at the start of a match. This will get rid of the previous manual task of updating these decks and should fix this issue and the other issues that were due to outdated Whizbang decks.

I'm leaving this issue open for the moment until the next version of HDT has shipped.

**Comment by beheh** [comment]
The rework launched today in HDT v1.23.11!
