### ISSUE TITLE
Plugins not showing up in HDT

### ISSUE THREAD

**Issue by Grandorx** [HearthSim/Hearthstone-Deck-Tracker#4050]
### Actual Behavior

Plugins worked fine before, but since updating to 1.11.2 the Plugins section in Options is empty, despite the plugins being present in the Plugins folder.
Plugins are present in the /roaming/ tree and seem to be copied correctly to /local/.

### Steps to reproduce behavior

Behaviour is consistent. Restarting does not help. Removing and re-installing the plugins did not help.

### Log/Screenshots

`1:02:07 PM|Info|PluginManager.LoadPluginsFromPath >> Loading Plugins... 1:02:07 PM|Error|PluginManager.GetModule >> Error loading C:\Users\XXX\AppData\Local\HearthstoneDeckTracker\app-1.11.2\Plugins\PackTracker.dll: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information. at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module) at System.Reflection.RuntimeModule.GetTypes() at System.Reflection.Assembly.GetTypes() at Hearthstone_Deck_Tracker.Plugins.PluginManager.GetModule(String pFileName, Type pTypeInterface) in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\Plugins\PluginManager.cs:line 196 1:02:07 PM|Error|PluginManager.GetModule >> Error loading C:\Users\XXX\AppData\Local\HearthstoneDeckTracker\app-1.11.2\Plugins\ArenaHelper\ArenaHelper.dll: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information. at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module) at System.Reflection.RuntimeModule.GetTypes() at System.Reflection.Assembly.GetTypes() at Hearthstone_Deck_Tracker.Plugins.PluginManager.GetModule(String pFileName, Type pTypeInterface) in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\Plugins\PluginManager.cs:line 196 1:02:07 PM|Info|Helper.GetCurrentRegion >> Region: EU`

https://user-images.githubusercontent.com/27730328/80597052-379ee180-8a1f-11ea-9e4b-7dca34182c33.png

**Comment by riQQ** [comment]
There was a breaking change for plugins. The plugins have to be update to work again:

> Hey,
> 
> I just wanted to let you know that the next HDT release will update several dependencies (see [HearthSim/Hearthstone-Deck-Tracker@11e1df4...6bb404d](https://github.com/HearthSim/Hearthstone-Deck-Tracker/compare/11e1df49c160...6bb404dedc50)) and upgrade [HearthDb](https://github.com/HearthSim/HearthDb) to .NET Standard 2.0.
> 
> This means the current release of PackTracker will no longer load. You will likely need to upgrade to at least .NET Framework 4.6.1 if you interact with HearthDb in any way.
> 
> The next version will likely be released on April 27th or 28th. I apologize for the short notice.
> 
> You can find a dev build for the new release [here](https://github.com/HearthSim/HDT-dev-builds/releases/latest) or on the [master branch of HDT](https://github.com/HearthSim/Hearthstone-Deck-Tracker).

Source: https://github.com/MGK82/PackTracker/issues/29#issue-607106306

**Comment by Grandorx** [comment]
Perfect - that fixed it.
