### ISSUE TITLE
As of the latest patch, Windows 8 users cant run HDT (.net 4.7 issue)

### ISSUE THREAD

**Issue by difel55** [HearthSim/Hearthstone-Deck-Tracker#4051]
### Expected Behavior
Run HDT as any other day

### Actual Behavior
I was prompted to download and use .net framework 4.7 which is not compatible with windows 8.

As a first, i would like to thank and congratulate you on the project!
You should be aware that the current version of HDT is not compatible with win 8 and as a result, probably several users along the globe are affected.

I understand that obsolete technology should be left behind, but personally i dont really consider win8 obsolete, especially for a project like HDT (meaning i dont find it essential to use .net framework that restricts a userbase).

Its up to you to judge this request and if it matters to your goals and policy.
Even a less feature-rich version that doesnt require .net 4.7.2 would be a better alternative to avoid such restrictions.
Cheers to everybody!

**Comment by azeier** [comment]
Both Windows 7 SP1 and Windows 8.1 support .NET Framework 4.8 ([see the official system requirements](https://docs.microsoft.com/en-us/dotnet/framework/get-started/system-requirements)). Microsoft no longer supports Windows 8 - you can [update to Windows 8.1 for free](https://support.microsoft.com/en-ca/help/15288/windows-8-update-to-windows-8-1).
