### ISSUE TITLE
Plugins "settings" no longer working

### ISSUE THREAD

**Issue by pagem** [HearthSim/Hearthstone-Deck-Tracker#4052]
### Expected Behavior

HDT auto updated this morning, now running version 1.11.7.

Every update you have to go into the settings of the Graveyard plugin to reset any customisations, such as window position, scale etc. Normally just clicking on the "settings" button within the plugin brings up the corresponding dialog window.

### Actual Behavior

Since the update nothing happens when you click on the "settings" button within the following plugins: Graveyard, Meta Detector. No settings are available and so, for instance in the example of Graveyard, all the Graveyard windows are overlayed on each other on the left hand side of Hearthstone when playing the game.

I have not applied an update to the plugins only HDT auto-updated.

### Steps to reproduce behavior

Update to 1.11.7 and try to access the plugin settings for Graveyard, Meta Detector.

**Comment by ceceita** [comment]
all old plugins are not working you need to update plugins manually if they are updated.

Problem is alot of plugins are not maintained anymore so will stop work forever without plugin developer updates.

**Comment by anonymous555** [comment]
There's an updated Graveyard plugin that works here

https://github.com/batstyx/Graveyard/releases
