### ISSUE TITLE
When i choose HSREPLAY Korean version Millhouse Manastorm in battle Ground, i can't see any information from deck tracker

### ISSUE THREAD

**Issue by hero864** [HearthSim/Hearthstone-Deck-Tracker#4054]
### Expected Behavior

Just working like other heroes in battleground

### Actual Behavior

Nothing happend, just can't see any kind of information in battleground

### Steps to reproduce behavior

1.Choose Millhouse manastorm in HSREPLAY Korean version
2. Doesn't work deck tracker

**Comment by azeier** [comment]
Duplicate of #4026
