### ISSUE TITLE
HDT crashes on start with .NET 4.5.2/4.7.2/4.8

### ISSUE THREAD

**Issue by KEKW666** [HearthSim/Hearthstone-Deck-Tracker#4065]
Windows 7 x64. What should I do?

> Problem signature:
  Problem Event Name	APPCRASH
  Application Name:	HearthstoneDeckTracker.exe
  Application Version:	1.11.7.3957
  Application Timestamp:	5eab7295
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.24384
  Fault Module Timestamp:	5c6e2226
  Exception Code:	c06d007e
  Exception Offset:	0000c5af
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1049
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by riQQ** [comment]
Please check if there is a corresponding .NET error in the event viewer and post it. See https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Reporting-Issues#windows-log-files (section `Windows log files`)

**Comment by KEKW666** [comment]
![1](https://user-images.githubusercontent.com/64682906/81378597-39982d00-9110-11ea-8878-c2cea4dda140.png)
![2](https://user-images.githubusercontent.com/64682906/81378601-3a30c380-9110-11ea-81c2-5f6e63586e32.png)

**Comment by riQQ** [comment]
Exception code: 0xc06d007e is `ERROR_MOD_NOT_FOUND`. So some module (= DLL) could not be found. In the past it was always the dll `wpfgfx_v0400.dll` (see also #3662).

Try the following
- Extract the attached Process Monitor configuration file
- Download [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon)
- Start Process Monitor
- `File > Import Configuration` selecting the extraced file 
- Start HDT
- Save the recorded data in Process Monitor via `File > Save...`
- Upload it here or with another file sharing service

[ProcmonConfiguration.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/4599899/ProcmonConfiguration.zip)

**Comment by KEKW666** [comment]
[Logfile.zip](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/4605367/Logfile.zip)

**Comment by KEKW666** [comment]
Okay riQQ. I installed KB4019990 for Windows 7 x64 and now HDT works. Big hanks for the help! Cheers!
