### ISSUE TITLE
HDT uses a lot of GPU when idle

### ISSUE THREAD

**Issue by riQQ** [HearthSim/Hearthstone-Deck-Tracker#4066]
## Bug report
Also discussed on reddit: https://www.reddit.com/r/hearthstone/comments/ggnhxw/hearthstone_deck_tracker_uses_60_of_gpu_and_20_of/

### Expected Behavior
HDT shouldn't use a lot of the GPU when idle

### Actual Behavior
HDT uses a lot of GPU when idle. This occurs when Hearthstone is not running and with the Overlays disabled in the HDT options. After quitting HDT the gpu usage goes back to 0%.

### Steps to reproduce behavior
Use HDT version 1.11.6 or higher (changed to .NET Framework 4.7.2 and higher version of MahApps.Metro). Further circumstances are yet unknown as it doesn't affect everyone.

### Log/Screenshots
![bug_idle_gpu_usage](https://user-images.githubusercontent.com/3404787/81311331-8da9ff80-9085-11ea-8209-7f75c19099a3.png)

**Comment by joc256** [comment]
According to procmon it seems to be spinning trying to open various Hearthstone logfiles, not sure why that would show up as GPU usage tho?

![image](https://user-images.githubusercontent.com/12632278/81473898-c8cd3f80-91f9-11ea-9e01-293fca58590a.png)

**Comment by riQQ** [comment]
That's normal and doesn't cause GPU usage.

**Comment by joc256** [comment]
Right I used the apitrace tool https://github.com/apitrace/apitrace to do a a trace of all GPU calls made by HDT:

`C:\"Program Files (x86)"\apitrace-msvc\apitrace.exe trace --api d3d9 "C:\Users\me\Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\bin\x86\Debug\Hearthstonedecktracker.exe"`

That gave me a 160MB "Hearthstonedecktracker.trace" which I was able to load in the "qapitrace" gui from the same project. I'm no expert on either C# or D3d but the icons shown in the screenshot seem to match some of the icons in the HDT UI so does this mean the entire app ui is somehow being redrawn using Direct3D every frame? That would explain the GPU usage certainly...

![image](https://user-images.githubusercontent.com/12632278/81496346-fb853f80-92ae-11ea-862d-41460c362ff8.png)

**Comment by joc256** [comment]
Window Detective http://windowdetective.sourceforge.net shows thousands of these "MilChannelNotify" messages being delivered to one of the HDT windows.

![image](https://user-images.githubusercontent.com/12632278/81501074-2c28a180-92ce-11ea-8681-0711979b4a64.png)

MilChannelNotify apparently is an internal WPF message used to tell its render thread to do some rendering. There aren't many Google hits but I found a few bugs that suggest it might be to do with animations still being run for hidden UI elements.

**Comment by DayKev** [comment]
Would listing .NET assembly/CLR versions installed be useful? I haven't been running into this bug from what I can tell (GPU usage seems appropriate, only rose ~4% after it started according to MSI Afterburner).

**Comment by bedire5069** [comment]
I have been running into this bug and GPU usage goes up to 41% for a few mins,  same as mentioned in "actual behavior" this started to happen after bobs buddy feature

**Comment by pendoza** [comment]
I have the same problem. GPU is normal watching YT and having HS open. 
![2020-05-12 18_56_05-Window](https://user-images.githubusercontent.com/18173119/81723647-73a45e80-9483-11ea-9306-d621d1479c57.png)

Having HDT open with it but not on active window (so minimized) it doesn't produce anything special.

![2020-05-12 19_05_43-2020_05_12_18_54_45_Window png - Paint](https://user-images.githubusercontent.com/18173119/81723949-e6153e80-9483-11ea-8e6e-ded364140770.png)

But if you want to use the program it shoots up to max. Even if you let it maximized but on background. So it seems to me that using the program lets it do all those things mentioned by others.
![2020-05-12 19_08_17-Hearthstone](https://user-images.githubusercontent.com/18173119/81724187-3db3aa00-9484-11ea-856d-9a04863ac12c.png)

**Comment by riQQ** [comment]
Are the ones with problems using a 144 Hz monitor?

**Comment by bedire5** [comment]
Yes using 144 Hz

**Comment by pendoza** [comment]
I have 2 monitors.

![2020-05-12 23_21_42-Settings](https://user-images.githubusercontent.com/18173119/81746826-66996680-94a7-11ea-9216-72d8d2818b6b.png)
![2020-05-12 23_21_14-Settings](https://user-images.githubusercontent.com/18173119/81746835-68632a00-94a7-11ea-810e-48581df2f7f4.png)

**Comment by Otto42** [comment]
Can confirm, HDT just jumps the GPU usage up to 20% and the CPU usage up to 10% for no reason. This is without HS or anything else of note running, just the main window of HDT does it.

Minimizing the main HDT window drops all usage to zero again. It appears to be only the main window causing this.

**Comment by asdman384** [comment]
confirm issue. HDT dramatically drains my GPU resource

**Comment by azeier** [comment]
Investigating this. Appears to be related to the deck picker component. Will update as I find out more.

**Comment by azeier** [comment]
I think I found & fixed the issue. 

It appears to be a problem with MahApps' `TextBoxHelper.IsWaitingForData`, though I have no idea why that would be. 

Here's a dev build. Can you guys try and see if you still have the same problems?

https://github.com/HearthSim/HDT-dev-builds/releases/download/v1.12.2.3976/HDT-Installer.exe
(This build will overwrite the existing installation and automatically update to the next HDT release once available)

**Comment by joc256** [comment]
That seems to have fixed the issue.

Before:
![before](https://user-images.githubusercontent.com/12632278/82411846-75b18300-9a6a-11ea-9c69-17aac4254fab.png)

After:

![after](https://user-images.githubusercontent.com/12632278/82411874-8235db80-9a6a-11ea-955b-13eaf1f37fb4.png)

Thanks!

**Comment by azeier** [comment]
Fantastic. This will be fixed with v1.12.3, which should roll out shortly.
