### ISSUE TITLE
HDT Overlay doesnt work, only shows 0/30

### ISSUE THREAD

**Issue by Sitnam91** [HearthSim/Hearthstone-Deck-Tracker#4070]
I expect HDT to work as it used to do till yesterday.

### Actual Behavior
When I play I can only see the overlay with 0/30 cards on both sides and if I minimize I cant open the HDT window while Im running Hearthstone.

I have tried to reinstall it, reboot it and reset the folder of the tracker and nothing works.

### Log/Screenshots
https://ibb.co/4PLYXfJ

**Comment by ceceita** [comment]
just wait , give them a bit of time , the new HS patch was just released

**Comment by otuyelu** [comment]
not working freezes

**Comment by a-laz** [comment]
I'm having the same issue

**Comment by fabianschonbeck** [comment]
Im having the same issue, too

**Comment by ActionJacksonATL** [comment]
I have this same problem; the HDT is slow, not very responsive and overlay only shows 0/30.  Was working last night.

**Comment by hashemi1711** [comment]
I have the same issue, I reinstalled and the issue still persists.

**Comment by jglatchney** [comment]
Same issue here; tried uninstall/reinstall; deck loaded as 30/30 and stayed that way the entire game; restarted computer; tried another game and went back to 0/30 with no cards showing

**Comment by levinjan** [comment]
hs devs mentioned new file system for hs. propably thats the reason why no deck tracker work

**Comment by funkyfoulek** [comment]
The gameplay.log is not create anymore by Hearthstone via the log.config in %localappdata%/blizzard/hearthstone. I think that's why HDT doesn't work !

**Comment by schneiderl** [comment]
Hearthstone deck tracker is already a consolidated thing and it already makes part of Hearthstone environment. It would be nice if Blizzar could show some respect and consideration for the maintainers of HS Deck tracker and notify them about those possibly feature-breaking patches.

Either way, keep up the good work. 

Awesome tool.

**Comment by ScroungerHS** [comment]
Same here. But I have additions to add. In addition to the decks not updating when in the play menu, any decks that are made and imported, they do not track when playing a game. Plus, opponents' decks do not track when in game. There is also now considerable lag when opening the constructed stats. And one more thing, the tracking for galakrond/c'thun/spells played etc, they are stuck at 1/1 or 6/6 with respect to each of their own.

I also exhausted the three options listed as a fix for this, the copying and pasting of the log file, the inclusion of the game path, and the uninstall+full deletion and then fresh install.

Additionally, I have deck tracker installed on two completely separate computers. Both were functioning just fine until yesterday(5/12/2020), both are now completely non functional.

**Comment by MisaRey** [comment]
When I'm out of the game, my tracker works normally. When you log in to the game, it freezes and does not respond to anything. And when I enter the game, only 0/30 cards are shown for both me and the opponent. Not fully working the counter galakrond and damage from the table. HDT hangs terribly during the game and sometimes does not start at all.

**Comment by lukewlms** [comment]
From @abrownhearth in the HSTracker repo:

> This is a known issue and was indeed caused by the latest update to Hearthstone. A lot of under the hood changes were made that affected HDT, HSTracker, and Arcane Tracker. We have to fix HDT first as its changes will affect HSTracker as well. We'll update here as we make progress!

https://github.com/HearthSim/HSTracker/issues/1135#issuecomment-627942880

**Comment by ZAMGZ** [comment]
> When I'm out of the game, my tracker works normally. When you log in to the game, it freezes and does not respond to anything. And when I enter the game, only 0/30 cards are shown for both me and the opponent. Not fully working the counter galakrond and damage from the table. HDT hangs terribly during the game and sometimes does not start at all.

Same,

I can't play without the Deck Tracker, just one game a day to test if it's back working or not.
If they don't fix it soon, HS will probably lose a lot of players.

**Comment by DuMarais9788** [comment]
I've got the same issue... and I also tried to reinstall HDT but nothing happened.. I hope they will be able to fixe this problem soon !!

**Comment by leoli2019** [comment]
Good , I am not alone

**Comment by lukewlms** [comment]
FYI all, v1.12.0 was released with a fix:

https://hsreplay.net/downloads/?hl=en

**Comment by nathanmchoi** [comment]
Works with 1.12.0.
