### ISSUE TITLE
Deck Tracker freezes when Hearthstone is opened or is already open

### ISSUE THREAD

**Issue by cbnsingram** [HearthSim/Hearthstone-Deck-Tracker#4072]

**Comment by AlienNight** [comment]
Same since new patch. Deck tracker freezes and doesn't appear on screen or it appears but bugged, not showing draws or cards left in your deck

**Comment by MisaRey** [comment]
Freeze tracker. The opponent's deck and mine are not shown. During the game begins to hang.

**Comment by schneiderl** [comment]
Same for me here. I've tried to reinstall it but even that does not seem to fix the problem.

**Comment by KaijiSama** [comment]
It doesn't work for me either. Doesn't show deck and freezes since latest HS patch.

**Comment by schneiderl** [comment]
I think this can be closed as the exact same issue is already being discussed on #4070.

**Comment by cbnsingram** [comment]
closing - see issue 4070.  Still no solution there, but more people attached.
