### ISSUE TITLE
Doesn't detect when "play" menu is open

### ISSUE THREAD

**Issue by dabruisa** [HearthSim/Hearthstone-Deck-Tracker#4073]
### Expected Behavior
When the "play" menu was opened in the Hearthstone app, I expected that the deck tracker would start importing decks. Also tried clicking "Import decks" expecting it to start importing the decks.

### Actual Behavior
The deck tracker did not detect by itself that I was in the play menu, nor did it detect it after I clicked the "Import decks" button. It still gave the message "Enter the 'Play' menu."

### Steps to reproduce behavior
Open the deck tracker and Hearthstone, go to the play area in Hearthstone. Attempt manual import of decks using the button in the deck tracker.

### Log/Screenshots
Not sure what a log is, but here's a screenshot. As you can see, I'm in the play menu but the deck tracker is still prompting me to enter it.
(https://user-images.githubusercontent.com/65270770/81771709-ba10b200-94b1-11ea-96ae-875ac4c1a458.png)

**Comment by InfernalDark** [comment]
Yep same here.

**Comment by Y-Pulse** [comment]
Me too, and I did all the FAQ recommended, even reinstalled the game...

**Comment by schneiderl** [comment]
I think this can be closed as the exact same issue is already being discussed on #4070.

**Comment by ScroungerHS** [comment]
Same here.  But I have additions to add.  In addition to the decks not updating when in the play menu, any decks that are made and imported, they do not track when playing a game.  Plus, opponents' decks do not track when in game.  There is also now considerable lag when opening the constructed stats.  And one more thing, the tracking for galakrond/c'thun/spells played etc, they are stuck at 1/1 or 6/6 with respect to each of their own.

I also exhausted the three options listed as a fix for this, the copying and pasting of the log file, the inclusion of the game path, and the uninstall+full deletion and then fresh install.

Additionally, I have deck tracker installed on two completely separate computers.  Both were functioning just fine until yesterday(5/12/2020), both are now completely non functional.

**Comment by dabruisa** [comment]
I believe they might be slightly different problems, as in that thread
there's no mention of being unable to import decks.

**Comment by riQQ** [comment]
Should work now
