### ISSUE TITLE
Deck is shown at battleground

### ISSUE THREAD

**Issue by Gaojianli** [HearthSim/Hearthstone-Deck-Tracker#4074]
### Expected Behavior
show battleground function

### Actual Behavior
Deck is shown at battleground

### Steps to reproduce behavior
just play battleground with friends
### Log/Screenshots
![image](https://user-images.githubusercontent.com/19235246/81775551-a00db880-951f-11ea-88f8-04747804ce46.png)

**Comment by AnthoSam** [comment]
same for me, any solution ? maybe an update will coming.

**Comment by NotPrecisellyaHeroButStillaProtagonist** [comment]
Same here.

**Comment by Verdelet** [comment]
I have the same issue

**Comment by szabo-roland** [comment]
Same issue here.

**Comment by nathanmchoi** [comment]
Seems to be fixed after 1.12.0. I tried it and it worked as intended after update.

**Comment by szabo-roland** [comment]
> 
> 
> Seems to be fixed after 1.12.0. I tried it and it worked as intended after update.

I can confirm too. I works in 1.12.0
