### ISSUE TITLE
Deck won't update in overlay while in game

### ISSUE THREAD

**Issue by Kwong486** [HearthSim/Hearthstone-Deck-Tracker#4075]
### Expected Behavior
Deck should be updating in game when cards go from deck to hand.

### Actual Behavior
Deck is static and nothing changes...opponents cards also don't update.

### Steps to reproduce behavior
?

**Comment by Bers2k** [comment]
Same problem.

**Comment by Verdelet** [comment]
Yup same issue

**Comment by Dextornater** [comment]
Me Too 
![image](https://user-images.githubusercontent.com/65298391/81831599-73649b80-9535-11ea-9f37-44b83b8a9a19.png)
seems to be crashing... 
Tried rebooting goes into nodeckmode then lock up cant change deck  etc

thx

**Comment by Kwong486** [comment]
I should also have said that I've rebooted the game, app, and pc several times...thought I messed up settings but i went through every single setting and could not fix it.

**Comment by Behlial** [comment]
Mine is freezing when I enter a game. It doesn't even pop the decks up.
Seems ok when I'm in the "lobby".
I've rebooted the game, app, and pc.

**Comment by benbenlaw** [comment]
got this as well

**Comment by milezeu** [comment]
Same issue here

**Comment by Puzl99** [comment]
Same issues here too... 
Also keeps dropping the deck list now-&-then. 
Going in to to no deck mode or not displaying what crads are in hand... Also what cards opponent has played. Basically unuseable atm.

**Comment by ZAMGZ** [comment]
> Mine is freezing when I enter a game. It doesn't even pop the decks up.
> Seems ok when I'm in the "lobby".
> I've rebooted the game, app, and pc.
> App version 1.11.9

Same

**Comment by Puzl99** [comment]
Also tried reinstalling .. to no avail

**Comment by DerfelKadarn** [comment]
This is obviously due to 17.2. BLZ says that they have reorganized assets. I'm sure the HDT team is working hard to get a compatible release out. In the meantime, back to the dark ages!

**Comment by nathanmchoi** [comment]
Seems to be fixed in 1.12.0.
