### ISSUE TITLE
Battlegrounds attack wrong

### ISSUE THREAD

**Issue by whitehatguy12** [HearthSim/Hearthstone-Deck-Tracker#4082]
### Expected Behavior
When in a battleground I'd expect the attack values to be equal to the damage in battleground stars, not the damage in minion attack.

### Actual Behavior
It shows the total minion attack.

### Steps to reproduce behavior
Just play battlegrounds.

**Comment by riQQ** [comment]
The attack counter is hidden for the next version (implemented by #4078).
