### ISSUE TITLE
"Copy Deck Code" button broken in Twitch for Chrome/Brave

### ISSUE THREAD

**Issue by moopypieloopy** [HearthSim/Hearthstone-Deck-Tracker#4090]
### Expected Behavior

When using the deck tracker overlay in Twitch, I expect to be able to copy the deck code by pressing the "Copy Deck Code" button.

### Actual Behavior

Pressing the "Copy Deck Code" button does nothing when using the Chrome or Brave browser.
### Steps to reproduce behavior

Open Chrome, watch your favorite streamer that uses hsreplay's deck tracker, click on "Copy Deck Code". Notice it does not say "Copied!", notice you cannot paste the deck code, as you haven't copied it. Repeat for Firefox and notice it works as intended.

**Comment by beheh** [comment]
I believe we fixed this a long time ago (HearthSim/twitch-hdt-frontend#50).
