### ISSUE TITLE
Can't build the latest release

### ISSUE THREAD

**Issue by ancientplayer** [HearthSim/Hearthstone-Deck-Tracker#4099]
Sorry for the probably trivial topic and the debug messages in german language (i think they are still straightforward to understand).
I'm trying to build HDT for the first time (wanting to create my own plugin).

1. I clone the git.

2. I run the bootstrap (no errors occur; see below):
MSBuild auto-detection: using msbuild version '16.6.0.22303' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin'.
Alle in "packages.config" aufgeführten Pakete sind bereits installiert.
git version 2.27.0.windows.1
Fetching HearthDb...
Fetching HearthMirror...
Fetching HSReplay...
Fetching BobsBuddy...
Cloning into 'HDT-Localization'...
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 1218 (delta 31), reused 5 (delta 1), pack-reused 1172 eceiving objects:  99% (1206/1218), 3.71 MiB | 2.47 MiB/s
Receiving objects: 100% (1218/1218), 4.37 MiB | 2.60 MiB/s, done.
Resolving deltas: 100% (926/926), done.
Cloning into 'hs-card-tiles'...
remote: Enumerating objects: 4843, done.
remote: Counting objects: 100% (4843/4843), done.
remote: Compressing objects: 100% (4841/4841), done.
remote: Total 4843 (delta 0), reused 4837 (delta 0), pack-reused 0 eceiving objects: 100% (4843/4843), 20.22 MiB | 3.02 Receiving objects: 100% (4843/4843), 21.24 MiB | 2.87 MiB/s, done.
Updating files: 100% (5591/5591), done.

3. I open the project in visual studio 2019.

4. I build HDT and receive 9 errors related to BobsBuddyInvoker.cs (missing definitions):
Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler	CS1061	"Minion" enthält keine Definition für "receivesPutricidePower", und es konnte keine zugängliche receivesPutricidePower-Erweiterungsmethode gefunden werden, die ein erstes Argument vom Typ "Minion" akzeptiert (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).	Hearthstone Deck Tracker	C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\BobsBuddy\BobsBuddyInvoker.cs	163	Aktiv
Fehler	CS1061	"TestInput" enthält keine Definition für "mySide", und es konnte keine zugängliche mySide-Erweiterungsmethode gefunden werden, die ein erstes Argument vom Typ "TestInput" akzeptiert (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).	Hearthstone Deck Tracker	C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\BobsBuddy\BobsBuddyInvoker.cs	300	Aktiv
Fehler	CS1061	"TestInput" enthält keine Definition für "theirSide", und es konnte keine zugängliche theirSide-Erweiterungsmethode gefunden werden, die ein erstes Argument vom Typ "TestInput" akzeptiert (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).	Hearthstone Deck Tracker	C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\BobsBuddy\BobsBuddyInvoker.cs	304	Aktiv
Fehler	CS1061	"Minion" enthält keine Definition für "receivesPutricidePower", und es konnte keine zugängliche receivesPutricidePower-Erweiterungsmethode gefunden werden, die ein erstes Argument vom Typ "Minion" akzeptiert (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).	Hearthstone Deck Tracker	C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\BobsBuddy\BobsBuddyInvoker.cs	308	Aktiv
Fehler	CS1061	"TestInput" enthält keine Definition für "mySide", und es konnte keine zugängliche mySide-Erweiterungsmethode gefunden werden, die ein erstes Argument vom Typ "TestInput" akzeptiert (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).	Hearthstone Deck Tracker	C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\BobsBuddy\BobsBuddyInvoker.cs	336	Aktiv
Fehler	CS1061	"TestInput" enthält keine Definition für "theirSide", und es konnte keine zugängliche theirSide-Erweiterungsmethode gefunden werden, die ein erstes Argument vom Typ "TestInput" akzeptiert (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).	Hearthstone Deck Tracker	C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\BobsBuddy\BobsBuddyInvoker.cs	340	Aktiv
Fehler	CS1061	"TestInput" enthält keine Definition für "mySide", und es konnte keine zugängliche mySide-Erweiterungsmethode gefunden werden, die ein erstes Argument vom Typ "TestInput" akzeptiert (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).	Hearthstone Deck Tracker	C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\BobsBuddy\BobsBuddyInvoker.cs	355	Aktiv
Fehler	CS1061	"TestInput" enthält keine Definition für "theirSide", und es konnte keine zugängliche theirSide-Erweiterungsmethode gefunden werden, die ein erstes Argument vom Typ "TestInput" akzeptiert (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).	Hearthstone Deck Tracker	C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\BobsBuddy\BobsBuddyInvoker.cs	355	Aktiv
Fehler	CS1061	"Minion" enthält keine Definition für "receivesPutricidePower", und es konnte keine zugängliche receivesPutricidePower-Erweiterungsmethode gefunden werden, die ein erstes Argument vom Typ "Minion" akzeptiert (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).	Hearthstone Deck Tracker	C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\BobsBuddy\BobsBuddyUtils.cs	46	Aktiv

I guess something related to bobs buddy is missing in the git then? Any ideas how i can fix this issue?
Thanks for your help.

**Comment by riQQ** [comment]
Have you run `bootstrap.ps1`?

**Comment by ancientplayer** [comment]
Thanks for the response.
As i said in step 2 above, yes I have run bootstrap.ps1.

**Comment by riQQ** [comment]
Sorry, I missed that.

Please paste the complete build output.

**Comment by ancientplayer** [comment]
Here is the build output:


1>------ Erstellen gestartet: Projekt: HearthWatcher, Konfiguration: Debug x86 ------
1>  HearthWatcher -> C:\Users\sohel\Documents\HDT\HDT\HearthWatcher\bin\x86\Debug\HearthWatcher.dll
2>------ Erstellen gestartet: Projekt: Hearthstone Deck Tracker, Konfiguration: Debug x86 ------
2>  Solution: C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\..\
2>  Project: C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\
2>  Target: C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\bin\x86\Debug\
2>  Skip git sync: False
2>  Skip resource copy: False
2>  
2>  Fetching HearthDb...
2>  Fetching HearthMirror...
2>  Fetching HSReplay...
2>  Fetching BobsBuddy...
2>  
2>  Resetting HDT-Localization to origin/master
2>  From https://github.com/HearthSim/HDT-Localization
2>     dc0ff3b..825d5d6  master       -> origin/master
2>   + 5ea3fff...c5d69ba l10n_master2 -> origin/l10n_master2  (forced update)
2>  HEAD is now at 825d5d6 New Crowdin translations (#195)
2>  
2>  Copying files from C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\..\HDT-Localization to C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\Properties\
2>  
2>  Copying files from C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\\Images\Themes to C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\bin\x86\Debug\Images\Themes
2>  
2>  Copying files from C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\..\ to C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\Resources
2>  
2>  Done.
2>C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\BobsBuddy\BobsBuddyInvoker.cs(163,14,163,36): error CS1061: "Minion" enthält keine Definition für "receivesPutricidePower", und es konnte keine zugängliche receivesPutricidePower-Erweiterungsmethode gefunden werden, die ein erstes Argument vom Typ "Minion" akzeptiert (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
2>C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\BobsBuddy\BobsBuddyInvoker.cs(300,29,300,35): error CS1061: "TestInput" enthält keine Definition für "mySide", und es konnte keine zugängliche mySide-Erweiterungsmethode gefunden werden, die ein erstes Argument vom Typ "TestInput" akzeptiert (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
2>C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\BobsBuddy\BobsBuddyInvoker.cs(304,29,304,38): error CS1061: "TestInput" enthält keine Definition für "theirSide", und es konnte keine zugängliche theirSide-Erweiterungsmethode gefunden werden, die ein erstes Argument vom Typ "TestInput" akzeptiert (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
2>C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\BobsBuddy\BobsBuddyInvoker.cs(308,15,308,37): error CS1061: "Minion" enthält keine Definition für "receivesPutricidePower", und es konnte keine zugängliche receivesPutricidePower-Erweiterungsmethode gefunden werden, die ein erstes Argument vom Typ "Minion" akzeptiert (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
2>C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\BobsBuddy\BobsBuddyUtils.cs(46,12,46,34): error CS1061: "Minion" enthält keine Definition für "receivesPutricidePower", und es konnte keine zugängliche receivesPutricidePower-Erweiterungsmethode gefunden werden, die ein erstes Argument vom Typ "Minion" akzeptiert (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
2>C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\BobsBuddy\BobsBuddyInvoker.cs(336,34,336,40): error CS1061: "TestInput" enthält keine Definition für "mySide", und es konnte keine zugängliche mySide-Erweiterungsmethode gefunden werden, die ein erstes Argument vom Typ "TestInput" akzeptiert (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
2>C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\BobsBuddy\BobsBuddyInvoker.cs(340,34,340,43): error CS1061: "TestInput" enthält keine Definition für "theirSide", und es konnte keine zugängliche theirSide-Erweiterungsmethode gefunden werden, die ein erstes Argument vom Typ "TestInput" akzeptiert (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
2>C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\BobsBuddy\BobsBuddyInvoker.cs(355,30,355,36): error CS1061: "TestInput" enthält keine Definition für "mySide", und es konnte keine zugängliche mySide-Erweiterungsmethode gefunden werden, die ein erstes Argument vom Typ "TestInput" akzeptiert (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
2>C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\BobsBuddy\BobsBuddyInvoker.cs(355,58,355,67): error CS1061: "TestInput" enthält keine Definition für "theirSide", und es konnte keine zugängliche theirSide-Erweiterungsmethode gefunden werden, die ein erstes Argument vom Typ "TestInput" akzeptiert (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
2>C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\Controls\OutlinedTextBlock.cs(223,21,225,46): warning CS0618: '"FormattedText.FormattedText(string, CultureInfo, FlowDirection, Typeface, double, Brush, NumberSubstitution, TextFormattingMode)" ist veraltet: "Use the PixelsPerDip override"
2>C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\UITheme.cs(118,23,118,24): warning CS0168: Die Variable "e" ist deklariert, wird aber nie verwendet.
2>C:\Users\sohel\Documents\HDT\HDT\Hearthstone Deck Tracker\Utility\Themes\CardTextImageBuilder.cs(13,16,13,132): warning CS0618: '"FormattedText.FormattedText(string, CultureInfo, FlowDirection, Typeface, double, Brush)" ist veraltet: "Use the PixelsPerDip override"
========== Erstellen: 1 erfolgreich, 1 fehlerhaft, 0 aktuell, 0 übersprungen ==========

**Comment by riQQ** [comment]
Can you check the references of the HDT project in Visual Studio? Any yellow warnings? Does the path in the properties of the references point to `..\lib\<dll-name>`?

**Comment by azeier** [comment]
This should all be fixed if you pull the latest changes.

**Comment by chucklu** [comment]
I need to set the  environment  variable  PATH with `C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin` to skip the error "msbuild is not recognized as the name of a cmdlet"

**Comment by claybo100** [comment]
@ancientplayer hey there, i've been looking for you... was wondering if you'd answer some terra mystica questions for me. Feel free to message me on discord- claybo
