### ISSUE TITLE
Found unknown cards with latest release ( from 2 hours ago )

### ISSUE THREAD

**Issue by ngvirus** [HearthSim/Hearthstone-Deck-Tracker#4100]
### Expected Behavior

With the release from few hours ago i believe i should see stats for new cards - pirates.
### Steps to reproduce behavior

enter a game, if you have pirates the error is there.

### Log/Screenshots

![image](https://user-images.githubusercontent.com/5470026/84210364-225aaf80-aac1-11ea-922d-37b1342e798a.png)
![image](https://user-images.githubusercontent.com/5470026/84210463-6e0d5900-aac1-11ea-87d1-59d59c7d14ae.png)

**Comment by azeier** [comment]
This is working as intended and will be back to normal with the next release.
