### ISSUE TITLE
(Korean version HDT)When i choose Millhouse Manastorm in battleground than HDT doesn't work for that round

### ISSUE THREAD

**Issue by hero864** [HearthSim/Hearthstone-Deck-Tracker#4104]
### Log/Screenshots
![버그1](https://user-images.githubusercontent.com/64659754/84810398-43ce1500-b046-11ea-8ba7-42261fc16979.png)

Just printed "Waiting for combat" and nothing more
This issue started since when Millhouse Manastorm added in Battleground for Korean version of HDT

**Comment by azeier** [comment]
Duplicate of #4026
