### ISSUE TITLE
Suggestion for adding a hotkey

### ISSUE THREAD

**Issue by omgfrost** [HearthSim/Hearthstone-Deck-Tracker#4113]
Hello,
i'd really like to have a "toggle gold overlay" as an option for binding it to a hotkey.
Since i'm not playing in full screen my Gold overlay stay over my current gold\Orbs when i navigate the shop, so i'd like to toggle gold overlay to actually see how much of above stuff i've left.
Hope you take this in consideration
Thanks in advance
Frost

**Comment by howiieb** [comment]
When "Gold progress always visible" in Overlay -> General is unticked, you can still see your gold progress by mousing over your gold total ingame. Is this sufficient?

**Comment by omgfrost** [comment]
well, i just tested it and even if it's a workaround i'd still prefer a hotkey to toggle it.
So right now i binded ctrl+q as toggling full overlays so when i want gold progress off i can use this one.
But anyway this is for the whole overlay. Gold progress hotkey would be very appreciated.
I can wait, there's no hurry as i said i got my "tools" to solve it but still...
Looking forward for it, if this will never happen, well..i guess i'll stick as said above
Thanks.
