### ISSUE TITLE
Overall stats, stats-recording without selected deck

### ISSUE THREAD

**Issue by azeier** [HearthSim/Hearthstone-Deck-Tracker#412]
I _finally_ (somewhat) finished this!

Short summary:
- Games played without a selected deck will be recorded now
- Stats screen includes an "overall" tab (this is also where you can find those games)

**Backup your files in "%appdata%/HearthstoneDeckTracker"**, I don't think this should cause any trouble but who knows. 
[**Download here**](http://www.mediafire.com/download/tlnx7m3xgdpgcrx/Hearthstone_Deck_Tracker-v0.5.11_PRE1.zip) (or just build master) - feedback on this would be much appreciated.

**Comment by culinko** [comment]
"@Epix37	clicking a selected deck deselects it (#412)"

Was this function lost with the new deck selection layout?

**Comment by Epix37** [comment]
More removed than lost, but yes. I think being able to select "no deck" via the `TRACKER` menu and the try icon context menu is fine.
