### ISSUE TITLE
Secret Tracker: Nether Portal Removed Mistakenly

### ISSUE THREAD

**Issue by abrownhearth** [HearthSim/Hearthstone-Deck-Tracker#4121]
### Expected Behavior
If a spell is countered by Counterspell, Nether Portal still could be a Secret on opponent's board.

### Actual Behavior
User played a spell. That spell triggered opponent's Counterspell. Nether Portal was removed from Secret Helper since user played a secret and didn't trigger Nether Portal.

**Comment by riQQ** [comment]
Fixed by a48a8cd11d8ccc05b21b625365b3720e1738c678
