### ISSUE TITLE
Whizbang decks are in german

### ISSUE THREAD

**Issue by mmiat** [HearthSim/Hearthstone-Deck-Tracker#4125]
in HSDT the Whizbang decks' names are in german:
![Screenshot 2020-08-08 22 06 01](https://user-images.githubusercontent.com/11910225/89718927-8f0c0080-d9c3-11ea-9a62-245128804436.png)

**Comment by azeier** [comment]
Indeed they are! Thanks for letting us know, this should now be fixed when importing them again (without needing an HDT update).

To get the correct names you will have to
- Restart HDT to get the latest whizbang deck lists
- Delete all the ones with a german name
- Enter the "Play" menu to re-import them
