### ISSUE TITLE
Outdated plugin on wiki

### ISSUE THREAD

**Issue by Kertic** [HearthSim/Hearthstone-Deck-Tracker#4137]
### Expected Behavior
The plugins page would reflect the updated status of plugins

### Actual Behavior
The plugins page incorrectly states that the Dust utility plugin is active when it is not

### Steps to reproduce behavior
https://github.com/CLJunge/Spawn.HDT.DustUtility/issues/4
Look at this issue
Then look at https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Available-Plugins
See how the creator says "it doesn't work" but the wiki does not say "this plugin is outdated"

I'm not sure how else to bring up that its outdated, I hope the github issues is the place.

**Comment by beheh** [comment]
The page has been updated, thanks!
