### ISSUE TITLE
Screen cut in half?

### ISSUE THREAD

**Issue by DreikFt** [HearthSim/Hearthstone-Deck-Tracker#4154]
### Expected Behavior

I wanted to use the tracker normally
### Actual Behavior

Its like the bottom of my screen is pushed up to the middle and i cannot set my cards and else any lower because they disappear
### Log/Screenshots

Screenshot 1: https://cdn.discordapp.com/attachments/282271461853626368/760677962114138112/unknown.png
Screenshot 2: https://cdn.discordapp.com/attachments/282271461853626368/760678075570061322/unknown.png

**Comment by beheh** [comment]
Is Hearthstone possibly running on a secondary monitor with a different resolution? Or do you have a secondary monitor with a different resolution?

**Comment by Vixys** [comment]
I came accross the same issue and seems to be caused by my second monitor which had the _Scale and Layout_ option at 150%.

When settings back to 100%, it works fine for me.

**Comment by beheh** [comment]
Duplicate of #3445.
