### ISSUE TITLE
Duels feature request

### ISSUE THREAD

**Issue by anonymous555** [HearthSim/Hearthstone-Deck-Tracker#4167]
Allow saving and stat tracking of duels decks across multiple runs.  They all start out with the base set of 15 cards.  Now the base deck is disconnected from each separate run.  Unify them somehow.  

Also track and display win/loss for duels enemies as you normally would show win/loss against a specific class.

**Comment by anonymous555** [comment]
Another duels feature.  For duels decks the hero power and treasure chosen are significant choices.   Have a way to specify those for a deck too.   For example see 

https://www.hearthstonetopdecks.com/duels-deck-builder/

**Comment by beheh** [comment]
Duels is no more.
