### ISSUE TITLE
Gold progress tracker no longer relevant

### ISSUE THREAD

**Issue by avejoe** [HearthSim/Hearthstone-Deck-Tracker#4180]
### Expected Behavior
Not to see "Wins:0/3 0/100G" in bottom right corner of display overlay.

### Actual Behavior
"Wins:0/3 (0/100G)" appears in bottom right corner of display overlay.

### Steps to reproduce behavior
Hover over the gold amount shown in bottom right corner of display.

**Comment by riQQ** [comment]
Was removed with #4179 for the next release.
