### ISSUE TITLE
Feature Request: In Battlegrounds, perform calculation assuming secret is ice block.

### ISSUE THREAD

**Issue by ericrbg** [HearthSim/Hearthstone-Deck-Tracker#4195]
With the arrival of the new update, we've had ice block added as something that is available to every hero. No other secrets are, but Bob's Buddy still understandably throws an error, thinking it could be Azakmazak and not wanting to give you bad outcomes. However, 99% of the time, the secret is ice block (and 100% of the time when not playing vs Azak). Could this be assumed in Bob's Buddy, maybe with a warning overlay that this doesn't take the secret into account?

**Comment by Jonysegal** [comment]
This is a great point, I'll add this in for non-Azakmazak heroes in the next HDT patch. I won't be able to do it for now for Azakmazak himself, but for other heroes it'll calculate normally.

**Comment by BramGoderie** [comment]
Sorry for necro-ing this thread, Did the feature not get added to the next patch, or has my update missed something?

**Comment by ericrbg** [comment]
Yeah to me this seems un-fixed right now still
