### ISSUE TITLE
I can see which cards in my opponent's hand were generated by their C'thun

### ISSUE THREAD

**Issue by CrimsonDoom** [HearthSim/Hearthstone-Deck-Tracker#4199]
### Expected Behavior
Presumably, I should not be able to see which cards my opponent's C'thun created since that isn't information I can have in-game.

### Actual Behavior
What actually happened is that the card in question had that little square icon overlaid on the card in question with a picture of C'Thun the Shattered. I've been seeing this for at least a week but only recently made the connection that it only ever seemed to happen against other C'Thun decks.

### Steps to reproduce behavior
I'd have trouble reproducing the issue on my own, since this is a problem with the opponent's overlay when they're running one specific card.

### Log/Screenshots
I only have the most recent incident available since I don't remember exactly when else I've encountered this.
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/5725382/hdt_log.txt)

**Comment by MathemagicalMLP** [comment]
I just noticed this as well. Any time C'Thun the Shattered is in my opponent's deck I can see which cards were generated by C'thun the Shattered and which specific card of those generated it is.
One additional thing I want to add is that any time I check "Hide card-marks" under Overlay -> Opponent in the tracker, it turns them off, then turns them back on if I uncheck it.
Just got a C'thun the Shattered in Duels, so I can upload a screenshot of what's happening.
![image](https://user-images.githubusercontent.com/76489623/102913700-22167600-444d-11eb-996b-8e729ee89940.png)

**Comment by riQQ** [comment]
Fixed by #4209
