### ISSUE TITLE
 The race values ​​on the battlefield were not translated into Korean.

### ISSUE THREAD

**Issue by paikend** [HearthSim/Hearthstone-Deck-Tracker#4205]
### Expected Behavior

Elementals and neutral race values ​​appear in English in Korean settings

### Actual Behavior

Translated into Korean that the values ​​of the elementals and neutral races are translated into English in the Korean setting.

### Steps to reproduce behavior

1. find in the Korean setting.
2. Replace values ​​that are not translated into Korean.
### Log/Screenshots

<img width="1536" alt="스크린샷 2021-01-02 오전 12 13 00" src="https://user-images.githubusercontent.com/26214518/103441407-23d40b00-4c91-11eb-9440-673ad9e5ebb6.png">

**Comment by beheh** [comment]
We did this a while ago in HDT, not sure about HSTracker. If this still occurs on macOS please report a new issue here: https://github.com/HearthSim/HSTracker/issues
