### ISSUE TITLE
Keeper Stalladris + Jade Idol

### ISSUE THREAD

**Issue by Drui7** [HearthSim/Hearthstone-Deck-Tracker#4210]
Hello!
[Keeper Stalladris] + [Jade Idol] = two spells of 1 mana each fall into the hand.
One of these spells mixes 3 new  [Jade Idol] into the deck, but the [Jade Idol]`s counter does not increase in the list of cards remaining in the deck.

**Comment by Drui7** [comment]
Card named [Jade Stash]

**Comment by beheh** [comment]
Fixed in 506f2cc2ca9d10de14924deebfa6d826dd64229e.
