### ISSUE TITLE
[BG] Greybough hero power doesn't seem to account reborn for simulations

### ISSUE THREAD

**Issue by PedroPerpetua** [HearthSim/Hearthstone-Deck-Tracker#4221]
## Bug report
Simulations for win chance doesn't seem to account reborn to work with Greybough hero power.
### Expected Behavior

See screenshot - expected 100% loss
### Actual Behavior

Win chance reports a 100% tie
### Steps to reproduce behavior

Fight Greybough with just an Acolyte of C'thun when you have just a Vulgar Homunculus

### Log/Screenshots

![](https://cdn.discordapp.com/attachments/321978794925752330/804342112224018452/unknown.png)

**Comment by ccnoecker** [comment]
Same issue if you fight a micro mummy with a rockpool or similar situation
