### ISSUE TITLE
[BG] Combat simulation not working after hearthstone internet reconnection

### ISSUE THREAD

**Issue by Nyi-code** [HearthSim/Hearthstone-Deck-Tracker#4222]
## Bug report
BB’s combat simulation not functional after internet reconnection in BG, even restart HDT won’t fix it for current match.
This is a well-known bug for some time, please take a look.

### Expected Behavior
Simulations still working for later turns after internet reconnection in BG.

### Actual Behavior
After reconnection, BB won’t calculate win rates for the rest of the turns, and panel keeps circling for the rest of the game.
I went through the log, and it seems HDT no longer have Board state info && matchInfo ect., after reconnection, thus no longer able to simulate?

### Steps to reproduce behavior
I’ve reproduced it 10+ times just to confirm, and it’s so common that everyone I know have encountered it many many times.
Step 1：disconnect hearthstone BG’s internet when about 5s left, resume internet after 3 seconds so it says “You were reconnected to your game. Resuming…”
Step 2：BG will skip combat phase, wait until next combat to see this problem occurs.
If not, try step 1 again, my experience is if BG disconnects for 2 two continuous battles, 100% glitches, if disconnect for one battle, 80% chance glitches. Don’t know what went wrong.
Please reproduce to see what happens, it'll really boost the experience if functional, thank you!!!
### Log/Screenshots
![2a](https://user-images.githubusercontent.com/62428040/106241018-43cefe00-6240-11eb-9216-a8670668302a.jpg)
![4a](https://user-images.githubusercontent.com/62428040/106241042-4f222980-6240-11eb-861a-6d899f41f9c8.jpg)
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/5892032/hdt_log.txt)

**Comment by Nyi-code** [comment]
Here's a video demo for it, please take a look. ( I cut the buying phase out since file's too big)

https://user-images.githubusercontent.com/62428040/106251328-cca16600-624f-11eb-8cbe-345a1d2cc167.mp4

**Comment by ShapeFriend** [comment]
Bumping. Experiencing same problem, would be very grateful to have both winrates displayed and disconnects each game.

**Comment by beheh** [comment]
This was fixed some time ago.
