### ISSUE TITLE
Suggestion: show odds on match with secrets (Battlegrounds)

### ISSUE THREAD

**Issue by Skydler** [HearthSim/Hearthstone-Deck-Tracker#4228]
It would be useful to see the odds of the match even if the opponent has a secret. Most of the time it's something like Ice Block and the odds are still relevant.
I don't think it would be difficult to ignore the secrets and show a hint telling the user it isn't taking secrets into account.
Please tell me if I'm wrong

**Comment by howiieb** [comment]
Seconding this. An alternative is to calculate odds fully for any player that is not running Prestidigitation and assume their secret must have come from the prizes.
