### ISSUE TITLE
[Mage secret] Rigged faire game greys out even though it hasn't been triggered

### ISSUE THREAD

**Issue by FowadIjaz** [HearthSim/Hearthstone-Deck-Tracker#4235]
### Expected Behavior
Rigged Faire game should remain highlighted when it is still in play when a player has checked for it. 

### Actual Behavior
Rigged faire game and all secrets get greyed out, even though rigged faire game is still in play

### Steps to reproduce behavior
Enemy plays rigged faire game. You check all secrets. On their next turn, rigged faire game is now greyed out, even though it is the secret in play.  

### Log/Screenshots
![Rigged Faire game](https://user-images.githubusercontent.com/63612037/107984859-e56f8280-6f96-11eb-9995-8cb2275c997c.png)

**Comment by swilkins1337** [comment]
![Untitled](https://user-images.githubusercontent.com/1679712/111565656-231c2280-8772-11eb-87ce-eafbcf1507b8.png)
It also get's eliminated wrongly sometimes.

**Comment by beheh** [comment]
I believe these should be fixed now after #4266 and #4289.
