### ISSUE TITLE
Assume secrets are "Ice Block" and show normal percentages.

### ISSUE THREAD

**Issue by Registerme1** [HearthSim/Hearthstone-Deck-Tracker#4237]
With Darkmoon prices (and Tickatus in the future) Ice Block is offered as reward, so every hero with a secret not Akazamzarak can be ignored in calculations. Even against The Great Akazamzarak it's in most cases Ice Block.

Just "ignoring" secrets and calculate percentages normally is in **EVERY WAY** - even if slightly wrong - preferable to just not having any at all.

**Comment by Skydler** [comment]
Same thing here #4228. It's silly not to show percentages.
