### ISSUE TITLE
Rigged Faire Game is being excluded wrong

### ISSUE THREAD

**Issue by OzanKurt** [HearthSim/Hearthstone-Deck-Tracker#4241]
https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/2016ea27934253f5f7ab9f14b18b018a956c3666/Hearthstone%20Deck%20Tracker/Hearthstone/Secrets/SecretsEventHandler.cs#L290

I am not familiar with the code but changing the to the current player might solve the issue. I believe it is checking if "I" as the player took any damage in the previous turn.

**Comment by qndel** [comment]
yes! I noticed it doesn't work properly as well :) +1

**Comment by riQQ** [comment]
Duplicate of #4235
