### ISSUE TITLE
le tracker ne se met pas a jour au vu de l'avancement de la partie

### ISSUE THREAD

**Issue by RYKORY** [HearthSim/Hearthstone-Deck-Tracker#4246]
comme indiquer dans le titre mon tracker ne se met pas a jour au vu de l'avancement de la partie 
mes victoires/défaites ne sont plus mise a jour etc j'aimerai solutionner ce problème au plus vite.
j'ai déjà relancer mon jeu ainsi que mon tracker a multiples reprises mais rien n'y fait.
Cordialement.

**Comment by beheh** [comment]
Fixed in  v1.14.0
