### ISSUE TITLE
Ranked Spells remain as their rank 1 version on your deck list after you draw them after 5 mana

### ISSUE THREAD

**Issue by rainerpour** [HearthSim/Hearthstone-Deck-Tracker#4252]
### Expected Behavior
Upgraded ranked spell should remove the rank1 spell from your deck list after you draw it. (or show the actual rank of the card as it upgrades)

### Actual Behavior
Ranked spell remains as the rank 1 spell in your deck list and shows that you drew/played a higher rank version

### Steps to reproduce behavior
Draw a ranked spell after 5 mana (this is where it upgrades)

### Log/Screenshots
It happened with demon hunter ranked spell for me. i did not test for other ones.

**Comment by azeier** [comment]
Fixed with v1.14.8
