### ISSUE TITLE
(Golden?) Lord Jaraxxus is not correctly marked as drawn

### ISSUE THREAD

**Issue by alterNERDtive** [HearthSim/Hearthstone-Deck-Tracker#4255]
### Expected Behavior
When you draw Lord Jaraxxus, he’s marked/indicated as drawn in your deck list.

### Actual Behavior
He’s marked as in your hand (green text) but not marked as no longer in your deck (grayed out).

### Steps to reproduce behavior
1. Put Lord Jaraxxus in your deck.
2. Play.
3. Draw Lord Jaraxxus.

(Might be exclusive to the golden version, can’t test.)

### Log/Screenshots
![image](https://user-images.githubusercontent.com/53827887/113218160-5933c900-927f-11eb-973d-9522cf7edd81.png)

**Comment by azeier** [comment]
Fixed with v1.14.4
