### ISSUE TITLE
Deck Tracker when unloading the GraveyardPlugin

### ISSUE THREAD

**Issue by ezxpro** [HearthSim/Hearthstone-Deck-Tracker#4256]
## Bug report
Deckttracker has been crashing a lot around here. I just checked the logs, it seems it's due to a plugin, the Graveyard plugin, which is the only one I have installed
### Expected Behavior
Should run without ever crashing randomly.

### Actual Behavior
Crashes a lot, sometimes during a match, sometimes when left at idle (e.g when I leave the game open and go do something else or when managing the collection)

### Steps to reproduce behavior
No idea, it never crashes consistently, in a way I can know what caused it.

### Log/Screenshots
screebshot of the log showing an exception has been thrown
![image](https://user-images.githubusercontent.com/15344931/113229315-179a2280-926d-11eb-89fd-e3526ee808c2.png)

**Comment by batstyx** [comment]
I'm assuming you're using [v1.6](https://github.com/RedHatter/Graveyard/releases/tag/v1.6)? 
I've been maintaining my own copy which might fix your issue as it's generally up-to-date with the latest HDT library versions 
https://github.com/batstyx/Graveyard/releases

**Comment by beheh** [comment]
Closing as this is a plugin issue.
