### ISSUE TITLE
Issue when facing an opponent hiding their name (shows up as "Your Opponent") deck tracker doesn't work

### ISSUE THREAD

**Issue by danyhood** [HearthSim/Hearthstone-Deck-Tracker#4257]
### Expected Behavior
Deck tracker tracks mine and my opponents cards. After the game the result is saved in deck tracker and the stats are added to the decks stats.

### Actual Behavior
My deck is displayed but cards are not tracked so when cards are drawn they are not removed from the deck list. Opponents cards are not tracked at all. After the game the result shows as None, and it does not track which class the opponent played.

### Steps to reproduce behavior
This occurs every time I face an opponent who hides their name.

### Log/Screenshots
![image](https://user-images.githubusercontent.com/81769834/113329677-c2661b80-9315-11eb-86e0-bba5551d1356.png)

**Comment by danyhood** [comment]
Great seeing the rapid response to this. Thank you!

**Comment by azeier** [comment]
Fixed with v1.14.4
