### ISSUE TITLE
Secret list is not up to date in Arena mode

### ISSUE THREAD

**Issue by MRJG232** [HearthSim/Hearthstone-Deck-Tracker#4258]

**Comment by azeier** [comment]
Can you provide more information? The arena secrets are dynamic and *should* be up to date. 

What secrets do you see and expect instead?

**Comment by azeier** [comment]
Most likely fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/eb43d183d5e0434597556b5dcc728cd0d25b4943
