### ISSUE TITLE
Hearthstone Deck Tracker hangs on after startup, 20.2 Hearthstone patch

### ISSUE THREAD

**Issue by Tarasovych** [HearthSim/Hearthstone-Deck-Tracker#4283]
### Expected Behavior
Hearthstone Deck Tracker is loading correctly

### Actual Behavior
Hearthstone Deck Tracker hangs on after startup

### Steps to reproduce behavior
1. Update Hearthstone to [20.2](https://playhearthstone.com/en-us/news/23665634)
2. Run Hearthstone Deck Tracker

### Log/Screenshots
There were no .NET Runtime events.
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/6423094/hdt_log.txt)

**Comment by azeier** [comment]
A release with a fix is coming shortly!
