### ISSUE TITLE
Secret Tracker incorrectly tracks Paladin's Reckoning if the attacking minion died

### ISSUE THREAD

**Issue by owelikecheez** [HearthSim/Hearthstone-Deck-Tracker#4290]
**Bug report**
Reckoning incorrectly becomes greyed out if a minion with 3+ attack dies to another minion after its attack. Despite what the tracker shows in this instance, Reckoning is still a possible secret outcome.

 **Expected Behavior**
Reckoning stays active in the tracker when the minion with more than three attack dies to another minion.

**Actual Behavior**
Reckoning becomes greyed out when the minion with more than three attack dies to another minion.

 **Steps to reproduce behavior**
Try killing off your 3+ attack minion to an enemy minion (thus not triggering the secret) and the secret will be greyed out on the tracker.

**Comment by beheh** [comment]
Fixed in #4299.
