### ISSUE TITLE
GameEventHandler HandlePlayerPlay and HandlePlayerSecretPlayed not being called 

### ISSUE THREAD

**Issue by batstyx** [HearthSim/Hearthstone-Deck-Tracker#4310]
The [`gameState.CurrentBlock?.Parent != null`](https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/39f4f97ea2d4936e1ef1ca974b490b5b46434dcb#diff-53cd11627ced1c18f5cab99e6c89b6c48b8727985e2f8424fafb7d5e41d92347) checks introduced in [Fix secrets](https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/39f4f97ea2d4936e1ef1ca974b490b5b46434dcb) (#4299) seem to be preventing `gameState.GameHandler.HandlePlayerPlay` and apparently also `gameState.GameHandler.HandlePlayerSecretPlayed` from being called for the player the majority of the time.

As I mention in this [issue](https://github.com/RedHatter/Graveyard/issues/61) raised for [Graveyard](https://github.com/RedHatter/Graveyard), there are no `Player.Play >> [Player]` entries in my HDT logs after 13th June when this change was introduced. 

I'm mainly playing Classic with a smattering of Standard and Wild so I guess I'm not coming across the situation the code was added for?

Reverting to HDT [v1.14.16](https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/tag/v1.14.16) and using Graveyard [v1.8.11.57](https://github.com/batstyx/Graveyard/releases/tag/v1.8.11.57) produces the expected Graveyard views for Tess Greymane and Lady Liadrin.

**Comment by Jonysegal** [comment]
Hey, I'm aware of this and will fix it with a release shortly. Thanks for noting it!
