### ISSUE TITLE
Kurtrus Ashfallen final hero power possible not being accounted for in the win/lose predictions.

### ISSUE THREAD

**Issue by salamisami** [HearthSim/Hearthstone-Deck-Tracker#4320]
## Bug report
The minions summoned infight by Kurtrus Ashfallen (and being passively buffed by the hero power open the gate)  in Battlegrounds may not be properly accounted for. I've watched several HS players play the game and decktracker giving them an unfavorable percentage to win the fight. Nevertheless they still do win the fight. 
### Expected Behavior

I expect the given win percentage for a fight to be a bit higher. I suspect it doesnt account the buff for units such as rat pack or Sneeds old Shredder.
### Actual Behavior

The given percentage to win was much lower than how the fight actually went. 
### Steps to reproduce behavior

1. Go into a BG lobby with 7 friends/helper. 
2. Get the Hero Kurtrus Ashfallen. 
3. Activate his final hero power. 
4. Get a unit such as rat pack or replicating menance
5. Stage a fight that should be won in 100% of the time if you account for the buffed summoned minions. 
6. Compare the %win number given by HDT.

**Comment by salamisami** [comment]
I want to note that this isnt a "proper" bug report and more of a suspicion.

**Comment by Jonysegal** [comment]
Hi- thank you for this report! This is a tricky effect to account for that I spent a lot of time on, so I do beleive there could be an issue. Looking into our error reporting I'm not seeing a large scale pattern so I'm inclined to say that the behavior is intended and it's just difficult to eyeball boards of this complexity; that said, I'll continue to monitor the problem. If you happen to see a peculiar one happen linking the name of the streamer here with a link or a date for the vod would be a huge help.
