### ISSUE TITLE
Casual Duels deck bug

### ISSUE THREAD

**Issue by saldaselfstone** [HearthSim/Hearthstone-Deck-Tracker#4356]
In casual Duels runs, after making the deck, the program erroneously assigns a different class to it (say, Mage instead of Warrior), such that on the first Duels match, the deck is not recognized and is not counted into the stats.

Only on the second run does it properly recognize the deck, so all the stats are counted without the first match and the erroneous "deck" is left ghosting in the deck list.

This happens every time I run a casual duels run.

Edit: After running Heroic Duels, I was able to reproduce the bug there as well.

**Comment by ceceita** [comment]
same for me ,  
the different class assigned is the last class played.

if you end a run as Paladin , and start a new one as Rogue , on HDT it creates a Paladin deck with Rogue cards and HDT can't select it so changes to no-deck mode.

**Comment by ceceita** [comment]
i think is fixed by
https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/a0a4e230ef0580fef527024f54d76f97f0141d04
Thanks
