### ISSUE TITLE
Version 1.16.7 completely broke plugin Advisor

### ISSUE THREAD

**Issue by anonymous555** [HearthSim/Hearthstone-Deck-Tracker#4358]
Prior to deck tracker version 1.16.7, the Advisor plugin was working well.
After 1.16.7, the plugin no longer notices the start of games or turns.  

https://github.com/kimsey0/Advisor

**Comment by chWolfgang** [comment]
I had to turn on Settings:Game Modes: Friendly
(in HDT Options: Plugins: Advisor)
in order to get Advisor to appear in ladder games. This may help.

**Comment by anonymous555** [comment]
Fixed by the latest HSDT release
