### ISSUE TITLE
Overlay for Mercenaries abilities has abilities positions swapped in 1.16.10 update

### ISSUE THREAD

**Issue by Purexbeatdown** [HearthSim/Hearthstone-Deck-Tracker#4368]
![MercsExample](https://user-images.githubusercontent.com/46423133/144531752-514d761e-3357-4694-9ec9-1c47fa8384db.jpg)

Above image shows what I'm talking about.
A few of the Mercenaries abilities have been swapped around on the ability overlay, here is a complete list of all the abilities that are in the wrong positions. This is on the HS Deck Tracker Version 1.16.10

Protector:
Alexstrasza ability 1 and 3 are swapped
Cariel abilites are all in wrong positions
Cornelius abilites are all in wrong positions
Garrosh ability 1 and 2 are swapped
Grommash ability 2 and 3 are swapped
Gruul ability 1 and 2 are swapped
Kurtrus abilties are all in wrong positions
Jaraxxus ability 1 and 3 are swapped
Malfurion's 2nd ability needs updated artwork.
Mannoroth ability 2 and 3 are swapped
Ragnaros ability 1 and 3 are swapped
Sneed ability 1 and 3 are swapped
Varian ability 1 and 3 are swapped

Fighter:
Diablo 2nd ability needs updated artwork.
Edwin ability 2 and 3 are swapped
Illidan abilities are all in wrong positions
King Krush ability 1 and 3 are swapped
Mutanus ability 1 and 2 are swapped
Murk-eye ability 1 and 2 are swapped
Rathorian ability 1 and 3 are swapped
Saurfang ability 1 and 3 are swapped
Sylvanas ability 1 and 3 are swapped
Tirion ability 1 and 3 are swapped
Valeera ability 1 and 3 are swapped
Voone ability 2 and 3 are swapped

Caster:
Anduin ability 1 and 2 are swapped
Baron Geddon abilities are all in wrong positions
Brightwing ability 1 and 3 are swapped
Brukan ability 2 and 3 are swapped
Cookie abilities are all in wrong positions
Guff ability 2 and 3 are swapped
Jaina ability 2 and 3 are swapped
Millhouse ability 2 and 3 are swapped
Natalie Seline ability 1 and 2 are swapped
Velen abilities are all in the wrong positions
Uther ability 1 and 2 are swapped
Varden abilities are all in the wrong positions
Vol'Jin ability 2 and 3 are swapped

**Comment by azeier** [comment]
We deployed a server side fix earlier, this should be fixed once you restart HDT.

**Comment by Purexbeatdown** [comment]
> We deployed a server side fix earlier, this should be fixed once you restart HDT.

thank you :)
