### ISSUE TITLE
Recording statistics of Battlegrounds

### ISSUE THREAD

**Issue by YooWMooY** [HearthSim/Hearthstone-Deck-Tracker#4375]
It would be nice if statistics from the battlefields were saved in order to conveniently track them. Display basic statistics, for example, how much earned or how much mmr was lost on a specific hero, on which hero played the last games (for example, the last 5-10) (percentage victories on the hero (what place he took in the last few games and percentage of places)), if possible, then the table (collected stack).

**Comment by beheh** [comment]
Hey there! I think all of is supported as part of the Tier7 subscription on HSReplay.net. We're not currently planning to add further stats windows within HDT for Battlegrounds.
