### ISSUE TITLE
Unable to upload collection or replays via deck tracker

### ISSUE THREAD

**Issue by Brok3nPix3l** [HearthSim/Hearthstone-Deck-Tracker#4390]
## Bug report
As of today, it appears that I am unable to upload my collection or replays to hsreplay.net.

### Expected Behavior
Sign into the deck tracker, open the collection, and have collection updated on hsreplay.
Play a game, click on the replay in the client, and view it on hsreplay.

### Actual Behavior
Whenever I log in to the client (regardless of whether Hearthstone is running or not) I receive an error in the client (1) and can see several reported in the log (2).

### Steps to reproduce behavior
This is an ongoing issue, so I am unable to reproduce it.

### Log/Screenshots
(1) ![image](https://user-images.githubusercontent.com/19913658/163298428-91179e0c-b4db-42c6-b677-da228ab7d365.png)
(2) [hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/8485695/hdt_log.txt)

I have tried logging out of and back into Blizzard, hsreplay, and the deck tracker client, clearing all cookies from my browser (tried using Opera GX and Google Chrome), uninstalling and reinstalling the client, and renaming the old data folder to have the client regenerate entirely new data (so none of the old replays were attempting to be uploaded again).

**Comment by Brok3nPix3l** [comment]
This appears to have been a network configuration error on my end

**Comment by vivianig** [comment]
@Brok3nPix3l any chance you could share some details about what the issue was? Been having the same for a couple of months and haven't been able to figure it out,

**Comment by Brok3nPix3l** [comment]
@vivianig sorry to hear that. Unfortunately, I don't know too much about the root cause. I was living in an apartment building for school and it seemed to just start happening one day, but it wouldn't happen from any other internet connection, so when I moved out it went away. I'd say it's probably something to do with your internet config, I'm not sure if there's anything you can do to reset that and I really hope that it's nothing like an IP shadow ban. Good luck fixing it!

**Comment by vivianig** [comment]
I see, thanks for the input!
