### ISSUE TITLE
Playing "Illuminate" doesn't show the "on bottom" portion of deck tracker

### ISSUE THREAD

**Issue by rustberry** [HearthSim/Hearthstone-Deck-Tracker#4397]
### Expected Behavior
Playing "Illuminate" should bring up a small window on bottom right displaying the cards on bottom

### Actual Behavior
The "on bottom" window didn't show up

### Steps to reproduce behavior
As Priest, play the card "Illuminate"

### Log/Screenshots
![image](https://user-images.githubusercontent.com/34592958/165441979-8fd53c05-dd7e-4acf-b576-dfa37ab97d10.png)

**Comment by LofhJann** [comment]
1.17.13 update broke Dredge for me as well. Tuskarrr Trawler and Obsidiansmith neither show "on top" or "on bottom" screens
