### ISSUE TITLE
1.17.13 update reset HDT settings

### ISSUE THREAD

**Issue by LofhJann** [HearthSim/Hearthstone-Deck-Tracker#4398]
Update 1.17.13 had most of my overlay settings reset. Not sure how reproducable this issue is but below are steps I took before issue came up:

- Start HS Deck tracker (First thing after turning on PC)
- Click "Launch Hearthstone" button on HDT
- Error shown ("Took too long to launch, start B.net launcher manually")
- B.net launcher started, Hearthstone started updating
- Launch Hearthstone from B.net launcher

At this point I noticed timers missing and other overlay settings reset.

**Comment by AntonK89** [comment]
Same issue. All my settings were reset to defaults with the update. Had to restore them from the backup.
There is a file named config_corrupted.xml in the HDT settings folder. I compared it with the old one and there are no differences beside the HDT version numbers.

**Comment by Lethalmikey** [comment]
Same issue. Please tell me you have some way of reverting this reset because i did not have a backup of my settings and i had a customized setup...

**Comment by LofhJann** [comment]
Backing up and trying to rename above mentioned config_corrupted.xml while changing version number to match new version might be worth a try. Didn't test myself yet

**Comment by AntonK89** [comment]
> Same issue. Please tell me you have some way of reverting this reset because i do not have a backup of my settings and i had a really customized setup...

HDT has automatic backups. They are in the folder %appdata%\HearthstoneDeckTracker\Backups. You can extract config.xml from an older archive and place it in %appdata%\HearthstoneDeckTracker\.

**Comment by abrownhearth** [comment]
@AntonK89 @Lethalmikey @LofhJann  There was an issue in the latest version that reset some things. In order to restore Dredge support, you can go to the backup folder at %AppData%\HearthstoneDeckTracker, find the config.xml file from before the update Tuesday (released around 3:30pm EST, so the file from before that), and copy and paste that file to replace the config.xml in the main folder of HDT. We're sorry for the inconvenience and are working to see if we can fix this in an upcoming update.

**Comment by Ahrimourn** [comment]
@abrownhearth Thanks so much for this info.  I was trying to determine why tracker wasn't showing me cards at bottom, this worked perfectly.

**Comment by Ahrimourn** [comment]
FYI - it still seems somewhat broken.  The option to show bottom has stayed since I replaced the config file, but after a few games it doesn't show bottom consistently after playing from the depths.

**Comment by Ahrimourn** [comment]
This problem seems specific to From the Depths, the bottom cards are showing properly for other dredge cards.  Has anyone else reported this?

**Comment by tw1npea** [comment]
I have the same problem, I just opened a new issue about this, hope it gets fixed.
