### ISSUE TITLE
Bottom cards don't show when "from the depths" is used

### ISSUE THREAD

**Issue by tw1npea** [HearthSim/Hearthstone-Deck-Tracker#4404]
## Bug report

Hello, I am not sure if only I'm experiencing the issue mentioned in the title or no, but for me the bottom cards don't show when using "from the depths". Maybe because there are 5 of them instead of 3 for example, but this is pretty upsetting and I hope it gets fixed.

**Comment by beheh** [comment]
Fixed in 587f7fce.
