### ISSUE TITLE
Jade idol's Jade Stash generated from Jerry Rig Carpenter does not add 3 jade idols to the tracker. 

### ISSUE THREAD

**Issue by Megaiwer** [HearthSim/Hearthstone-Deck-Tracker#4413]
### Expected Behavior
After Playing Jade Stash generated from Jerry rig carpenter's effect, the counter of jade idols in the deck should update.

### Actual Behavior
Upon playing Jade stash the counter does not update properly.
### Steps to reproduce behavior
Play Jerry Rig Carpenter with Jade Idol in your deck, and play the generated jade stash.

### Log/Screenshots
![image](https://user-images.githubusercontent.com/106786798/171762588-08ab976d-03a9-4afe-9ddd-1195f26ad1ed.png)

**Comment by beheh** [comment]
Thanks for the report! This is fixed in the next HDT version.
