### ISSUE TITLE
Tier7 overlay request

### ISSUE THREAD

**Issue by solomongrundy6** [HearthSim/Hearthstone-Deck-Tracker#4441]
## Feature Request

Could you add an option to disable the Tier7 overlay image on the main Battlegrounds screen? (Before pressing play, where it tells you to sign in to get Tier7 stats in the overlay.)  I don't use that function, and it gets in the way of other windows (even the deck tracker window) if I have to do some work or change settings between games.  It also conflicts with the "Hide in menu" option being enabled, this overlay always stays visible regardless of that setting.  It also stays there if you open your Battlegrounds Track and the Full Stats, partially blocking buttons and always blocking certain parts of the stats. (I have no way of seeing my 'Top 4' stat with it up, for example.)

Thanks.

**Comment by jafferdoodles** [comment]
Yeah the feature is obnoxious and is basically screaming for you to pay them  for tier 7. Its actually so awful

**Comment by solomongrundy6** [comment]
I see this has been implemented in the newest version, so I think I can close this now.  Thanks!
