### ISSUE TITLE
Feature: Battlegrounds: Show available types instead of unavailable types.

### ISSUE THREAD

**Issue by quinnabrvau** [HearthSim/Hearthstone-Deck-Tracker#4450]
## Feature Request
Have an option to show minion types that are in the game. Now that there are the same number of minion types in the game as there are banned. It is easier to think about the minion types in the game. 

### Expectations
1. an option to turn on available minion types next to the option to show banned minion types
2. if both available and banned minion type options are turned on, clear graphics showing which row is available and which row is banned. [Ideally in the same order as in game: available over unavailable]

**Comment by beheh** [comment]
Hey there! This is included starting with Hearthstone Deck Tracker v1.25.4, and you can enable it in the settings screen:
![Hearthstone Deck Tracker Settings Screen with two settings highlighted](https://github.com/HearthSim/Hearthstone-Deck-Tracker/assets/929769/cb620ed1-24ab-4795-9f3f-886d841aad57)

Here's what it looks like in-game:
![Available Minion types in the Hearthstone Deck Tracker overlay](https://github.com/HearthSim/Hearthstone-Deck-Tracker/assets/929769/7bf29574-df3a-478a-9891-27e6ad4e6468)
