### ISSUE TITLE
Mulligan Guide and Hero Picking don't slide out properly

### ISSUE THREAD

**Issue by MillenniumDH** [HearthSim/Hearthstone-Deck-Tracker#4454]
### Expected Behavior
 "What Should I Keep?" button not being extremely shy and showing itself normally.

### Actual Behavior
 "What Should I Keep?"  button being extremely shy and hiding on the bottom right corner of the screen.

### Steps to reproduce behavior
 It doesn't happen every time, couldn't find a consistent pattern.
### Log/Screenshots
 Couldn't find the log.

![hs decktracker](https://user-images.githubusercontent.com/64160781/222884450-3a38b8a4-7a2d-413e-8a82-235fcb130515.png)

**Comment by MillenniumDH** [comment]
> 

it seems this is the issue yeah. haven't directly tested it but 95% sure this is the reason.

**Comment by andrediamant** [comment]
I have the exact same issue, didn't have this (even while alt tabbing all the time) for 4+ years of using HDT. Any thoughts?

**Comment by beheh** [comment]
This also happens during Battlegrounds hero picking.

**Comment by beheh** [comment]
This should be fixed by 243c6fa1cf7bcc5b74f99450b165f4958c638601, which will release with the next HDT version.
