### ISSUE TITLE
Mouseover card details gone?

### ISSUE THREAD

**Issue by privacyguy123** [HearthSim/Hearthstone-Deck-Tracker#4459]
### Expected Behavior

Card info on mouseover/hover deck list

### Actual Behavior

No matter what I do I can't get this option to turn back on after most recent app update :S

### Steps to reproduce behavior

Open Hearthstone Deck Tracker/Hearthstone and mouse over a card on left or right side

**Comment by lordamon** [comment]
same

**Comment by Striding** [comment]
yep, same problem

**Comment by lordamon** [comment]
now i can't even hover cards on left or right list to maginify it

**Comment by DubKriss** [comment]
Same here :(

**Comment by Sinancancengiz** [comment]
same. will they fix it?

**Comment by privacyguy123** [comment]
I got it back by restoring to a previous setting backup - something busted in the update

**Comment by DubKriss** [comment]
Recent update fixed this problem :)
