### ISSUE TITLE
Standard decks converted to Wild, even though they are 100% Standard compatible. All new Standard deck imports import to Wild as well.

### ISSUE THREAD

**Issue by vvzz68** [HearthSim/Hearthstone-Deck-Tracker#4462]
### Expected Behavior

Standard decks to remain Standard and import as Standard.

### Actual Behavior

Any previous standard deck that is 100% Standard compatible is now wild. Any new Standard deck imported, imports in as Wild.

### Steps to reproduce behavior

I can't import any new Standard decks at all. They always import as Standard from deck code or website. Also all my previous 100% Standard compatible decks got moved to Wild.

**Comment by sgkoishi** [comment]
Can you share a test deckstring?

**Comment by bitbangboom** [comment]
HDT is still using year of the hydra, should be year of the wolf

deckcode from HDT:

### divine pal
# Class: Paladin
# Format: Wild
# Year of the Hydra
#
# 2x (1) Righteous Protector
# 2x (1) Sanguine Soldier
# 2x (1) Sinful Sous Chef
# 2x (2) Argent Protector
# 1x (2) Blood Matriarch Liadrin
# 2x (2) Class Action Lawyer
# 2x (2) Disco Maul
# 2x (2) For Quel'Thalas!
# 2x (2) Hand of A'dal
# 1x (2) Kotori Lightblade
# 2x (3) Boogie Down
# 2x (3) Funkfin
# 2x (3) Seal of Blood
# 2x (4) Jitterbug
# 1x (7) The Countess
# 1x (8) Tirion Fordring
# 2x (9) Lightray
#
AAEBAZ8FBO2fBIbiBKHiBISWBQ3rnwTJoATi0wS/4gTy7QSrkwWBlgWDlgXAxAXBxAXKxAW6xwW1ngYAAA==
#
# To use this deck, copy it to your clipboard and create a new deck in Hearthstone
# Generated by HDT - https://hsreplay.net

Same deck, code from hearthstone:

### divine pal
# Class: Paladin
# Format: Standard
# Year of the Wolf
#
# 2x (1) Righteous Protector
# 2x (1) Sanguine Soldier
# 2x (1) Sinful Sous Chef
# 2x (2) Argent Protector
# 1x (2) Blood Matriarch Liadrin
# 2x (2) Class Action Lawyer
# 2x (2) Disco Maul
# 2x (2) For Quel'Thalas!
# 2x (2) Hand of A'dal
# 1x (2) Kotori Lightblade
# 2x (3) Boogie Down
# 2x (3) Funkfin
# 2x (3) Seal of Blood
# 2x (4) Jitterbug
# 1x (7) The Countess
# 1x (8) Tirion Fordring
# 2x (9) Lightray
# 
AAECAaToAgTtnwSG4gSh4gSElgUN658EyaAE4tMEv+IE8u0Eq5MFgZYFg5YFwMQFwcQFysQFuscFtZ4GAAA=
# 
# To use this deck, copy it to your clipboard and create a new deck in Hearthstone

**Comment by vvzz68** [comment]
Thanks for the quick fix!
