### ISSUE TITLE
new HS patch completely broken

### ISSUE THREAD

**Issue by privacyguy123** [HearthSim/Hearthstone-Deck-Tracker#4466]
see title

**Comment by Howardzi-nn** [comment]
tested on
 macOS 13.3.1
 HSTracker 2.4.2

<img width="251" alt="image" src="https://github.com/HearthSim/Hearthstone-Deck-Tracker/assets/42576391/9a2d1269-aa30-4802-aa36-d17c464d3e49">

App not responding

**Comment by Jessibear2115** [comment]
Windows 10
Battlegrounds overlay not showing outside of left side MMR summary.
Application hangs as soon as match starts.
App crashes when attempting to close.

**Comment by sgkoishi** [comment]
The latest patch comes with a big update that breaks things - just wait.

**Comment by Govthub** [comment]
> tested on macOS 13.3.1 HSTracker 2.4.2 HS 26.2.0.174258
> 
> <img alt="image" width="251" src="https://user-images.githubusercontent.com/42576391/237247017-9a2d1269-aa30-4802-aa36-d17c464d3e49.png">
> App not responding

Drop your WhatsApp or telegram so we can handle this , am here to help you

**Comment by SirCoitus** [comment]
latest update broke deck tracker.
deck tracker not syncing collection
also not tracking games, cards used, etc. 
all it shows is overlay of deck using with no functionality.

**Comment by Hruberen** [comment]
Also broken for me, app will freeze, go gray and unresponsive as soon as I open Hearthstone. Restarting app, hearthstone, or computer does not fix this.

**Comment by CounterTrap** [comment]
Exactly the same for me.  Uninstalled, reloaded, changed every setting = recognizes no input, can't import or create decks, or track anything at all.

**Comment by Milamber2k** [comment]
Same exact thing for me.

**Comment by douglascorrea** [comment]
Same here

**Comment by HackerJohnMD** [comment]
Are there any viable alternatives for the time being?

**Comment by pinemartin22** [comment]
Same issue for me - before the patch it would occasionally stop working, but restarting and/or restarting the computer would fix it.   But now no amount of restarting fixes it - it just hangs.

**Comment by pinemartin22** [comment]
I also looked at a different tracker - firestone - and it is displaying the attached message.   So it's a bigger issue than just for HS tracker...
![Screenshot 2023-05-10 161411](https://github.com/HearthSim/Hearthstone-Deck-Tracker/assets/133161325/01719f55-2335-4e59-a01e-41e87334599e)

**Comment by vvzz68** [comment]
> I also looked at a different tracker - firestone - and it is displaying the attached message. So it's a bigger issue than just for HS tracker... ![Screenshot 2023-05-10 161411](https://user-images.githubusercontent.com/133161325/237534098-01719f55-2335-4e59-a01e-41e87334599e.png)

Why does Blizzard do dumb things like this. I hope there is a fix in the near future. Thanks.

**Comment by YourHotExGf** [comment]
I uninstalled battlenet, HS, and HDT, then re installed, and now its working fine. Hope it works for everyone else

**Comment by DreidSpb** [comment]
> I uninstalled battlenet, HS, and HDT, then re installed, and now its working fine. Hope it works for everyone else

Don't think you had to do this — its just update of HDT (1.20.0) has been released.

**Comment by YourHotExGf** [comment]
> 

Ah when i tried just HDT nothing was working so i just did all 3 and it worked for me

**Comment by beheh** [comment]
This was resolved.
