### ISSUE TITLE
Experience counter has stopped appearing for several months

### ISSUE THREAD

**Issue by mechanicarts** [HearthSim/Hearthstone-Deck-Tracker#4469]
### Expected Behavior
Show a bar in-game, next to the gold (default location) that tracks level in rewards path, and current progress.

### Actual Behavior
Experience counter does not show.

### Steps to reproduce behavior
None known.
HSDT has been reset and reinstalled multiple times, and it's the only thing not working.

**Comment by AstroNauta21** [comment]
yep, already wrote in this post:

https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/4443

Hope this issue can be solved

**Comment by beheh** [comment]
Duplicate of #4443
