### ISSUE TITLE
Missing translation keys for uploaded collections

### ISSUE THREAD

**Issue by fdela** [HearthSim/Hearthstone-Deck-Tracker#4471]
## Bug report
There are no translatable strings for "Collection uploaded!" and "Find decks on HSReplay.net"

### Expected Behavior
They should be transatable

### Actual Behavior
They are hardcoded

### Steps to reproduce behavior
Perform any action that triggers the showing of the temporary message (shown on the bottom right of HearthStone window), like disenchanting a card and coming back to main menu

**Comment by beheh** [comment]
Hi there, thanks for the report! This has been fixed. The string should appear in Crowdin later today, and a future HDT update will pick it up and include then.
