### ISSUE TITLE
Battlegrounds Unsupported Battlecry Annihilan Battlemaster

### ISSUE THREAD

**Issue by DirtierMike** [HearthSim/Hearthstone-Deck-Tracker#4479]
### Expected Behavior
Battlegrounds Tracker to show the Win/Loss percentage

### Actual Behavior
Did not show the tracker rather showed an error message saying "Unsupported battlecry Annihilan Battlemaster"

### Steps to reproduce behavior
Play the cards "Annihilan Battlemaster" and "Rylak Metalhead" next to eachother

**Comment by beheh** [comment]
Thanks for the report! We've implemented Annihilan Battlemaster since and this message should be gone.
