### ISSUE TITLE
Plugin develop

### ISSUE THREAD

**Issue by AngelXxxX6** [HearthSim/Hearthstone-Deck-Tracker#4481]
Good time of day. I want to learn how to write plugins for HS. I have experience in C#. Is there any relevant information on this issue somewhere? Interested in at least basic information about mana and cards in hand / on the table. I tried to run this https://github.com/andburn/hdt-plugin-example/tree/master plugin example, but it doesn't work, apparently it has lost relevance. I would be grateful if someone helps in this matter)

**Comment by beheh** [comment]
Hi there, there is an updated template here you can try: https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Creating-Plugins#template
