### ISSUE TITLE
Bait and Switch is missing from Hunter secret list (Arena)

### ISSUE THREAD

**Issue by EndarkeN** [HearthSim/Hearthstone-Deck-Tracker#4483]
### Expected Behavior
A list of all possible secrets with respect to the class in the current Arena meta to display upon the opponent putting a secret into the battlefield.

### Actual Behavior
All secrets except Bait and Switch showed in the secrets list. Bait and Switch is the only new secret from TITANS, I believe.

### Steps to reproduce behavior
Play against a Hunter in Arena and wait for them to put a secret into the battlefield.

### Log/Screenshots
[hdt_log.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/12208826/hdt_log.txt)

**Comment by beheh** [comment]
Thanks for the report! This was fixed a few weeks ago in d276fcb2d1e4db08424dd4f53a71ec7432f57d13.
