### ISSUE TITLE
Bob's Buddy simulation result opens by itself when updating opponent's hand

### ISSUE THREAD

**Issue by gabrieljablonski** [HearthSim/Hearthstone-Deck-Tracker#4485]
### Expected Behavior
When the option "Show results during combat phase" is disabled, the combat simulation results should only be shown after combat is over, or when clicking the overlay.

### Actual Behavior
When the card "Free-Flying Feathermane" is summoned by opponent during combat (the new tier-3 beast), the combat simulation results overlay opens by itself. It may happen in other situations as well (maybe Bassgill?), but this is the one I've actually noticed.

### Log/Screenshots
https://github.com/HearthSim/Hearthstone-Deck-Tracker/assets/21102974/dfb759fd-7c4f-40a9-92d2-5f501b4a944b

### Additional context
Very likely something to do with changes from commit dba5c8d. Pretty sure it's [this line](https://github.com/HearthSim/Hearthstone-Deck-Tracker/blob/dba5c8d5d58634e64b28cd8cebb3cac322b156ab/Hearthstone%20Deck%20Tracker/BobsBuddy/BobsBuddyInvoker.cs#L518).

**Comment by beheh** [comment]
Thanks for the report! This has been fixed by https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/a5897612467a33fa5c26867df4306ad4c94f45ea and will go live out in an HDT release shortly.
