### ISSUE TITLE
Win ratio HS deck tracker for Mac OS

### ISSUE THREAD

**Issue by cHyNNNNN** [HearthSim/Hearthstone-Deck-Tracker#4488]
### Expected Behavior

Win ratio should be tracked for each deack and shown in UI
### Actual Behavior

Win ratio doesn´t show any change after each game.
### Steps to reproduce behavior

Activate UI to see win ratio, play a game, see it won´t show real results.

**Comment by beheh** [comment]
Hello! For HSTracker on macOS, please redirect your feature requests to https://github.com/HearthSim/HSTracker/
