### ISSUE TITLE
Bob's buddy: attach previous combats to oppenents not hero portrait

### ISSUE THREAD

**Issue by theRealThomasDavidson** [HearthSim/Hearthstone-Deck-Tracker#4492]
### Expected Behavior
in Bob's buddy, 
In battlegrounds last played should be linked to a particular opponent. 

### Actual Behavior
last played in instead linked to hero portrait.

### Steps to reproduce behavior
open the deck tracker.
enter a bg game. 
after playing an opponent, see that all opponents with that hero portrait have their last board updated to the opponent you just played. (honestly look at the 

### Log/Screenshots
https://www.twitch.tv/videos/1924981112
at 2:50

**Comment by beheh** [comment]
We did this in 80051867.
