### ISSUE TITLE
Show constructed anomaly on Twitch

### ISSUE THREAD

**Issue by samplenull** [HearthSim/Hearthstone-Deck-Tracker#4493]
With recent patch, I guess it's pretty obvious feature. I hope it's possible to implement.

**Comment by beheh** [comment]
The game always displays this in the top right corner. Our Twitch Extension even has a hover zone setup there so viewers can see it as well. Where would you expect another display of it?

**Comment by samplenull** [comment]
Any specific settings need to be adjust? A see a lot of HS streamers, and don't see this functionality.

**Comment by samplenull** [comment]
Maybe some misunderstanding, but "anomaly" is displaying at the top of log events at the left.

**Comment by samplenull** [comment]
![Screenshot 2023-09-22 at 18 54 43](https://github.com/HearthSim/Hearthstone-Deck-Tracker/assets/191599/cde322f1-e21c-491a-8f23-7454f04ae2fb)

**Comment by beheh** [comment]
Ah, this is about the constructed anomalies. I thought this was about the Battlegrounds anomalies. This question is specific to streaming though, right? That was not clear from your first message.

**Comment by beheh** [comment]
This will be in the next version of the Twitch Extension. Thanks for the report!
