### ISSUE TITLE
Secret list update for Fall of Uldar Arena meta

### ISSUE THREAD

**Issue by EndarkeN** [HearthSim/Hearthstone-Deck-Tracker#4495]
### Expected Behavior
A list of secrets in the current arena meta to show up upon the opponent introducing a secret into the battlefield.

### Actual Behavior
The list of secrets shown was only correct with respect to the previous arena meta.

### Steps to reproduce behavior
Play against the secret classes in arena.

**Comment by beheh** [comment]
We have a solution now that updates this list automatically.

**Comment by EndarkeN** [comment]
The card sets for the arena meta has changed in Showdown in the Badlands, and most of the secrets have been updated to reflect that with one exception: Snipe has been brought back through the Caverns of Time set, and it is not showing up as a possibility for Hunter secrets.

**Comment by beheh** [comment]
@EndarkeN Ah, this is a bug because the Wonders version of the secret has a different card id. A fix is pushed here and will be released in the coming days.

**Comment by beheh** [comment]
The fix for this has been released in HDT v1.23.4.
