### ISSUE TITLE
HSTracker crashed when opened on macOS 14.0

### ISSUE THREAD

**Issue by GODLiangCY** [HearthSim/Hearthstone-Deck-Tracker#4497]
## Bug report

When opening HSTracker(the newest macOS version), it gets stuck on the "Loading remote configuration" or "Loading Arena card tiers" step
<img width="367" alt="image" src="https://github.com/HearthSim/Hearthstone-Deck-Tracker/assets/73387709/cf2a861c-dc99-4a67-943c-ce68935ceba1">

### Expected Behavior

should open normally

### Actual Behavior

could not open

### Log/Screenshots

not know how to track logs on macOS, so I tried directly opening Terminal and typing "open /Applications/HSTracker.app/Contents/MacOS/HSTracker", it got

<img width="563" alt="image" src="https://github.com/HearthSim/Hearthstone-Deck-Tracker/assets/73387709/43676cb6-94c9-426b-888e-8eb6613cebb2">
 
seems like a macOS14-related bug. Hope this problem can be solved

**Comment by GODLiangCY** [comment]
I suddenly found that it can be used again today. I'm very sorry, this should be my network problem.

**Comment by pugnobellum** [comment]
I have the same issue, same loading screen. It occasionally works but mostly gets stuck. You think it was a network issue? I am on a VPN not sure if that is contributing factor,.

**Comment by GODLiangCY** [comment]
> I have the same issue, same loading screen. It occasionally works but mostly gets stuck. You think it was a network issue? I am on a VPN not sure if that is contributing factor.

Not very sure but that could be a network issue cause I'm on a VPN too
