### ISSUE TITLE
Voice chat

### ISSUE THREAD

**Issue by heitorgiacomini** [HearthSim/Hearthstone-Deck-Tracker#4512]
Could it be possible to make a voice chat?

**Comment by beheh** [comment]
Hey, thanks for your feature request! Unfortunately I don't understand how this would be related to Hearthstone Deck Tracker, when more suited tools like Teamspeak, Skype or Discord exist. With whom would you talk?

**Comment by heitorgiacomini** [comment]
@beheh To talk to enemy player. It could get the enemy name and if he has decktracker installed them an chat option is avaiable. it could be implemented with WEBRTC. The reason is cause this game lacks communication.

**Comment by sgkoishi** [comment]
The game doesn't even allow you to add your opponents as friends until the match ends, and removed the `Sorry` emote due to BM 🐱

**Comment by beheh** [comment]
This is not something we're interested in exploring at this time. Maybe a plugin is the right place to do this.
