### ISSUE TITLE
Plugin Addition to wiki

### ISSUE THREAD

**Issue by VeXHarbinger** [HearthSim/Hearthstone-Deck-Tracker#4527]
Sorry, this isn't so much a feature request as it is a request to update the plugin list.
I just didn't feel right marking it as a bug, but I just can't seem check in a branch of the wiki to generate a PR to add it in.
If I just missed a step in the process please enlighten me and I'll be happy to follow it.

I have the HTML to be appended here.  I wrote a VS Project template to make it easier for folks to jump right in.
I'd love any feedback if you feel items should be addressed differently than I implemented them.
Thanks in advance for updating the wiki.
 
The text file has the HTML
[HDTPluginTemplateText.txt](https://github.com/HearthSim/Hearthstone-Deck-Tracker/files/14016123/HDTPluginTemplateText.txt)

**Comment by VeXHarbinger** [comment]
Anyone?

**Comment by sgkoishi** [comment]
[It can be edited here but only with permission](https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Available-Plugins/_edit) :cry:

**Comment by VeXHarbinger** [comment]
Which I do not have, lol which is why I asked here so that someone who could, would

**Comment by beheh** [comment]
Added to https://github.com/HearthSim/Hearthstone-Deck-Tracker/wiki/Creating-Plugins.

**Comment by VeXHarbinger** [comment]
Thank you so much and thanks for all your hard work on the project itself
