### ISSUE TITLE
Does not show either deck list after 28.6.0

### ISSUE THREAD

**Issue by chWolfgang** [HearthSim/Hearthstone-Deck-Tracker#4529]
### Expected Behavior

To show deck lists of Player and Opponent.

### Actual Behavior

Neither deck list shows. Just the cards. However, you can mouse over them and get the pop-up. Both the header and footer show. ETC frame also shows. This appears to be a transparency issue. (Not saying it is, but it seems to be.)

### Steps to reproduce behavior

Relaunched the game and/or HDT. Tried setting Transparency to full in Options/General. Tried in Casual, Wild, and Standard. 

The issue continues.

**Comment by beheh** [comment]
Hey there, we released v1.24.2 with a fix for the likely culprit here. Could you give it a test and make sure it's fixed?

**Comment by chWolfgang** [comment]
That did fix it. TYVM!
