### ISSUE TITLE
Decklists not displayed in overlay and in client (under Linux/wine)

### ISSUE THREAD

**Issue by htam-net** [HearthSim/Hearthstone-Deck-Tracker#4530]
### Expected Behavior

Decklists are displayed in client and overlay

### Actual Behavior

Decklists are not displayed, but there _is_ a list and when the mouse is overing, the card is displayed.

### Steps to reproduce behavior

Launch the app.
I know I use it under Wine on Linux (tried several recent versions including wine-staging 9.2 and wine-ge), but it begins with version HDT version 1.42.1 (no problem before).

### Log/Screenshots

![image](https://github.com/HearthSim/Hearthstone-Deck-Tracker/assets/3779325/2afdebbc-10c1-431b-a3b2-5dbe54799b05)

**Comment by htam-net** [comment]
Hello,
My bad, I just reinstalled it completely ... and it works

**Comment by beheh** [comment]
Yeah, this was fixed in 1.42.2.
