### ISSUE TITLE
tier 7 minion list

### ISSUE THREAD

**Issue by solara322** [HearthSim/Hearthstone-Deck-Tracker#4533]
Ability to select the "always show tier 7 minions" setting

**Comment by beheh** [comment]
Hi there! We can do this, but I'd like to know more about the use case. When might you want to see Tier7 outside of the anomaly? 

We already show it automatically when you have the appropriate hero power that grants you a Tier 7 minion. Is this about the tavern spell?

**Comment by kavunisa** [comment]
I think that it would be handy in the following scenarios:
If you or anyone else has the quest for a tier 7 minion (that "Sire Denathrius" hero power grants) (this is also run as a event in battlegrounds that every player can obtain this)
If you or anyone else is "Thorim, Stormlord", so you can plan ahead of time for the possible picks.

**Comment by Drixi** [comment]
There are multiple scenarios in which I would have liked to check for tier 7 minions. I would like to request for a checkbox in the settings to always show the tier 7 badge/list.

**Comment by beheh** [comment]
We've added a setting that will be included in the next HDT version (https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/ba76e3c17b8021ff6cb77e50822e34a51f61bb06). Thanks for the request!
