### ISSUE TITLE
accessibility for screen reader

### ISSUE THREAD

**Issue by Majin-Buu611** [HearthSim/Hearthstone-Deck-Tracker#4534]
I saw a similar issue to this about three years ago, but nothing happened with this. Hearthstone has been made accessible with a screen reader. The mod can be found at "hearthstoneaccess.com". How difficult would it be to make the deck tracker accessible with a screen reader? It could be in a separate window, and display information as string. That's just an idea. It would be nice to be able to use this software like a sighted person can. Thank you.

**Comment by beheh** [comment]
Hi there! This is possible, but I think it depends on exactly what it looks like. Would you be able to write down an example of content in such a deck window?

**Comment by Majin-Buu611** [comment]
Sorry fr the late reply, I was thinking that you would simply put any
information displayed by th tracker when a game is active into strings. Fo
example, the tracker shows what cards you've played, so when the game
starts, a new window could open that the user could alt tab to, and one
section could be titled "your played cards". In that section, it could list
the cards you've played. The user could tab back and forth between
different text boxes and read the different categories of information. I
don't think that it is necessary to include the card information because
the user should know what the cards in there deck does. Thank you for
taking the time to work on ti issue.
