### ISSUE TITLE
One of the latest update broke the plugin advisor

### ISSUE THREAD

**Issue by triplimonkey** [HearthSim/Hearthstone-Deck-Tracker#4535]
### Expected Behavior

its not opening advisor, its getting this error

### Actual Behavior

System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<Hearthstone_Deck_Tracker.Hearthstone.Card> Hearthstone_Deck_Tracker.Utility.Extensions.CardListExtensions.ToSortedCardList(System.Collections.Generic.IEnumerable`1<Hearthstone_Deck_Tracker.Hearthstone.Card>)'.
   en HDT.Plugins.Advisor.Advisor.<UpdateCardList>d__21.MoveNext()
   en System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   en HDT.Plugins.Advisor.Advisor.UpdateCardList()
   en HDT.Plugins.Advisor.Advisor..ctor(AdvisorOverlay overlay)
   en HDT.Plugins.Advisor.AdvisorPlugin.<OnLoad>d__14.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by beheh** [comment]
Hi there, you'll have to talk to the plugin author about that.
