### ISSUE TITLE
Aspect Ratio is wrong

### ISSUE THREAD

**Issue by p1r473** [HearthSim/Hearthstone-Deck-Tracker#4540]
### Expected Behavior

Aspect Ratio of Opponent Deck is wrong if too many cards

### Actual Behavior

Aspect Ratio of Opponent Deck is wrong

### Steps to reproduce behavior

Increased the scaling to max 

### Log/Screenshots

![image](https://github.com/HearthSim/Hearthstone-Deck-Tracker/assets/9235633/95674951-e53c-4ecb-8216-90cfa9d9952d)
Note: I tried this and it didnt fix it even after restarting HDT
![image](https://github.com/HearthSim/Hearthstone-Deck-Tracker/assets/9235633/a764fe17-c1fb-454e-8aa2-b44bdece68bd)

**Comment by beheh** [comment]
The aspect ratio is intended to be like this when you have not enough vertical space available. While it gets silly eventually, it does actually go a long way in making more cards visible on screen.

You could try reducing the scaling again or unlocking the overlay and playing around with the deck list to make more vertical space available.

**Comment by p1r473** [comment]
@beheh but I definitely do have extra vertical space available above and below the opponent's deck, as seen by the empty black space

**Comment by p1r473** [comment]
@beheh but I definitely do have extra vertical space available above and below the opponent's deck, as seen by the empty black space

**Comment by p1r473** [comment]
@beheh but I definitely do have extra vertical space available above and below the opponent's deck, as seen by the empty black space
