### ISSUE TITLE
Battlegrounds Minion Browser list is not showing tooltips

### ISSUE THREAD

**Issue by CramerBH** [HearthSim/Hearthstone-Deck-Tracker#4546]
### Expected Behavior

Normally when one hovers their cursor over a minion or spell in the list to the right of the screen, a popup tooltip of the entire card appears.

### Actual Behavior

So far only the Demon (and not even all of them) tribe still seems to have this functionality, but it also shows up two times, once as the proper opacity as the rest of the overlay is set to, and another at 100% normal opacity slightly offset and sometimes overlapping the previous tooltip popup). All other tribes in previous game (Murlocs, Elementals, Beasts, Undead, Spells, and All) did not have this function at all. 

### Steps to reproduce behavior

Normal settings for HSReplay Ive always had. I havent changed anything that would cause this.

### Log/Screenshots

![HSReplayoverlay-nothingelse-tooltippopup](https://github.com/HearthSim/Hearthstone-Deck-Tracker/assets/132217856/601d0717-4473-4ede-a98e-7d69fd20ef70)
nothing else yields any type of popup at all. Nothing. 

![HSReplayoverlay-demonsonly-tooltippopup](https://github.com/HearthSim/Hearthstone-Deck-Tracker/assets/132217856/babe8906-7b9e-4826-86cb-dc4482aefefd)
And Demons Only and only some of them, but notice the double popup of the same minion

**Comment by CramerBH** [comment]
Im unaware of a way to add battlegrounds label to the original posting. I cant seem to find any way of doing so.

**Comment by beheh** [comment]
@CramerBH could you try running Hearthstone in windowed mode to see if that changes anything? The demos part seems like a red herring as there is no difference between the tribes.

**Comment by OzanKurt** [comment]
I have the same problem but with all the cards.

**Comment by CramerBH** [comment]
I no longer encounter this issue, i just logged in for the first time in a long time unrelated to this issue or even hearthstone lol. thanks for the replies tho and the effort.

**Comment by beheh** [comment]
Great, thanks for reporting back!
