### ISSUE TITLE
Secrets tab not updated

### ISSUE THREAD

**Issue by EndarkeN** [HearthSim/Hearthstone-Deck-Tracker#4553]
### Expected Behavior

In Constructed and Arena, the Secret tab should show Bargain Bin as a possibility if an enemy Hunter secret is in play.

### Actual Behavior

Bargain Bin is not listed as if Dr. Boom's Incredible Inventions has not released.

Also for Arena, please update the Paladin and Rogue secrets lists to show those from Ashes of Outland and onwards, since that is the limit for the generation pool.

### Steps to reproduce behavior

Wait until the opponent plays some secrets.

**Comment by beheh** [comment]
Fixed in 86438128a6e9bd370166eb292a10727a3d9f98cd (releasing today or tomorrow).
