### ISSUE TITLE
Add tourist as a known card

### ISSUE THREAD

**Issue by anonymous555** [HearthSim/Hearthstone-Deck-Tracker#4564]
When the opponent's tourist card is shown on the side as a notification, show it as a known card in their deck.

**Comment by homorunner** [comment]
Is this feature working on by anyone? Otherwise I would like to try to implement it.

**Comment by beheh** [comment]
@homorunner Hey, thanks for the initiative! There's a dev actually building it right now, so this should be fixed very soon. But maybe there's something else you can find :-)

**Comment by beheh** [comment]
Fixed in dba23b4865ee62f6415aabb460c26b0220c3788a.
