### ISSUE TITLE
Wrong version of 'Scavenger's Ingenuity' in deck tracker.

### ISSUE THREAD

**Issue by GodAdriel** [HearthSim/Hearthstone-Deck-Tracker#4565]
### Expected Behavior

Card in game currently reads "Draw a Beast. Give it +3/+3.", so the deck tracker version should reflect that.

### Actual Behavior

The deck tracker shows that the card gives +2/+2, when it actually gives +3/+3.

### Steps to reproduce behavior

it's always present in the newest version of the tracker. 

### Log/Screenshots

https://gyazo.com/a55d42d9499c115c11bc736a14f94e8b

**Comment by beheh** [comment]
This has been fixed, thanks for the report!
