### ISSUE TITLE
Probability / frequency of a tribe appearing throughout match in BGs

### ISSUE THREAD

**Issue by CramerBH** [HearthSim/Hearthstone-Deck-Tracker#4567]
It would be pretty rad if the tracker kept note after each tavern refresh of the number of times and frequency a tribe is appearing in the tavern, so as the more refreshes of it occur the more data it collects to give an idea to the user what the lobby is statistically offering you. 

Example: Minions offered in the tavern refreshes

1. Turn one: 2 murloc 1 mech
2. Turn two: 1 beast 1 murloc 1 neutral
3. Turn three: 1 Demon, 2 Undead, 1Murloc, refreshed: 2 demon, 2 murloc

At this point the tavern has shown us 6 murloc, 1 mech, 1 beast, 1 neutral, 3 demon, and 2 undead, The maths of this could be displayed  as a probability or as statistical avarage of all the previous refreshes and whenever you hover over any minions of a tribe it has data on, you;d see a tooltip with that value appear over them. So like murloc account for 6 out of 14 of the minions offered so far in the tavern, a tooltip of something like 42% would appear over any Murlocs you hovered over. 

The point of this is to point the user into adapting to the minions being offered more reliably than to waste turn after turn unable to locate the key minion they are hoping to find. I've gone many a game picking a tribe and no one else in the lobby picked that tribe and still being unable to find the key minions for that tribe as Im offered so much of a different set or sets of tribes over and over again.

This would be a progressive function that would take its data points after each refresh. I wouldn't mind if it didnt take into account other effects such as hero powers that change a singular minion in the tavern to a tier higher one at random, but the spells that change the entire tavern to a tier higher should be included as its a complete refresh of the tavern still.

**Comment by CramerBH** [comment]
This would be immensly useful now given the new version of BGs. For instance when trying to go murlocs if the game could tell me im encountering murlocs at about a less than 10% frequency I can pivot to something more reliably being offered.

**Comment by beheh** [comment]
Hey there, thanks for your suggestion!

I've had a chat with a few others, and we think you already get most of this benefit by hovering over the sidebar to see what tribe people are in. That'll also update much faster as people sell minions, especially in the first half of the game.
If you want to really test shop sampling you could write a plugin to test this out - we'll happily add it to the Available Plugins page at that time.

Again, thanks for your suggestion! I will close this issue for now in an attempt to keep the issue tracker clean, but feel free to comment further.

**Comment by CramerBH** [comment]
I dont understand how hovering over what the other players are using does what Im talking about. We know there is a known number of each minion of each tier in each tribe offered in the pool. It isnt like there is a variable weight to one tribe in a match compared to another (like there's never 3x as many murlocs as there are any other tribe) but you suggest that if I see 3 other players going murloc that is the case? No, what I'm suggesting is a simple survey of the player's tavern refreshes, and gives a percentage of each tribe thus far in every refresh as the game progresses. so if I encountered a quillboar in almost every refresh all game long it would have the one of the highest percentages to show thus far that game. So if a player is being starved of their build's minions because lets say, 3 or more other players are also that tribe... then the highest percentage thus far would be the smart pivot at that point in the game.

**Comment by beheh** [comment]
I think I understood your suggested approach, I merely proposed the "hover the leaderboard" technique as a low-tech way of seeing which tribes are locked up.

The problem we see with sampling is that the pool is *massive*. Once you're even just in tier 3 there's a total pool of ~600 cards, and later in the game it's 1000 cards or more. Refreshing 10 times in one turn (or even across a few turns) is not going to tell you reliably that 20 cards from one tribe are locked up somewhere, especially because the pool you're drawing is constantly changing, as players sell or buy or discover cards, or pivot themselves - so your earlier measurements will very quickly become outdated and misleading.

Overall we're just not convinced it's worth pursuing this in HDT for now, especially as we have many other things we want to work.  However, this is a perfect opportunity to write a plugin or find somebody to collaborate with on it.

Again, thanks for the suggestion!

**Comment by CramerBH** [comment]
I dont think you got what I was trying to convey as the hovering over
another user just tells me what that user's primary tribe might be. What I
mean is to have an ongoing ratio of what YOU specifically have been offered
in the tavern tribe wise. Its one thing to be playing as say Jaraxxus and
obviously should be going Demons but if you've gotten to say turn 6 and
have only been offered demons less than 3% of all your tavern options thus
far, it might benefit someone to be able to see that stark disparity as
compared to maybe you have thus far been offered quillboar over 60% of all
tavern options thus far... basically a way of taking off the tunnel vision
blinders that many dont realize they even have on because no one would
willingly pick a hero with a tribe specific ability and progress thru the
game ignoring that tribe but if the ongoing ratios can point out this the
player then a pivot can entirely be possible instead of the usual "the game
denies me any demons when Im jaraxxxus" games that so may tribe specific
heroes fall victim to. Im not even remotely worried about how many of a
minion is in the pool or sold back or owned by others etc. Im just focused
on "what has the tavern said my options have been, and statistically, which
tribe was most prevalent? Without writing it down each turn and each
refresh and then doing a whole lot of maths its impossible for a normal
person to be able to "know" what the game is telling me to go with instead
of any normal plans one enters into BGs with such as going demons if you
picked jaraxxxus. again, not even as complicated as what you detailed as
being too complex and so on with other players comps and all that. just
literally the running tally of how many times a named tribe was an option
in the tavern for me. and being able to decide if a planned strat is viable
or not and also if a pivot is needed and what is the most logical pivot
based on what the game has been offering so far.

**Comment by CramerBH** [comment]
You still are not getting what Ive suggested AT ALL. I am only concerned with what HAS been presented TO ME so far, nothing to do with total pools of cards or what is being used by others. This suggestion would have nothing to do with anyone else's boards at all but the singular user and what the tavern has been offering them. Hovering over the other players doesnt tell anything as far as if the tavern has been favoring one tribe as a majority or multiple tribes evenly over the tavern refreshes FOR ME AND ME ONLY. Nothing to do with the total number of each minion in each tier or anything like that. just for example:

round one: tavern yields 2 pirates and 1 neutral       So far the ratio would show up as just 100% Pirates so far for me
round two: tavern yields 1 demon, 1 beast, 1 neutral  So far now the ratio shifts to 50% Pirates, 25% Demons, 25% Beasts, so far for me
round three: tavern yields 1 pirate, 1 beast, 2 neutrals So far the ratio shifts again and now 50% Pirates, 33% Beast, 12% Demons have been whats been offered to me so far. 

and so on. 

Very simple, very informative, very helpful data the player could use to help figure out "what the tavern wants the player to play" vs the normal "pick a tribe and hope you dont get screwed by RNG."

Has nothing to do with the total number of cards in a tier, or anything other players have going on, nor anything to do with card pools, just a very straightforward "What has the game been giving me so far this game?" data that isnt something a player can just "know" without writing it all down each turn and doing the maths to find the majority tribe as once the refresh button is pressed, any idea of what was offered prior is 100% gone and cannot be simply remembered without photographic memory along with intense head maths to arrive at the same useful info I'm proposing.
