### ISSUE TITLE
My Last Games are not Logged

### ISSUE THREAD

**Issue by Galaxonx** [HearthSim/Hearthstone-Deck-Tracker#4576]
### Expected Behavior

Its been a while. I enabled show latest games in Battlegrounds. After every session it has to be showing the latest 8 games with placement a ranked points. But it doesn't! I played duo mode. In solo mode it worked. So what is the reason? Maby anyone know?

Fg 
![B hi jzfs](https://github.com/user-attachments/assets/296d59b8-a5df-45dc-bc4b-041eeb3694dc)
![B hi jzfs SV](https://github.com/user-attachments/assets/d5c11c7b-170f-4957-ae53-a1cf4e64e67d)

### Actual Behavior

My Last Games are not Logged

### Log/Screenshots

[hdt_log.txt](https://github.com/user-attachments/files/17160204/hdt_log.txt)

**Comment by beheh** [comment]
Hey there, thanks for the report! This is a duplicate of #4566.
