### ISSUE TITLE
unable save config after upgrade to 1.36.1

### ISSUE THREAD

**Issue by Camork** [HearthSim/Hearthstone-Deck-Tracker#4590]
### Expected Behavior

change language should work as expected.

### Actual Behavior

after the restart, everything was reset

**Comment by mikualpha** [comment]
> Same bug. It seems that the `config.xml` was automatically overwritten when the program started.

In `1.36.2`, it can save lang config but don't work anyway.

**Comment by beheh** [comment]
Hey all! If this is still happening to you, can you please send us hdt_log.txt files? Ideally:
- a first log file before it's reset, after you've closed it
- a second log file after you're opend it again and the settings are lost
That way we can investigate this further.

**Comment by mikualpha** [comment]
> Hey all! If this is still happening to you, can you please send us hdt_log.txt files? Ideally:
> 
> * a first log file before it's reset, after you've closed it
> * a second log file after you're opend it again and the settings are lost
>   That way we can investigate this further.

It can save config successfully now in `1.36.2` (config bug is in `1.36.1`).  Only all language configs have been reset but just need to reconfigure it.
