### ISSUE TITLE
macos 15.01 不能使用

### ISSUE THREAD

**Issue by debby97cheer** [HearthSim/Hearthstone-Deck-Tracker#4595]
### Expected Behavior

启动了软件不显示记牌器

### Actual Behavior

启动了软件不显示记牌器

**Comment by beheh** [comment]
Hello, for macOS issues please open a report in [HearthSim/HSTracker](https://github.com/HearthSim/HSTracker/). Unfortunately I wasn't able to translate your report into English, so maybe you could translate it or write a bit more? Thanks!
