### ISSUE TITLE
DeepBattler Reaches EU Top 0.1% Player Level with Custom HDT Plugin I Developed

### ISSUE THREAD

**Issue by william-Dic** [HearthSim/Hearthstone-Deck-Tracker#4600]
Hi HDT team,

First, thank you for creating such an amazing tool with HDT—it’s been incredibly helpful and inspiring for my work!

I’ve built a plugin for HDT that extracts all useful entities into a JSON file and connects it to GPT-o1. The AI has now reached a top 0.1% player level and serves as a coach to assist human players.

I’d love to discuss how this project could contribute to HDT or the Hearthstone community. Here’s a YouTube demo if you’re interested: https://youtu.be/A9XKPx1COfc si=J8bGnYMwPdmeNbQG

Thanks again for your work on HDT, and I’m looking forward to hearing your thoughts!

**Comment by beheh** [comment]
Hey there, could you please reach out to `andrew.wilson` on Discord? Due to the holidays it may be a few days, but just reference this report and he'll know what's this is about.
