### ISSUE TITLE
UI Translation

### ISSUE THREAD

**Issue by azeier** [HearthSim/Hearthstone-Deck-Tracker#471]
~~Thanks to @Cuiyansong, all the basics for this are done!
I will be adding the remaining fields to the resx files within the next few days, after that the only thing left is finding people willing to translate!~~
**Will be added eventually, NO ETA**

* deDE: @Epix37
* enGB: neccesary at all?
* enUS: **default**
* esES: 
* esMX:
* frFR: @waibcam 
* itIT: @Elitesparkle 
* koKR: @ideocl4st 
* plPL: @Paradowski 
* ptBR: 
* ruRU: @disshishkov
* zhCN: @Cuiyansong 
* zHTW:

* Dutch: @astie85

@waibcam, @disshishkov: you guys still up for this? :)

**Comment by chucklu** [comment]
I can use LocBaml to create "Hearthstone Deck Tracker.resources.dll",however i find there still have some English info like this:
In this file :Hearthstone-Deck-Tracker\Hearthstone Deck Tracker\MainWindow\MainWindow_Load.cs
			if(_updatedLogConfig)
			{
				this.ShowMessage("Restart Hearthstone",
				                 "This is either your first time starting the tracker or the log.config file has been updated. Please restart Heartstone once, for the tracker to work properly.");
			}
LocBaml can just translate the info on in xaml file.

**Comment by chucklu** [comment]
if (Config.Instance.SelectedLanguage.Equals("zhCN"))
            {
                CultureInfo ci = new CultureInfo("zh-CN");
                Thread.CurrentThread.CurrentCulture = ci;
                Thread.CurrentThread.CurrentUICulture = ci;
            }
when i set the ui culture,it's wierd.
So,if you can change the language string form zhCN to zh-CN

**Comment by Paradowski** [comment]
As I wrote in #818 , I can help with translating to Polish (plPL) ;)

**Comment by ideocl4st** [comment]
I can help with Korean. How do I start?

**Comment by Epix37** [comment]
You can't yet, the software-side of things is not done yet (or has been worked on for a while, tbh).

This is on my list for 1.0 though, so I will let you know eventually :).

**Comment by mariocosme** [comment]
I can help translating to ptPT (Portugal) which ptBR (Brazil) players should understand completely.

**Comment by eliasmpw** [comment]
I could help with the esMX (latin american spanish) translation.

**Comment by eggling** [comment]
guys i can help with the spanish translation, sing me in! lets do this! :+1:

**Comment by Drui7** [comment]
@Epix37 please, see my answer here: 
https://github.com/Epix37/Hearthstone-Deck-Tracker/issues/2325#issuecomment-207593546

**Comment by azeier** [comment]
Closing in favor of #2797
