### ISSUE TITLE
Idea: Multi-level tree view in ReplayViewer

### ISSUE THREAD

**Issue by BVA64** [HearthSim/Hearthstone-Deck-Tracker#532]
What if under each turn in the tree on the left we would have on the first level only actions directly done by the player (play a card, attack, etc.). The events triggered by this action would be a the sub-elements of this node (death of a minion, drawing of cards, etc.). If the effects have consequences of their own they would also get a further sub-tree.

I'm not sure if we have enough information in the log to do this though.

**Comment by Epix37** [comment]
That's a good idea. 

Currently I'm only reading `TAG_CHANGE` messages regardless of them being nested or not. However if `ACTION_START` is considered this should be easily possible for the most part.

Sample:
`ACTION_START Entity=[name=Undertaker ...] SubType=ATTACK Index=-1 Target=[name=Rexxar ...]`
`----ACTION_START Entity=[name=Freezing Trap ...] SubType=TRIGGER Index=0 Target=0`
`--------TAG_CHANGE Entity=[name=Undertaker ...] tag=ZONE value=HAND`
`----ACTION_END` 
`ACTION_END`

Deaths are handled in a seperate ("toplevel") action after `SubType=ATTACK ` but merging those should be possible.
`ACTION_START Entity=GameEntity SubType=DEATHS Index=0 Target=0` 
`----TAG_CHANGE Entity=[name=Undertaker ...] tag=ZONE value=GRAVEYARD`
`ACTION_END`

This could also solve the heropower problem (#529). Probably requires some restructuring of the replays.

**Comment by judge2020** [comment]
the in-hdt replay viewer has been removed
