### ISSUE TITLE
Rag attacks are not shown in Replay

### ISSUE THREAD

**Issue by BVA64** [HearthSim/Hearthstone-Deck-Tracker#541]
https://www.mediafire.com/?xf2107dyzt1bzcz

At the end of Turn 24 my Rag killed the opponents Baine Bloodhoof. In the replay only the death was shown without the cause. 

This is a bit confusing because it is unclear from what can be seen what caused the death.

**Comment by Epix37** [comment]
Same goes for e.g. knife juggler. The problem is that, from what I could tell, the log only contains a trigger followed by the damage taken. No real indication of an attack or an attacker/defender.

**Comment by culinko** [comment]
I think this should be sufficient now:

D 11:01:18.5333863 PowerTaskList.DebugPrintPower() - ACTION_START Entity=[name=Knife Juggler id=21 zone=PLAY zonePos=5 cardId=NEW1_019 player=1] BlockType=TRIGGER Index=0 Target=0
D 11:01:18.5333863 PowerTaskList.DebugPrintPower() -     META_DATA - Meta=TARGET Data=0 Info=1
D 11:01:18.5333863 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[name=Silverback Patriarch id=65 zone=PLAY zonePos=1 cardId=CS2_127 player=2] tag=PREDAMAGE value=1
D 11:01:18.5333863 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[name=Silverback Patriarch id=65 zone=PLAY zonePos=1 cardId=CS2_127 player=2] tag=PREDAMAGE value=0
D 11:01:18.5333863 PowerTaskList.DebugPrintPower() -     META_DATA - Meta=DAMAGE Data=1 Info=1
D 11:01:18.5333863 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[name=Silverback Patriarch id=65 zone=PLAY zonePos=1 cardId=CS2_127 player=2] tag=LAST_AFFECTED_BY value=21
D 11:01:18.5333863 PowerTaskList.DebugPrintPower() -     TAG_CHANGE Entity=[name=Silverback Patriarch id=65 zone=PLAY zonePos=1 cardId=CS2_127 player=2] tag=DAMAGE value=1
D 11:01:18.5333863 PowerTaskList.DebugPrintPower() - ACTION_END

**Comment by judge2020** [comment]
the in-hdt replay viewer has been removed
