### ISSUE TITLE
Cards given to the opponent by Lorewalker Cho are shown as unknown in Replay

### ISSUE THREAD

**Issue by BVA64** [HearthSim/Hearthstone-Deck-Tracker#542]
https://www.mediafire.com/?xf2107dyzt1bzcz

Turn 26: I played 3 spells while Cho was on the field. All 3 are shown as unknown in the opponents hand.

**Comment by judge2020** [comment]
No longer does this in HSReplay

and the in-hdt replay viewer has been removed
