### ISSUE TITLE
Save User Information Using Cloud Storage Providers

### ISSUE THREAD

**Issue by mkrain** [HearthSim/Hearthstone-Deck-Tracker#579]
I have HDT on my Surface, Win8 PC and Yoga Tablet 2 8.  It's easy enough to create a linked directory to my OneDrive account so I can store information or set each up identically using the Import from Arena/Web functionality.  However, this is rather tedious and error prone.  It would be nice to be able to add cloud integration so I can store all of my information in once place, be it OneDrive, Google Drive, dropbox, etc.  There are plenty of SDK's for .NET that simplify this process so I don't forsee this being difficult but I do understand that other issues/features take precedence.  Fingers crossed, though.

**Comment by Epix37** [comment]
I think especially with the addition of #571 (ability to set the data directory) it should be easy enough to do this manually if desired. 

I will leave this open though, in case someone feels like implementing this (maybe even me at some point).

**Comment by Epix37** [comment]
#629 !

**Comment by riQQ** [comment]
As HearthStats is dead, this is now tracked in #3235.
