### ISSUE TITLE
Crazy idea for an advanced new feature: a meta tracker

### ISSUE THREAD

**Issue by MyopicCat** [HearthSim/Hearthstone-Deck-Tracker#625]
I've had this idea in the back of my head since the first version of the tracker. It's really complex, basically an entire new application in itself. I thought I'd finally throw it out there. Even if Epix37 thinks this is out of the question for his tracker, maybe someone else will run with the idea.

The idea: if your user base is large enough, you could implement a meta tracker.

Currently everybody has a very rough idea of what the meta is like based on their last 20 or so games. The problem is that the meta can shift quickly, and if you see a change you never know if it's a meta shift or just RNG in your matchups. But if you aggregate data from lots of users, you can get an accurate picture of the meta at any rank, potentially in real time.

So, the deck tracker could call home to a server and report your opponent's rank and class. Your data is shared anonymously and voluntarily. The server sends back the aggregated picture of the meta around your rank, as gathered during the past hour/day/week. You could encourage players to share their data if only active data sharers get access to the meta info.

This all requires that the rank of your opponent is stored in the log files. Is it? I have no idea.

Also, a feature like this could cross the line for what Blizzard accepts in a helper application. It may be a good idea to check with them before starting to implement something like this.

**Comment by Epix37** [comment]
Well the data part is taken care of :) #629

**Comment by BenReierson** [comment]
This is a great idea. A real-time meta tracker could open up a whole new level of deck tweaking.

**Comment by judge2020** [comment]
I recommend you open an issue at https://github.com/HearthSim/HSReplay.net, HearthStats is no longer supported by HDT.

**Comment by riQQ** [comment]
This is implemented in HSReplay.
