### ISSUE TITLE
Suggestion: Replay viewer display suggestions

### ISSUE THREAD

**Issue by GiggliG** [HearthSim/Hearthstone-Deck-Tracker#635]
In the replay viewer, the left frame shows each event as it occurred. I'd like to be able to resize this frame within the window. My screen is big enough to view each event on a single line, rather than breaking it up over two rows.

I also suggest having each even row be shaded softly, so that it's easy to see at a glance the different events, rather than looking at a large mass of whitespace.

Finally the numbering of the turns through me off at first. I suggest rather than Turn 1, Turn 2, etc., you list it as Player Turn 1, Opponent Turn 1, Player Turn 2, Opponent Turn 2, etc. as appropriate.

**Comment by azeier** [comment]
Local replay support has now been fully removed.
