### ISSUE TITLE
Hearthstats Sync Date Issue

### ISSUE THREAD

**Issue by GiggliG** [HearthSim/Hearthstone-Deck-Tracker#685]
When doing the first sync of HDT decks and games to hearthstone, the date and time assigned to each game is the time of upload, not the date the game was actually played. I have stats going back 6-7 months, so this is a little concerning.
Will it be possible to update game history with their correct dates and times, for new accounts?

**Comment by Epix37** [comment]
Is that just the time displayed on the website? iirc I pass the start time of matches and it did return that time when syncing decks back. If so, the correct dates are already there, just not used. Should be easy to fix in that case.

**Comment by GiggliG** [comment]
When you look at your stats on hearthstats, you can filter by Hearthstone Season, and there's also a graph of your win rate over time on your dashboard. It's clear from these that all my game history (going back to last July or August) was given the same date, Feb 12th, and almost the same time, which is the time of upload.
If this is just a display issue, and is fixable, great, but for now it does seem like hearthstats is using the upload time as the game played time. I understand how this might happen, because the hearthstats uploader is used in real time. So it might be a limitation on hearthstats end.

**Comment by judge2020** [comment]
HearthStats is no longer supported by HDT, a new synchronization system is planned for HSReplay.
