### ISSUE TITLE
Feature Suggestion: select active deck

### ISSUE THREAD

**Issue by GiggliG** [HearthSim/Hearthstone-Deck-Tracker#690]
When I'm looking at the stats screen, and looking down the old games I've played, I'd sometimes like to view the deck I played that game with.

Suggestion: when you select a game in the Stats --> Overall --> Games list, the deck that game was played with becomes selected in HDT.

**Comment by Elitesparkle** [comment]
> Suggestion: when you select a game in the Stats --> Overall --> Games list, the deck that game was played with becomes selected in HDT.

I think adding a button to load the deck in the main window will be a good idea.

**Comment by GiggliG** [comment]
That would work, but I think it's smoother if it happens automatically. You can always go back to the deck you were in first by clicking a game you played with that deck.

A supplementary suggestion: have the hovertext when you hover over a deck game show the name of the deck used.

**Comment by Elitesparkle** [comment]
Sometimes I need to open a different deck while playing. The same is true
for the stats.

Selecting another deck shouldn't change the one on the overlay
automatically. There should be a button to load it manually.

If you make it change automatically when looking at the stats as well, we
couldn't select a game record while playing to avoid loading another deck
on the overlay.

You could just say it isn't needed to do those things while playing but I
think it's a good improvement.

> That would work, but I think it's smoother if it happens automatically.
You can always go back to the deck you were in first by clicking a game you
played with that deck.
>
> A supplementary suggestion: have the hovertext when you hover over a deck
game show the name of the deck used.

**Comment by GiggliG** [comment]
That's a different suggestion. I wasn't talking about while playing, but while browsing your game history.
I agree, when in game, it would be nice to change decks in HDT without it affecting the overlay.
I'm not sure how best that would be to implement. When HDT doesn't detect a deck correctly, you have to select it manually to get it displayed in the overlay.

**Comment by Elitesparkle** [comment]
I know it's different but it's related to it.

> That's a different suggestion. I wasn't talking about while playing, but
while browsing your game history.
> I agree, when in game, it would be nice to change decks in HDT without it
affecting the overlay.
> I'm not sure how best that would be to implement. When HDT doesn't detect
a deck correctly, you have to select it manually to get it displayed in the
overlay.

**Comment by GiggliG** [comment]
Is this enhancement likely to be added?
