### ISSUE TITLE
Suggestion: new filters

### ISSUE THREAD

**Issue by Elitesparkle** [HearthSim/Hearthstone-Deck-Tracker#692]
Since we have new fields for each game records, it would be useful to add some new filters.

Suggestions:
- Rank: select a range to show games played at those ranks (e.g. from Rank 5 to 1);
- Opponent Name: insert the opponent name, or part of it, to look for the games played against him (e.g. opponent name containing the string "ad"; starting with "Ch" and similar);
- Turns: select a range to show games that lasted that amount of turns (e.g. from 10 to 20 turns; up to 10 turns; at least 5 turns);
- Coin: choose to show games with Coin or without it;
- Time: select a range to show games that lasted that amount of time (e.g. from 10 to 15 minutes; up to 7 minutes; at least 5 minutes);
- Started (see #573): select a range to show games played in that period (e.g. from 12 February 2015 15:00 to 13 February 15:00).

**Comment by dvide** [comment]
I like the filter by range of ranks idea. It'd be nice to see the win percentages of a deck within certain brackets of opponent's rank.

**Comment by Elitesparkle** [comment]
Actually I decided to open this issue just for that, then I added the rest.

> I like the filter by range of ranks idea. It'd be nice to see the win
percentages of a deck within certain brackets of opponent's rank.

**Comment by GiggliG** [comment]
Excellent suggestions.

**Comment by Cu8eR** [comment]
Really nice idea, I dont think that all filters mentioned above would be added but some of them are really useful

**Comment by culinko** [comment]
Another suggestion: Filter stats by region (#1107).

**Comment by MechaLynx** [comment]
Is region even recorded or present in the logs?

**Comment by culinko** [comment]
Region tag is saved to each game in DeckStats.xml.

**Comment by MechaLynx** [comment]
Then I guess the only obstacle is overcoming the sheer terror of refactoring the internal indexing and the UI to accommodate this kind of search.

**Comment by Epix37** [comment]
The easiest is probably to just throw the whole control away and re-do it.

**Comment by MechaLynx** [comment]
.NET already has an sql-like query syntax for lists or something doesn't it? Perhaps if the properties of games are all collected into a single massive monolithic object or list (or have an interface that pretends they are) and there's some search ui like the ["Additional Filters"](http://www.hearthpwn.com/decks) on hearthpwn (and other sites) to allow for composite searches. 

In an ideal world, one would read all the games into an sqlite in-memory database and use proper sql mapped to a dynamic ui like the aforementioned one to create composite queries. A bit overkill, but definitely a once-and-for-all solution.

**Comment by chucklu** [comment]
I hope the tracker can support region filter

**Comment by culinko** [comment]
Filter by number of season: #1485.

**Comment by culinko** [comment]
More date-related filters: expansion/adventure timeframes. E.g. fiter stats since Naxx/GvG/TGT or "since Naxx until Brm", etc.

**Comment by zedor** [comment]
I saw that for quite some time the stats module is named '[OLD] Games & statistics'. I'm wondering if this is still being worked on or am I missing the [NEW] version :)

**Comment by Epix37** [comment]
I *did* start working on it recently: https://github.com/Epix37/Hearthstone-Deck-Tracker/tree/constructed-stats

Some time Q2 2016 is probably a reasonable guess.

**Comment by Epix37** [comment]
Anything I missed?
![filters](https://cloud.githubusercontent.com/assets/7737910/14706933/fa0c710e-07c1-11e6-86fb-c1012aebc57b.PNG)

**Comment by GiggliG** [comment]
Date ranges?

Does the time box include the same date picking options as on the arena stats: pikcing custom allows you to select a start and an end date?

Also, the Mode: what I'd love is a multi-select option here, so you could filter on Ranked + Casual, or exclude Brawl + Innkeeper, say.

**Comment by Epix37** [comment]
Yes it's the same time filter as arena has. Plus I added "last season" for both.

I'll look into multi select. That would probably make sense for `(O.) Class` and `Region` too.

I was also thinking about adding regex support for the `Opponent Name` and `Note` fields. That would essentially allow multi select there as well.

**Comment by culinko** [comment]
My only request is to have ranked seasons selectable somewhere in the Time dropdown. So you could choose a custom season number (1-x, we are currently in 25th season). First ranked season started in April 2014.

**Comment by Epix37** [comment]
The current and last season have separate dropdown items, you can access all the other one via the 'custom' filter (i.e. setting a start and end date). Chances are you are not looking at past ones often enough to justify the UI clutter.

**Comment by culinko** [comment]
On the contrary, I am looking at my past seasons very often. To see how much I played in the past, how good was my deck against a certain class (e.g. how Rogue did against Paladin before and how it does now - my winrate dropped over time). Also when was the best meta for Control Warrior, Freeze Mage, etc. Using the start and end date takes too much time currently. The seasons filter is actually one of the most important filters for me and I would like it to be included now, because I doubt there will be any new filters anytime soon.

**Comment by Epix37** [comment]
Added "custom season" to time filter, which allows to set a season range. E.g. 22-24 or 25-25 (current only)..

**Comment by Epix37** [comment]
pre-release: https://github.com/HearthSim/Hearthstone-Deck-Tracker/releases/tag/v0.14.3

**Comment by Epix37** [comment]
Added with v0.14.4.
