### ISSUE TITLE
Time Zone?

### ISSUE THREAD

**Issue by FenrisWolffe** [HearthSim/Hearthstone-Deck-Tracker#707]
While still trying to figure out my missing games, I noticed 3-5 tracked in the future...... O.o

I live in Central Time, USA. Is there someplace to edit this that I am missing?

Thanks In Advance.

**Comment by Epix37** [comment]
Uh.. It should just use whatever time your pc is set to. That might explain missing games though. iirc, the upper bound in time filters for stats is the 11:59pm of the current day.

**Comment by FenrisWolffe** [comment]
Nope. It’d madness. The time is often off, another chunk of games missing today.
Question. If I play 5 games as version 1.2, change the deck, and resave as 1.2, do those games stay or get wiped?

**Comment by Epix37** [comment]
Please check if the games show up later. They might just not be displayed "yet". 

Stats should stay when saving the deck as current.

**Comment by FenrisWolffe** [comment]
They have not shown up. I think what happens is, if you change a deck (example: version 1.1) and save it as the same version, it erases the OLD version 1.1 and any games associated with it.


So, maybe I found you a very interesting bug, if you can replicate it.

**Comment by culinko** [comment]
Does this still happen?
