### ISSUE TITLE
Sync issue between 2 computers : updates are not sent to the second computer

### ISSUE THREAD

**Issue by jeantend** [HearthSim/Hearthstone-Deck-Tracker#709]
1. I have a deck sync on 2 computers using hearthstats
2. on computer 1 : I update the name / the version / some cards
3. the modifications are updates on the hearthstats site
4. on computer 2 the version has changed, but the cards and deck name modifications are never sync (tried normal and full sync)

Let me know if you need more informations
Regards,

**Comment by judge2020** [comment]
HearthStats is no longer supported by HDT, a new synchronization system is planned for HSReplay.
