### ISSUE TITLE
Importing opponent deck list includes obtained cards

### ISSUE THREAD

**Issue by hetoord** [HearthSim/Hearthstone-Deck-Tracker#718]
I'm currently using the "import opp. deck" feature to retroactively label the deck my opponent was using. This work great, except cards they obtain during the game are also included in this deck list. This includes cards obtained through Duplicate, Echo of Medivh, Thoughsteal and Unstable Portal and Webspinner.

**Comment by Epix37** [comment]
Fixed with https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/608fd115b3e80e02943d8560c0cbf11ee2cff803.

For new matches only. Can't fix this for existing ones.
