### ISSUE TITLE
Images showing improperly in deck view

### ISSUE THREAD

**Issue by zeron851** [HearthSim/Hearthstone-Deck-Tracker#757]
While editing or making a deck, or even just viewing, if you scroll, often the cards will look like in the image unless you remove/add something in the deck. Of which it goes back to normal for a short time. This happens with almost all of my decks after the update.

![capture](https://cloud.githubusercontent.com/assets/11362275/6540872/e4b820e6-c483-11e4-9a85-027bd1258dff.PNG)

I don't know what causes this, but it's ridiculously annoying.

**Comment by Epix37** [comment]
That is probably issue #268. That was fixed in the main window with v0.7.0 however and has been working flawlessly for me ever since. Is this an issue for anyone else?

My biggest problem is that I never understood why the "fix" there worked in the first place. So this might be a though one to fix. I'm going to try having the images as embedded resources. Maybe that helps?

**Comment by mvordeme** [comment]
This seems to be occurring in more places than just the old game detail dialog, of late, see #1115. Since this is already marked "bug", I closed the new one.

![deckbuilder](https://cloud.githubusercontent.com/assets/12465335/8330916/1dded9da-1a85-11e5-9e99-a049616bba90.png)

**Comment by culinko** [comment]
So this also happens in old replay viewer (#830)  show opp. deck (#898) and in the Collection Tracker plugin (very often here). Just linking all here since this seems to be the main ticket for it.

**Comment by culinko** [comment]
Collection Tracker plugin with the new dark theme displays this bug like this. Using 0.13.19.: 

![collection-bug](https://cloud.githubusercontent.com/assets/11700272/14156263/c9ce6932-f6c5-11e5-9cc3-5d19eb4bdc19.png)

**Comment by Omen724** [comment]
Deleting the config file in the appdata folder and launching HDT has fixed this issue for me at the moment.

**Comment by riQQ** [comment]
I moved my `%APPDATA%\HearthstoneDeckTracker` folder to use HDT with default settings. The bug still persists.
