### ISSUE TITLE
Post-game note popup box loses focus

### ISSUE THREAD

**Issue by MyopicCat** [HearthSim/Hearthstone-Deck-Tracker#835]
Just a reminder from #833.

**Comment by Epix37** [comment]
Perfect, thanks. 

Also: 

Hearthstone windowed / fullscreen? 
Note dialog popup after game or when back in menu?

**Comment by MyopicCat** [comment]
Fullscreen, back in menu.

**Comment by Epix37** [comment]
Hm... I can't reproduce it.

Note dialog stays focused for me.

**Comment by MyopicCat** [comment]
Things seem to have changed since BRM. Previously when I returned to HS menu after a game I was thrown back to the desktop, the note dialog popped up on top temporarily, and about a second later its focus got stolen by the main tracker window. I had to rummage around to find the dialog, enter the note, and alt-tab back to HS. (Often HS got stuck minimized, and neither alt-tabbing or using the taskbar could maximize it again. Only way to get it back was using the task manager to maximize hearthstone.exe.)

Now when a game ends the note dialog pops up on top of HS itself (in fullscreen mode). I enter the note and continue playing without seeing the desktop. Perfect behavior IMO. With BRM there were some changes related to fullscreen mode, so maybe everything is fixed now.
http://www.reddit.com/r/hearthstone/comments/30yehq/rejoice_fullscreen_is_fixed/
http://www.reddit.com/r/hearthstone/comments/317if2/dual_monitor_issue_fixed/
http://www.reddit.com/r/hearthstone/comments/3127mh/windowed_fullscreen_works_again/

I've only played a few games so I'm not sure everything is OK yet. Could you keep this issue open a few more days?

**Comment by Epix37** [comment]
Oh they finally fixed fullscreen mode? Awesome. 

This sounds good :).

**Comment by Elitesparkle** [comment]
I think that when the note dialog popups, it doesn't have focus.
I have to click on it every time to be able to write.

**Comment by MyopicCat** [comment]
Just want to bump this up again. I think the issue was temporarily fixed by one of Blizzard's patches, but some time between the above comments in early April and early June the focus problem came back. Just like Elitesparkle says, the box has no focus when it pops up. I've reproduced this on three different computers with various versions of Windows (7, 8 and 8.1).

**Comment by MyopicCat** [comment]
Clarification (which may explain the "can't reproduce" tag): the popup window appears to lack focus, but when you hit any key it activates. So it seems to have some kind of latent focus. But this means that the first keystroke you make to write your note gets eaten, which gets annoying fast,

**Comment by culinko** [comment]
I couldn't reproduce this (windowed mode), the first letter was entered correctly.
