### ISSUE TITLE
Ctrl + Enter to save deck?

### ISSUE THREAD

**Issue by dantedog** [HearthSim/Hearthstone-Deck-Tracker#881]
After editing a deck, if you are in the name screen ctrl + enter to save it? I don't know if that makes sense to anyone else, but it seems natural to me.

**Comment by Epix37** [comment]
I would consider ctrl-s a lot more "natural" but I think we can do this, yea :).

**Comment by dantedog** [comment]
Control-s sounds like it should work 'globally' when the edit page is open. That actually makes a lot more sense.

**Comment by Epix37** [comment]
Saving via `Enter` from the name textbox makes sense too actually (no need for ctrl here imo). I'll try to implement both of those.
