### ISSUE TITLE
Show opp. deck includes obtained and stolen cards

### ISSUE THREAD

**Issue by culinko** [HearthSim/Hearthstone-Deck-Tracker#890]
If you click on the "show opp. deck" button, it also lists obtained cards (from Unstable Portal, Webspinner, Duplicate, Echo of Medivh) and stolen cards (Secrets stolen with Kezan Mystic, maybe more stolen cards, not tested). Currently is shows only class or neutral cards, it doesn't show cards from other classes anymore (it used to, as can be seen in my screenshot below).

**Comment by Epix37** [comment]
Those cards *should* be removed usually. Apparently they are not (always)? Huh..

**Comment by culinko** [comment]
Do you want me to paste the log? I still have the tracker open.

**Comment by Epix37** [comment]
The log, the replay of that game (%AppData%/HearthstoneDeckTracker/Replays) and a screenshot of the displayed cards would probably help, yea!

**Comment by culinko** [comment]
Log: http://pastebin.com/raw.php?i=nbdrabY3
Replay (match starts approx 20:20): http://kopasite.net/up/f4v08gf66a7276i/culinko(Paladin)%20vs%20Gammoth(Mage)%202028-110415.hdtreplay

The example card in this match is grove tender: 
![grove-tender](https://cloud.githubusercontent.com/assets/11700272/7102802/67877786-e08d-11e4-9e52-58b12bcc88b1.png)

**Comment by Epix37** [comment]
Perfect, thanks. I'll have a look tomorrow.

**Comment by culinko** [comment]
Also, related to #718.

**Comment by culinko** [comment]
So, I reviewed some of my replays against Tempo Mages lately and it seems that other class cards (Shielded Minibot or Axe Flinger) are no longer included in the list, but neutral cards (Target Dummy, Oasis Snapjaw) are. I believe mage cards are also included, but I don't have enough samplesize to see confirm that. Spare parts are not in the list, but things from Duplicate and Echo of Medivh are. Not sure about other "out of the deck" cards. Example screenshot (echo+duplicate):
![echo](https://cloud.githubusercontent.com/assets/11700272/9275065/cfa2b730-429a-11e5-8fff-8d0c6ba102e3.png)
