### ISSUE TITLE
RFE: Import stats from HearthstoneTracker client (HearthstoneTracker.com)

### ISSUE THREAD

**Issue by TehJumpingJawa** [HearthSim/Hearthstone-Deck-Tracker#894]
1) Hearthstone-Deck-Tracker's stats recording now does pretty much everything the HearthstoneTracker client does, and more importantly it's a lot more reliable. (and I also find the interface more intuitive)

2) HearthstoneTracker appears to have been abandoned; it hasn't been updated since BRM & consequently doesn't track games properly anymore. Also the website is partially broken.

The only thing stopping me from completely migrating to Hearhtstone-Deck-Tracker is the huge loss of historic stats data.
A means of easily importing these stats into Hearthstone-Deck-Tracker would be awesome!

**Comment by andburn** [comment]
@TehJumpingJawa If you are still interested in this I might have a solution. HearthstoneTracker has a [companion](https://github.com/HearthstoneTracker/ExcelAddIn) add-in for Excel, it can be downloaded [here](https://github.com/HearthstoneTracker/ExcelAddIn/releases). It allows you to get your stats into CSV format.

If you could use this and give me a sample of the CSV output, I could make an importer for HDT.

**Comment by riQQ** [comment]
There's a plugin by andburn, that supports importing csv: https://github.com/andburn/hdt-plugin-statsconverter.

**Comment by jleclanche** [comment]
That's gonna have to be good enough :)
