### ISSUE TITLE
Request: Ability to see deck history without editing the deck

### ISSUE THREAD

**Issue by culinko** [HearthSim/Hearthstone-Deck-Tracker#904]
Hi :) It would be cool if you could see the deck history panel all the time, not just when editing the deck. Or perhaps there could be an option for that. Many times I just want to see what I changed between versions by clicking on the decks, but currently you need to edit them to see the panel. It would be awesome, thanks :)

**Comment by GiggliG** [comment]
I'd like this too.

**Comment by culinko** [comment]
@Epix37 Was this added with b001aba?

**Comment by Epix37** [comment]
No it wasn't and there's more involved than just moving the button.

**Comment by riQQ** [comment]
An independent version history flyout was added with c661d09b.
