### ISSUE TITLE
Add options to auto-archive or delete decks tagged as "arena" after 3 losses and/or 12 wins

### ISSUE THREAD

**Issue by NightKev** [HearthSim/Hearthstone-Deck-Tracker#909]
Separate options for each possibility would be nice.

**Comment by mkrain** [comment]
I like this, currently I'm doing this manually.

**Comment by jimrrchen** [comment]
+1 on this. This can just be an option that user can toggle on/off

**Comment by Epix37** [comment]
Implemented with #2575.
