### ISSUE TITLE
Arena importing not working

### ISSUE THREAD

**Issue by xitaah** [HearthSim/Hearthstone-Deck-Tracker#943]
Hi.

For the last two patches this function haven't been working for me.
Since last patch I've had to wait until the very first game had begun, before I was able to import my card.
Now I just keep getting the tooltip when I try to import my arena deck (but still it works when I'm IN the first game)

I'm wondering if it's only on my behalf, since I can't find anyone else in here with the same problem?

Kind regards

Mads

**Comment by Epix37** [comment]
Maybe asset unloading works differntly on some machines. Instead of just going back to the main menu, try clicking the "play" button and import.

You may also have to leave and reenter the arena once before starting the importing process (going back to the main menu and clicking import).

**Comment by xitaah** [comment]
I've tried both of your suggestions. Both times I only get the guide to "how to import arena". I can only import when I'm in the first game :(

**Comment by Epix37** [comment]
Very weird, but I guess if it works that way...

**Comment by culinko** [comment]
Is this still an issue with the newest version?

**Comment by culinko** [comment]
Should be fixed with 0.15.
