### ISSUE TITLE
Games not being recorded in Casual when opponent quits

### ISSUE THREAD

**Issue by Jademalo** [HearthSim/Hearthstone-Deck-Tracker#989]
I've been playing some games against a friend, and the last one never seems to record. What seems to happen is if he quits before I've gone from the victory screen to the deck delect screen, the game flat out doesn't record.

**Comment by Epix37** [comment]
* Casual or friend?
* What did you do after he quit? Go back to the menu or quit right away as well?

**Comment by Jademalo** [comment]
vs a friend.

The match ended, and he immediately quit to the main menu. After he quit, the text box of "x has left the challenge" or whatever it was appeared on top of the victory/loss banner. I then clicked cancel I think, it booted me to the main menu, and the game wasn't recorded. I think the same happened if I clicked in the background, but I'm not sure.

**Comment by Epix37** [comment]
Okay, thanks for the info. I will have a look at this.

For the mean time: you can manually add games via `STATS > DECK > GAMES > ADD NEW GAME`, should this happen again.

**Comment by Jademalo** [comment]
Thanks, I've done that. I've also salvaged and backed up the hearthstone log file.

Is there any way to manually add a replay to that game, or convert a log to a replay?

**Comment by Epix37** [comment]
Oh, perfect! Could you upload (http://pastebin.com/) and post it here?

No way to generate a replay from that, sorry.

**Comment by Jademalo** [comment]
http://pastebin.com/PjuaT7w4

There you go. And damn, it was a really good game =p

Thanks!

**Comment by culinko** [comment]
Is this still an issue with the newest version?

**Comment by culinko** [comment]
Couldn't reproduce in 0.15.6.
